= Use Flow Designer to Configure Veeva Vault Connector - Mule 4

Anypoint Design Center's Flow Designer enables you to create apps visually. For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour].

To create an app in Flow Designer:

* Configure the input source (trigger) for your app.
* Add the connector as a component to process the input for the app.

For information about Flow Designer field values, see the xref:veevavault-connector-reference.adoc[Veeva Vault Connector Reference].


== Configure the Input Source Trigger

. In Design Center, click *Create*.
. Click *Create new application* to open Flow Designer.
. Specify a value for *Project name* and click *Create*.
. Click *Go straight to canvas* to exit from *Let's get started*.
. Click the trigger card.
. If you are using the HTTP Listener operation as a trigger, search for and select *HTTP Listener*.
. In the HTTP Listener’s *General* tab, enter the *Path* that defines the resource location. +
The path is the relative path from the path set in the HTTP Listener configuration.
. Click the *X* in the upper-right corner of the card to close the trigger card.

Flow Designer automatically saves all changes.

== Configure the Target Component

The target component enables your app to process data received from the trigger. Veeva Vault Connector provides operations that help you integrate Veeva Vault with third-party applications and services. For example, this integration enables you to create Vault connectivity and retrieve picklists data from the Vault, which can then be further integrated or processed.

. Click *+* next to the trigger card.
. In *Select a component*, search for Veeva Vault Connector.
. Select the connector name.
. Search for and select an operation for the connector, such as *Get Picklists*.
. In the *General* tab, enter a configuration name. +
. Click *Add Connection* and enter a name for the connection.
. In *Connection Type*, Select *1-Basic Authentication*.
. In the *General* tab, complete the following required fields:
+
[%header%autowidth.spread]
|===
|*Field* |*Description*
|*Name* |Enter a name for this configuration to reference it later.
|*Vault URL* |Enter the Veeva Vault instance URL.
|*Username* |Enter the Veeva Vault instance username.
|*Password* |Enter the password that corresponds to the username.
|*Version* |Enter the Veeva Vault API version, for example: `v19.1`.
|*Client Id* a|Enter the client ID to send with each request in the header for tracking purposes, in the format: `\{organisation}-{company\|team}`. +
The client ID is prefixed with "mulesoft" and has a suffix with "client-vaultconnector" internally, for example: `mulesoft-abcpharma-clinicalprod-client-vaultconnector`.
|===
+
. In the *Advanced* tab, select *Burst API Limit Profile* and *Daily API Limit Profile* for the connection.
. Click *Test* to test the connection.
. Click *Save*.

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
