= Mailchimp Marketing Connector - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Mailchimp Marketing (Mailchimp Marketing Connector) enables you to integrate your applications and the Mailchimp Marketing data and functionality. This connector exposes operations provided by the Mailchimp Marketing API.

For information about compatibility and fixed issues, refer to the Mailchimp Marketing Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Mailchimp Marketing Connector’s API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Mailchimp Marketing target resource
* Anypoint Platform
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Some common use cases for Mailchimp Marketing Connector include:

*

== Connection Types

Mailchimp Marketing connections use the following authentication types:



== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:mailchimp-marketing-connector-reference.adoc[Mailchimp Marketing Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
