= Validation Module 2.0 - Mule 4
:page-aliases: connectors::validation/validation-connector.adoc



The Validation module verifies that the content of a message in a Mule flow matches specific criteria. If a message does not meet the defined validation criteria, the validation fails and returns a validation error, such as `VALIDATION:INVALID_URL`, which is a `ValidationException`. Based on the specific data you are validating, you can customize the exception message that is displayed in the logs.

== Prerequisites

To use this module, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have access to Anypoint Platform and Anypoint Studio.

== Next Step

After you complete the prerequisites and try the examples, you are ready to create your own app and configure the connector using xref:validation-studio-config.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
