= Upgrading Validation Module to Version 2.0 - Mule 4

Upgrade Validation module to version 2.x.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|1.4.x |2.0.1
|===

== Changes in This Release

The following operation names changed:

[%header%autowidth.spread]
|===
|Previous Operation Name | New Operation Name

| *Is not blacklisted ip* | *Is not denied ip*
| XML `is-not-blacklisted-ip` | XML `is-not-denied-ip`
| *Is whitelisted ip* | *Is allowed ip*
| XML `is-whitelisted-ip` | XML `is-allowed-ip`
|===

The following parameters names changed:

[%header%autowidth.spread]
|===
|Previous Parameter Name | New Parameter Name

| *Black list* | *Deny list*
| XML `blackList` | XML `denyList`
| *White list* | *Allow list*
| XML `whiteList` | XML `allowList`
|===

[[changed_operations]]
== Changed Operations


=== Is Not Denied Ip

`<validation:is-not-denied-ip>`

Validates that an IP address is not present in the IP list.

=== Is Allowed Ip

`<validation:is-allowed-ip>`

Validates that an IP address is present in the IP list.


== Upgrade Prerequisites

Before you perform the upgrade, you must:

* Create a backup of your files, data, and configurations in case you need to restore to them.

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In *Mule Palette*, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `validation module` in the search field.
. In *Available modules*, select *Validation module* and click *Add*.
. Click *Finish*.
. Verify that the `mule-validation-module` dependency version is `2.0.1` in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.


== Post-Upgrade Steps

After you install the latest version of the connector, and if you have Mule apps that use the previous operations and parameters, manually change them to the new operations and parameters:

 . In Studio, drag the new operation to your flow.
 . Configure the new operation with the same settings as the previous operation.
 . Remove the previous operation.

You can also update the Mule app XML configuration file to the new names and parameters:

 . In Studio, navigate to the *Configuration XML* window.
 . Update the previous operations and parameters names with the new names.


=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.


=== Revert the Upgrade

If it is necessary to revert to the previous version of Validation module, change the `mule-validation-module` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:index.adoc[Validation Module Overview]
* xref:validation-documentation.adoc[Validation Module Reference]
