= SAP Connector 5.2 - Mule 4
:page-aliases: connectors::sap/sap-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Premium]

Anypoint Connector for SAP (SAP Connector) enables the integration of data to and from external systems based on SAP NetWeaver.

SAP Connector is not available in the Design Center feature of Anypoint Platform.

This connector requires a separate license. Contact MuleSoft to evaluate or use this connector in production.

Mule runtime engine (Mule) supports SAP integration through Anypoint Connector for SAP, an SAP-certified Java connector that leverages the SAP Java Connector (JCo) libraries. SAP JCo facilitates communication between an SAP backend system and a Java application. It allows Java programs to connect to SAP systems and invoke Remote Function Modules. It also allows parsing of IDocs (SAP Intermediate Documents), among other object types. The SAP configuration supports both inbound and outbound communications.

The SAP JCo libraries enable Mule apps to:

* Execute BAPI functions over the following types of remote function call (RFC) protocols:
** Synchronous RFC (sRFC)
** Asynchronous RFC (aRFC)
* Act as a JCo server to call as a Business Application Programming Interface (BAPI) over sRFC and aRFC
* Send IDocs over transactional RFC (tRFC) and queued RFC (qRFC)
* Receive IDocs over tRFC and qRFC
* Transform SAP objects (JCo function for BAPI and IDocs) to and from XML

See xref:sap-connector-terminology.adoc[SAP Terminology] to understand SAP acronyms and terminology.

For compatibility information and fixed issues, see the SAP Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The SAP business context and, in particular, the SAP R/3 Business Suite
* The SAP NetWeaver Platform from an administration point of view
* The ABAP language
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule aapp using Anypoint Studio (Studio)

Before creating and app, you must have:

* An SAP ID to download the required SAP libraries
* Access to the SAP target resource
* Access to Anypoint Platform
* SAP login credentials to test your connection to your target resource
* Use of the RFC protocol to connect to NetWeaver Application Servers (NWAS) +
http://www.cipherbsc.com/solutions/sap-erp-central-component-erp-ecc/[ECC] and https://help.sap.com/viewer/p/SAP_CUSTOMER_RELATIONSHIP_MANAGEMENT[CRM] run on top of NWAS, as other SAP solutions do, so any customer using the connector can access those systems.

== Common Use Cases for the Connector

Some of the common use cases for SAP Connector include:

* Send an IDoc to SAP
* Triggering an incoming IDoc request

For examples of these use cases, see xref:sap-connector-examples.adoc[SAP Connector Examples].

== Audience

* New user +
Configure your Mule app in
xref:sap-connector-studio.adoc[Anypoint Studio]. The xref:sap-connector-config-topics.adoc[Additional Configuration Information] topic helps you extend your understanding of the SAP Connector.
* Advanced user +
Read the xref:sap-connector-xml-maven.adoc[XML and Maven Support],
xref:sap-connector-config-topics.adoc[Additional Configuration Information],
and xref:sap-connector-examples.adoc[Examples] topics.

== Authentication Types

SAP Connector connections use the following authentication types:

* Certificate +
Uses X.509 certificate authentication 
* Simple connection provider +
Uses the username and password to authenticate

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates and examples
to simplify your use of the SAP connector. Templates provide a starting point
that enables you to add additional functionality. Examples provide a complete solution.

* *General:* https://www.mulesoft.com/exchange/org.mule.templates/template-apiled-system-account-sap/[Account System API - SAP Implementation Template],
https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sfdc.wday.sap.db-account-broadcast/[Salesforce to Salesforce, Workday, SAP, and Database Account Broadcast]

* *Salesforce and SAP:* https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-account-aggregation/[Account Aggregation],
https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-customer-bidirectional-sync/[Account Customer Bidirectional Sync],
https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-opportunity-aggregation/[Opportunity Aggregation], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-product-aggregation/[Product Aggregation], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-product-bidirectional-sync/[Product Bidirectional Sync]

* *Salesforce to SAP:* https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-account-broadcast/[Account Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-account-migration/[Account Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-opportunity-broadcast/[Opportunity Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-opportunity-migration/[Opportunity Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-product-broadcast/[Product Broadcast]

* *SAP to Salesforce:* https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-contact-broadcast/[Contact Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-contact-migration/[Contact Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-customer-broadcast/[Customer Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-customer-migration/[Customer Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-product-broadcast/[Product Material Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-material-migration/[Product Material Migration]

* *SAP to Workday:* https://www.mulesoft.com/exchange/org.mule.templates/template-sap2wday-employee-migration/[Employee Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2wday-organization-broadcast/[Organization Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2wday-organization-migration/[Organization Migration]

* *Workday and SAP:*
https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sap-organization-aggregation/[Organization Aggregation], https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sap-worker-aggregation/[Worker (Employee) Aggregation]

* *Workday to SAP:* https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sap-worker2employee-migration/[Worker (Employee) Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sap-worker-broadcast/[Worker Broadcast]

== Next

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app with
xref:sap-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:release-notes::connector/sap-connector-release-notes-mule-4.adoc[SAP Connector Release Notes]
* https://help.mulesoft.com[MuleSoft Help Center]
