= Upgrading and Migrating Slack Connector to Version 2.x  

Upgrade Anypoint Connector for Slack (Slack Connector) to version 2.x.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|1.0 |2.x
|===

== Changes in This Release

This release contains the following changes:

* This connector no longer has the *Upload File* operation because the Slack `files.upload` API method is deprecated. For more information, refer to the https://docs.slack.dev/reference/methods/files.upload/[Slack API documentation].

* To upload files, this connector now includes the new *Get upload url* and *Complete Upload External* operations. 
+
For more information about the operations, refer to xref:slack-connector-reference.adoc#GetFilesUploadUrl[Get Upload URL] and xref:slack-connector-reference.adoc#CreateFilesCompleteuploadExternal[Complete Upload External]. 
+
For examples about how to use these operations, refer to xref:slack-connector-examples.adoc#upload-file-to-channel[Upload a File to a Slack Channel (Using File Path)] and xref:slack-connector-examples.adoc#upload-file-text-content-to-channel[Upload File Text Content to a Slack Channel].

* In the Slack Connector configuration window, the *TLS* tab is renamed to the *Security* tab.

== Upgrade Prerequisites

Before you perform the upgrade, create a backup of your files, data, and configurations in case you need to restore to them.

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In *Mule Palette*, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `slack` in the search field.
. In *Available modules*, select *Slack* and click *Add*.
. Click *Finish*.
. Verify that the Slack Connector dependency version is 2.x in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

=== Verify the Upgrade

After you install the latest version of the connector, verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

=== Reverting the Upgrade

If it is necessary to revert to the previous version of Slack Connector, change the mule-slack dependency version in the project’s `pom.xml` file to the previous version.

You must update the project’s `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.salesforce.com[Salesforce Help]
