= Database Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

// Add transition

To configure a connector in Anypoint Studio:

. Install the connector.
. Configure the connector.
. Configure an input source for the connector.

== Install the Connector

. In Anypoint Studio, click the Anypoint Exchange icon in the Studio task bar.
. In Anypoint Exchange, click *Login* and supply your Anypoint Platform username and password.
. Search for the Database connector, click the card for the connector, and click *Add to project*.
. Follow the prompts.

== Configure the Connector

// Put Global Elements Properties info here

== Configure an Input Source

Configure an input source for the connector such as a connector operation,
using *HTTP Listener*, or *Scheduler*.

You can put the following operations for the connector in the *Source* area
of the Studio canvas.

// List of operations that can be an input source (from Design Center)

////
== Next

Now that you have completed configuring Studio,
see the xref:db/database-connector-config-topics.adoc[Additional Configuration Information] topic
for more configuration ideas.
////

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
