= Google Sheets Connector 1.1 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Google Sheets (Google Sheets Connector) synchronizes data and automates business processes between Google Sheets and third-party applications, either on-premises or in the cloud.

Google Sheets is a real-time spreadsheet tool with powerful functions to help teams efficiently perform multiple functions such as helping sales teams collaborate on leads and opportunities, and helping HR teams collaborate on candidates for interviewing and hiring.

For compatibility information and fixed issues, see the Google Sheets Connector release notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Google Sheets API and the Google Drive API (if planning to use the List Drive Files operation)
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have access to:

* The Google Sheets API target resource
* Anypoint Studio version 4.2.1 or later

== Common Use Case for the Connector

Common use cases for the connector include the following:

* Improve sales operations
+
Automate a workflow in which a Google Sheets spreadsheet is auto-populated every time a new lead is created in Salesforce. This sales team can then use the spreadsheet to collaborate on further research.
+
* Enhance customer service
+
Catalog all incoming issues in a spreadsheet and set up automatic rules to alert the team when an issue starts approaching SLA deadlines.
+
* Optimize HR processes
+
When a new candidate reaches out via an applicant tracking system such as Workday or Greenhouse, capture the candidate details in a spreadsheet so that other stakeholders can review and contact the appropriate candidates.

== Next Step

After you complete the prerequisites, you are ready to create your own app and configure the connector using xref:google-sheets-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
