= Upgrade Salesforce Einstein Analytics Connector to Version 4.0
:page-aliases: connectors::salesforce/salesforce-analytics-connector-upgrade.adoc

Use this guide to upgrade Salesforce Einstein Analytics Connector from version 3.x to version 4.0.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
| From Version | To Version
| 3.x | 4.0
|===

== Prerequisites

Before upgrading, ensure that your Mule runtime version is 4.6.0 or later. Connector 4.0 requires Mule 4.6.0 as the minimum runtime version. If you're using an earlier runtime version, continue using the 3.x major until you can upgrade your runtime.

== Changes in This Release

* Added OAuth 2.0 Client Credentials Flow as a new authentication method, which is the recommended approach for automated, server-to-server integrations that don't require user interaction.

For more information about how to upgrade, see xref:salesforce-analytics-connector-upgrade.adoc[].

== Upgrade Steps

. In your Mule project's `pom.xml` file, change the connector version to `4.0.x`:
+
[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-sfdc-analytics-connector</artifactId>
  <version>4.0.x</version>
  <classifier>mule-plugin</classifier>
</dependency>
----
+
Replace `4.0.x` with the specific version you're installing.

. Verify that your Mule runtime version is 4.6.0 or later.

. If you used the Username Password connection type, note that it remains supported for Salesforce API v64.0 and earlier versions only. Review your connection configuration and consider migrating to a supported OAuth connection type.

. Test your application with the new connector version to confirm it works as expected.

== See Also

* xref:index.adoc[Salesforce Einstein Analytics Cloud Connector Overview]
* xref:salesforce-analytics-connector-reference.adoc[Salesforce Einstein Analytics Connector Reference]
* xref:release-notes::connector/salesforce-analytics-connector-release-notes-mule-4.adoc[Salesforce Einstein Analytics Connector Release Notes]
