= Upgrading and Migrating Salesforce Einstein Analytics Connector to Version 4.x

Upgrade Anypoint Connector for Salesforce Einstein Analytics Cloud (Salesforce Analytics Connector) from version 3.x to version 4.x.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
| From Version | To Version
| 3.x | 4.x
|===

== Changes

=== 4.0

* Salesforce Analytics Connector now supports the xref:salesforce-analytics-connector-reference.adoc#salesforce-analytics_oauth-client-credentials[OAuth Client Credentials] connection type, which enables automated, server-to-server integrations that don't require user interaction.
* The *Username Password* connection type is supported for Salesforce API v64.0 and earlier versions only. If your integration uses the *Username Password* connection type with a Salesforce API version later than v64.0, migrate to a supported OAuth connection type, such as xref:salesforce-analytics-connector-reference.adoc#salesforce-analytics_basic[OAuth 2.0], xref:salesforce-analytics-connector-reference.adoc#salesforce-analytics_oauth-client-credentials[OAuth Client Credentials], xref:salesforce-analytics-connector-reference.adoc#salesforce-analytics_oauth-jwt-connection[OAuth JWT], or xref:salesforce-analytics-connector-reference.adoc#salesforce-analytics_oauth-saml-connection[OAuth SAML Bearer].

== Requirements

Ensure your system meets the following compatibility requirements before you perform the upgrade:

[%header%autowidth.spread]
|===
| Application/Service | Version
| Mule runtime | 4.6.0 and later
|===

== Upgrade Prerequisites

Before you perform the upgrade, you must:

. Create a backup of your files, data, and configuration in case you need to restore to the previous version.
. Ensure that your Mule runtime version is 4.6.0 or later.
. If your app uses the *Username Password* connection type with a Salesforce API version later than v64.0, migrate to the *OAuth Client Credentials*, *OAuth JWT*, *OAuth SAML Bearer*, or *OAuth 2.0* connection type.

== Upgrade Steps

Follow these steps to perform the upgrade from Salesforce Analytics Connector 3.x to Salesforce Analytics Connector 4.x:

. In Anypoint Studio, create a Mule project.
. In the Mule Palette view, click *Search in Exchange*.
. In the *Add Dependencies to Project* window, enter `Salesforce Einstein Analytics` in the search field.
. In the *Available modules* section, select *Salesforce Einstein Analytics Connector - Mule 4* and click *Add*.
. Click *Finish*.
. Verify that the `mule-sfdc-analytics-connector` dependency version is `4.x.x` in the `pom.xml` file, where `x.x` is the minor release and patch version number. For example, if you are upgrading to v4.0, the dependency version in the `pom.xml` file should be `4.0.0`.

Studio upgrades the connector automatically.

== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Check the project `pom.xml` file and verify that there are no problems.
. Test the connection and verify that the operations work.

== Troubleshooting

If there are problems with caching the parameters and caching the metadata, try restarting Studio.

== Revert the Upgrade

If it is necessary to revert to the previous version of Salesforce Analytics Connector, change the `mule-sfdc-analytics-connector` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:index.adoc[Salesforce Einstein Analytics Cloud Connector Overview]
* xref:salesforce-analytics-connector-reference.adoc[Salesforce Einstein Analytics Connector Reference]
* xref:release-notes::connector/salesforce-analytics-connector-release-notes-mule-4.adoc[Salesforce Einstein Analytics Connector Release Notes]
