= Confluent Schema Registry Connector - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Confluent Schema Registry (Confluent Schema Registry Connector) enables
interaction with Confluent's Schema Registry to save and retrieve avro schemas to reduce
the size of an avro message while it transports through the network.

For information about compatibility and fixed issues, see the Confluent Schema Registry Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Confluent Schema Registry Connector’s API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Confluent Schema Registry target resource
* Anypoint Platform
* Anypoint Studio version 7.3.5 or later

== Common Use Cases For the Connector

Some possible uses for this connector include:

* Send an avro message to a Kafka broker.
* Consume an avro message with a schema ID.
* Send a schema to Confluent Schema Registry using authentication.

== Connection Types

Confluent Schema Registry connections use the following authentication types:

* Basic auth +
Basic HTTP authentication supported by the API.

* Unsecured +
Unauthenticated.

For information about configuring authentication types, see xref:confluent-schema-registry-connector-studio.adoc[Use Studio to Configure Confluent Schema Registry Connector].

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:confluent-schema-registry-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:confluent-schema-registry-connector-reference.adoc[Confluent Schema Registry Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
