= Anthropic MCP Connector 1.0 - Mule 4
:lc-connector-name: anthropic-mcp

Anypoint Connector for Anthropic MCP (MCP Connector) uses the Model Context Protocol (MCP) to enable supported Agents like Claude, Cursor, Windsurf, and the growing fleet of MCP clients to invoke and communicate with APIs and other artifacts built on Anypoint Platform. 

MCP is an open protocol that enables seamless integration between LLM applications and external data sources and tools. MCP is a new standard allowing LLM and agent applications to communicate with each other (and with preexisting systems) in a consistent way. 

MCP Connector allows you to write Mule apps that can act as both an MCP server and client. 

This beta release is focused on tools and resources. 

== Before You Begin

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Code Builder or Anypoint Studio

Before creating an app, you must have:

* Java 17
* Apache Maven
* Anypoint Platform
* Credentials to connect with 
* The latest versions of Anypoint Code Builder or Anypoint Studio


== Common Use Cases for the Connector

These are some common use cases for the connector:

* Customer Service
+
Use AI agents to help human agents to be more efficient by handling time-intensive tasks like reviewing case histories, analyzing reported issues, and retrieving relevant information.
* Sales
+
Improve sales teams' success by accelerating prospect research, generating customized collateral, and preparing contracts.
* Marketing
+
Empower marketing teams with AI-driven support for drafting social media content, conducting market research, and analyzing campaign performance.


== Next Step

include::connectors::partial$t-index-partial.adoc[tags=next-step]

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[]
* xref:connectors::introduction/intro-config-use-acb.adoc[]
* xref:connectors::introduction/intro-config-use-studio.adoc[]
* xref:anthropic-mcp-connector-reference.adoc[Anthropic MCP Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
