= Cryptography Module
:page-aliases: mule-runtime::cryptography.adoc

Cryptography Module provides cryptography capabilities to a Mule application. Its main features include:

* Symmetric encryption and decryption of messages.
* Asymmetric encryption and decryption of messages.
* Message signing and signature validation of signed messages.

The module supports these strategies to encrypt and sign your messages:

* xref:cryptography-module-jce.adoc[JCE] +
Provides cryptography capabilities of Java Cryptography Extension.
* xref:cryptography-module-pgp.adoc[PGP] +
Provides signing and encryption using Pretty Good Privacy.
* xref:cryptography-module-xml.adoc[XML] +
Provides signing and encryption of XML documents or elements.


Additionally, the module offers two general operations to calculate and validate stream checksums.
For details, refer to xref:cryptography-module-reference.adoc[]

== See Also
* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.salesforce.com/[Salesforce Help Center]