= Zuora Connector 5.0 - Mule 4


Anypoint Connector for Zuora (Zuora Connector) enables access to the Zuora platform. This connector exposes all of the operations provided by Zuora's REST API.

For information about the Zuora REST API methods and parameters, see the https://www.zuora.com/developer/api-reference[Zuora REST API Reference].

Release Notes: xref:release-notes::connector/zuora-connector-release-notes-mule-4.adoc[Zuora Connector Release Notes] +
Exchange: https://anypoint.mulesoft.com/exchange/com.mulesoft.connectors/mule-zuora-connector[Zuora Connector]


== About Connectors

Anypoint connectors are Mule runtime engine (Mule) extensions that enable you to connect to APIs and resources on external systems, such as Salesforce, Zuora, ServiceNow, and Twitter.

== Prerequisites

Before creating an app, you must have access to the Zuora target resource and Anypoint Platform. You must also understand how to create a Mule app using Design Center or Anypoint Studio.

== Audience

* Starting user
+
Read this Get Started document
and create your Mule app in xref:zuora-connector-design-center.adoc[Design Center] or
xref:zuora-connector-studio.adoc[Anypoint Studio].
* Power user
+
Read the xref:zuora-connector-xml-maven.adoc[XML and Maven Support] and xref:zuora-connector-examples.adoc[Examples] documents.

== Next Step

After you have read this topic, you are ready to create an app with
xref:zuora-connector-design-center.adoc[Design Center] or
xref:zuora-connector-studio.adoc[Anypoint Studio].


== See Also

xref:release-notes::connector/zuora-connector-release-notes-mule-4.adoc[Zuora Connector Release Notes]
https://anypoint.mulesoft.com/exchange/com.mulesoft.connectors/mule-zuora-connector[Zuora Connector]
https://help.mulesoft.com[MuleSoft Help Center]
