= Zuora XML and Maven Support - Mule 4


If you manually code a Mule app in XML either from the
Studio XML editor or a text editor, you must perform the
following actions to get access to the connector:

. Add the namespace for the connector to your XML flow.
. Add dependency information to your Maven `pom.xml` file.

In the Studio visual editor, when you drag a connector from the palette to the canvas, Studio automatically populates the XML code with the connector namespace and schema location.

== Add a Namespace for the Connector

If you manually code the Mule app using Studio’s XML editor or another text editor, paste the following code inside the `<mule>` tag of the header of your configuration XML.

[source,text,linenums]
----
xsi:schemaLocation="
...
http://www.mulesoft.org/schema/mule/zuora-connector
http://www.mulesoft.org/schema/mule/zuora-connector/current/mule-zuora-connector.xsd"
----

This example shows how the namespace statements are placed in the mule XML block:

[source,xml,linenums]
----
<mule xmlns:http="http://www.mulesoft.org/schema/mule/http"
      xmlns:mule-zuora-connector="http://www.mulesoft.org/schema/mule/mule-zuora-connector"
	    xmlns="http://www.mulesoft.org/schema/mule/core"
	    xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core
               http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/mule-zuora-connector
               http://www.mulesoft.org/schema/ mule/mule-zuora-connector/current/mule-mule-zuora-connector.xsd
               http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">
      <!-- Insert your configuration elements and your flow here -->
</mule>
----

[[pomfile]]
== Add a POM File Dependency

The `pom.xml` Maven file generated by Anypoint Studio contains dependencies for a Mule app. When you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to this connector. The Mule runtime engine translates the `RELEASE` dependency keyword to the current version.

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-zuora-connector</artifactId>
  <version>RELEASE</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

== Next Step

After completing this section, see the the xref:zuora-connector-examples.adoc[Zuora Examples] to experiment with Zuora Connector.

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
