= ServiceNow Connector 5.0 Migration Guide
:keywords: anypoint studio, esb, connector, endpoint, servicenow, service now
:page-aliases: 3.9@mule-runtime::servicenow-connector-5.0-migration-guide.adoc

The ServiceNow connector v5.0 is a complete revamp of the connector, and is not compatible with any older version of the connector. Please refer to the DevKit annotation documentation for more information.

The ServiceNow Connector version 5.0 is developed to:

* Support all standard ServiceNow operations
* Support customized tables (including the custom fields)

*Guide:* xref:index.adoc[ServiceNow Connector Overview]

*Release Notes*: xref:release-notes::connector/servicenow-connector-release-notes.adoc#5-0[ServiceNow Connector 5.0 Release Notes]

== Version 5.0 vs. Previous Versions

[%header,cols="3*a"]
|===
|  |ServiceNow Connector 5.0 |Previous versions of the ServiceNow Connector
|Global Configuration |
The ServiceNow connector now offers two global configuration types:

.  *Simple Configuration* - Apart from the support for username, password, and service address, you can now provide a list of user tables in the global element. This list contains the names of tables which need to be fetched from the ServiceNow sandbox dynamically. This is an important feature for supporting true customizations.
. *Advanced Config* - Apart from what is available in the simple configuration, the advanced configuration supports a user defined HTTP Request Configuration having proxies, SSL support, and authentication methods.

 |Previous versions of the connector only have support for username, password, and service address fields for test connectivity. They support 47 tables out of the box and it is not possible to support more tables without upgrading the connector to version 5.0.
|Connector Component - Basic Settings Panel |The connector component lists only one operation called *Invoke* in the *Operation* list. |These versions have seven operations by default. They are delete record, delete multiple, get, get keys, get records, insert, and update.
|Connector Component - General Panel |
Two new combo-boxes are added:

. *Table* Lists all the tables that can be queried. The list of tables is based on the 47 tables already available in the connector, and some additional tables that are entered in the *List of Tables* in the Global Configuration. The connector dynamically fetches the list of tables from the sandbox and generates the data sense model.
. *Operation* - Lists all the operations supported for the selected table. This list is also dynamic in nature and is generated as a part of the DataSense look up.

 |Support only one combo box listing the tables that are available in the connector. There is an object creation section where input payload can be built.
|Payload Manipulation |Use of data mapper is encouraged to manipulate payload for input and process response. The connector picks the input request from the flow payload. The connector does not support the creation of payload in its component window. |These connectors allow you to create data using DataMapper as well as from the connector’s component window.
|===

=== Updating from an Older Version

When a new version of a connector is released, Anypoint studio displays a popup in the bottom right corner of you screen with the following message: *Updates Available*.
To upgrade to the newer version of the ServiceNow connector:

. Click the popup and check for the available updates.
. Select the **ServiceNow connector 5.0** checkbox and click *Next*
. Follow the instructions provided by the user interface.
. Restart Studio when prompted.

After restarting, if you have multiple versions of the connector installed, Mule asks you for the version of the connector you like to use.
