= Gmail Connector 1.0 - Mule 4



Anypoint Connector for Gmail (Gmail Connector) enables the management of your Gmail account, including sending and receiving emails and reacting to received emails.

For information about compatibility and fixed issues, see the Gmail Connector Release Notes.

== Before You Begin

To use this connector, you must be familiar with:

* The Gmail Connector’s API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Gmail target resource
* Anypoint Platform
* Anypoint Studio version 7.0 or later

== Common Use Cases For the Connector

Some possible uses for this connector include:

* Sending an email to thank customers for a new purchase.
* Organizing all emails related to an event.
* Receiving attachments via email to verify an ID.

== Connection Types

Gmail connections use the Oauth2c authentication type, which uses access tokens provided by the authorization server to access protected data.

For information about configuring authentication types, see xref:gmail-connector-studio.adoc[Using Anypoint Studio to Configure Gmail Connector].

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:gmail-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:gmail-connector-reference.adoc[Gmail Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
