= Tracing Module Examples

To fully benefit from using Tracing module, see the following examples of configuring the module operations and scope. The examples use Anypoint Code Builder; see xref:tracing-module-config-acb.adoc[Using Anypoint Code Builder to Configure Tracing Module] to get started.


* xref:tracing-module-with-correlationid.adoc[Change the Correlation ID During Flow Execution] +
Configure the *With CorrelationID* scope to modify the correlation ID during flow execution.
* xref:tracing-module-logging.adoc[Configure Logging Variables] +
Configure the *Clear logging variables*, *Remove logging variable* and *Set logging variable* Tracing module operations.
* xref:tracing-module-add-root-span-attributes.adoc[Add Custom Attributes to the Root Span] +
Configure the *Add Root Span Attributes* operation to attach transaction-level fields to the root span.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.salesforce.com[Salesforce Help]
