= Compression Module
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, compression, module, release notes

The Compression module provides functionality for handling compressed data.

== Compressing data

The `zip` operation compresses data using the ZIP format.

Actual compression will occur in a lazy manner. This operation returns a stream and actual compression will happen as the stream is consumed.
Keep in mind that any errors that may rise during compression will not occur in this operation, but in those which are consuming the stream returned here.

The following example will compress the current message payload:

[source,xml,linenums]
----
<compression:zip />
----

You can also use embedded DataWeave transformations to compress a custom content:

[source,xml,linenums]
----
<compression:zip>
    <compression:content>
        #[payload.userData.image]
    </compression:content>
</compression:zip>
----

== Decompressing data

The `unzip` operation decompresses data using the ZIP format.

Actual compression will occur in a lazy manner. This operation returns a stream and actual decompression will happen
as the stream is consumed. Keep in mind that not all errors that may rise during compression will occur in this operation.
Some might actual appear in the components that consume this stream

The following example will decompress the current message payload:

[source,xml,linenums]
----
<compression:unzip />
----

You can also use embedded DataWeave transformations to compress a custom content:

[source,xml,linenums]
----
<compression:unzip>
    <compression:content>
        #[payload.userData.compressedImage]
    </compression:content>
</compression:unzip>
----

== Adding the module to your project

To use the FTPS module, you simply add it to your Mule app through the Studio or Flow Designer UI, or you can add the following dependency in your `pom.xml` file:

[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-compression-module</artifactId>
    <version>1.0.0</version> <!-- or newer -->
    <classifier>mule-plugin</classifier>
</dependency>
----



== See Also

xref:compression/compression-documentation.adoc[Compression Module Technical Reference]