// Connector Landing Page


:connector-name: Redis
:support-category: Select
:lc-connector-name: redis
:version: 1.0
:studio-version: 4.1.1

= {connector-name} Connector {version} - Mule 4

include::connectors::partial$t-index-partial.adoc[tags=category]

<Connector description>

////
For example:
Anypoint Connector for Remote Dictionary Server (Redis Connector) is an open source, in-memory data structure store used to cache user profiles, create leader boards, track real-time activities on a website, and filter spam. You can use Redis Connector as a message queue, custom object store, and more.
////

== Prerequisites

include::connectors::partial$t-index-partial.adoc[tags=prerequisites]

== Common Use Cases For the Connector

////
Make the title singular if there is just one use case.

Add a lead in sentence and then list common use cases for the connector. For example:
These are some common use cases for {connector-name} Connector...
////

For examples of these use cases, see xref:{lc-connector-name}-connector-examples.adoc[{connector-name} Connector Examples].

== Connection Types

[NOTE]
Redis Connector supports only password-based authentication. Redis Connector does not currently support Role-Based Access Control (RBAC).

Redis Connector uses the following connection types:

* Clustered
* NonClustered
* Sentinel

For information about configuring authentication types, see xref:{lc-connector-name}-connector-studio.adoc#configure-global-element[Configure a Global Element for the Connector].

== Next Step

include::connectors::partial$t-index-partial.adoc[tags=next-step]

== See Also

include::connectors::partial$t-index-partial.adoc[tags=see-also]
