
////
Set connector-specific values for the following variables:

* {connector-name} - Name of the connector without the word "Connector." For example, Redis.
* {version} - connector version. For example, 1.0.
* lc-connector-name - Lower case connector name to use in the namespace code and POM file. For example: redis
* connector-xsd - Last part of the connector XSD path to use in the namespace code. For example: For example: mule-redis.xsd
* group-id-exchange - Connector group ID for the POM file. For example: com.mulesoft.connectors
* artifact-id-exchange - Connector artificat ID for the POM file. For example: mule-redis.xsd
* {exchange-search-name} - Lower case term used to find the connector in Exchange. For example, redis.
////

:connector-name: Redis
:version: 1.0
:lc-connector-name: redis
:connector-xsd: redis.xsd
:group-id-exchange: com.mulesoft.connectors
:artifact-id-exchange: mule-redis-connector
:exchange-search-name: redis

= {connector-name} Connector {version} - XML and Maven Support - Mule 4

include::connectors::partial$t-xml-maven-partial.adoc[tags=topic-intro]

== Add a Namespace for the Connector
include::connectors::partial$t-xml-maven-partial.adoc[tags=add-namespace]

== Add a POM File Dependency
include::connectors::partial$t-xml-maven-partial.adoc[tags=pom-file]

== Next Step
include::connectors::partial$t-xml-maven-partial.adoc[tags=next-step]

== See Also
include::connectors::partial$t-xml-maven-partial.adoc[tags=see-also]
