= Configuring Chat Operations

Configure the *[Chat] Answer Prompt* and *[Chat] Completions* operations. 

== Configure the Chat Answer Prompt Operation

The *[Chat] Answer Prompt* operation is a simple prompt request operation to the configured LLM. It uses a plain text prompt as input and responds with a plain text answer. 

Apply the *[Chat] Answer Prompt* operation in various scenarios, such as for:

* *Basic Chatbots*
+
Answer simple user prompts.
* *Customer Service Queries*
+
Provide direct answers to frequently asked questions.

To configure the *[Chat] Answer Prompt* operation:

include::connectors::partial$t-configure-operations.adoc[]
* *Prompt*
+
Enter the prompt as plain text for the operation.

This is the XML for this operation:

[source,xml,linenums, subs=attributes+]
----
<mac-inference:chat-answer-prompt doc:name="Chat answer prompt" doc:id="f513c329-d277-41e6-932c-f5032b3365ac" config-ref="Github_Models" >
	<mac-inference:prompt ><![CDATA[#[payload.prompt]]]></mac-inference:prompt>
</mac-inference:chat-answer-prompt>
----

=== Output Configuration

This operation responds with a JSON payload containing the main LLM response. This is an example response:

[source,json]
----
{
    "response": "The capital of Switzerland is Bern. It's known for its well-preserved medieval old town, which is a UNESCO World Heritage site. Bern became the capital of Switzerland in 1848. The Swiss parliament, the Federal Assembly, is located in Bern."
}
----

The operation also returns attributes that aren't within the main JSON payload, that include information about token usage, for example:

[source,json]
----
{
  "tokenUsage": {
      "outputCount": 9,
      "totalCount": 18,
      "inputCount": 9
  },
  "additionalAttributes": {}
}
----

* `tokenUsage`: Token usage metadata returned as attributes
** `outputCount`: Number of tokens used to generate the output
** `totalCount`: Total number of tokens used for input and output
** `inputCount`: Number of tokens used to process the input

== Configure the Chat Completions Operation

The *[Chat] Completions* operation is useful when you want to retain conversation history for a multi-user chat operation. MuleSoft Object Store or any database can hold previous user conversation, which can be provided as messages into the *[Chat] Completions* operation. 

Apply the *[Chat] Completions* operation in various scenarios, such as for:

* *Customer Support Chats*
+
Retaining the context of ongoing support conversations.
* *Multi-user Chat Applications*
+
Maintaining conversation history for different users.
* *Personal Assistants*
+
Keeping track of user interactions to provide more relevant responses.

To configure the *[Chat] Completions* operation:

include::connectors::partial$t-configure-operations.adoc[]
* *Messages*
+
Specify the conversation history as a JSON array.

This is the XML for this operation:

[source,xml,linenums, subs=attributes+]
----
<mac-inference:chat-completions doc:name="Chat completions" doc:id="b2c68037-6af9-4e2a-9297-c57749a38193" config-ref="Ollama" >
	<mac-inference:messages ><![CDATA[#[payload.data]]]></mac-inference:messages>
</mac-inference:chat-completions>
----    

=== Output Configuration

This operation responds with a JSON payload containing the main LLM response. This is an example response:

[source,json]
----
{
   "response": "The capital of Switzerland is **Bern**. 🇨🇭 \n"
}
----

The operation also returns attributes that aren't within the main JSON payload, that include information about token usage and additional metadata, for example:

[source,json]
----
{
    "attributes": {
        "tokenUsage": {
            "outputCount": 15,
            "totalCount": 37,
            "inputCount": 22
        },
        "additionalAttributes": {
            "finish_reason": "stop",
            "model": "gemma2-9b-it",
            "id": "chatcmpl-fc2425f6-0b70-4018-936f-f0df6c0b5da1"
        }
    }
}
----

* `tokenUsage`: Token usage metadata returned as attributes
** `outputCount`: Number of tokens used to generate the output
** `totalCount`: Total number of tokens used for input and output
** `inputCount`: Number of tokens used to process the input
* `additionalAttributes`: Additional metadata from the LLM provider
** `finish_reason`: The finish reason for the LLM response
** `model`: The ID of the model used
** `id`: The ID of the request

== See Also

* xref:index.adoc[MuleSoft Inference Connector Overview]
* xref:mulesoft-inference-connector-reference.adoc[MuleSoft Inference Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center] 