= Configuring Tools Operations

Configure the *[Tools] Native Template (Reasoning only)* operation.

== Configure the Tools Native Template (Reasoning only) Operation

The *[Tools] Native Template (Reasoning only)* operation is useful if you want to create autonomous agents that can use external tools whenever a prompt can't be answered directly by the AI model. This operation selects which tools can be used for execution.

Apply the *[Tools] Native Template (Reasoning only)* operation in various scenarios, such as for:

* *Automating Routine Tasks*
+
Create autonomous agents that handle routine tasks by calling appropriate APIs.
* *Customer Support*
+
Automate responses to common queries by integrating tools that provide necessary information.
* *Inventory Management*
+
Use tools to check inventory levels or order status based on user prompts.
* *Employee Management*
+
Retrieve employee information or manage employee-related tasks through API calls.
* *Sales and Marketing*
+
Access CRM data or manage leads and accounts efficiently using predefined tools.

To configure the *[Tools] Native Template (Reasoning only)* operation:

include::connectors::partial$t-configure-operations.adoc[]
* *Template*
+
Enter the template for the operation.
* *Instructions*
+
Enter the instructions for the operation.
* *Data*
+
Enter the prompt to send to the LLM, along the tools array. The result suggests a chaining of the tool as a request to fulfill the users request.
* *Tools*
+
Enter the tools for the operation.

This is an example of the tools array in the payload:

[source,json,linenums]
----
{
   "tools":[
      {
         "type":"function",
         "function":{
            "name":"get_current_temperature",
            "description":"Get the current temperature for a specific location",
            "parameters":{
               "type":"object",
               "properties":{
                  "location":{
                     "type":"string",
                     "description":"The city and state, e.g., San Francisco, CA"
                  },
                  "unit":{
                     "type":"string",
                     "enum":[
                        "Celsius",
                        "Fahrenheit"
                     ],
                     "description":"The temperature unit to use. Infer this from the user's location."
                  }
               },
               "required":[
                  "location",
                  "unit"
               ]
            }
         }
      },
      {
         "type":"function",
         "function":{
            "name":"get_rain_probability",
            "description":"Get the probability of rain for a specific location",
            "parameters":{
               "type":"object",
               "properties":{
                  "location":{
                     "type":"string",
                     "description":"The city and state, e.g., San Francisco, CA"
                  }
               },
               "required":[
                  "location"
               ]
            }
         }
      },
      {
         "type":"function",
         "function":{
            "name":"get_delivery_date",
            "description":"Get the delivery date for a customer's order. Call this whenever you need to know the delivery date, for example when a customer asks 'Where is my package'",
            "parameters":{
               "type":"object",
               "properties":{
                  "order_id":{
                     "type":"string",
                     "description":"The customer's order ID."
                  }
               },
               "required":[
                  "order_id"
               ]
            }
         }
      }
   ]
}
----

This is the XML for this operation:

[source,xml,linenums]
----
<ms-inference:tools-native-template doc:name="Tools native template" doc:id="ff267b16-b0f7-4a8d-8dd8-004a8269862b" config-ref="Portkey">
    <ms-inference:template ><![CDATA[You are a helpful assistant that can use the following tools to answer questions.]]></ms-inference:template>
    <ms-inference:instructions ><![CDATA[Use the tools to answer the question.]]></ms-inference:instructions>
    <ms-inference:data ><![CDATA[#[payload.dataset]]]></ms-inference:data>
    <ms-inference:tools ><![CDATA[#[payload.tools]]]></ms-inference:tools>
</ms-inference:tools-native-template>
 
----

=== Output Configuration

This operation responds with a JSON payload containing the main LLM response. 

==== Example Response Payload (Tools not used)

If the prompt is a general question that can be answered with public knowledge, such as `What is the capital of Switzerland?`, the response is:

[source,json,linenums]
----
{
    "response": "The capital of Switzerland is Bern."
}
----

==== Example Response Payload (Tools used)

If the prompt requires accessing external data through a tool, such as `When will my order (ID = 220) be delivered?`, the AI model uses the configured tool to fetch the information, and the response is:

[source,json,linenums]
----
{
    "response": {
        "tools": [
            {
                "function": {
                    "name": "get_delivery_date",
                    "arguments": "{\"order_id\":\"220\"}"
                },
                "id": "call_ylw95cO0kxCt7NELy91cF7bX",
                "type": "function"
            }
        ]
    }
}
----

The operation also returns attributes that aren't within the main JSON payload, that include information about token usage, for example:

[source,json,linenums]
----
{
    "attributes": {
        "tokenUsage": {
            "inputCount": 204,
            "outputCount": 16,
            "totalCount": 220
        },
        "additionalAttributes": {
            "finish_reason": "tool_calls",
            "model": "gpt-4o-2024-08-06",
            "id": "chatcmpl-AQwXGmrzcO7XG5Ic1Hp0PKIrRoL4O"
        }
    }
}
----
 
* `tokenUsage`: Token usage metadata returned as attributes
** `inputCount`: Number of tokens used to process the input
** `outputCount`: Number of tokens used to generate the output
** `totalCount`: Total number of tokens used for input and output
* `additionalAttributes`: Additional metadata from the LLM provider
** `finish_reason`: The finish reason for the LLM response
** `model`: The ID of the model used
** `id`: The ID of the request

== See Also

* xref:index.adoc[MuleSoft Inference Connector Overview]
* xref:mulesoft-inference-connector-reference.adoc[MuleSoft Inference Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center] 