= Configuring Agent Operations

Configure the *[Agent] Define Prompt Template* operation. 

== Configure the Agent Define Prompt Template Operation

The *[Agent] Define Prompt Template* operation is essential for using specific prompt templates with your LLMs. This operation allows you to define and compose AI functions using plain text, enabling the creation of natural language prompts, generating responses, extracting information, invoking other prompts, or performing any text-based task.

Apply the *[Agent] Define Prompt Template* operation in various scenarios, such as for:

* *Customer Service Agents*
+
Enhance customer service by providing case summaries, case classifications, summarizing large datasets, and more.
* *Sales Operation Agents*
+
Assist sales teams in writing sales emails, summarizing cases for specific accounts, assessing the probability of closing deals, and more.
* *Marketing Agents*
+
Support marketing teams in generating product descriptions, creating newsletters, planning social media campaigns, and more.

To configure the *[Agent] Define Prompt Template* operation:

include::connectors::partial$t-configure-operations.adoc[]
* *Template*
+
Enter the prompt template for the operation.
* *Instructions*
+
Provide the instructions for the inference provider, outlining the goals of the task.
* *Data*
+
Specify the data for the inference provider to evaluate using the provided template and instructions.

This is the XML for this operation:
[source,xml,linenums, subs=attributes+]
----
<mac-inference:agent-define-prompt-template doc:name="Agent define prompt template" doc:id="5944353c-c784-4268-9f16-c036e5eaf8e3" config-ref="Github_Models" >
			<mac-inference:template ><![CDATA[#[payload.template]]]></mac-inference:template>
			<mac-inference:instructions ><![CDATA[#[payload.instructions]]]></mac-inference:instructions>
			<mac-inference:data ><![CDATA[#[payload.dataset]]]></mac-inference:data>
</mac-inference:agent-define-prompt-template>
----

=== Output Configuration

This operation responds with a JSON payload containing the main LLM response. This is an example response:

[source,json]
----
{
  "response": "{\n  \"type\": \"positive\",\n  \"response\": \"Thank you for your positive feedback on the training last week. We are glad to hear that you had a great experience. Have a nice day!\"\n}"
}
----

The operation also returns attributes that aren't within the main JSON payload, that include information about token usage, for example:

[source,json]
----
{
  "tokenUsage": {
      "outputCount": 9,
      "totalCount": 18,
      "inputCount": 9
  },
  "additionalAttributes": {}
}
----

* `tokenUsage`: Token usage metadata returned as attributes
** `outputCount`: Number of tokens used to generate the output
** `totalCount`: Total number of tokens used for input and output
** `inputCount`: Number of tokens used to process the input

== See Also

* xref:index.adoc[MuleSoft Inference Connector Overview]
* xref:mulesoft-inference-connector-reference.adoc[MuleSoft Inference Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center] 