= MuleSoft Inference Connector 1.0 XML and Maven Support 

include::connectors::partial$t-xml-maven-partial.adoc[tags=topic-intro]

== Add a Namespace for the Connector

Paste the following code inside the `mule` tag of the header of your configuration XML:

[source,xml,linenums, subs=attributes+]
----
http://www.mulesoft.org/schema/mule/ms-inference 
http://www.mulesoft.org/schema/mule/ms-inference/current/mule-ms-inference.xsd
----

This example shows how the namespace statements are placed in the `<mule>` XML block:

[source,xml,linenums, subs=attributes+]
----
<mule xmlns:ms-inference="http://www.mulesoft.org/schema/mule/ms-inference" 
    xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core 
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
    http://www.mulesoft.org/schema/mule/http 
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
    http://www.mulesoft.org/schema/mule/ms-inference 
	http://www.mulesoft.org/schema/mule/ms-inference/current/mule-ms-inference.xsd">
----

== Add a POM File Dependency

The Apache Maven `pom.xml` file generated by Anypoint Code Builder and Studio contains dependencies for a Mule app. If you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to this connector:

[source,xml,linenums,subs=attributes+]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule4-inference-connector</artifactId>
  <version>x.x.x</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

Replace `x.x.x` with the version that corresponds to the connector you are using.

To get the most up-to-date `pom.xml` file information:

. Go to https://www.mulesoft.com/exchange/[Anypoint Exchange].
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for `mulesoft inference`.
. Select the connector.
. Click *Dependency Snippets* near the upper right of the screen.

== Example Configuration

This example shows a complete Mule application configuration using the MuleSoft Inference Connector:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns:ms-inference="http://www.mulesoft.org/schema/mule/ms-inference"
    xmlns:http="http://www.mulesoft.org/schema/mule/http"
    xmlns="http://www.mulesoft.org/schema/mule/core"
    xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core 
    http://www.mulesoft.org/schema/mule/core/current/mule.xsd
    http://www.mulesoft.org/schema/mule/http 
    http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
    http://www.mulesoft.org/schema/mule/ms-inference 
    http://www.mulesoft.org/schema/mule/ms-inference/current/mule-ms-inference.xsd">

    <http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config">
        <http:listener-connection host="0.0.0.0" port="8081" />
    </http:listener-config>

    <ms-inference:config 
        name="MuleSoft_Inference_Configuration" 
        doc:name="MuleSoft Inference Config"
        configType="Environment Variables"
        filePath="-"
        provider="OPENAI"
        modelName="gpt-4o"
        temperature="0.7"
        maxTokens="1000"
        timeout="60">
    </ms-inference:config>

    <flow name="chat-flow" doc:id="12345678-1234-1234-1234-123456789012">
        <http:listener 
            doc:name="Listener" 
            config-ref="HTTP_Listener_config" 
            path="/chat"/>
        <ms-inference:chat-answer-prompt 
            doc:name="Chat answer prompt"
            config-ref="MuleSoft_Inference_Configuration"
            prompt="#[payload.prompt]"/>
        <logger level="INFO" doc:name="Logger" message="#[payload]"/>
    </flow>
</mule>
----

== Supported Java Version

The MuleSoft Inference Connector requires Java 17 for both compilation and runtime. Ensure your Mule runtime environment supports Java 17.

== See Also

* xref:index.adoc[MuleSoft Inference Connector Overview]
* xref:mulesoft-inference-connector-reference.adoc[MuleSoft Inference Connector Reference]
* xref:mulesoft-inference-additional-config.adoc[MuleSoft Inference Connector - Additional Configuration]
* https://help.mulesoft.com[MuleSoft Help Center] 