= Azure Service Bus Connector 3.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]


Anypoint Connector for Azure Service Bus (Azure Service Bus Connector) enables message integration with Azure Service Bus on the cloud. This connector supports communication with queues and topics. 

To use the management API to discover Azure Service Bus objects automatically and to provision them, use the Anypoint Connector for Azure Service Bus Management (Azure Service Bus Management Connector).

For compatibility information and fixed issues, see the xref:release-notes::connector/<connector>.adoc[Azure Service Bus Messaging Connector Release Notes] 

== Prerequisites

To use this connector, you must be familiar with:

* The Azure Service Bus APIs
* Anypoint connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to the Azure target resource. 

== Common Use Cases For the Connector

// Add a lead in sentence and then list common use cases for the connector

// For examples, see xref:azure-service-bus-messaging-connector-examples.adoc[Examples].

== Audience

* New user
+
To create your Mule app, see:

* xref:azure-service-bus-messaging-connector-studio.adoc[Studio Configuration] 
* xref:azure-service-bus-messaging-connector-config-topics.adoc[Additional Configuration Information]
to help extend your understanding of the Azure Service Bus Messaging connector 
* xref:azure-service-bus-messaging-connector-examples.adoc[Examples], which provides one or more use cases for the connector.
+
* Advanced user
+
* Read the following: 

* xref:azure-service-bus-messaging-connector-xml-maven.adoc[XML and Maven Support]
* xref:azure-service-bus-messaging-connector-config-topics.adoc[Additional Configuration Information]
* xref:azure-service-bus-messaging-connector-examples.adoc[Examples] topics

For a major or minor release, see
xref:azure-service-bus-messaging-connector-upgrade-migrate.adoc[Upgrade and Migrate].

== Authentication Types

//If there is one authentication type, use the following format:

Azure Service Bus Connector uses the <authentication-type> authentication type to connect to Azure, which ... <add a brief description of the authentication type like the descriptions below>.

//If there is more than one authentication type, use a list like that shown below:

Azure Service Bus connections can use the following authentication types:

* Basic authentication
+
Uses a username and password for authentication
+
* OAuth
+
Uses access tokens provided by the authorization server to get access to protected data 
+
* OAuth2 
+
Delegates user authentication to the service hosting the user account

For information about configuring these authentication types, see xref:azure-service-bus-studio.adoc[Use Studio to Configure Azure Service Bus Connector].


////
Include this section only if Exchange provides templates, examples, or both for the connector. If there are templates and not examples, or vice versa, reword the section as applicable. 
////

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as a starting point for your app, as well as examples that illustrate a complete solution.

////
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////


== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app and configure the connector using xref:azure-service-bus-connector-studio.adoc[Anypoint Studio].

== See Also

xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
<link to the connector in Exchange>
https://help.mulesoft.com[MuleSoft Help Center]
