= Azure Service Bus Connector 3.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]


Anypoint Connector for Azure Service Bus (Azure Service Bus Connector) makes it easy to build integrations that send messages to and receive messages from Azure Service Bus, which is an asynchronous messaging cloud platform. This connector supports communication with queues and topics and can perform actions such as:

* Send to queue
* Send to topic
* Receive from queue
* Receive from subscription

To use the Azure management API for CRUD operations of queues, topics, subscriptions, and rules, use Anypoint Connector for Azure Service Bus Management (Azure Service Bus Management Connector).

[NOTE]
This connector supports integrations with Azure Service Bus (cloud). It does not work with Microsoft Service Bus (on-premises). To connect with Microsoft Service Bus on-premises, use Anypoint Connector for Microsoft Service Bus. 

For compatibility information and fixed issues, see the release notes. 

== Prerequisites

To use this connector, you must be familiar with:

* The Azure Service Bus APIs
* Anypoint connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Access to the Azure target resource
* Java 8
* Anypoint Studio 7.1.0 or later
* Mule Runtime 4.2.x EE or later

== Audience

* New user
+
To create your Mule app, see:

* xref:azure-service-bus-connector-studio.adoc[Studio Configuration]  
* xref:azure-service-bus-connector-examples.adoc[Examples], which provides one or more use cases for the connector.
+
* Advanced user
+
* Read the following: 

* xref:azure-service-bus-connector-xml-maven.adoc[XML and Maven Support]
* xref:azure-service-bus-connector-examples.adoc[Examples] topics

== Authentication Types

Azure Service Bus Connector uses the SAS (shared access signature) authentication connection type to connect to Azure.

For information about configuring these authentication types, see xref:azure-service-bus-connector-studio.adoc[Use Studio to Configure Azure Service Bus Connector].


== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app and configure the connector using xref:azure-service-bus-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://anypoint.mulesoft.com/exchange/com.mulesoft.connectors/mule-azure-service-bus-connector/[Azure Service Bus Connector on Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
 
