= Upgrading and Migrating Amazon EC2 Connector to Version 3.x

Upgrade Anypoint Connector for Amazon EC2 (Amazon EC2 Connector) to version 3.x.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|2.x |3.x
|===

== Changes in This Release

* The AWS SDK version is upgraded to v2.x.x. The response is now aligned with the new SDK specifications.

== Requirements

Ensure your system meets the following compatibility requirements before you perform the upgrade:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule runtime |4.2.0 and later
|AWS SDK for Java |v2.35.3
|OpenJDK |8, 11, and 17
|===

== Upgrade Prerequisites

Before you perform the upgrade, create a backup of your files, data, and configuration in case you need to restore to the previous version.

== Upgrade Steps

Follow these steps to perform the upgrade to version 3.x:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `amazon ec2` in the search field.
. In *Available modules*, select *Amazon EC2 Connector* and click *Add*.
. Click *Finish*.
. Verify that the Amazon EC2 Connector dependency version is 3.x in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

== Post-Upgrade Steps

After you install the latest version of the connector, verify that your error handling is updated to work with the minor changes in error codes in this version of the connector.

== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Revert the Upgrade

If it is necessary to revert to the previous version of Amazon EC2 Connector, change the Amazon EC2 Connector dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.salesforce.com[Salesforce Help]
