= Troubleshooting VM Connector - Mule 4

To troubleshoot Anypoint Connector for Virtual Machine (VM Connector), become familiar with the information about enabling verbose logging and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with VM Connector is failing, temporarily enable verbose logging for VM Connector. +

Remember to always disable the enhanced verbosity after troubleshooting, because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="org.mule.extensions.vm" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* VM:EMPTY_QUEUE

 The referenced queue is empty.

* VM:RETRY_EXHAUSTED

 The maximum number of retries for the operation is reached.

* VM:CONNECTIVITY

 The connection is no longer valid. Apply a reconnection policy if defined in the application setup.

* VM:QUEUE_TIMEOUT

 Timeout exceeded waiting for response on a queue.

* VM:PUBLISH_CONSUMER_FLOW_ERROR

 The *Publish consume* operation failed to process the published message.

== See Also

* xref:vm-reference.adoc[VM Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
* https://issues.salesforce.com/[Known Issues]