= VM Connector Examples - Mule 4
:page-aliases: connectors::vm/vm-connector-examples.adoc

To fully benefit from using Anypoint Connector for Virtual Machine (VM Connector), see the following examples of configuring the connector operations:

* xref:vm-dynamic-routing.adoc[Dynamic Routing] +
Configure the *Publish* operation to dynamically route messages to different queues depending on certain conditions.
* xref:vm-propagate-messages.adoc[Propagate Message Attributes] +
Configure both the *Publish* operation and *Listener* source to propagate message attributes through a VM queue via the message payload.
* xref:vm-publish-across-apps.adoc[Send Messages across Different Apps] +
Configure the *Publish*, *VM Listener*, and *Consume* operations to send messages across different apps.
* xref:vm-publish-listen.adoc[Publish and Listen to Messages] +
Configure the *Publish* operation and *Listener* source to publish a message that is received by a different flow.
* xref:vm-publish-response.adoc[Publish a Message and Get a Response] +
Configure the *Publish consume* operation to publish a message and get a response.

This is a suggestion text.
Testing new line, do not accept me!
This is another new comment
== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
