= VM Connector Publish and Listen to Messages Example - Mule 4
:page-aliases: connectors::vm-consume.adoc, connectors::vm/vm-publish-listen.adoc


The following example shows how to publish a message that is received by a different flow. To do this, use the `<vm:publish>` and `<vm:listener>` elements that point to the same queue.

. Define a flow named `listener` that receives the published message from the subsequent `publish` flow. The `listener` flow contains `<vm:listener>` as a message source and points to `queueName="myQueue"`:

[source,xml,linenums]
----
<flow name="listener">
   <vm:listener queueName="myQueue" config-ref="vm"/>
   <flow-ref name="yourIntegrationLogic"/>
</flow>
----

[start=2]
. Define a flow named `publish` that references to `myQueue` queue that you created in the `listener` flow. The `publish` flow is triggered by an HTTP request. The payload of this request contains the `body` attribute of a JSON object and publishes it to the queue created in the `listener` flow.

* The `publish` operation is one-way. Once the message is posted into the queue, the flow continues. The processing on the listening side happens asynchronously. You do not receive notification of its outcome.
* The `content` parameter enables you to use DataWeave to build the value to send. If you do not specify the `content` parameter, the entire payload is sent.

[source,xml,linenums]
----
    <flow name="publish">
        <http:listener path="/json-here" allowedMethods="POST" config-ref="httpListener" />
        <vm:publish queueName="myQueue">
            <vm:content>#[payload.body]</vm:content>
        </vm:publish>
        <logger/>
    </flow>
----

Having the `<vm:publish>` and `<vm:listener>` elements point to the same queue prevents message loss caused by sending messages to a queue that nobody is listening to.
