= Anypoint Custom Metrics Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Premium

Anypoint Connector for Custom Metrics (Custom Metrics Connector) enables you to send operational and business metric values from an application deployed to an on-premises server and managed in CloudHub to Anypoint Monitoring, where the metrics can be visualized in real time using custom dashboards. 

Once the metrics are in a custom dashboard, you can filter and group the metrics along the included dimensions. You can include multiple custom and built-in metrics in a single dashboard visualization.

[NOTE] 
====
To use the Anypoint Custom Metrics connector, you must have a Titanium subscription. +
This feature is currently supported only for hybrid applications.
====

For an example of how to use the Anypoint Custom Metrics connector in an end-to-end flow, see xref:monitoring::anypoint-custom-metrics-connector.adoc[Custom Metrics].

== See Also

* xref:metrics/custom-metrics-connector-reference.adoc[Custom Metrics Connector Reference]
* xref:monitoring::anypoint-custom-metrics-connector.adoc[Custom Metrics]
