= Microsoft Dynamics 365 - Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

To configure a connector in Anypoint Studio:

. Install the connector
. Configure the connector
. Configure an input source for the connector

== Add the Connector to Your Project

Anypoint Studio provides two ways to add the connector to your Studio project: from the Exchange
button in the taskbar or from the Mule Palette.

=== Add the Connector Using Exchange

. In Studio, create a Mule Project.
. Click the Exchange *(X)* icon in the upper left of the Studio task bar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for Microsoft Dynamics 365.
. Select the connector, click *Add to project*.
. Follow the prompts to install the Microsoft Dynamics 365 Connector.

=== Add the Connector in Studio

. In Studio, create a Mule Project.
. In the Mule Palette, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type Microsoft Dynamics 365 in the search field.
. Click the Microsoft Dynamics 365 Connector name in *Available modules*.
. Click *Add*.
. Click *Finish*.

== Configure an Input Source

Configure an input source trigger for the connector using *On modified object* or *On new object*. When a new or modified 
object occurs in the Microsoft Dynamics 365 operation, an input source is sent to the connector app. 

See xref:microsoft/microsoft-dynamics-365-connector#trigger-required-fields[Trigger Required Fields] to configure the
input source operations.

Alternatively, you can also trigger a connector app by listening for HTTP requests or at timed intervals using Scheduler.

== Configure the Connector

Create a new Mule project using the Anypoint Studio visual editor:

. In Anypoint Studio, click *File* > *New* > *Mule Project*.
. Specify a Project Name and click *Finish*.
. Search for "http" and drag the HTTP connector to the canvas. 
. Click the green
plus sign (+) next to *Connector Configuration*, and click *OK* in the menu to accept the default values.
. Search for "365" and drag the Microsoft Dynamics 365 connector to the canvas.
Click the green plus sign (+) next to *Connector Configuration* and specify your access credentials.
. Click a connection strategy for authentication:
+
** Microsoft Dynamics 365 OAuth 2.0 Connection
** Microsoft Dynamics 365 OAuth 2.0 Username-Password

=== Configure OAuth 2.0 Connection

This configuration provides access to the Microsoft Dynamics 365 Web API.

=== Configure OAuth 2.0 Username-Password

. Click the green plus sign (+) to the right of *Connector Configuration*.
. Provide the following credentials to enable access to your Microsoft Dynamics 365 server:
+
* *General* tab:
+
[%header,cols="30s,70a"]
|===
|Field |Description
|Client ID |The application ID assigned to your app when you registered it with Azure Active Directory. You can find this in the Azure Portal. Click *Active Directory*, click the directory, choose the application, and click *Configure*.
|Client Secret |The application secret that you created in the app registration portal for your app. This should not be used in a native app, because client secrets cannot be reliably stored on devices. This is required for web apps and web APIs, which have the ability to store the client secret securely on the server side.
|Username |User name used to initialize the session
|Password |Password used to authenticate the user
|Resource |The application ID URI of the web API (secured resource). This must be the root URI, without specifing the CRM version: for example, `+https://YOUR_ORG.crm.dynamics.com/+`.
|Token Request Endpoint |The token endpoint that is called to get the access token: for example, `+https://login.windows.net/TENANT_ID/oauth2/token+`, where TENANT_ID is the Azure Active Directory ID.
|===
+
* *Advanced* tab:
+
[%header,cols="30s,70a"]
|===
|Field |Description
|Read Timeout |The duration in milliseconds that the consumer waits for a response before
timing out. Zero (0) means wait forever.
|Connection Timeout |The duration in milliseconds that the consumer tries to establish a connection before timing out. Zero (0) means wait forever.
|===
+
. Click *Test Connection* to ensure that your credentials are accepted at the server endpoint.
. If present, click *Enable DataSense* to let your application acquire metadata from the server.

== Configure Connector Operations

* <<createop,Create>>
* <<createmultop,Create multiple>>
* <<delop,Delete>>
* <<delmultop,Delete multiple>>
* <<disop,Disassociate>>
* <<doactop,Do action>>
* <<invop,Invoke>>
* <<retop,Retrieve>>
* <<retmultop,Retrieve multiple>>
* <<retmultqop,Retrieve multiple by query>>
* <<upop,Update>>
* <<upmultop,Update multiple>>
* <<unauthop,Unauthorize>>

[[createop]]
=== Create an Entity

. Drag the Create operation to the canvas.
. Specify the Logical Name (required), which is the name of the schema in lowercase.
. Define optional attributes for the default, from a DataWeave expression, or manually set attributes as one or more key and value map pairs.

[[createmultop]]
=== Create Multiple Entities

. Drag the Create Multiple operation to the canvas.
. Specify the Logical Name (required), which is the name of the schema in lowercase.
. Click Use Single Transaction to indicate that if the transaction fails, the transaction is rolled back.
. Add a DataWeave expression for the Logical Name attribute.
. Define optional attributes in a DataWeave Transform component, or manually set attributes as one or more key and value map pairs.

[[delop]]
=== Delete an Entity

. Drag the Delete operation to the canvas.
. Specify a DataWeave expression for the ID field.
. Specify a logical name (required).

[[delmultop]]
=== Delete Multiple Entities

. Drag the Delete Multiple operation to the canvas.
. Specify the Logical Name (required), which is the name of the schema in lowercase.
. Define optional attributes for the default in a DataWeave Transform component, or manually set attributes as one or more key and value map pairs.

[[disop]]
=== Disassociate an Entity

. Drag the Disassociate operation to the canvas.
. Specify the Logical Name (required), which is the name of the schema in lowercase.
. Define optional attributes for the default in a DataWeave Transform component, or manually set attributes as one or more key and value map pairs.

[[doactop]]
=== Do an Action

. Drag the Do Action operation to the canvas.
. Specify the Action Name (required).
. Specify the Bounded Entity ID.
. Specify the Bounded Entity Type.
. Define optional attributes for the default in a DataWeave Transform component, or manually set attributes as one or more key and value map pairs.

[[invop]]
=== Invoke the Web API

. Drag the Invoke operation to the canvas.
. Specify a URI or set a DataWeave Transform component for the Web API.
. Speciy an HTTP method (required): DELETE, GET, PATCH, POST, or PUT.
. Specify the request HTTP headers from the expression or manually.
. Specify the JSON string value (required) that is placed in the body
of the request.

[[retop]]
=== Retrieve an Entity

. Drag the Retrieve operation to the canvas.
. Specify the ID field using a DataWeave Transform component.
. Specify a Logical Name (required).

[[retmultop]]
=== Retrieve Multiple Entities

. Drag the Retrieve Multiple operation to the canvas.
. Specify the Data Query URL or set up a DataWeave Transform component for what to retrieve.
. Specify the Paging Fetch Size in pages to retrieve. The default is 100 pages.

[[retmultqop]]
=== Retrieve Multiple Entities by Query

. Drag the Retrieve Multiple By Query operation to the canvas.
. Specify the query language.
. Configure the Query for what you want to retrieve.
. Specify the Paging Fetch Size in pages to retrieve. The default is 100 pages.

[[unauthop]]
=== Unauthorize Access from a Dynamics 365 Server

. Drag the Unauthorize operation to the canvas.
. Provide the Consumer Key, Consumer Secret, Listener Config, and Callback Path.
. Provide the Authorization URL and Access Token URL that you used to authorize access to the Microsoft Dynamics 365 server.

[[upop]]
=== Update an Entity

. Drag the Update operation to the canvas.
. Specify the  Logical Name (required), which is the name of the schema in lowercase.
. Define optional attributes for the default in a DataWeave Transform component, or manually set attributes as one or more key and value map pairs.

[[upmultop]]
=== Update Multiple Entities

. Drag the Update Multiple operation to the canvas.
. Specify the Logical Name (required), which is the name of the schema in lowercase.
. Click Use Single Transaction to indicate that if the transaction fails it is rolled back.
. Add a DataWeave Transform component to get the Logical Name attribute.
. Define optional attributes for the default or manually set attributes as one or more key and value map pairs.

== Run a Flow

. In Package Explorer, right-click your project's name and click *Run As* > *Mule Application*.
. Check the console to see when the application starts.
You should see messages such as these if no errors occur:

[source,text,linenums]
----
************************************************************
INFO  2019-10-14 22:12:42,003 [main] org.mule.module.launcher.DeploymentDirectoryWatcher:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Mule is up and kicking (every 5000ms)                    +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO  2019-10-14 22:12:42,006 [main] org.mule.module.launcher.StartupSummaryDeploymentListener:
**********************************************************
*  - - + DOMAIN + - -               * - - + STATUS + - - *
**********************************************************
* default                           * DEPLOYED           *
**********************************************************

************************************************************************
* - - + APPLICATION + - -   * - - + DOMAIN + - -  * - - + STATUS + - - *
************************************************************************
* myapp                     * default             * DEPLOYED           *
************************************************************************
----

== Next Step

After configuring the Microsoft Dynamics 365 Connector for use in Studio, see the
xref:microsoft/microsoft-dynamics-365-connector-examples.adoc[Examples] 
topic for more configuration information.

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
