= Microsoft Dynamics 365 - Design Center Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

The Flow Designer feature of Design Center enables you to create apps visually. To use Flow Designer, 
work with your Anypoint Platform administrator to ensure that you have 
a xref:access-management::environments.adoc#to-create-a-new-environment[Design environment]. 
For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour].

To create an app in Flow Designer:

* Configure the input source (trigger) for your app.
* Add the connector as a component to process the input for the app.

For information on Flow Designer field values, see 
the xref:microsoft/microsoft-dynamics-365-connector-reference.adoc[Microsoft Dynamics 365 Connector Reference]. 

// Ensure that the connector reference xref and title are correct.

== Configure the Input Source Trigger

Create an app in Flow Designer based on what input source you want for the app. Microsoft Dynamics 365 Connector enables
you to have your app receive input when objects are created or modified. Alternatively, you can set up an input source using HTTP, or at timed intervals using Scheduler.

. In Design Center, click *Create*.
. Click *Create new application* to open Flow Designer.
. Specify a value for *Project name*, and click *Create*.
. Click *Go straight to canvas* to exit from *Let's get started*. 
. Click the trigger card.
. Select *Microsoft Dynamics 365 Connector* and select your input source as either *On New Object* or *On Modified Object*, and see xref:microsoft/microsoft-dynamics-365-connector.adoc[Required Fields].
. After configuring, click the *Test* button to test the connection.

Design Center automatically saves all changes.

== Configure the Target Component

. Click *+* next to the trigger card.
. In *Select a component*, search for the Microsoft Dynamics 365 Connector.
. Select the connector name. 
. Select an operation for the connector.
. Complete the required fields for the operation.
. Click the *Test* button to test the connection. 

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
