= Validation Module 1.4 - Mule 4
:page-aliases: connectors::validation/validation-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

The Validation module verifies that the content of a message in a Mule flow matches specific criteria. The module provides explicit messages about the cause of an exception in a flow. Based on the specific data you are validating, you can customize the exception message that is displayed in the logs.

If a message does not meet the defined validation criteria, the validation fails and returns a validation error, such as `VALIDATION:INVALID_URL`, which is a `ValidationException`. By default, this message contains customizable text.

== Prerequisites

To use this module, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have access to Anypoint Platform and Anypoint Studio.

== Audience

* New users, read:
** xref:validation-studio-config.adoc[Use Studio to Configure the Module] to create your Mule app
** xref:validation-examples.adoc[Examples], which provide one or more use cases for the connector
* Advanced users, read:
** xref:validation-xml-maven.adoc[XML and Maven Support]
** xref:validation-examples.adoc[Examples], which provides one or more use cases for the connector

== Next Step

After you complete the prerequisites and try the examples, you are ready to create your own app and configure the connector using xref:validation-studio-config.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
