= Troubleshooting Validation Module - Mule 4

To troubleshoot Validation module, become familiar with the information about enabling verbose logging and and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with the Validation module is failing, temporarily enable verbose logging for Validation module. +

Remember to always disable the enhanced verbosity after troubleshooting because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="org.mule.extension.validation" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* VALIDATION:BLANK_STRING

The value provided is an empty String and the expected value is not.

* VALIDATION:NOT_BLANK_STRING

The value provided is not an empty String and the expected value it is.

* VALIDATION:ELAPSED_TIME

Too much time has elapsed since the specified start time.

* VALIDATION:NOT_ELAPSED_TIME

Not enough time has elapsed since the specified start time.

* VALIDATION:INVALID_EMAIL

The value provided is not a valid email address.

* VALIDATION:EMPTY_COLLECTION

The value provided is an empty collection and the expected value is not.

* VALIDATION:NOT_EMPTY_COLLECTION

The value provided is not an empty collection and the expected value is not.

* VALIDATION:INVALID_BOOLEAN

The value provided does not match with the expected boolean value.

* VALIDATION:INVALID_IP

The value provided is not a valid IP address.

* VALIDATION:REJECTED_IP

The value provided is not valid acording the ranges expecting.

* VALIDATION:NULL

The value provided is null. (Keep in mind that the definition of `null` may vary depending on the value's mimeType. For example, for an `application/java` mimeType, `null` means a blank pointer. However, is the mimeType is `application/json` then the String `'null'` is also a null value.)

* VALIDATION:NOT_NULL

The value provided is not null. (Keep in mind that the definition of `null` may vary depending on the value's mimeType. For example, for an `application/java` mimeType, `null` means a blank pointer. However, is the mimeType is `application/json` then the String `'null'` is also a null value.)

* VALIDATION:INVALID_NUMBER

The value provided does not satisfy the number type or the minimum or maximum expected values.

* VALIDATION:INVALID_TIME

The value provided is not a valid time for the pattern used to parse it. If no pattern is provided, then the locale's default will be used.

* VALIDATION:INVALID_URL

The value provided  is not a valid url.

* VALIDATION:MISMATCH

The value provided is not match with the regular expression.

* VALIDATION:INVALID_SIZE

The value provided is not between the specificied inclusive boundaries.

* VALIDATION:MULTIPLE

It summarizes all of the found errors in a list of nested validation operations. 

== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:validation-documentation.adoc[Validation Module Reference]
