= SAP S/4HANA for SOAP - XML and Maven Support - Mule 4
:page-aliases: connectors::sap/sap-s4hana-soap-connector-xml-maven.adoc

If you manually code a Mule app in XML either from the Anypoint Studio XML editor
or from a text editor, you can get access to the connector in your app by adding
reference statements to your XML Mule flow and in the Apache Maven POM file.

[NOTE]
====
You can avoid the manual process described in this topic by using Studio. When
you install the connector in Anypoint Studio, Studio automatically populates
the XML code with the connector's namespace and schema location, and adds a
dependency to the pom.xml file.
====

== Add a Namespace for the Connector

Paste the following code inside the `mule` tag of the header
of your configuration XML:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/s4hana-soap
http://www.mulesoft.org/schema/mule/s4hana-soap/current/mule-s4hana-soap.xsd
----

This example shows how the namespace statements are placed in the XML:

[source,xml,linenums]
----
<mule xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
xmlns:s4hana-soap="http://www.mulesoft.org/schema/mule/s4hana-soap"
xmlns:http="http://www.mulesoft.org/schema/mule/http"
xmlns="http://www.mulesoft.org/schema/mule/core"
xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core
http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http
http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/s4hana-soap
http://www.mulesoft.org/schema/mule/s4hana-soap/current/mule-s4hana-soap.xsd
http://www.mulesoft.org/schema/mule/ee/core
http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd">
----

== Add a POM File Dependency

The pom.xml Apache Maven file generated by Anypoint Studio contains dependencies
for a Mule app. When you code a Mule app manually, include this XML snippet in
your POM file to enable access to this connector:

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-sap-s4hana-soap-cloud-connector</artifactId>
  <version>x.x.x</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

Verify that the connector `version` corresponds to the one you are using.

To obtain the most up-to-date `pom.xml` file information:

. Go to https://www.mulesoft.com/exchange/[Anypoint Exchange].
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for `SAP S/4HANA SOAP`.
. Click *Dependency Snippets*.

== Next Step

After completing your namespace and pom.xml file, you can try
the xref:sap-s4hana-soap-connector-examples.adoc[Examples].

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
