= Kerberos Module Reference 
:page-aliases: connectors::kerberos/kerberos-documentation.adoc

Kerberos Module v1.1

NOTE: Requires Mule 4.10 or later and Mule HTTP Connector 1.11 or later.

Kerberos Module adds Kerberos (SPNEGO) proxy authentication support for the Mule HTTP Connector only.
IMPORTANT: The Kerberos module adds only proxy authentication. It does not implement request-based Kerberos authentication for HTTP requests.

== Configuration

[[proxy-authentication]]
=== Kerberos Proxy Authentication (proxy-authentication)

Kerberos proxy authentication configuration for the Mule HTTP Connector. Supports using the Kerberos ticket cache or a keytab file for authenticating outbound HTTP traffic via a proxy.

==== Parameters
[%header,cols="20s,20a,35a,20a,5a"]
|===
| Name | Type | Description | Default Value | Required
| Host | String | Proxy host. |  | x
| Port | Number | Proxy port. |  | x
| Principal | String | Kerberos principal (for example, `user@EXAMPLE.COM`). |  | x
| Realm | String | Kerberos realm (for example, `EXAMPLE.COM`). |  | x
| Use Ticket Cache | Boolean | Whether to use the local Kerberos ticket cache for authentication. | true | 
| Keytab Path | String | Path to a keytab file to obtain credentials when not using a ticket cache. |  | 
| Non Proxy Hosts | String | Hosts that should be reached directly, bypassing the proxy. |  | 
| Service Type | String | Kerberos service type used to build the SPN. | HTTP | 
|===

==== XML Example
[source,xml,linenums]
----
<mule xmlns:kerberos="http://www.mulesoft.org/schema/mule/kerberos"
      xmlns:http="http://www.mulesoft.org/schema/mule/http"
      xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
                          http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
                          http://www.mulesoft.org/schema/mule/kerberos http://www.mulesoft.org/schema/mule/kerberos/current/mule-kerberos.xsd">

  <http:request-config name="httpCfg">
    <http:proxy-config>
      <kerberos:proxy-authentication
          host="proxy.example.com"
          port="8080"
          principal="user@EXAMPLE.COM"
          realm="EXAMPLE.COM"
          useTicketCache="false"
          serviceType="HTTP"/>
    </http:proxy-config>
  </http:request-config>

</mule>
----

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
