= List Files Using the SFTP Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The List operation returns a List of Messages, where each message represents any file or folder found within the Directory Path (`directoryPath`).

By default, the operation does not read or list files or folders within any sub-folders of `directoryPath`.

To list files or folders within any sub-folders, you can set the `recursive` parameter to `true`.

This example lists all messages in a `directoryPath`, without listing the contents of any sub-folders. Note that the path can be absolute, or it can be relative to a Working Directory (`workingDir`) set in the File configuration (through `<sftp:config/>`).

[source,xml,linenums]
----
<flow name="list">
  <sftp:list directoryPath="~/dropFolder" />
  <foreach>
    <choice>
      <when expression="#[attributes.directory]">
        <flow-ref name="processDirectory" />
      </when>
      <otherwise>
        <logger message="Found file #[attributes.path] which content is #[payload]" />
      </otherwise>
    </choice>
  </foreach>
</flow>
----

The example above lists the contents of a folder, then uses the For Each and Choice components to handle each directory in the list differently than it handles each file.

== Poll a Directory

Poll a directory to look for new files to process. Because Mule 4 no longer has a polling message source (like the Mule 3 transport did), you can poll in Mule 4 by combining a `<scheduler />` element with the `<sftp:list>` element.

[source,xml,linenums]
----
<flow name="poll">
  <scheduler>
      <scheduling-strategy>
          <fixed-frequency frequency="1000"/>
      </scheduling-strategy>
  </scheduler>
  <sftp:list directoryPath="~/dropFolder" />
  <foreach>
      <flow-ref name="processFile" />
      <sftp:delete path="#[attributes.path]" />
  </foreach>
</flow>
---- 

In this example, a flow lists the contents of a folder once per second. The flow then processes the files one by one and after processing, deletes each file. 

Note: Unlike the Mule 3 transport which automatically deleted or moved the file when the flow ended, now you have to manually do that. This gives a much higher level of control, especially in failure scenarios. You can also choose to do more things just as moving, renaming, sending to an external system, etc, and even change the behavior depending on other conditions or failures.

== Match Filter 

When listing files there is the need to only consider files that match a certain criteria. 

For that, the `<sftp:matcher>` element exists. This element defines the possible criteria to use to either accept or reject a file. 

Matcher definition:
 
[source,xml,linenums]
----
<sftp:matcher
filename-pattern="a?*.{htm,html,pdf}"
path-pattern="a?*.{htm,html,pdf}"
createdSince="2019-06-03T13:21:58+00:00"
createdUntil="2019-07-03T13:21:58+00:00"
updatedSince="2019-05-03T13:21:58+00:00"
updatedUntil="2019-06-03T13:21:58+00:00"
accessedSince="2019-06-03T13:21:58+00:00"
accessedUntil="2019-06-03T13:21:58+00:00"
directory="true|false"
regularFile="true|false"
symbolicLink="true|false"
minSize="0"
maxSize="1024" />
----

All these attributes are optional and all are ignored if not provided. Also, they all relate to each other under an AND operator. 

Individual attributes:

* accessedSince: Inclusive lower boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* accessedUntil: Inclusive upper boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* createdSince: Inclusive lower boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* createdUntil: Inclusive upper boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* directory: Match only if the file is a directory.
* filename-pattern: Similar to the current filename pattern filter but more powerful. Glob expressions and regex are supported. Glob is the default. You can select which one to use by setting a prefix. For example: `glob:*.{java, js}` , regex:`[0-9]_test.csv`
* maxSize: Inclusive upped boundary for the file size expressed in bytes.
* minSize: Inclusive lower boundary for the file size expressed in bytes.
* path-pattern: Same as filename-pattern but applies over the entire file path. Not just a filename.
* regularFile: Match only if the file is a regular file.
* symbolicLink: Match only if the file is a symbolic link.
* updatedSince: Inclusive lower boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* updatedUntil: Inclusive upper boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.

The file matcher can either be used as a named top level elemen, allowing it to be reused, or as an inner element proprietary to a particular component. 

For example, here are the two ways of using it: 

* Example of top level, reusable matcher (not available in Flow Designer):
+
[source,xml,linenums]
----
<sftp:matcher name="smallFileMatcher" maxSize="100" />
      <flow name="smallFiles">
      <sftp:list path="~/smallfiles" matcher="smallFileMatcher" />
      ...
</flow>
---- 
+
* Example of inner, not reusable, matcher:
+
[source,xml,linenums]
----
<flow name="smallFiles">
      <sftp:list path="~/smallfiles" matcher="smallFileMatcher">
            <ftp:matcher maxSize="100" />
      </sftp:list>
      ...
</flow>
----

For more on the capabilities of the matcher, see xref:sftp/sftp-documentation.adoc[SFTP Connector Documentation Reference].

//== STREAMING INCLUDE in File, FTP, and SFTP Connector docs
include::partial$common-streaming.adoc[]