= List Files Using the SFTP Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The `list` operation returns a list of messages, where each message represents any file or folder found within the directory path (`directoryPath`).

By default, the operation does not read or list files or folders within any sub-folders of `directoryPath`.

To list files or folders within any sub-folders, you can set the `recursive` parameter to `true`.

Set the path in the file configuration (through `<sftp:config/>`). The path can be absolute, or it can be relative to a working directory (`workingDir`). 

The following example lists the contents of a folder and all messages in a `directoryPath`, without listing the contents of any of the sub-folders. The `<foreach>` and `<choice>` components handle each directory in the list differently from the way it handles each file.

[source,xml,linenums]
----
<flow name="list">
  <sftp:list directoryPath="~/dropFolder" />
  <foreach>
    <choice>
      <when expression="#[attributes.directory]">
        <flow-ref name="processDirectory" />
      </when>
      <otherwise>
        <logger message="Found file #[attributes.path] which content is #[payload]" />
      </otherwise>
    </choice>
  </foreach>
</flow>
----

== Poll a Directory

Poll a directory to look for new files to process. Because Mule 4 no longer has a polling message source (like the Mule 3 transport did), you can poll in Mule 4 by combining a `<scheduler />` element with the `<sftp:list>` element.

[source,xml,linenums]
----
<flow name="poll">
  <scheduler>
      <scheduling-strategy>
          <fixed-frequency frequency="1000"/>
      </scheduling-strategy>
  </scheduler>
  <sftp:list directoryPath="~/dropFolder" />
  <foreach>
      <flow-ref name="processFile" />
      <sftp:delete path="#[attributes.path]" />
  </foreach>
</flow>
----

In the above example, a flow lists the contents of a folder once per second. The flow then processes the files one by one and deletes each file after it is processed.

In Mule 4 (unlike in Mule 3), you have to manually delete or move files when the flow ends, which gives you a much higher level of control, especially in failure scenarios. You can also do more things such as moving, renaming, sending to an external system, and other actions, as well as change the behavior, depending on other conditions or failures.

== Match Filter

When listing files, use the `<sftp:matcher>` element so that only files that match a certain criteria are considered. This element defines the possible criteria to use to either accept or reject a file.

Matcher definition:

[source,xml,linenums]
----
<sftp:matcher
filenamePattern="a?*.{htm,html,pdf}"
path-pattern="a?*.{htm,html,pdf}"
createdSince="2019-06-03T13:21:58+00:00"
createdUntil="2019-07-03T13:21:58+00:00"
updatedSince="2019-05-03T13:21:58+00:00"
updatedUntil="2019-06-03T13:21:58+00:00"
accessedSince="2019-06-03T13:21:58+00:00"
accessedUntil="2019-06-03T13:21:58+00:00"
directory="true|false"
regularFile="true|false"
symbolicLink="true|false"
minSize="0"
maxSize="1024" />
----

=== Individual Attributes

Individual attributes are optional and are ignored if not provided.  You can use an `AND` operator to combine individual attributes. 

* `accessedSince` +
Inclusive lower boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* `accessedUntil` + 
Inclusive upper boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* `createdSince` +
Inclusive lower boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* `createdUntil` +
Inclusive upper boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* `directory` +
Match only if the file is a directory.
* `filenamePattern` +
Similar to the current filename pattern filter but more powerful. Glob expressions (default) and regex are supported. You can select which one to use by setting a prefix. For example: `glob:*.{java, js}` or `regex:[0-9]test.csv`. 
* `maxSize` +
Inclusive upper boundary for the file size expressed in bytes.
* `minSize` +
Inclusive lower boundary for the file size expressed in bytes.
* `path-pattern` + 
Same as filenamePattern but applies over the entire file path. Not just a filename.
* `regularFile` +
Match only if the file is a regular file.
* `symbolicLink` +
Match only if the file is a symbolic link.
* `updatedSince` + 
Inclusive lower boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* `updatedUntil` + 
Inclusive upper boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.

You can use the file matcher as either a named top level element, which allows it to be reused, or as an inner element that is proprietary to a particular component.

=== Top Level, Reusable Matcher

This is an example of top level, reusable matcher (not available in Flow Designer):

[source,xml,linenums]
----
<sftp:matcher name="smallFileMatcher" maxSize="100" />
      <flow name="smallFiles">
      <sftp:list path="~/smallfiles" matcher="smallFileMatcher" />
      ...
</flow>
----

=== Inner, Non Reusable Matcher

This is an example of inner, non reusable, matcher:

[source,xml,linenums]
----
<flow name="smallFiles">
      <sftp:list path="~/smallfiles" matcher="smallFileMatcher">
            <ftp:matcher maxSize="100" />
      </sftp:list>
      ...
</flow>
----

For more information about the capabilities of the matcher, see xref:sftp/sftp-documentation.adoc[SFTP Connector Documentation Reference].

//== STREAMING INCLUDE in File, FTP, and SFTP Connector docs
include::partial$common-streaming.adoc[]
