= About the SFTP Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: SFTP, connector, matcher, directory, listener
:toc:
:toc-title:

Release Notes: xref:release-notes::connector/connector-sftp.adoc[SFTP Connector Release Notes]

The SFTP connector provides access to files and folders on a SFTP server. Its main features include:

// INCLUDE FOR file, ftp, and sftp connectors
include::{partialsdir}/common-file-actions.adoc[]

[[connection_settings]]
== Connecting to an SFTP Server

You set up a connection through an `sftp:config` element, for example:

[source,xml,linenums]
----
<sftp:config name="ftp">
  <sftp:connection username="anonymous" password="password"
    host="localhost" port="${ftpPort}"
    workingDir="${workingDir}"/>
</sftp:config>
----

The `workingDir` provides the path to a directory that is treated as the root of every relative path used with this connector. If the directory is not provided, the remote server’s default serves as the working directory.
The `username`, `password`, `host`, and `port` attributes are self explanatory.

// Included in FTP, SFTP
include::{partialsdir}/common-dynamic-connections.adoc[]

The next is example is identical to the previous one, except that it uses an SFTP Write operation.

.Example: Using SFTP Write
[source,xml,linenums]
----
<sftp:config name="ftp"> // <1>
  <sftp:connection host="#[payload.host]" username="#[payload.user]" password="#[payload.password]" />
</sftp:config>

<flow name="ftpMultitenant" >
  <http:listener config-ref="HTTP_Listener_config" path="/multitenant"/> // <2>
  <set-variable variableName="content" value="#[payload]" />
  <file:read path="recipients.csv" outputMimeType="application/csv" /> // <3>

  <foreach> // <4>
    <sftp:write path="demo.txt" config-ref="ftp"> // <5>
      <sftp:content>#[vars.content]</sftp:content>
    </sftp:write>
  </foreach>

  <set-payload value="Multicast OK"/>
</flow>
----

// Notes on Mule 4 behavior (for Mule 3 users):
//INCLUDED IN FTP, SFTP
include::{partialsdir}/common-note-mule4.adoc[]

//INCLUDED IN FTP, SFTP, FILE
include::{partialsdir}/common-file-attributes.adoc[]

[[see_also]]
== See Also

xref:sftp/sftp-documentation.adoc[SFTP Connector Documentation Reference]

xref:sftp/sftp-read.adoc[To Read Files]

xref:sftp/sftp-write.adoc[To Write Files]

xref:sftp/sftp-list.adoc[To List Files]

xref:sftp/sftp-on-new-file.adoc[To Listen for New or Modified Files]

xref:sftp/sftp-copy-move.adoc[To Copy or Move Files]