= To Copy and Move Files with the SFTP connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The connector also provides the ability to copy and move files or directories on demand.

[source,xml,linenums]
----
<sftp:copy sourcePath="source.txt"
  targetPath="backup" overwrite="true|false"
  createParentDirectories="true|false"
  renameTo="renamed.txt"/>
<sftp:move sourcePath="source.txt"
  targetPath="backup"  overwrite="true|false"
  createParentDirectories="true|false"
  renameTo="renamed.txt"/>
----

Notice the `targetPath` and `renameTo` parameters:

* `targetPath` is the path to the directory into which the file is to be copied or moved. This path must point to a directory.

* `renameTo` is an optional parameter that renames the file as part of the operation. This parameter must be a file name, not a path. If this attribute is not provided, the original file name is retained.

[[createdir]]
== Create Directory

This operation simply creates a directory of a given name. If the reason for creating the directory is to immediately after write, copy or move contents to it, then use the write, copy, or move operations with the `createParentDirectories=true` parameter.

For a complete description of the parameters, return type and errors, see the SFTP xref:sftp-documentation.adoc#createDirectory[Create Directory Operation].

== See Also

* xref:sftp-documentation#copy[SFTP Copy Operation]
* xref:sftp-documentation#move[SFTP Move Operation]
* xref:sftp-documentation#write[SFTP Write Operation]
