= About the SFTP Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Release Notes: xref:release-notes::connector/connector-sftp.adoc[SFTP Connector Release Notes]

The SFTP connector provides access to files and folders on a SFTP server. Its main features include:

// INCLUDE FOR file, ftp, and sftp connectors
include::partial$common-file-actions.adoc[]

[[connection_settings]]
== Connecting to an SFTP Server

You set up a connection through an `sftp:config` element, for example:

[source,xml,linenums]
----
<sftp:config name="sftp">
  <sftp:connection username="anonymous" password="password"
    host="localhost" port="${ftpPort}"
    workingDir="${workingDir}"/>
</sftp:config>
----

The `workingDir` provides the path to a directory that is treated as the root of every relative path used with this connector. If the directory is not provided, the remote server’s default serves as the working directory.
The `username`, `password`, `host`, and `port` attributes are self explanatory.

// Included in FTP, SFTP
include::partial$common-dynamic-connections.adoc[]

The next is example is identical to the previous one, except that it uses an SFTP Write operation.

.Example: Using SFTP Write
[source,xml,linenums]
----
<sftp:config name="ftp"> // <1>
  <sftp:connection host="#[payload.host]" username="#[payload.user]" password="#[payload.password]" />
</sftp:config>

<flow name="ftpMultitenant" >
  <http:listener config-ref="HTTP_Listener_config" path="/multitenant"/> // <2>
  <set-variable variableName="content" value="#[payload]" />
  <file:read path="recipients.csv" outputMimeType="application/csv" /> // <3>

  <foreach> // <4>
    <sftp:write path="demo.txt" config-ref="ftp"> // <5>
      <sftp:content>#[vars.content]</sftp:content>
    </sftp:write>
  </foreach>

  <set-payload value="Multicast OK"/>
</flow>
----

// Notes on Mule 4 behavior (for Mule 3 users):
//INCLUDED IN FTP, SFTP
include::partial$common-note-mule4.adoc[]

//INCLUDED IN FTP, SFTP, FILE
include::partial$common-file-attributes.adoc[]

== Poll a Directory

Poll a directory to look for new files to process. Because Mule 4 no longer has a polling message source (like the old Mule 3 transport did), you can achieve poll by combining a `<scheduler />` element with the `<sftp:list>` element.

[source,xml,linenums]
----
<flow name="poll">
  <scheduler>
      <scheduling-strategy>
          <fixed-frequency frequency="1000"/>
      </scheduling-strategy>
  </scheduler>
  <sftp:list directoryPath="~/dropFolder" />
  <foreach>
<sflow-ref name="processFile" />
<sftp:delete path="#[attributes.path]" />
</foreach>
</flow>
---- 

In this example a flow lists the contents of a folder once per second. It processes the files one by one and then deletes each processed file. 

Note: Unlike the old Mule 3 transport which automatically deleted or moved the file when the flow ended, now you have to manually do that. This gives a much higher level of control, especially in failure scenarios. You could even choose to do more things just as moving, renaming, sending to an external system, etc, and even change that behavior depending on other conditions or failures.

== Match Filter 

Another common scenario when listing files, is the need for only consider files which match with certain criteria. 

For that, a `<sftp:matcher>` element exists. This element defines the possible criteria to use to either accept or reject a file. 

Matcher definition:
 
[source,xml,linenums]
----
<sftp:matcher
filename-pattern="a?*.{htm,html,pdf}"
path-pattern="a?*.{htm,html,pdf}"
createdSince="2019-06-03T13:21:58+00:00"
createdUntil="2019-07-03T13:21:58+00:00"
updatedSince="2019-05-03T13:21:58+00:00"
updatedUntil="2019-06-03T13:21:58+00:00"
accessedSince="2019-06-03T13:21:58+00:00"
accessedUntil="2019-06-03T13:21:58+00:00"
directory="true|false"
regularFile="true|false"
symbolicLink="true|false"
minSize="0"
maxSize="1024" />
----

All these attributes are optional and all are ignored if not provided. Also, they all relate to each other under an AND operator. 

Individual attributes:

* accessedSince: Inclusive lower boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* accessedUntil: Inclusive upper boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* createdSince: Inclusive lower boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* createdUntil: Inclusive upper boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* directory: Match only if the file is a directory.
* filename-pattern: Similar to the current filename pattern filter but more powerful. Glob expressions and regex are supported. Glob is the default. You can select which one to use by setting a prefix. For example: `glob:*.{java, js}` , regex:`[0-9]_test.csv`
* maxSize: Inclusive upped boundary for the file size expressed in bytes.
* minSize: Inclusive lower boundary for the file size expressed in bytes.
* path-pattern: Same as filename-pattern but applies over the entire file path. Not just a filename.
* regularFile: Match only if the file is a regular file.
* symbolicLink: Match only if the file is a symbolic link.
* updatedSince: Inclusive lower boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.
* updatedUntil: Inclusive upper boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.

The file matcher can either be used as a named top level elemen, allowing it to be reused, or as an inner element proprietary to a particular component. 

For example, here are the two ways of using it: 

Example of top level, reusable matcher (not available in Flow Designer):
 
[source,xml,linenums]
----
<sftp:matcher name="smallFileMatcher" maxSize="100" />
<sflow name="smallFiles">
<sftp:list path="~/smallfiles" matcher="smallFileMatcher" />
...
</flow>
---- 

Example of inner, not reusable, matcher:
 
[source,xml,linenums]
----
<flow name="smallFiles">
<sftp:list path="~/smallfiles" matcher="smallFileMatcher">
<sftp:matcher maxSize="100" />
</sftp:list>
...
</flow>
----

[[see_also]]
== See Also

xref:sftp/sftp-documentation.adoc[SFTP Connector Documentation Reference]

xref:sftp/sftp-read.adoc[To Read Files]

xref:sftp/sftp-write.adoc[To Write Files]

xref:sftp/sftp-list.adoc[To List Files]

xref:sftp/sftp-on-new-file.adoc[To Listen for New or Modified Files]

xref:sftp/sftp-copy-move.adoc[To Copy or Move Files]
