= Microsoft Power BI Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Microsoft Power BI (Microsoft Power BI Connector) gives you access to the Microsoft Power BI APIs. This connector exposes the most commonly used operations provided by the Microsoft Power BI APIs. 

For compatibility information and fixed issues, see the Microsoft Power BI Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Microsoft Power BI APIs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector




== Authentication Types

Microsoft Power BI Connector connections use the OAuth 2.0 authorization code grant type, which can be used in apps that are installed on a device to gain access to protected resources.


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:microsoft-power-bi-connector-reference.adoc[Microsoft Power BI Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
