= Microsoft Power BI Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Microsoft Power BI (Power BI Connector) synchronizes data and automates business processes between Power BI and third-party applications, either on premises or in the cloud. Power BI is a suite of analytics tools designed to visualize data from various systems and garner insights. 

For compatibility information and fixed issues, see the Microsoft Power BI Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Microsoft Power BI APIs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Common use cases for Power BI Connector include the ability to automate business processes by integrating Power BI with other IT tools and systems in your organization, including:

* Optimizing sales operations by analyzing your sales data (opportunities, leads, and so on) by feeding data from your CRM system to Power BI, and then using Power BI to visualize patterns and identify trends. 
* Getting a complete view of your customer by feeding data streams from all customer data stores (CRM, support, marketing, and so on) to Power BI and using Power BI to see a customer-centric view.
* Increasing customer satisfaction and reducing attrition risk by notifying the relevant customer account team (using Slack, email, or another messaging system) when customer satisfaction drops below the threshold defined in Power BI. 


== Authentication Types

Microsoft Power BI Connector uses the OAuth 2.0 authorization code grant connection type used in apps that are installed on a device to gain access to protected resources.


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:microsoft-power-bi-connector-reference.adoc[Power BI Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
