= Tableau Connector 1.0 Examples - Mule 4

The following examples show how to perform Hyper and Rest configuration operations
with Tableau Connector:

* Hyper configuration operations include:
**

* Rest configuration operations include:
..

== Prerequisites

* Java 8 or 11

* Anypoint Studio 7.5 and later

* Mule runtime engine (Mule) 4.3.0 and later

* DataWeave

== Append to File Upload - Rest Configuration

This Mule flow uploads a block of data and appends it to the data that is
already uploaded. To get an *Upload Session Id*, run the *Initiate file upload*
operation.

Here is what each operation is doing:

* *HTTP Listener* +
Accepts data from HTTP requests
* *Read* +
Reads a file
* *Transform Message* +
Transforms the HTTP input
* *Append to file upload* +
Uploads a block of data and appends it to the data that is already uploaded
* *Transform Message* +
Outputs the results of the *Append to file upload* operation in JSON format

// image

=== XML for This Example

Paste this code into the Studio XML editor to quickly load the flow for this example into your Mule app:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:tableau="http://www.mulesoft.org/schema/mule/tableau" xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns:tableau-specialist="http://www.mulesoft.org/schema/mule/tableau-specialist" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/tableau-specialist http://www.mulesoft.org/schema/mule/tableau-specialist/current/mule-tableau-specialist.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
http://www.mulesoft.org/schema/mule/tableau http://www.mulesoft.org/schema/mule/tableau/current/mule-tableau.xsd">
	<configuration-properties file="project-properties.properties"/>
	<tableau-specialist:tableau-specialist-config name="Tableau_Specialist_Configuration" doc:name="Tableau Specialist Configuration" doc:id="0086ca3c-2ec6-4940-96e5-d319c5d35c15" >
		<tableau-specialist:basic-username-password-connection serverUrl="${credentials.serverUrl}" apiVersion="${credentials.apiVersion}" contentUrl="${credentials.contentUrl}" username="${credentials.username}" password="${credentials.password}" />
	</tableau-specialist:tableau-specialist-config>
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="fa83ce28-e898-4ac9-b524-3fdef2ad15f6" >
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<flow name="tableau-demo-append-to-file-upload" doc:id="4dc68be9-5aeb-4ac0-bb7a-21e0ae9bd60a" >
		<http:listener doc:name="Listener" doc:id="59db6c98-5a3d-4b7e-9a48-618367c27431" config-ref="HTTP_Listener_config" path="/append-to-file-upload"/>
		<file:read doc:name="Read" doc:id="46317ac5-ac57-4481-9872-4e794f9dd95d" config-ref="File_Config" path="customers.hyper" />
		<ee:transform doc:name="Transform Message" doc:id="94e523a5-e86e-482f-a45f-0257c6896247">
			<ee:variables>
				<ee:set-variable variableName="fileContent"><![CDATA[%dw 2.0
output application/java
---
payload]]></ee:set-variable>
			</ee:variables>
		</ee:transform>
		<tableau-specialist:append-to-file-upload doc:name="Append to file upload" doc:id="b9439947-1577-4443-a0bc-1a8583e3a3a8" config-ref="Tableau_Specialist_Configuration" uploadSessionId="Upload session id"/>
		<ee:transform doc:name="Transform Message" doc:id="20359447-a8b0-46a6-8a01-fc708e816557" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
</mule>
----
