= Tableau Connector 1.0 Examples - Mule 4

The following examples show how to perform Hyper and Rest configuration operations
with Tableau Connector:

* Hyper configuration operations include:
**

* Rest configuration operations include:
..

== Prerequisites

* Java 8 or 11

* Anypoint Studio 7.5 and later

* Mule runtime engine (Mule) 4.3.0 and later

* DataWeave

== Append to File Upload - Rest Configuration

This Mule flow uploads a block of data and appends it to the data that is
already uploaded. To get an *Upload Session Id*, run the *Initiate file upload*
operation.

Here is what each operation is doing:

* *HTTP Listener* +
Accepts data from HTTP requests
* *Read* +
Reads a file
* *Transform Message* +
Transforms the HTTP input
* *Append to file upload* +
Uploads a block of data and appends it to the data that is already uploaded
* *Transform Message* +
Outputs the results of the *Append to file upload* operation in JSON format

// image

=== XML for This Example

Paste this code into the Studio XML editor to quickly load the flow for this example into your Mule app:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:tableau="http://www.mulesoft.org/schema/mule/tableau" xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns:tableau-specialist="http://www.mulesoft.org/schema/mule/tableau-specialist" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/tableau-specialist http://www.mulesoft.org/schema/mule/tableau-specialist/current/mule-tableau-specialist.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
http://www.mulesoft.org/schema/mule/tableau http://www.mulesoft.org/schema/mule/tableau/current/mule-tableau.xsd">
	<configuration-properties file="project-properties.properties"/>
	<tableau-specialist:tableau-specialist-config name="Tableau_Specialist_Configuration" doc:name="Tableau Specialist Configuration" doc:id="0086ca3c-2ec6-4940-96e5-d319c5d35c15" >
		<tableau-specialist:basic-username-password-connection serverUrl="${credentials.serverUrl}" apiVersion="${credentials.apiVersion}" contentUrl="${credentials.contentUrl}" username="${credentials.username}" password="${credentials.password}" />
	</tableau-specialist:tableau-specialist-config>
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="fa83ce28-e898-4ac9-b524-3fdef2ad15f6" >
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<flow name="tableau-demo-append-to-file-upload" doc:id="4dc68be9-5aeb-4ac0-bb7a-21e0ae9bd60a" >
		<http:listener doc:name="Listener" doc:id="59db6c98-5a3d-4b7e-9a48-618367c27431" config-ref="HTTP_Listener_config" path="/append-to-file-upload"/>
		<file:read doc:name="Read" doc:id="46317ac5-ac57-4481-9872-4e794f9dd95d" config-ref="File_Config" path="customers.hyper" />
		<ee:transform doc:name="Transform Message" doc:id="94e523a5-e86e-482f-a45f-0257c6896247">
			<ee:variables>
				<ee:set-variable variableName="fileContent"><![CDATA[%dw 2.0
output application/java
---
payload]]></ee:set-variable>
			</ee:variables>
		</ee:transform>
		<tableau-specialist:append-to-file-upload doc:name="Append to file upload" doc:id="b9439947-1577-4443-a0bc-1a8583e3a3a8" config-ref="Tableau_Specialist_Configuration" uploadSessionId="Upload session id"/>
		<ee:transform doc:name="Transform Message" doc:id="20359447-a8b0-46a6-8a01-fc708e816557" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
</mule>
----

== Create Project - Rest Configuration

This Mule flow creates a project on the specified site.

Here is what each operation is doing:

* *HTTP Listener* +
Accepts data from HTTP requests
* *Create project* +
Creates a project on the specified site
* *Transform Message* +
Outputs the results of the *Create project* operation in JSON format

// image

=== XML for This Example

Paste this code into the Studio XML editor to quickly load the flow for this example into your Mule app:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:tableau="http://www.mulesoft.org/schema/mule/tableau" xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns:tableau-specialist="http://www.mulesoft.org/schema/mule/tableau-specialist" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/tableau-specialist http://www.mulesoft.org/schema/mule/tableau-specialist/current/mule-tableau-specialist.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
http://www.mulesoft.org/schema/mule/tableau http://www.mulesoft.org/schema/mule/tableau/current/mule-tableau.xsd">
	<configuration-properties file="project-properties.properties"/>
	<tableau-specialist:tableau-specialist-config name="Tableau_Specialist_Configuration" doc:name="Tableau Specialist Configuration" doc:id="0086ca3c-2ec6-4940-96e5-d319c5d35c15" >
		<tableau-specialist:basic-username-password-connection serverUrl="${credentials.serverUrl}" apiVersion="${credentials.apiVersion}" contentUrl="${credentials.contentUrl}" username="${credentials.username}" password="${credentials.password}" />
	</tableau-specialist:tableau-specialist-config>
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="fa83ce28-e898-4ac9-b524-3fdef2ad15f6" >
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
<flow name="tableau-demo-create-project" doc:id="21de738a-6777-4305-aced-c8ce22f93062" >
		<http:listener doc:name="Listener" doc:id="b189857b-6fbe-4f8b-b50a-274d4f9c738b" config-ref="HTTP_Listener_config" path="/create-project"/>
		<tableau-specialist:create-project doc:name="Create project" doc:id="95f6ddb3-f33b-4f46-a694-5f918766a38f" config-ref="Tableau_Specialist_Configuration">
			<tableau-specialist:content ><![CDATA[#[output application/json
---
{
	project: {
		name: "demo-test",
		description: "demo-description"
	}
}]]]></tableau-specialist:content>
		</tableau-specialist:create-project>
		<ee:transform doc:name="Transform Message" doc:id="1dbb0073-df1a-46db-bde7-7e7157b96572" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
</mule>
----

== Delete Project - Rest Configuration

This Mule flow deletes a project from the specified site. When a project is
deleted, all of its assets are also deleted, such as its associated workbooks,
data sources, project view options, and rights. Use this operation with caution.

Here is what each operation is doing:

* *HTTP Listener* +
Accepts data from HTTP requests
* *Delete project* +
Deletes a project from the specified site
* *Transform Message* +
Outputs the results of the *Delete project* operation in JSON format

// image

=== XML for This Example

Paste this code into the Studio XML editor to quickly load the flow for this example into your Mule app:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:tableau="http://www.mulesoft.org/schema/mule/tableau" xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns:tableau-specialist="http://www.mulesoft.org/schema/mule/tableau-specialist" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/tableau-specialist http://www.mulesoft.org/schema/mule/tableau-specialist/current/mule-tableau-specialist.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
http://www.mulesoft.org/schema/mule/tableau http://www.mulesoft.org/schema/mule/tableau/current/mule-tableau.xsd">
	<configuration-properties file="project-properties.properties"/>
	<tableau-specialist:tableau-specialist-config name="Tableau_Specialist_Configuration" doc:name="Tableau Specialist Configuration" doc:id="cb468146-0f1e-4582-823f-931301fe573e" >
		<tableau-specialist:basic-username-password-connection serverUrl="${credentials.serverUrl}" apiVersion="${credentials.apiVersion}" contentUrl="${credentials.contentUrl}" username="${credentials.username}" password="${credentials.password}" />
	</tableau-specialist:tableau-specialist-config>
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="a5594c7d-a121-4db2-a96b-09b935af2550" >
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<flow name="tableau-demo-delete-project" doc:id="96cf801d-bcae-4f2c-91c2-973feb4eb9bc" >
		<http:listener doc:name="Listener" doc:id="fb1582e1-4445-48c5-b53f-adda3ab50592" config-ref="HTTP_Listener_config" path="/delete-project"/>
		<tableau-specialist:delete-project doc:name="Delete project" doc:id="7e135059-0ccd-4d51-b10d-fc38bc4f304d" config-ref="Tableau_Specialist_Configuration" projectId="Id of the project to be deleted"/>
		<ee:transform doc:name="Transform Message" doc:id="b69f9dd5-9a97-47a3-a7ad-6fae4056d396" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
</mule>
----

== Initiate File Upload - Rest Configuration

This Mule flow initiates the upload process for a file.

Here is what each operation is doing:

* *HTTP Listener* +
Accepts data from HTTP requests
* *Initiate file upload* +
Initiates the upload process for a file
* *Transform Message* +
Outputs the results of the *Initiate file upload* operation in JSON format

// image

=== XML for This Example

Paste this code into the Studio XML editor to quickly load the flow for this example into your Mule app:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:tableau="http://www.mulesoft.org/schema/mule/tableau" xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns:tableau-specialist="http://www.mulesoft.org/schema/mule/tableau-specialist" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/tableau-specialist http://www.mulesoft.org/schema/mule/tableau-specialist/current/mule-tableau-specialist.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
http://www.mulesoft.org/schema/mule/tableau http://www.mulesoft.org/schema/mule/tableau/current/mule-tableau.xsd">
	<configuration-properties file="project-properties.properties"/>
	<tableau-specialist:tableau-specialist-config name="Tableau_Specialist_Configuration" doc:name="Tableau Specialist Configuration" doc:id="6c0dc7f6-facd-4f38-acbe-b598686b2fb6" >
		<tableau-specialist:basic-username-password-connection serverUrl="${credentials.serverUrl}" apiVersion="${credentials.apiVersion}" contentUrl="${credentials.contentUrl}" username="${credentials.username}" password="${credentials.password}" />
	</tableau-specialist:tableau-specialist-config>
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="6dd0ac5f-0a8b-421f-bd81-ceb4f450a792" >
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<flow name="tableau-demo-initiate-file-upload" doc:id="2d565997-700f-4828-b129-ade9777d37f8" >
		<http:listener doc:name="Listener" doc:id="4ca7aa6e-54e6-4b11-b3d9-8cd6c5a35527" config-ref="HTTP_Listener_config" path="/initiate-file-upload"/>
		<tableau-specialist:initiate-file-upload doc:name="Initiate file upload" doc:id="2f6a418d-6122-49f1-83b9-21e37f64a86d" config-ref="Tableau_Specialist_Configuration"/>
		<ee:transform doc:name="Transform Message" doc:id="7e32ae77-622a-4ba8-8b13-5529bbcf5dc1" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
</mule>
----

== Publish Datasource - Rest Configuration

This Mule flow publishes a data source onto the specified site, or appends data
onto an existing data source. You can use *customers.hyper* as an example
datasource to upload.

Here is what each operation is doing:

* *HTTP Listener* +
Accepts data from HTTP requests
* *Initiate file upload* +
Initiates the upload process for a file
* *Transform Message* +
Outputs the results of the *Initiate file upload* operation in JSON format

// image

=== XML for This Example

Paste this code into the Studio XML editor to quickly load the flow for this example into your Mule app:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:tableau="http://www.mulesoft.org/schema/mule/tableau" xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns:tableau-specialist="http://www.mulesoft.org/schema/mule/tableau-specialist" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/tableau-specialist http://www.mulesoft.org/schema/mule/tableau-specialist/current/mule-tableau-specialist.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
http://www.mulesoft.org/schema/mule/tableau http://www.mulesoft.org/schema/mule/tableau/current/mule-tableau.xsd">
	<configuration-properties file="project-properties.properties"/>
	<tableau-specialist:tableau-specialist-config name="Tableau_Specialist_Configuration" doc:name="Tableau Specialist Configuration" doc:id="6c0dc7f6-facd-4f38-acbe-b598686b2fb6" >
		<tableau-specialist:basic-username-password-connection serverUrl="${credentials.serverUrl}" apiVersion="${credentials.apiVersion}" contentUrl="${credentials.contentUrl}" username="${credentials.username}" password="${credentials.password}" />
	</tableau-specialist:tableau-specialist-config>
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="6dd0ac5f-0a8b-421f-bd81-ceb4f450a792" >
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<flow name="tableau-demo-initiate-file-upload" doc:id="2d565997-700f-4828-b129-ade9777d37f8" >
		<http:listener doc:name="Listener" doc:id="4ca7aa6e-54e6-4b11-b3d9-8cd6c5a35527" config-ref="HTTP_Listener_config" path="/initiate-file-upload"/>
		<tableau-specialist:initiate-file-upload doc:name="Initiate file upload" doc:id="2f6a418d-6122-49f1-83b9-21e37f64a86d" config-ref="Tableau_Specialist_Configuration"/>
		<ee:transform doc:name="Transform Message" doc:id="7e32ae77-622a-4ba8-8b13-5529bbcf5dc1" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
</mule>
----
