= Zendesk Connector 1.0 Examples - Mule 4

////
While each example differs, all connector examples should have the following components:

An introductory paragraph that states what the example depicts. This paragraph should explicitly state why the example is helpful to the audience, and it can provide other necessary contextual information.

A screenshot of each Studio flow that the user is creating

Step-by-step instructions for creating the example in Studio

The resulting XML that users can paste into the Studio XML editor. You must remove the  attributes from the XML before including it in the topic.

If the example contains multiple flows or is long and complex, break up the example into subsections that reflect logical chunks of functionality. For example, the Apache Kafka Connector Examples topic shows how to publish a message for Apache Kafka and then retrieve it. It has one subsection for each flow plus one for the XML:

Create the Producer Flow
Create the Consumer Flow
XML for Consuming and Publishing a Topic

The Amazon SQS Connector Examples topic also contains two flows: one for publishing an Amazon SQS topic and one for consuming the published topic. However, the first flow consists of many components. This topic breaks up the first flow into additional subsections:

Create a Flow to Send a Message
Add a Transform Message Component to Attach the Metadata
Add and Configure the SQS Send Message Operation
Add a Logger Component to Display the Response in the Mule Console
Obtain the Number of Messages in the Queue
Add a Logger to Display the Number in the Mule Console
Create a Flow to Receive Messages
Example Mule Application XML Code

If your Examples topic contains multiple examples, create a hyperlinked list of examples in the topic introduction, as shown in the Template for Creating Multiple Examples in One Examples Topic, or use the Template for Using Multiple Examples Topics.
////

// Put Examples here -- You may need to obtain these from the
// code repo /demo folder.

Template for a Single Example

// Use this template to include a single example in the Examples topic.
// For examples of this template, see Amazon SQS Connector Examples and Apache Kafka Connector Examples.

= <connector> Example - Mule 4

<Introductory text>
The following text can be in the same paragraph as the introductory text or in a separate paragraph, depending on the introductory paragraph length.
This example uses variables for some field values. You can either:
Replace the variables with their values in the code.
Provide the values for each variable in a properties file and then refer to that file from the connector configuration.
If you don't know how to use a properties file, see Configuring Property Placeholders.
Use subsections, if needed, to show the configuration steps.
== Subsection 1
== Subsection 2
== Subsection 3
.
.
.

// Add these steps to the end of the numbered list:
. Save the project.
. Test the app by sending a <REST command> request to <url>.

== XML for <what the example shows>

Paste this code into the Studio XML editor to quickly load the flow for this example into your Mule app:

// <Copy the XML from Studio and paste it here.
// Remove the  attributes from the XML before including it in the topic.>

// If you aren't splitting the example into subsections, add these subsections instead:

== Steps for <what the example shows>

// Add these steps to the end of the numbered list:
. Save the project.
. Test the app by sending a <REST command> request to <url>.

== XML for <what the example shows>

Paste this code into your Studio XML editor to quickly load the flow for this example into your Mule app:

// <Copy the XML from Studio and paste it here.
// Remove the  attributes from the XML before including it in the topic.>

Template for Including Multiple Examples in One Examples Topic

// Use this template under one of these circumstances to include multiple examples in the
// Examples topic:

// The examples are related.
// There are only a few examples and the documentation for each one is fairly short.

////
For an example of this template, see NetSuite Connector 10.0 Examples - Mule 4. Consider using the Template for Including Multiple Examples in One Examples Topic if you have multiple, unrelated examples.
////

= <connector> Examples - Mule 4

The following examples show how to <action> with <connector-name>:

<Hyperlink 1>
<short description of the example>
<Hyperlink 2>
<short description of the example>
.
.
.
These examples use variables for some field values. You can either:
Replace the variables with their values in the code
Provide the values for each variable in a properties file and then refer to that file from the connector configuration.
If you don't know how to use a properties file, see Configuring Property Placeholders.

== <Example 1>

// Use subsections, if needed, to show configuration steps.
=== Subsection 1
=== Subsection 2
=== Subsection 3
.
.
.
// Add these steps to the end of the numbered list:
. Save the project.
. Test the app by sending a <REST command> request to <url>.

=== XML for <what the example shows>

Paste this code into the Studio XML editor to quickly load the flow for this example into your Mule app:

// <Copy the XML from Studio and paste it here.
// Remove the  attributes from the XML before including it in the topic.>

// If you aren't splitting the example into subsections, add these subsections instead:

=== Steps for <what the example shows>

// Add these steps to the end of the numbered list:
. Save the project.
. Test the app by sending a <REST command> request to <url>.

=== XML for <what the example shows>

Paste this code into your Studio XML editor to quickly load the flow for this example into your Mule app:

// <Copy the XML from Studio and paste it here.
// Remove the  attributes from the XML before including it in the topic.>

== <Example 2>

// Same template for Example 1

== <Example 3>
.
.
.

== See Also

* xref:connectors::introduction/anypoint-connector-authentication.adoc[Anypoint Connector Authentication]
* https://help.mulesoft.com[MuleSoft Help Center]
