= LDAP Connector 3.4 - Mule 4
:page-aliases: connectors::ldap/ldap-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Lightweight Directory Access Protocol (LDAP) is a public standard that facilitates maintenance and access to distributed directories (such as network user privilege information) over an Internet Protocol (IP) network.

This version of the connector supports both LDAP over SSL and LDAP over TLS.

Many LDAP servers are included in free-use open source projects and packages. The particulars of installing, running and configuring LDAP servers fall outside the scope of this document.

For information about compatibility and fixed issues, see the LDAP Connector Release Notes

[[prerequisites]]
== Prerequisites

To use this connector, you must be familiar with:

* The LDAP Connector’s API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access an OpenLDAP instance that supports LDAP v3
* Anypoint Platform
* Anypoint Studio version 7.0 or later

== Common Use Cases For the Connector

Common use cases for LDAP Connector include:

* Adding user accounts to Active Directory
+
You can add business users to Active Directory groups defined on the base DN.
+
* Retrieving user attributes
+
You can retrieve basic attributes of a business user such as the user's e-mail or phone number.

== Connection types

LDAP Connectors connections use the following authentication types:

* Basic
+
Uses a username and password for authentication
+
* SSL
+
Uses the Secure Sockets Layer (SSL) to provide authentication
* TLS
+
Uses Transport Layer Security (TLS) to provide

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:ldap-connector-reference.adoc[LDAP Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
