= LDAP 3.5 Additional Configuration Information  - Mule 4

Read this topic to learn how to configure LDAP over SSL and LDAP over TLS.

== Configure LDAP over SSL

To configure LDAP over SSL, use Anypoint Studio to set up an SSL connection in the LDAP global element:

. In the *Connection* field of the global element, select `SSL Configuration`.
. Complete the required fields.

Connect to SLS using port 636.

== Configure LDAP over TLS

To configure LDAP over TLS, use Studio to set up a TLS connection in the LDAP global element:

. In the *Connection* field of the global element, select `TLS Configuration`.
. Select the Advanced Tab.
. In the *Extended configurations* field, select *Edit inline* and then add the `org.mule.module.ldap.trustStorePath` and `org.mule.module.ldap.trustStorePassword` key values.
. Ensure that the native LDAP pooling functionality is turned off. For example if using JNDI, do not use attributes such as `com.sun.jndi.ldap.connect.pool=true`, which causes problems when using TLS.

Connect to TLS using port 389. Use `ldap` instead of of `ldaps` in the associated URL.

For an example of configuring a TLS connection, see xref:ldap-connector-examples.adoc#set-up-common-truststore[Setting up a Common Truststore].

== Next Step

After you complete configuring the connector, you can try the xref:ldap-connector-examples.adoc[LDAP Connector Examples].

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
