= LDAP Connector 3.4 Additional Configuration Information - Mule 4

== Configuring LDAP over SSL

To configure LDAP over SSL, set up an SSL connection in the LDAP global element:
. In the *Connection* field of the global element, select `SSL Configuration`.
. Complete the required fields.

== Configuring LDAP over TLS

To configure LDAP over TLS, set up a TLS connection in the LDAP global element:

. Complete the required fields.
. Select the Advanced Tab.
. In the *Extended configurations* field, select *Edit inline* and then add the `org.mule.module.ldap.trustStorePath` and `org.mule.module.ldap.trustStorePassword` keys.

Use port 389 only.
Use `ldap` of `ldaps` in the associated URL.

For an example of configuring a TLS connection, see xref:ldap-connector-examples.adoc#set-up-common-truststore[Setting up a Common Truststore].

== Next Step

After you complete configuring the connector, you can try the xref:ldap-connector-examples.adoc[LDAP Connector Examples].

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
