
= Dynamics 365 For Operations - How to handle enums

In 3.1.7 version of Dynamics 365 for operations connector a custom logic has been introduced to handle complex types when creating entities.

== How it was done before

The following code snippet is a payload for the 'Create' operation.

[source,json,linenums]
----
%dw 2.0
output application/java
---
{
    "Name": "GENERIC-CUSTOMER-NAME",
    "CustomerAccount": "CUSTOMER-ACCOUNT",
    "SalesCurrencyCode": "EUR",
    "CustomerGroupId": "GROUP-ID",
    "IsServiceDeliveryAddressBased": "No"
}
----

In this case, 'IsServiceDeliveryAddressBased' property is of type 'Microsoft.Dynamics.DataEntities.NoYes'. This is a complex object in Microsoft data model of type Enum.
Using this payload in the 'Create' operation will result in an exception being raised because the value 'No' is sent as String instead of Enum type.

The solution for this is to use the newly added logic.
[source,json,linenums]
----
%dw 2.0
output application/java
---
{
    "Name": "GENERIC-CUSTOMER-NAME",
    "CustomerAccount": "CUSTOMER-ACCOUNT",
    "SalesCurrencyCode": "EUR",
    "CustomerGroupId": "GROUP-ID",
    "IsServiceDeliveryAddressBased": {
            "muleAdditions": {
                "kind": "enum",
                "type": "Microsoft.Dynamics.DataEntities.NoYes"
            },
            "value" : "No"
        }
}
----

The value for 'IsServiceDeliveryAddressBased' has to be an object type this time and it should contain the following:

. The key "value" and the actual value of the enum as String based on the enum type.
. The object "muleAdditions" with its two keys "kind" and "type"
.. kind - the kind of complex object that should be handled.
.. type - the actual type in the Microsoft data model.

Supported kind values:

. enum

Supported type values:

Any enum type available in Microsoft data model.
There are two ways to find out the type of the enum:
. With 3.1.7 update, metadata has been improved and now shows complete naming of a data type:

TODO: ADD enum.png image

. Execute a GET request on https://{tenant}.com/data/$metadata. The resulting xml file contains the entire data model.





