= EDIFACT EDI Connector 2.1 - Mule 4
:page-aliases: connectors::edifact/edifact-edi-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Premium]

Anypoint Connector for EDIFACT EDI (EDIFACT connector) enables you to convert EDIFACT messages to and from DataWeave-compatible representations using lists and maps.

////
Add this line with a link to the supported versions once the file is created:
The schema definitions for all xref:x12-edifact-versions.adoc[supported EDIFACT versions] are provided.
////
This connector supports EDIFACT versions D.00A,  D.00B,  D.01A,  D.01B, D.01C,  D.02A,  D.02B,  D.03A,  D.03B,  D.04A, D.04B, D.05A, D.05B, D.06A, D.06B, D.07A, D.07B, D.08A, D.08B, D.09A, D.09B, D.10A, D.10B, D.11A, D.11B, D.12A, D.12B, D.13A, D.13B, D.14A, D.14B, D.15A, D.15B, D.93A, D.95B, D.96A, D.97A, D.98A, D.98B, D.99A, D.99B
with supplied schema definitions for all standard messages.

== Prerequisites

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

To use the EDIFACT connector in a production environment, you must have:

* Purchased a MuleSoft license for Anypoint B2B

* Anypoint Studio 7.0 or later

[NOTE]

EDIFACT Connector supports files of up to 15 MB in size, and the memory requirement is approximately 40 to 1.
For example, a 1-MB file requires up to 40 MB of memory to process, so it's important to consider this memory requirement in conjunction with your Transactions Per Second (TPS)  needs for large X12 files.
This is not an exact figure; the value varies according to the complexity of the mapping instructions.

////
Does this need to be doc'd somewhere?
* The undocumented "default" schema configuration for EDIFACT EDI connector 1.x is now officially supported by EDIFACT EDI connector 2.x. If no schemas are referenced in the configuration, the standard version of the schema for each message is looked up from the classpath and used for reading and writing. When this is done, no metadata is available for the message data structure, since the actual messages are unknown at design time.
////

== Creating Schemas

If your implementation conventions differ from the standard, you can create schemas to describe your messages according to your implementation. Standard versions of the schemas for all defined EDIFACT messages and supported versions are included in the distribution.

=== About the EDI Schema Language

The EDIFACT EDI Module uses a YAML format called ESL (for EDI Schema Language) to represent EDI schemas. Basic ESLs define the structure of EDI messages in terms of structures (messages, in EDIFACT terminology), groups, segments, composites, and elements.

////
Make sure these match the previous and move to separate file.
ESLs for the EDIFACT versions d00a, d00b, d01a, d01b, d01c, d02a, d02b, d03a, d03b, d04a, d04b, d05a, d05b, d06a, d06b, d07a, d07b, d08a, d08b, d09a, d09b, d10a, d10b, d11a, d11b, d12a, d12b, d13a, d13b, d14a, d14b, d15a, d15b, d93a, d95b, d96a, d97a, d98a, d98b, d99a, d99b are included.
////
You can customize the EDIFACT schema definitions to suit your data by defining an overlay schema. An overlay schema is a special form of ESL that allows you to modify a base schema, such as an EDIFACT D.98B ORDERS schema, with your specific conventions. You don't need an overlay schema if you're using the structure defined by the standard, but most EDI exchanges modify the base definitions in an implementation convention.

You can also define your own schemas from scratch, or copy and edit a base EDIFACT schema definition to suit your data.

////
Correct this xref
See the xref:1.0@partner-manager::edi-schema-language-reference.adoc[EDI Schema Language Reference] for more details.
////

=== Readability
YAML uses a combination of lists and sets of key-value pairs. The order of
values is not important, as long as the required items are present. Quotes
(such as single or double) are used around values that consist
of digits but are meant to be interpreted as strings (otherwise the
YAML parser treats the values as numbers). Indentation is used to show the nesting of lists.

The ESL structures shown here defines all simple key-value pairs before any lists that are part of the same definition.

== About Schema Locations

To use the connector, you need to know the locations of the schemas
in your project. If you're using out-of-the-box EDIFACT schemas and
not customizing anything, the schema location follows the
`/edifact/{version}/{message}.esl` pattern, so for the D.98B version of the ORDERS message, your schema location is "/edifact/d98b/ORDERS.esl".

If you're using one or more custom schemas, put these under
`src/main/resources` and refer to the location relative to this directory.
For example, if you've put your ORDERS schema (either overlay or full) at `src/main/resources/mypartner/ORDERS.esl,
your schema location is `/mypartner/ORDERS.esl`.

== About Schema Locations

You can configure schema locations in the Anypoint Studio XML view.

In Anypoint Studio, switch to the XML view by clicking Configuration XML and modify your EDIFACT EDI configuration to include a list of all the schemas you wish to include by adding an `+<http://edischema[edi:schema]>+` element for each document type:

[source,xml,linenums]
----
<edifact-edi:config name="EDIFACT_EDI__Configuration" identKeys="true" doc:name="EDIFACT EDI: Configuration">
  <edifact-edi:schemas>
    <edifact:schema value="/edifact/d96a/ORDERS.esl"/>
  </edifact-edi:schemas>
</edifact-edi:config>
----

After you create a global element for your EDIFACT EDI, configure any schemas and operations.

== About the EDIFACT Message Structure

The connector enables reading or writing of EDIFACT documents into or from the canonical EDI message structure. This structure is represented as a hierarchy of Java Maps and Lists, that can be manipulated using DataWeave or code. Each transaction has its own structure, as defined in the schemas, as outlined above.

The message itself contains the following keys (some of that only applys to either the read operation or the write operation, as indicated):

[%header%autowidth.spread]
|===
|Key Name |Description
|Delimiters (optional) |The delimiters used for the message (set based on the last interchange processed by a read operation). If set for a write operation, this overrides the values in the module configuration. The characters in the string are interpreted based on position, in the following order: (data element separator), (component element separator), (repetition separator), (segment terminator), (release character).
|Errors (read only) |A list of errors that are associated with the input as a whole, or with interchanges with no valid messages. See the EdifactError structure description in the To Read and Validate EDIFACT EDI Messages section below.
|FunctionalAcksGenerated (read only) |A list of CONTRL acknowledgment messages that were generated by the module during the read operation. To send an acknowledgment, see the Sending Acknowledgments section below.
|FunctionalAcksToSend (write only) |A list of CONTRL acknowledgment messages that are to be sent by the module during the write operation.
|Interchange (write only) |Map of UNB interchange header segment values used as defaults when writing interchanges.
|Messages |A hierarchy of the messages that were read by the module during a read operation, or that are to be sent by the module during a write operation. The value of this top-level key is a map with standard versions as keys, in the form "D96A" (for instance). For example, if you are using version D96.A ORDERS and CUSRES messages, the Messages would contain a map with one key, "D96A". The value of this key would be another map, this one with two keys, "ORDERS" and "CUSRES". Each of these would contain a list of individual ORDERS and CUSRES messages that you could then process.
|===

Individual messages have their own maps, with the following keys:

[%header%autowidth.spread]
|===
|Key |Description
|Detail |Map of segments or loops from the detail section of the message. Values are maps for segments or loops that occur at most once. Lists of maps are for values that can repeat.
|Errors (read only) |A list of errors associated with the message. (See the EdifactError class description in the Reading and Validating EDI Messages section below.)
|Heading |Map of segments or loops from the heading section of the message. Values are maps for segments or loops that occur at most once. Lists of maps are used for values that can be repeated.
|Id |Message ID, that must match the key of the containing message list.
|Interchange |Map of UNB interchange header segment values. When reading a message, this map is the actual data from the enclosing interchange (a single map linked from all messages in the interchange). When writing a message, these values are used for creating the enclosing interchange (gathering messages with the same interchange values into a single interchange, regardless of whether the actual maps are the same or not). Values not populated in this map default to the values from the Interchange map at the message level.
|MessageHeader |Map of UNH message header segment values. This gives the actual header data for a read operation, and allows you to provide overrides for configuration settings for a write operation.
|Name |Message name.
|Summary |Map of segments or loops from the summary section of the message. Values are maps for segments or loops that occur at most once. Lists of maps are used for values that can be repeated.
|===

Generated CONTRL functional acknowledgment messages differ from received messages in their handling of interchange information:

[%header%autowidth.spread]
|===
|Key name |Description
|Interchange |Map of UNB interchange header segment values. For functional acknowledgments generated by receive processing, this map is a copy of the data for the containing interchange with sender and receiver identification components (UNB2.1/UNB2.2 and UNB2.1/UNB3.2) interchanged. When writing a message, these values are used for creating the enclosing interchange (gathering messages with the same interchange values into a single interchange, regardless of whether the actual maps are the same or not). Values not populated in this map default to the values from the Interchange map at the message level.
|===

== Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as starting points for your apps and examples that illustrate a complete solution.

////
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////

== Next Step

After you complete the prerequisites, you are ready to create your own app and configure the connector using xref:x12-edi-connector-studio.adoc[Anypoint Studio].

== See Also

xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]

xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]

https://help.mulesoft.com[MuleSoft Help Center]
