= Salesforce Connector 10.11 Examples - Mule 4

See the following examples of configuring Salesforce Connector:

* xref:salesforce-example-accept-transform-data.adoc[Accept and Transform Data] +
Configure the *Create* operation to accept Salesforce account data from an HTTP input form and create the new account; the *Query* operation to query accounts by name, and the File Connector *Write* operation to write the new account data to a CSV file.
* xref:salesforce-example-parent-child.adoc[Create or Update an Object in a Parent Child Relationship] +
Configure the *Upsert* operation to create or update a Salesforce object that is in a parent-child relationship.
* xref:salesforce-example-find-duplicates.adoc[Delete Accounts]+
Configure the *Find duplicate* operation to locate duplicate Salesforce accounts.
* xref:salesforce-example-delete.adoc[Delete Accounts]+
Configure the *Delete* operation to delete accounts located on the specified path.


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
