= MongoDB Connector 6.2 XML and Maven Support - Mule 4

If you manually code a Mule app in XML either from the Anypoint Studio XML editor or from a text editor, you can get access to Anypoint Connector for MongoDB (MongoDB Connector) in your app by adding reference statements to your XML Mule flow and in the Apache Maven `pom.xml` file.

You can avoid the manual process described in this topic by using Studio. When you install MongoDB Connector in Studio, Studio automatically populates the XML code with the MongoDB Connector namespace and schema location, and adds a dependency to the `pom.xml` file.

== Add a Namespace for the Connector

Paste the following inside the `<mule>` tag of the header of your configuration XML:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/mongodb
http://www.mulesoft.org/schema/mule/mongodb/current/mule-mongo.xsd
----

This example shows how the namespace statements are placed in the <mule> XML block:

[source,xml,linenums]
----
<mule xmlns:mongodb="http://www.mulesoft.org/schema/mule/mongodb"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/file
	http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
	http://www.mulesoft.org/schema/mule/http
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/core
	http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
	http://www.mulesoft.org/schema/mule/mongodb
	http://www.mulesoft.org/schema/mule/mongodb/current/mule-mongo.xsd">
----

== Add a POM File Dependency

The `pom.xml` Maven file generated by Studio contains dependencies for a Mule app. When you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to this connector:

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-mongodb-connector</artifactId>
  <version>6.x.x</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

To obtain the most up-to-date `pom.xml` file information, access the connector in
https://www.mulesoft.com/exchange/[Anypoint Exchange] and click *Dependency Snippets*. Replace `6.x.x` in the `<version>` element with your MongoDB version.

== Next Steps

After completing your namespace and `pom.xml` file, you can try the MongoDB xref:mongodb-connector-examples.adoc[Examples].

== See Also

*  xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
