= JSON Module - Mule 4
:page-aliases: connectors::json/json-module.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

JSON Module v2.1

The JSON module provides extra functionality for processing JSON documents. Although DataWeave is the tool that Mule uses to access data in JSON documents, this module provides extra functionality that falls outside of DataWeave's scope, like schema validation.

Release Notes: xref:release-notes::connector/json-module-release-notes.adoc[JSON Module Release Notes] +
Exchange: https://www.mulesoft.com/exchange/org.mule.modules/mule-json-module/[JSON Module]


To use the JSON module, add it to your Mule app in Anypoint Studio or Design Center, or you can add the following dependency into your `pom.xml` file:

[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-json-module</artifactId>
    <version>RELEASE</version>
    <classifier>mule-plugin</classifier>
</dependency>
----

Mule converts RELEASE to the latest version.

== See Also

* xref:json-schema-validation.adoc[Validate Documents against a JSON Schema with the JSON Module]
* xref:json-reference.adoc[JSON Module Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
