= Troubleshooting AMQP Connector - Mule 4

To troubleshoot Anypoint Connector for AMQP (AMQP Connector), become familiar with the information about enabling verbose logging and and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with the ... is failing, temporarily enable verbose logging for AMQP connector. +

Remember to always disable the enhanced verbosity after troubleshooting because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="" level="DEBUG"/>
				<AsyncLogger name="" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* AMQP:CONNECTIVITY


* AMQP:CONSUMING


* AMQP:CREATION_NOT_ALLOWED


* AMQP:QUEUE_NOT_FOUND


* AMQP:RETRY_EXHAUSTED


* AMQP:TIMEOUT


* AMQP:ILLEGAL_BODY


* AMQP:UNROUTABLE_MESSAGE


* AMQP:PUBLISHING


* AMQP:PUBLISHING_CONSUMING


== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:amqp-documentation.adoc[AMQP Connector Reference]
