= Troubleshooting AMQP Connector - Mule 4

To troubleshoot Anypoint Connector for AMQP (AMQP Connector), become familiar with the information about enabling verbose logging and and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with the AMQP Connector is failing, temporarily enable verbose logging for AMQP connector. +

Remember to always disable the enhanced verbosity after troubleshooting because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="com.mule.extensions.amqp" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* AMQP:CONNECTIVITY

The connection is no longer valid. It is disposed of, but you can apply a reconnection policy if defined in the application setup.

* AMQP:CONSUMING

An error arised during consuming and could not be identified.

* AMQP:CREATION_NOT_ALLOWED

The queue or exchange does not exist and the disableCreationOfFallbackQueues or disableCreationOfFallbackExchanges is set.

* AMQP:QUEUE_NOT_FOUND

The queue defined does not exist and no fallbackQueueDefinition is provided.

* AMQP:RETRY_EXHAUSTED

The maximum number of retries for the operation is reached.

* AMQP:TIMEOUT

The timeout for the requested operation is exceeded.

* AMQP:ILLEGAL_BODY

An error generated by attempting to send a message with an illegal body (for example, a null body).

* AMQP:UNROUTABLE_MESSAGE

The message could not be routed either because it could not be immediately delivered or because there are no queues bound to the exchange depending on the exchange configuration in the broker.

* AMQP:PUBLISHING

An error aroused during publishing and could not be identified.

* AMQP:PUBLISHING_CONSUMING

Generic error for publishing-consuming which could not be identified.

* AMQP:EXCHANGE_NOT_FOUND

The exchange defined does not exist and no fallbackExchangeDefinition exists.

* AMQP:EXCHANGE_DECLARATION

An exception raised during exchange declaration.

* AMQP:BLOCKED_BROKER

An error is generated by attempting to send a message where the broker is blocked because it runs out of resources.

* AMQP:ACKNOWLEDGING

A generic error for acknowledging which could not be identified.

* AMQP:DELIVER_TAG_NOT_FOUND

The deliver tag to acknowledged was not found by the broker.

* AMQP:REJECTING

A generic error for rejecting which could not be identified.

* AMQP:REQUEUE

A generic error on requeue process.

* AMQP:NO_CHANNEL_AVAILABLE

No channel available


== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:amqp-documentation.adoc[AMQP Connector Reference]
