= Object Store Connector Examples - Mule 4

To fully benefit from using Anypoint Connector for Object Store (Object Connector), see the following examples of configuring the connector operations:

* xref:object-store-to-define-a-new-os.adoc[Define Object Stores] +
Define a global o private object store configuration to use in your Mule application.
* xref:object-store-to-store-and-retrieve.adoc[Store and Retrieve information in Object Stores] +
Configure the *Store* and *Retrieve* operations to store and retrieve information in an object store.
* xref:object-store-to-watermark.adoc[Set up Watermarks with an Object Store] +
Configure Object Store Connector parameters to set up watermarking technique in order to store and retrieve the point at which a periodic synchronization should resume the next time it's executed.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
