= Google Pub/Sub Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Google Pub/Sub (Google Pub/Sub Connector) enables you to access the Google Pub/Sub messaging platform.
This connector exposes operations provided by the Google Pub/Sub client libraries.

For compatibility information and fixed issues, refer to the Google Pub/Sub Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Google Pub/Sub API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Google Pub/Sub Connector enables you to create systems of event producers and consumers, called publishers and subscribers.
Publishers communicate with subscribers asynchronously by broadcasting events, rather than synchronously through remote procedure calls (RPCs).

Some common use cases for Google Pub/Sub Connector include:

* Ingesting user interaction and server events
+
Forward user interaction events from end-user apps or server events from your system to Pub/Sub and then use a stream processing tool to deliver the events to BigQuery, Bigtable, Cloud Storage, and other databases. Pub/Sub enables you to gather events from multiple clients simultaneously.

* Processing events in real-time
+
Use real-time event distribution for raw or processed events for real-time processing. Pub/Sub enables you to integrate with Google systems that export events to Pub/Sub.

* Replicating data among databases
+
Distribute events from databases to construct views of the database state and state history in BigQuery and other data storage systems.

* Using parallel processing and workflows.
+
Distribute a large number of tasks, such as compressing text files, sending email notifications, evaluating AI models, or reformatting images, among multiple workers by using Pub/Sub messages to connect Cloud Functions.

* Developing enterprise event buses
+
Create an enterprise-wide real-time data sharing bus that distributes business events, database updates, and analytics events across your organization.

* Streaming data from IoT devices
+
Use IoT devices to collect and send data, for example, a residential sensor can stream data to backend servers hosted in the cloud.

* Refreshing distributed caches
+
Refresh and update distributed caches, for example, an application can publish invalidation events to modify the IDs of changed objects.

* Load balancing for reliability
+
Monitor applications with load balancing, for example, instances of a service can be deployed on Compute Engine in multiple zones but subscribe to a common topic. When the service fails in any zone, the other instances pick up the load automatically.

* Updating subscriber codes safely
+
Incorporate snapshots into your deployment process to recover from subscriber code bugs.

* Recovering from unexpected subscriber problems
+
Enable acknowledged message retention for a subscription to recover from problems in which there are no relevant snapshots.

* Saving processing time and cost
+
Perform a bulk acknowledgment on a large backlog of messages that are no longer relevant.

* Testing subscriber code on known data
+
Use the same data in every run when testing subscriber code for performance and consistency with snapshots.


== Authentication Types

Google Pub/Sub Connector uses the PubSub Connection authentication method, in which you create a service account and obtain credentials. For more information, refer to https://cloud.google.com/iam/docs/service-accounts#service_account_keys[Google Cloud Service Accounts].


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:google-pubsub-connector-reference.adoc[Google Pub/Sub Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
