= Google Pub/Sub Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Google Pub/Sub (Google Pub/Sub Connector) enables you to access the Google Pub/Sub messaging platform.
This connector exposes operations provided by the Google Pub/Sub client libraries.

For compatibility information and fixed issues, refer to the Google Pub/Sub Connector Release Notes.

== Before You Begin

To use this connector, you must be familiar with:

* The Google Pub/Sub API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Some common use cases for Google Pub/Sub Connector include:

* Publishing messages
* Listening to messages
* Managing snapshots
* Replaying messages

== Authentication Types

Google Pub/Sub Connector uses the PubSub Connection authentication method, in which you create a service account and obtain credentials. For more information, refer to https://cloud.google.com/iam/docs/service-accounts#service_account_keys[Google Cloud Service Accounts].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:google-pubsub-connector-reference.adoc[Google Pub/Sub Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
