= Google Pub/Sub Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Google Pub/Sub (Google Pub/Sub Connector) enables you to access the Google Pub/Sub messaging platform.
This connector exposes operations provided by the Google Pub/Sub client libraries.

For compatibility information and fixed issues, refer to the Google Pub/Sub Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Google Pub/Sub API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Google Pub/Sub Connector enables you to create systems of event producers and consumers, called publishers and subscribers.
Publishers communicate with subscribers asynchronously by broadcasting events, rather than synchronously through remote procedure calls (RPCs).

Some common use cases for Google Pub/Sub Connector include:

* Ingesting user interaction and server events

Forward user interaction events from end-user apps or server events from your system to Pub/Sub and then use a stream processing tool to deliver the events to BigQuery, Bigtable, Cloud Storage, and other databases. Pub/Sub enables you to gather events from multiple clients simultaneously.

* Processing events in real-time

Use real-time event distribution for raw or processed events for real-time processing. Pub/Sub enables you to integrate with Google systems that export events to Pub/Sub.

* Replicating data among databases

Pub/Sub is commonly used to distribute change events from databases. These events can be used to construct a view of the database state and state history in BigQuery and other data storage systems.

* *Parallel processing and workflows*. You can efficiently distribute a large number of tasks among multiple workers--such as compressing text files, sending email notifications, evaluating AI models, or reformatting images--by using Pub/Sub messages to connect Cloud Functions.
* *Enterprise event bus*. You can create an enterprise-wide real-time data sharing bus, distributing business events, database updates, and analytics events across your organization.
* *Data streaming from IoT devices*. For example, a residential sensor can stream data to backend servers hosted in the cloud.
* *Refreshing distributed caches*. For example, an application can publish invalidation events to update the IDs of objects that have changed.
* *Load balancing for reliability*. For example, instances of a service may be deployed on Compute Engine in multiple zones but subscribe to a common topic. When the service fails in any zone, the others can pick up the load automatically.
* *Update subscriber code safely*. A concern with deploying new subscriber code is that the new executable may erroneously acknowledge messages, leading to message loss. Incorporating snapshots into your deployment process gives you a way to recover from bugs in new subscriber code.
* *Recover from unexpected subscriber problems*. In cases where subscriber problems are not associated with a specific deployment event, you might not have a relevant snapshot. In this case, if you have enabled acknowledged message retention for a subscription, seeking to a time in the past gives you a way to recover from the error.
* *Save processing time and cost*. Perform a bulk acknowledgement on a large backlog of messages that are no longer relevant.
* *Test subscriber code on known data*. When testing subscriber code for performance and consistency, it is useful to use the same data in every run. Snapshots enable consistent data with strong semantics. In addition, snapshots can be applied to any subscription on a given topic, including a newly created one.

== Authentication Types

Google Pub/Sub Connector uses the PubSub Connection authentication method. Which practicaly is Oauth2 authorization with implicit grant type. To make this work, you have to create service acount and obtain credentials. For more information see link https://cloud.google.com/iam/docs/service-accounts#service_account_keys[Google Cloud Service Accounts]


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:google-pubsub-connector-reference.adoc[Google Pub/Sub Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
