// Used in Connector troubleshooting pages.
== Enable SSL Logging
Enable SSL logs to investigate an issue related to TLS communications.

You can set your SSL log level depending on your required level of detail:

. Enable only SSL log details
`javax.net.debug=ssl`
. Enable only handshaking details (The handshake protocol is a series of messages exchanged over the record protocol)
`javax.net.debug=ssl:handshake`
. Enable handshaking and SSL at the same time
`javax.net.debug=ssl, handshake`
. Enable dumping of all details and all traffic data
`javax.net.debug=all`
+
NOTE: This option is very verbose and under normal circumstances is not necessary.

[WARNING]
SSL logging results in a performance impact for HTTPS (or other TLS) connections. SSL logging must only be enabled to troubleshoot a specific issue and must not be enabled for extended periods. SSL logging produces a significant amount of log messages and can inundate your log file if it is left enabled and unattended.

To enable SSL logs:

The debug parameter must be set as an argument in the runtime configuration for the application.

. In Studio, right-click on the project and select *Run > Run Configurations*.
. Go to the *Arguments* tab and add `-M-Djavax.net.debug=ssl` in the *VM arguments* section.