// Used in Connector troubleshooting pages, for connectors of DEBUG packages starting with org.mule.extension
== Enable Verbose Logging

To get a better understanding of why an application's interaction with {page-service-name} Connector is failing, temporarily enable verbose logging for the connector. +

Remember to always disable enhanced verbosity after troubleshooting, because it can affect your Mule application's performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,subs="+attributes"]
----
			<Loggers>
				...
				<AsyncLogger name="org.mule.extension.{page-connector-name}" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.
