= Example: To Send Messages across Different Apps
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: VM, queues, connector, publish, listen, response, domain, across applications


Instead of using the `<vm:listener>` message source, you can consume messages in a VM queue through the `<vm:consume>` operation.

This operation can consume messages on demand, allowing you to:

* Dynamically consume from different queues depending on a certain condition.
* Have a tighter control on the rhythm at which the app consumes messages.

You can also send messages across apps by using Mule domains. Starting in Mule 4, every connector can be placed in a domain. If you create the VM configuration in a domain, all apps in that domain can use the same configuration.

. Create a VM configuration in a domain like in this:
+
[source,xml,linenums]
----
<mule-domain xmlns="http://www.mulesoft.org/schema/mule/domain"
  xmlns:vm="http://www.mulesoft.org/schema/mule/vm"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.mulesoft.org/schema/mule/vm http://www.mulesoft.org/schema/mule/vm/current/mule-vm.xsd
  http://www.mulesoft.org/schema/mule/domain http://www.mulesoft.org/schema/mule/domain/current/mule-domain.xsd">

  <vm:config name="sharedVMConfig">
    <vm:queue queueName="sharedQueue" queueType="PERSISTENT" />
  </vm:config>

</mule-domain>
----
+
. Publish messages from a second application, also of the same domain:
+
[source,xml,linenums]
----
<flow name="crossAppRequester">
  <vm:publish queueName="sharedQueue" config-ref="sharedVMConfig" />
</flow>
----
+
. Pull messages from the queue after they are published.
+
[source,xml,linenums]
----
<flow name="queueConsume">
  <vm:consume queueName="sharedQueue" config-ref="sharedVMConfig" />
  <logger />
</flow>
----
+
In this example, the `publish` and `consume` operations point to the configuration defined in `mule-domain`.
