= Using Anypoint Studio to Configure MuleSoft Vectors Connector 1.0 
:exchange-search-name: mulesoft vectors
:connector-name: MuleSoft Vectors
:lc-connector-name: mulesoft-vectors
:studio-connector-name: MuleSoft Vectors Connector

include::connectors::partial$t-studio-partial.adoc[tags=topic-intro]

[[create-mule-project]]
== Create a Mule Project

include::connectors::partial$t-studio-partial.adoc[tags=create-project-intro]

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

Add MuleSoft Vectors Connector to your Mule project to automatically populate the XML code with the connector's namespace and schema location and add the required dependencies to the project's `pom.xml` file: 

. In *Mule Palette*, click *(X) Search in Exchange*.
. In *Add Dependencies to Project*, type `mulesoft vectors` in the search field.
. Click *MuleSoft Vectors Connector* in *Available modules*.
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio does not make that connector available to other projects in your Studio workspace.

== Configure Shared Libraries

To reduce the overall size of the connector and avoid adding dependencies that are not required, all the optional libraries are removed from the connector and only the required ones can be added depending on the specific use case. You can use the Mule Maven plugin to add the required dependencies to the project's `pom.xml` file. For more information about how to configure shared libraries, see xref:mule-runtime::mmp-concept.adoc#configure-shared-libraries[Configure Shared Libraries].

=== Storage Services

==== Configuration

[source,xml,linenums]
----
...
<sharedLibraries>
		<sharedLibrary>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j</artifactId>
		</sharedLibrary>
		<sharedLibrary>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-document-parser-apache-tika</artifactId>
		</sharedLibrary>
    ...
</sharedLibraries>
...
<dependencies>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j</artifactId>
			<version>1.0.1</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-document-parser-apache-tika</artifactId>
			<version>1.0.1-beta6</version>
		</dependency>
    ...
</dependencies>
...
----

==== Connections

[tabs]
====
Amazon S3::
+
[source,xml,linenums]
----
...
<sharedLibraries>
    <sharedLibrary>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>s3</artifactId>
    </sharedLibrary>
    ...
</sharedLibraries>
...
<dependencies>
    <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>s3</artifactId>
        <version>2.31.6</version>
    </dependency>
    ...
</dependencies>
...
----

Azure Blob Storage::
+
[source,xml,linenums]
----
...
<sharedLibraries>
    <sharedLibrary>
        <groupId>com.azure</groupId>
        <artifactId>azure-storage-blob</artifactId>
    </sharedLibrary>
    ...
</sharedLibraries>
...
<dependencies>
    <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-storage-blob</artifactId>
        <version>12.30.0</version>
    </dependency>
    ...
</dependencies>
...
----

Google Cloud Storage::
+
[source,xml,linenums]
----
...
<sharedLibraries>
    <sharedLibrary>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-storage</artifactId>
    </sharedLibrary>
    ...
</sharedLibraries>
...
<dependencies>
    <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-storage</artifactId>
        <version>2.43.0</version>
    </dependency>
    ...
</dependencies>
...
----

Local Storage::
+
[source,xml,linenums]
----
...
<sharedLibraries>
	<sharedLibrary>
		<groupId>dev.langchain4j</groupId>
		<artifactId>langchain4j-document-transformer-jsoup</artifactId>
	</sharedLibrary>
    ...
</sharedLibraries>
...
<dependencies>
	<dependency>
		<groupId>dev.langchain4j</groupId>
		<artifactId>langchain4j-document-transformer-jsoup</artifactId>
		<version>1.0.1-beta6</version>
	</dependency>
    ...
</dependencies>
...
----
====

=== Embedding Models

==== Configuration

[source,xml,linenums]
----
...
<sharedLibraries>
	<sharedLibrary>
		<groupId>dev.langchain4j</groupId>
		<artifactId>langchain4j-core</artifactId>
	</sharedLibrary>
    ...
</sharedLibraries>
...
<dependencies>
	<dependency>
		<groupId>dev.langchain4j</groupId>
		<artifactId>langchain4j-core</artifactId>
		<version>1.0.1</version>
	</dependency>
    ...
</dependencies>
...
----

=== Vector Stores

==== Connections

[tabs]
====
Azure AI Search::
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-azure-ai-search</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-azure-ai-search</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  ...
</dependencies>
...
----

AlloyDB::
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-community-alloydb-pg</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-community-alloydb-pg</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  ...
</dependencies>
...
----

Chroma::
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-chroma</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-chroma</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  ...
</dependencies>
...
----

Elasticsearch::
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-elasticsearch</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-elasticsearch</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  ...
</dependencies>
...
----

Milvus::
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-milvus</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-milvus</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  ...
</dependencies>
...
----

Amazon OpenSearch::
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-opensearch</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-opensearch</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  ...
</dependencies>
...
----

PGVector::
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-pgvector</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-pgvector</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  ...
</dependencies>
...
----

Pinecone::
+
NOTE: You can't use Pinecone with Milvus or Qdrant.
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-pinecone</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-pinecone</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  ...
</dependencies>
...
----

Qdrant::
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-qdrant</artifactId>
  </sharedLibrary>
  <sharedLibrary>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty-shaded</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-qdrant</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty-shaded</artifactId>
      <version>1.65.1</version>
  </dependency>
  ...
</dependencies>
...
----

Weaviate::
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-weaviate</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-weaviate</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  ...
</dependencies>
...

----

MongoDB Atlas::
+
[source,xml,linenums]
----
...
<sharedLibraries>
  <sharedLibrary>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-mongodb-atlas</artifactId>
  </sharedLibrary>
  ...
</sharedLibraries>
...
<dependencies>
  <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-mongodb-atlas</artifactId>
      <version>1.0.1-beta6</version>
  </dependency>
  ...
</dependencies>
...
----

Ephemeral File::
+
[source,xml,linenums]
----
...
<sharedLibraries>
		<sharedLibrary>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j</artifactId>
		</sharedLibrary>
    ...
</sharedLibraries>
...
<dependencies>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j</artifactId>
			<version>1.0.1</version>
		</dependency>
    ...
</dependencies>
...
----
====

[[configure-source]]
== Configure a Source

include::connectors::partial$t-studio-partial.adoc[tags=configure-source-intro]
You can configure one of these sources to use with MuleSoft Vectors Connector:

include::connectors::partial$t-studio-partial.adoc[tags=listener-scheduler-descriptions]

include::connectors::partial$t-studio-partial.adoc[tags=listener-steps]

[[add-connector-operation]]
== Add a Connector Operation to the Flow

When you add a connector operation to your flow, you are specifying an action for that connector to perform.

To add an operation for MuleSoft Vectors Connector, follow these steps:

. In *Mule Palette*, select *MuleSoft Vectors Connector* and then select the operation to add.
. Drag the operation onto the Studio canvas, next to the source.

[[configure-global-element]]
== Configure a Global Element for the Connector

When you configure a connector, configure a global element that all instances of that connector in the app can use. Configuring a global element requires you to provide the authentication credentials that the connector requires to access the target vector stores and embedding providers.

include::connectors::partial$t-studio-partial.adoc[tags=property-placeholders]

To configure the global element for MuleSoft Vectors Connector, follow these steps.

. Select the operation in the Studio canvas.
. On the properties screen for the operation, click the Add (*+*) icon to access the global element configuration fields.
. Choose from these configs.
+
* Embedding Config
* Store Config  
* Transform Config
. Fill out the fields depending on the operation type and target vector store or embedding provider.
. Click *OK*.

[[configure-other-fields]]
== Configure Additional Connector Fields

After you configure a global element for the connector, configure the other required fields. The required fields vary depending on which connector operation you use.

For detailed configuration information for each operation type, see xref:mulesoft-vectors-additional-config.adoc[MuleSoft Vectors - Additional Configuration Information].

[[view-app-log]]
== View the App Log

include::connectors::partial$t-studio-partial.adoc[tags=view-app-log]

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-config-use-studio.adoc[Using Studio to Configure a Connector]
* xref:mulesoft-vectors-connector-reference.adoc[MuleSoft Vectors Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center] 