= Amazon Lambda Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Amazon Lambda (Amazon Lambda Connector) provides access to standard Amazon Kinesis Data Stream operations using Anypoint Platform.

For compatibility information and fixed issues, see the Amazon Lambda Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Amazon Lambda API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* AWS Identity and Access Management (IAM) Access Key credentials 
* Access to the Amazon Lambda target resource
* Anypoint Studio version 7.3 or later

== Common Use Cases for the Connector

Common use cases for Lambda Connector include the following:


== Authentication Types

Amazon Lambda Connector supports Access Key authentication. With this type of authentication, the connector authenticates to AWS by using an access key, secret key, and optionally, a role.

For information about configuring authentication, see xref:amazon-kinesis-connector-studio.adoc[Use Studio to Configure Amazon Lambda].


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
