= Zuora AQuA XML and Maven Support - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

If you manually code a Mule app in XML either from the Anypoint Studio XML editor or from a text editor, you can get access to the connector in your app by adding reference statements to your XML Mule flow and in the Apache Maven POM file.

[NOTE]
====
You can avoid the manual process described in this topic by using Studio. When you install the connector in Studio, it automatically populates the XML code with the connector's namespace and schema location, and adds a dependency to the POM file.
====

== Add a Namespace for the Connector

Paste the following code inside the `<mule>` tag of the header of your configuration XML.

[source,text,linenums]
----
xsi:schemaLocation="
...
http://www.mulesoft.org/schema/mule/zuora-aqua-connector
http://www.mulesoft.org/schema/mule/zuora-aqua-connector/current/mule-zuora-aqua-connector.xsd"
----

This example shows how the namespace statements are placed in the mule XML block:

[source,xml,linenums]
----
<mule xmlns:http="http://www.mulesoft.org/schema/mule/http"
      xmlns:mule-zuora-aqua-connector="http://www.mulesoft.org/schema/mule/mule-zuora-aqua-connector"
	    xmlns="http://www.mulesoft.org/schema/mule/core"
	    xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core
               http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/mule-zuora-aqua-connector
               http://www.mulesoft.org/schema/ mule/mule-zuora-aqua-connector/current/mule-mule-zuora-aqua-connector.xsd
               http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">
      <!-- Insert your configuration elements and your flow here -->
</mule>
----

[[pomfile]]
== Add a POM File Dependency

The `pom.xml` Apache Maven file generated by Anypoint Studio contains dependencies for a Mule app. When you code a Mule app manually, include this XML snippet in your POM file to enable access to this connector. Mule runtime engine translates the `RELEASE` dependency keyword to the current version.

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-zuora-aqua-connector</artifactId>
  <version>RELEASE</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

To obtain the most up-to-date POM file information, access the connector in https://www.mulesoft.com/exchange/[Anypoint Exchange] and click *Dependency Snippets*.

== Next Step

After completing this section, you can try the xref:zuora-aqua/zuora-aqua-connector-examples.adoc[Zuora Examples].

== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
