= JMS Connector Examples - Mule 4

To fully benefit from using Anypoint Connector for JMS (JMS Connector), see the following examples of configuring the connector operations:

* xref:jms-activemq-configuration.adoc[Configure an ActiveMQ Connection] +
Configure JMS Connector to connect to ActiveMQ.
* xref:jms-ack.adoc[Manage Message Acknowledgements] +
Configure AMQP Connector to manage different acknowledgment configurations, such as automatic acknowledgment on success, immediate acknowledgment, and manual acknowledgment.
* xref:jms-listener.adoc[Listen for New Messages] +
Configure the *On New Message* source to listen for new messages as they arrive to the destination.
* xref:jms-publish.adoc[Publish New Messages] +
Configure the *Publish* operation to create a new message and send it to the specified destination.
* xref:jms-consume.adoc[Consume Messages] +
Configure the *Consume* operation to consume a message at any given time in the flow, from any given destination.
* xref:jms-publish-consume.adoc[Publish Messages and Listen for Replies] +
Configure the *Publish consume* operation to publish a message to any destination, and then wait for a reply on a different destination.
* xref:jms-publish-consume-example.adoc[Publish and Consume Messages Within Flows] +
Configure the *Publish consume* operation to publish and consume messages within two flows, and use a correlation ID to ensure that the incoming messages are replies to a specific outgoing message.
* xref:jms-transactions.adoc[Manage Transactions] +
Configure JMS Connector to execute a series of operations that are performed only when the transaction is committed.
* xref:jms-topic-subscription.adoc[Configure Topic Subscription] +
Configure topics subscriptions in JMS Connector to control how subscriptions behave regarding consumers connections and also how these consumers interact with each other.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
