= Troubleshooting Java Module - Mule 4

To troubleshoot Java module, become familiar with the information about enabling verbose logging and and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with the ... is failing, temporarily enable verbose logging for Java module. +

Remember to always disable the enhanced verbosity after troubleshooting because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="" level="DEBUG"/>
				<AsyncLogger name="" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* JAVA:ARGUMENTS_MISMATCH


* JAVA:CLASS_NOT_FOUND


* JAVA:INVOCATION


* JAVA:NO_SUCH_METHOD


* JAVA:WRONG_INSTANCE_CLASS


* JAVA:NO_SUCH_CONSTRUCTOR

* JAVA:NOT_INSTANTIABLE_TYPE


== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:java-reference.adoc[Java Module Reference]
