= Java Module Examples - Mule 4

To fully benefit from using Java module, see the following examples of configuring the connector operations:

* xref:java-create-instance.adoc[Create an Instance of a Class] +
Configure the *New* operation to create an instance of a Java class.
* xref:java-invoke-method.adoc[Invoke Java Methods] +
Configure the *Invoke* and *Invoke static* operations to call Java methods.
* xref:java-argument-transformation.adoc[Transform Arguments] +
Configure Java module to transform the arguments given to a Java invocation even if they don't exactly match the type expected by the Java method.
* xref:java-instanceof.adoc[Test for an Instance of a Class] +
Configure the *Validate type* operation to operation that tests whether an object is an instance of a class.
* xref:java-trhowable.adoc[Work With Throwables] +
Configure Java module to use DataWeave functions for throwable instances.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
