= Troubleshooting Java Module - Mule 4

To troubleshoot Java module, become familiar with the information about enabling verbose logging and and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with the Java Module is failing, temporarily enable verbose logging for Java module. +

Remember to always disable the enhanced verbosity after troubleshooting because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="org.mule.extensions.java" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* JAVA:ARGUMENTS_MISMATCH

There is an error because any of the arguments is of the wrong type, missing or too many arguments were provided

* JAVA:CLASS_NOT_FOUND

There is an error because a definition could not be found for the class with the specified name.

* JAVA:INVOCATION

There is an error during the invocation of a Method or Constructor.

* JAVA:NO_SUCH_METHOD

There is an error because the specified method cannot be found.

* JAVA:WRONG_INSTANCE_CLASS

There is an error because the class of the a given instance does not match with the expected Class.

* JAVA:NO_SUCH_CONSTRUCTOR

There is an error because  the class doesn't have a matching constructor or it is not visible.

* JAVA:NOT_INSTANTIABLE_TYPE

There is an error because  the supplied class is abstract or an interface.


== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:java-reference.adoc[Java Module Reference]
