= OAuth2 Provider Module - Mule 4

OAuth2 Provider Module v1.1

The OAuth2 Provider module enables a Mule runtime engine (Mule) app to be configured as an Authentication Manager in an OAuth2 dance.
With this role, the application can authenticate to previously registered clients, grant tokens, validate tokens, or register and delete clients, all during the execution of a flow.

The following documentation assumes a basic knowledge of the OAuth2 authorization protocol. For further reference, see the https://tools.ietf.org/html/rfc6749[RFC-6749].

If the app behaves as the client in the OAuth2 dance, use the xref:oauth-module::index.adoc[OAuth Module] instead.


== Before You Begin

To use this module, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as starting points for your apps and examples that illustrate a complete solution.


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
