= Commerce Cloud B2C Data Connector XML and Maven Support - Mule 4

If you manually code a Mule app in XML either from the Anypoint Studio XML editor or from a text editor, you can access Anypoint Connector for Shop API (Shop API Connector) in your app by adding reference statements to your XML Mule flow and in the Apache Maven `pom.xml` file.

[NOTE]
====
You can avoid the manual process described in this topic by using Studio. When
you install Shop API Connector in Anypoint Studio, Studio automatically populates
the XML code with the connector namespace and schema location and adds a
dependency to the `pom.xml` file.
====

== Add a Namespace for the Connector

Paste the following code inside the `mule` tag of the header
of your configuration XML:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/shop-api
http://www.mulesoft.org/schema/mule/shop-api/current/mule-shop-api.xsd
----

This example shows how the namespace statements are placed in the XML:

[source,xml,linenums]
----
<mule xmlns:http="http://www.mulesoft.org/schema/mule/http" 
	xmlns:shop="http://www.mulesoft.org/schema/mule/shop"
    xmlns="http://www.mulesoft.org/schema/mule/core"
    xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core 
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/shop 
	http://www.mulesoft.org/schema/mule/shop/current/mule-shop.xsd
	http://www.mulesoft.org/schema/mule/http 
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">
</mule>
----

== Add a POM File Dependency

The Maven `pom.xml` file generated by Anypoint Studio contains dependencies
for a Mule app. When you code a Mule app manually, include this XML snippet in
your `pom.xml` file to enable access to the connector. The Mule runtime
engine translates the `RELEASE` dependency keyword to the current version.
[source,xml,linenums]
```
<dependency>
    <groupId>com.mulesoft.connectors</groupId>
    <artifactId>shop-api</artifactId>
    <version>RELEASE</version>
    <classifier>mule-plugin</classifier>
</dependency>
```

To obtain the most up-to-date `pom.xml` file information, access the
connector in https://www.mulesoft.com/exchange/[Anypoint Exchange]

and click *Dependency Snippets*.

== Next Step

After completing your namespace and `pom.xml` file, you can try
the xref:shop-api-connector-examples.adoc[Examples].

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
