= Commerce Cloud B2C Data Connector - Mule 4

Support Category: Select


Anypoint Connector for Commerce Cloud B2C Data (Commerce Cloud B2C Data Connector) is an operation-based connector, which means that when you add the connector to your flow, you need to configure a specific operation for the connector to perform. 

Commerce Cloud B2C Data Connector provides access to the Open Commerce API (OCAPI) by using certain configurations. You can then access the data, update the data, and delete the data, as required.

OCAPI enables you to access resources using HTTP requests and HTTP responses. Each resource is addressed by its unique URL, which includes the API version. Data is transported using request or header parameters, or within the request body as a JSON document with a defined structure. 

OCAPI is divided into different APIs: 

* Shop API +
Enables a client to interact with the system as a shop customer or as an agent shopping on behalf of a customer
* Data API +
Gives create, read, update, and delete access to system resources
* Meta API +
Retrieves a formal description of the Open Commerce API, including custom attributes

== Prerequisites

To use this connector, you must be familiar with:

* The Commerce Cloud B2C Data API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the Commerce Cloud Shop API target resource
* Anypoint Studio version 7 or later

== Common Use Cases For the Connector

See xref:shop-api-connector-examples.adoc[Examples] for a simple use case.

== Audience

* New users, read:
** xref:commerce-cloud-b2c-data-connector-studio.adoc[Use Studio to Configure the Connector] to create your Mule app 
** xref:commerce-cloud-b2c-data-connector-examples.adoc[Examples], which provides one or more use cases for the connector

* Advanced users, read:
** xref:commerce-cloud-b2c-data-connector-xml-maven.adoc[XML and Maven Support]
** xref:commerce-cloud-b2c-data-connector-examples.adoc[Examples], which provides one or more use cases for the connector

== Authentication Types

Commerce Cloud B2C Data Connector connections use the following authentication types:

* Client ID
* JWT 
* OAuth 2

== Next Step

After you complete the prerequisites, you are ready to create your own app and configure the connector using
xref:commerce-cloud-b2c-data-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:commerce-cloud-b2c-data-connector-reference.adoc[Commerce Cloud B2C Data Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
