= Salesforce Commerce Cloud B2C Data Connector - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Salesforce Commerce Cloud B2C Data API (B2C Data Connector) enables you to access the Commerce Cloud Data API by using certain configurations, and to then access the data, update the data, and delete the data, as required.

== Prerequisites

To use this connector, you must be familiar with:

* The Commerce Cloud Data API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Anypoint Studio version 7 or later
* Commerce Cloud credentials such as client Id, Client Secret, and Scopes to access the Data API. +
You can get the required credentials from the Salesforce team. 

== Common Use Cases For the Connector

See xref:data-api-connector-examples.adoc[Examples] for a simple use case.

== Audience

* New users, read:
** xref:commerce-cloud-b2c-data-connector-studio.adoc[Use Studio to Configure B2C Data Connector] to create your Mule app.
** The xref:commerce-cloud-b2c-data-connector-examples.adoc[Examples] topic, which provides one or more use cases for using the connector.
* Advanced users, read:
** xref:commerce-cloud-b2c-data-connector-xml-maven.adoc[XML and Maven Support]
** The xref:commerce-cloud-b2c-data-connector-examples.adoc[Examples] topic, which provides one or more use cases for using the connector.

== Authentication Types

B2C Data Connector connections use the OAuth 2 Application Provider authentication type.

== Next Step

After you complete the prerequisites, you are ready to create your own app and configure the connector using xref:data-api-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]