= X12 EDI Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]
// If this is a Premium connector, change Select to Premium

X12 EDI Connector Version Major.Minor

Anypoint Connector for X12 EDI provides ...

For information about compatibility and fixed issues, see xref:release-notes::connector/x12-edi.adoc[X12 EDI Connector Release Notes] 

== Prerequisites

To use this connector, you must be familiar with:

* The <target connector’s API>
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to:

* The <backend system> target resource
*// If your connector has other prerequisites specific to this connector, list them here.
* Anypoint Studio version <x.x> or later

Before creating an app, you must:

* Have access to the X12 EDI target resource and Anypoint Platform. 
// If your connector has other prerequisites, list them here.

== Common Use Cases For the Connector

// List common use cases for the X12 EDI Connector and provide 
// a link to the xref:x12-edi/x12-edi-connector-examples.adoc[Examples] use cases.

== Audience

* New user
+
To create your Mule app, see:

* xref:x12-edi/x12-edi-connector-studio.adoc[Studio Configuration] 
* xref:x12-edi/x12-edi-connector-config-topics.adoc[Additional Configuration Information]
to help extend your understanding of the X12 EDI connector 
* xref:x12-edi/x12-edi-connector-examples.adoc[Examples], which provides one or more use cases for the connector.
+
* Advanced user
+
* Read the following: 

* xref:x12-edi/x12-edi-connector-xml-maven.adoc[XML and Maven Support]
* xref:x12-edi/x12-edi-connector-config-topics.adoc[Additional Configuration Information]
* xref:x12-edi/x12-edi-connector-examples.adoc[Examples] topics

For a major or minor release, see
xref:x12-edi/x12-edi-connector-upgrade-migrate.adoc[Upgrade and Migrate].

== Connection Types

// If there is one authentication type, use the following format:

X12 EDI connections use the <authentication-type> authentication type, which ... <add a brief description of the authentication type like the descriptions below>.

////
If there is more than one authentication type, use a list like the one shown below (use only the applicable connection types--delete the others):

X12 EDI connections can use the following authentication types:

* Basic authentication
+
Uses a username and password for authentication
+
* OAuth
+
Uses access tokens provided by the authorization server to get access to protected data 
+
* OAuth2 
+
Delegates user authentication to the service hosting the user account
+
Kerberos
+
Uses the Kerberos principal as the username. The keytab path you specify obtains a ticket-granting ticket (TGT) from the authorization server.
////

For information about configuring authentication types, see xref:x12-edi/x12-edi-studio.adoc[Use Studio to Configure X12 EDI Connector.

////
Include the following section only if Exchange provides templates, examples, or both for the connector. If there are templates and not examples, or vice versa, reword the section as applicable. 
////

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as a starting point for your app, as well as examples that illustrate a complete solution.

////
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////

== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app and configure the connector using xref:x12-edi/x12-edi-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://www.mulesoft.com/exchange/?search=x12-edi&type=connector[X12 EDI Connector on Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
