= Connecting to Gmail

Configure Email Connector to connect to your Gmail account.

For new integrations, use OAuth 2.0 with xref:gmail-connector::index.adoc[Gmail Connector], which is the preferred Google authentication method for Gmail API access. If you use Email Connector with username and password, Google requires an app password with 2-Step Verification enabled.

== Configure an App Password in Your Gmail Account

To send emails to a Gmail account via the Email Connector, https://support.google.com/accounts/answer/185833?visit_id=637917932546436561-2352829986&p=InvalidSecondFactor&rd=1[configure an app password] in your Gmail account.

Use the app password instead of your regular Gmail email password, which enables you to use email protected by MFA (Multi-Factor Authentication).

== IMAP Configuration

Configure the following required parameters:

* Gmail IMAP Connection: `IMAPS Connetion`
* Gmail IMAP server address: `imap.gmail.com`
* Gmail username: Your full Gmail address (for example, +`user@gmail.com`+).
* Gmail password: Use a Google app password (not your regular Gmail password).
* Gmail IMAP port (SSL): `993`
* TLS Configuration: `Check insecure`

[source,xml,linenums]
----
<email:imap-config name="gmail">
  <email:imaps-connection host="imap.gmail.com"
    port="993" user="user@gmail.com"
    password="mypassword">
    <tls:context>
        <tls:trust-store insecure="true"/>
    </tls:context>
  </email:imaps-connection>
</email:imap-config>
----

== POP3 Configuration

Configure the following required parameters:

* Gmail POP3 Connection: `POP3S Connetion`
* Gmail POP server address: `pop.gmail.com`
* Gmail username: Your full Gmail address (for example, +`user@gmail.com`+).
* Gmail password: Use a Google app password (not your regular Gmail password).
* Gmail POP port (SSL): `995`
* TLS Configuration: `Check insecure`

[source,xml,linenums]
----
<email:pop3-config name="gmail">
    <email:pop3s-connection host="pop.gmail.com"
      port="995"  user="user@gmail.com"
      password="mypassword">
        <tls:context>
            <tls:trust-store insecure="true"/>
        </tls:context>
    </email:pop3s-connection>
</email:pop3-config>
----

== SMTP Configuration

Configure the following required parameters:

* Gmail SMTP Connection: `SMTPS Connetion`
* Gmail SMTP server address: `smtp.gmail.com`
* Gmail username: Your full Gmail address (for example, +`user@gmail.com`+).
* Gmail password: Use a Google app password (not your regular Gmail password).
* Gmail SMTP port (SSL): `465`
* TLS Configuration: `Check insecure`

[source,xml,linenums]
----
<email:smtp-config name="smtp-gmail" from="sender@gmail.com">
    <email:smtps-connection host="smtp.gmail.com"
      port="465" password="mypassword"
      user="user@gmail.com">
        <tls:context enabledProtocols="TLSv1.2,SSLv3">
            <tls:trust-store insecure="true"/>
        </tls:context>
    </email:smtps-connection>
</email:smtp-config>
----

== Troubleshoot SMTPS Connection Issues

Google no longer supports the Less Secure Apps setting for Gmail accounts.

If SMTP authentication fails when you use Email Connector with Gmail:

. Verify that 2-Step Verification is enabled for the Gmail account.
. Generate an app password and use that password in your Email Connector configuration.
. Confirm that you're not using your normal Gmail account password.
+
For details, see https://support.google.com/accounts/answer/185833[Sign in using app passwords].
