= AS2 Connector 7.0 Examples 

The mule application that uses AS2 Connector needs a global configuration to add external libraries based on the security mode. Due to the restricition of only one External Libs global configuration allowed per mule application it needs to be configured manually in the examples below. Refer xref:as2-connector::as2-connector-upgrade-migrate.adoc[Configure External Libraries].

The following examples show how to configure send and receive messages in Anypoint Connector for AS2 (AS2 Connector):

* xref:as2-connector-example-receive-send.adoc[Receiving AS2 Messages and Sending Back MDNs] +
Configure the *As 2 listener* source to start receiving AS2 requests and the *Send with Sync MDN* and *Send with Async MDN* operations to start sending AS2 requests.
* xref:as2-connector-example-receiving-mdn-messages.adoc[Receiving AS2 MDN Messages] +
Configure the *As 2 mdn listener* source to start receiving Messsage Disposition Notification (MDN) Messages.
* xref:as2-connector-example-send.adoc[Sending AS2 Messages and Receiving MDNs] +
Configure the connector to send AS2 messages to a partner and handle both synchronous and asynchronous MDNs.
* xref:as2-connector-example-multiple-partners.adoc[Sending MDNs to Multiple Partners] +
How to send MDNs to multiple partners.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
