= Google BigQuery Connector 1.0

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Google BigQuery (Google BigQuery Connector) synchronizes data and automates business processes between Google BigQuery and third-party applications, either on-premises or in the cloud.

Google BigQuery is a serverless, highly scalable, and cost-effective multicloud data warehouse designed for business agility.

- Democratize insights with a secure and scalable platform with built-in machine learning
- Power business decisions from data across clouds with a flexible, multicloud analytics solution
- Run analytics at scale with 26%–34% lower three-year TCO than cloud data warehouse alternatives
- Adapting to your data at any scale, from bytes to petabytes, with zero operational overhead

For compatibility information and fixed issues, see the Google BigQuery Connector Release Notes.

== Prerequisites

To use this connector, you should be familiar with:

* The Google BigQuery API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access Google BigQuery
* Anypoint Studio version 4.2.1 or later

== Common Use Cases for the Connectors

Common use cases for Google BigQuery Connector include the following:

* Migrating data warehouses to BigQuery
+
Solve for today’s analytics demands and seamlessly scale your business by moving to Google Cloud’s modern data warehouse. Streamline your migration path from Netezza, Oracle, Redshift, Teradata, or Snowflake to BigQuery and accelerate your time to insights. Learn more and get started with our comprehensive data warehouse migration guides.
* Predictive analytics
+
Predictive analytics helps you predict future outcomes more accurately and discover opportunities in your business. Our smart analytics reference patterns are designed to reduce time-to-value for common analytics use cases with sample code and technical reference guides.
* Bring any data into BigQuery
+
Make analytics easier by bringing together data from multiple sources in BigQuery, for seamless analysis. You can upload data files from local sources, Google Drive, or Cloud Storage buckets, take advantage of BigQuery Data Transfer Service (DTS), Data Fusion plug-ins, or leverage Google's industry-leading data integration partnerships. You have ultimate flexibility in how you bring data into your data warehouse.

== Authentication Types

Google BigQuery Connector uses the OAuth 2.0 authentication type, which uses access tokens provided by the authorization server to get access to protected data.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
