= Workday - Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/
:page-aliases: workday-studio.adoc, /docs-release-notes/connector/workday-connector-release-notes-mule-4.adoc

To configure Anypoint Connector for Workday: 

. Add the connector to your project from either Exchange or from within Anypoint Studio.
. Configure the connector.
. Configure an input source for the connector.

== Install the Connector Using Exchange

. In Studio, create a Mule Project.
. Click the Exchange *(X)* icon in the upper left of the Studio task bar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for Workday.
. Select Workday, click *Add to project*.
. Follow the prompts to install the Workday Connector.

== Install the Connector in Studio

. In Studio, create a Mule Project.
. In the Mule Palette, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type Workday in the search field.
. Click the Workday Connector name in *Available modules*.
. Click *Add*.
. Click *Finish*.

== Configure an Input Source

Configure an input source for the connector such as an operation for
the Workday connector, *HTTP Listener*, or *Scheduler*.

You can put the *On New Objects* operation for the connector in
the *Source* area of the Studio canvas.

  
. Select *Click here to set it up* to set the required fields for the *User Name*, *Password*,
and *Tenant Name*. This information is available from your Workday account.

== Configure the Connector

[%header,cols="30s,70a"]
|===
|Field |Description
|Configuration Name |The name of the configuration.
|Connection |The connection associated with the configuration.
|Username |The username to log in with.
|Password |The corresponding password.
|Tenant Name |The Workday Tenant ID, which usually has the suffix `pt_1` appended to it, such as `acme_pt1`.
|Host Name |The host name of one of Workday’s Cloud Servers. The default value is: `impl-cc.workday.com`.
|===

== To Increase Timeout in Studio

Depending on connectivity conditions while using Studio, there can be a timeout while obtaining
metadata from the Workday connector.

=== Symptoms

There can be two types of errors for this condition:

[source,text,linenums]
----
org.mule.runtime.api.exception.MuleRuntimeException: Error while retrieving soap client id [Absence_Management]
  org.mule.runtime.api.exception.MuleRuntimeException: Error while retrieving soap client id [Absence_Management]
  Caused by: java.util.concurrent.ExecutionException:
  org.mule.wsdl.parser.exception.WsdlParsingException: Error processing
  WSDL file [https://wd3-impl-services1.workday.com/ccx/service/deakin_amu1/Absence_Management/v29.1?wsdl]:
  Unable to locate document at 'https://wd3-impl-services1.workday.com/ccx/service/deakin_amu1/Absence_Management/v29.1?wsdl&#39;.
----

Or:

[source,text,linenums]
----
org.mule.tooling.client.api.exception.TimeoutException: Mule Agent REST service timed out
  org.mule.tooling.client.api.exception.TimeoutException: Mule Agent REST service timed out
  javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
  	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:244)
  	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:245)
  	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:671)
  	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:668)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
  	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
  	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:668)
  	at
----

=== Solution

When one of these conditions occurs:

. In Anypoint Studio, navigate to *Preferences > Anypoint Studio > Tooling*.  
. Double the values for `Default Connection Timeout` and `Default Read Timeout`. 
. Click *Apply*, and restart Studio.

== Next Step

After configuring the Workday Connector in Studio, see the xref:workday/workday-connector-examples.adoc[Examples] to experiment with the connector.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
