= Workday Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

Workday Connector Version 11.1.0

The Anypoint Connector for Workday provides access to standard Workday operations. 
Workday is a Software-as-a-Service (SaaS) solution developed by Workday Inc. It consists of a set of management applications, covering several areas like human resources management, staffing, recruiting and performance management.

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect 
to APIs and resources on external systems, such as Salesforce, Workday, ServiceNow,
and Twitter.

== Prerequisites

Before creating an app, you must have access to the Workday target resource and 
Anypoint Platform. You also need to understand how to create a Mule app using 
Design Center or Anypoint Studio.

== Audience

* Starting user -- To create your Mule app,
see xref:mule-workday-connector/workday-connector-design-center.adoc[Design Center Configuration]
or xref:mule-workday-connector/workday-connector-studio.adoc[Studio Configuration]. The
xref:mule-workday-connector/workday-connector-config-topics.adoc[Additional Configuration Information]
topic helps extend your understanding of the Workday connector. The
xref:mule-workday-connector/workday-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Power user - Read the xref:mule-workday-connector/workday-connector-xml-maven.adoc[XML and Maven Support],
xref:mule-workday-connector/workday-connector-config-topics.adoc[Additional Configuration Information],
and xref:mule-workday-connector/workday-connector-examples.adoc[Examples] topics.

== Common Use Cases For the Connector

The common use case for Workday connector is simply invoking any of Workday's standard operations. xref:mule-workday-connector/workday-connector-examples.adoc[Example use cases] include making a position request in Workday or adding a fund to the financial management service.

== Learn Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
you can use as a starting point for your app, as well as examples that illustrate a complete solution.

Examples and templates include:
* Adding a new customer to Workday Revenue Management (example)
* Workday and ServiceNow Employee Aggregation (template)
* Workday and SAP Worker (Employee) Aggregation (template)
* Workday to Salesforce Terminated Employee Broadcast (template)
* Workday to Salesforce Hired Employee Broadcast (template)
* Workday to Salesforce Employee Role Change Broadcast (template)
* Workday to Salesforce Employee Update Broadcast (template)
* Workday Worker to ServiceNow Service Request Migration (template)
* Workday Worker to ServiceNow User Broadcast (template)
* Workday and ServiceNow Worker Bi-Directional Sync (template)

== Next Step

After you have met the prerequisites and experimented with templates and examples, you are ready to create an app with
xref:mule-workday-connector/workday-connector-design-center.adoc[Design Center] or xref:mule-workday-connector/workday-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/?search=workday&type=connector[Anypoint Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]
