= Workday - Upgrade and Migrate - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Upgrade Anypoint Connector for Workday (Workday Connector) to version 12.0.0.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|11.1.2 |12.0.0
|===

== Changes in This Release

This release contains the following changes:

* Workday API upgraded to 34.0.
* New Student Core Operation/service added.
* The WORKDAY:UNKNOWN error type removed.
* *Reconnect* object changed (*blocking* field was removed)
* *Reconnect Forever* object changed (*blocking* field was removed)


== Changes in Connection Types

There are no changes related to connection types.

== Changed Operations, Parameters, and Return Types

There are no changes related to Operations, parameters, and return types.

== Changes in Operations Metadata

There are no changes related to keys, input metadata, or output metadata.

== Upgrade Prerequisites

Before you perform the upgrade, you must:

. Create a backup of your files, data, and configuration in case you need to restore to the previous version.
. Install Workday Connector v12.0 to replace the Workday operations that were previously included in Workday Connector v11.1.x.

== Upgrade Steps

Follow these steps to perform the upgrade from Workday Connector v11.1.x to Workday Connector v12.0:

. In Anypoint Studio, create a Mule project.
. In the Mule Palette view, click *Search in Exchange*.
. In the *Add Dependencies to Project* window, enter `Workday` in the search field.
. In the *Available modules* section, select *Workday Connector - Mule 4* and click *Add*.
. Click *Finish*.
. Verify that the `workday-connector` dependency version is `12.0.0` in the `pom.xml` file.

Studio upgrades the connector automatically.


== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Check the project `pom.xml` file and verify that there are no problems.
. Test the connection and verify that the operations work.

== Troubleshooting

If there are problems with caching the parameters and caching the metadata, try restarting Studio.

== Revert the Upgrade

If it is necessary to revert to the previous version of Workday Connector, change the `workday-connector` dependency version `12.0.0` in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
