= Upgrade Commerce Cloud B2C Shop Connector to Version 2.0 - Mule 4

Upgrade Anypoint Connector for Salesforce Commerce Cloud B2C Shop APIs (B2C Shop Connector) to take advantage of the functionality provided by the Shopper Customer APIs version 0.0.24.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|1.x.x |2.x.x
|===

== Changes in This Release

* The connector is updated with the latest Salesforce Commerce B2C Shop APIs. 
* The Shopper Customer endpoints that did not work in the previous version of the connector are fixed.


== Upgrade Prerequisites

Before you perform the upgrade, you must create a backup of your files, data, and configurations in case you need to restore to them. 

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `commerce cloud b2c shop` in the search field.
. In *Available modules*, select *<connector>* and click *Add*.
. Click *Finish*.
. Verify that the <connector> dependency version is <latest-version> in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.


=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Troubleshoot

If there are common known issues and errors that occur when upgrading, give troubleshooting tips.

=== Revert the Upgrade

If it is necessary to revert to the previous version of B2C Shop Connector, change the `connector-name-dependency` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.
