= Upgrade Commerce Cloud B2C Shop Connector to Version 2.0 - Mule 4

Upgrade Anypoint Connector for Salesforce Commerce Cloud B2C Shop APIs (B2C Shop Connector) to take advantage of the functionality provided by the Shopper Customer APIs version 0.0.24.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|1.x.x |2.x.x
|===

== Changes in This Release

The Shopper Customer APIs were upgraded to version 0.0.24. 

* // List all changes that affect users, including changed schemas, 
// changed data structures, changed POM files, changed and new fields 
// (locations, names, etc.) and parameters, deprecated parameters, etc.
// Examples:
//
// * The create operation name changed from <old-name> to <new-name>.
// * The <field-name> is now located in the <tab-name> tab.
// * What happens with the upgrade? Are changes made to app data? 
// * The single global configuration is divided into operation and source-specific global configurations like:
// ** send-config
//Used by send-with-sync-mdn and send-with-async-mdn operations
// ** listener-config
//Used by as2-listener source
// ** mdn-listener-config
Used by as2-mdn-listener source.
// * Changed namespace from <old-namespace> to <new-namespace>.

// If applicable, use tables to describe new and changed operations and sources. Examples follow: 

////
[[new_operations]]
== New Operations

[%header%autowidth.spread]
|===
|<connector> Operation | Description | Parameters
| Enter the name of the operation. Example: Commit
a| Enter a description for the operation. Example: Commits the offsets associated to a message or batch of messages consumed in a message listener. a| Specify the operation parameters. Example: Consumer commit key
|===


[[changed_operations]]
== Changed Operations

[%header%autowidth.spread]
|===
|<connector> Operation | Description | Parameters

| Enter the name of the operation. Example: Commit
a| Enter a description for the operation. Example: Commits the offsets associated to a message or batch of messages consumed in a message listener. a| Specify the operation parameters. Example: Consumer commit key
|===


[[new_sources]]
== New Sources

[%header%autowidth.spread]
|===
|<connector> Source | Description | Parameters

| Enter the name of the source. Example: Batch message listener
a| Enter a description for the source. Example: The message list that was obtained in the poll is handled by a flow as a single event, so the handling of concurrency is simpler than in the simple message listener. a| Enter the parameters. Example: * Poll timeout
* Poll timeout time unit
* Acknowledgment mode
* Number of parallel consumers
|===

[[changed_sources]]
== Changed Sources

[%header%autowidth.spread]
|===
|<connector> Source | Earlier Version | Parameters

| <name-in-new-version> Example:Message listener | <name-in-oldMessage consumer a| * Poll timeout
* Poll timeout time unit
* Acknowledgment mode
* Number of parallel consumers
|===
////


== Upgrade Prerequisites

Before you perform the upgrade, you must create a backup of your files, data, and configurations in case you need to restore to them. 

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `commerce cloud b2c shop` in the search field.
. In *Available modules*, select *<connector>* and click *Add*.
. Click *Finish*.
. Verify that the <connector> dependency version is <latest-version> in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.


=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Troubleshoot

If there are common known issues and errors that occur when upgrading, give troubleshooting tips.

=== Revert the Upgrade

If it is necessary to revert to the previous version of B2C Shop Connector, change the `connector-name-dependency` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.
