= Commerce Cloud B2C Shop Connector - Troubleshoot - Mule 4

There are a few scenarios when the Commerce Cloud B2C Shop Connector might return 4XX errors.

*400 Bad Request*

Commerce Cloud B2C Shop Connector might return a `400 Bad Request` error response if the URI parameters, such as Organization Id, Site Id, and Version parameters are not passed with the proper values, for example:

** The parameters are passed with the wrong values.
** The parameters are passed with an extra space.

== Solution

Correct and pass the proper values.

*401 Unauthorized*

Commerce Cloud B2C Shop Connector might return a `401 Unauthorized` error response in the following cases:

* The Client Id used in the configuration is incorrect.
* The Client Secret used in the configuration is incorrect.

== Solutions

* Correct and pass the proper values for the Client ID and Client Secret.
* If the Client Id and Client Secret are both correct and you are still getting the error, contact the Commerce Cloud team.

*403 Forbidden*

Commerce Cloud B2C Shop Connector might return a `403 Forbidden` error response if the Scopes used in the configuration are incorrect.

== Solution

* Correct and pass the proper values for the Scopes.

*405 Method Not Allowed*

Commerce Cloud B2C Shop Connector method returns a `405 Method Not Allowed` error when a resource that previously supported an HTTP POST got removed and had its HTTP GET method deprecated because of business decisions.

== Solution

* Contact the Commerce Cloud team.

*415 Unsupported Media Type*

Commerce Cloud B2C Shop Connector might return a `415 unsupported media type` error response in these cases:

* The body type the user is passing to the connector `Content` parameter does not match the required input type.
* Expression mode is enabled and the output type of the body is not defined as `application/json`.

== Solution

* Use the correct type for the body.
* Enable Expression mode and define the output type of the body as `application/json`.

== See Also

* xref:connectors::introduction/anypoint-connector-authentication.adoc[Anypoint Connector Authentication]
* https://help.mulesoft.com[MuleSoft Help Center]
