= MongoDB XML and Maven Support - Mule 4
:page-aliases: connectors::mongodb/mongodb-connector-xml-maven.adoc

If you manually code a Mule app in XML either from the Anypoint Studio XML editor or from a text editor, you can get access to the <connector> in your app by adding reference statements to your XML Mule flow and in the Apache Maven pom.xml file.

[NOTE]
====
You can avoid the manual process described in this topic by using Studio. When you install the MongoDB Connector in Anypoint Studio, Studio automatically populates the XML code with the MongoDB Connector namespace and schema location, and adds a dependency to the `pom.xml` file.
====


== Add a Namespace for the Connector

Paste the following into the header of your configuration XML, inside the `<mule>` tag:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/mongodb
http://www.mulesoft.org/schema/mule/mongodb/current/mule-mongodb.xsd
----

This example shows how the namespace statements are placed in the mule XML block:

[source,xml,linenums]
----
<mule xmlns:mongodb="http://www.mulesoft.org/schema/mule/mongodb"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/file
	http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
	http://www.mulesoft.org/schema/mule/http
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/core
	http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
	http://www.mulesoft.org/schema/mule/mongodb
	http://www.mulesoft.org/schema/mule/mongodb/current/mule-mongodb.xsd">
----

== Add a POM File Dependency

The `pom.xml` Maven file generated by Anypoint Studio contains dependencies for a Mule app. When you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to this connector. 

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-mongodb-connector</artifactId>
  <version>x.x.x</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

Replace `x.x.x` with the version that corresponds to the connector you are using.

To obtain the most up-to-date `pom.xml` file information, access the connector in https://www.mulesoft.com/exchange/[Anypoint Exchange] and click *Dependency Snippets*.

== Next

After completing your namespace and `pom.xml` file, you can try out the MongoDB xref:mongodb-connector-examples.adoc[Examples].

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
