= MongoDB Design Center Configuration - Mule 4
:page-aliases: connectors::mongodb/mongodb-connector-design-center.adoc

Design Center enables you to create apps visually. To use Design Center, work with your Anypoint Platform administrator to ensure that you have a xref:access-management::environments.adoc#to-create-a-new-environment[Design environment]. For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour].

To create an app in Design Center:

* Configure the input source (trigger) for your app.
* Add the connector as a component to process the input for the app.

For information on Design Center field values, see the xref:mongodb-connector-reference.adoc[MongoDB Connector Reference].

== Configure the Trigger

. In Design Center, click *Create*.
. Click *Create new application*.
. Specify a value for *Project name*.
. Exit from *Let's get started* by clicking *Go straight to canvas*.
. Click the name of the trigger card.
. If you are using the MongoDB connector as an input source trigger, choose an operation:
+
** *Deleted Objects* - The trigger your app uses when a MongoDB user deletes an object.
** *Modified Objects* - The trigger your app uses when a MongoDB user modifies an object.
** *New Object* - The trigger your app uses when a MongoDB user creates an object.
+
Alternatively, you can trigger your app using the HTTP Listener or the Scheduler.
+
. If you are using the MongoDB connector as a trigger, refer to these reference sections for values:
+
** xref:mongodb-connector-reference.adoc#deleted-object-trigger[Deleted Objects]
** xref:mongodb-connector-reference.adoc#modified-object-trigger[Modified Objects]
** xref:mongodb-connector-reference.adoc#new-object-trigger[New Object]

Design Center automatically saves changes you make in a session.

== Configure the Target Component

. Click *+* next to the trigger card.
. In *Select a component*, search for the connector name.
. Select the connector name.
. Select an operation for the connector.
. Enter the required values in the *General* tab.
. If needed, enter values for other tabs.
. Specify access information to the connector resource.
. Click *Test Connection* to ensure you have access to MongoDB.

Complete these fields to set up a MongoDB configuration:
+
[%header%autowidth.spread]
|===
|Fields |Description
|Required Libraries |Reference to the MongoDB Driver. The version must be 3.11 or higher.
|Servers |List of server addresses to use for the connection.
|Database |MongoDB database
|Username |MongoDB username
|Password |MongoDB password
|===

To make a simple flow, you can select these operations:

* Insert Document:
+
[%header%autowidth.spread]
|===
|Fields |Description
|*Collection Name* |This location points to the collection you want. This collection needs to be created in the database which you have selected before.
|===
+
* Find a document and update it.
* Remove the document.

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
