= LDAP Connector 3.7
:page-aliases: connectors::ldap/ldap-connector.adoc



Anypoint Connector for Lightweight Directory Access Protocol (LDAP) is a public standard that facilitates maintenance and access to distributed directories (such as network user privilege information) over an Internet Protocol (IP) network.

LDAP Connector supports LDAP over SSL, LDAP over TLS, and a Secure SSL connection type for FIPS 140-3 compliant deployments.

Many LDAP servers are included in free-use open source projects and packages. The particulars of installing, running, and configuring LDAP servers fall outside the scope of this document.

For information about compatibility and fixed issues, see the LDAP Connector Release Notes.

[[prerequisites]]
== Before You Begin

To use this connector, you must be familiar with:

* The LDAP Connector’s API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access an OpenLDAP instance that supports LDAP v3
* Anypoint Platform
* Anypoint Studio version 7.0 or later

== Common Use Cases For the Connector

Common use cases for LDAP Connector include:

* Adding user accounts to Active Directory
+
You can add business users to Active Directory groups defined on the base distinguished name (DN).
+
* Retrieving user attributes
+
You can retrieve the basic attributes of a business user such as a user's e-mail or phone number.

== Connection Types

LDAP Connector supports four types of connections:

* Basic
+
Communications are not encrypted.
+
NOTE: If running in an instance configured with `mule.security.model=fips140-2`, attempting to use a Basic connection returns an `LDAP:SECURITY` error.
+
* SSL
+
Communications are encrypted using Secure Sockets Layer (SSL). Accepts a custom truststore path for certificate validation.
+
* Secure SSL
+
Communications are encrypted using SSL and accept a Mule TLS context factory for trust store configuration. This connection type is required for FIPS 140-3 compliant deployments, and is also supported in non-FIPS environments with any trust store type provided via *TLS Context*.
+
* TLS
+
Communications are encrypted using Transport Layer Security (TLS).

You can use Basic (username and password) authentication for each of these connection types.

For more information about configuring connection types and authentication, see xref:ldap-connector-use-studio.adoc[Using Studio to Configure LDAP Connector].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:ldap-connector-reference.adoc[LDAP Connector Reference]
* https://help.salesforce.com[Salesforce Help]
