= WSS Module XML and Maven Support - Mule 4

If you manually code a Mule application in XML either from the Studio XML editor or a text editor, you must perform the following actions to get access to a connector:

Add the namespace for the connector to your XML flow.

Add dependency information to your Maven pom.xml file.

In the Studio visual editor, when you drag a connector from the Mule Palette to the canvas, Studio automatically populates the XML code with the connector namespace and schema location.

// Ensure that XML code examples have line breaks after XML elements
// to reduce the need for users to scroll the code horizontally to read it.

== Add a Namespace for the Connector

If you manually code the Mule application in the Studio XML editor or another
text editor, paste the following code inside the <mule> tag in your XML
configuration:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/...
http://www.mulesoft.org/schema/mule/...
----


This example shows how the namespace statements are
placed in the `mule` XML block:

[source,xml,linenums]
----
<mule ...>
----

== Add a POM File Dependency

The `pom.xml` Apache Maven file generated by Anypoint Studio contains dependencies
for a Mule app. When you code a Mule app manually, include this XML snippet in
your POM file to enable access to this connector:

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>...</artifactId>
  <version>x.x.x</version>
  <classifier>mule-plugin</classifier>
</dependency>
----
// Writer: Replace GROUP_ID_FROM_EXCHANGE, ARTIFACT_ID_FROM_EXCHANGE with correct information from Exchange.

Replace `x.x.x` with the version that corresponds to the connector you are using.

To obtain the most up-to-date pom.xml file information:

. Go to https://www.mulesoft.com/exchange/[Anypoint Exchange].
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for `WSS Module`.
. Select the connector.
. Click *Dependency Snippets* near the upper right of the screen.

== Next Step

After completing your namespace and `pom.xml` file, you can try
the xref:wss-examples.adoc[Examples].

== See Also

* xref:connectors::introduction/anypoint-connector-authentication.adoc[Anypoint Connector Authentication]
* https://help.mulesoft.com[MuleSoft Help Center]
