= Veeva Vault Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Veeva Vault Connector Version 1.1.0

Anypoint Connector for Veeva Vault (Veeva Vault Connector) enables you to connect Mule flows to the Veeva Vault platform using the Veeva Vault REST API.

This connector works with the https://developer.veevavault.com/api/19.1/#authentication[Veeva Vault REST, Bulk, and Streaming API], depending on the operations you configure. Each API call uses a JSON or CSV request and returns JSON input stream responses over an HTTPS connection. All required request headers, error handling, and HTTPS connection configurations are built into the connector.

You can use Veeva Vault Connector in Mule applications as an outbound connector with CRUD (create, retrieve, update, delete), query, export, and Spark validator operations on the following Veeva Vault objects:

* Documents: Create, retrieve, update, delete, export
* Document Renditions: create, retrieve, delete
* Vault Object: create, retrieve, update, delete
* Picklists: Retrieve
* Audit Trail: Retrieve
* Query: VQL auery to query on documents, Vault objects, workflows
* Spark validator: Validates and verifies the Spark message with signature that is triggered from Veeva Vault

You can configure Veeva Vault Connector using basic authentication with credentials to connect to a Veeva Vault instance and perform operations.

== About Connectors

Anypoint Connectors are Mule runtime engine (Mule) extensions that enable you to connect to APIs and resources on external systems, such as Salesforce, Veeva Vault, ServiceNow, Twitter, and so on.

== Prerequisites

To use this information, you must be familiar with http://vaulthelp2.vod309.com/wordpress/vault-basics/[Veeva Vault], https://developer.veevavault.com/vql/#introduction-to-vault-queries[Vault Query Language (VQL)], Mule runtime engine (Mule), Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and Global Elements.

Before creating an app, you must:

* Have an AnyPoint Platform account
* Have a Veeva Vault account to access the Veeva Vault target resources
* Understand how to create a Mule app using Design Center or Anypoint Studio

== Audience

* Starting user +
To create your Mule app, see xref:veevavault/veevavault-connector-design-center.adoc[Design Center Configuration] or xref:veevavault/veevavault-connector-studio.adoc[Studio Configuration]. +
The xref:veevavault/veevavault-connector-config-topics.adoc[Additional Configuration Information]
topic helps extend your understanding of Veeva Vault Connector. +
The xref:veevavault/veevavault-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Power user +
Read the xref:veevavault/veevavault-connector-xml-maven.adoc[XML and Maven Support], xref:veevavault/veevavault-connector-config-topics.adoc[Additional Configuration Information], and xref:veevavault/veevavault-connector-examples.adoc[Examples] topics.

== Learn Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates you can use as a starting point for your app, as well as examples that illustrate a complete solution. The following templates are available for Veeva Vault Connector: 

* https://anypoint.mulesoft.com/exchange/c5788341-a495-4d6f-a931-875757082c63/filesystem-to-veeva-vault-template/[FileSystem to Veeva Vault]
* https://anypoint.mulesoft.com/exchange/c5788341-a495-4d6f-a931-875757082c63/veevavault-connector-project-templates/[Veeva Vault to FileSystem]
* https://anypoint.mulesoft.com/exchange/c5788341-a495-4d6f-a931-875757082c63/spark-message-solution-template/[Spark Message End Solution]

== Next Step

After you complete the prerequisites and experiment with the templates and examples, you are ready to create an app with xref:veevavault/veevavault-connector-design-center.adoc[Design Center] or xref:veevavault/veevavault-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:release-notes::connector/veevavault-connector-release-notes.adoc[Veeva Vault Connector Release Notes] 
* https://www.mulesoft.com/exchange/?search=veevavault&type=connector[Veeva Vault Connector]
* https://help.mulesoft.com[MuleSoft Help Center]
