= VeevaVault Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Veeva Vault Connector Version 1.1.0

Anypoint Connector for Veeva Vault lets you connect Mule flows to the Veeva Vault platform using the Veeva REST API depending on the operation you configure.

This connector works with the https://developer.veevavault.com/api/19.1/#authentication[Veeva Vault REST, Bulk, and Streaming API], depending on the operation you configure. Each API call uses an JSON/CSV request and returns JSON input stream response over an HTTPS connection. All required request headers, error handling, and HTTPS connection configurations are built into the connector.

The Veeva Vault Connector can be use in the Mule application as an outbound connector with CRUD (Create, Retrieve, Update, Delete), Query, Export, Spark Validator operations on following Vault Objects. These operations are discussed later in this document.

* Documents – Create, Retrieve, Update, Delete, Export.
* Document Renditions – Create, Retrieve, Delete.
* Vault Object – Create, Retrieve, Update, Delete.
* Picklists – Retrieve.
* Audit Trail – Retrieve.
* Query – VQL Query to query on Documents, Vault Object, Workflows.
* Spark Validator – Validates and verifies the Spark message triggered from Vault with signature.

You can configure the Veeva Vault Connector using Basic Authentication configuration with credentials to connect to a Veeva Vault instance and perform operations.

Release Notes: xref:release-notes::connector/veevavault-connector-release-notes.adoc[Veeva Vault Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/?search=veevavault&type=connector[Veeva Vault Connector]

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect to APIs and resources on external systems, such as Salesforce, Veeva Vault, ServiceNow, Twitter etc.

== Prerequisites

To use this information, you must be familiar with http://vaulthelp2.vod309.com/wordpress/vault-basics/[Veeva Vault], https://developer.veevavault.com/vql/#introduction-to-vault-queries[Vault Query Language (VQL)], Mule runtime engine (Mule), Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and Global Elements.

Before creating an app, you must have access to the Veeva Vault target resource and Anypoint Platform. You also need understand how to create a Mule app using
Design Center or Anypoint Studio.

To use this connector, you need:

* AnyPoint Platform Account.
* Veeva Vault account.

== Audience

* Starting user -- To create your Mule app, see xref:./veevavault-connector-design-center.adoc[Design Center Configuration] or xref:./veevavault-connector-studio.adoc[Studio Configuration]. The xref:./veevavault-connector-config-topics.adoc[Additional Configuration Information]
topic helps extend your understanding of the Veeva Vault connector. The xref:./veevavault-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Power user -- Read the xref:./veevavault-connector-xml-maven.adoc[XML and Maven Support], xref:./veevavault-connector-config-topics.adoc[Additional Configuration Information], and xref:./veevavault-connector-examples.adoc[Examples] topics.

== Learn Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates you can use as a starting point for your app, as well as examples that illustrate a complete solution. Following are the templates available with use case.

* https://anypoint.mulesoft.com/exchange/c5788341-a495-4d6f-a931-875757082c63/filesystem-to-veeva-vault-template/[FileSystem to VeevaVault]
* https://anypoint.mulesoft.com/exchange/c5788341-a495-4d6f-a931-875757082c63/veevavault-connector-project-templates/[VeevaVault to FileSystem]
* https://anypoint.mulesoft.com/exchange/c5788341-a495-4d6f-a931-875757082c63/spark-message-solution-template/[Spark Message End Solution]

== Next Step

After you have met the prerequisites and experimented with templates and examples, you are ready to create an app with xref:./veevavault-connector-design-center.adoc[Design Center] or xref:./veevavault-connector-studio.adoc[Anypoint Studio].

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
