= Salesforce Data Cloud Connector 1.5  

Anypoint Connector for Salesforce Data Cloud (Salesforce Data Cloud Connector) provides a quick and easy way to integrate with Salesforce Data 360 (formerly Salesforce Data Cloud) API endpoints. You can automate data ingestion from third parties, query the Data 360 Data Lake, search and query customer profile information and calculated insights, and consume data action events to enrich the 360-degree view of the customers in your Data 360 instance.

Each API call uses a request/response pattern over an HTTPS connection. All required request headers, error handling, and HTTPS connection configurations are built into the connector.

For information about compatibility and fixed issues, refer to the Salesforce Data Cloud Connector release notes.

== Before You Begin

To use this connector, you must be familiar with:

* https://developer.salesforce.com/docs/data/data-cloud-int/references/data-cloud-ingestionapi-ref/c360-a-api-get-started.html[The Salesforce Data 360 Ingestion API]
* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Anypoint Connectors]
* xref:mule-runtime::index.adoc[Mule runtime engine] (Mule)
* xref:mule-runtime::global-elements.adoc[Elements and global elements] in a Mule flow
* xref:mule-runtime::mule-app-dev.adoc[How to create a Mule app using Anypoint Studio]

Before creating an app, you must have:

* <<set-up-the-ingestion-api, Set up the Ingestion API>>
* Credentials to access the Salesforce Data 360 target resource
* Anypoint Platform
* Anypoint Studio version 7.11.x or later

[[set-up-the-ingestion-api]]
== Set Up the Ingestion API

To use Salesforce Data Cloud Connector, you must first set up the Ingestion API. For more information, refer to https://docs.mulesoft.com/salesforce-data-cloud-connector/latest/[Connect MuleSoft with Data 360]. 

After setting up the Ingestion API, refer to <<next-step>> to configure your connector.

== Common Use Cases For the Connector

These are some common use cases for Salesforce Data Cloud Connector:

* Stream data via insert and delete object endpoints of the Ingestion API Connector
* Create a bulk job, upload job data, close or abort a job, get a job status, retrieve all bulk jobs, and delete a job as part of the Bulk Ingestion interaction pattern of the Ingestion API Connector
* Query Data 360 objects
* Query Salesforce Data 360 data lake across data model, lake, unified, and linked objects
* Query calculated insights with selected dimensions, selected measures, and optional filters
* Look up and search customer profile information
* Create webhooks as data action targets for data actions in Data 360

For examples, see xref:salesforce-data-cloud-connector-examples.adoc[Salesforce Data Cloud Connector Examples] use cases.

== Connection Types

Salesforce Data Cloud Connector uses these authentication types:

* OAuth Client Credentials
+
Uses OAuth 2.0 with a token endpoint for authentication
* OAuth JWT 
+
Uses OAuth 2.0 with a JSON Web token (JWT) request for authentication
* OAuth Username Password 
+
Uses OAuth 2.0 with a username and password for authentication

For information about configuring authentication types, see xref:salesforce-data-cloud-connector-studio.adoc[Using Anypoint Studio to Configure Salesforce Data Cloud Connector].

[[next-step]]
== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:salesforce-data-cloud-connector-studio.adoc[Anypoint Studio].

== See Also

* https://help.salesforce.com/s/articleView?id=data.c360_a_customer360_lm.htm&type=5[Salesforce Data 360]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:salesforce-data-cloud-connector-reference.adoc[Salesforce Data Cloud Connector Reference]
* https://help.salesforce.com[Salesforce Help]
