= Use Cases - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Use Case: Studio

Create a Cassandra keyspace, which groups column families, then create a Cassandra table.

=== Create a Keyspace


. Create a new Mule Project in Anypoint Studio and fill in the Cassandra credentials in `src/main/resources/mule-app.properties`.
+
[source,text,linenums]
----
config.host=<HOST>
config.port=<PORT>
config.keyspace=<KEY_SPACE>
config.username=<USERNAME>
config.password=<PASSWORD>
----
+
. Drag an HTTP connector onto the canvas and leave the default values for Host and Port and set the path to `/test/createKeyspace`.
+
.Drag a Transform Message component from the Mule palette to the right (process) side of the flow, select the component, and set the output payload. For example:
+
[source,dataweave,linenums]
----
%dw 2.0
output application/java
---
{
  "keyspaceName": payload.keyspaceName,
  "replicationFactor": payload.replicationFactor,
  "replicationStrategyClass": payload.replicationStrategyClass
} as Object {
  class : "org.mule.modules.cassandradb.api.CreateKeyspaceInput"
}
----
+
. Drag a Cassandra component for Create Keyspace onto the canvas.
+
[%header%autowidth.spread]
|===
|Field |Description
|Host | Enter a host name, or IP address of a Cassandra node.
|Port | Enter a port number. The default port is 9042.
|Keyspace | Enter the Cassandra keyspace. A keyspace groups column families.
|Username | Enter a Cassandra user name, if you enabled PasswordAuthenticator in the Cassandra YAML file. If AllowAllAuthenticator is enabled, leave this value blank.
|Password | Enter the password, if you enabled PasswordAuthenticator. Otherwise leave this value blank.
|===
+
*Note:* Click the Test Connection option to confirm that Mule can connect with the Cassandra instance. If the connection is successful, click OK to save the configuration. Otherwise, review and correct any invalid parameters and retest.
+
. Run the application. In a browser, use the following URL to enter a query parameter for the keyspace name (ks_name), replication factor (rf), and replication strategy class (rs_class):
+
`+http://localhost:8081/simple?ks_name=simple_keyspace&rf=3&rs_class=SimpleStrategy+`

=== Create a Cassandra Table

. Create a new Mule Project in Anypoint Studio and fill in the Cassandra credentials in `src/main/resources/mule-app.properties`.
+
[source,text,linenums]
----
config.host=<HOST>
config.port=<PORT>
config.keyspace=<KEY_SPACE>
config.username=<USERNAME>
config.password=<PASSWORD>
----
+
. Drag an HTTP connector onto the canvas and leave the default values for Host and Port and set the path to `/test/createTable`.
+
. Drag a Transform Message component from the Mule palette to the right (process) side of the flow, select the component, and set the output payload. For example:
+
[source,dataweave,linenums]
----
%dw 2.0
output application/java
---
{
  "columns": payload.columns,
  "tableName": payload.tableName,
  "keyspaceName": payload.keyspaceName
} as Object {
  class : "org.mule.modules.cassandradb.api.CreateTableInput"
}
----
+
. Drag a Cassandra component for the Create Table operation onto the canvas.
+
[%header%autowidth.spread]
|===
|Field |Description
|Host | Enter a host name, or IP address, of a Cassandra node.
|Port | Enter a port number. The default port is 9042.
|Keyspace | Enter the Cassandra keyspace. A keyspace groups column families.
|Username | Enter a Cassandra user name if you enabled PasswordAuthenticator in the Cassandra YAML file. If AllowAllAuthenticator is enabled, leave this value blank.
|Password | Enter the password if you enabled PasswordAuthenticator; otherwise, leave this value blank.
|===
+
*Note:* Click the Test Connection option to confirm that Mule can connect with the Cassandra instance. If the client test is successful, click OK to save the configuration. Otherwise, review or correct any invalid parameters and retest.
+
. Run the Mule app. In Postman, select POST. Select Body > Raw, select the JSON (application/json) MIME type, and enter the following table description using uppercase for data types.
+
[source,text,linenums]
----
{
  "tableName": "users",
  "keyspaceName": "Excelsior",
  "columns":
  [
    {
      "name": "id",
      "type": "INT",
      "primaryKey": "true"
    },
    {
      "name": "username",
      "type": "TEXT",
      "primaryKey": "true"
    },
    {
      "name": "name",
      "type": "TEXT",
      "primaryKey": "false"
    },
    {
      "name": "email",
      "type": "TEXT",
      "primaryKey": "false"
    }
  ]
}
----
+
. In Postman, click Send, and look for Status: 200 OK.


== XML Flows
Copy and paste this XML code into Anypoint Studio to experiment with the flow described in the previous section.

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:cassandra-db="http://www.mulesoft.org/schema/mule/cassandra-db"
xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
xmlns:http="http://www.mulesoft.org/schema/mule/http"
xmlns="http://www.mulesoft.org/schema/mule/core"
xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core
http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http
http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/core
http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
http://www.mulesoft.org/schema/mule/cassandra-db
http://www.mulesoft.org/schema/mule/cassandra-db/current/mule-cassandra-db.xsd">

  <configuration-properties file="mule-app.properties" />
  <http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config">
    <http:listener-connection host="0.0.0.0" port="8081" />
    </http:listener-config>
  <cassandra-db:config name="CassandraDB_Config" doc:name="CassandraDB Config">
    <cassandra-db:connection host="${config.host}" port="${config.port}" keyspace="${config.keyspace}" username="${config.username}" password="${config.password}"/>
	</cassandra-db:config>
  <flow name="HTMLForm">
    <http:listener doc:name="Listener" config-ref="HTTP_Listener_config" path="/"/>
    <parse-template doc:name="Parse Template" location="form.html"/>
  </flow>
  <flow name="CreateKeyspace">
    <http:listener doc:name="Listener" config-ref="HTTP_Listener_config" path="/createKeyspace"/>
    <ee:transform doc:name="Transform Message">
      <ee:message >
        <ee:set-payload ><![CDATA[%dw 2.0
output application/java
---
{
  "keyspaceName": payload.keyspaceName,
  "replicationFactor": payload.replicationFactor,
  "replicationStrategyClass": payload.replicationStrategyClass
} as Object {
  class : "org.mule.modules.cassandradb.api.CreateKeyspaceInput"
}]]></ee:set-payload>
      </ee:message>
    </ee:transform>
    <cassandra-db:create-keyspace doc:name="Create keyspace" config-ref="CassandraDB_Config"/>
    <ee:transform doc:name="Transform Message">
      <ee:message >
        <ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
      </ee:message>
    </ee:transform>
  </flow>
  <flow name="CreateTable">
    <http:listener doc:name="Listener" config-ref="HTTP_Listener_config" path="/createTable"/>
    <ee:transform doc:name="Transform Message">
      <ee:message>
        <ee:set-payload><![CDATA[%dw 2.0
output application/java
---
{
  "columns": payload.columns,
  "tableName": payload.tableName,
  "keyspaceName": payload.keyspaceName
} as Object {
  class : "org.mule.modules.cassandradb.api.CreateTableInput"
}]]></ee:set-payload>
      </ee:message>
    </ee:transform>
    <cassandra-db:create-table doc:name="Create table" config-ref="CassandraDB_Config"/>
    <ee:transform doc:name="Transform Message">
      <ee:message>
        <ee:set-payload><![CDATA[%dw 2.0
output application/json
---
payload]]></ee:set-payload>
      </ee:message>
    </ee:transform>
  </flow>
</mule>
----


== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
