= Additional Cassandra Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Refer to the following when configuring Cassandra to work in your environment.

== Configure Cassandra Authentication

The Cassandra connector configuration needs to match the Cassandra configuration with regard to Basic Authentication.
By default, accessing the Cassandra database does not require credentials.
You need to configure Cassandra to enable authentication.
After enabling authentication, you can run the `cqlsh` command from the Cassandra installation home directory as shown in this example that uses default credentials with username cassandra and password cassandra:

[source,text,linenums]
----
bin/cqlsh localhost -u cassandra -p cassandra
Connected to Test Cluster at localhost:9042.
[cqlsh 5.0.1 | Cassandra 3.10 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
----

. After installing Cassandra, open `conf\cassandra.yaml` file for editing.
. Optionally, change the value of AllowAllAuthenticator to PasswordAuthenticator.
. Restart Cassandra.
. In a separate terminal tab, check that Cassandra is running:
+
`bin/nodetool status`

== POJO configuration

The connector exposes multiple operations in the Cassandra Connector Reference.
The following operations accept some POJOs as input parameters that are needed for the DataSense functionality:
These are: `addNewColumn`, `changeColumnType`, `createKeyspace`, `createTable`, `deleteColumnsValue`, `deleteRows`, `dropColumn`, `dropKeyspace`, `dropTable`, `executeCQLQuery`, `getTableNamesFromKeyspace`, `renameColumn`, `select`, and `update`.
