= Cassandra Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

Cassandra Connector v1.0

The Cassandra connector implements the DataStax Java Driver for Apache Cassandra 3.1. The connector exposes multiple operations in the Cassandra Connector Reference.

Certain operations accept some custom POJOs as input parameters, and these are needed for the DataSense functionality.

These are: addNewColumn, changeColumnType, createKeyspace, createTable, deleteColumnsValue, deleteRows, dropColumn, dropKeyspace, dropTable, executeCQLQuery, getTableNamesFromKeyspace, renameColumn, select, and update.

== Topics
* xref:cassandra/cassandra-xml-maven.adoc[Cassandra-Connector.adoc - XML and Maven Support]
* xref:cassandra/cassandra-design-center.adoc[Cassandra-Connector.adoc - Design Center]
* xref:cassandra/cassandra-studio.adoc[Cassandra-Connector.adoc - Studio]
* xref:cassandra/cassandra-config-topics.adoc[Cassandra-Connector.adoc - Configuration Topics]
* xref:cassandra/cassandra-use-cases.adoc[Cassandra-Connector.adoc - Use Cases]

== Prerequisites

Familiarity with Cassandra, Mule, Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and Global Elements.

A set of valid login credentials to test your connection to your target resource.

Refer to the Connector Release Notes for compatibility information.

== Templates and Examples
<No existing examples>

== Triggers
. In Design Center, click Set Up > Upload, browse for and select the driver for this connector on your file system, and upload it. Or, search for and select a driver that is already uploaded.
. Click a trigger. You can create a global element by selecting this connector as the trigger.
If a global element is not required, use an HTTP Listener or a Scheduler as the trigger.
+

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
