= Anypoint Connector for Cassandra - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

Cassandra Connector v3.1.1

Anypoint Connector for Cassandra (Cassandra Connector) creates connectivity between Cassandra databases and third-party applications, systems, services such as SAP, PeopleSoft, or Workday, as well as other databases across the enterprise.
Apache Cassandra is an open source distributed NoSQL database intended to manage large amounts of product, customer, and employee data, which implements the DataStax Java Driver for Apache Cassandra 3.1.

== About Connectors

Anypoint Connectors are extensions of Mule that let you work with external systems such as Cassandra, Salesforce, ServiceNow, Workday, Twitter, and more to send and receive information from these systems to create something new.
Anypoint Connectors let you connect Mule applications to APIs and resources.
A connector lets you send and receive data over a protocol, or to and from an API.
Use this information to work with Design Center or Anypoint Studio to adjust the UI settings to enable the connector to work with a Mule app.

== Prerequisites

Before starting, ensure you have access to the connector, Anypoint Platform, Design Center, or Anypoint Studio.
You should have the Mule Enterprise Edition and entitlements necessary to use this software.
You should be familiar with the use of Anypoint Platform, Design Center, Anypoint Studio, and Mule applications.

Requirements for using the connector:

 * Cassandra Login credentials to test your connection to your target resource.

== Audience

* Starting user - Use this Get Started to see where you can create a Mule application in xref:cassandra/cassandra-connector-design-center.adoc[Design Center] or xref:cassandra/cassandra-connector-studio.adoc[Anypoint Studio].
* The xref:cassandra/cassandra-connector-config-topics.adoc[Configuration Topics] help you extend your understanding of Cassandra actions.
* Power user - Read the xref:cassandra/cassandra-connector-xml-maven.adoc[XML and Maven Support], xref:cassandra/cassandra-connector-config-topics.adoc[Configuration Topics], and xref:cassandra/cassandra-connector-examples.adoc[Example] documents.


== Next

Now that you've started, try using xref:cassandra/cassandra-connector-design-center.adoc[Design Center] or
xref:cassandra/cassandra-connector-studio.adoc[Anypoint Studio] to configure the Cassandra connector.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
