= Cassandra Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

Cassandra Connector v3.1

The Anypoint CassandraDB connector creates connectivity between Cassandra databases and third-party applications, systems, services such as SAP, PeopleSoft, or Workday, as well as other databases across the enterprise. Apache Cassandra is an open source distributed NoSQL database intended to manage large amounts of product, customer, and employee data. 
The Cassandra connector implements the DataStax Java Driver for Apache Cassandra 3.1.

The following operations accept some POJOs as input parameters that are needed for the DataSense functionality:
These are: `addNewColumn`, `changeColumnType`, `createKeyspace`, `createTable`, `deleteColumnsValue`, `deleteRows`, `dropColumn`, `dropKeyspace`, `dropTable`, `executeCQLQuery`, `getTableNamesFromKeyspace`, `renameColumn`, `select`, and `update`.


== Audience

 * New user -- Read this document and configure your Mule application in xref:cassandra/cassandra-design-center.adoc[Design Center].   
* Current Mule user -- Read this document and configure your Mule application in xref:cassandra/cassandra-design-center.adoc[Design Center] or xref:cassandra/cassandra-studio.adoc[Anypoint Studio]. 
The xref:cassandra/cassandra-config-topics.adoc[Configuration Topics] help you extend your understanding of Cassandra actions.
* Power user - Read the xref:cassandra-connector-xml-maven.adoc[XML and Maven Support], xref:cassandra/cassandra-config-topics.adoc[Configuration Topics], and xref:cassandra/cassandra-use-cases.adoc[Use Cases].

== Prerequisites

Familiarity with Cassandra, Mule, Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and Mule global elements.


Requirements for using the connector:

 * Login credentials.


== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
