= Cassandra Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

Cassandra Connector v3.1

The Anypoint CassandraDB connector creates connectivity between Cassandra databases and third-party applications, systems, services such as SAP, PeopleSoft, or Workday, as well as other databases across the enterprise. Apache Cassandra is an open source distributed NoSQL database intended to manage large amounts of product, customer, and employee data. The Cassandra connector implements the DataStax Java Driver for Apache Cassandra 3.1.

== Prerequisites

Requirements for using the connector:

 * Cassandra Login credentials.

== Audience

 * Starting user - Use this Get Started to learn to create a Mule application in xref:cassandra/cassandra-design-center.adoc[Design Center] or xref:cassandra/cassandra-studio.adoc[Anypoint Studio].
* The xref:cassandra/cassandra-config-topics.adoc[Configuration Topics] help you extend your understanding of Cassandra actions.
* Power user - Read the xref:cassandra-connector-xml-maven.adoc[XML and Maven Support], xref:cassandra/cassandra-config-topics.adoc[Configuration Topics], and xref:cassandra/cassandra-use-cases.adoc[Example] documents.

== Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates and examples to simplify your use of the Salesforce connector. Templates provide a starting point that enables you to add additional functionality. Examples provide a complete solution.

// <List up to 10 Exchange templates and examples for this connector -- Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation)>

== Next

Now that you've started, try xref:cassandra/cassandra-design-center.adoc[Design Center] or
xref:cassandra/cassandra-studio.adoc[Anypoint Studio].

== See Also

* Connector in Exchange link
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
