= Configuring Embeddings Operations

== Configure the Embedding New Store Operation

The *Embedding new store* operation creates a new in-memory embedding and exports it to a physical file. The in-memory embedding in MuleSoft AI Chain persists its data through file exports upon any changes.

To configure the *Embedding new store* operation:

. On the *General* properties tab, configure the full file path for the embedding store to save in *Store Name*. 
+
If the file already exists, it is overwritten. Ensure the file path is accessible. 
+
You can also use a DataWeave expression for this field, for example:
+
`#[mule.home ++ "/apps/" ++ app.name ++ payload.storeName]`

This is the XML configuration for this operation:

[[source,xml]]
----
<ms-aichain:embedding-new-store 
  doc:name="Embedding new store" 
  doc:id="e3b52f5f-b765-4fad-9ecc-34755f386db4" 
  storeName='#[mule.home ++ "/apps/" ++ app.name ++ payload.storeName]'
/>
----

=== Output Configuration

This operation responds with a JSON payload that contains the status of the store. 

This is an example response of the main payload:

[source,json]
----
{
    "status": "created"
}
----

The operation also returns attributes that aren't within the main JSON payload, which include information about token usage, for example:

[source,json]
----
{
  "storeName": "knowledge-store"
}
----

=== Example Use Cases

* Create a new in-memory vector store for storing document embeddings.
* Export an in-memory embedding to a physical file for persistence across sessions.

== Configure the Embedding Add Document to Store Operation

The *Embedding add document to store* operation adds a document into an embedding store and exports it to a file. The document is ingested into the embedding using in-memory embedding. The in-memory embedding in MuleSoft AI Chain persists its data through file exports upon any changes.

To configure the *Embedding add document to store* operation:

. In the *General* properties for the operation, configure the following fields:
* *Store Name* 
+
Contains the full file path for the embedding store to be saved. If the file already exists, it will be overwritten. Ensure the file path is accessible.
* *Context Path*
+
Contains the full file path for the document to be ingested into the embedding store.
* *Max Segment Size* 
+
Specifies the maximum size, in tokens or characters, of each segment that the document will be split into before being ingested into the embedding store.
* *Max Overlap Size* 
+
Defines the number of tokens or characters that will overlap between consecutive segments when splitting the document.
. In the *Context* section for the operation, select the *File Type*:
* *any* 
+
Automatically detects the file format and processes it accordingly. This option allows flexibility when the file type is unknown or varied.
* *text* 
+
Text files, such as JSON, XML, TXT, and CSV
* *url* 
+
A single URL pointing to web content to ingest.

This is the XML configuration for this operation:

[[source,xml]]
----
<ms-aichain:embedding-add-document-to-store
  doc:name="Embedding add document to store"
  doc:id="e8b73dbe-c897-4f77-85d0-aaf59476c408"
  storeName='#["/Users/john.wick/Desktop/mac-demo/stores/" ++ payload.storeName]'
  contextPath="#[payload.filePath]" 
  maxSegmentSizeInChars="#[payload.maxChunkSize]" 
  maxOverlapSizeInChars="#[payload.maxOverlapSize]" 
  fileType="#[payload.fileType]"
/>

=== Output Configuration

This operation responds with a json payload containing the status of the store. 

This is an example response of the main payload:

[source,json]
----
{
    "status": "updated"
}
----

In addition to the main payload, file-related metadata attributes, such as the file path, store name, and file type, are returned separately, for example:

[source,json]
----
{
  "filePath": "/Users/john.wick/Downloads/mulechain.txt",
  "storeName": "/Users/john.wick/Downloads/knowledge-store",
  "fileType": "text"
}
----

=== Example Use Cases