= MuleSoft AI Chain Connector 1.0 - Mule 4

Anypoint Connector for MuleSoft AI Chain (MuleSoft AI Chain Connector) helps developers design, build and manage AI agents within Anypoint Platform. It provides the tools and support to integrate Large Language Models (LLMs), vector stores, and other advanced AI services into MuleSoft applications.
 
For information about compatibility and fixed issues, see the MuleSoft AI Chain Connector Release Notes.
 
== Before You Begin

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Code Builder or Anypoint Studio

Before creating an app, you must have:

* Java Development Kit (JDK) 8, 11, and 17
* Apache Maven
* Credentials to access the MuleSoft AI Chain Connector target resource
* Anypoint Platform
* The latest versions of Anypoint Code Builder or Anypoint Studio

== Common Use Cases for the Connector

These are some use cases for the MuleSoft AI Chain Connector:

* Apply prompt templates in a variety of scenarios, such as:
** Customer Service Agents
+
Enhance customer service by providing case summaries, case classifications, summarizing large datasets, and more.
** Sales Operation Agents
+
Assist sales teams in writing sales emails, summarizing cases for specific accounts, assessing the probability of closing deals, and more.
** Marketing Agents
+
Support marketing teams in generating product descriptions, creating newsletters, planning social media campaigns, and more.

== Connection Types

////
If there is one authentication type, use the following format:
{connector-name} Connector connections use the <authentication-type> authentication type, which ... <add a brief description of the authentication type like the descriptions below>.
If there is more than one authentication type, use a list like the one shown below (use only the applicable connection types--delete the others):
{connector-name} connections use the following authentication types:
* Basic authentication +
Uses a username and password for authentication
* OAuth +
Uses access tokens provided by the authorization server to get access to protected data
* OAuth2 +
Delegates user authentication to the service hosting the user account
Kerberos +
Uses the Kerberos principal as the username. The keytab path you specify obtains a ticket-granting ticket (TGT) from the authorization server.
////

For information about configuring authentication types, see xref:{lc-connector-name}-connector-studio.adoc#configure-global-element[Configure a Global Element for the Connector].


== Next Step

include::connectors::partial$t-index-partial.adoc[tags=next-step]

== See Also

// You can add additional see also links before this include, if applicable.

include::connectors::partial$t-index-partial.adoc[tags=see-also]