= MuleSoft AI Chain Connector 1.0 - Mule 4

Anypoint Connector for MuleSoft AI Chain (MuleSoft AI Chain Connector) provides ...
 
For information about compatibility and fixed issues, see the MuleSoft AI Chain Connector Release Notes.
 
== Before You Begin

To use this connector, you must be familiar with:

* The MuleSoft Chain AI Connector’s API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Code Builder or Anypoint Studio

Before creating an app, you must have:

* Credentials to access the MuleSoft AI Chain Connector target resource
* Anypoint Platform
* The latest versions of Anypoint Code Builder or Anypoint Studio

== Common Use Cases for the Connector

// Make the title singular if there is just one use case

// Add a lead in sentence and then list common use cases for the connector
These are some common use cases for {connector-name} Connector...

For examples of these use cases, see xref:{lc-connector-name}-connector-examples.adoc[{connector-name} Connector Examples].

== Connection Types

////
If there is one authentication type, use the following format:
{connector-name} Connector connections use the <authentication-type> authentication type, which ... <add a brief description of the authentication type like the descriptions below>.
If there is more than one authentication type, use a list like the one shown below (use only the applicable connection types--delete the others):
{connector-name} connections use the following authentication types:
* Basic authentication +
Uses a username and password for authentication
* OAuth +
Uses access tokens provided by the authorization server to get access to protected data
* OAuth2 +
Delegates user authentication to the service hosting the user account
Kerberos +
Uses the Kerberos principal as the username. The keytab path you specify obtains a ticket-granting ticket (TGT) from the authorization server.
////

For information about configuring authentication types, see xref:{lc-connector-name}-connector-studio.adoc#configure-global-element[Configure a Global Element for the Connector].


== Next Step

include::connectors::partial$t-index-partial.adoc[tags=next-step]

== See Also

// You can add additional see also links before this include, if applicable.

include::connectors::partial$t-index-partial.adoc[tags=see-also]