= MuleSoft AI Chain Connector 1.0 XML and Maven Support - Mule 4

include::connectors::partial$t-xml-maven-partial.adoc[tags=topic-intro]

== Add a Namespace for the Connector

Paste the following code inside the `mule` tag of the header of your configuration XML:

[source,xml,linenums, subs=attributes+]
----
http://www.mulesoft.org/schema/mule/ms-aichain
http://www.mulesoft.org/schema/mule/ms-aichain/current/mule-mule-ms-aichain.xsd
----

This example shows how the namespace statements are placed in the `<mule>` XML block:

[source,xml,linenums, subs=attributes+]
----
<mule xmlns:ms-aichain="http://www.mulesoft.org/schema/mule/ms-aichain" 
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:file="http://www.mulesoft.org/schema/mule/file" 
	xmlns="http://www.mulesoft.org/schema/mule/core" 
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core 
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/file 
	http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
	http://www.mulesoft.org/schema/mule/http 
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/core 
	http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
	http://www.mulesoft.org/schema/mule/ms-aichain 
	http://www.mulesoft.org/schema/mule/ms-aichain/current/mule-mule-mule-ms-aichain.xsd">
----

== Add a POM File Dependency

The Apache Maven `pom.xml` file generated by Anypoint Code Builder and Studio contains dependencies for a Mule app. If you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to this connector:

[source,xml,linenums,subs=attributes+]
----
<dependency>
	<groupId>com.mule.mulechain</groupId>
	<artifactId>mulechain-ai-connector</artifactId>
	<version>x.x.x</version>
	<classifier>mule-plugin</classifier>
</dependency>
----

Replace `x.x.x` with the version that corresponds to the connector you are using.

To get the most up-to-date `pom.xml` file information:

. Go to https://www.mulesoft.com/exchange/[Anypoint Exchange].
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for `MuleSoft AI Chain Connector`.
. Select the connector.
. Click *Dependency Snippets* near the upper right of the screen.


== See Also

include::connectors::partial$t-xml-maven-partial.adoc[tags=see-also]
* xref:mulesoft-ai-chain-additional-config.adoc[]
