= Configuring Agent Operations for Agentforce Connector

== Configure the Agent Define Prompt Template Operation

Use the *Agent define prompt template* operation to use specific prompt templates with your LLMs. This allows you to create natural language prompts that generate responses, extract information, invoke other prompts, or perform any text-based task.

include::connectors::partial$t-configure-operations.adoc[]
* *Template*
+
Enter the prompt template for the operation.
* *Instructions*
+
Provide the instructions for the LLM, outlining the goals of the task.
* *Dataset*
+
Specify the dataset for the LLM to evaluate using the provided template and instructions.
include::connectors::partial$einstein-ai-chat-config-properties-partial.adoc[]

This is the XML for this operation:

[source,xml,linenums, subs=attributes+]
----
<ms-agentforce:agent-define-prompt-template 
  doc:name="Agent define prompt template" 
  doc:id="f1c29c39-eac9-468c-9c46-4109a66303ec" 
  config-ref="Agentforce" 
  template="#[payload.template]" 
  instructions="#[payload.instructions]" 
  dataset="#[payload.dataset]"
/>
----


=== Output Configuration

This operation responds with a JSON payload containing the main LLM response. Additionally, attributes such as token usage are included as part of the metadata (attributes) but not within the main payload.

This is an example response:

[source,json]
----
{
  "response": "{\n  \"type\": \"positive\",\n  \"response\": \"Thank you for your positive feedback on the training last week. We are glad to hear that you had a great experience. Have a nice day!\"\n}"
}
----

The operation also returns attributes that aren't within the main JSON payload, which include information about token usage, for example:

[source,json]
----
{
  "tokenUsage": {
      "outputCount": 9, 
      "totalCount": 18, 
      "inputCount": 9 
  },
  "additionalAttributes": {}
}
----

* `tokenUsage` 
+
Token usage metadata returned as attributes
* `outputCount` 
+
Number of tokens used to generate the output
* `totalCount` 
+
Total number of tokens used for input and output
* `inputCount` 
+
Number of tokens used to process the input

== Configure the Start Agent Conversation Operation

The *Start agent conversation* operation opens the connection between the app and the agent.

include::connectors::partial$t-configure-operations.adoc[]
* *Agent list*
+
Select the agent to invoke. The lists shows only agents that are currently active in the org. 

=== Output

The operation returns a session ID for the interaction between the app and the agent. The session ID is used as an input for the *Continue agent conversation* operation.

== Configure the Continue Agent Conversation Operation


include::connectors::partial$t-configure-operations.adoc[]
* *Message*
+
Enter plain text instructions to help the agent make decisions for different use cases.
* Session ID*
+
Enter the session ID that was returned with the *Start agent conversation* operation. This is required to send the prompt defined in the *Message* field to the agent.

== Configure the End Agent Conversation Operation

include::connectors::partial$t-configure-operations.adoc[]
* *Session ID*
+



== See Also

* xref:connectors::introduction/intro-config-use-acb.adoc[]
* xref:connectors::introduction/intro-config-use-studio.adoc[Using Studio to Configure a Connector]
* xref:agentforce-connector-reference.adoc[Agentforce Connector Reference]
* xref:agentforce-additional-config.adoc[Agentforce - Additional Configuration Information]
* https://help.mulesoft.com[MuleSoft Help Center]

