= Agentforce Connector 1.0 - Mule 4
:lc-connector-name: agentforce

Anypoint Connector for Agentforce (Agentforce Connector) provides connectivity to the AI agents running in Salesforce’s Agentforce platform.

Agentforce Connector offers a group of capabilities that simplifies agent integration in MuleSoft applications.

Use this connector to:
* Authenticate with a Salesforce org and discover active agents
* Start a new session with an AI agent application
* Surface a prompt from an external application to an agent running in Salesforce
* Bring the power of AI agents to your external applications 
* Orchestrate new, innovative experiences for your customers, partners and employees 

For information about compatibility and fixed issues, see the Agentforce Connector release notes.

== Before You Begin

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Code Builder or Anypoint Studio

Before creating an app, you must have:

* Java 8 or 17
* Apache Maven
* Connected App credentials to connect with your Salesforce org
* Anypoint Platform
* The latest versions of Anypoint Code Builder or Anypoint Studio

== Common Use Cases for the Connector

These are some common use cases for the connector:

* Customer Service 
+
Increase human agents' productivity by having AI agents to complete time consuming tasks such as reviewing case history, analyzing reported issues and looking up other related information.
* Sales 
+
Improve sales team efficacy by accelerating prospect research, generating customized collateral, and preparing contracts.
* Marketing 
+
Support marketing teams by drafting social media copy, executing market research, and completing campaign analysis.


== Next Step

include::connectors::partial$t-index-partial.adoc[tags=next-step]

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-config-use-acb.adoc[]
* xref:connectors::introduction/intro-config-use-studio.adoc[Using Studio to Configure a Connector]
* xref:agentforce-connector-reference.adoc[Agentforce Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]