= About HTTP Connector Migration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: http, https, request, requester

Key changes in the HTTP connector for Mule Runtime 4.0 and later that can affect migration are:

* The `http:listener-config` and `http:request-config` have a new, inner connection element.
* The HTTP body option replaces the source parameter in the request and is incorporated to the Listener's response and error response.
* The HTTP Listener and Request components return attributes, which include all previous properties.
* HTTP parsing has been removed. DataWeave now handles special mime types. It can be used to both read and write such payloads.
* The `static-resource-handler` is renamed `load-static-resource`.
+
* To access source HTTP Listener and HTTP Request attributes, the following DataWeave syntax replaces the Mule Expression Language (MEL) expressions for accessing past properties.
+
`#[attributes.<parameter>]`

The "HTTP Connector XML Reference" maps Mule 3.x MEL expressions to Mule 4.0 DataWeave expressions.

The following constructs are removed in Mule Runtime 4.0:

* Request and response builders, `http:request-builder` and `http:response-builder`
* Worker threading profile

The request, response, and error-response replace the builders. Using DataWeave expressions eliminates the need for building parameters.

== See Also

* xref:http/http-connector-xml-reference.adoc[HTTP Connector XML Reference]
* xref:http/http-documentation.adoc[HTTP Connector Technical Reference]