= To Route Requests Based on HTTP Method
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

. Create a flow with an HTTP Listener, set its Path to *requests* and the Allowed Methods field to GET.
. Create a Global Element for the Listener, set Host to `localhost`, leave the Port as the default *8081* and set the Base Path to *mypath*.
. Add another building block, such as a Logger transformer, after the HTTP Listener. Set Message to *flow 1*.
. Create a second flow with an HTTP Listener. In Extension configuration, select the existing HTTP_Listener_Config global element you created for the first connector.
. Set its Path to *requests*. Set the Allowed Methods field to POST.
. Add a Logger transformer after the HTTP Listener. Set Message to *flow 2*.
. Using a browser extension such as Postman, send HTTP GET and POST requests to `+http://localhost:8081/mypath/requests+`.
+
The GET request response is flow 1. The POST request response is flow2.
+
. Send a DELETE request.
+
"405 Method Not Allowed" is returned.