= To Consume a REST Service (Studio)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can design an app to consume a REST service by setting up HTTP Listener and Request operations. In this procedure, you first consume a REST API service using primarily default HTTP configurations. Next, you test the HTTP request. You edit the configuration to make a secure HTTPS request. Finally, you test the HTTPS request.

. From the Mule Palette, drag an HTTP Listener operation to a new flow.
. Set up the Listener configuration: Click + and set the default host, port and base path. For example, host = 0.0.0.0, port = 8081, and no base path.
. In General, set Path to */trigger*.
. Accept the other default Listener settings, and save the configuration.
. From Mule Palette, drag an HTTP Request operation to the flow.
. Set up the Request configuration:
+
* Set URL Or Path to `+http://jsonplaceholder.typicode.com/users+`.
* Accept the other default settings and save.
+
. Deploy the app. Open a browser, and go to `+localhost:8081/trigger+`.
+
The Listener hears the request on port 8081, and starts the app. The list of users appears in the browser.
. Change the Request configuration to use HTTPS protocol.
* Set URL Or Path to `+https://jsonplaceholder.typicode.com/users+`.
* Set the port to *443*.
* Accept the other default settings and save.
. Deploy the app, run the app, open a browser, and go to `+localhost:8081/trigger+`.
+
The Listener hears the request on port 8081, and starts the app. The list of users appears in the browser.



== See Also

* About the HTTP Request Operation
* About HTTP Connector Migration
* HTTP Connector Reference
* HTTP Connector Documentation Reference