= About the HTTP Connector (Design Center)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, http, https

Using the HTTP or HTTPS protocol, the HTTP connector performs one of the following operations:

* Listener
+
Starts executing the Mule flow upon receiving an HTTP request.
+
* Request
+
Consumes an HTTP service.

Mule preconfigures the first HTTP connector in an empty flow as a Listener and trigger. When the app runs and the Listener hears a request, the flow executes.

By default, the Listener configuration connects to CloudHub using HTTP and the Request configuration connects to port 80 using HTTP and GET.  You can quickly configure an app to consume an HTTP service using the two HTTP connector instances as follows:

* Listener configuration: Path = */somepath*, for example
* Request configuration: Path Or URL = the URL of the HTTP service you want to consume

== See Also

* xref:http/http-consume-web-service.adoc[To Consume a REST Service]
* xref:http/http-about-http-connector-migration.adoc[About HTTP Connector Migration]
* xref:http/http-documentation.adoc[HTTP Connector Technical Reference]