= Start an App from a Browser
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In this procedure, you configure an HTTP Listener to specify a host name, a port, and a path. To listen on a specific port for every network interface on the server, you set host to `0.0.0.0`. Using `localhost` listens for incoming requests generated inside the server. From a browser, you submit a URL, and the result appears in the Anypoint Studio Console.

. Create a new project.
. From Mule Palette, drag an HTTP Listener to a new flow.
. Configure the Listener:
* Click + and set the default host, port and base path. For example, host = 0.0.0.0, port = 8081, and no base path.
* In the properties editor, set *Path* to the URL to start the app from the browser. For example, set Path to */trigger*.
* Accept the other default Listener settings, and save the configuration.
+
. From the Mule Palette, drag Core > Logger to the flow.
. In Logger, in Message, type *"Hello"*.
+
. Click the project name in Package Explorer and click *Run* > *Run As* > *Mule Application*. Ensure that the console messages state that the application started correctly by looking for the message `Mule is up and kicking`.
. Open a browser and type `+http://0.0.0.0:8081/trigger+`.
+
The HTTP Listener hears the request on port 8081, and the app starts.
+
. In Console, scroll through the logs and you see Hello.
