= Upgrading and Migrating Amazon S3 Connector to Version 6.x
:page-aliases: connectors::amazon/amazon-s3-connector-upgrade-migrate.adoc

Upgrade Anypoint Connector for Amazon S3 (Amazon S3 Connector) to version 6.x.

== Supported Upgrade Paths

[%header,"cols=50a,50a"]
|===
|From Version | To Version
|5.8.0 |6.0.0
|===

== Changes in This Release

This connector is now migrated to AWS SDK for Java 2.x. This release contains the following changes:

* Connection Types
** The *Basic* and *Role* connection types are no longer available. Now, the new *Connection (S3)* connection type covers both *Basic* and *Role* connection types.

* Operations
** The *Create Object*, *Create Object Presigned URI*, *Get Object Metadata*, and *Initiate Multipart Upload* operations are removed.
** The *Get Object Attributes*, *Head Object*, *List Object Versions*, *Put Object*, *Restore Object*, and *Select Object Content* operations are added.
** Some operation names are changed. <<link>>


* Parameters
** Added the following parameters to some operations:
*** *Config Ref*
***


changed parameter names:
some operations revmoed Part ETags ->Completed Parts
- some are title case to sentence case Bucket Name to Bucket name
Key to Object key
Source Key to Source object key
destination key to destination object key
removed location constraint, changed to region
changed canned acl - acl and removed some options
revmoed force
bucket name to bucket
version id to object version id
added object identifiers
removed version id from some operations, modified since, unmodified since , start, end
added part number to some oeprations
version id to object version id
added region to some operations
added page size, removed max uploads and eocnding type  and delimiter
removed topic configurations added notification configuratio
policy text - policy
revmoed tag sets added bucket tags
bucket website configuration to website config
add object acl , target variable, target value
removed part size, md5 digest , content, file offset , is last part
Matching ETag Constraints is matching etag , added Not matching ETag, removed first byte last byte , added bytes range


sources: added folder and config ref

added folder, ,queue name , config ref



deletebuckettaggingconfiguration
deleteBucketWebsiteConfiguration
getbucketcorsconfiguration
getbucketloggingconfiguration
getBucketTaggingConfiguration
getBucketVersioningConfiguration
getBucketWebsiteConfiguration
listversions -> list object versions
set bucker acl > put bucket ACL
set bucketcors config
set bucket lifecccle config
setbucketlogging config
setbucketnotiifcationconfig
setbucket policy
setb ucket tagging config
set BucketVersioningRespon
set bucket website
set object ACL

new: getobjectattributes , head object, listobjectversions, put object, restore object, select object content,

error Types


object types:
removed
* <<AccessControlListAttributes>>
* <<BLCRule>>
* <<Bucket>>
* <<BucketLoggingConfiguration>>
* <<BucketWebsiteConfiguration>>
* <<CompleteMultipartUploadResult>>
* <<CopyPartResult>>
* <<KeyVersion>>
* <<MultipartUploadListing>>
* <<ObjectMetadataParameterGroup>>
* <<ObjectResult>>
* <<PartETag>>
* <<PartListing>>
* <<PartSummary>>
* <<RoutingRuleCondition>>
* <<S3ObjectAttributes>>
* <<S3ObjectSummary>>
* <<S3VersionSummary>>
* <<UploadPartResult>>

added:
* <<ApiChecksum>>
* <<ApiCopyObjectResult>>
* <<ApiCopyPartResult>>
* <<ApiCsvInput>>
* <<ApiCsvOutput>>
* <<ApiGetObjectAttributesParts>>
* <<ApiInitiator>>
* <<ApiInputSerialization>>
* <<ApiObjectPart>>
* <<ApiObjectVersion>>
* <<ApiOutputSerialization>>
* <<ApiS3Object>>
* <<ApiScanRange>>
* <<BucketAclResponse>>
* <<BucketCorsResponse>>
* <<BucketNotificationResponse>>
* <<BucketPolicyResponse>>
* <<BucketResponse>>
* <<BucketTaggingResponse>>
* <<BucketVersioningResponse>>
* <<BucketWebsiteResponse>>
* <<CompleteMultipartUploadResponse>>
* <<Condition>>
* <<CopyObjectResponse>>
* <<CreateMultipartUploadResponse>>
* <<FilterRule>>
* <<GetObjectAclResponse>>
* <<GetObjectAttributesResponse>>
* <<HeadObjectResponse>>
* <<LambdaFunctionConfiguration>>
* <<LifecycleConfiguration>>
* <<LifecycleRule>>
* <<LifecycleRuleFilter>>
* <<ListBucketsResponse>>
* <<LoggingStatus>>
* <<MultipartPart>>
* <<NotificationConfigurationFilter>>
* <<ProxyConfiguration>>
* <<PutObjectResponse>>
* <<QueueConfiguration>>
* <<RestoreObjectResponse>>
* <<Role>>
* <<S3KeyFilter>>
* <<S3ObjectTriggerResponse>>
* <<StandardRevocationCheck>>
* <<Tag>>
* <<TopicConfiguration>>
* <<UploadPartCopyResponse>>
* <<UploadPartResponse>>
* <<WebsiteConfiguration>>

=== Requirements

Ensure your system meets the following compatibility requirements before you perform the upgrade:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule |4.1.1 and later
|AWS SDK for Java	|1.11.969
|===

== Upgrade Prerequisites

Before you perform the upgrade, create a backup of your files, data, and configuration in case you need to restore to the previous version.

== Upgrade Steps

Follow these steps to perform the upgrade to version 5.7.0:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `amazon s3` in the search field.
. In *Available modules*, select *Amazon S3* and click *Add*.
. Click *Finish*.
. Verify that the Amazon S3 dependency version is 5.5 in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

== Post-Upgrade Steps

After you install the latest version of the connector, verify that your error handling is updated to work with the minor changes in error codes in this version of the connector.

=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

=== Revert the Upgrade

If it is necessary to revert to the previous version of Amazon S3, change the `mule-amazon-s3` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.
