= Upgrading and Migrating File Connector to Version 2.0.x - Mule 4
:page-aliases: connectors::file/file-upgrade-migrate.adoc

Upgrade Anypoint Connector for File (File Connector) to version 2.0.x.

== Supported Upgrade Paths

[%header,"cols=50a,50a"]
|===
|From Version | To Version
|1.5 |2.0.x
|===

== Changes in This Release

This release contains a new parameter *Recursive Testing* in List operation.

* Parameters
** List operation now contain the following parameter:
*** *Recursive Testing*

== Requirements

Ensure your system meets the following compatibility requirements before you perform the upgrade:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule |4.1.5 and later
<Need info here..>
|===

== Upgrade Prerequisites

Before you perform the upgrade, create a backup of your files, data, and configuration in case you need to restore to the previous version.

== Upgrade Steps

Follow these steps to perform the upgrade to version 2.0:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `file` in the search field.
. In *Available modules*, select *File Connector* and click *Add*.
. Click *Finish*.
. Verify that the File Connector dependency version is 2.0 in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

== Post-Upgrade Steps

After you install the latest version of the connector, verify that your error handling is updated to work with the minor changes in error codes in this version of the connector.

== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Revert the Upgrade

If it is necessary to revert to the previous version of File Connector, change the `mule-file` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
