= Using Anypoint Studio to Configure File Connector 2.0 - Mule 4

Anypoint Studio (Studio) editors help you design and update your Mule applications, properties, and configuration files.

To add and configure a connector in Studio:

. <<create-mule-project,Create a Mule project>>.
. <<add-connector-to-project,Add the connector to your Mule project>>.
. <<configure-input-source,Configure a source for the connector's flow>>.
. <<add-connector-operation,Add a connector operation to the flow>>.
. <<configure-global-element,Configure a global element for the connector>>.

When you run the connector, you can view the app log to check for problems in real time, as described in <<view-app-log,View the App Log>>.

If you are new to configuring connectors in Studio, see xref:connectors::introduction/intro-config-use-studio.adoc[Use Studio to Configure a Connector]. If you need additional information about the connector fields after reading this topic, see the xref:file-documentation.adoc[File Connector Reference Reference].

[[create-mule-project]]
== Create a Mule Project

In Studio, create a new Mule project in which to add and configure the connector:

. In Studio, select *File > New > Mule Project*.
. Enter a name for your Mule project and click *Finish*.


[[add-connector-to-project]]
== Add the Connector to Your Mule Project

Add File Connector to your Mule project to automatically populate the XML code with the connector's namespace and schema location and to add the required dependencies to the project's `pom.xml` file:

. In the *Mule Palette* view, click *(X) Search in Exchange*.
. In the *Add Dependencies to Project* window, type `file` in the search field.
. Click *File Connector* in *Available modules*.
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio does not make that connector available to other projects in your Studio workspace.


[[configure-input-source]]
== Configure a Source

A source initiates a flow when a specified condition is met.
You can configure one of these sources to use with File Connector:

* *On New or Updated File* +
Initiates a flow by polling a directory for files that have been created or updated and generates a message for each file found.
* *HTTP Listener* +
Initiates a flow each time it receives a request on the configured host and port.
* *Scheduler* +
Initiates a flow when a time-based condition is met.

For example, to configure the *On New or Updated File* source, follow these steps:

. In the *Mule Palette* view, select *On New or Updated File*.
. Drag *On New or Updated File* to the Studio canvas.
. On the *On New or Updated File* configuration screen, optionally change the value of the *Display Name* field.
. Specify a value for the *Path* field.
. Click the plus sign (*+*) next to the *Connector configuration* field to configure a global element that can be used by all instances of *On New or Updated File* in the app.
. On the *General* tab, specify the connection information for the connector.
. Set *Host* to specify the FTP server host, for example, `localhost` or `192.168.0.1`.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.
. On the *On New or Updated File* configuration screen, specify a *Scheduling Strategy* value and optionally complete other fields.

[[add-connector-operation]]
== Add a Connector Operation to the Flow

When you add a connector operation to your flow, you immediately define a specific operation for that connector to perform.

To add an operation for File Connector, follow these steps:

. In the *Mule Palette* view, select *File* and then select the desired operation.
. Drag the operation onto the Studio canvas, next to the source.


[[configure-global-element]]
== Configure a Global Element for the Connector

When you configure a connector, it’s best to configure a global element that all instances of that connector in the app can use. Configuring a global element requires you to configure the FTP server connection.

To configure the global element for File Connector, follow these steps:

. Select the name of the connector in the Studio canvas.
. Select the operation in the Studio canvas.
. In the configuration screen for the operation, click the plus sign (*+*) next to the *Connector configuration* field to access the global element configuration fields.
. On the *General* tab, specify the connection information for the connector:
. Set the *Working Directory* as the root of every relative path used with this connector. +
If it's not provided, the value defaults to the value of the `user.home` system property. If the system property is not set, the connector  fails to initialize. 
. Set *Host* to specify the FTP server host, for example, `localhost` or `192.168.0.1`.
. On the *Advanced* tab, optionally specify a timeout configuration and reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.


In the *Configuration XML* editor, the configuration `file:config` looks like this:
[source,xml,linenums]
----
<file:config name="File_Config" doc:name="File Config" >
		<file:connection workingDir='/Users/me/myfiles"'/>
----

[[view-app-log]]
== View the App Log

To check for problems, you can view the app log as follows:

* If you’re running the app from Anypoint Platform, the output is visible in the Anypoint Studio console window.
* If you’re running the app using Mule from the command line, the app log is visible in your OS console.

Unless the log file path is customized in the app’s log file (`log4j2.xml`), you can also view the app log in the default location `MULE_HOME/logs/<app-name>.log`.


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-config-use-studio.adoc[Use Studio to Configure a Connector]
* xref:file-documentation.adoc[File Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
