= Shopify Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Shopify (Shopify Connector) gives you access to the Shopify platform. This connector exposes operations provided by the Shopify REST Admin API.

For information about compatibility and fixed issues, see the Shopify Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Shopify Connector’s API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the Shopify target resource
* Anypoint Platform
* Anypoint Studio version 7.3.5 or later

== Common Use Cases For the Connector

Some common use cases for Shopify Connector include:

* Syncing a new customer's information when they place an order.
* Storing information when a new order is placed through a client's Shopify store.
* Managing items when a new product is created in Shopify. 

== Connection Types

Shopify Connector uses the following authentication methods:

* Basic Auth +
Uses a username and password for authentication.

* OAuth2 +
Delegates user authentication to the service hosting the user account.

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:shopify-connector-reference.adoc[Shopify Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
