= Shopify Connector - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]
// If this is a Premium connector, change Select to Premium

Anypoint Connector for Shopify provides ...

For information about compatibility and fixed issues, see the Shopify Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Shopify Connector’s API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Shopify target resource
* Anypoint Platform
* Anypoint Studio version <x.x> or later
*// If your connector has other prerequisites specific to this connector, list them here.

== Common Use Cases For the Connector
// Make the title singular if there is just one use case
// Add a lead in sentence and then list common use cases for the connector

These are some common use cases for Shopify Connector...

For examples, see xref:shopify-connector-examples.adoc[Shopify Connector Examples] use cases.

== Connection Types
// If there is one authentication type, use the following format:

Shopify connections use the <authentication-type> authentication type, which ... <add a brief description of the authentication type like the descriptions below>.

////
If there is more than one authentication type, use a list like the one shown below (use only the applicable connection types--delete the others):
Shopify connections use the following authentication types:
* Basic authentication +
Uses a username and password for authentication
* OAuth +
Uses access tokens provided by the authorization server to get access to protected data
* OAuth2 +
Delegates user authentication to the service hosting the user account
Kerberos +
Uses the Kerberos principal as the username. The keytab path you specify obtains a ticket-granting ticket (TGT) from the authorization server.
////

For information about configuring authentication types, see xref:shopify-studio.adoc[Use Studio to Configure Shopify Connector].

////
Include the following section only if Exchange provides templates, examples, or both for the connector. If there are templates and not examples, or vice versa, reword the section as applicable.
////

== Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as a starting point for your app, as well as examples that illustrate a complete solution.

////
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:shopify-connector-studio.adoc[Anypoint Studio].

== See Also
// Add useful links. Add link to upgrade topic if applicable
* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:shopify-connector-reference.adoc[Shopify Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
