= Amazon SQS Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select
Amazon SQS Connector Version v4.2.0

The Anypoint Connector for Amazon SQS provides an easy way to interface with the Amazon Simple Queue Service (Amazon SQS) API, allowing Mule users to manage SQS queueing services without having to deal with the API directly.

Amazon SQS offers a reliable, highly scalable hosted queue for storing messages as they travel between computers. By using Amazon SQS, developers can move data between distributed application components and perform different tasks without losing messages or requiring each component to be always available. Amazon SQS makes it easy to build an automated workflow that works closely with the Amazon Elastic Compute Cloud (Amazon EC2) and other AWS infrastructure web services.

The AWS SDK for Java provides a Java API for AWS infrastructure services. The Amazon SQS connector is built using the SDK for Java.

== Queue Support

The Amazon SQS connector provides support for two types of queues:

* Standard Queues
+
Standard queues have high throughput. However, using these queues can occasionally result in having duplicate copies of messages delivered out of order.
+
* FIFO Queues
+
FIFO (First-In-First-Out) queues deliver messages in the same order in which they are sent. However, these queues have limited throughput.

For information about creating FIFO queues, see xref:amazon/amazon-sqs-connector-config-topics.adoc[Additional Configuration Topics].

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect
to APIs and resources on external systems, such as Salesforce, Amazon SQS, ServiceNow,
and Twitter.

== Prerequisites

Before creating an app, you must:

* Have access to the Amazon SNS target resource and Anypoint Platform.
* Understand how to create a Mule app using Design Center or Anypoint Studio.
* Have AWS Identity and Access Management (IAM) credentials.


== Compatibility

Amazon SQS connector 5.0 is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |4.1.x
|AWS SDK for Java |1.11.515
|===

== Audience
* Starting user -- To create your Mule app,
see xref:amazon/amazon-sqs-connector-design-center.adoc[Design Center Configuration]
or xref:amazon/amazon-sqs-connector-studio.adoc[Studio Configuration]. The
xref:amazon/amazon-sqs-connector-config-topics.adoc[Additional Configuration Information]
topic helps extend your understanding of the Amazon SQS connector. The
xref:amazon/amazon-sqs-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Power user - Read the xref:amazon/amazon-sqs-connector-xml-maven.adoc[XML and Maven Support],
xref:amazon/amazon-sqs-connector-config-topics.adoc[Additional Configuration Information],
and xref:amazon/amazon-sqs-connector-examples.adoc[Examples] topics.

== Common Use Cases For the Connector

Common use cases for the connector include sending messages to a queue and retrieving messages from a queue. For an example of these use cases, see <<amazon/amazon-sqs-connector-examples.adoc#install-connector,Amazon SQS Examples>>.

== Next Step

After you have met the prerequisites and experimented with templates and examples, you are ready to create an app with
xref:amazon/amazon-sqs-connector-design-center.adoc[Design Center] or xref:amazon/amazon-sqs-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/?search=amazon-sqs&type=connector[Anypoint Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]
