= Amazon DynamoDB Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Amazon DynamoDB Connector v1.4

Anypoint Connector for Amazon DynamoDB (Amazon DynamoDB Connector) provides connectivity to the Amazon DynamoDB API, which enables you to interact with Amazon DynamoDB to create a database table that can store and retrieve any amount of data, serve any level of request traffic, and automatically spread the data and traffic for the table over a sufficient number of servers to handle the request capacity and the amount of data stored, while maintaining consistent and fast performance.


Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability.

Release Notes: xref:release-notes::connector/amazon-dynamodb-connector-release-notes-mule-4.adoc[Amazon DynamoDB Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-amazon-dynamodb-connector/[Amazon DynamoDB Connector]

== Prerequisites

To use this information, you must be familiar with Amazon DynamoDB API, Mule, Anypoint Connectors, Anypoint Studio, Mule
concepts, elements in a Mule flow, and Global Elements.

For software requirements and compatibility information, see the Connector Release Notes.

To use this connector with Maven, view the pom.xml dependency information in
the Dependency Snippets in Anypoint Exchange.

To use the Amazon DynamoDB Connector, you must have the following:

- Access to Amazon Web Services - DynamoDB
- AWS Identity and Access Management (IAM) user account credentials to access AWS with the connector
- Anypoint Studio version 7.0 or later, or Design Center

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
* https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/Welcome.html[Amazon API documentation]
