= Amazon SQS Additional Configuration Information - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/


== Creating the FIFO Queue

To create the FIFO queue, use the *Create queue* operation in the connector, and set *FifoQueue* and *ContentBasedDeduplication* to true.

End the *queue name* with the `.fifo` extension. For example,  `MyTestFIFOQueue.fifo`.

While creating the FIFO queues, choose either of the two regions: US East (Ohio) or US West (Oregon). Amazon only supports these two regions for FIFO queues.

When using Amazon SQS Connector to send messages to the FIFO queue, use the same queue URL and region name that you used when creating the FIFO Queue. You also have to provided a value for the attribute `message group id` in the connector configuration while sending messages.

== Next

After you read this topic, you can try
the Amazon SQS Connector xref:amazon/amazon-sqs-connector-examples.adoc[Amazon SQS Connector Examples].

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
