= Amazon SQS Additional Configuration Information - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

== Use the AWS Credentials Provider Chain in CloudHub

With the Default AWS Credentials Provider Chain, you can specify the access key and secret in the CloudHub environment:

. Use the following configuration to prepare a Mule app.
+
[source,xml,linenums]
----
 
 <sqs:config name="Amazon_SQS_Configuration" doc:name="Amazon SQS Configuration" doc:id="b2abe98e-3511-40aa-80f3-9a5845dd2021" >
 <sqs:basic-connection accessKey="${aws.accessKeyId}" secretKey="${aws.secretKey}" tryDefaultAWSCredentialsProviderChain="true" />
 </sqs:config>
----
+
. Export this configuration to get a deployable zip archive.
. Deploy to CloudHub and set the properties `aws.accessKeyId` and `aws.secretKey` through Runtime Manager > Settings > Properties.
. Finish deploying and testing.

[NOTE]
The access key and secret key are not listed in the connector configuration. Instead, the correct values are used from the values specified in the settings.

== Next Step

After you understand how to provide credentials, you can try out the xref:amazon/amazon-sqs-connector-examples.adoc[Example].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]