= Amazon S3 Design Center Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

== Configure a connector in Design Center

To configure a connector in Design Center, follow this process:

. Configure the trigger, which can be an operation from this connector (if available), an HTTP Listener, or a Scheduler.
. Configure the connector from the trigger or later as a component. *What does this mean?*

== Configure the Amazon S3 Connector in Design center

To configure the Amazon S3 connector in Design Center:

. From the Anypoint Platform Design Center, click *Create*, and then click *Create new application* under *Create a Mule Application*.
. *Enter* a project name and click *Create*.
. Exit the *Let’s Get Started* wizard by clicking *Go straight to canvas*.
. *Click the plus sign*.
. *
. Select a trigger as follows:
 +
 * To have an Amazon S3 event initiate access to your app (that is, to trigger your app), select the Amazon S3 Connector and then select one of the Amazon S3 trigger operations. Alternatively, you can *select* an *HTTP Listener* or *Scheduler as the trigger*.
 . 

== Amazon S3 Trigger Operations:

You can use the following Amazon S3 operations as triggers:
* `On Deleted Object` - Initiates access to your app when an Amazon S3 object is deleted.
* `On New Objects` - Initiates access to your app when an Amazon S3 object is created.


= Next

Now that you have completed ____, you can try out ______.

== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
