= Amazon S3 Design Center Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

== Configure a connector in Design Center

To configure a connector in Design Center, follow this process:

. Configure the trigger for the connector, which can be an HTTP Listener, a Scheduler, or an operation from the connector (if available).

. Configure the target component for the connector.

== Configure the trigger

Configure an input source for the Amazon S3 connector, such as aan HTTP Listener, a Scheduler, or a connector operation.

== Configure the Amazon S3 Connector in Design Center

To configure the Amazon S3 connector in Design Center:

. From the Anypoint Platform Design Center, click *Create*, and then click *Create new application* under *Create a Mule Application*.
. *Enter* a project name and click *Create*.
. Exit the *Let’s Get Started* wizard by clicking *Go straight to canvas*.
. Click the plus sign.
. . Select a trigger as follows:
 +
 * To have an Amazon S3 event initiate access to your app (that is, to trigger your app), select the Amazon S3 Connector and then select one of the Amazon S3 trigger operations. Alternatively, you can select an HTTP Listener or Scheduler as the trigger.

You can use the following Amazon S3 operations as triggers:
* `*On Deleted Object* - Initiates access to your app when an Amazon S3 object is deleted.
* *On New Objects* - Initiates access to your app when an Amazon S3 object is created.

== Configure the Target Component

In Design Center's Flow Designer, after you specify a trigger, you can add the Amazon S3 connector as a component to process the input you received from the trigger. You may also want to add a DataWeave Transform
between the trigger and the component to transform the input information to what you want as input to the Amazon S3 connector component. The Salesforce connector doesn't have to be a component, it depends on what you're trying
to accomplish with your app.

To add an Amazon S3 connector as a component:

. After creating a trigger, click the plus sign.
. If needed, click *Transform* to use DataWeave to map fields between your received data and what to use with your Salesforce component.
. Click the plus sign to the right of the *Choose an operation*.

== Configure Basic Username Password Authorization

Important fields:

* *Username* (required): Enter the Salesforce username.
* *Password* (required): Enter the corresponding password.
* *Security Token*: Enter the corresponding security token.

[NOTE]
Implementing OAuth 2.0-based authentication mechanisms involves extra steps, but may be preferred if your service is exposed to external users, as it ensures better security.

= Next

Now that you have completed ____, you can try out ______.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
