= Amazon SQS XML and Maven Support - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

If you manually code a Mule app in XML either from the Anypoint Studio XML editor or from a text editor, you can get access to the Amazon SQS Connector in your app by adding reference statements to your XML Mule flow and in the Apache Maven `pom.xml` file.

[NOTE]
====
You can avoid the manual process described in this topic by using Studio. When you install Amazon SQS Connector in Anypoint Studio, Studio automatically populates the XML code with the Amazon SQS Connector namespace and schema location, and adds a dependency to the `pom.xml` file.
====

== Add a Namespace for the Connector

Paste the following code inside the `<mule>` tag of the headerof your configuration XML:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/amazon-sqs
http://www.mulesoft.org/schema/mule/amazon-sqs/current/mule-amazon-sqs.xsd
----

This example shows how the namespace statements are placed in the XML:
[source,xml,linenums]
----
<mule xmlns:$2="http://www.mulesoft.org/schema/mule/$2"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/file
	http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
	http://www.mulesoft.org/schema/mule/http
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/core
	http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
	http://www.mulesoft.org/schema/mule/$2
	http://www.mulesoft.org/schema/mule/$2/current/mule-$2.xsd">
----

== Add a POM File Dependency

The `pom.xml` Maven file generated by Anypoint Studio contains dependencies for
a Mule app. When you code a Mule app manually, include this XML snippet in
your `pom.xml` file to enable access to the connector. The Mule runtime engine
translates the `RELEASE` dependency keyword to the current version.

[source,xml,linenums]
----
<dependency>
    <groupId>com.mulesoft.connectors</groupId>
    <artifactId>mule-amazon-sqs-connector</artifactId>
    <version>RELEASE</version>
    <classifier>mule-plugin</classifier>
</dependency>
----

To obtain the most up-to-date `pom.xml` file information, access the
connector in https://www.mulesoft.com/exchange/[Anypoint Exchange]
and click *Dependency Snippets*.

== Next Step

After completing your namespace and `pom.xml` file, you can try
the xref:amazon/amazon-sqs-connector-examples.adoc[Examples].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
