= Amazon S3 Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/
Support Category: Select
Amazon S3 Connector v<Major>.<Minor>

The Anypoint Amazon S3 connector provides connectivity to the Amazon S3 API, enabling you to interface with Amazon S3 to store objects, download and use data with other AWS services, and build applications that require internet storage.

Instant access to the Amazon S3 API enables seamless integrations between Amazon S3 and other databases, CMS applications such as Drupal, and CRM applications such as Salesforce. Use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. You can accomplish these tasks by using the simple and intuitive web interface of the AWS Management Console.

The AWS SDK for Java provides a Java API for AWS infrastructure services.
The Amazon S3 connector is built using the SDK for Java.

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect
to APIs and resources on external systems, such as Salesforce, Amazon S3, ServiceNow,
and Twitter.

== Prerequisites

Before creating an app, you must:

* Have access to the Amazon S3 target resource and Anypoint Platform.
* Understand how to create a Mule app using
Design Center or Anypoint Studio.
* Have AWS Identity and Access Management (IAM) credentials.

[Note]
For the Amazon S3 operations to work, you need to enable or update the subset of the overall list of Amazon S3 actions in the bucket to specify that the AWS account has access these actions.

To see a list of Amazon S3 operations, see the xref:amazon/amazon-s3-connector-reference.adoc[Amazon S3 Connector Reference].

== Audience

* Starting user -- Read this Get Started document and create your Mule app in
xref:amazon/amazon-s3-connector-design-center.adoc[Design Center] or
xref:amazon/amazon-s3-connector-studio.adoc[Anypoint Studio].
The xref:amazon/amazon-s3-connector-config-topics.adoc[Additional Configuration Information] topic
helps you extend your understanding of Amazon S3 connector actions.
* Power user - Read the xref:amazon/amazon-s3-connector-xml-maven.adoc[XML and Maven Support],
xref:amazon/amazon-s3-connector-config-topics.adoc[Additional Configuration Information] topic,
and xref:amazon/amazon-s3-connector-examples.adoc[Amazon S3 Examples] topics.

== See Also

* https://anypoint.mulesoft.com/exchange/com.mulesoft.connectors/mule-amazon-s3-connector[Amazon S3 connector in Anypoint Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
