= Amazon SNS Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

Amazon SNS Connector Version vxxx

The Anypoint Connector for Amazon SNS provides connectivity to the Amazon Simple Notification Service (Amazon SNS) API, enabling you to build distributed web-enabled applications. Mule apps can use the Amazon SNS Connector to easily push real-time notification messages to interested subscribers over multiple delivery protocols.

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect
to APIs and resources on external systems, such as Salesforce, Amazon SNS, ServiceNow, and Twitter.

== Prerequisites

To be able to use the Amazon SNS Connector, you must have the following:

* Access to Amazon Web Services - SNS.
* To access AWS with the connector, you need the credentials in the form of IAM.
* Anypoint Studio version 7.0 (or higher) or Anypoint Design Center.

=== Compatibility

Amazon SNS connector is compatible with:

[%header,cols="20a,80a",width=70%]
|===
|Application/Service|Version
|Mule Runtime |4.1.x
|AWS SDK for Java |1.11.515
|Java |1.8.0_x
|Anypoint Studio |7.0 or higher
|===

== Audience

* Starting user -- Read this Get Started document and create your Mule app in
xref:amazon/amazon-sns-connector-design-center.adoc[Design Center] or
xref:amazon/amazon-sns-connector-studio.adoc[Anypoint Studio].
* Power user - Read xref:amazon/amazon-sns-connector-xml-maven.adoc[XML and Maven Support]
and xref:amazon/amazon-sns-connector-examples.adoc[Examples].

== Next Steps

After you have met the prerequisites and experimented with templates
and examples, you are ready to create an app with
xref:amazon/amazon-sns-connector-design-center.adoc[Design Center] or
xref:amazon/amazon-sns-connector-studio.adoc[Anypoint Studio].

== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
