= Amazon S3 Design Center Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

== Configure a connector in Design Center

To configure a connector in Design Center, follow this process:

. Configure the trigger for the connector, which can be an HTTP Listener, a Scheduler, or an operation from the connector (if available).

. Configure the target component for the connector.

== Configure the trigger

Configure an input source for the Amazon S3 connector, such as an HTTP Listener, a Scheduler, or a connector operation.

== Configure the Amazon S3 Connector in Design Center

To configure the Amazon S3 connector in Design Center:

. From the Anypoint Platform Design Center, click *Create*, and then click *Create new application* under *Create a Mule Application*.
. Enter a project name and click *Create*.
. Exit the *Let’s Get Started* wizard by clicking *Go straight to canvas*.
. Click the plus sign.
. Select a trigger as follows:
 +
 * To have an Amazon S3 event initiate access to your app (that is, to trigger your app), select the Amazon S3 Connector and then select one of the Amazon S3 trigger operations. Alternatively, you can select an HTTP Listener or Scheduler as the trigger.

You can use the following Amazon S3 operations as triggers:
* *On Deleted Object* - Initiates access to your app when an Amazon S3 object is deleted.
* *On New Object* - Initiates access to your app when an Amazon S3 object is created.

== Configure the Target Component

In Design Center's Flow Designer, after you specify a trigger, you can add the Amazon S3 connector as a component to process the input you received from the trigger. You may also want to add a DataWeave Transform
between the trigger and the component to transform the input information to what you want as input to the Amazon S3 connector component.

To add an Amazon S3 connector as a component:

. After creating a trigger, click the plus sign.
. If needed, click *Transform* to use DataWeave to map fields between your received data and what to use with your Amazon S3 component.
. Select *Amazon S3 Connector*, and then select an operation.
. Click *Click here to set it up*.
. Select a connection type and enter the required information:
+
* For the *Basic* connection type:
+
[%header%autowidth.spread]
|===
|Parameter |Description
|Configuration Name |Name for the configuration to use to reference the connector instance.
|Access Key |Alphanumeric text string that uniquely identifies the user who owns the AWS account.
|Secret Key |Key that plays the role of a password.
|Try Default AWS Credentials Provider Chain |(Optional) Indicates whether to use temporary credentials.
|Region Endpoint |
|===
+
* For the *Role* connection type:
[%header%autowidth.spread]
|===
|Parameter |Description
|Configuration Name |Name for the configuration to use to reference the connector instance.
|Access Key |Alphanumeric text string that uniquely identifies the user who owns the AWS account.
|Secret Key |Key that plays the role of a password.
|Try Default AWS Credentials Provider Chain |(Optional) Indicates whether to use temporary credentials.
|Region Endpoint |URL entry point for a web service.
|Role ARN |ARN (Amazon Resources Name) that uniquely identifies AWS resources.
|===
. If you are:
+
* Using the default Amazon S3 storage, leave the default entries for the *Proxy* tab and the *Advanced* tabs.
* Connecting to a different storage than the default AWS S3, specify its URL in the the *Advanced* tab's *S3 Compatible Storage URL* field.
+
. Click  *Save*.
. Enter values for the connector operation.

= Next

Now that you have completed ____, you can try out ______.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
