= Amazon SNS XML and Maven Support - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

If you manually code a Mule application in XML either from the Studio XML editor or a text editor, you must perform the following actions to get access to a connector:

. Add the namespace for the connector to your XML flow.
. Add dependency information to your Maven `pom.xml` file.

In the Studio visual editor, when you drag a connector from the palette to the canvas, Studio automatically populates the XML code with the connector namespace and schema location.

== Add a Namespace for the Connector

If you manually code the Mule application in the Studio XML editor or another text editor, paste the following code inside the <mule> tag in your XML configuration:
[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/sns
http://www.mulesoft.org/schema/mule/sns/current/mule-sns.xsd
----

This example shows how the namespace statements are
placed in the mule XML block:

[source,xml,linenums]
----
<?xml version="1.0"?>

<mule xmlns:http="http://www.mulesoft.org/schema/mule/http"
   xmlns:sns="http://www.mulesoft.org/schema/mule/sns"
   xmlns="http://www.mulesoft.org/schema/mule/core"
   xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core
   http://www.mulesoft.org/schema/mule/sns
   http://www.mulesoft.org/schema/mule/sns/current/mule-sns.xsd
   http://www.mulesoft.org/schema/mule/http
   http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">

<!-- Put your flows and configuration elements here -->

</mule>
----

== Add a POM File Dependency

The `pom.xml` Maven file generated by Anypoint Studio contains dependencies for a Mule app. When you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to the connector. The Mule runtime engine translates the RELEASE dependency keyword to the current version.

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-amazon-sns-connector</artifactId>
  <version>RELEASE</version>
  <classifier>mule-plugin</classifier>
</dependency>
----
To obtain the most up-to-date `pom.xml` file information, access the connector in
https://www.mulesoft.com/exchange/[Anypoint Exchange] and click *Dependency Snippets*.

== Next Steps

Now that you have read about XML support, you can try out the Amazon SNS xref:amazon/amazon-sns-connector-examples.adoc[Examples].

== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
