= Amazon S3 Additional Configuration Information - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

== Create Object Operation

In the `Create Object` operation, set the `Content Length` to a value greater than zero. If the `Content Length` is set to zero (0), the `Create Object` operation creates a zero-byte object.

== To Use an AWS KMS Master Key

To encrypt objects that you want to store in S3 buckets using customer managed master keys, specify a Customer Master Key ID in the `KMS Master Key` field in the `Create Object` configuration.

== To Use the AWS Credentials Provider Chain in CloudHub

With the Default AWS Credentials Provider Chain, you can specify the access key and secret in the CloudHub environment:

. Use the following configuration to prepare a Mule app.
+
[source,xml,linenums]
----
 <s3:config name="Amazon_S3_S3_configuration" doc:name="Amazon S3 S3 configuration"
    doc:id="DOC_ID" >
  <s3:basic-connection accessKey="${aws.accessKeyId}" secretKey="${aws.secretKey}"
    tryDefaultAWSCredentialsProviderChain="true"/>
 </s3:config>
----
+
. Export this configuration to get a deployable zip archive.
. Deploy to CloudHub and set the properties `aws.accessKeyId` and `aws.secretKey` through Runtime Manager > Settings > Properties.
. Finish deploying and testing.

[NOTE]
The access key and secret key are not listed in the connector configuration. Instead, the correct values are used from the values specified in the settings.

== Next Step

You can try out the xref:amazon/amazon-s3-connector-examples.adoc[Example].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
