= Amazon SQS Additional Configuration Information - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/


== Creating the FIFO Queue

To create the FIFO queue use the *Create queue* operation in the connector and set *FifoQueue* and *ContentBasedDeduplication* to true.

The *queue name* should end with the `.fifo` extension. For example,  `MyTestFIFOQueue.fifo`.

While creating the FIFO queues choose either of the two regions US East (Ohio) or US West (Oregon). Amazon only supports these two regions for FIFO queues.

When using Amazon SQS Connector to send messages to the FIFO queue, use the same queue URL and region name that you used when creating the FIFO Queue. Also you have to give the value to the attribute `message group id` in the connector configuration while sending messages.

== Next

Now that you have completed configuration, you can try
the Amazon SQS Connector xref:amazon/amazon-sqs-connector-examples.adoc[Examples].

== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
