= Amazon S3 Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/
Support Category: Select
Amazon S3 Connector v<Major>.<Minor>

The Anypoint Amazon S3 connector provides connectivity to the Amazon S3 API, enabling you to interface with Amazon S3 to store objects, download and use data with other AWS services, and build applications that require internet storage.

Instant access to the Amazon S3 API enables seamless integrations between Amazon S3 and other databases, CMS applications such as Drupal, and CRM applications such as Salesforce. Use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. You can accomplish these tasks by using the simple and intuitive web interface of the AWS Management Console.

The AWS SDK for Java provides a Java API for AWS infrastructure services.
The Amazon S3 connector is built using the SDK for Java.

== About Connectors

Anypoint Connectors are extensions of Mule that let you work with external systems such as Salesforce, ServiceNow, Workday, Twitter, and more to send and receive information from these systems to create something new. Anypoint Connectors let you connect Mule applications to APIs and resources.

A connector lets you send and receive data over a protocol, or to and from an API. Use this information to work with Design Center or Anypoint Studio to adjust the UI settings to enable the connector to work with a Mule application.

== Prerequisites

Before starting, ensure you have the Mule Enterprise Edition and have access to the following:

* Amazon S3 connector on Exchange
* Anypoint Platform
* Design Center
* Anypoint Studio
* Amazon Web Services

You should be familiar with the use of Anypoint Platform and with creating a Mule application. You also need to have AWS Identity and Access Management (IAM) credentials.

== Audience

* Starting user -- Read this Get Started document.
 and create your Mule application in [Design Center] or [Anypoint Studio].
* Power user - Read the [XML and Maven Support] and [Examples] documents.

== Examples

== Next

Now that you have completed ____, you can try out ______.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
