= Amazon S3 Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/
Support Category: Select
Amazon S3 Connector v<Major>.<Minor>

The Anypoint Amazon S3 connector provides connectivity to the Amazon S3 API, enabling you to interface with Amazon S3 to store objects, download and use data with other AWS services, and build applications that require internet storage.

Instant access to the Amazon S3 API enables seamless integrations between Amazon S3 and other databases, CMS applications such as Drupal, and CRM applications such as Salesforce. Use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. You can accomplish these tasks by using the simple and intuitive web interface of the AWS Management Console.

The AWS SDK for Java provides a Java API for AWS infrastructure services.
The Amazon S3 connector is built using the SDK for Java.

== About Connectors

Anypoint Connectors are extensions of Mule that let you work with external systems
such as Salesforce, ServiceNow, Workday, Twitter, and more to send and receive
information from these systems to create something new. Anypoint Connectors let you
connect Mule applications to APIs and resources. You can use connectors within your
Mule applications to send and receive data over a protocol, or to and from an API.
The topics in these documents let you work with Design Center and Anypoint Studio
to configure, that is, to adjust the settings provided in the UI for each of these
programs to enable the connector to work with your Mule application.

== Prerequisites
Before starting, ensure you have access to the connector, Anypoint Platform, Design Center, and Anypoint Studio. You should have the Mule Enterprise Edition and entitlements necessary to use this software.

You should be familiar with the use of Anypoint Platform, Design Center, Anypoint Studio, and Mule applications.

To use the Amazon S3 connector, you must have the following:

* Access to Amazon Web Services.
* AWS Identity and Access Management (IAM) credentials.

This document assumes that you are familiar with Amazon S3, Mule, Anypoint Connectors,
Anypoint Studio, elements in a Mule flow, and global elements.

=== Compatibility

The Amazon S3 connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.1.x
|AWS SDK for Java|1.11.517
|===

== Audience
* New to Mule products -- Read this document and create your Mule application in
xref:amazon-s3-connector/amazon-s3-connector-connector-design-center.adoc[Design Center].
* Power user - Read the xref:amazon-s3-connector/amazon-s3-connector-connector-xml-maven.adoc[XML and Maven Support],
xref:amazon-s3-connector/amazon-s3-connector-connector-config-topics.adoc[Configuration Topics],
and xref:amazon-s3-connector/amazon-s3-connector-connector-examples.adoc[Examples].

== Templates and Examples
<List up to 10 Exchange templates and examples for this connector -- Use the Integration
Pattern categories (broadcast, migration, bidirectional sync, aggregation)>
== Triggers
TBD
== Next

Now that you have completed ____, you can try out ______.
== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
