= Amazon SQS Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

To configure a connector in Anypoint Studio:

. Install the connector.
. Configure the connector.
. Configure an input source for the connector.

== Install the Connector from Exchange

. In Anypoint Studio, create a Mule Project.
. Click the Exchange icon (X) in the Studio task bar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, select *All assets* and search for `Amazon SQS`.
. Select *Amazon SQS Connector - Mule 4* and click *Add to project*.
. Follow the prompts to install the connector.

== Install the Connector From within Studio:

. In Studio, create a Mule Project.
. In the Mule Palette, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type the name of the connector in the search field.
. Click the connector name in *Available modules*.
. Click *Add >*.
. Click *Finish*.


== Configure Amazon SQS

To configure this connector:

. Drag and drop a connector operation into the Studio canvas.
. To create a global element for the connector, click the *Global Elements* tab at the base of the canvas, and then click *Create*.
. In the *Choose Global Type* window, expand *Connector Configuration*, and click *Amazon SQS Configuration*.
. Click *OK*.
. Select *Amazon SQS Configuration (Configuration)*, and click *Edit*.
. Specify the global element properties:
+

+
[%header%autowidth.spread]
|===
|Parameter |Description
|Test queue ARN |
|Access Key |Alphanumeric text string that uniquely identifies the user who owns the AWS account.
|Secret Key |Key that plays the role of a password.
|Try Default AWS Credentials Provider Chain |(Optional) Indicates whether to use temporary credentials.
|Region Endpoint |The regional endpoint to process your requests.
|Default Global Queue URL| 
|===
+
You can either enter your credentials into the global configuration properties or reference a configuration placed in a file in the `src` folder of your project file that contains these values. You should use a configuration file for simpler maintenance and better reuse of your project.
+


. Click *Test Connection* to confirm that the parameters of your global configuration are accurate and that Mule is able to successfully connect to your instance of Amazon SQS.
+

. Click *OK* to save the global connector configurations.


== Configure an Input Source

Configure an input source for the connector such as an operation for this connector, *HTTP Listener*, or *Scheduler*.

You can put the following operations for the connector in the *Source* area of the Studio canvas. 


  * The connector's *Receive messages* operation to initiate access to your app to receive messages from specified queue

  
If you use an Amazon SQS connector's operation as a trigger, enter the URL of the Amazon SQS queue you want to receive messages from and the number of messages to receive on the *General* tab.

== Next Step

After configuring the connector in Studio,
see the xref:amazon/amazon-sqs-connector-config-topics.adoc[Additional Configuration Information] topic for more configuration steps.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]