= Amazon SQS Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select
Amazon SQS Connector Version Major.Minor

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect
to APIs and resources on external systems, such as Salesforce, Amazon SQS, ServiceNow,
and Twitter.

== Prerequisites
Before creating an app, you must have access to the Amazon SQS target resource and
Anypoint Platform. You must also understand how to create a Mule app using
Design Center or Anypoint Studio.

== Audience
* Starting user -- To create your Mule app,
see xref:amazon/amazon-sqs-connector-design-center.adoc[Design Center Configuration]
or xref:amazon/amazon-sqs-connector-studio.adoc[Studio Configuration]. The
xref:amazon/amazon-sqs-connector-config-topics.adoc[Additional Configuration Information]
topic helps extend your understanding of the Amazon SQS connector. The
xref:amazon/amazon-sqs-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Power user - Read the xref:amazon/amazon-sqs-connector-xml-maven.adoc[XML and Maven Support],
xref:amazon/amazon-sqs-connector-config-topics.adoc[Additional Configuration Information],
and xref:amazon/amazon-sqs-connector-examples.adoc[Examples] topics.
== Common Use Cases For the Connector
// List common use cases for the connector and provide
// link to the Examples section use cases.
== Learn Using Exchange Templates and Examples
https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
you can use as a starting point for your app, as well as examples that illustrate a complete solution.
// List up to 10 Exchange templates and examples for the connector
// Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation)
== Next Step
After you have met the prerequisites and experimented with templates and examples, you are ready to create an app with
xref:amazon/amazon-sqs-connector-design-center.adoc[Design Center] or xref:amazon/amazon-sqs-connector-studio.adoc[Anypoint Studio].
== See Also
* https://www.mulesoft.com/exchange/?search=amazon-sqs&type=connector[Anypoint Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]
