= Use Studio to Configure Amazon DynamoDB - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Studio (Studio) editors help you design and update your Mule applications, properties, and configuration files.

To add and configure a connector in Studio:

. Create a Mule project.
. Add the connector to your Mule project.
. Configure an input source for the connector's flow.
. Configure the connector.

If you are new to configuring Anypoint connectors in Studio, see xref:introduction/intro-config-use-studio.adoc[Use Studio to Configure a Connector].

== Create a Mule Project

In Anypoint Studio, create a new Mule project in which to add and configure the connector.

. In Anypoint Studio, from the main menu, select *File > New > Mule Project*.
. Enter a name for your Mule project, and click *Finish*.

== Add the Connector to Your Project

Add Amazon DynamoDB Connector to a Mule project to automatically populate the XML code with the connector's namespace and schema location, as well as add the required dependencies to the project's `pom.xml` file.

. In the *Mule Palette* view, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type `Amazon DynamoDB` in the search field.
. Click the *Amazon DynamoDB* in *Available modules*.
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio does not make that connector available to other projects in your Studio workspace.

== Configure an Input Source

An input source initiates a flow when a specified condition is met. The act of dragging the connector's operation from the palette onto the Studio canvas automatically populates the XML code with the connector namespace and schema location.

Possible input sources for this connector are:

* `HTTP Listener`, which initiates a flow each time it receives a request on the configured host and port.
* `Scheduler`, which initiates a flow when a time-based condition is met.

For example, to configure `HTTP Listener`, follow these steps:

. In the *Mule Palette* view, select *HTTP*, and then select *Listener*.
. Drag *Listener* to the Studio canvas.
. On the *Listener* configuration screen, optionally change the value of the *Display Name* field.
. Specify a value for the *Path* field.
. Configure a global element that can be used by all instances of `HTTP Listener` in the app.
+
To access the global element configuration fields, click the plus sign (+) next to the *Connector configuration* field.
. On the *General* tab, specify connection information.
. On the *TLS* tab, optionally specify TLS information.
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specific server.
. Click *OK*.

== Configure a Global Element for the Connector

To configure a connector, first configure a global element that can be used by all instances of that connector in the app.

When you configure a global element, you must provide the authentication credentials to use for accessing the target Amazon DynamoDB system. Amazon DynamoDB Connector supports both basic and role-based authentication.

You can enter your authorization credentials in the global configuration properties or you can reference a configuration file that contains ANT-style property placeholders. For simpler maintenance and better reusability of your project, it is recommended that you use a configuration file. To make the values for the placeholders available, create a YAML file or properties file to contain the values, place the file in `src/main/resources` in the Mule project, and then reference the file from the connector configuration.

To configure the global element for the Amazon DynamoDB connector, follow these steps:

. In the *Mule Palette* view, select *Amazon DynamoDB* and then select the desired operation.
. Drag the operation onto the Studio canvas to the right of the input source.
. In the configuration screen for the operation, click the plus sign (+) next to the Connector configuration field to configure a global element for the connector.
. On the *General* tab, configure basic or role authentication, as described in xx.
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm hat Mule can connect with the specified server.
. Click *OK*.

=== Basic Authentication

Enter the following information on the *General* tab of the global element to configure basic authentication:

[%header,cols="30s,70a"]
|===
|Parameter |Description
|Name |Enter the configuration name.
|Connection | Select `Basic`.
|Session Token | Enter the session token provided by Amazon STS.
|Access Key | Enter the alphanumeric text string that uniquely identifies the user who owns the account.
|Secret Key | Enter the key that acts as a password.
|Try Default AWS Credentials Provider Chain | Select whether temporary credentials should be used.
|===

For example:

<screenshot>

For more information about configuring basic authentication, see the xref:amazon/amazon-dynamodb-connector-reference.adoc[Amazon DynamoDB Reference].

=== Role Authentication

Enter the following information to configure role authentication:
+
[%header,cols="30s,70a"]
|===
|Parameter |Description
|Name |Enter the configuration name.
|Connection | Select `Role`.
|Role ARN | Enter
|Access Key | Enter the alphanumeric text string that uniquely identifies the user who owns the account.
|Secret Key | Enter the key that acts as a password.
|Try Default AWS Credentials Provider Chain | Select whether temporary credentials should be used.
|Region Endpoint |
|===

<screenshot>

For more information about configuring role authentication, see the xref:amazon/amazon-dynamodb-connector-reference.adoc[Amazon DynamoDB Reference].

== Configure Other Connector Fields

After you configure a global element for Amazon DynamoDB connector, configure the the other fields for the connector. For information, see the xref:amazon/amazon-dynamodb-connector-reference.adoc[Amazon DynamoDB Reference].

== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
