= Troubleshooting Compression Module - Mule 4

To troubleshoot Compression module, become familiar with the information about enabling verbose logging and and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with the Compression Module is failing, temporarily enable verbose logging for Compression module. +

Remember to always disable the enhanced verbosity after troubleshooting because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="org.mule.extension.compression" level="DEBUG"/>
				<AsyncLogger name="org.apache.commons.compress" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* COMPRESSION:COULD_NOT_COMPRESS

There is an error while trying to compress a content.

* COMPRESSION:COULD_NOT_DECOMPRESS

There is an error while trying to decompress a content.

* COMPRESSION:INVALID_ARCHIVE

There is an error because the content to be decompressed is not a valid archive.

* COMPRESSION:TOO_MANY_ENTRIES

There is an error because an archive with multiple entries is passed to the decompress operation and the module is not able to pic only one entry.


== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:compression-documentation.adoc[Compression Module Reference]
