= To Consume Messages
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mq, amnypoint-mq, connector, consume, message, messaging, queue


The Consume operation in the Anypoint MQ connector provides ability to consume a Message at any given time of the flow, from any given Destination.

== Consuming A Message
The syntax to consume a message from a Queue is:

[source,xml,linenums]
----
<anypoint-mq:consume config-ref="MQ_config" destination="#[vars.destination]"/>
----

The operation above consumes the first available message in the Queue identified by the destination, and then converts it to a `MuleMessage` resulting in the following structure:

* The message's content as payload.
* The message's metadata in the message attributes.

By default, the ACK mode is `MANUAL`, so the Message won't be ACKed. If you want the message to be acknowledged as soon as it is consumed, set the mode to `IMMEDIATE`.
For more information regarding a Message ACK, check the xref:anypoint-mq/anypoint-mq-ack.adoc[How To Handle Message Acknowledgement].

== Waiting for a Message

By default, the maximum wait time is configured in 10 seconds, producing a `null` result if no message is available in that period.
If order to configure a timeout that fits better your use case, customize the `pollingTime` parameter.

== Incomming Message Metadata

As stated before, each Message received will consist of two parts:

* The payload, containing the content of the Message
* The attributes, containing metadata regarding the Message

This Metadata maps all the information available in a Anypoint MQ Message, including:

* Message ID
* Headers
* Properties

Check the |xref:anypoint-mq/anypoint-mq-connector-reference.adoc#consume[Consume Docs] for details regarding the Attributes structure.

== See Also

* xref:anypoint-mq/anypoint-mq-connector-reference.adoc#consume[Consume Technical Reference]
* xref:anypoint-mq/anypoint-mq-ack.adoc[How To Handle Message Acknowledgement]