= Anypoint MQ Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mq, connector

_Select_

The Anypoint MQ connector provides publish-subscribe messaging to Mule applications using the Anypoint MQ cloud service.

Anypoint MQ supports a wide range of messaging use cases: enterprise messaging patterns, asynchronous communications between microservices, IoT, and more. Anypoint MQ also has a REST API for publishing or consuming messages using any framework such as node.js, Java, Go, and devops bash scripts.

For more information, see the xref:mq::index.adoc[Anypoint MQ documentation set] and additional resources listed in <<See Also>>.

== Prerequisites

To use this connector, you should be familiar with Anypoint Studio, Anypoint connectors, and Mule flows. The Anypoint MQ connector is free, but connecting to the service in Anypoint Platform requires a license. Free trial software is available.

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.0.0 and later
|Anypoint Studio |v7 and later
|===

== To Install This Connector

From Anypoint Exchange:

. In Anypoint Studio, click the Exchange icon in the Studio task bar.
. Click Login in Anypoint Exchange and supply your Anypoint Platform username and password.
. Search for the connector and click Install.
. Follow the prompts to install the connector.

For applications written in XML or that are standalone:

. Open your Mule project in Anypoint Studio.
. Add the connector as a dependency in the pom.xml file:
+
[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>anypoint-mq-connector</artifactId>
  <version>2.0.0</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

== To Configure with the Studio Visual Editor

. In Studio, click File > New > Mule Project.
. Search for "http" and drag the HTTP connector to the Studio Canvas. Click the HTTP connector, and click the green plus sign to the right of Connector Configuration. Click OK to accept the defaults. In the HTTP properties window, set the Path to `/mq/{messageId}`.
. Search for "mq" and drag the *Anypoint MQ* connector to the canvas. If you cannot find this connector, return to
<<To Install This Connector>> and ensure you installed the connector.
. Click the green plus sign to the right of Connector Configuration.
. Specify the URL for the region you want your MQ queues and exchanges to reside.
+
Possible values are:
+
** North America:
*** US East (N. Virginia): `+https://mq-us-east-1.anypoint.mulesoft.com/api/v1+`
*** US West (Oregon): `+https://mq-us-west-2.anypoint.mulesoft.com/api/v1+`
*** Central Canada: `+https://mq-ca-central-1.anypoint.mulesoft.com/api/v1+`
** Europe:
*** EU (Ireland): `+https://mq-eu-west-1.anypoint.mulesoft.com/api/v1+`
*** EU (London): `+https://mq-eu-west-2.anypoint.mulesoft.com/api/v1+`
** APAC:
*** Asia Pacific (Singapore): `+https://mq-ap-southeast-1.anypoint.mulesoft.com/api/v1+`
*** Asia Pacific (Sydney): `+https://mq-ap-southeast-2.anypoint.mulesoft.com/api/v1+`
+
FIFO queues can reside in US East, US West, and EU Ireland.
+
. In Anypoint Platform, click MQ > Client Apps. If needed, create a client app.
. Copy the Anypoint Platform > MQ > Client App > Client App ID value to Studio's Client ID field.
. Copy the Client App > Client Secret value to Studio's Client Secret field. You can ignore the other settings to test your  connector.
. Click OK.
. Click the Operation field and specify an operation such as Publish or Consume.
. If using the Publish or Consume operations, specify the *Destination* as the name of the queue or message exchange that you set in Anypoint Platform.
. For the Publish operation, you can leave the Message ID field empty, or specify a message ID if you want to publish a specific message ID. If a message ID is not set, MQ auto generates a unique message ID for each message that’s sent to a queue. When publishing to FIFO queues, if you specify a Message ID and the Message ID is the same on multiple messages, the messages with the same Message ID are not redelivered.

Possible operations are:

[%header%autowidth.spread]
|===
|Operation |Description
|xref:anypoint-mq/anypoint-mq-connector-reference.adoc#ack[Ack] |Indicates that the message has been consumed correctly and deletes the message from in-flight status.
|xref:anypoint-mq/anypoint-mq-connector-reference.adoc#consume[Consume] |Consumes messages from a queue.
|xref:anypoint-mq/anypoint-mq-connector-reference.adoc#nack[Nack] |Changes the status of the message from in-flight to in-queue to be consumed again by a subscriber.
|xref:anypoint-mq/anypoint-mq-connector-reference.adoc#publish[Publish] |Publishes messages
to a queue or message exchange.
|===

For a list of configuration fields for each operation and information about XML elements, see the xref:anypoint-mq/anypoint-mq-connector-reference.adoc[Anypoint MQ Connector Reference].

== XML Schema and Endpoint

If you are creating an XML or standalone application, add this dependency to your pom.xml file:

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>anypoint-mq-connector</artifactId>
  <version>2.0.1</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

For the latest POM, Gradle, or SBT dependencies, see the  https://www.anypoint.mulesoft.com/exchange/com.mulesoft.connectors/anypoint-mq-connector/[Exchange Anypoint MQ Connector] asset. Click *Dependency Snippets* for a complete list.

*Note:* If you are creating an application using Anypoint Studio, when you install the MQ connector, the MQ dependency
in the pom.xml file is updated for you.

Endpoint: `+http://www.mulesoft.org/schema/mule/anypoint-mq+`

== Example: MQ and DataWeave

The following example illustrates the use of the Anypoint MQ connector with DataWeave to transform
a Mule message to JSON:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:dw="http://www.mulesoft.org/schema/mule/ee/dw"
	xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:spring="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/ee/dw
	http://www.mulesoft.org/schema/mule/ee/dw/current/dw.xsd
http://www.springframework.org/schema/beans
http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core
http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http
http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/anypoint-mq
http://www.mulesoft.org/schema/mule/anypoint-mq/current/mule-anypoint-mq.xsd">
  <anypoint-mq:default-subscriber-config name="Anypoint_MQ_Configuration"
  doc:name="Anypoint MQ Configuration">
      <anypoint-mq:connection url="https://mq-us-east-1.anypoint.mulesoft.com/api/v1"
      clientId="<id>" clientSecret="<secret>"/>
  </anypoint-mq:default-subscriber-config>
<flow name="producerFlow">
  <poll doc:name="Poll">
    <dw:transform-message doc:name="Create Customer">
    <dw:set-payload><![CDATA[%dw 1.0
%output application/json
---
{
    "firstName" : "Joe",
    "lastName" : "Schmoe",
    "company" : "Acme, Inc"
}]]></dw:set-payload>
    </dw:transform-message>
  </poll>
  <anypoint-mq:publish config-ref="Anypoint_MQ_Configuration"
    destination="MyExchange"
    messageId="mq42" doc:name="Anypoint MQ">
   <anypoint-mq:body>#[payload]</anypoint-mq:body>
  </anypoint-mq:publish>
</flow>
</mule>
----

== See Also

* xref:mq::index.adoc[MQ documentation]
* xref:mq::mq-faq.adoc[MQ FAQ]
* xref:mq::mq-apis.adoc[REST API]
* xref:anypoint-mq/anypoint-mq-connector-reference.adoc[Anypoint MQ Connector Reference]
* https://www.anypoint.mulesoft.com/exchange/com.mulesoft.connectors/anypoint-mq-connector/[Anypoint MQ Connector]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/[MuleSoft Developer Portal]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]