= To Publish Messages
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint-mq, mq, connector, publish, messaging, queue

This operation allows you to create a new Anypoint MQ Message and send it to the specified destination, be it a Queue, FIFO Queue or an Exchange. With it, you can configure not only the content of the message, but also all the headers and properties that may be need.

== Sending a Message

When used in its default form, the connector will publish whatever is in the message payload:

[source,xml,linenums]
----
<anypoint-mq:publish destination="invoiceQueue" config-ref="MQ_config"/>
----

But what happens if the payload is not in the correct format, and you actually need to make a transformation? You could place a DataWeave transformation before the `publish` operation, but that would cause the message payload to change and impact the operation placed after the `publish` operation.

To avoid this undesired impact, you can now place the transformation inside the `publish` operation:

[source,xml,linenums]
----
<anypoint-mq:publish destination="invoiceQueue" config-ref="MQ_config">
  <anypoint-mq:body>#[%dw 2.0
   output application/json
   ---
   payload.payments
   ]</anypoint-mq:body>
</anypoint-mq:publish>
----

Now, the transformation can be used for generating the content that will be published, without producing a side effect on the message in transit.

== Configuring User Properties

Every Anypoint MQ Message can have a set of properties, which can be used in many different ways, like to provide compatibility with other messaging systems or communicate the content-type of the message.
The `publish` operation allows you to configure this properties directly in the Message:

Whenever you need to set a property for an outgoing Message, all you have to do is use the `properties` element in the Message:

[source,xml,linenums]
----
<anypoint-mq:publish config-ref="MQ_config" destination="${bridgeDestination}" 
                     properties="#[{AUTH_TYPE: 'jwt', AUTH_TOKEN: attributes.queryParams.token}]">
    <anypoint-mq:body>#["bridged_" ++ payload]</anypoint-mq:body>
</anypoint-mq:publish>
----

== See Also

xref:anypoint-mq/anypoint-mq-publish-consume.adoc[To Listen For A Reply]