= Upgrading and Migrating NetSuite Connector to Version 12.x
:page-aliases: connectors::netsuite/netsuite-connector-upgrade-migrate.adoc

Upgrade Anypoint Connector for NetSuite (NetSuite Connector) to version 12.x.

== Supported Upgrade Paths

[%header,"cols=50a,50a"]
|===
|From Version | To Version
|11.x |12.x
|===

== Changes in This Release

* NetSuite Connector is now compatible only with Java 17.
* The connector no longer supports the *Omit the internal Id in the name of the custom field* field because its functionality is now the default behavior of the connector.
* These libraries are upgraded to address reported security vulnerabilities:

** The `springframework` library is upgraded to version 6.2.
** The `jakarta.activation-api` library is upgraded to version 2.1.4.
** The `wiremock.server.dependency` library is upgraded to version 3.0.1.
** The PowerMock library is replaced by Mockito version 5.2.0.
** The `commons-io` library is added at version 2.16.1.
** The `disruptor` library is added at version 4.0.0.

== Requirements

Ensure your system meets the following compatibility requirements before you perform the upgrade:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule |4.9.0 and later
|Java |17
|===

== Upgrade Prerequisites

Before you perform the upgrade, create a backup of your files, data, and configuration in case you need to restore to the previous version.

== Upgrade Steps

Follow these steps to perform the upgrade to version 12.x:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `netsuite` in the search field.
. In *Available modules*, select *NetSuite* and click *Add*.
. Click *Finish*.
. Verify that the `mule-netsuite-connector` dependency version is 12.x in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

== Post-Upgrade Steps

After you install the latest version of the connector:

* Remove any `omitInternalIdFromCustomFields` attribute from the NetSuite global configuration in your flow XML or Studio settings.
* Update any DataWeave scripts or configuration that references custom field names in the `TYPE__SCRIPTID__INTERNALID` format to use the new `TYPE__SCRIPTID` format.
* Confirm that each Mule application using this connector runs on Mule 4.9.0 or later with Java 17.
* Ensure your connector configuration uses *Token-Based Authentication*.
* Verify that error handling still works as expected. See xref:netsuite-troubleshooting.adoc[Troubleshooting NetSuite Connector] if you encounter new validation or connectivity errors.

== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Revert the Upgrade

If it is necessary to revert to the previous version of NetSuite Connector, change the `mule-netsuite-connector` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:netsuite-reference.adoc[NetSuite Connector Reference]
* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.salesforce.com[Salesforce Help]
