= AS2 Connector 6.2 - Mule 4
:page-aliases: connectors::as2/as2-connectorMule4.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Premium]

Mule runtime engine (Mule) supports the AS2 protocol through Anypoint Connector for AS2 (AS2 Connector).

AS2 Connector enables trading partners to transmit and receive AS2 messages with EDI-X12, EDIFACT, XML, or binary payloads, for example:

* Send messages, signed or unsigned, over HTTP or HTTPS, using the AS2 protocol
* Receive messages over HTTP or HTTPS, using the AS2 protocol
* Receive asynchronous MDN for sent messages

For compatibility information and fixed issues, see the AS2 Connector Release Notes.

For a major or minor release, see
xref:<as2-connectors-upgrade-migrate.adoc[Upgrade and Migrate].

== Prerequisites

To use this connector, you must be familiar with:

* The AS2 target resource
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have access to:

* Credentials to access the AS2 target resource
* Anypoint Platform
* Anypoint Studio version 7.6 or later

== Common Use Cases for the Connector

Common use cases for AS2 Connector include the following:

* Send with sync MDN

Sends a message through HTTP or HTTPS using the AS2 protocol requesting the partner for a synchronous MDN (receipt)

* Send with async MDN

Sends a message through HTTP or HTTPS using the AS2 protocol requesting the partner for an asynchronous MDN (receipt)

* Listener

Source that receives messages via HTTP or HTTPS using the AS2 protocol

* MDN Listener

Source that receives asynchronous MDN receipts via HTTP or HTTPS using the AS2 protocol

* Non repudiation Listener

Source that receives a signed copy of a receipt or a message for persistent non-repudiation storage

== Non-Repudiation Storage of AS2 Messages and MDNs

If needed, you can configure non-repudiation storage for your AS2 operations to support regulatory or compliance requirements.

Only signed messages and MDNs are eligible for non-repudiation.

The following AS2 Connector 6.1 sources and operations support the non-repudiation feature:

* AS2 Send Sync operation
* AS2 Send Async operation
* AS2 Listener source
* AS2 MDN Listener source

=== Prerequisites for Non-Repudiation Storage

To enable non-repudiation of a message in AS2 Connector, you must implement and configure a separate Mule flow that acts as a non-repudiation flow:

* The non-repudiation flow must have access to the signed MIME message that is passed to it, along with appropriate non-repudiation specific attributes.
* This non-repudiation-specific Mule flow is responsible for receiving, storing, and acting upon the messages and attributes it receives.
* The name of this non-repudiation flow must be configured on an appropriate listener or operation that has non-repudiation storage enabled.

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:as2-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
