= To Trigger a Flow When a New File is Created or Modified
:keywords: sftp, connector, trigger, new file, updated file, message source
:toc:
:toc-title:

The File, FTP, and SFTP connectors provide a listener (called `On New or Updated file` in Studio and Flow Designer UI) that polls a directory for files that have been created or updated. One message is generated for each file that is found.

The key part of this functionality is how to determine that a file is new. There are three strategies for making this determination:

 * Setting the `autoDelete` parameter to `true`. This setting deletes each file after it has been processed so that all files found in the next poll will be new.
 * Setting `moveToDirectory` parameter to move each processed file to a different directory after it has been processed. This produces the same effect as `autoDelete` but without losing the file.
 * Using the `watermark` parameter to only pick files that have been created or updated after the last poll was executed.
 * Using a matcher to filter the files.

== Listener

Listeners function similarly for the FTP, SFTP, and File connectors. However, the XML element used for them is different: