== Dynamic Connections

Many integrations require connecting to different servers depending on conditions. 

Examples of this include:

* Connecting to different invoice storage servers depending on the branch that sent the invoice.
* Connecting to different servers depending on an integration subject, such as in a multi-tenant use case.

To accommodate these use cases, the `config` element supports expressions, which make it possible for connection parameters to evaluate these conditions and connect to the correct server.

The example that follows shows a dynamic multicast app that:

* Defines a `config` for the connector in which the `host`, `username`, and `password` are expressions.
* Describes a flow in which content is posted through HTTP.
* Uses the File connector to read a CSV file that contains a random set of SFTP destinations with columns such as host, user, and port.
* Uses a `<foreach>` component to iterate over each of the lines in the CSV file.
* On each `<foreach>` iteration, resolves each expression in the connector's `config` to a different value, establishing different connections to each of the servers.