= Kafka Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

Kafka Connector v3.0

The Anypoint Connector for Apache Kafka allows you to interact with the Apache Kafka messaging system, and enable seamless integration between your Mule app and an Apache Kafka cluster, using Mule runtime.

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect 
to APIs and resources on external systems, such as Salesforce, Kafka, ServiceNow,
and Twitter.

== Prerequisites

Before creating an app, you must have access to the Kafka target resource and 
Anypoint Platform. You must also understand how to create a Mule app using 
Design Center or Anypoint Studio.

== Audience

* Starting user -- Read this Get Started document and create your Mule app in
xref:kafka/kafka-connector-design-center.adoc[Design Center] or 
xref:kafka/kafka-connector-studio.adoc[Anypoint Studio]. 
* Power user - Read xref:kafka/kafka-connector-xml-maven.adoc[XML and Maven Support]
and xref:kafka/kafka-connector-examples.adoc[Examples].

== Next

Now that you've started, try xref:kafka/kafka-connector-design-center.adoc[Design Center] or xref:kafka/kafka-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-kafka-connector/[Kafka in Anypoint Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
