= Kafka Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

Kafka Connector v3.0

The Anypoint Connector for Apache Kafka allows you to interact with the Apache Kafka messaging system, enabling seamless integration between your Mule applications and an Apache Kafka cluster, using Mule runtime.

Read through this user guide to understand how to set up and configure a basic Mule flow with the Apache Kafka connector.

== About Connectors

Anypoint Connectors are extensions of Mule that let you work with external systems such as Salesforce, ServiceNow, Workday, Twitter, and more to send and receive information from these systems to create something new. Anypoint Connectors let you connect Mule applications to APIs and resources. 

A connector lets you send and receive data over a protocol, or to and from an API. Use 
this information to work with Design Center or Anypoint Studio to adjust the UI settings 
to enable the connector to work with a Mule application.

== Prerequisites

Before starting, ensure you have access to the connector, Anypoint Platform, Design Center, 
or Anypoint Studio. You should have the Mule Enterprise Edition and entitlements necessary 
to use this software.

== Audience

* Starting user -- Read Get Started (this document) and configure your Mule application in 
xref:kafka/kafka-connector-design-center.adoc[Design Center] or 
xref:kafka/kafka-connector-studio.adoc[Anypoint Studio]. 
* Power user - Read xref:kafka/kafka-connector-xml-maven.adoc[XML and Maven Support]
and xref:kafka/kafka-connector-examples.adoc[Examples].

== Next

Now that you've started, try xref:kafka/kafka-connector-design-center.adoc[Design Center] or 
xref:kafka/kafka-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-kafka-connector/[Kafka in Anypoint Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
