= Apache Kafka Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Apache Kafka Connector v4.0

Anypoint Connector for Apache Kafka (Apache Kafka Connector) enables you to interact with the Apache Kafka messaging system and achieve seamless integration between your Mule app and a Kafka cluster, using Mule runtime engine (Mule).

For compatibility information see the xref:release-notes::connector/kafka-connector-release-notes-mule-4.adoc[Apache Kafka Connector Release Notes].

== Prerequisites

Before creating an app, you must:

* Have access to the Apache Kafka target resource and Anypoint Platform
* Understand how to create a Mule app using Design Center or Anypoint Studio
* Have access to Apache Kafka to get values for the fields that appear in Studio and Design Center

== Use Cases

Apache Kafka is a multi-purpose application. Integration with Apache Kafka relies on the applications that are typically used with it. 

A few examples of use cases include:

* An integration application that ensures patients in a hospital receive the care they need in a timely manner +
An example of this is a hospital server that processes emergency requests for patient admissions. The requests are ordered by priority, which is determined by specified criteria, such as how critical the patient's condition is and the staff that is available to treat the patient. In this scenario, an application processes Kafka messages in the order that they are received, relying on the order and idempotency of the messages sent through the queue. 
* An application that is time-sensitive +
An example is a newsroom that uses the Apache Kafka system to deliver the latest news. The news must always arrive at the latest point first. In this case, reading from the Kafka queue sometimes requires skipping to the end of the queue in order to retrieve the latest news first. 
* Multiple applications that are reliant on the information provided by Apache Kafka +
For example, a department store uses a website activity tracker to improve the online shopping experience. The data that is gathered is sent to multiple departments for various computations. Each department reviews the information that's received to stay informed about what the customer is looking for and then provides recommendations accordingly. 

== Audience

* Starting user
+
To create a Mule app, see
xref:kafka/kafka-connector-design-center.adoc[Apache Kafka Design Center Configuration] or
xref:kafka/kafka-connector-studio.adoc[Apache Kafka Studio Configuration].
+
* Power user
+
Read xref:kafka/kafka-connector-xml-maven.adoc[XML and Maven Support]
and xref:kafka/kafka-connector-examples.adoc[Examples].

== Next

After you complete the prerequisites, you are ready to create an app with xref:kafka/kafka-connector-design-center.adoc[Use Design Center to Configure Apache Kafka Connector Configuration] or xref:kafka/kafka-connector-studio.adoc[Use to Studio to Configure Apache Kafka Connector].

== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-kafka-connector/[Apache Kafka Connector]
* xref:introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
