= Set the Error Status Code and Reason Phrase - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: connectors::http/http-error-status-reason-phrase-task.adoc

The following Mule application example uses Anypoint Connector for HTTP (HTTP Connector) and helps you to set the error status code and reason phrase for a user login validation request. To view the status code and explanation of a an HTTP request, use a browser extension such as Postman (Google Chrome), or the http://curl.haxx.se/[curl] command line utility. +
The example expects to receive requests in the address of http://localhost:8081/login/, these requests must contain a query parameter named `user`. Depending on the value of this parameter, one of two things may occur:

* When the parameter equals to `user=mule`: +
** The validation evaluates to true.
** A set payload element sets the message payload to a success message.
** The HTTP Connector sets variables in *Status Code* and *Reason* as `200 Log in Successful!`.

* When the parameter equals to `user=anythingElse`: +
** The validation assertion fails.
** The flow calls an error handler.
** The HTTP Connector sets the variables in *Status Code* and *Reason* as `404 Requested user does not exist`

Note that in either case, the request response doesn't display as the response body, so it won't display if you make your request through a browser window. 



== XML Editor

. Create a flow with an HTTP Listener and set the *Path* to `/login`.
. Create a Global Element for the connector, set the *Host* to `localhost`, and leave the *Port* as the default `8081`. Set the *config-ref* attribute in the listener to the name of the created configuration.
+
[source,xml,linenums]
----
<http:listener-config name="HTTP_Listener_config" >
    <http:listener-connection host="localhost" port="8081" />
</http:listener-config>
<flow name="customResponseFlow" >
    <http:listener path="/login" config-ref="HTTP_Listener_config"/>
</flow>
----

. In the properties editor for HTTP Connector, in the *Responses* section, set the *Status Code* to 200 and the *Reason* to `Login Successful`.
+
[source,xml,linenums]
----
<http:listener-config name="HTTP_Listener_config" >
    <http:listener-connection host="localhost" port="8081" />
</http:listener-config>
<flow name="customResponseFlow" >
    <http:listener path="/login" config-ref="HTTP_Listener_config">
        <http:response statusCode="200" reasonPhrase="Login Successful" />
    </http:listener>
</flow>
----

. In the *Error Response Settings* section, set the *Status Code* to `&#35;[vars.errorStatusCode]` and the reason to `&#35;[vars.errorReasonPhrase]`.
. After HTTP Listener, add a *Validation: Is True* processor:
.. In order to validate the 'user' query parameter, add the following in the *Expression* field:
+

[source,text,linenums]
----
#[attributes.queryParams.user == 'mule']
----

. After the validation, add a Set Payload element and set its *Value* field to `Log in Successful!`
+
[source,xml,linenums]
----
<http:listener-config name="HTTP_Listener_config" >
    <http:listener-connection host="localhost" port="8081" />
</http:listener-config>
<flow name="customResponseFlow" >
    <http:listener path="/login" config-ref="HTTP_Listener_config">
        <http:response statusCode="200" reasonPhrase="Login Successful" />
        <http:error-response statusCode="#[vars.errorStatusCode]" reasonPhrase="#[vars.errorReasonPhrase]" />
    </http:listener>
    <validation:is-true expression="#[attributes.queryParams.user == 'mule']"/>
    <set-payload value="Log in Successful!" />
</flow>
----

. Add an *On Error Propagate* to the Error Handling section of your flow.
. Add two Variable transformers in this exception strategy and: +
* Configure the first to set the variable `errorStatusCode` to `404`
* Configure the second to set `errorReasonPhrase` to `Requested user does not exist`
+
[source,xml,linenums]
----
<http:listener-config name="HTTP_Listener_config" >
    <http:listener-connection host="localhost" port="8081" />
</http:listener-config>
<flow name="customResponseFlow" >
    <http:listener path="/login" config-ref="HTTP_Listener_config">
        <http:response statusCode="200" reasonPhrase="Login Successful" />
        <http:error-response statusCode="#[vars.errorStatusCode]" reasonPhrase="#[vars.errorReasonPhrase]" />
    </http:listener>
    <validation:is-true expression="#[attributes.queryParams.user == 'mule']"/>
    <set-payload value="Log in Successful!" />
    <error-handler name="Error_Handler" >
        <on-error-propagate enableNotifications="true" logException="true" >
            <set-variable value="404" variableName="errorStatusCode"/>
            <set-variable value="Requested user does not exist" variableName="errorReasonPhrase"/>
        </on-error-propagate>
    </error-handler>
</flow>
----


== Status Code and Reason - Full XML Code

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns:validation="http://www.mulesoft.org/schema/mule/validation"
      xmlns:http="http://www.mulesoft.org/schema/mule/http"
      xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
                          http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
                          http://www.mulesoft.org/schema/mule/validation http://www.mulesoft.org/schema/mule/validation/current/mule-validation.xsd">
    <http:listener-config name="HTTP_Listener_config" >
        <http:listener-connection host="localhost" port="8081" />
    </http:listener-config>
    <flow name="customResponseFlow" >
        <http:listener doc:name="Listener" path="/login" config-ref="HTTP_Listener_config">
            <http:response statusCode="200" reasonPhrase="Login Successful" />
            <http:error-response statusCode="#[vars.errorStatusCode]" reasonPhrase="#[vars.errorReasonPhrase]" />
        </http:listener>
        <validation:is-true expression="#[attributes.queryParams.user == 'mule']"/>
        <set-payload value="Log in Successful!" />
        <error-handler name="Error_Handler" >
            <on-error-propagate enableNotifications="true" logException="true" >
                <set-variable value="404" variableName="errorStatusCode"/>
                <set-variable value="Requested user does not exist" variableName="errorReasonPhrase"/>
            </on-error-propagate>
        </error-handler>
    </flow>
</mule>
----
