= Troubleshoot HTTP Connector - Mule 4
:keywords: anypoint studio, esb, connectors, http, https, http headers, troubleshooting, rest, raml
:page-aliases: connectors::http/http-troubleshooting.adoc

To troubleshoot Anypoint Connector for HTTP (HTTP Connector), become familiar with the information about troubleshooting connectivity, permissions and server-side issues, troubleshooting Mule application issues, and interpreting commonly thrown messages.

== Enable Wire Logging

Sometimes you are not sure why the application is failing and you require a better understanding of what is going on with the app. Enabling wire logging logs the actual raw HTTP requests and responses flowing. You can the use the logs to validate the current configuration or to compare the HTTP Connector behavior to other clients and servers.

To enable HTTP wire logging:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. If the following line is already in the `log4j2.xml` file, uncomment it to enable it; otherwise, add it:

[source,xml,linenums]
----
<?xml version="1.0" encoding="utf-8"?>
<Configuration>
    ...
    <Loggers>
        ...
        <!-- Http Logger shows wire traffic on DEBUG. -->
        <AsyncLogger name="org.mule.service.http.impl.service.HttpMessageLogger" level="DEBUG"/>
        ...
    </Loggers>
</Configuration>
----

[start=6]
. Save your changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.

== Enable TLS Debugging

When SSL failures occur because of HTTPS, usually connections cannot be established and wire logging is not helpful. In these situations, enable TLS debugging that logs all SSL related data, such as connection attempts, handshakes and negotiations.

You can then examine the logs to determine whether the correct certificates are in place, why a cipher or protocol mismatch occurs or why connectivity fails.

To enable TLS debugging, configure the following system property: `-Djavax.net.debug=ssl`.


== Troubleshoot Host Header Misuse

HTTP clients use the `Host` header to indicate the host and port number of the resource requested. The HTTP Connector *Request* operation autogenerates this mandatory header considering the configured host and port.

Often, servers do not account for the port information because it's optional, and fail when receiving a request that has both the host and port data.

Such failures should be reported to the server owners. As a workaround for the issue, modify the *Request* operation by providing an explicit `Host` header without the port section.

The following examples shows the `<http:headers>` configuration that sends a `Host: somehost.com` header:

[source,xml,linenums]
----
<flow name="connectingToFaultyServer">
  <http:request method="GET" url="http://somehost.com:8081/api/v3/someresource">
    <http:headers>
      #[{"Host" : "somehost.com"}]
    </http:headers>
  </http:request>
  <logger level="INFO"
   message="#['Received a ' ++ attributes.status code ++ ' response with body: {' ++ payload ++ '}']"/>
</flow>
----

Without the explicit header configuration, an autogenerated `Host: somehost.com:8081` would be sent.

== Troubleshoot HTTP Encoding

When there is no available information about the size of the data to send, the HTTP Connector sends requests and responses with the `Transfer-Encoding: chunked` encoding. This behavior is common when working with streamed data to obtain better performance.

Occasionally, HTTP clients and servers are not prepared to receive such data and fail.

Such failures should be reported to the server or client owners. As a workaround for the issue, modify the *Listener* and *Request* operations by returning `Content-Length` encoded bodies.

The following example shows the HTTP *Listener* operation configured with `responseStreamingMode` `NEVER`, which indicates to use `Content-Length` encoding:

[source,xml,linenums]
----
<flow name="main-contact-read">
  <http:listener path="account/{accountId}/main-contact" allowedMethods="GET" responseStreamingMode="NEVER" config-ref="HTTP_Listener_config"/>
  <!-- fetch main contact for accountId -->
</flow>
----

The following example shows the HTTP *Requester* operation configured with `requestStreamingMode` `NEVER`, which indicates to use `Content-Length` encoding:

[source,xml,linenums]
----
<flow name="connectingToFaultyServer">
  <http:request method="GET" url="http://somehost.com:8081/api/v3/someresource" requestStreamingMode="NEVER"/>
  <logger level="INFO"
   message="#['Received a ' ++ attributes.status code ++ ' response with body: {' ++ payload ++ '}']"/>
</flow>
----

== Understand Common Throws

Here is a list of common throws messages and how to interpret them.

* HTTP:BAD_REQUEST

 The server can not understand the request due to invalid syntax. For example, when some header size exceeds the maximum.

* HTTP:CLIENT_SECURITY

 Indicates a security type problem enforced by an external entity.

* HTTP:CONNECTIVITY

 A problem occurred and a connection could not be established.

* HTTP:FORBIDDEN

  The server refuses to give the requested resource because the client does not have access rights to the content.

* HTTP:INTERNAL_SERVER_ERROR

 The server encountered a situation which prevented from fulfilling the request.

* HTTP:METHOD_NOT_ALLOWED

 The request method is known by the server but the target resource does not support it.

* HTTP:NOT_ACCEPTABLE

 The server cannot produce a response matching the list of acceptable values defined in the request's proactive content negotiation headers.

* HTTP:NOT_FOUND

 The server could not find the requested resource.

* HTTP:PARSING

 [DEPRECATED] Kept for compatibility. The thrown message returned in a removed parsing mechanism.

* HTTP:RETRY_EXHAUSTED

 The maximum number of retries for the operation is reached.

* HTTP:SECURITY

 The requester authentication failed.

* HTTP:SERVICE_UNAVAILABLE

 The server is unable to manage the request because it is down for maintenance or overloaded.

* HTTP:TIMEOUT

 The request sent by an http:requester timed out.

* HTTP:TOO_MANY_REQUESTS

 Too many request were sent in a given amount of time.

* HTTP:UNAUTHORIZED

 Authentication failed or has not yet been provided to get the requested response.

* HTTP:UNSUPPORTED_MEDIA_TYPE

 The server does not support the media format of the requested data.

* HTTP:BAD_GATEWAY

 The server acting as a gateway or proxy to manage the request got an invalid response.

* HTTP:GATEWAY_TIMEOUT

 The server acting as a gateway or proxy to manage the request did not receive a response in time.

* HTTP:BASIC_AUTHENTICATION

 HTTP Request operation requires basic authentication to send requests to the service, or the provided credentials are incorrect.

== See Also

* xref:http-listener-ref.adoc[HTTP Listener Configuration Reference]
* xref:http-request-ref.adoc[HTTP Request Configuration Reference]
