= HTTP Connector Troubleshooting Guide
:keywords: anypoint studio, esb, connectors, http, https, http headers, troubleshooting, rest, raml
:page-aliases: connectors::http/http-troubleshooting.adoc

== Wire Logging

The best way to troubleshoot HTTP issues is to enable wire logging. When wire logging is set up, the actual raw HTTP requests and response flowing through are logged.

Once logs are collected, they can be used to validate the current configuration or to compare the HTTP connector behavior to other clients and servers.

To enable HTTP wire logging, the following entry should be added to your artifact's log configuration (`log4j2.xml`):

[source,xml,linenums]
----
<?xml version="1.0" encoding="utf-8"?>
<Configuration>
    ...
    <Loggers>
        ...
        <!-- Http Logger shows wire traffic on DEBUG. -->
        <AsyncLogger name="org.mule.service.http.impl.service.HttpMessageLogger" level="DEBUG"/>
        ...
    </Loggers>
</Configuration>
----

== TLS Debug

When SSL failures are seen or suspected because HTTPS is being used, usually connections cannot even be established and wire logging is not helpful.
In this situations, SSL debug should be enabled which will log all SSL related data, such as connection attempts, handshakes, negotiations and so on.

Logs can then be examined to determine whether the correct certificates are in place, a cipher or protocol mismatch is occurring or why connectivity is failing.

To enable TLS debugging, the following system property needs to be configured: `-Djavax.net.debug=ssl`.

== Common Issues

These are some of the common issues seen while working with HTTP.

=== Host Header Misuse

The `Host` header is used by HTTP clients to indicate the host and port number of the resource being requested. It is a mandatory header which the HTTP request
autogenerates considering the configured host and port.

Often, servers do not account for the port information because it's optional, and fail when receiving a request that has both the host and port data.

Such failures should be reported to the server owners. While a fix is provided, the HTTP request operation can be modified to workaround the issue by providing an explicit `Host` header without the port section.

For example, the following configuration will send a `Host: somehost.com` header.

[source,xml,linenums]
----
<flow name="connectingToFaultyServer">
  <http:request method="GET" url="http://somehost.com:8081/api/v3/someresource">
    <http:headers>
      #[{"Host" : "somehost.com"}]
    </http:headers>
  </http:request>
  <logger level="INFO"
   message="#['Received a ' ++ attributes.status code ++ ' response with body: {' ++ payload ++ '}']"/>
</flow>
----

Without the explicit header configuration, an autogenerated `Host: somehost.com:8081` would be sent.

=== HTTP Encoding Support

The HTTP connector sends requests and responses with `Transfer-Encoding: chunked` encoding when there's no available information about the size of the data to send. This is very common when working with streamed data to obtain better performance.

Occasionally, HTTP clients and servers are not prepared to receive such data and fail.

Such failures should be reported to the server or client owners. While a fix is provided, both the HTTP listener and request can be modified to workaround the issue by always returning `Content-Length` encoded bodies.

In the following example, an HTTP listener is configured with `responseStreamingMode` `NEVER`, which indicates `Content-Length` encoding should always be used.

[source,xml,linenums]
----
<flow name="main-contact-read">
  <http:listener path="account/{accountId}/main-contact" allowedMethods="GET" responseStreamingMode="NEVER" config-ref="HTTP_Listener_config"/>
  <!-- fetch main contact for accountId -->
</flow>
----

In this example, an HTTP request operation is configured `requestStreamingMode` `NEVER`, which indicates `Content-Length` encoding should always be used.

[source,xml,linenums]
----
<flow name="connectingToFaultyServer">
  <http:request method="GET" url="http://somehost.com:8081/api/v3/someresource" requestStreamingMode="NEVER"/>
  <logger level="INFO"
   message="#['Received a ' ++ attributes.status code ++ ' response with body: {' ++ payload ++ '}']"/>
</flow>
----

== Understand Common Throws

Here is a list of common throws messages and how to interpret them.

* HTTP:BAD_REQUEST

 The server can not understand the request due to invalid syntax. For example, when some header size exceeds the maximum.

* HTTP:CLIENT_SECURITY

 Indicates a security type problem enforced by an external entity.

* HTTP:CONNECTIVITY

 Indicates that a problem occurred and a connection could not be established.

* HTTP:FORBIDDEN

  The server refuses to give the requested resource because the client does not have access rights to the content.

* HTTP:INTERNAL_SERVER_ERROR

 The server encountered a situation which prevented from fulfilling the request.

* HTTP:METHOD_NOT_ALLOWED

 The request method is known by the server but the target resource does not support it.

* HTTP:NOT_ACCEPTABLE

 The server cannot produce a response matching the list of acceptable values defined in the request's proactive content negotiation headers.

* HTTP:NOT_FOUND

 The server could not find the requested resource.

* HTTP:PARSING

 [DEPRECATED] Kept for compatibility. It was used in a removed parsing mechanism.

* HTTP:RETRY_EXHAUSTED

 The maximum number of retries for the operation is reached.

* HTTP:SECURITY

 The requester authentication failed.

* HTTP:SERVICE_UNAVAILABLE

 The server is unable to manage the request because it is down for maintenance or overloaded.

* HTTP:TIMEOUT

 The request sent by an http:requester timed out.

* HTTP:TOO_MANY_REQUESTS

 Too many request were sent in a given amount of time.

* HTTP:UNAUTHORIZED

 Authentication failed or has not yet been provided to get the requested response.

* HTTP:UNSUPPORTED_MEDIA_TYPE

 The server does not support the media format of the requested data.

* HTTP:BAD_GATEWAY

 The server acting as a gateway or proxy to manage the request got an invalid response.

* HTTP:GATEWAY_TIMEOUT

 The server acting as a gateway or proxy to manage the request did not receive a response in time.

* HTTP:BASIC_AUTHENTICATION

 HTTP Request operation requires basic authentication to send requests to the service, or the provided credentials are incorrect.

== See Also

* xref:http-listener-ref.adoc[HTTP Listener Configuration Reference]
* xref:http-request-ref.adoc[HTTP Request Configuration Reference]
