= Anypoint Custom Metrics Connector - Mule 4
:page-aliases: connectors::metrics/custom-metrics-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Custom Metrics Connector enables you to send operational and business metric values that you define from an application to Anypoint Monitoring, where the metrics can be visualized in real time using custom dashboards.

Once the metrics are in a custom dashboard, you can filter and group the metrics along the included dimensions. You can include multiple custom and built-in metrics in a single dashboard visualization.

[NOTE]
====
To use the Anypoint Custom Metrics connector, you must have a Titanium subscription. +
This feature is currently supported only for hybrid applications.
====

For an example of how to use the Anypoint Custom Metrics connector in an end-to-end flow, see xref:monitoring::anypoint-custom-metrics-connector.adoc[Custom Metrics].

== See Also

* xref:custom-metrics-connector-reference.adoc[Custom Metrics Connector Reference]
* xref:release-notes::monitoring/anypoint-monitoring-release-notes.adoc[Anypoint Monitoring Release Notes]
* xref:monitoring::anypoint-custom-metrics-connector.adoc[Custom Metrics]
