= Upgrading and Migrating IBM MQ Connector

Upgrade Anypoint Connector for IBM MQ (IBM MQ Connector) from version 1.x to version 2.0 to run on Java 17 and the Jakarta Messaging (`jakarta.jms`) namespace.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|1.x |2.0.x
|===

== Changes in This Release

This release contains breaking changes:

* Changed the minimum Mule runtime engine (Mule) version to 4.10.2, upgraded from 4.4.0.
* Required Java 17 for both compilation and runtime, upgraded from Java 8.
* Migrated from the `javax.jms` namespace to the `jakarta.jms` namespace.
* Changed the recommended IBM MQ client library from `com.ibm.mq.allclient` to `com.ibm.mq.jakarta.client` 9.4.5.1.
* Renamed the connection element from `<ibm-mq:connection>` to `<ibm-mq:ibm-mq-connection>`, which appears as *IBM MQ Connection* in the *Connection* field in Studio.
* Removed the `enableXa` attribute and replaced it with the `<ibm-mq:ibm-mq-xa-connection>` element, which appears as *IBM MQ XA Connection* in the *Connection* field in Studio.

== Requirements

Ensure that you meet these requirements before you perform the upgrade.

=== Mule Requirements

* The minimum Mule version required is 4.10.2, which supports both Java 17 and Jakarta Messaging classloading.
* Mule versions 4.4, 4.6, and 4.9 are not supported. Applications on these versions must remain on IBM MQ Connector 1.x.

=== Java Runtime Requirements

* The minimum and only supported JDK version is 17.
* Java 8 and Java 11 are not supported.

=== Development Environment

* Anypoint Studio 7.21 or later, which includes Mule 4.10.2.
* Maven configured with a JDK 17 toolchain.

== Considerations

Before you perform the upgrade, be aware of these considerations:

* Upgrade the Mule runtime and JDK in all environments before you upgrade the connector. The connector doesn't load on earlier runtimes.
* Applications that specify the `enableXa` attribute fail to parse at startup. Update these configurations before you deploy.
* Applications that use the `<ibm-mq:connection>` element fail to parse at startup. Update these configurations before you deploy.
* Retest all connections and XA transaction flows after you upgrade.

== Upgrade the Connector in Anypoint Code Builder

Follow these steps to perform the upgrade:

. In *Explorer*, right-click the configuration XML file in your integration project, and select *Project Properties*.
. In *Project Properties*, select *Connectors*.
. Select the latest version for the connector, and click *Apply*.

== Upgrade the Connector in Studio

Follow these steps to perform the upgrade:

. In Anypoint Studio, open your existing Mule project.
. In *Mule Palette*, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `ibm mq` in the search field.
. In *Available modules*, select *IBM MQ Connector* and click *Add*.
. Click *Finish*.
. Verify that the IBM MQ Connector `<dependency>` version is `2.0.0` in the `pom.xml` file in the Mule project:
+
[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-ibm-mq-connector</artifactId>
  <version>2.0.0</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

Studio upgrades the connector automatically, but configuration changes are required.

== Post Upgrade Steps

After you install the latest version of the connector, follow these steps to complete the upgrade.

=== Update the IBM MQ Client Library

Replace the `com.ibm.mq.allclient` library with the Jakarta Messaging client library:

Before (version 1.x):

[source,xml,linenums]
----
<dependency>
    <groupId>com.ibm.mq</groupId>
    <artifactId>com.ibm.mq.allclient</artifactId>
    <version>9.4.4.0</version>
</dependency>
----

After (version 2.0):

[source,xml,linenums]
----
<dependency>
    <groupId>com.ibm.mq</groupId>
    <artifactId>com.ibm.mq.jakarta.client</artifactId>
    <version>9.4.5.1</version>
</dependency>
----

If you keep the `com.ibm.mq.allclient` library, the connector wraps it to expose a `jakarta.jms` connection factory. This backward compatibility support is best-effort only. For details and limitations, see xref:index.adoc#javax-client-library[Support for the Legacy javax.jms Client Library].

=== Rename the Connection Element

The connection element is renamed from `<ibm-mq:connection>` to `<ibm-mq:ibm-mq-connection>`. In Studio, this connection type appears as *IBM MQ Connection* in the *Connection* field of the global element configuration:

Before (version 1.x):

[source,xml,linenums]
----
<ibm-mq:config name="IBM_MQ_Config">
  <ibm-mq:connection>
    <ibm-mq:connection-mode>
      <ibm-mq:client host="0.0.0.0" port="1414" queueManager="QM1" channel="DEV.ADMIN.SVRCONN"/>
    </ibm-mq:connection-mode>
  </ibm-mq:connection>
</ibm-mq:config>
----

After (version 2.0):

[source,xml,linenums]
----
<ibm-mq:config name="IBM_MQ_Config">
  <ibm-mq:ibm-mq-connection>
    <ibm-mq:connection-mode>
      <ibm-mq:client host="0.0.0.0" port="1414" queueManager="QM1" channel="DEV.ADMIN.SVRCONN"/>
    </ibm-mq:connection-mode>
  </ibm-mq:ibm-mq-connection>
</ibm-mq:config>
----

=== Replace the enableXa Attribute

The `enableXa` attribute is removed. To use XA transactions, use the `<ibm-mq:ibm-mq-xa-connection>` element instead. In Studio, select *IBM MQ XA Connection* in the *Connection* field of the global element configuration:

Before (version 1.x):

[source,xml,linenums]
----
<ibm-mq:config name="IBM_MQ_Config">
  <ibm-mq:connection enableXa="true">
    <ibm-mq:connection-mode>
      <ibm-mq:client host="0.0.0.0" queueManager="QM1"/>
    </ibm-mq:connection-mode>
  </ibm-mq:connection>
</ibm-mq:config>
----

After (version 2.0):

[source,xml,linenums]
----
<ibm-mq:config name="IBM_MQ_Config">
  <ibm-mq:ibm-mq-xa-connection>
    <ibm-mq:connection-mode>
      <ibm-mq:client host="0.0.0.0" queueManager="QM1"/>
    </ibm-mq:connection-mode>
  </ibm-mq:ibm-mq-xa-connection>
</ibm-mq:config>
----

Both connection types accept the same connection parameters. The *IBM MQ XA Connection* type adds the *Min Pool Size* (`minPoolSize`), *Max Pool Size* (`maxPoolSize`), and *Max Idle Seconds* (`maxIdleSeconds`) XA connection pool parameters, which default to `4`, `32`, and `60`. For details, see xref:ibm-mq-xml-ref.adoc#config_xa_connection[IBM MQ XA Connection].

=== Update the Runtime Environment

. Make sure all environments run on Mule 4.10.2 or later.
. Make sure all environments use JDK 17.
. Update the Maven build configuration to use a JDK 17 toolchain.

=== Verify the Upgrade

After you install the latest version of the connector, verify the upgrade:

. Verify that the `pom.xml` file shows version 2.0.0 of IBM MQ Connector.
. Verify that no `enableXa` attributes and no `<ibm-mq:connection>` elements remain in your configurations.
. Use the *Test Connection* feature to validate connectivity.
. Verify that the application log doesn't contain a warning about the legacy `javax.jms` client library.
. Run your existing tests, including XA transaction flows, to confirm that functionality is preserved.

== Troubleshooting

If you encounter issues, perform these troubleshooting steps.

=== Troubleshoot Startup Parse Failures

If the application fails to start with an unknown-attribute or unknown-element error, follow these steps:

. Replace the `enableXa="true"` attribute with the `<ibm-mq:ibm-mq-xa-connection>` element.
. Rename `<ibm-mq:connection>` elements to `<ibm-mq:ibm-mq-connection>`.

=== Troubleshoot Runtime Compatibility Issues

If the application fails to deploy with a JDK or Mule runtime error, follow these steps:

. Upgrade to Mule 4.10.2 or later. Earlier versions can't load this connector version.
. Upgrade to JDK 17.

=== Troubleshoot Connection Failures That Report shim:javax-fallback

If connection failure messages end with `[shim:javax-fallback]`, the connector is using the legacy `com.ibm.mq.allclient` library through the backward compatibility wrapper. Replace that library with `com.ibm.mq.jakarta.client` 9.4.5.1.

=== Revert the Upgrade

If you need to revert to a previous version of IBM MQ Connector, in the project's `pom.xml` file, change the `mule-ibm-mq-connector` dependency version from `2.0.0` to the version you used previously, and restore the connection elements and the IBM MQ client library to their 1.x form.

[IMPORTANT]
Reverting requires an environment that is compatible with version 1.x requirements.

== See Also

* xref:index.adoc[IBM MQ Connector Overview]
* xref:ibm-mq-transactions.adoc[Handling Transactions in IBM MQ]
* xref:ibm-mq-xml-ref.adoc[IBM MQ Connector Reference]
* https://help.salesforce.com[Salesforce Help]
