= Stripe Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Stripe (Stripe Connector) gives you access to the Stripe platform. This connector exposes operations provided by the Stripe API. 

For compatibility information and fixed issues, see the Stripe Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Stripe API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the Stripe target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

* Sales
** A company wants to organize all of their sales for the accounting team, so every time a new sale is completed in Stripe, it is added as a new row in Google Sheets.
** The sales team wants to connect Salesforce with Stripe to keep track of potential upsell opportunities, so every time there is a new Stripe charge, invoice, order, or refund, a Salesforce opportunity is created. 
** A marketing team uses Marketo as their main marketing tool, so every time there is a purchase from a new customer in Stripe, a new lead is added for this customer in Marketo.
** A company uses Zendesk to assign tickets for a variety of tasks based on customer requests. +
Based on a Zendesk ticket, a customer, subscription, product, or invoice is automatically created or updated in Stripe.
* Communication
** A company wants to be notified in Gmail or Slack whenever there is a new Stripe event, so every time there is a new Stripe event, customer, order, refund, invoice, or charge, a custom message is sent to Slack or a custom email is sent to Gmail.
** A company wants to notify previous customers of a new coupon they can use to buy some of their items, so every time a new coupon is created, they send an email to a set of customers to encourage them to buy certain items.
* Data 
** The sales department wants to visualize data related to customers, subscriptions, orders, charges, refunds and events. +
To do this, they create a spreadsheet in Google Sheets that updates a row every time one of these events happens in Stripe. Every quarter, they create a CSV file from this spreadsheet and use it as a data source for Tableau. They can then publish this data source to Tableau and visualize it there.


== Authentication Types

Stripe Connector connections use the Basic authentication type, which uses a username and password to connect to Stripe. 

For information about configuring the Basic authentication type, see xref:stripe-connector-studio.adoc[Use Studio to Configure Stripe Connector].

== Next Step

After you complete the prerequisites, you are ready to create your own app and configure the connector using xref:stripe-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
