= SAP S/4HANA SOAP Connector 2.6 - Mule 4
:page-aliases: connectors::sap/sap-s4hana-soap-connector.adoc

Anypoint Connector (SAP S/4HANA SOAP Connector) provides full support for the SOAP APIs exposed by SAP S/4HANA Cloud ERP, and starting with version 2.1, also provides support for SAP S/4HANA on-premise ERP. This connector enables you to automatically discover SOAP services enabled on your SAP S/4HANA instance and to invoke the SOAP service and associated operations.

For software requirements and compatibility
information, see the xref:release-notes::connector/sap-s4-hana-soap-cloud-connector-release-notes-mule-4.adoc[SAP S/4HANA SOAP Connector Release Notes].

== Before You Begin

Before you create an app and use this connector, you must:

* Have a developer account or other valid SAP S/4HANA instance.
* Have a MuleSoft Enterprise license.
* Enable discovery service in your SAP S/4HANA instance.
* Have a communication user that is assigned to the corresponding communication arrangements for the desired APIs.
* Be familiar with:
** SAP S/4HANA SOAP
** Mule runtime engine (Mule)
** Anypoint Connectors
** Anypoint Studio essentials

== Common Use Cases For the Connector

Send an XML request to SAP S/4HANA's SOAP API and print a response.

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
you can use as a starting point for your app, as well as examples that illustrate a complete solution.

== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app with xref:sap-s4hana-soap-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:release-notes::connector/sap-s4-hana-soap-cloud-connector-release-notes-mule-4.adoc[SAP S/4HANA SOAP Connector Release Notes]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-sap-s4hana-soap-cloud-connector/[SAP S/4HANA SOAP Connector on Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
