= AS2 Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Premium

Version 5.0.0

Mule runtime engine (Mule) supports the AS2 protocol through Anypoint Connector for AS2 (AS2 Connector).
The AS2 Connector enables trading partners to transmit and receive AS2 messages with EDI-X12, EDIFACT, XML, or binary payloads.

* Send messages, signed or unsigned, over HTTP or HTTPS, following the AS2 protocol

* Receive messages, also over HTTP or HTTPS, following the AS2 protocol

* Receive asynchronous MDN for the message sent


== About Connectors

Anypoint Connectors are Mule runtime engine extensions that enable you to connect to APIs and resources on external systems, such as X12 and RosettaNet.

== Prerequisites

Familiarity with AS2, Mule, Anypoint Connectors, and Anypoint Studio.

== Add a POM File Dependency
The `pom.xml` Apache Maven file generated by Anypoint Studio contains dependencies for
a Mule app. When you code a Mule app manually, include this XML snippet in
your `pom.xml` file to enable access to the connector. The Mule runtime engine
translates the `RELEASE` dependency keyword to the current version.

[source,xml,linenums]
----
<dependency>
   <groupId>com.mulesoft.connectors</groupId>
   <artifactId>mule-as2-connector</artifactId>
   <version>5.0.0</version>
   <classifier>mule-plugin</classifier>
</dependency>
----
To obtain the most up-to-date `pom.xml` file information, access the
connector in https://www.mulesoft.com/exchange/[Anypoint Exchange]
and click *Dependency Snippets*.

== Add a Namespace for the Connector

Paste the following code inside the `mule` tag of the header
of your configuration XML, making sure to include `current` in the schema path:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/as2-mule4
http://www.mulesoft.org/schema/mule/as2/current/mule-as2-mule4.xsd
----

[source,xml,linenums]
<mule xmlns:http="http://www.mulesoft.org/schema/mule/http"
xmlns:as2="http://www.mulesoft.org/schema/mule/as2-mule4"
xmlns="http://www.mulesoft.org/schema/mule/core"
xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:spring="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	    xsi:schemaLocation="http://www.springframework.org/schema/beans
	    http://www.springframework.org/schema/beans/spring-beans-current.xsd
        http://www.mulesoft.org/schema/mule/core
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/as2-mule4
	http://www.mulesoft.org/schema/mule/as2/current/mule-as2-mule4.xsd">
      <!-- put your global configuration elements and flows here -->
</mule>


== Common Operations

* Send with sync MDN
Sends a message through HTTP or HTTPS using the AS2 protocol requesting the partner for a synchronous MDN (receipt).
* Send with async MDN
Sends a message through HTTP or HTTPS using the AS2 protocol requesting the partner for an asynchronous MDN (receipt).
* Listener
Source that receives messages via HTTP or HTTPS using the AS2 protocol.
* MDN Listener
Source that receives asynchronous MDN receipts via HTTP or HTTPS using the AS2 protocol.

== Example: Configure a Send AS2 Message

. Place the connector in your flow as applicable for your use case.
. To send an AS2 message with request for MDN in your Mule application, create a global `AS2 Connector Send config` element for use by the AS2 send operations.
The `AS2 Connector Send config`  provides the following global configuration parameters:
+
[%header%autowidth.spread]
|===
|Key| Description
|Self config - AS2 Partner Name| Sender’s AS2 system identifier. Used for AS2-From and AS2-To headers.
|Self config - x509 alias| Sender’s certificate and/or private key alias in the keystore. Required if using signing or encryption.
|Self config - Email| Sender partner’s email.
|Partner config - AS2 ID| Receiver’s AS2 system identifier. Used for AS2-From and AS2-To headers.
|Partner config - x509 alias| Receiver’s Certificate and/or private key alias in the keystore. Required if using signing or encryption.
|Partner config - Email| Receiver partner’s email.
|Requester config - Subject| Free-form text for MIME subject header. Can include references to self or partner `simpleName` values along with the message `fileName`: for example, sending file example.txt to partner via AS2.
|Requester config - MDN MIC Signature Algorithm| The algorithm with which MIC is calculated for the MDN signature. The message is `UNSIGNED` by default.
|Requester config - Request a receipt| Option to request a receipt from the partner. `SIGNED_OPTIONAL` by default.
|Requester config - Request delivery URL| Asynchronous receipt delivery URL that points to the MDN listener endpoint.
|Requester config - Encryption Algorithm| The encryption algorithm for encrypting the message. `UNENCRYPTED` by default.
|Requester config - MIC Signature Algorithm| The algorithm with which MIC is calculated for the message signature.  The message is `UNSIGNED` by default.
|Requester config - Content transfer encoding| The content transfer encoding. `BINARY` by default.
|Requester config - Compression type| ZLIB is the only supported compression and decompression type. `NONE` by default.
|Keystore config - Keystore Path| The path of the keystore where certificates and keys are provided.
|Keystore config - Keystore Password| The password for the keystore.
|Keystore config - Private key Password| If the private key requires a password.
|===
+
. Configure a connection to the partner AS2 endpoint by providing the `Partner Base URL`.
. If you want to configure other connection details (such as TLS, proxy, timeouts) you can do that now.
. Send the file or message by either using `Send with sync mdn` or `Send with async mdn`:

** The payload is the message content to be sent.

** Filename is the file name of the message being sent.

** Boolean to configure if the process should fail or if the receipt status is not processed.

. If you choose to request an asynchronous receipt, you need to configure `MDN Listener`.

=== Configure an MDN Listener

Place the connector’s `MDN Listener` as a source in your flow as applicable for your use case and reference the global config defined here.

[%header%autowidth.spread]
|===
|Key| Description
|Self config - AS2 OID| Sender partner’s OID.
|Self config - x509 alias| Sender’s certificate and/or private key alias in the keystore.
|Self config - Email| Sender partner’s email.
|Partner config - AS2 ID| Receiver partner’s OID.
|Partner config - x509 alias| Receiver’s Certificate and/or private key alias in the keystore.
|Partner config - Email| Receiver partner’s email.
|HTTP Listener config| Reference to HTTP Listener global config.
|Keystore config - Keystore Path| The path of the keystore where certificates and keys are provided.
|Keystore config - Keystore Password| The password for the keystore.
|Keystore config - Private key Password| If the private key requires a password.
|===

=== Example: Configure an AS2 Listener for Receiving a Message

. Place the connector’s `AS2 Listener` as a source in your flow as applicable for your use case and reference the global config as defined here.
+
[%header%autowidth.spread]
|===
|Key| Description
|Self config - AS2 OID| Receiver partner’s OID.
|Self config - x509 alias| Receiver alias as defined in the keystore file.
|Self config - Email| Receiver partner’s email.
|Partner config - AS2 ID| Sender partner’s OID.
|Partner config - x509 alias| Sender alias as defined in the keystore.
|Partner config - Email| Sender partner’s email.
|HTTP Listener config| Reference to HTTP Listener global config.
|Keystore config - Keystore Path| The path of the keystore where certificates and keys are provided.
|Keystore config - Keystore Password| The password for the keystore.
|Keystore config - Private key Password| If the private key requires a password.
|===
+
. Configure a connection to the partner if the MDN request is to be sent asynchronously.
. If you want to configure other connection details (such as TLS, proxy, timeouts) do that now.

== Runtime Configuration

The AS2 Connector reads data using repeatable streams. Data is read into memory until a configurable threshold is reached, at which point the data is written to disk.
The default threshold for writing to disk is 64 KB. You can change this by using the system property `com.mulesoft.connectors.as2.CachedOutputStream.Threshold`.
This property requires an integer value:

** A positive value defines the maximum amount of data to read into memory in KB.

** A zero value means that all data is written directly to disk.

** A value of -1 means that the data is never written to disk, and is stored into memory.

By default, the data is written to temporary files in the directory set by `java.io.tmpdir`.
To change the directory, set the System property `com.mulesoft.connectors.as2.CachedOutputStream.OutputDirectory`.

== Considerations when Migrating from the AS2 connector 4.x

The AS2 version 5 connector requires the `Async MDN` to be handled as a separate flow. The retry of AS2 Message Send is not automatic. The application has to handle the retry upon failure in an MDN or upon failure to receive an MDN.

Version 5 enables you to reuse the application HTTP listener configuration.


== See Also

* See https://forums.mulesoft.com/search.html?q=AS2+connector[MuleSoft Forum for this connector]
