= AS2 Connector 6.0.0 - Upgrade and Migrate - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

== Supported Upgrade Paths

This a direct upgrade from the AS2 connector 5.x to 6.0.0.

== Changes in This Release

* Digitally signed copies of outgoing and received messages as well as their corresponding receipts can now be saved for Non-repudiation purposes, if configured and enabled on operations and sources of the AS2 connector. A new Mule source ‘Non repudiation listener’ is added to support this feature, which must be user configured to persist the Non Repudiation information provided by any of the AS2 Connector operations and sources via a persistance strategy defined by the user.

* Some attributes object fields have been renamed (and deprecated fields removed) as outlined in Upgrade Steps below.

== Requirements and Limitations

You should be aware of some requirements and limitations before you upgrade to the latest version.

=== Requirements

Ensure that you meet the following requirements before you migrate.

Mule 4.3.0 or later

Java 8

== Upgrade Steps

Follow these steps to perform the upgrade to AS2 version 6.0.0:

. Download the AS2 connector 6.0.0 from Exchange and place appropriate source/operation in the flow that is being upgraded.
. No changes to the way AS2 Listener and AS2 MDN Listener are configured and/or used.
. For `Send with Sync MDN` and `Send with Async MDN` operations, an attribute object of type `com.mulesoft.connector.as2.api.AS2MdnAttributes` has following changes done in v6.0.0. Please ensure mule flows which are using these attributes are amended accordingly. Note: The field `com.mulesoft.connector.as2.api.AS2SendAttributes.as2MdnAttributes` is of type `com.mulesoft.connector.as2.api.AS2MdnAttributes`)

=== AS2 MDN attributes 
[%header%autowidth.spread]
|===
|v5.x Field Name| v6.0.0 Field Name | v5.x Type | v6.0.0 Type
|dispositionContent |dispositionContent | MultiMap<String, String> | MultiMap<String List<String>>
|mdnMic | receivedContentMic | String | String
|mdnProcessed | processed | boolean | boolean
|originalAS2MessageId | originalMessageId | String | String
|reportText | Field Removed | String | Field Removed
|===

=== Post Upgrade Steps

After you perform the previous steps, follow these steps to complete the upgrade:

. Verify that the connector is working by making sure there are no exceptions on startup and test it against your AS2 partner.

. Notify your Partners of any new URL (port) configurations that corresponds to the HTTP listener you are using.

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
