= Troubleshooting Amazon SQS Connector 5.11 - Mule 4

To troubleshoot Anypoint Connector for Amazon SQS Connector, familiarize yourself with the information about interpreting commonly thrown exception messages. 

==Understand Commonly Thrown Expectations

Here is a list of commonly thrown exception messages and how to interpret them:

* SQS:ACCESS_DENIED

 The user does not have permission to execute this operation. 

* SQS:CONNECTIVITY

 The connection to the Amazon SQS server was interrupted.

* SQS:INTERNAL_FAILURE
    
 The request failed because of an unknown error, exception or failure. 

* SQS:INVALID_CREDENTIALS

 Authentication against the SFTP server failed due to invalid credentials. 

* SQS:INVALID_DATA

 <description>

* SQS:OPT_IN_REQUIRED

 <description> 

* SQS:REQUEST_EXPERIED

 <description>

* SQS:RETRY_EXHAUSTED

 <description>

* SQS:SERVICE_UNAVAILABLE

 The server is experiencing a temporary failure.

* SQS:THROTTLING_EXPECTION

 The request failed due to request throttling.



== Understand Specific Errors

* SQS:MESSAGE_NOT_IN_FLIGHT

 The specified queue recieved a PurgeQueue request within the last 60 seconds. 

* SQS:OVER_LIMIT

 The attempted action exceeds a limit. 
    <description>

* SQS:PURGE_QUEUE_IN_PROGRESS

 The specified queue recieved a PurgeQueue request within the last 60 seconds. 

* SQS:QUEUE_ALREADY_EXISTS

 There is a queue with this name already and the request includes different attributes from the existing queue with this name.

* SQS:QUEUE_DELETED_RECENTLY

 A queue with the same name was deleted within the last 60 seconds. 


== Understand Large Payload Errors

* SQS:MESSAGE_SIZE_THRESHOLD_OUT_OF_RANGE

 <description>

* SQS:PARAMETER_OUT_RANGE

 <description>

* SQS:S3_BUCKET_ACCESS_DENIED

 <description>

* SQS:S3_BUCKET_NOT_FOUND

 <description>





 