= Troubleshooting Amazon SQS Connector 5.11 - Mule 4

To troubleshoot Anypoint Connector for Amazon SQS (Amazon SQS Connector), become familiar with the information about interpreting commonly thrown exception messages.

include::connectors::partial$ssl-logs.adoc[]

include::connectors::partial$verbose-exception-logs.adoc[]

include::connectors::partial$verbose-logs-org.adoc[]

== Troubleshoot AWS STS Regionalized Endpoints

In AWS SDK v2, the endpoint that the STS client of the `AssumeRoleConnectionProvider` uses to get session tokens is now regionalized instead of global. See the https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html[AWS STS Regionalized endpoints] documentation for details.
As explained in the https://docs.aws.amazon.com/general/latest/gr/sts.html[AWS Security Token Service endpoints and quotas] documentation, regionalized endpoints shouldn’t cause changes in the connector’s functionality.
AWS recommends using Regional STS endpoints to reduce latency, build in redundancy, and increase session token validation.

If you encounter any issues as a result of the change in endpoints to regionalized, you can force Amazon SQS Connector to use the global endpoint by specifying the URL endpoint `+https://sts.amazonaws.com+` in the *Custom STS Endpoint* field located in the *Advanced* tab of the *Global Elements* properties configuration window of the connector.

== Understand Commonly Thrown Exceptions

Here is a list of commonly thrown exception messages and how to interpret them:

* SQS:ACCESS_DENIED

 The user does not have permission to execute this operation.

* SQS:CONNECTIVITY

 The connection to the Amazon SQS server is interrupted.

* SQS:INTERNAL_FAILURE

 The request fails due to an unknown error, exception, or failure.

* SQS:INVALID_CREDENTIALS

 Authentication against the Amazon SQS server fails due to invalid credentials.

* SQS:INVALID_DATA

 The test connection cannot be performed because the Test Queue ARN parameter is not set.

* SQS:MESSAGE_NOT_IN_FLIGHT

 The specified message is not in flight.

* SQS:MESSAGE_SIZE_THRESHOLD_OUT_OF_RANGE

 The message threshold size is not between 0 and 256 KB.

* SQS:OPT_IN_REQUIRED

 The AWS access key ID requires a subscription for the service.

* SQS:OVER_LIMIT

 The attempted action exceeds a limit, for example, if the Recieve Messages source receives the maximum number of inflight messages or if the Add Permission operation reaches the maximum number of permissions for the queue.

* SQS:PARAMETER_OUT_RANGE

 The value is not within the specified range.

* SQS:PURGE_QUEUE_IN_PROGRESS

 The specified queue receives a Purge Queue request within the last 60 seconds.

* SQS:QUEUE_ALREADY_EXISTS

 There is a queue with this name already and the request includes different attributes from the existing queue with this name.

* SQS:QUEUE_DELETED_RECENTLY

 A queue with the same name is deleted within the last 60 seconds.

* SQS:REQUEST_EXPIRED

 The request reaches the service more than 15 minutes after the request date stamp or the request expiration date, or the request date stamp is more than 15 minutes in the future.

* SQS:RETRY_EXHAUSTED

 The retries of a certain execution block are exhausted.

* SQS:S3_BUCKET_ACCESS_DENIED

 The server returns an AmazonSQSException with a 403 HTTP status code.

* SQS:S3_BUCKET_NOT_FOUND

 The server returns an AmazonSQSException with a 404 HTTP status code.

 * SQS:SERVICE_UNAVAILABLE

 The server is experiencing a temporary failure.

* SQS:THROTTLING_EXCEPTION

 The request fails due to request throttling.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:amazon-sqs-connector-reference.adoc[Amazon SQS Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
* https://issues.salesforce.com/[Known Issues]
