= Troubleshooting Amazon SQS Connector 5.11 - Mule 4

To troubleshoot Anypoint Connector for Amazon SQS Connector, familiarize yourself with the information about interpreting commonly thrown exception messages. 

==Understand Commonly Thrown Expectations

Here is a list of commonly thrown exception messages and how to interpret them:

* SQS:ACCESS_DENIED

 The user does not have permission to execute this operation. 

* SQS:CONNECTIVITY

 The connection to the Amazon SQS server was interrupted.

* SQS:INTERNAL_FAILURE
    
 The request failed due to an unknown error, exception, or failure.

* SQS:INVALID_CREDENTIALS

 Authentication against the SFTP server failed due to invalid credentials. 

* SQS:INVALID_DATA

 <description>

* SQS:OPT_IN_REQUIRED

 The AWS access key ID needs a subscription needs a subsription for the service.

* SQS:REQUEST_EXPERIED

 The request reached the service more than 15 minutes after the date stamp on the request, more than 15 minutes after the request expiration date, or the date stamp on the request is more than 15 minutes in the future.

* SQS:RETRY_EXHAUSTED

 <description>

* SQS:SERVICE_UNAVAILABLE

 The server is experiencing a temporary failure.

* SQS:THROTTLING_EXPECTION

 The request failed due to request throttling.



== Understand Specific Errors

* SQS:MESSAGE_NOT_IN_FLIGHT

 The specified queue recieved a PurgeQueue request within the last 60 seconds. 

* SQS:OVER_LIMIT

 The attempted action exceeds a limit. 
 This happens, for example, if the number of inflight messages is reached for RecieveMessage or if the queue reaches the maximum number of permissions for ADDPermission. 

* SQS:PURGE_QUEUE_IN_PROGRESS

 The specified queue recieved a PurgeQueue request within the last 60 seconds. 

* SQS:QUEUE_ALREADY_EXISTS

 There is a queue with this name already and the request includes different attributes from the existing queue with this name.

* SQS:QUEUE_DELETED_RECENTLY

 A queue with the same name was deleted within the last 60 seconds. 


== Understand Large Payload Errors

* SQS:MESSAGE_SIZE_THRESHOLD_OUT_OF_RANGE
//this isnt very helpful

 Validation error.

* SQS:PARAMETER_OUT_RANGE
// not very helpful

 Validation error.

* SQS:S3_BUCKET_ACCESS_DENIED

 AmazonSQSException is returned from the server with a 403 HTTP status code.

* SQS:S3_BUCKET_NOT_FOUND

 AmazonSQSException is returned from the server with a 404 HTTP status code.


==See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:amazon-sqs-connector-reference.adoc[Amazon SQS Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]


 