= Web Service Consumer Connector 1.9 - Mule 4


Anypoint Connector for Web Service Consumer (Web Service Consumer Connector) consumes a SOAP web service from a Mule app to acquire data from an external source. In many cases, you can use Anypoint Connector for Workday (Workday Connector) or Anypoint Connector for ServiceNow (ServiceNow Connector) to connect to a service provider, however, when no connector is available for a specific web service, the easiest way to consume the service is to use the Web Service Consumer Connector.

The main features of the connector include:

* Ability to consume DOC literal web services
* Use of SOAP multipart messages
* Use of SOAP headers
* Support for a DataSense for SOAP headers, SOAP body, and attachments
* Use of embedded DataWeave transformations inside the operation
* Support for a unified experience for SOAP with attachments and MTOM handling
* Custom HTTP configuration as a transport
* Support for Web Service Security (WS Security)

[NOTE]
Web Service Consumer Connector doesn't support RPC WSDLs (Remote procedure call Web Service Descripting Language).


== Before You Begin

To use this connector, you must be familiar with:

* SOAP and WSDLs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* DataWeave
* Creating a Mule app using Anypoint Studio

Before creating an app, you must have access to Anypoint Studio.


== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:web-service-consumer-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://anypoint.mulesoft.com/exchange/org.mule.connectors/mule-wsc-connector/[Web Service Consumer in Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
