= Aggregators Module Examples - Mule 4
:page-aliases: connectors::aggregator/aggregator-examples.adoc

To fully benefit from using Aggregators Module, see the following examples of configuring the module scopes, source, and fields:

* xref:aggregators-size-example.adoc[Configure Size-Based Aggregator Scope] +
Configure the *Size based aggregator* scope to aggregate elements until a predefined size number of elements completes the aggregation.
* xref:aggregators-time-example.adoc[Configure Time-Based Aggregator Scope] +
Configure the *Time based aggregator* scope to aggregate elements within a predefined time limit.
* xref:aggregators-group-example.adoc[Configure Group-Based Aggregator Scope] +
Configure the *Group based aggregator* scope to aggregate elements into groups by group ID.
* xref:aggregators-multiple-examples.adoc[Aggregators Module Multiple Examples Configuration] +
Configure the *Size based aggregator* and *Group based aggregator* scopes to aggregate elements and then process them in batch.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
