= Troubleshoot Aggregators Module - Mule 4

To troubleshoot Aggregators module, become familiar with the information about app logs, enabling verbose logging, and interpreting commonly thrown messages.

== Use the Latest Aggregators Module Version

To ensure that you use the latest patches, update the Aggregator module to the latest version. In the Apache Maven `pom.xml` file generated by Anypoint Studio replace `x.x.x` with the version that corresponds to the latest version:

[source,xml,linenums]
----
<dependency>
  <groupId>org.mule.modules</groupId>
  <artifactId>mule-aggregators-module</artifactId>
  <version>x.x.x</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

To obtain the most up-to-date `pom.xml` file information:

. Go to https://www.mulesoft.com/exchange/[Anypoint Exchange].
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for `aggregators`.
. Select the connector.
. Click *Dependency Snippets* near the upper right of the screen.


== Understand the Timeout Behavior in the Size-Based Aggregator

For the *Size based aggregator*, the *Timeout* field indicates the maximum time to wait for the aggregation to complete. If the timeout is reached before the total number of elements is equal to the value set in the *Max size* field, the aggregation is not considered complete. Take into account that you can use an *Aggregator listener* source to capture the aggregated values when giving timeout.

== Make Sure You Are Not in a Multiple Worker Setting

Aggregators don't work with multiple workers and a persistent Object Store because clustering is not available in CloudHub. For details on how workers can be shared or doubled to scale your application and provide high availability, see the xref:runtime-manager::cloudhub-fabric.adoc[CloudHub Fabric]documentation.

== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

For *Size based aggregator*:

* AGGREGATORS:AGGREGATOR_CONFIG

  The Max size or Timeout fields have invalid values, for example, Max size < 0.

* AGGREGATORS:OBJECT_STORE_ACCESS

  An error occurred during an attempt to access the object store used to store the aggregated values.

For *Time based aggregator*:

* AGGREGATORS:AGGREGATOR_CONFIG

  The Period or Max size fields have invalid values, for example, Period = 0.

* AGGREGATORS:OBJECT_STORE_ACCESS

  An error occurred during an attempt to access the object store used to store the aggregated values.

For *Time based aggregator*:

* AGGREGATORS:GROUP_COMPLETED

  An error occurred during an attempt to add a new element to an already completed group that was not yet evicted.

* AGGREGATORS:GROUP_TIMED_OUT

  An error occurred during an attempt to add a new element to a group that timed out, and the group was not yet evicted.

* AGGREGATORS:NO_GROUP_ID

  The expression that resolves to the group ID returns null.

* AGGREGATORS:NO_GROUP_SIZE

  The expression that resolves to the group size returns null.

* AGGREGATORS:AGGREGATOR_CONFIG

 The Group size or Timeout fields have invalid values, for example, &#96;groupSize&#96; < 0.

* AGGREGATORS:OBJECT_STORE_ACCESS

 An error occurred during an attempt to access the object store used to store the aggregated values.

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
* xref:aggregators-module-reference.adoc[Aggregators Module Reference]
