= Aggregators Module - Mule 4
:page-aliases: connectors::aggregator/aggregators-module.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Aggregators Module v1.0

Aggregators Module contains different types of aggregators capable of storing values and releasing them all together based on the configuration specified. An aggregator is a component used to collect those values until a condition is met, then execute a processor’s chain with the list of aggregated elements as the payload.

The basic aggregator configuration consists of the definition of the value to aggregate (extracted from the message through an expression evaluation), a condition that defines when the aggregation is considered complete, and a processor chain that executes once that condition is met.

An aggregator is a pass-through router, meaning that the same message that is processed by the aggregator is going to be processed by the components that follow it. The only modifications are the addition of some message attributes that provide information about the aggregation.

Release Notes: xref:release-notes::connector/aggregators-module-release-notes.adoc[Aggregators Module Release Notes] +
Exchange: https://www.mulesoft.com/exchange/org.mule.modules/mule-aggregators-module/[Aggregators Module]

== See Also

* xref:aggregators-module-reference.adoc[Aggregators Module Reference]
* xref:aggregators-examples.adoc[Aggregator Examples]
