= Aggregators Module 1.0 - Mule 4
:page-aliases: connectors::aggregator/aggregators-module.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

For compatibility information and fixed issues, see the Aggregator Module Release Notes.

Aggregators Module contains different types of aggregators capable of storing values and releasing them all together based on the configuration specified. An aggregator scope is a component used to collect those values until a condition is met, then execute a processor’s chain with the list of aggregated elements as the payload.

The basic aggregator configuration consists of the definition of the value to aggregate (extracted from the message through an expression evaluation), a condition that defines when the aggregation is considered complete, and a processor chain that executes once that condition is met.

Aggregators are pass-through routers. The same data that an aggregator scope receives is processed by the components that follow the aggregator scope. The only modifications are the propagation of variables in case any are set while executing any of the aggregation routes.

== Prerequisites

To use this module, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have to Anypoint Platform and Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
