= Dropbox Connector 1.0 - Mule 4



Anypoint Connector for Dropbox (Dropbox Connector) provides access to the Dropbox API.

For information about compatibility and fixed issues, refer to the Dropbox Connector Release Notes.

== Before You Begin

To use this connector, you must be familiar with:

* The Dropbox Connector’s API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Dropbox target resource
* Anypoint Platform
* Anypoint Studio version 7.3.5 or later


== Connection Types

Dropbox connections use the Oauth 2.0 authentication type, which delegates user authentication to the service hosting the user account.

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:dropbox-connector-reference.adoc[Dropbox Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
