= Salesforce CDP Connector 1.1 - Mule 4



Anypoint Connector for Salesforce CDP (Salesforce CDP Connector) provides Mule users with a quick and easy way to integrate with Salesforce CDP API endpoints. Users can automate data ingestion from third parties, query the CDP Data Lake, search and query customer profile information and calculated insights, and consume data action events to enrich the 360-degree view of their customers in their CDP instance.

Each API call uses a request/response pattern over an HTTPS connection. All required request headers, error handling, and HTTPS connection configurations are built into the connector.

For information about compatibility and fixed issues, refer to the Salesforce CDP Connector release notes.

== Before You Begin

To use this connector, you must be familiar with:

* https://developer.salesforce.com/docs/atlas.en-us.c360a_api.meta/c360a_api/c360a_api_salesforce_cdp_ingestion.htm[The Salesforce CDP Ingestion API]
* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Anypoint Connectors]
* xref:mule-runtime::index.adoc[Mule runtime engine] (Mule)
* xref:mule-runtime::global-elements.adoc[Elements and global elements] in a Mule flow
* xref:mule-runtime::mule-app-dev.adoc[How to create a Mule app using Anypoint Studio]

Before creating an app, you must have:

* <<set-up-the-ingestion-api, Set up the Ingestion API>>
* Credentials to access the Salesforce CDP target resource
* Anypoint Platform
* Anypoint Studio version 7.3.x or later

[[set-up-the-ingestion-api]]
== Set Up the Ingestion API

To use Salesforce CDP Connector, you must first set up the Ingestion API. For more information, refer to https://developer.salesforce.com/docs/atlas.en-us.c360a_api.meta/c360a_api/c360a_api_mulesoft.htm?_ga=2.167255478.925669352.1676304856-540573202.1655924724[Connect MuleSoft with Customer Data Platform]. 

After setting up the Ingestion API, refer to <<next-step>> to configure your connector.

== Common Use Cases For the Connector

These are some common use cases for Salesforce CDP Connector:

* Stream data via insert and delete object endpoints of the Ingestion API Connector
* Create a bulk job, upload job data, close or abort a job, get a job status, and delete a job as part of the Bulk Ingestion interaction pattern of the Ingestion API Connector
* Query CDP objects
* Query Salesforce CDP data lake across data model, lake, unified, and linked objects
* Query calculated insights with selected dimensions, selected measures, and optional filters
* Look up and search customer profile information
* Create webhooks as data action targets for data actions in CDP

For examples, see xref:salesforce-cdp-connector-examples.adoc[Salesforce CDP Connector Examples] use cases.

== Connection Types

Salesforce CDP connections use the following authentication types:

* OAuth JWT +
Uses OAuth 2.0 with a JSON Web token (JWT) request for user authentication
* OAuth Username Password +
Uses OAuth 2.0 with a user and password for authentication


For information about configuring authentication types, see xref:salesforce-cdp-connector-studio.adoc[Using Anypoint Studio to Configure Salesforce CDP Connector].

[[next-step]]
== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:salesforce-cdp-connector-studio.adoc[Anypoint Studio].

== See Also

* https://help.salesforce.com/s/articleView?id=sf.customer360_a.htm&type=5[Salesforce CDP]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:salesforce-cdp-connector-reference.adoc[Salesforce CDP Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
