= Microsoft .NET Connector 3.1 - Mule 4
:page-aliases: connectors::microsoft/microsoft-dotnet-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Microsoft .NET (Microsoft .NET Connector) enables you to execute native .NET code in a Mule application.

This connector executes .NET code using the Java Native Interface (JNI), which provides fast interprocess communication between the Java Virtual Machine (JVM) and a native application that runs in a host operating system.

The connector supports one operation, *Execute*, which enables users to select a class and a method to execute, and to pass the corresponding arguments for that method.

NOTE: This connector is compatible with Java 8 only.

== Prerequisites

To use this connector, you must be familiar with:

* The .NET API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have access to:

* The .NET target resource
* Anypoint Studio version 4.1.1 or later

NOTE: This connector is not supported for use with Anypoint Design Center.

== Common Use Cases for the Connector

Common use cases for this connector include:

* Executing code in an existing binary assembly (DLL) without modification
* Developing new .NET code that extends the capability of your integration application

For examples, see xref:microsoft-dotnet-connector-examples.adoc[Examples].

== Audience

* New users, read:
** xref:microsoft-dotnet-connector-connector-studio.adoc[Use Studio to Configure the Connector] to create your Mule app
* xref:microsoft-dotnet-connector-connector-examples.adoc[Examples], which provide one or more use cases for the connector
* Advanced users, read:
** xref:microsoft-dotnet-connector-connector-xml-maven.adoc[XML and Maven Support]
** xref:microsoft-dotnet-connector-connector-examples.adoc[Examples], which provide one or more use cases for the connector

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
