= Upgrade Cassandra Connector to Version 4.x - Mule 4

Upgrade Cassandra Connector to version 4.x to use mutual TLS authentication.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|3.x |4.x
|===

== New Features in This Release

This release supports Mutual TLS authentication.

== Changes in This Release

This release contains the following changes:

* Removed the *SSL* field from the configuration and replaced it with *TLS*
* Refactored error handling and error types

== Upgrade Prerequisites

Before you perform the upgrade, create a backup of your files, data, and configurations in case you need to restore to them.

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `cassandra` in the search field.
. In *Available modules*, select *Cassandra* and click *Add*.
. Click *Finish*.
. Verify that the Cassandra Connector dependency version is `<4.0.0>` in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Revert the upgrade

If it is necessary to revert to the previous version of Cassandra Connector, change the `cassandra-connector` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
