= Use Studio to Configure Apache Cassandra Connector 4.0 - Mule 4
:page-aliases: connectors::cassandra/cassandra-connector-studio.adoc, page-aliases: connectors::cassandra/cassandra-connector-design-center.adoc

Anypoint Studio (Studio) editors help you design and update your Mule applications, properties, and configuration files.

To add and configure a connector in Studio:

. Create a Mule project.
. Add the connector to your Mule project.
. Configure a source for the connector's flow.
. Add a connector operation to the flow.
. Configure a global element for the connector.
. Configure the other connector fields.

When you run the connector, you can view the app log to check for problems, as described in <<view-app-log,View the App Log>>.

If you are new to configuring connectors in Studio, see xref:connectors::introduction/intro-config-use-studio.adoc[Use Studio to Configure a Connector]. If, after reading this topic, you need additional information about the connector fields, see the <link to the connector Reference Guide [<connector name> Reference].

[[create-mule-project]]
== Create a Mule Project

In Studio, create a new Mule project in which to add and configure the connector:

. In Studio, select *File > New > Mule Project*.
. Enter a name for your Mule project and click *Finish*.

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

Add Apache Cassandra Connector to your Mule project to automatically populate the XML code with the connector's namespace and schema location and to add the required dependencies to the project's `pom.xml` file:

. In the *Mule Palette* view, click *(X) Search in Exchange*.
. In the *Add Dependencies to Project* window, type `cassandra` in the search field.
. Click *CassandraDB* in *Available modules*.
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio does not make that connector available to other projects in your Studio workspace.

[[configure-input-source]]
== Configure a Source

A source initiates a flow when a specified condition is met.
You can configure one of these sources to use with Apache Cassandra Connector:

* *HTTP Listener*
+
Initiates a flow each time it receives a request on the configured host and port
* *Scheduler*
+
Initiates a flow when a time-based condition is met

For example, to configure an HTTP listener, follow these steps:

. In the *Mule Palette* view, select *HTTP > Listener*.
. Drag *Listener* to the Studio canvas.
. On the *Listener* configuration screen, optionally change the value of the *Display Name* field.
. Specify a value for the *Path* field.
. Click the plus sign (*+*) next to the *Connector configuration* field to configure a global element that can be used by all instances of the HTTP listener in the app.
. On the *General* tab, specify the connection information for the connector.
. On the *TLS* tab, optionally specify the TLS information for the connector.
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.

== Add a Connector Operation to the Flow

When you add a connector operation to your flow, you immediately define a specific operation for that connector to perform.

To add an operation for Apache Cassandra Connector, follow these steps:

. In the *Mule Palette* view, select *CassandraDB* and then select the desired operation.
. Drag the operation onto the Studio canvas and to the right of the input source.

[[configure-global-element]]
== Configure a Global Element for the Connector

When you configure a connector, it’s best to configure a global element that all instances of that connector in the app can use. If an Apache Cassandra database has authentication enabled, you must provide credentials when accessing it from the connector. Apache Cassandra supports basic authentication only. To provide credentials to an Apache Cassandra database, enter the corresponding values in the Apache Cassandra Connector global element.

To configure the global element for Apache Cassandra Connector, follow these steps:

. Select the operation in the Studio canvas.
. In the configuration screen for the operation, click the plus sign (*+*) next to the *Connector configuration* field to access the global element configuration fields.
. On the *General* tab, complete the following fields:
+
[%header%autowidth.spread]
|===
|Field a|Description
|Host | Enter a host name, or IP address of an Apache Cassandra node.
|Port | Enter a port number. The default port is `9042`.
|===
+
If the target database has authentication enabled, you must also complete these fields:
+
[%header%autowidth.spread]
|===
Field a|Description
|Keyspace | Enter the Cassandra keyspace. A keyspace groups column families.
|Username | Enter an Apache Cassandra user name, if you enabled PasswordAuthenticator in the Cassandra YAML file. If `AllowAllAuthenticator` is enabled, leave this value blank.
|Password | Enter the password if you enabled `PasswordAuthenticator`. Otherwise leave this value blank.
|===
+
You can reference a configuration file that contains ANT-style property placeholders (recommended), or you can enter your authorization credentials in the global configuration properties. For information about the benefits of using property placeholders and how to configure them, see xref:connectors::introduction/intro-connector-configuration-overview.adoc[Anypoint Connector Configuration].
+
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.

[[configure-other-fields]]
== Configure Additional Connector Fields

After you configure a global element for Apache Cassandra Connector, configure the the other required fields for the connector. The required fields vary depending on which connector operation you use.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
