= Xero Accounting Connector 1.1
:page-aliases: connectors::xero/xero-accounting-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Xero Accounting (Xero Accounting Connector) enables you to access the Xero Accounting APIs. Xero Accounting APIs expose accounting and related functions of the main Xero application and can be used for a variety of purposes, such as creating transactions like invoices and credit notes, to extracting accounting data via the Reports endpoint.

For compatibility information and fixed issues, see the Xero Connector Release Notes.

include::connectors::partial$prerequisites-partial.adoc[]


== Authentication Types

Xero Connector connections use the OAuth 2.0 authentication method.


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:xero-accounting-connector-reference.adoc[Xero Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
