= Amazon DynamoDB Connector - Mule 4
:page-aliases: connectors::amazon/amazon-dynamodb-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Amazon DynamoDB Connector v1.4

Anypoint Connector for Amazon DynamoDB (Amazon DynamoDB Connector) provides connectivity to the Amazon DynamoDB API. Amazon DynamoDB is a fully managed NoSQL database service that provides fast and predictable performance with seamless scalability.

For compatibility information and fixed issues, see the xref:release-notes::connector/amazon-dynamodb-connector-release-notes-mule-4.adoc[Amazon DynamoDB Connector Release Notes]

== Common Use Cases for the Connector

Amazon DynamoDB Connector enables you to interact with Amazon DynamoDB to create a database table that can:

* Store and retrieve any amount of data
* Serve any level of request traffic
* Automatically distribute the data and traffic for the table over a sufficient number of servers to manage the request capacity and the amount of data stored.
+
Amazon Dynamo DB Connector does this while maintaining consistent, fast performance.

== Prerequisites

To use this information, you must be familiar with:

* The Amazon DynamoDB API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to:

* Amazon DynamoDB
* AWS Identity and Access Management (IAM) user account credentials
* Anypoint Studio version 7.0 or later

== Audience

* Starting user
+
To create your Mule app,
see xref:amazon-dynamodb-connector-studio.adoc[Use Studio to Configure Amazon DynamoDB Connector]. The
xref:amazon-dynamodb-connector-examples.adoc[Examples] topic provides one or more use cases for the connector.
+
* Power user
+
Read the xref:amazon-dynamodb-connector-xml-maven.adoc[XML and Maven Support] and xref:amazon-dynamodb-connector-examples.adoc[Examples] topics.

== Authentication Types

Amazon DynamoDB Connector supports the Basic and Role authentication types. For information about configuring these authentication types, see xref:amazon-dynamodb-connector-studio.adoc[Use Studio to Configure Amazon DynamoDB Connector].

== Next Step

After you complete the prerequisites and finish experimenting with templates and examples, you are ready to create a new app using Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:amazon-dynamodb-connector-studio.adoc[Use Studio to Configure Amazon DynamoDB Connector]
* https://help.mulesoft.com[MuleSoft Help Center]
