= Zuora Connector 6.0 - Mule 4
:page-aliases: connectors::zuora/zuora-connector.adoc


Anypoint Connector for Zuora (Zuora Connector) enables access to the Zuora platform. This connector exposes all of the operations provided by Zuora's REST API.

For information about the Zuora REST API methods and parameters, see the https://www.zuora.com/developer/api-reference[Zuora REST API Reference].

For compatibility information and fixed issues, see the Zuora Connector Release Notes. 

== Prerequisites

To use this connector, you must be familiar with:

* The Zuora API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have access to the Zuora target resource.

== Audience

* New user
+
Read this Get Started document
and create your Mule app in xref:zuora-connector-design-center.adoc[Design Center] or
xref:zuora-connector-studio.adoc[Anypoint Studio].
* Advanced user
+
Read the xref:zuora-connector-xml-maven.adoc[XML and Maven Support] and xref:zuora-connector-examples.adoc[Examples] documents.

== Next Step

After you complete the prerequisites, you are ready to create an app with
xref:zuora-connector-design-center.adoc[Design Center] or
xref:zuora-connector-studio.adoc[Anypoint Studio].

== Authentication Types

Zuora Connector connections use the Basic authentication type, which  uses a username and password for authentication.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:release-notes::connector/zuora-connector-release-notes-mule-4.adoc[Zuora Connector Release Notes]
* https://help.mulesoft.com[MuleSoft Help Center]
