= About ServiceNow Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, connector, endpoint, servicenow, http

The ServiceNow connector facilitates connections between Mule and ServiceNow apps. You can use the ServiceNow operations with the custom ServiceNow tables, along with any operations available through the installed plugins.

Requirements for using the connector:

* A ServiceNow account.
* Namespace and schema location: If you plan to create the XML for your Mule application, you need to include the correct namespace and schema location in your XML file. Anypoint Studio adds this information to the XML file automatically when you add the ServiceNow connector to a flow in a Mule app.

If you are upgrading from a previous version of the connector through Anypoint Studio, click the *Updates Available* message.

[[Actions]]
== Actions

* Aggregate
* Delete Multiple
* Delete Record
* Get
* Get Keys
* Get Records
* Insert
* Insert Multiple
* Update

Note: The ServiceNow SOAP site provides a full list of operations for any version of the ServiceNow connector.

[examples]
Examples
