= Troubleshooting Salesforce Connector 10.14 - Mule 4
:page-aliases: connectors::salesforce/salesforce-troubleshoot.adoc

To troubleshoot Anypoint Connector for Salesforce (Salesforce Connector), become familiar with the information about performing general troubleshooting and interpreting commonly thrown exception messages.

== Perform General Troubleshooting

Here is a list of general troubleshooting guidelines for Salesforce Connector:

* <<currency>>
* <<evaluate-values-in-a-salesforce-list>>
* <<insert-values-in-a-salesforce-connector-list>>
* <<japanese-support>>
* <<limits-on-api-calls>>
* <<opportunity-object>>
* <<query>>
* <<upsert>>
* <<upsert-picklist-values>>

[[currency]]
=== Currency

Currency values cannot exceed 18 characters in length.

When working with multiple currencies, you must know which currency your sObject uses to avoid inaccurate entries. The default currency matches the location at the organization level.

[[evaluate-values-in-a-salesforce-list]]
=== Evaluate Values in a Salesforce List

When using a value to evaluate against contents of an existing list field in Salesforce, use the exact value in the list. For example, if you use the value `US` to evaluate against contents of a list that contains the value `USA`, the evaluation works, but the result returns two values in the list: one for `US` and one for `USA`.

[[insert-values-in-a-salesforce-connector-list]]
=== Insert Values in a Salesforce Connector List

Inserting dependent values into an existing list in Salesforce Connector does not always work. Test to confirm this functionality.

[[japanese-support]]
=== Japanese Support

Salesforce Connector supports Japanese characters for all operations, with the following exceptions:

* The *Publish Streaming Channel* operation does not support Japanese characters in the *Channel name* field, which can contain only alphanumeric and the `&#95;` or `/` characters. Refer to the Salesforce https://developer.salesforce.com/docs/atlas.en-us.228.0.object_reference.meta/object_reference/sforce_api_objects_streamingchannel.htm[StreamingChannel] documentation for more information.

* Metadata operations might return error messages if some fields contain Japanese characters. For example, creating custom objects or custom fields with a *Full Name* that contains Japanese characters triggers a `FIELD_INTEGRITY_EXCEPTION` error with the following message: +
`The Object Name field can only contain underscores and alphanumeric characters. It must be unique, begin with a letter, not include spaces, not end with an underscore, and not contain two consecutive underscores.`

[[limits-on-api-calls]]
=== Limits on API Calls

You must know the scope of the rate limiting policy that applies to your account so that you do not exceed the number of allotted API calls per day.

[[opportunity-object]]
=== Opportunity Object

When extracting data from a Salesforce Opportunity object, be aware that a `quarter` in this context is relative to the fiscal year of the organization and not necessarily to the calendar year.

[[query]]
=== Query

Although you can see the fields of an SObject and their corresponding types via DataSense, the *Query* operation returns all fields as strings. To use the actual type of a field, use a *Transform* or *Transform Message* component to convert the field to the desired type.

Although the *Created Date* field appears as `dateTime`, the query returns a string that represents the date. To use the field as a `dateTime` field, use a *Transform Message* component to configure the field. To store `Date` and `dateTime` fields, use DataWeave expressions to create `Date` and `Calendar` Java objects.

[[upsert]]
=== Upsert

Unless you configure the *External Id Field Name* field for the SObject to upsert, the *Upsert* operation fails.

The *Upsert* operation does not work with the SObject `priceBookentry2`.

Although you cannot change the *Content Type* value for a bulk upsert, you can use the *Create Job* operation to set the content type to CSV (or zipped CSV if you reach the character limit) and then follow up with the *Create Batch* operation.

[[upsert-picklist-values]]
=== Upsert Picklist Values

For a picklist field in an object, the *Upsert Metadata* operation updates only
the picklist mapping for that specific object. To update the actual picklist
values, such as adding or removing values in the picklist, use the
*Deploy Metadata* operation. You must perform a metadata deploy for
*Custom Field* or *Global Picklist* based on whether the picklist is tied to a
custom field or is a global picklist.


== Understand Common Throws

Here is a list of common throw messages and how to interpret them.

* SALESFORCE:CONNECTIVITY

 A problem occurred and a connection could not be established.

* SALESFORCE:INVALID_INPUT

 The provided input data for an operation is not valid.

* SALESFORCE:INVALID_RESPONSE

 The response from the server cannot be processed.

* SALESFORCE:LIMIT_EXCEEDED

 A specific limit is exceeded, for example, if you try to create more than 200 entities at once with the *Create* operation.

* SALESFORCE:MUTUAL_AUTHENTICATION_FAILED

 The mutual authentication failed.

* SALESFORCE:NOT_FOUND

 The server could not find the requested resource.

* SALESFORCE:RETRY_EXHAUSTED

 The maximum number of retries for the operation is reached.

* SALESFORCE:TIMEOUT

 A specific request takes longer than a configured amount of time to complete.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:salesforce-connector-config-topics.adoc[Additional Configuration Information]
* xref:salesforce-connector-examples.adoc[Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
