= Anypoint M Q Connector - 3.x
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_Select_

The Anypoint MQ connector provides publish-subscribe messaging to Mule applications using the Anypoint MQ cloud service.

Anypoint MQ supports a wide range of messaging use cases: enterprise messaging patterns, asynchronous communications between microservices, IoT, and more. Anypoint MQ also has a REST API for publishing or consuming messages using any framework such as node.js, Java, Go, and devops bash scripts.

For more information, see the xref:mq::index.adoc[Anypoint MQ documentation set] and additional resources listed in <<See Also>>.

== Prerequisites

To use this connector, you should be familiar with Anypoint Studio, Anypoint connectors, and Mule flows. The Anypoint MQ connector is free, but connecting to the service in Anypoint Platform requires a license.

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.1.1 and later
|Anypoint Studio |v7 and later
|===

IMPORTANT: This documentation applies only to Mule 4. For Mule 3 compatible connector information, see xref:3.9@mule-runtime::anypoint-mq-connector.adoc[Mule 3 MQ Connector].

TIP: Check the migration guide for moving from *old connector 2.x version* to the *new 3.x version* for Mule 4 xref:anypoint-mq/3.x/anypoint-mq-new-major.adoc[Mule 4 MQ Connector - Migration Guide].

== Install This Connector

From Anypoint Exchange:

. In Anypoint Studio, click the Exchange icon in the Studio task bar.
. Click Login in Anypoint Exchange and supply your Anypoint Platform username and password.
. Search for the connector and click Install.
. Follow the prompts to install the connector.

For applications written in XML or that are standalone:

. Open your Mule project in Anypoint Studio.
. Add the connector as a dependency in the pom.xml file:
+
[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>anypoint-mq-connector</artifactId>
  <version>${mq.latest.version}</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

For the latest POM, Gradle, or SBT dependencies, see the  https://www.anypoint.mulesoft.com/exchange/com.mulesoft.connectors/anypoint-mq-connector/[Exchange Anypoint MQ Connector] asset. Click *Dependency Snippets* for a complete list.


== Using Anypoint MQ In A Mule Project

1) Make sure you have installed the connector. Read how to do it here: <<Install This Connector>>
2) Create a new project in Studio:  Click File > New > Mule Project.
3) Search for "mq" in the palette and all the operations for the *Anypoint MQ* connector should be now available.

=== Create a new Configuration for the Anypoint MQ Connector

1) Click the green plus sign to the right of Connector Configuration.

2) Specify the broker URL for the region you want your MQ queues and exchanges to reside. This URL can be obtained and configured from the Anypoint Platform > Anypoint MQ console.

+
Possible values are:
+
** North America:
*** US East (N. Virginia): `+https://mq-us-east-1.anypoint.mulesoft.com/api/v1+`
*** US West (Oregon): `+https://mq-us-west-2.anypoint.mulesoft.com/api/v1+`
*** Central Canada: `+https://mq-ca-central-1.anypoint.mulesoft.com/api/v1+`
** Europe:
*** EU (Ireland): `+https://mq-eu-west-1.anypoint.mulesoft.com/api/v1+`
*** EU (London): `+https://mq-eu-west-2.anypoint.mulesoft.com/api/v1+`
** APAC:
*** Asia Pacific (Singapore): `+https://mq-ap-southeast-1.anypoint.mulesoft.com/api/v1+`
*** Asia Pacific (Sydney): `+https://mq-ap-southeast-2.anypoint.mulesoft.com/api/v1+`
+
FIFO queues can reside in US East, US West, and EU Ireland.
+

3) In Anypoint Platform, click MQ > Client Apps. If needed, create a client app.

4) Copy the Anypoint Platform > MQ > Client App > Client App ID value to the Studio Client ID field.

5) Copy the Client App > Client Secret value to the Studio Client Secret field. You can ignore the other settings to test your  connector.

6) Click OK.

=== Selecting An Operation

1) In the Studio palette you should now see a list with all the operations available. Possible operations are:

[%header%autowidth.spread]
|===
|Operation |Description
|xref:anypoint-mq/3.x/anypoint-mq-publish.adoc[Publish] |Publishes messages to a destination.
|xref:anypoint-mq/3.x/anypoint-mq-consume.adoc[Consume] |Consumes messages from a queue.
|xref:anypoint-mq/3.x/anypoint-mq-listener.adoc[Subscribe] |Listens for messages from a queue.
|xref:anypoint-mq/3.x/anypoint-mq-ack.adoc[Ack] |Indicates that the message has been consumed correctly and deletes the message from in-flight status.
|xref:anypoint-mq/3.x/anypoint-mq-ack.adoc[Nack] |Changes the status of the message from in-flight to in-queue to be consumed again by a subscriber.
|===

2) Drag & drop the desired operation to the canvas
3) Configure the operation accordingly. For a list of configuration fields for each operation and information about XML elements, see the xref:anypoint-mq/3.x/anypoint-mq-connector-reference.adoc[Anypoint MQ Connector Reference].


INFORMATION: For more information on how to use each of the operations, please refer to the <<See Also>> section at the bottom.

== See Also

* xref:anypoint-mq/3.x/anypoint-mq-connector-reference.adoc[Anypoint MQ Connector Reference]
* xref:anypoint-mq/3.x/anypoint-mq-publish.adoc[Publishing a Message]
* xref:anypoint-mq/3.x/anypoint-mq-consume.adoc[Consuming a Message]
* xref:anypoint-mq/3.x/anypoint-mq-listener.adoc[Listening for Messages]
* xref:anypoint-mq/3.x/anypoint-mq-ack.adoc[Acknowledgment]
* xref:mq::index.adoc[MQ documentation]
* xref:mq::mq-faq.adoc[MQ FAQ]
* xref:mq::mq-apis.adoc[REST API]
* https://www.anypoint.mulesoft.com/exchange/com.mulesoft.connectors/anypoint-mq-connector/[Exchange Anypoint MQ Connector]
