= Anypoint MQ Connector 3.x Migration Guide
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Anypoint MQ Connector version 3.0 includes new features, such as simplified configuration, standardized endpoints, and non-blocking functionality.

=== Global Configuration

In the previous version of the Anypoint MQ Connector, the `config` element included parameters, as shown in this example:

[source,xml,linenums]
----
<anypoint-mq:default-subscriber-config
    name="Anypoint_MQ_Default_subscriber"
    acknowledgementMode="IMMEDIATE"
    acknowledgementTimeout="10000" <!-- (1) -->
    maxRedelivery="2"              <!-- (2) -->
    pollingTime="2000"
    fetchSize="5"                  <!-- (3) -->
    fetchTimeout="5000"            <!-- (3) -->
    frequency="2000">              <!-- (3) -->
  <anypoint-mq:connection          <!-- (4) -->
    clientId="${client.id}"
    clientSecret="${client.secret}"/>
  <anypoint-mq:circuit-breaker     <!-- (5) -->
    circuitName="InvoiceSettings"
    onErrorTypes="JMS:TIMEOUT"
    errorsThreshold="10" tripTimeout="1"
    tripTimeoutUnit="MINUTES" />
</anypoint-mq:default-subscriber-config>
----

In this version, the `config` element for the MQ Connector now contains only the connection settings:

[source,xml,linenums]
----
<anypoint-mq:config name="Anypoint_MQ_Config">
    <anypoint-mq:connection
        clientId="${client.id}"
        clientSecret="${client.secret}" />
</anypoint-mq:config>
----

The following table describes the `config` parameter differences.

[%header,cols="20a,40a,40a"]
|===
|Element | 2.x Version Behavior | 3.x Version Equivalent
|*(1)* - Acknowledgment
|Global acknowledgment settings for the Anypoint MQ Subscribers
|Configure for each Subscriber instance.

|*(2)* - Max Redelivery
|Redelivery filter for Anypoint MQ messages located in the `redeliveryCount` header
|Deprecated and no longer available as a standalone filter. Use `"DLQ + Idempotent Filter"` pattern instead.

|*(3)* - Message Fetch
|All parameters related to how messages are retrieved from the Anypoint MQ service, including `prefetch` configuration.
|Configure all the fetching strategy parameters on each Subscriber under the `Subscriber Type` parameter.

|*(4)* - Connection
|Connection parameters
|Idem configuration for all the connection settings.

|*(5)* - Circuit Breaker
|Circuit Breaker configuration for the Anypoint MQ Subscriber
|Handle each Circuit Breaker instance either as a standalone element referenced by each Anypoint MQ Subscriber or as a private Circuit Breaker for the Subscriber who declares it.
|===


=== Subscriber Listener

In this version, the `Subscriber` message source configuration for message listening has changed.

For information about the new subscriber, see xref:anypoint-mq/3.x/anypoint-mq-listener.adoc[Anypoint MQ Subscriber Operation].

==== Message Acknowledgment

In the previous version of the connector, the `acknowledgementMode` of the subscriber was defined at the configuration level:

[source,xml,linenums]
----
<anypoint-mq:default-subscriber-config name="Anypoint_MQ_Default_subscriber"
       acknowledgementMode="MANUAL" acknowledgementTimeout="120000">
    <anypoint-mq:connection clientId="${client.id}" clientSecret="${client.secret}"/>
</anypoint-mq:default-subscriber-config>
----

These parameters are now part of the subscriber element itself and affect only that single subscriber instance. The semantics of the acknowledgment parameters has not changed.
Here's the equivalent configuration of the subscriber:

[source,xml,linenums]
----
<anypoint-mq:subscriber config-ref="Anypoint_MQ_Config"
    destination="queue"
    acknowledgementMode="MANUAL"
    acknowledgementTimeout="2"
    acknowledgementTimeoutUnit="MINUTES"/>
----

==== Prefetch Mode

In the previous version of Anypoint MQ Connector, `prefetch` mode was enabled by default and you specified all related parameters at the configuration level:

[source,xml,linenums]
----
<anypoint-mq:default-subscriber-config
      name="Anypoint_MQ_Default_subscriber"
      pollingTime="2000" fetchSize="5"
      fetchTimeout="5000" frequency="2000">
    <anypoint-mq:connection clientId="${client.id}"
      clientSecret="${client.secret}"/>
</anypoint-mq:default-subscriber-config>
----

This version includes a new concept called `Subscriber Type`, in which you control the `prefetch` configuration.

[source,xml,linenums]
----
<anypoint-mq:subscriber config-ref="Anypoint_MQ_Config"
    destination="queue">
   <anypoint-mq:subscriber-type>
     <anypoint-mq:prefetch maxBufferSize="20"/>
   </anypoint-mq:subscriber-type>
</anypoint-mq:subscriber>
----

The following table describes the `prefetch` parameter differences.

[%header,cols="20a,30a,20a,30a"]
|===
| 2.x Version Parameter |Description| 3.x Version Equivalent |Description
|`fetchSize`| Declared at Config level, controls the size of the local message buffer, which is calculated as three times the `fetchSize`.
|`maxBufferSize`| Declared at the `Subscriber` level, explicitly controls the maximum size that the local message buffer can have. This parameter serves as a target number, attempting to fetch as many messages as needed to fill it completely.

|`fetchTimeout`| Controlled the time waiting for a response from the service.
|Deprecated| This parameter is no longer available. The connector always uses the maximum long-polling value.

|`frequency`| Controlled when to recheck for messages after the queue is empty.
|Deprecated | This parameter is no longer available. The connector now handles the frequency internally - fixed at 1 second.

|`pollingTime`| Used only when `fetchSize` was `0`, effectively disabling the `prefetch` mode and moving to a `polling` mode.
|Deprecated| This parameter is replaced by the more powerful `polling` Subscriber Type.
|===

==== Polling Mode

Previous versions of the Anypoint MQ Connector allowed you to disable the `prefetch` mode by setting the `fetchSize` parameter to `0` and then using the `pollingTime` as a fixed-frequency polling scheduler.

In this version, the polling mode of the subscriber has been simplified and normalized. You can now use the schedulers provided by Mule Runtime out of the box, either as `fixed-frequency` or `cron`:

* `fixed-frequency`
+
[source,xml,linenums]
----
<anypoint-mq:subscriber config-ref="Anypoint_MQ_Config"
  destination="queue">
   <anypoint-mq:subscriber-type >
      <anypoint-mq:polling >
         <scheduling-strategy >
            <fixed-frequency frequency="1" timeUnit="SECONDS" />
         </scheduling-strategy>
      </anypoint-mq:polling>
   </anypoint-mq:subscriber-type>
</anypoint-mq:subscriber>
----

* `cron`
+
[source,xml,linenums]
----
<anypoint-mq:subscriber destination="queue"
    config-ref="Anypoint_MQ_Config">
    <anypoint-mq:subscriber-type>
        <anypoint-mq:polling>
            <scheduling-strategy>
                <cron expression="0 * 14 * * ?"
                timeZone="America/Los_Angeles"/>
            </scheduling-strategy>
        </anypoint-mq:polling>
    </anypoint-mq:subscriber-type>
</anypoint-mq:subscriber>
----


==== Circuit Breaker

The circuit breaker declaration is no longer in the config and is now either a global element, or an inline declaration.

In the previous version, you declared the circuit breaker as part of the config and then referenced the config across multiple subscribers:

[source,xml,linenums]
----
<anypoint-mq:default-subscriber-config name="ConfigWithCircuit" >
     <anypoint-mq:connection url="${providerUrl}"
       clientId="${clientId}"
      clientSecret="${clientSecret}"/>
   <anypoint-mq:circuit-breaker
       circuitName="InvoiceProcess"
       onErrorTypes="FTP:RETRY_EXHAUSTED, HTTP:SERVICE_UNAVAILABLE"
       errorsThreshold="10"
       tripTimeout="5"
       tripTimeoutUnit="MINUTES"/>
</anypoint-mq:default-subscriber-config>

<flow name="subscribe">
    <anypoint-mq:subscriber
        config-ref="ConfigWithCircuit"
        destination="${reservationsQueue}"/>
    <flow-ref name="invoiceProcess">
</flow>

<flow name="otherSubscribe">
    <anypoint-mq:subscriber
        config-ref="ConfigWithCircuit"
        destination="${paymentsQueue}"/>
    <flow-ref name="invoiceProcess">
</flow>

<sub-flow name="invoiceProcess">
  <ftp:write path="${auditFolder}" config-ref="ftp-config"/>
  <http:request config-ref="requestConfig" path="/external"/>
</sub-flow>
----

In this version, you declare one standalone global element, and reference that global element from each subscriber, no longer binding a connection to the app logic circuit:

[source,xml,linenums]
----

<anypoint-mq:config name="Anypoint_MQ_Config">
    <anypoint-mq:connection url="${providerUrl}"
       clientId="${clientId}"
       clientSecret="${clientSecret}"/>
</anypoint-mq:config>

<anypoint-mq:circuit-breaker
    name="InvoiceProcess"
    onErrorTypes="FTP:RETRY_EXHAUSTED, HTTP:SERVICE_UNAVAILABLE"
    errorsThreshold="10"
    tripTimeout="5"
    tripTimeoutUnit="MINUTES"/>

<flow name="subscribe">
    <anypoint-mq:subscriber
        destination="${reservationsQueue}"
        config-ref="Anypoint_MQ_Config"
        circuitBreaker="GlobalCircuit"/>
    <flow-ref name="invoiceProcess">
</flow>

<flow name="otherSubscribe">
    <anypoint-mq:subscriber
        destination="${paymentsQueue}"
        config-ref="Anypoint_MQ_Config"
        circuitBreaker="GlobalCircuit"/>
    <flow-ref name="invoiceProcess">
</flow>

<sub-flow name="invoiceProcess">
  <ftp:write path="${auditFolder}" config-ref="ftp-config"/>
  <http:request config-ref="requestConfig" path="/external"/>
</sub-flow>

----

=== Publish Operation

In the previous version, `Publish` operation properties were declared like this:

[source,xml,linenums]
----
<anypoint-mq:publish config-ref="Anypoint_MQ_Default_subscriber"
       destination="queue"
       messageId="#[vars.messageId]" sendContentType="false">
   <anypoint-mq:body >#[vars.messageBody]</anypoint-mq:body>
   <anypoint-mq:properties >
      <anypoint-mq:property key="MSG_TYPE" value="My Value"/>
   </anypoint-mq:properties>
</anypoint-mq:publish>
----

In version 3.x, you now declare the same properties as a dynamic map, subject to transformations and a dynamic number of keys, instead of having fixed keys for each message:

[source,xml,linenums]
----
<anypoint-mq:publish config-ref="Anypoint_MQ_Config"
     destination="queue"
     messageId="#[vars.currentId]" sendContentType="false">
   <anypoint-mq:body >#[vars.messageBody]</anypoint-mq:body>
   <anypoint-mq:properties ><![CDATA[#[output application/java -----
{
   "MSG_TYPE" : vars.msgType
}]]]></anypoint-mq:properties>
</anypoint-mq:publish>
----

The following table describes the `Publish` operation differences.

[%header,cols="35,30,30"]
|===
| Changes | 2.x Version | 3.x Version
| Execution Type
| Blocking
| Non-Blocking

| Properties Parameter
| Fixed key/value map
| Dynamic "content" parameter map
|===


For more information, see xref:anypoint-mq/3.x/anypoint-mq-publish.adoc[Anypoint MQ Publish Operation]

=== Consume Operation

The following table describes the Consume operation differences.

[%header,cols="35,30,30"]
|===
| Changes | 2.x Version | 3.x Version
| Execution Type
| Blocking
| Non-Blocking

| Default Acknowledgment Mode
| MANUAL
| IMMEDIATE
|===

For more information, see xref:anypoint-mq/3.x/anypoint-mq-consume.adoc[Anypoint MQ Consume Operation].

=== ACK and NACK Operations

The ACK and NACK operations now use the `ackToken` string.

You can obtain this new `ackToken` value from the attributes object. The `ackToken` is available only for messages that have a `MANUAL` acknowledgment mode.

The following table describes the ACK and NACK operation differences.

[%header,cols="50,50"]
|===
| 2.x Version | 3.x Version
| Operations received a `messageContext` parameter, whose value had to be the `attributes` element from a given message.
| Use the `ackToken` string of the message to perform the ACK or NACK of a message.
|===


For more information, see xref:anypoint-mq/3.x/anypoint-mq-ack.adoc[Anypoint MQ ACK and NACK Operations].

=== Platform Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.1.1 and later
|Anypoint Studio |v7 and later
|===
