= Message Acknowledgment
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


== Acknowledgement Configurations 

The Anypoint MQ connector provides different acknowledgment configurations.

=== Immediate Acknowledgment

Setting the `acknowledgementMode` to `IMMEDIATE` either in `anypoint-mq:subscriber` or `anypoint-mq:consume` operations  causes the message to be automatically acknowledged once it is consumed, and prior to any processing of the message by the application.
Having the message automatically acknowledged once it is received means that the message isn't redelivered if an error occurs during the processing of the message. To handle possible message errors, you need to handle application logic like creating a dead letter queue to handle errors without losing messages.

If an error occurs while trying to acknowledge the message using `IMMEDIATE` mode, an `ANYPOINT-MQ:ACKING` error will be thrown.

=== Automatic Acknowledgment

You can use the AUTO `acknowledgementMode` in the `anypoint-mq:subscriber` component to cause an automatic ACK of the received message - if and only if the flow execution completes successfully.
If an error occurs during the flow execution, causing its execution to terminate prematurely, then the message is NACKed, returning to the queue for redelivery to occur.

=== Manual Acknowledgment

The `MANUAL` acknowledgement mode delegates all the responsibility for performing an ACK on the message to the application logic to decides and when to perform the acknowledgement of the message, using the xref:anypoint-mq/3.x/anypoint-mq-ack.adoc[ACK] or xref:anypoint-mq/3.x/anypoint-mq-ack.adoc[NACK] operations. 

With this configuration, every message received by either the `subscriber` or `consume` operations has an `ackToken` value available in the Mule message `attributes` that identifies this message uniquely for a given connection. 
Save this `ackToken`, as it has to be used later as input for the `ACK`  or `NACK` operations.

=== Acknowledgement Timeout

When using either `AUTO` or `MANUAL` acknowledgement modes, is important to consider the `acknowledgementTimeout` parameter, meant to control for how long is the message allowed to remain in-flight waiting to be acknowledged, before automatically returning to the queue. 
By default, the connector will honor the time defined at queue level from the admin console with the `Message Lock Default TTL` value.

WARNING: Always use an `Acknowledgement Timeout` that better suits your expected application time processing, leaving room for unexpected but possible extra delays due to external systems delay, application back-pressure due to high load, so on. For example, if the consumed message is expected to be processed within 10 seconds, the `acknowledgementTimeout` is recommended to be a minimum of 15 seconds.

==== Acknowledgement Timeout With AUTO Acknowledge

After a message is consumed by the `subscriber`, a timer begins indicating how long the message has been in-flight for the broker waiting for an acknowledgment to occur. If the flow processing does not end, either with a success or a failure, before the `acknowledgementTimeout` limit is reached, the message automatically returns to the queue for redelivery. 

==== Acknowledgement Timeout With MANUAL Acknowledge

When consuming a message using `MANUAL` acknowledgement mode, both in the `subscriber` or the `consume` operation, the application is required to execute either an `anypoint-mq:ack` or `anypoint-mq:nack` operation using the message `ackToken` before the `acknowledgementTimeout` limit is reached. If neither operation is executed with the given token before the timeout, the message will automatically return to the queue for redelivery. Any attempt of acknowledging the message after the timeout will fail due to an expired token.


== Manual Acknowledgment Using The ACK Operation

Acknowledging a message commands the broker that the message has been processed and thus it needs to be removed from the queue, avoiding any redelivery,

The *acknowledgement token* of a message, available in the `ackToken` field of the Anypoint MQ Message Attributes, is a unique token for the message that needs to be used when performing the `anypoint-mq:ack` operation:

[source,console,linenums]
----
<flow name="consumerWithManualAck">
    <scheduler>
			<scheduling-strategy >
				<fixed-frequency />
			</scheduling-strategy>
	</scheduler>

    <!-- Consume a message -->
    <anypoint-mq:consume destination="${destination}" acknowledgementMode="MANUAL" config-ref="Anypoint_MQ_Config"/>
    
    <!-- Save the ackToken for future acknowledgment -->
    <set-variable variableName="currentAckToken" value="#[attributes.ackToken]"/>
    
    <!-- Do the required processing of the message -->
    <flow-ref name="process-message"/>

    <!-- Use the ackToken to acknowledge the message -->
    <anypoint-mq:ack ackToken="#[vars.currentAckToken]" config-ref="Anypoint_MQ_Config" />
</flow>
----

WARNING: If during the processing of an MQ message, a non-void operation is invoked, the payload and attributes of the Mule message are modified. To do an ACK after processing, you must save the `ackToken` in a variable.

A convenient way to save the attributes for later is using the `target` and `targetValue`  parameters, storing the whole message in a variable:

[source,console,linenums]
----
<flow name="consumerWithManualAck">
    <scheduler>
			<scheduling-strategy >
				<fixed-frequency />
			</scheduling-strategy>
	</scheduler>

    <!-- Consume a message -->
    <anypoint-mq:consume destination="${destination}" acknowledgementMode="MANUAL" config-ref="Anypoint_MQ_Config"
                target="mqMessage" 
                targetValue="#[message]"/>
    

    <!--Do any message processing-->
    <jms:publish-consume destination="#[vars.mqMessage.attributes.targetDestination]" config-ref="JMS_Config">
        <jms:message>
            <jms:body>#[vars.mqMessage.payload]</jms:body>
        </jms:message>
    </jms:publish-consume>

    <!-- Use the ackToken to acknowledge the message -->
    <anypoint-mq:ack ackToken="#[vars.mqMessage.attributes.ackToken]" config-ref="Anypoint_MQ_Config" />
</flow>
----

=== Execute a NACK

Not-Acknowledging a message commands the broker that the message was not processed successfully and it has to be returned to the queue for  redelivery to any available consumer.
The *acknowledgement token* of a message, available in the `ackToken` field of the Anypoint MQ Message Attributes, is a unique token for the message that needs to be used when performing the `anypoint-mq:nack` operation:

[source,console,linenums]
----
<flow name="consumerWithManualAck">
    <scheduler>
			<scheduling-strategy >
				<fixed-frequency />
			</scheduling-strategy>
	</scheduler>

    <!-- Consume a message -->
    <anypoint-mq:consume destination="${destination}" acknowledgementMode="MANUAL" config-ref="Anypoint_MQ_Config"
                target="mqMessage" 
                targetValue="#[message]"/>

    <!--Do message processing -->
    <logger message="#[payload]"/>

    <!-- Use the ackToken to NACK the message -->
    <anypoint-mq:ack ackToken="#[vars.mqMessage.attributes.ackToken]" config-ref="Anypoint_MQ_Config" />
</flow>
----


== See Also

* xref:anypoint-mq/3.x/anypoint-mq-consume.adoc[Consume a Message]
* xref:anypoint-mq/3.x/anypoint-mq-listener.adoc[Listen For New Messages]
