= Test - Use Anypoint Studio to Configure Amazon Kinesis Data Streams Connector 1.0 - Mule 4

include::connectors::partial$t-studio-topic-intro-partial.adoc[]

[[create-mule-project]]
== Create a Mule Project

include::connectors::partial$t-studio-create-project-sect-partial.adoc[]

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

include::connectors::partial$t-studio-add-connector-sect-intro-partial.adoc[]

[[configure-source]]
== Configure a Source

include::connectors::partial$t-studio-config-source-sect-intro-partial.adoc[]

include::connectors::partial$t-studio-listener-scheduler-bullets-partial.adoc[]

For example, to configure the Amazon Kinesis *Listener* source, follow these steps:

. In the *Mule Palette* view, select *Kinesis*.
. Drag *Listener* to the Studio canvas.
. On the *Listener* properties window, optionally change the value of the *Display Name* field.
. Click the plus sign (*+*) next to the *Connector configuration* field to configure a global element that can be used by all instances of the Amazon Kinesis Connector in the app.
. On the *General* tab, complete the following fields:
+
[%header,cols="30s,70a"]
|===
|Field a|Description
|Name | Name used to reference this connector instance
|Access Key | Access key provided by Amazon
|Secret Key | Secret key provided by Amazon
|Region Endpoint |  URL entry point for a web service
|Role | IAM role, if any
|===
+
. On the *Security* tab, optionally specify the TLS information for the connector.
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.
. In the *Listener Params* section of the *Listener* properties window, optionally enter values for the fields.

[[add-connector-operation]]
== Add a Connector Operation to the Flow

include::connectors::partial$t-studio-add-connector-op-sect-intro-partial.adoc[]

You can use the following operations:

* *Checkpoint*, which keeps track of the current position in the Kinesis data stream
* *Seek*, which moves the reading position of the sources (listeners)
+
While moving forward in the stream is fluent, moving backward causes an internal restart of the Kinesis Client Library (KCL) instance. Therefore, use this operation sparingly to move backward in a stream.
+
* *Put Record*, which puts a record into the Kinesis data stream.
+
If the *Aggregation Enabled* field in the global configuration *Advanced* tab is `true` (the default), then multiple records are combined and stored in one Kinesis Data Streams record.
+
Records include binary data, a partition key, and an explicit hash key. The explicit hash key value is normally computed with the MD5 function of the record partition key, but you can override the value by using the *Explicit Hash Key* field. The operation uses the Kinesis Producer Library (KPL), which increases throughput.

To add an operation for Amazon Kinesis Data Streams Connector, follow these steps:

. In the *Mule Palette* view, select *Kinesis* and then select the desired operation.
. Drag the operation onto the Studio canvas to the right of the source.

[[configure-global-element]]
== Configure a Global Element for the Connector

include::connectors::partial$t-studio-config-global-element-sect-intro-partial.adoc[]

Amazon Kinesis Data Streams Connector supports Access Key authentication, which uses *Access Key* and *Secret Key* field values for AWS Identity and Access Management (IAM).

To configure a global element, follow these steps:

. Select the name of the connector in the Studio canvas.
. In the configuration screen for the operation, click the plus sign (*+*) next to the *Connector configuration* field to access the global element configuration fields.
. On the *General* tab, configure the following fields.
+
[%header,cols="30s,70a"]
|===
|Field |Description
|Name | Name used to reference the connector instance
|Access Key | Access key provided by Amazon
|Secret Key | Secret key provided by Amazon
|Region Endpoint | URL entry point for a web service
|Role | IAM role, if any
|===
+
. On the *Advanced* tab, optionally specify proxy and reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.

[[view-app-log]]
== View the App Log

include::connectors::partial$t-studio-view-app-log-sect-partial.adoc[]

== Next Step

After you configure a global element and connection information, configure the other fields for the connector.

== See Also

include::connectors::partial$t-studio-see-also-sect-partial.adoc[]
