= Advanced driver configuration - Database Connector 1.10 - Mule 4
:page-aliases: connectors::db/database-connector-advanced-driver-configuration.adoc

Usually Studio helps to setup driver dependecies without problems, but there are some special scenarios where there's an additional configuration required in order to properly setup the driver classes visibility (due classloading isolation mechanisms). 

. <<driver-visible-across-the-application, Driver visible across the application>>.
. <<driver-only-visible-for-connector, Driver only visible for the connector>>.


[[driver-visible-across-the-application]]
== The driver visible across the application

By default, when configuring additional dependencies from Studio, the https://docs.mulesoft.com/mule-runtime/4.3/mmp-concept#configure-shared-libraries[Shared Libraries Mechanism] of the Mule Maven Plugin is used. 
Under this mechanism are visible across components whitin an application. 



[[driver-only-visible-for-connector]]
== Driver only visible for the connector

When there's risk of dependency colission or there's a need to have in the same ClassLoader the connector and the driver dependency, there's another option for hinting that the driver classes should be loaded by the same ClassLoader that's loading the connector. This mechanism is known as https://docs.mulesoft.com/mule-runtime/4.3/mmp-concept#configure-plugin-dependencies[Additional Plugin Dependencies]



* *Important*
Please note that you should be aware of which component is in charge of stablishing the connection, and the driver should be in the scope of that component's ClassLoader. For example, an application using datasource reference targeting a spring bean datasource definition. The database library is needed by the Spring's ClassLoader (Not the database). The recommended way to set up the application dependencies is using the Shared Libraries approach.


== See Also

* https://docs.mulesoft.com/mule-runtime/4.3/mmp-concept[Mule Maven Plugin]
* xref:database-documentation.adoc[Database Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
