= XML Module 1.3 - Mule 4
:page-aliases: connectors::xml/xml-module.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

The XML Module process and extracts data from an XML document. Although DataWeave is recommended for most XML-related cases, use the XML Module for cases that involve the usage of XML standards such as XSLT, XPath, and XQuery, or XSD.

For compatibility information and fixed issues, see the XML Module Release Notes.


== Prerequisites

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have access to Anypoint Platform and Anypoint Studio.

== Common Use Cases for the Connector

Common use cases for XML Module include the following:

* Validate documents against an XSD schema
* Take XML input and transform it using an XSL style sheet
* Evaluate Xpath expressions in XML input content and extract the result
* Take XML input content and transform it based on XQuery expressions

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
