= Workday Connector - Get Started - Mule 4
:page-aliases: connectors::workday/workday-about.adoc, connectors::workday/workday-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Workday Connector Version 12.0

Anypoint Connector for Workday (Workday Connector) provides access to standard Workday operations.
Workday is a Software-as-a-Service (SaaS) solution developed by Workday, Inc.
Workday provides a set of software apps for financial and human capital management, such as
human resources, staffing, recruiting, and performance.

Release Notes: xref:release-notes::connector/workday-connector-release-notes-mule-4.adoc[Workday Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-workday-connector/[Workday Connector]

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect
to APIs and resources on external systems, such as Salesforce, Workday, ServiceNow,
and Twitter.

== Prerequisites

Before creating an app, you must have access to the Workday target resource and
Anypoint Platform. You also need to understand how to create a Mule app using
Design Center or Anypoint Studio.

== Audience

* Starting user
+
To create your Mule app,
see xref:workday-connector-design-center.adoc[Design Center Configuration]
or xref:workday-connector-studio.adoc[Studio Configuration].
The
xref:workday-connector-config-topics.adoc[Additional Configuration Information]
topic helps extend your understanding of the Workday connector.
The xref:workday-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Power user
+
Read the xref:workday-connector-xml-maven.adoc[XML and Maven Support]
and xref:workday-connector-examples.adoc[Examples] topics.

== Common Use Cases For the Connector

The common use case for Workday Connector is starting any of Workday's standard operations. xref:workday-connector-examples.adoc[Example] use cases include creating a position request in Workday or adding a fund to the financial management service.

== Learn Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
you can use as a starting point for your app, as well as examples that illustrate a complete solution.

* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker-bidirectional-sync[Workday and ServiceNow Worker Bidirectional Sync]
* https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2wday-user-bidirectional-sync[Salesforce and Workday Bidirectional Sync]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-workerservicerequest-migration[Workday Worker to ServiceNow Service Request Migration]
* https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sfdc-worker-migration[Salesforce to Workday Financials Account - Customer Migration]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-employee-aggregation[Workday and ServiceNow Employee Aggregation]
* https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sfdc-worker-aggregation[Workday and Salesforce Worker Aggregation]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker-migration[Workday to ServiceNow Service Worker Migration]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker2servicerequest-broadcast[Workday Worker to ServiceNow Service Request Broadcast]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker2user-broadcast[Workday Worker to ServiceNow User Broadcast]
* https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sfdc-workercase-broadcast[Workday to Salesforce Worker Case Broadcast]

== Next Step

After you have met the prerequisites and experimented with templates and examples, you are ready to create an app with
xref:workday-connector-design-center.adoc[Design Center] or xref:workday-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
