= Workday - Studio Configuration - Mule 4
:page-aliases: connectors::workday/workday-studio.adoc, connectors::workday/workday-connector-studio.adoc

To configure Anypoint Connector for Workday:

. Add the connector to your project from either Exchange or from within Anypoint Studio.
. Configure the connector.
. Configure an input source for the connector.

== Add the Connector to Your Project

Anypoint Studio provides two ways to add the connector to your Studio project: from the Exchange button in the taskbar or from the *Mule Palette*.

=== Add the Connector Using Exchange

. In Studio, create a Mule Project.
. Click the Exchange *(X)* icon in the upper left of the Studio task bar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for "Workday".
. Select Workday Connector, click *Add to project*.
. Follow the prompts to install the connector.

=== Add the Connector in Studio

. In Studio, create a Mule Project.
. In the Mule Palette, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type "Workday" in the search field.
. Click the connector name in *Available modules*.
. Click *Add*.
. Click *Finish*.

== Configure an Input Source

Configure an input source for the connector.  Possible input source operations are:

* On New Objects +
Start your app when an object is created in Workday.
* HTTP Listener +
Start your app using a browser or a command such as `curl`.
* Scheduler +
Start your app at timed intervals.

In Studio, drag the input operation you choose from the *Mule Palette* to the *Source* panel in the canvas.

The required fields for the On New Objects input source are:

[%header,cols="30s,70a"]
|===
|Studio Field |Description
|Connector configuration |Global Element Properties configuration name
|Object type |One of: `ABSENCE_INPUTS`, `ACADEMIC_CONTACTS`, `ALL_CURRENCIES`, `APPLICANTS`, `BASIC_CUSTOMERS`, `CANDIDATES`, `CERTIFICATION_ISSUERS`, `CERTIFICATIONS`, `COMPETENCIES`, `DEGREES`, `DONORS`, `EDUCATION_TEST_RESULTS`, `EDUCATIONAL_INSTITUTION_COURSE`, `HEALTH_CARE_RATES`, `INVESTORS`, `ORGANIZATIONS`, `PAYMENTS`, `PROGRAMS_OF_STUDY`, `STUDENTS`, `STUDENTS_APPLICATIONS`, `WORKERS`
|Scheduling Strategy |Configures the scheduler that triggers polling *&#8224;*
|Username |The username to log in with
|Password |The corresponding password
|Tenant Name |The Workday tenant ID, which usually has the suffix `_pt1` appended to it, such as `acme_pt1`
|===

*&#8224;* *Scheduling Strategy* tells the source how it can poll the data. This field accepts two options:

* *Fixed Frequency*
+
Polls for data at a specified number of milliseconds, seconds, minutes, hours, or days. The default is 1000 milliseconds.
* *Cron*
+
Accepts an expression that polls for data based on a filter, such as, every Monday in a month at a given time. See xref:mule-runtime::scheduler-concept.adoc#cron-expressions[Cron Expressions] for examples.

IMPORTANT: To validate connectivity using the Test Connection button, the Workday connector uses an Identity_Management WSDL service with the Get_Workday_Account_Signons_Request operation. Ensure that your service account has permissions to operate on that service. If not, use of Test Connection fails.

== Configure Other Operations

Each Workday operation has its own required fields in Anypoint Studio. For more information, see
the xref:workday-reference.adoc[Connector Reference].

See also xref:workday-connector-config-topics.adoc[Additional Configuration Information].

== Increase Timeout in Studio

Depending on connectivity conditions while using Studio, there can be a timeout while obtaining
metadata from the Workday connector.

=== Symptoms

There can be two types of errors for this condition:

[source,text,linenums]
----
org.mule.runtime.api.exception.MuleRuntimeException: Error while retrieving soap client id [Absence_Management]
  org.mule.runtime.api.exception.MuleRuntimeException: Error while retrieving soap client id [Absence_Management]
  Caused by: java.util.concurrent.ExecutionException:
  org.mule.wsdl.parser.exception.WsdlParsingException: Error processing
  WSDL file [https://wd3-impl-services1.workday.com/ccx/service/deakin_amu1/Absence_Management/v29.1?wsdl]:
  Unable to locate document at 'https://wd3-impl-services1.workday.com/ccx/service/deakin_amu1/Absence_Management/v29.1?wsdl&#39;.
----

Or:

[source,text,linenums]
----
org.mule.tooling.client.api.exception.TimeoutException: Mule Agent REST service timed out
  org.mule.tooling.client.api.exception.TimeoutException: Mule Agent REST service timed out
  javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
  	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:244)
  	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:245)
  	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:671)
  	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:668)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
  	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
  	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:668)
  	at
----

=== Solution

When one of these conditions occurs:

. In Anypoint Studio, navigate to *Preferences* > *Anypoint Studio* > *Tooling*.
. Double the values for `Default Connection Timeout` and `Default Read Timeout`.
. Click *Apply*, and restart Studio.

== Next Step

After configuring Workday Connector in Studio, see the xref:workday-connector-examples.adoc[Examples] for financial management use cases that demonstrate the use of this connector.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
