= B2C Shop Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Salesforce Commerce Cloud B2C Shop APIs (B2C Shop Connector) enables a client to interact with the Commerce Cloud B2C API system as either a shop customer or as an agent shopping on behalf of a customer.

For information about compatibility and fixed issues, see Commerce Cloud B2C Shop Connector Release Notes. 

== Prerequisites

To use this connector, you must be familiar with:

* https://developer.commercecloud.com/s/commerce-api-apis[Salesforce Commerce Cloud Shop API]
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to:

* The Commerce Cloud B2C Shop Connector target resource
* Anypoint Platform
* Anypoint Studio version 7.1 or later
* Salesforce-provided Commerce Cloud credentials (such as Client Id, Client Secret, or Scopes) necessary to access Shop API.

== Common Use Cases for the Connector

These are some common use cases for B2C Shop Connector:

* Create a basket
* Add items to a basket
* Add shipping details 
* Place an order

Check the xref:shop-api-connector-examples.adoc[Examples] for a simple use case.

== Audience

* New user
+
To create your Mule app, see:

* xref:shop-api-connector-studio.adoc[Use Studio to Configure Commerce Cloud B2C Connector]
* xref:shop-api-connector-examples.adoc[Examples], with use case information for the connector
+
* Advanced user
+
* Read the following: 

* xref:shop-api-connector-xml-maven.adoc[XML and Maven Support]
* xref:shop-api-connector-examples.adoc[Examples], with use case information for the connector

== Connection Types

B2C Shop Connector connections can use the following authentication types:

* Customers Auth +
Uses a Bearer Token, which is generated using the *Authorize Customer* operation
* OAuth 2.0 +
Delegates user authentication to the service hosting the user account


For information about configuring authentication types, see xref:shop-api-connector-studio.adoc[Use Studio to Configure Commerce Cloud B2C Shop Connector].

== Next Step

After you complete the prerequisites and try the templates and examples, you are ready to create an app and configure the connector using xref:shop-api-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
