= Troubleshooting Salesforce Marketing Cloud Connector 5.0 

To troubleshoot Anypoint Connector for Salesforce Marketing Cloud (Salesforce Marketing Cloud Connector), become familiar with the information about interpreting commonly thrown exception messages.

include::connectors::partial$ssl-logs.adoc[]

include::connectors::partial$verbose-exception-logs.adoc[]

include::connectors::partial$verbose-logs-com.adoc[]

== Understand Commonly Thrown Exceptions

Here is a list of commonly thrown exception messages and how to interpret them:

* SFDC-MARKETING-CLOUD:CONNECTIVITY

 Either a connection could not be established or there is a connectivity error.

* SFDC-MARKETING-CLOUD:ERROR_RESPONSE

 The external service responds with an error.

* SFDC-MARKETING-CLOUD:INVALID_INPUT

 The provided input data for an operation is not valid.

* SFDC-MARKETING-CLOUD:PARSING

 An error occurs when parsing the input or output data to XML.

* SFDC-MARKETING-CLOUD:RETRY_EXHAUSTED

 The maximum number of retries for the operation is reached.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:salesforce-mktg-connector-reference.adoc[Salesforce Marketing Cloud Connector Reference]
* https://help.salesforce.com[Salesforce Help]
include::release-notes::partial$release-notes/rn-known-issues.adoc[tag=knownIssuesSeeAlsoLink]
