= MSMQ Connector FAQs
:keywords: anypoint studio, esb, connector, endpoint, msmq, microsoft, message queuing
:page-aliases: 3.9@mule-runtime::msmq-connector-faqs.adoc

== Can I send and receive data using this connector?

Yes, this connector can be used as an inbound or outbound endpoint.

== Can this connector be used from a non-Windows platform?

Yes, this connector can be used from a non-Windows platform such as Linux or Unix due to the Anypoint Gateway for Windows that complements the MSMQ connector.

== What is the Anypoint Gateway for Windows?

The Anypoint Gateway for Windows is a lightweight MSMQ API that provides a bridge between the Mule environment and Windows environment. The Anypoint Gateway for Windows must be installed on a Windows Server that has MSMQ messaging installed. It is this gateway that communicates directly with local or MSMQ queues.

== Does the Anypoint Gateway for Windows have to be installed on each MSMQ Server that I want to connect to?

No, the Anypoint Gateway for Windows needs to be installed on a Windows server where the MSMQ messaging component exists, but it does not need to be installed on every MSMQ instance.

== What happens if I am trying to communicate with another application and it uses a specific .NET formatter which cannot be changed?

Using the MSMQ connector in combination with the .NET Connector will help address this issue, because the .NET Connector can include custom or standard .NET formatters. The MSMQ connector can then communicate with MSMQ by using byte arrays that ensure the message stays intact.
