= NetSuite Connector 11.0 - Mule 4
:page-aliases: connectors::netsuite/netsuite-about.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]


Anypoint Connector for NetSuite (NetSuite Connector) synchronizes data and automates business processes between NetSuite and third-party applications, either on-premises or in the cloud. NetSuite provides cloud-based business management software that helps companies manage core business processes, ERP financials, CRM, e-commerce, inventory, and more.

NetSuite Connector provides the following features:

* SOAP-based integration
* Generation of NetSuite business objects 
* Different authentication levels
* Error-handling support 
* Access to NetSuite using REST calls to RESTlets that expose APIs created with SuiteScript

For compatibility information and fixed issues, see the xref:release-notes::connector/netsuite-connector-release-notes-mule-4.adoc[NetSuite Connector Release Notes].

== Prerequisites

To use this connector, you must be familiar with:

* The NetSuite API
* Anypoint connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* How to create a Mule app using Anypoint Studio +
You can also use this connector in Design Center in Anypoint Platform, and as a standalone application developed in XML.

You must also have a NetSuite account with the Web Services features enabled.

== Audience

* New user
+
To create your Mule app, see
xref:netsuite-studio-configure.adoc[Studio Configuration].
* Advanced user
+
** Try the xref:netsuite-examples.adoc[NetSuite examples].
** To develop the connector as a standalone application, see xref:netsuite-connector-xml-maven.adoc[XML and Maven Support].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-netsuite-connector/[NetSuite Connector on Exchange]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:netsuite-reference.adoc[NetSuite Reference]
* https://help.mulesoft.com[MuleSoft Help Center]


