= NetSuite Connector 10.0 - Mule 4
:page-aliases: connectors::netsuite/index.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for NetSuite (NetSuite Connector) synchronizes data and automates business processes between NetSuite and third-party applications, either on-premises or in the cloud. NetSuite provides cloud-based business management software that helps companies manage core business processes, ERP financials, CRM, e-commerce, inventory, and more.

NetSuite Connector provides the following features:

* SOAP-based integration
* Generation of NetSuite business objects
* Different authentication levels
* Error-handling support
* Access to NetSuite using REST calls to RESTlets that expose APIs created with SuiteScript

For compatibility information and fixed issues, see the xref:release-notes::connector/netsuite-connector-release-notes-mule-4.adoc[NetSuite Connector Release Notes].

== Prerequisites

To use this connector, you must be familiar with:

* The NetSuite API
* Anypoint connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access NetSuite Web Services
* Anypoint Studio version 1.1 or later

== Common Use Cases for the Connector

* Quote-to-Cash
+
Improve cash flow, remove manual order entry, and minimize order errors by leveraging real-time integrations to connect and synchronize data about your customer’s intent to buy from your CRM application, such as Salesforce, into its realization of revenue in Netsuite ERP.
+
* Invoice-to-Reconciliation
+
Automate your Accounts Receivable (A/R) process by automatically applying bank payments against invoices in NetSuite for real-time A/R processing. Streamline accounts payable by automating payment file transfers between NetSuite and your banks.
+
Hire-to-Retire
+
Build a single view of your employees with real-time synchronization of employee information between Netsuite and your Human Capital Management (HCM) services, such as Workday, Oracle HCM, PeopleSoft, and so on. Automatically trigger employee on-boarding processes such as ordering computer equipment, uniforms, system access setup, and so on, while reversing the process upon retirement.

== Audience

* New users, read:

** xref:netsuite-studio-configure.adoc[Use Studio to Configure the Connector] to create your Mule app
** xref:netsuite-examples.adoc[Examples], which provide one or more use cases for the connector
* Advanced users, read:
+
** xref:netsuite-connector-xml-maven.adoc[XML and Maven Support]
** xref:netsuite-examples.adoc[Examples], which provides one or more use cases for the connector
** xref:netsuite-connector-xml-maven.adoc[XML and Maven Support]
** xref:netsuite-connector-config-topics.adoc[Additional Configuration Information] to help extend your understanding of NetSuite_Config connector
** xref:netsuite-connector-call-restlets-example.adoc[Call NetSuite RESTlets Example].

For a major or minor release, see
xref:netsuite-connector-upgrade-migrate.adoc[Upgrade to NetSuite Connector 11.x ].

== Authentication types

NetSuite connections use the following authentication types:

* <<request-based-authentication,Request-Based Authentication>>, which xxx
* <<token-authentication,Token Authentication>>. With this type of authentication, client apps use a token to access NetSuite through APIs.

For information about configuring these authentication types, see xref:netsuite-studio-configure.adoc[Use Studio to Configure NetSuite Connector].

== Next Step

After you complete the prerequisites and try the templates and examples, you are ready to create your own app and configure the connector using xref:netsuite-studio-configure.adoc[Use Studio to Configure NetSuite Connector].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-netsuite-connector/[NetSuite Connector on Exchange]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:netsuite-reference.adoc[NetSuite Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
