= Upgrade and Migrate to NetSuite 11.0 - Mule 4

Upgrade NetSuite Connector to version 10.0 to use the new features. 

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|10.0.0 |11.0.0
|===

== New Features in This Release

This release contains the following new features:

* These operations were added: 
** *Get Account Governance Info* 
** *Get Integration Governance Info* 


== Changed Functionality in This Release

This release contains the following changed functionality:

* The Login and SSO authentication types were removed. +
If your integration is based on these authentication types, you must migrate to a Request or Token-Based authentication type.
* Other nonfunctional changes were applied to the interface of the connector to make it more consistent with other Anypoint Connectors. +
This means that some of the operation calls in your existing application might not initially work until some minor migration tasks are performed.
* Unknown errors are now thrown as `ANY` rather than `UNKNOWN`. +
Consequently, error codes `DISPOSE_ERROR`, `MAPPING_ERROR`, `CANT_READ_FILE`, and `TRIGGER` are now considered `ERROR_FAULT` errors instead of `UNKNOWN`.
* The *Map SSO* operation was removed.
* All exposed classes have been moved from the `org.mule.module.netsuite.extension.api` package to the `com.mulesoft.connector.netsuite.extension.api` package.

[[changed_operations]]
== Changed Operations

The behavior of some operations has changed in NetSuite Connector 10.0.

The following operations' parameters no longer default to `payload`:

[%header%autowidth.spread]
|===
|Operation | Parameter

| Change Email a| newEmail
| Change Password a| newPasword
| Get Data Center URLs a| accountId
| Get Async Result a| jobId
| Get Custom Record a| internalId 
|===

The following operations' parameters are now primary content parameters:

[%header%autowidth.spread]
|===
|Operation | Parameter 
| Async Search a| criteria 
| Async Add List a| recordAttributes 
| Async Update List a| recordAttributes 
| Async Upsert List a| recordAttributes
| Update Invitee Status List a| inviteeStatuses 
| Get Posting Transaction Summary | fields 
| Get Posting Transaction Summary | filters
| Add File a| attributes 
| Add Record a| attributes  
| Get Deleted Records a| deletedDate 
| Update Record a| attributes 
| Upsert Record a| attributes 
|===

When a parameter is designated as primary content, if you do not explicitly assign a value to it, it defaults to `payload`. 

For example, the `criteria` parameter for the Async Search operation is now designated as a primary content parameter. This means that if you do not explicitly assign a value to the `criteria` parameter, it defaults to `payload]`.

Additionally, since `criteria` is now a content parameter, you no longer use it like this: +
`<netsuite:async-search config-ref="..." criteria="something">`.

Instead, you must assign it like this: +
----
<netsuite:async-search config-ref="...">
  <netsuite:criteria> something, a DW script, etc </netsuite:criteria>
</netsuite:async-search>
----

[[changed_sources]]
== Changed Sources

The three message sources were renamed:

[%header%autowidth.spread]
|===
|Source name |Old XML name | New XML name

| On New Object | `<netsuite:new-object-trigger` | `<netsuite:new-object-listener`
| On Modified Object |  `<netsuite:modified-trigger` | `<netsuite:modified-listener`
| On Deleted Object | `<netsuite:deleted-trigger` | `<netsuite:deleted-listener`
|===

== Upgrade Steps

If you are upgrading from an earlier version of the connector, you can click the `Updates Available` pop-up message in the bottom right corner of Anypoint Studio and follow the prompts.  

You can also follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In *Mule Palette*, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `netsuite` in the search field.
. In *Available modules*, select *NetSuite* and click *Add*. +
Studio upgrades the connector automatically.
. Click *Finish*.
. In the `pom.xml` file for the Mule project, verify that the NetSuite Connector dependency version is `11.0.0`.

== Post Upgrade Tasks

* Ensure that your configurations are only *Token* authentication.
* Verify that your error handling is updated to work with the minor changes in error codes in this version of the connector.

== Verify the Upgrade (TODO : Check this)

After you install the latest version of the connector, verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Revert the Upgrade (TODO check this)

If you must revert to your previous version of NetSuite Connector, change the `mule-netsuite-connector` dependency version `10.0.0` in the project’s `pom.xml` to the previous version.
Additionally, revert any changes made in the operations to their previous state.

== Setting permissions (TODO : Check this)

Add to the role used for the token authentication provider the following permissions :
. Permissions -> Setup -> SOAP Web Services : Full .
. Permissions -> Setup -> USER Access Tokens : Full .
. Permissions -> Setup -> Control SuiteScript and Workflow Triggers in Web Services Request.

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
