
= Anypoint Connectors Shared Responsibilities

The successful operation of Anypoint Connectors is a shared responsibility between MuleSoft and the customer. It is critical to understand which areas customers are responsible for and which areas MuleSoft is responsible for.

We have created this page as a helpful summary for you to better understand the different responsibilities. However this page is provided for convenience only as all support obligations are subject to your executed agreement with MuleSoft. 


== Anypoint Connectors Categories

Anypoint Connectors fall into these categories:

* *Premium* +
These connectors must be purchased as add-ons to an Anypoint Platform subscription and are available to licensed users only.

* *Select* +  
These connectors are included with a paid MuleSoft subscription. 
+
Select and Premium connectors can further be categorized  as:
+
  ** *Connectors or modules that enable connectivity to MuleSoft or Salesforce applications* + 
  For example, Salesforce Marketing Cloud Connector or Anypoint MQ Connector.

  ** *Connectors that enable the use of cross-platform protocols or open APIs* + 
  For example, Database Connector, which is based on Oracle’s JDBC protocol.

  ** *Connectors that enable connectivity to third-party or partner APIs* +
  For example, Azure Key Vault Connector or Stripe Connector.

* *MuleSoft Certified* +
Connectors developed by MuleSoft’s partners and subsequently reviewed and certified by MuleSoft, for example, ESRI Connector. For these connectors, MuleSoft takes initial support calls and isolates the issue for resolution. MuleSoft disclaims any additional support obligation for MuleSoft Certified Connectors. For additional support of MuleSoft Certified Connectors, contact the MuleSoft partner who created the connector.

* *Community* +
Connectors developed by the MuleSoft developer community. For example, Slack Connector - Mule 3.

== Shared Responsibilities

The following table clarifies the responsibilities that customers and MuleSoft share for Anypoint Connectors:

[%header%autowidth.spread]
|===
| Type of Connector | MuleSoft Responsibilities | Customer Responsibilities 
a|Premium or Select: Connectors or modules that enable connectivity to MuleSoft or Salesforce applications. + 

For example: +

* Salesforce Marketing Cloud Connector
* Anypoint MQ Connector
 | Support for the connector source code and the functionalities that the connector provides. a| * Ensure that the connector versions and Mule runtime engine (Mule) versions are up to date with the latest version released by MuleSoft.
* Grant roles and permissions for access to resources.
* Check the shared libraries, plugin dependencies, configuration files, templates, scripts, proxies, and network configuration.
* Check the third-party driver limitations, load balancing, parallel processing, and authentication protocols.
* Check performance issues in destination servers and partner applications.
 
a| Premium or Select Connectors: Connectors that enable the use of cross-platform protocols or open APIs. +


For example: +

* Database Connector
* JMS Connector 
* SFTP Connector 
* X12 Connector 
* EDIFACT Connector 
* TRADACOMS EDI Connector

a| * Support for the connector source code, its packaged libraries, and the functionalities the connector provides. +

*  MuleSoft incorporates specific industry-standard message specifications into these connectors, but  is not responsible for the partner system or domain technology configuration.

 a| * Ensure that the connector and Mule runtime engine (Mule) versions are updated with the latest version released by MuleSoft.
* Grant roles and permissions for access to resources.
* Check the shared libraries, plugin dependencies, configuration files, templates, scripts, proxies, and network configuration.
* Check the third-party driver limitations, load balancing, parallel processing, and authentication protocols.
* Check performance issues in destination servers and partner applications.
* Check with the partner their system or domain configuration, and technology, for example database and JMS broker administration. 
a| Premium or Select Connectors: Connectors that enable connectivity to third-party or partner APIs. +

For example: +

* Stripe Connector
* Azure Key Vault Connector
a| * Support for the connector source code, connector packaged libraries, and the functionalities the connector provides. 

* MuleSoft is not responsible for specific third-party SDK libraries.  MuleSoft uses APIs provided by the partner, but it is not responsible for these third-party provider configurations and does not provide assistance with issues related to the drivers or APIs that the connector uses in the background. For underlying third-party configuration or issues, contact the third-party provider directly.
a| * Ensure that the connector version and Mule version are up to date with the latest version released by MuleSoft.
* Implement the driver of your choice to configure third-party SDK libraries.
* Review the third-party API specification documentation for configuration information.
* Grant roles and permissions for access to resources.
* Check the shared libraries, plugin dependencies, configuration files, templates, scripts, proxies, and network configuration.
* Check the third-party driver limitations, load balancing, parallel processing, and authentication protocols.
* Check the performance issues in destination servers and partner applications.
* Check with the third-party or partner who provides security updates and apply modifications to the underlying endpoints. Third parties and partners can assist with using third-party APIs and drivers and with configuring SDK libraries.| 
|===

== See Also

* https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Product Versioning and Back Support Policy]
