
= Anypoint Connectors Shared Responsibilities

The successful operation of Anypoint Connectors is a shared responsibility between MuleSoft and the customer. It is critical to understand which areas customers are responsible for and which areas MuleSoft is responsible for.

== Anypoint Connectors Categories

Anypoint Connectors fall into these categories:

* Connectors that enable the use of cross-platform protocols or open APIs. 
+
For example, Database Connector, which is based on Oracle’s JDBC protocol.

* Connectors or modules that enable connectivity to MuleSoft or Salesforce applications. 
+
For example, Salesforce Marketing Cloud Connector and Anypoint MQ Connector.

* Connectors that enable connectivity to third-party or partner APIs. 
+
For example, Azure Key Vault Connector and Stripe Connector.

* Connectors developed by MuleSoft’s partners and subsequently reviewed and certified by MuleSoft.
+
For example ESRI Connector (in Anypoint Exchange identify them as MuleSoft Partner).

* Connectors developed by MuleSoft developer community and subsequently reviewed and certified by MuleSoft.
+
For example, Slack Connector - Mule 3 (in Anypoint Exchange identify them as Open-Source Community).

== Third-party Providers and Partners

Additionally, there are third-party providers and partners:

* Third-party providers +
These entities, which are external to the MuleSoft organization, provide and develop libraries or drivers that you add and configure for the operation of the connector under certain circumstances. MuleSoft does not include these libraries and drivers in the connector source code. 
+
For example, some connectors ( such as Database Connector) use a common protocol, JDBC, for connecting to a database. There are several vendor-provided JDBC drivers. You can select which JDBC driver to use for connecting to a specific vendor’s database.
+

* Partners +
MuleSoft partners develop MuleSoft Certified Connectors. They assist with partner systems, domain configuration, technology, and connector configuration.

== Shared Responsibilities

The following table describes the responsibilities that customers, third-party providers, partners, and MuleSoft share for Anypoint Connectors.

[%header%autowidth.spread]
|===
| Type of Connector | MuleSoft Responsibilities | Customer Responsibilities | Third-party Responsibilities | Partner Responsibilities
a|Connectors for cross-platform protocols or open APIs. For example:

* Database Connector
* JMS Connector 
* SFTP Connector 
* X12 Connector 
* EDIFACT Connector 
* TRADACOMS EDI Connector | Support for the connector source code, its packaged libraries, and the functionalities the connector provides. +

MuleSoft incorporates specific industry-standard message specifications into these connectors, but it is not responsible for the partner system or domain technology configuration.
a| * Ensure that the connector and Mule runtime engine (Mule) versions are updated with the latest version released by MuleSoft.
* Grant roles and permissions for access to resources.
* Check the shared libraries, plugin dependencies, configuration files, templates, scripts, proxies, and network configuration.
* Check the third-party driver limitations, load balancing, parallel processing, and authentication protocols.
* Check performance issues in destination servers and partner applications.| |Assist with partner system or domain configuration, and technology, for example database and JMS broker administration.
a| Connectors and modules for MuleSoft or Salesforce applications. For example: +

* Salesforce Marketing Cloud Connector
* Anypoint MQ Connector
| Support for the connector source code and the functionalities the connector provides.
 a| * Ensure that the connector versions and Mule runtime engine (Mule) versions are up to date with the latest version released by MuleSoft.
* Grant roles and permissions for access to resources.
* Check the shared libraries, plugin dependencies, configuration files, templates, scripts, proxies, and network configuration.
* Check the third-party driver limitations, load balancing, parallel processing, and authentication protocols.
* Check performance issues in destination servers and partner applications.
 | |
a| Connectors for third-party or partner APIs. For example: +

* Stripe Connector
* Azure Key Vault Connector
| Support for the connector source code, connector packaged libraries, and the functionalities the connector provides. +

MuleSoft  is not responsible for specific third-party SDK libraries.  
MuleSoft uses APIs provided by the partner, but it is not responsible for these third-party provider configurations and does not provide assistance with issues related to the drivers or APIs that the connector uses in the background.
{sp}+
{sp}+
For underlying third-party configuration or issues, contact the third-party provider directly.
a| * Ensure that the connector version and Mule version are up to date with the latest version released by MuleSoft.
* Implement the driver of your choice to configure third-party SDK libraries.
* Review third-party API specification documentation for configuration information.
* Grant roles and permissions for access to resources.
* Check the shared libraries, plugin dependencies, configuration files, templates, scripts, proxies, and network configuration.
* Check the third-party driver limitations, load balancing, parallel processing, and authentication protocols.
* Check the performance issues in destination servers and partner applications.
 a| * Provide security updates and apply modifications to the underlying endpoints. +
* Assist with using third-party APIs, using drivers and configuring SDK libraries.
  |
| MuleSoft Certified Connectors| MuleSoft supports initial calls and isolates the issue for resolution. MuleSoft disclaims any additional support obligation for MuleSoft Certified Connectors. For MuleSoft Certified Connectors support, contact the MuleSoft partner that created the connector.
 | For support, contact the MuleSoft partner that created the connector. |  | Provide assistance with the partner connector configuration or issue.
| Community Connectors| Support for troubleshooting the connector to ensure that all licensed components of the platform are working as designed. 
{sp}+
{sp}+
If the Community Connector is the source of the issue and assistance is required to modify or alter the connector, you can engage with MuleSoft Professional Services or an accredited MuleSoft Partner by contacting their MuleSoft Account Manager. | For initial support, contact MuleSoft Customer Support. |  |
|===

== See Also

* https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Product Versioning and Back Support Policy].
