= Upgrading and Migrating FTP Connector to Version 2.0  - Mule 4

Upgrade Anypoint Connector for FTP (FTP Connector) to version 2.x.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|1.8.x |2.0.x
|===

== Changes in This Release

This release contains the following changes:

* The `mule-file-commons` module dependency is removed to make FTP Connector a standalone connector. 
* The *List* operation now returns the file path instead of the file content. 

== Requirements

Ensure that you meet these requirements before you perform the upgrade:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule |4.3.0 and later
|===

== Upgrade Prerequisites

Before you perform the upgrade, create a backup of your files, data, and configuration in case you need to restore to the previous version.

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In *Mule Palette*, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `ftp` in the search field.
. In *Available modules*, select *FTP* and click *Add*.
. Click *Finish*.
. Verify that the FTP Connector dependency version is 2.0 in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

== Post-Upgrade Steps

After you install the latest version of the connector, verify that your error handling is updated to work with the minor changes in error codes in this version of the connector.

== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Revert the Upgrade

If it is necessary to revert to the previous version of FTP Connector, change the `mule-ftp-connector` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
