= Azure Key Vault Connector 1.1 - Mule 4

Anypoint Connector for Azure Key Vault (Azure Key Vault Connector) enables you to retrieve secrets, keys, or certificates, and encrypt or decrypt content.

For information about compatibility and fixed issues, refer to the Azure Key Vault Connector Release Notes.

== Before You Begin

To use this connector, you must be familiar with:

* The Azure Key Vault Secrets API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Azure Key Vault target resource
* Anypoint Platform
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Some common use cases for Azure Key Vault Connector include:

* Authenticating to Azure Key Vault via Client Secret Credential to access Key Vault secrets without exposing sensitive credentials in code, thus improving resilience and security
* Enabling other applications in a Mule flow to have access to encrypt and decrypt operations using Azure Key Vault keys to avoid key rotations
* Authenticating to other database and HTTP connectors in a more secure and automated way to fetch and use credentials to access other endpoints
* Retrieving a certificate and saving the certificate into a file

== Connection Types

Azure Key Vault connections use the Connection authentication type, which uses a client ID, client secret, and cryptography client cache.

== Environment Variables

When setting *Use Azure Default Credential* to `True`, you must set one of the following environment variables `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET`, or `AZURE_TENANT_ID`. Refer to xref:mule-runtime::setting-environment-variables.adoc[Setting environment variables] documentation for details.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:azure-key-vault-connector-reference.adoc[Azure Key Vault Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
