= Configuring Agent Operations for Einstein AI Connector 1.1

== Configure the Agent Define Prompt Template Operation

Use the *Agent define prompt template* operation to define specific prompt templates for use when integrating with the LLM of your choice. This allows you to create natural language prompts that generate responses, extract information, invoke other prompts, or perform any text-based task.

include::connectors::partial$t-configure-operations.adoc[]
* *Template*
+
Enter the prompt template for the operation.
* *Instructions*
+
Provide the instructions for the LLM, outlining the goals of the task.
* *Dataset*
+
Specify the dataset for the LLM to evaluate using the provided template and instructions.
include::connectors::partial$einstein-ai-chat-config-properties-partial.adoc[]

This is the XML for this operation:

[source,xml,linenums, subs=attributes+]
----
<ms-einstein-ai:agent-define-prompt-template 
  doc:name="Agent define prompt template" 
  doc:id="f1c29c39-eac9-468c-9c46-4109a66303ec" 
  config-ref="Einstein_AI" 
  template="#[payload.template]" 
  instructions="#[payload.instructions]" 
  dataset="#[payload.dataset]"
/>
----

=== Output Configuration

This operation responds with a JSON payload containing the main LLM response. Additionally, attributes such as token usage are included as part of the metadata (attributes) but not within the main payload. This additional metadata is particularly useful to track token usage across applications and manage costs associated with LLM adoption.

This is an example response:

[source,json]
----
{
  "response": "{\n  \"type\": \"positive\",\n  \"response\": \"Thank you for your positive feedback on the training last week. We are glad to hear that you had a great experience. Have a nice day!\"\n}"
}
----

The operation also returns attributes that aren't within the main JSON payload, which include information about token usage, for example:

[source,json]
----
{
  "tokenUsage": {
      "outputCount": 9, 
      "totalCount": 18, 
      "inputCount": 9 
  },
  "additionalAttributes": {}
}
----

* `tokenUsage` 
+
Token usage metadata returned as attributes
* `outputCount` 
+
Number of tokens used to generate the output
* `totalCount` 
+
Total number of tokens used for input and output
* `inputCount` 
+
Number of tokens used to process the input


== See Also

* xref:connectors::introduction/intro-config-use-acb.adoc[]
* xref:connectors::introduction/intro-config-use-studio.adoc[Using Studio to Configure a Connector]
* xref:einstein-ai-connector-reference.adoc[Einstein AI Connector Reference]
* xref:einstein-ai-additional-config.adoc[Einstein AI - Additional Configuration Information]
* https://help.salesforce.com[Salesforce Help]

