= Configuring Chat Operations for Einstein AI Connector 1.1

== Configure the Chat Answer Prompt Operation

The *Chat answer prompt* operation sends a request to the configured LLM. This operation uses a plain text prompt as input and responds with a plain text answer.

. Select the operation on the Anypoint Code Builder or Studio canvas.
. In the *General* properties tab for the operation, enter plain text for the *Prompt*.
include::connectors::partial$einstein-ai-chat-config-properties-partial.adoc[]

This is the XML configuration for this operation:

[source,xml]
----
<ms-einstein-ai:chat-answer-prompt 
  doc:name="Chat answer prompt" 
  doc:id="66426c0e-5626-4dfa-88ef-b09f77577261" 
  config-ref="Einstein_AI" 
  prompt="#[payload.prompt]"
/>
----

== Configure the Chat Generate from Messages Operation

The *Chat generate from messages* operation is a prompt request operation to the configured LLM, with provided messages. This operation accepts multiple messages and uses a plain text prompt as input. The operation responds with a plain text answer.

. Select the operation on the Anypoint Code Builder or Studio canvas.
. In the *General* properties tab for the operation, enter plain text for the *Messages*.
include::connectors::partial$einstein-ai-chat-config-properties-partial.adoc[]

This is the configuration XML for this operation:

[source,xml]
----
<ms-einstein-ai:chat-generate-from-messages 
  doc:name="Chat generate from messages" 
  doc:id="94fa27f3-18ce-436c-8a5f-10b8dbfa4ea3" 
  config-ref="Einstein_AI" 
  messages="#[payload.messages]"
/>
----



== See Also

* xref:connectors::introduction/intro-config-use-acb.adoc[]
* xref:index.adoc[Einstein AI Connector Overview]
* xref:einstein-ai-connector-reference.adoc[Einstein AI Connector Reference]
* https://help.salesforce.com[Salesforce Help]
