= Salesforce Data Cloud - Additional Configuration Information - Mule 4

Configure Anypoint Connector for Salesforce Data Cloud (Salesforce Data Cloud Connector) to generate an OAuth 2.0 keystore file.

[[generate-keystore]]
== Generate a Keystore File

Salesforce Data Cloud Connector uses the Bouncy Castle cryptographic library to load the certificate from the keystore and sign the payload for the authentication requests.

The Bouncy Castle library has a https://nvd.nist.gov/vuln/detail/CVE-2018-5382[vulnerability (CVE-2018-5382)] that relates to the BKS-V1 keystore file type, so do not use BKS-V1 keystore files, as documented in the https://www.kb.cert.org/vuls/id/306792[Bouncy Castle proposed solution]. By default, Salesforce Data Cloud Connector uses JKS or PKCS12 keystores.

To generate a JKS keystore file:

. Go to your Mule workspace and open the command prompt (for Windows) or Terminal (for Mac).
. Enter this command:
+
[source]
----
keytool -genkeypair -alias salesforce-cert -keyalg RSA -keystore salesforce-cert.jks
----
+
. Enter the following information:
+
** Password for the keystore
** Your first name and last name
** Your organization unit
** Your city and state, and the two-letter code for your country
+
The system generates a Java keystore file (JKS format) that contains a private or public key pair in your workspace.
+
. Provide the file path for the keystore in your connector configuration.
+
Enter this command:
+
[source]
----
keytool -exportcert -alias salesforce-cert -file salesforce-cert.crt -keystore salesforce-cert.jks
----
+
The system exports the public key from the keystore into the workspace. This is the public key to enter in your Salesforce instance.
+
. Verify that you have both the keystore (`salesforce-cert.jks`) and the public key (`salesforce-cert.crt`) files in your workspace.


== Next Step

After you complete configuring the connector, you can try the xref:salesforce-data-cloud-connector-examples.adoc[Examples].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
