= Web Service Consumer Connector 1.6 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Web Service Consumer (Web Service Consumer Connector) consumes a SOAP web service from a Mule app to acquire data from an external source. In many cases, you can use Anypoint Connector for Workday (Workday Connector) or Anypoint Connector for ServiceNow (ServiceNow Connector) to connect to a service provider, however, when no connector is available for a specific web service, the easiest way to consume the service is to use the Web Service Consumer Connector.

The main features of the connector include:

* Ability to consume DOC literal web services
* Use of SOAP multipart messages
* Use of SOAP headers
* Support for a DataSense for SOAP headers, SOAP body, and attachments
* Use of embedded DataWeave transformations inside the operation
* Support for a unified experience for SOAP with attachments and MTOM handling
* Custom HTTP configuration as a transport
* Support for Web Service Security (WS Security)

[NOTE]
Web Service Consumer Connector doesn't support RPC WSDLs (Remote procedure call Web Service Descripting Language).


== Prerequisites

To use this connector, you must be familiar with:

* SOAP and WSDLs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* DataWeave
* Creating a Mule app using Design Center or Anypoint Studio

Before creating an app, you must have access to Anypoint Studio.


== Audience

* New user, read:
** xref:web-service-consumer-studio.adoc[Studio Configuration]
** xref:web-service-consumer-config-topics.adoc[Additional Configuration Information]
to help extend your understanding of the Web Service Consumer Connector
** xref:web-service-consumer-examples.adoc[Examples], which provides one or more use cases for the connector

* Advanced user, read:
** xref:web-service-consumer-xml-maven.adoc[XML and Maven Support]
** xref:web-service-consumer-config-topics.adoc[Additional Configuration Information]
** xref:web-service-consumer-examples.adoc[Examples], which provides one or more use cases for the connector


== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app and configure the connector using xref:web-service-consumer-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://anypoint.mulesoft.com/exchange/org.mule.connectors/mule-wsc-connector/[Web Service Consumer in Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
