= Troubleshoot Web Service Consumer
This page contains common troubleshooting suggestions for Anypoint Connector for Web Service Consumer(Web Service Consumer Connector).

[[generic-issues]]
== Troubleshoot Generic Issues
You can find here a listing of the most common Web Service Consumer generic issues and how to overcome them.
//Create an unordered list of common generic issues for the connector/component.

*<<enable-wire-logging, Enable Wire Logging>>.

[[enable-wire-logging]]
=== How to Enable Wire Logging
//Include an introduction to explain what the issue is about, for example, when you <do this>, you receive <this output> and <this> happens.
// Try to include as much information as possible about how the error is generated, and where it is generated. Provide the actual error string, if possible. If the error is generated in a particular component of the product, clearly mention that as well.

Sometimes when troubleshooting, it is helpful to look at the transport request and response on the Web Service Consumer.
When you are using the underlying HTTP transport, you can enable wire logging so that you can see what the exact HTTP message is, the headers used in the transmission and the status of the response.

To enable Wire Logging:
// Include information about how to fix the issue only no other explanation that belongs in the intro section.

. Find your log4j2.xml inside resources path's of your application.
. Add or uncomment this line.

[source,xml,linenums]
<AsyncLogger name="org.mule.service.http.impl.service.HttpMessageLogger" level="DEBUG" />

Now you can read the HTTP messages in the mule's logger.

// TODO: This must be in the same text block
[source,plain-text]
POST /essentials/delta HTTP/1.1
soapaction:
Host: ilt.mulesoft-training.com
User-Agent: AHC/1.0
Connection: keep-alive
Accept: */*
Content-Type: text/xml; charset=UTF-8
Transfer-Encoding: chunked

b1
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns0:listAllFlights xmlns:ns0="http://soap.training.mulesoft.com/"/></soap:Body></soap:Envelope>

DEBUG 2021-04-06 15:04:23,058 [[wsc-base].wsc-dispatcher.11 SelectorRunner] [processor: ; event: ] org.mule.service.http.impl.service.HttpMessageLogger.wsc-dispatcher: REQUESTER
0


DEBUG 2021-04-06 15:04:23,319 [[wsc-base].wsc-dispatcher.11 SelectorRunner] [processor: ; event: ] org.mule.service.http.impl.service.HttpMessageLogger.wsc-dispatcher: REQUESTER
HTTP/1.1 200
Date: Tue, 06 Apr 2021 18:04:23 GMT
Content-Type: text/xml; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
MULE_ENCODING: UTF-8
Strict-Transport-Security: max-age=31536000; includeSubdomains;
X-Content-Type-Options: 1
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

bfe
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:listAllFlightsResponse xmlns:ns2="http://soap.training.mulesoft.com/">...


[common-errors]]
== Troubleshoot Common Errors
You can find here a listing of the most common Web Service Consumer errors and how to overcome them.
//Create an unordered list of the connector common errors.

*<<attachments-position, Can't access response attachments>>.
*<<design-time-wsdl-parsing, Design time WSDL issues>>.

[[attachments-position]]
=== Can't access attachments.

Some servers can respond with MTOM messages.
These messages are characterized by having the data separated into parts within the same http message, in this way data of different content types can coexist in the same http message.
MTOM in particular in charge of sending binary data in a separate part and referencing it from the corresponding field within the soap envelope.
Wsc users will interact with this kind of messages (multipart) only with the MTOM configuration, This is not to say that MTOM, XOP, and MIME / multipart are the same.

Please refer to the following documentation for further information.

https://www.ietf.org/rfc/rfc2387.txt[RFC2387 - The MIME Multipart/Related Content-type]

https://www.w3.org/TR/2005/REC-xop10-20050125/[XML-binary Optimized Packaging (XOP) W3C Recommendation]

https://www.w3.org/TR/soap12-mtom/[SOAP Message Transmission Optimization Mechanism (MTOM)
W3C Recommendation]


Since 1.6.4, WSC allows the user to configure MTOM for request messages, but it automatically handles MTOM responses regardless of the MTOM setting in the wsc configuration. This means that incoming messages with MTOM will be treated as MTOM enabled regardless of whether or not MTOM is enabled in wsc configuration.

[source,xml,linenums]
<wsc:config name="Web_Service_Consumer_Config" doc:name="Web Service Consumer Config">
    <wsc:connection wsdlLocation="http://ilt.mulesoft-training.com/essentials/delta?wsdl" service="TicketServiceService" port="TicketServicePort" address="http://ilt.mulesoft-training.com/essentials/delta" mtomEnabled="true">
        <wsc:web-service-security actor="http://schemas.xmlsoap.org/soap/actor/next" />
    </wsc:connection>
</wsc:config>

Depending on server side multipart setting, it may decide to send some binary data as a base64-encoded text field or as a referenced binary part in the MIME message.

If the former is the case, users must access this field as part of the message, base64 decoding is not needed, wsc will do it by itself.
But if the case is the second, the user must access this field as an attachment.

In the following example, an image that was sent as an attachment with MTOM by the ws server, is accessed and transformed into json.
In this case, Base64 encoding is required.

[source,text-plane,linenums]
import * from dw::core::Strings
import dw::core::Binaries
output application/json
ns nam http://mynamespace.com
---
{
...
"image": Binaries::toBase64(payload.attachments[0]),
...
}

[[design-time-wsdl-parsing]]
=== Design time WSDL issues.

Some errors related to incorrect wsdl recognition, acquisition, or parsing may lead to some of the following issues.

. DataSense does not correctly expose the message metadata defined in wsdl.
. No operations are displayed in the operations combo box.
. During WSC configuration service, port and address are not automatically filled when a WSDL location is selected.

To resolve this issue:

. Check the integrity of your wsdl, there are both online and desktop applications to do this. By now every parsing error during configuration it not shown at design time, so an external application is needed.
. If the WSDL is not added as a resource in the application resource/api folder, check for a correct connection to the server hosting the WSDL.
Sometimes you need to add custom HTTP settings to access an HTTP server in an HTTP security layer, such as OAuth settings or user/password settings. See xref:web-service-consumer-configure.adoc[Setting a Custom HTTP Transport Configuration.]


[[common-throws]]
== Understand Common Throws

* WSC:SOAP_FAULT

  Error matching the soap response whith the format provided by the wsdl.
  Every cxf SoapFault error is wrpped in a WSC:SOAP_FAULT.

* WSC:BAD_REQUST

  Operation does not exist in WSDL.
  The request body is not a valid XML.

* WSC:INVALID_WSDL

  Bad formated WSDL.


== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:Web Service Consumer-reference.adoc[Connector Reference]
