= Troubleshoot Web Service Consumer
This page contains common troubleshooting suggestions for Anypoint Connector for Web Service Consumer(Web Service Consumer Connector).

[[generic-issues]]
== Troubleshoot Generic Issues
You can find here a listing of the most common Web Service Consumer generic issues and how to overcome them.
//Create an unordered list of common generic issues for the connector/component.

*<<enable-wire-logging, Enable Wire Logging>>.

[[enable-wire-logging]]
=== How to Enable Wire Logging
//Include an introduction to explain what the issue is about, for example, when you <do this>, you receive <this output> and <this> happens.
// Try to include as much information as possible about how the error is generated, and where it is generated. Provide the actual error string, if possible. If the error is generated in a particular component of the product, clearly mention that as well.

Sometimes when troubleshooting, it is helpful to look at the transport request and response on the Web Service Consumer.
When you are using the underlying HTTP transport, you can enable wire logging so that you can see what the exact HTTP message is, the headers used in the transmission and the status of the response.

To enable Wire Logging:
// Include information about how to fix the issue only no other explanation that belongs in the intro section.

. Find your log4j2.xml inside resourses path's of your application.
[source,xml,linenums]
<!--AsyncLogger name="org.mule.service.http.impl.service.HttpMessageLogger" level="DEBUG" /-->
<AsyncLogger name="org.mule.service.http" level="WARN"/>
<AsyncLogger name="org.mule.extension.http" level="WARN"/>

. Uncomment the first line.
[source,xml,linenums]
<AsyncLogger name="org.mule.service.http.impl.service.HttpMessageLogger" level="DEBUG" />
<AsyncLogger name="org.mule.service.http" level="DEBUG"/>
<AsyncLogger name="org.mule.extension.http" level="DEBUG"/>

now you can read the HTTP messages in the mule's logger.

// TODO: Example of http message in the logger.



[common-errors]]
== Troubleshoot Common Errors
You can find here a listing of the most common Web Service Consumer errors and how to overcome them.
//Create an unordered list of the connector common errors.

*<<attachments-position, Can't access response attachments>>.
*<<design-time-wsdl-parsing, Design time WSDL issues>>.

[[attachments-position]]
=== Can't access attachments.

Some servers can respond with multi-part messages.
When we refer to multipart in WSC, we mean MTOM, as far as this guide is concerned, MTOM, XOP, and multipart / MIME will be the same. (But they are not)
Please refer to the following documentation for further information.

https://www.ietf.org/rfc/rfc2387.txt[RFC2387 - The MIME Multipart/Related Content-type]

https://www.w3.org/TR/2005/REC-xop10-20050125/[XML-binary Optimized Packaging (XOP) W3C Recommendation]

https://www.w3.org/TR/soap12-mtom/[SOAP Message Transmission Optimization Mechanism (MTOM)
W3C Recommendation]


Since 1.6.4, WSC allows the user to configure multipart requests, but it automatically handles multipart responses regardless of multipart settings in wsc configuration.
// TODO: Multipart config picture

Depending on server side multipart setting, it may decide to send some binary data as a base64-encoded text field or as a referenced binary part in the MIME message.

If the former is the case, users must access this field as part of the message, base64 decoding is not needed, wsc will do it by itself.
// TODO: Example without mtom

But if the case is the second, user must access this field as an attachment.
// TODO: Example with mtom

[[design-time-wsdl-parsing]]
=== Design time WSDL issues.

Some errors related to incorrect wsdl recognition, acquisition, or parsing may lead to some of the following issues.

. Intellisense does not correctly expose the messages' metadata defined in the wsdl.
. No operations are displayed in the operations' combo box.
. During WSC configuration service, port and address are not automatically filled when a WSDL location is selected.

To resolve this issue:

. Check the integrity of your wsdl, there are both online and desktop applications to do this. By now every parsing error during configuration it not shown at design time, so an external application is needed.
. If the WSDL is not added as a resource in the application resource/api folder, check for a correct connection to the server hosting the WSDL.
Sometimes you need to add custom HTTP settings to access an HTTP server in an HTTP security layer, such as OAuth settings or user/password settings. See xref:web-service-consumer-configure.adoc[Setting a Custom HTTP Transport Configuration.]


[[common-throws]]
== Understand Common Throws
//Include the list of throws messages and a simple description of what they mean.

* <Throw message/error>

  <Description of the thrown message>.

* <Throw message/error>

  <Description of the thrown message>.
.
.
.

== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:Web Service Consumer-reference.adoc[Connector Reference]
