= Troubleshooting Amazon S3 Connector 6.3 - Mule 4

To troubleshoot Anypoint Connector for Amazon S3 (Amazon S3 Connector), become familiar with the information about interpreting commonly thrown exception messages.

include::connectors::partial$ssl-logs.adoc[]

include::connectors::partial$verbose-exception-logs.adoc[]

include::connectors::partial$verbose-logs-org.adoc[]

== Understand Commonly Thrown Exceptions

Here is a list of commonly thrown exception messages and how to interpret them:

* S3:BAD_REQUEST

 The input or payload is invalid.

* S3:BUCKET_ALREADY_EXISTS

 The bucket name you specify already exists.

* S3:BUCKET_ALREADY_OWNED_BY_YOU

 The bucket you create already exists and is owned by you.

* S3:CONNECTIVITY

 A connection cannot be established.

* S3:FORBIDDEN

 There is a `403` forbidden error, for example, there are missing permissions.

* S3:GLACIER_EXPEDITED_RETRIEVAL_NOT_AVAILABLE

 Expedited retrieval is not available.

* S3:INTERNAL_ERROR

 There is an internal error, such as a server issue or a temporary glitch.

* S3:INVALID_OBJECT_STATE

 The object state is invalid with the action.

* S3:MALFORMED_XML

 The XML you send is malformed.

* S3:NO_SUCH_KEY

 The key you specify does not exist.

* S3:NO_SUCH_LIFECYCLE_CONFIGURATION

 The lifecycle configuration you specify does not exist.

* S3:NO_SUCH_TAG_SET

 The tag set you specify does not exist.

* S3:NO_SUCH_UPLOAD

 The upload you specify does not exist.

* S3:OBJECT_ALREADY_IN_ACTIVE_TIER

 The object is already in the active tier.

* S3:OPERATION_ABORTED

 The operation is aborted because there is another in-progress action against the same resource.

* S3:RESTORE_ALREADY_IN_PROGRESS

 The restore is already in progress.

* S3:RETRY_EXHAUSTED

 The maximum number of retries for the operation is reached.

* S3:S3_ERROR

 An error occurs in Amazon S3.

* S3:SERVER_BUSY

 The server is busy.

* S3:SERVICE_ERROR

 There is a service error.

* S3:REQUEST_TIMEOUT

 The Put Object operation had a request timeout.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:amazon-s3-connector-reference.adoc[Amazon S3 Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
* https://issues.salesforce.com/[Known Issues]
