= Scripting Module 2.0 - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: connectors::scripting/scripting-module.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Scripting module executes custom logic written in a scripting language. In some cases, you might need to create custom code to perform all or part of a complex task, or to reuse modules that you have already written.
Starting with Scripting module version 2.0, you must provide a compliant `jsr-223` scripting language engine.


== Prerequisites

To use this module, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* Creating a Mule app using Design Center or Anypoint Studio

Before creating an app, you must have access to Anypoint Platform.


== Common Use Cases for the Module

Scripting module performs logic in a supported language, which enables you to access variables and the registry, log information via the Mule logger, read payloads, and so on.

For examples, see xref:scripting-module-examples.adoc[Examples].

== Audience

* New user
+
To create your Mule app, see:

* xref:scripting-module-studio.adoc[Studio Configuration]
* xref:scripting-module-examples.adoc[Examples], which provides one or more use cases for the connector


* Advanced user
+
Read the following:

* xref:scripting-module-xml-maven.adoc[XML and Maven Support]
* xref:scripting-module-examples.adoc[Examples] topics

For a major or minor release, see
xref:scripting-module-upgrade-migrate.adoc[Upgrade and Migrate].


== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app and configure the connector using xref:scripting-module-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://www.mulesoft.com/exchange/?search=scripting-module&type=connector[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
