= Troubleshooting the Scripting Module - Mule 4

To troubleshoot the Scripting Module, become familiar with the information about enabling verbose logging and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with the Scripting module is failing, temporarily enable verbose logging for the module. +

Remember to always disable the enhanced verbosity after troubleshooting, because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="org.mule.plugin.scripting" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Title for general troubleshooting A

////
Include an introduction to explain what the generic troubleshooting is about, for example, when you <do this>, you receive <this output> and <this> happens.

Try to include as much information as possible about how and where the issue is generated. Provide the actual error string, if possible. If the issue is generated in a particular component of the product, clearly state that as well. If there are unexpected consequences of performing a particular troubleshooting resolution (all your connections will break, monitoring will do X, or whatever), explain what they are.

Use the following template for up to three general troubleshooting guidelines or errors.
////

To resolve this issue/workaround:
// Include information about how to fix the issue only. Other explanation belongs in the intro section.
1. Do this...
2. Do this...
3. Do this...
.
.



== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* SCRIPTING:COMPILATION

 The content of the property code had problems in the compilation stage. Check that your code is valid and export the classes used with the Scripting module.

* SCRIPTING:UNKNOWN_ENGINE

 The engine name provided in the engine parameter is unknown.

* SCRIPTING:EXECUTION

 An exception occurred during the execution stage. Set the log level in DEBUG mode and find more information in the log file.

== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:scripting-reference.adoc[Scripting Module Reference]
