= Google Calendar Connector 1.1

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Google Calendar (Google Calendar Connector) synchronizes data and automates business processes between Google Calendar and third-party applications, either on-premises or in the cloud.

Google Calendar is a calendar and task planning application that focusses on enhancing personal and team productivity. Using Google Calendar, individuals can easily schedule tasks and meetings. They can also share events with colleagues through an easy-to-use calendar interface.

For compatibility information and fixed issues, see the Google Calendar Connector Release Notes.

== Prerequisites

To use this connector, you should be familiar with:

* The Google Calendar API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access Google Calendar
* Anypoint Studio version 4.2.1 or later

== Common Use Cases for the Connectors

Common use cases for Google Calendar Connector include the following:

* Improve scheduling efficiency

Remove the manual effort of scheduling events that are part of established processes. For example, you can create a 15-minute triage meeting automatically whenever a high-severity customer issue is received.

* Enhance employee productivity

Sync event details, such as customer calls, from external systems like Trello, Asana, and other task planning apps into Google Calendar so that individuals have all of their scheduled engagements in one place.

* Streamline collaboration

Integrate your team calendar with your team channel on messaging systems like Slack and Teams so that anytime you schedule a new event on your team calendar, your team receives a notification.

== Authentication Types

Google Calendar Connector uses the OAuth 2.0 authentication type, which uses access tokens provided by the authorization server to get access to protected data.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
