= Using Websockets Connector in CloudHub
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket, CloudHub, vpc

You can deploy Mule apps that contain inbound WebSocket endpoints, outbound WebSocket endpoints, or both to CloudHub. If your app has inbound WebSocket endpoints only, follow these steps before deploying the app to CloudHub:

. Configure an Anypoint Virtual Private Cloud (VPC).
. Set up a dedicated load balancer to route WS and WSS traffic to the Mule app.

To set up the inbound WebSocket endpoints:

. Configure the WebSockets Inbound Listener (`<ws:inbound-listener>`) to listen on one of the following ports:
* `0.0.0.0`, for communication over xxx.
* `8091` for communication over WS.
* `8092` to communication over WSS.
. Deploy your app to the VPC.
. Set up the dedicated load balancer's URI mapping rules to associate a URI with a specific app.
+
For example, if your app is named 'my-websocket-mule-app', you can define a rule like the following:
* Input Path: `/my-websocket-mule-app/`
* Target App: `my-websocket-mule-app`
* Output Path: `/`
* Protocol: `ws`

//mylb.lb.anypointdns.net:80/my-websocket-mule-app/

This rule routes all requests to your dedicated load balancer's URI and the specified input path to your Mule app's root path, `/`. The load balancer's name determines its assigned URI, so for this example, if you name your Load Balancer 'mylb', then you would need to hit: ws://mylb.lb.anypointdns.net:80/my-websocket-mule-app/ to connect to your WebSocket Listener.

* For WS connections, the dedicated load balancer forwards all requests issued to port 80 to the app's port 8091.
* For WSS connections,the dedicated load balancer forwards all requests issued  to port 443 to the app's port 8092.

=== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
* https://docs.mulesoft.com/runtime-manager/vpc-architecture-concept
* https://docs.mulesoft.com/runtime-manager/lb-architecture
* https://docs.mulesoft.com/runtime-manager/lb-mapping-rules
