= WebSocket Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

WebSocket Connector Version 1.0

A Websocket is a bi-directional, TCP connection between a client and server that is kept open until the application closes it. When using WeSockets, an application makes an initial connection with HTTP. The connection then gets upgraded to a TCP socket-based connection.

WebSockets are a key piece of modern integration due to their ability to:

* Establish bi-directional and full-duplex communication between a server and client
* Implement server push notifications
* Seamlessly work on top of existing HTTP infrastructure
* Avoid the need for clients to regularly poll the server for new data

WebSocket Connector enables you to create Mule apps that...

== Advantages of Full-Duplex Communication

In traditional HTTP, a connection is half-duplex (unidirectional) and works by using a request-response message exchange pattern:

. A client connects to a server and sends a request.
. The server processes the request and sends a response back.
. The client receives the request and the connection ends.

Traditional HTTP connections require a lot of overhead because the client application is blocked until it receives a response from the server. Another disadvantage of using traditional HTTP connections is that the client must always initiate the request. Therefore, the server cannot push notifications to multiple applications at the same time.

When a client connects to a server using WebSockets, a persistent connection is established and kept open. Both the client and server can then send multiple messages to each other without needing to follow the HTTP request-response message exchange pattern. A WebsSocket is built on top of the existing HTTP infrastructure, making it easy to reuse infrastructure that is already in place for traditional HTTP.

For more information about WebSockets, see the IETF document for RFC 6455 - The WebSocket Protocol.

== Common Use Cases for the WebSocket Connector

The WebSocket Connector is useful for real-time applications that need to avoid the overhead caused by the HTTP request-response message exchange pattern.

Typical use cases for WebSocket Connector include chat applications and stock quote applications.

=== Chat Applications

A chat application sends messages to multiple clients in a group. If a Mule app uses HTTP to send messages, the clients must constantly poll the server for available messages, which can create performance issues. If a Mule app uses WebSockets, the server can push the available message to all subscribed users without the need for client polling.

=== Stock Quotes Applications

A stock quotes application continuously sends updated prices for a set of relevant stocks. Clients can open a WebSocket to access this service. Because prices change continuously, the ability to reuse the same connection and receive messages at random times make WebSockets ideal for this type of application.

In this scenario, once the connection is established, the client has no need to send additional requests to the server.

== Compatibility

WebSocket Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.2.2 or higher
|Java |1.8.0_x
|Anypoint Studio|7.4 or higher
|===

== Prerequisites

Before creating an app, you must have access to the WebSocket target resource and Anypoint Platform. You must also understand how to create a Mule app using Design Center or Anypoint Studio.

== Basic WebSocket Connector Concepts

The following concepts are integral to understanding how WebSocket Connector works:

* <<websocket-types,WebSocket types>>
* <<websocket-id,WebSocket ID>>
* <<groups,Groups>>
* <<triggers,Triggers>>
* <<operations,Operations>>

=== WebSocket Types [websocket types]

There are two types of WebSockets:

* Inbound: WebSockets created when the Mule app listens for incoming connections.
+
In this scenario, an external system connects to an endpoint exposed by the Mule app.
+
* Outbound: WebSockets created when the Mule app connects to an external system.
+
In this scenario, the Mule app initiates communication and asks an external system to establish a WebSocket.

Once the initial connection is established, both types of WebSockets support bidirectional, full-duplex communication.

=== WebSocket Id [[websocket-id]]

All WebSockets, both inbound and outbound, have a unique socket ID that identifies them. The app must reference these IDs to operate on individual WebSockets.

=== Groups [[groups]]

WebSocket Connector introduces the concept of groups, which are string identifiers to which individual WebSockets can subscribe. An app can use groups to broadcast one single message to a group of different WebSockets. Groups facilitate the process of identifying which WebSockets should participate in each broadcast.

Subscriptions only exist in the context of each instance of a Mule WebSocket Connector configuration. Therefore, when you establish a web socket between a Mule app and a remote system, subscribing the WebSocket on Mule's end of the connection to a group doesn't affect the WebSockets on the remote system's end.

== Triggers [[triggers]]

Triggers initiate the execution of a flow upon receiving a message or event notification. You can specify the following triggers for WebSocket-related events:

* `inbound-listenerPort` exposes an endpoint that external systems can connect to and initiates the containing flow when a message is received.
* `on-inbound-connection` initiates a flow when a new connection to the Inbound Listener is established.
* `outbound-listener` exposes an endpoint that initiates a flow when an outbound WebSocket receives a message from an external system.
* `on_connection-closed` initiates the containing flow when an inbound or outbound WebSocket is closed.

== Operations [[operations]]

WebSocket Connector support the following operations:

* `open-outbound-socket` connects to an external system and creates an outbound webSocket.
* `send` sends a message through a WebSocket.
* `subscribe-groups` subscribes a WebSocket to one or more groups.
+
The app can invoke this operation on the same web socket multiple times. If an app invokes this operation for . Repeated groups are ignored.
+
* `unsubscribe-groups` unsubscribes a Websocket from one or more groups.
+
You can invoke this operation multiple times on the same socket, with each invocation being additive over the previous ones. Repeated groups are ignored.
+
* `broadcast` send a message to multiple Websocket's classified by path, type, and group.
* `close-socket` closes a Websocket connection.

== Security Scheme

WebSockets Connector supports securing the client and server endpoints through TLS, using the following URI schemes:

* WS identifies a WebSocket server and resource name without using encryption (e.g: ws://localhost:80).
* WSS identifies a WebSocket server and resource name, secure through TLS (e.g: wss://localhost:433).

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]

<Additional links TBD>
