= Websocket Messsaging Operations - Mule 4 [[messaging-operations]]
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket

You can use the following operations to send messages through a WebSocket:

* <<send-operation,Send (`<websocket:send>`>>)
* <<broadcast-operation,Broadcast ()`<websocket:broadcast>`>>)

== Send Operation [[send-operation]]

Use `<websocket:send` to send a message through a WebSocket. You can use this operation to send a message from the WebSocket's inbound endpoint to its outbound endpoint, or from its outbound endpoint to its inbound endpoint.

For example:

* The flow named `Say Hello`:
. Opens an outbound endpoint on a WebSocket called `socketId` on path `/chat/hello`.
. Sends the message `Good morning!` through the WebSocket.
* The flow named `Say Hello Back`:
. Listens for a message on the path `/chat/hello`.
. Responds `Good morning to you` when it hears a message.

[source,xml,linenums]
----
    <flow name="sayHello">
      <websocket:open-outbound-socket path="/chat/hello"
        config-ref="ws" target="outboundSocketId"
        targetValue="#[attributes.socketId]"/>
      <websocket:send socketId="#[vars.socketId]"
        config-ref="ws">
        <websocket:content>'Good morning!'</websocket:content>
      </websocket:send>
    </flow>
    <flow name="sayHelloBack">
        <websocket:inbound-listener path="/chat/hello"
          config-ref="ws" outputMimeType="text/plain" />
        <websocket:send socketId="#[attributes.socketId]"
          config-ref="ws">
          <websocket:content>#['Good morning to you ' ++
           attributes.socketId ++ '!']</websocket:content>
        </websocket:send>
    </flow>
----

== Broadcast Operation [[broadcast-operation]]

Use `<websocket:broadcast>` to send a message to a group of other WebSockets. You can filter the target group according to the following criteria:

* WebSockets subscribed to specific groups (`groups` attribute)
* WebSockets connected to a specific path (`path` attribute)
* Inbound or outbound WebSockets (`type` attribute)

The `groups` and `type` parameters work in tandem. You can use them separately, but when used together, they provide two levels of filtering.

The Broadcast operation returns an empty payload and no attributes.

The following examples shows the different types of filtering you can use with the Broadcast operation:

[source,xml,linenums]
----
<!-- send to all WebSockets connected to an endpoint at path /quotes -->
<websocket:broadcast path=”/quotes” ​config-ref​=​"ws"​ />
<!-- send to all inbound WebSockets connected to an endpoint at path /quotes -->
<websocket:broadcast path=”/quotes” ​type​=​"INBOUND"​ ​
config-ref​="​ws"​ />
<!-- send to all outbound WebSockets connected to the /quotes endpoint -->
<websocket:broadcast path=”/quotes” ​type​=​"OUTBOUND"​ ​
config-ref​=​"ws"​ />
<!-- send to all inbound WebSockets connected to the /quotes endpoint,
in the MARVEL and DC groups -->
<websocket:broadcast path=”/quotes” ​type​=​"INBOUND"​ ​
groups​="​ #[['MARVEL', 'DC']]"​ ​config-ref​=​"ws"​ />
----

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]

<Additional links TBD>
