= WebSocket Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

WebSocket Connector Version 1.0

A WebSocket is a bidirectional, TCP connection between a client and server that is kept open until the application closes it. When using WeSockets, an application makes an initial connection with HTTP. The connection then gets upgraded to a TCP socket-based connection.

WebSockets are a key piece of modern integration due to their ability to:

* Establish bi-directional and full-duplex communication between a server and client
* Implement server push notifications
* Seamlessly work on top of existing HTTP infrastructure
* Avoid the need for clients to regularly poll the server for new data

WebSocket Connector enables you to create real-time applications that need to avoid the overhead causes by the HTTP request-response message exchange pattern.  //<<TBD - I will probably add more text here once I get this information from Esteban.>>

== Common Use Cases

Typical use cases for WebSocket Connector include chat applications and stock quote applications.

=== Chat Applications

A chat application sends messages to one or more groups to which multiple clients subscribe. If a Mule app acting as a server uses HTTP to send messages, the clients must constantly poll the server for available messages, which can create performance issues. If an app uses WebSockets instead, the server can push the available message to all subscribed users without the need for client polling.

=== Stock Quotes Applications

A stock quotes application continuously sends clients updated prices for a set of relevant stocks as soon as this data becomes available. Clients open a WebSocket to access this service. Because prices change continuously, the ability to reuse the same connection and receive messages at random times make WebSockets ideal for this type of application.

In a stock quotes application, once the connection is established, the client has no need to send additional requests to the server.

== Compatibility

WebSocket Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.2.2 and later
|Java |1.8.0_x
|Anypoint Studio|7.4 and later
|===

== Prerequisites

Before creating an app that uses WebSocket Connector, you must have access to the WebSocket target resource and Anypoint Platform. You must also understand how to create a Mule app.

[[triggers]]
== Triggers

Triggers initiate the execution of a flow upon receiving a message or event notification. You can specify the following triggers for WebSocket-related events:

* `inbound-listener` exposes an endpoint to which external systems can connect and initiates the associated app flow when the endpoint receives a message.
* `on-inbound-connection` initiates an app flow when a new connection to the Inbound Listener is established.
* `outbound-listener` exposes an outbound endpoint and initiates the associated app flow when the endpoint receives a message from an external system.
* `on_connection-closed` initiates an app flow when an inbound or outbound WebSocket is closed.

[[operations]]
== Operations

WebSocket Connector supports the following operations:

* `open-outbound-socket` connects to an external system and creates an outbound WebSocket.
* `send` sends a message through a WebSocket.
* `broadcast` sends a message to a group of other WebSockets.
* `subscribe-groups` subscribes a WebSocket to one or more groups.
+
The app can invoke this operation on the same WebSocket multiple times. Each time the app specifies a new group, it is added to the list of target groups for the broadcast.
+
* `unsubscribe-groups` unsubscribes a WebSocket from one or more groups.
+
The app can invoke this operation on the same WebSocket multiple times. Each time an app invokes this operation for a group, the specified group is removed from the list of target groups for the broadcast.
+
* `close-socket` closes a WebSocket connection.

== Security and Authentication

WebSocket Connector supports the WS (Web Sockets) and WSS (Web Sockets over SSL/TLS) URI schemes for outbound endpoints:

*  WS identifies a WebSocket server and resource name in a URI, but does not use SSL for authentication or TLS to encrypt the communication. To use WS for an outbound endpoint, specify `ws` in the URI:
+
`ws://localhost:80`
+
* WSS identifies a WebSocket server and resource name in a URI. In addition, it uses SSL for authentication and TLS to encrypt the communication. To use WSS for an outbound endpoint, specify `wss` in the URI:
+
`wss://localhost:433`.

For an inbound endpoint, TLS and other HTTP configurations are inherited from the configuration of the referenced HTTP Listener.

For detailed information about configuring TLS for a WebSocket, see <<websocket/websocket-connector-configuration.adoc#tls-configuration,TLS Configuration>>.

== See Also

*  xref:websocket/websocket-connector-key-concepts.adoc[WebSocket Connector Key Concepts]
*  xref:websocket/websocket-connector-configuration.adoc[WebSocket Connector Configuration]
* xref:websocket/websocket-connector-reference.adoc[WebSocket Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
