= WebSocket Client Trigger and Operation - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/


You can perform the following operations in the flow associated with an outbound endpoint:

* Open Outbound Socket Operation (`websocket:open-outbound-socket>`)
* Send Message (`<websocket:send-message>`)
* Broadcast Message (`<websocket:broadcast-message>`)
* Subscribe Groups (`<websocket:subscribe-groups`)
* Unsubscribe Groups (`<websocket:unsubscribe-groups`)

For information about the Send Message and Broadcast Message operations, see xref:websocket/websocket-connector-messaging-components.adoc[WebSockets Messaging Operations]. For information on the Subscribe Groups and Unsubscribe Groups operations, see xref:websocket/websocket-connector-management-components.adoc[WebSockets Management Operations].




== Open Outbound Socket Operation [[open-outound-operation]]

Use the Open Outbound Socket Operation to enable an outbound socket to establish a connection to a websocket endpoint.

In order to establish a connection a configuration reference must be provided. In addition, parameters like path and uri can be provided. For further reference check connector's technical reference.

The following example opens a connection reusing most of the settings defined in the configuration reference, but others like the uri are overridden.

=== Output

This operation returns a WebSocketAttributes Object in the attributes and an empty payload.

=== Socket Id

The WebSocketAttributes Object will provide you with a Socket Id (unless you specify your own socket Id in the <open-outbound> operation using the socketId parameter)

The Socket Id can be accessed using the following expression: #[attributes.socketId]. This attribute is especially important because it is what you will use to reference the connection in many operations. You will need the Socket Id to send messages through a WebSocket and close an established connection.

[source,xml,linenums]
----
<flow ​name​=​"connectToMuleStocksAndSendMessage"​>
    ​<websocket:open-outbound path=​"/quotes"​ ​config-ref​=​"ws"​ />

    <websocket:send doc:name="Send" config-ref="ws" socketId="#[attributes.socketId]">
        <websocket:content>#['Hello World!']</websocket:content>
    </websocket:send>
</flow>
----

=== Headers and Query Parameters

You can add custom headers or query parameters to your connection operation. These will be sent along with the default headers and parameters in the initial HTTP request to establish the WS connection. They can be set using DataWeave expressions as shown in the example below.

[source,xml,linenums]
----
<flow ​name​=​"connect"​>
    <websocket:open-outbound-socket path="/chatEcho" config-ref="ws" target="connectionAttributes" targetValue="#[attributes]">
        <websocket:headers><![CDATA[
                #[
                    {
                        chatAlias: 'Captain Marvel',
                        personalities: 'Vers',
                        personalities: 'Carol Danvers'
                    }
                ]
            ]]>
        </websocket:headers>
        <websocket:query-params><![CDATA[
                #[
                    {
                        theme: 'USA'
                    }
                ]
            ]]>
        </websocket:query-params>
    </websocket:open-outbound-socket>
</flow>
----

=== ERRORS

* WEBSOCKET:INVALID_SOCKET_ID
+
The app specified an invalid WebSocket ID when it attempted to establish a connection to a WebSocket .
+
* WEBSOCKET:CONNECTIVITY
+
The app specified a non-existing endpoint when it attempted to establish a connection to a WebSocket.
+
* WEBSOCKET:SERVICE_UNAVAILABLE
+
An app specified an an invalid path when it attempted to establish a connection to a WebSocket.
+
* WEBSOCKET:SERVICE_UNAVAILABLE
+
The app specified an existing WebSocket ID when attempted to create a new WebSocket.

=== See Also

* xref:http/websockets-connector-get-started.adoc[About WebSocket Connector]
