= A2A Connector 0.1.0-BETA 
:lc-connector-name: a2a

Anypoint Connector for Agent2Agent (A2A) (A2A Connector) provides A2A protcol support for your LLM agents, enabling your agents to talk to other agents. A2A Connector makes any LLM or other applications available to A2A clients. This enables client agents to delegate the user’s prompt processing to an agent that specializes in that skill. 

The A2A protocol is an open standard designed to facilitate communication between AI agent systems and aims to:

* Discover each agent’s capabilities
* Negotiate agent interaction methods
* Securely exchange information without needing internal access to each agent's system

A2A Connector:

* Enables you to write Mule applications that can act as both an A2A Server and an A2A client
* Acts as a new A2A Listener with the *Task Listener* operation
** Automatically returns an Agent Card that's based on the connector configuration
** Listens to A2A requests sent by the client Agent, which enables the A2A protocol for existing Agents or other connectors
* Acts as an A2A Client that:
** Sends a task to another A2A host agent 
** Gets task status from an A2A host agent

[NOTE]
====
Anypoint Connector for Agentforce (A2A) is a beta connector that is subject to the Beta Services Terms at https://www.salesforce.com/company/legal/agreements/[Agreements - Salesforce.com] or a written Unified Pilot Agreement if executed by Customer, and the Non-GA Gen AI and Non-GA Credit Consumption terms in the https://ptd.salesforce.com/?_ga=2.247987783.1372150065.1709219475-629000709.1639001992[Product Terms Directory]. Use of this beta connector with external systems or services consumes Mule messages and is at the Customer's sole discretion. 
====

For information about compatibility and fixed issues, see the A2A Connector Release Notes.

== Before You Begin

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Code Builder or Anypoint Studio

Before creating an app, you must have:

* Java 17
* Apache Maven
* Anypoint Platform
* Credentials to connect with the target resource
* The latest versions of Anypoint Code Builder or Anypoint Studio

== Common Use Cases for the Connector

Build specialized domain specific agents each for Customer Service, Sales, or Marketing and have other agents interact with these agents using the A2A protocol.


== Connection Types

* Client
+

* Server
+

== Next Step

include::connectors::partial$t-index-partial.adoc[tags=next-step]

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[]
* xref:connectors::introduction/intro-config-use-acb.adoc[]
* xref:connectors::introduction/intro-config-use-studio.adoc[]
* xref:a2a-connector-reference.adoc[A2A Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
