= MongoDB Connector 6.3 - Mule 4
:page-aliases: connectors::mongodb/mongodb-connector-6-0.adoc



Anypoint Connector for MongoDB (MongoDB Connector) is a closed-source connector that provides a connection between the Mule runtime engine (Mule) and third-party software on a MongoDB server.

Release Notes: xref:release-notes::connector/mongodb-connector-release-notes-mule-4.adoc[MongoDB Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-mongodb-connector/[MongoDB Connector]

== Before You Begin

To use this connector, you must be familiar with MongoDB, Mule runtime engine (Mule), Anypoint Connectors, Anypoint Studio, elements in a Mule flow, and global elements.

Before creating an app, you must have access to the MongoDB target resource and Anypoint Platform. You must also understand how to create a Mule app using Anypoint Studio.

To use the this connector, you need:

* A MongoDB instance
* A set of valid credentials, including the required MongoDB endpoints that point to your instance

== Common Use Cases for the Connector

Common use cases for MongoDB Connector include:

* *Single View of Data*
+
Create a single view of your most important data and aggregate your siloed data from multiple enterprise systems, transform the data, and write the data to MongoDB. For example, you can import data into a CSV format from a local directory into MongoDB.

* *Mainframe Offloading*
+
Mirror or synchronize your operational data from mainframes into MongoDB to offload workloads from your mainframes while enabling the ability to meet your customer where they are.

* *Real-time Analytics*
+
Leverage MongoDB’s rich query language to make real-time decisions on shipping, inventory, and pricing, and analyze any data using documents in MongoDB.

* *Personalization*
+
Create personalized omnichannel retail experiences by collecting and synchronizing data across your retail channels and your backend systems into MongoDB.

For examples of these use cases, refer to xref:mongodb-connector-examples.adoc[MongoDB Connector Examples].


== Authentication

This connector does not validate all possible authentication types.

== Exchange Example

https://www.mulesoft.com/exchange/org.mule.examples/importing-a-CSV-file-into-Mongo-DB/[Anypoint Exchange] has an example that shows how to import data in a CSV format from a local directory into MongoDB.

== Next Steps

After you complete the prerequisites and experiment with the example, you are ready to create an app with xref:mongodb-connector-studio.adoc[Studio].

== See Also

* xref:connectors::introduction/intro-use-exchange.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
