= Microsoft Dynamics 365 Connector 2.4 XML and Maven Support - Mule 4
:page-aliases: connectors::microsoft/microsoft-dynamics-365-connector-xml-maven.adoc

If you manually code a Mule app in XML either from the Anypoint Studio XML editor or from a text editor, you can get access to the Microsoft Dynamics 365 Connector in your app by adding reference statements to your XML Mule flow and in the Apache Maven pom.xml file.

[NOTE]
====
You can avoid the manual process described in this topic by using Studio. When
you install Microsoft Dynamics 365 Connector in Anypoint Studio, Studio automatically populates
the XML code with the Microsoft Dynamics 365 Connector namespace and schema location, and adds a
dependency to the pom.xml file.
====

== Add a Namespace for the Connector

Paste the following code inside the `mule` tag of the header
of your configuration XML:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/microsoft-dynamics-365
http://www.mulesoft.org/schema/mule/microsoft-dynamics-365/current/mule-microsoft-dynamics-365.xsd
----

This example shows how the namespace statements are placed in the XML:

[source,xml,linenums]
----
<mule xmlns:$2="http://www.mulesoft.org/schema/mule/$2"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/file
	http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
	http://www.mulesoft.org/schema/mule/http
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/core
	http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
	http://www.mulesoft.org/schema/mule/$2
	http://www.mulesoft.org/schema/mule/$2/current/mule-$2.xsd">
----

== Add a POM File Dependency

The Maven pom.xml file generated by Anypoint Studio contains dependencies for
a Mule app. When you code a Mule app manually, include this XML snippet in
your pom.xml file to enable access to the connector. The Mule runtime engine
translates the RELEASE dependency keyword to the current version.

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-sap-connector</artifactId>
  <version>RELEASE</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

To obtain the most up-to-date pom.xml file information, access the
connector in https://www.mulesoft.com/exchange/[Anypoint Exchange]
and click *Dependency Snippets*.

== Next Step

After completing your namespace and pom.xml file, you can try
the xref:microsoft-dynamics-365-connector-examples.adoc[Examples].

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
