= Snowflake Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]
// If this is a Premium connector, change Select to Premium

Anypoint Connector for Microsoft Snowflake (Snowflake Connector) provides ...

For information about compatibility and fixed issues, see the Microsoft Snowflake Connector Release Notes. 

== Prerequisites

To use this connector, you must be familiar with:

* The Microsoft Snowflake API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Microsoft Snowflake target resource
* Anypoint Platform
* Anypoint Studio version 7.3 or later


== Common Use Cases For the Connector

These are some common use cases for Snowflake Connector... 

For examples, see xref:microsoft-snowflake-connector-examples.adoc[Snowflake Connector Examples] use cases.

== Connection Types

Snowflake connections use the Snowflake Connection type to connect to Snowflake.

For information about configuring authentication types, see xref:microsoft-snowflake-studio.adoc[Use Studio to Configure Snowflake Connector].


== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:microsoft-snowflake-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:microsoft-snowflake-connector-reference.adoc[Microsoft Snowflake Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
