= Microsoft Snowflake Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]
// If this is a Premium connector, change Select to Premium

Anypoint Connector for Microsoft Snowflake provides ...

For information about compatibility and fixed issues, see the Microsoft Snowflake Connector Release Notes. 

== Prerequisites

To use this connector, you must be familiar with:

* The Microsoft Snowflake API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Microsoft Snowflake target resource
* Anypoint Platform
* Anypoint Studio version 7.3 or later


== Common Use Cases For the Connector

These are some common use cases for Microsoft Snowflake Connector... 

For examples, see xref:microsoft-snowflake-connector-examples.adoc[Microsoft Snowflake Connector Examples] use cases.

== Connection Types

// If there is one authentication type, use the following format:

Microsoft Snowflake connections use the <authentication-type> authentication type, which ... <add a brief description of the authentication type like the descriptions below>.

////
If there is more than one authentication type, use a list like the one shown below (use only the applicable connection types--delete the others):

Microsoft Snowflake connections use the following authentication types:

* Basic authentication +
Uses a username and password for authentication
* OAuth +
Uses access tokens provided by the authorization server to get access to protected data 
* OAuth2 +
Delegates user authentication to the service hosting the user account
Kerberos +
Uses the Kerberos principal as the username. The keytab path you specify obtains a ticket-granting ticket (TGT) from the authorization server.
////

For information about configuring authentication types, see xref:microsoft-snowflake-studio.adoc[Use Studio to Configure Microsoft Snowflake Connector].


== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:microsoft-snowflake-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:microsoft-snowflake-connector-reference.adoc[Microsoft Snowflake Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
