= Amazon Redshift Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Amazon Redshift (Amazon Redshift Connector) is a bulk-load connector that enables you to connect to Amazon Redshift database to perform inserts, deletes, updates, and to execute SQL queries. 

For compatibility information and fixed issues, see the Amazon Redshift Connector Release Notes.

include::connectors::partial$prerequisites-partial.adoc[]

== Common Use Cases for the Connector

Some possible uses for this connector include:

* Analytics
* Streaming data in to a data warehouse

== Authentication Types

Amazon Redshift Connector uses the following connection methods:

* Basic username and password authentication
* Temporary credentials, which are retrieved using IAM user authentication 


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:amazon-redshift-connector-reference.adoc[Amazon Redshift Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
