= Amazon Redshift Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Amazon Redshift (Amazon Redshift Connector) is a bulk-load connector that enables you to connect to Amazon Redshift database to perform inserts, deletes, updates, and to execute SQL queries. 

For compatibility information and fixed issues, see the Amazon Redshift Connector Release Notes.

include::connectors::partial$prerequisites-partial.adoc[]

== Common Use Cases for the Connector

Some possible uses for this connector include:

* Analytics
+
Amazon Redshift operates as an optimized data warehouse that can store large volumes of data, which can then be analyzed using a business intelligence (BI) tool such as Tableau.
* Real-time processing of social media feeds
+
Stream data from your social media feeds, such as a Twitter feed, into Amazon Kinesis Data Streams, and then store that data in a data warehouse, such as Amazon Redshift to perform real-time analytics.

== Authentication Types

Amazon Redshift Connector uses the following connection methods:

* Basic authentication, which uses *user* and *password* field values to connect to the database
* IAM authentication, which uses *access key* and *secret key* field values to retrieve the temporary password for the specified user in order to connect to the database


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:amazon-redshift-connector-reference.adoc[Amazon Redshift Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
