= Troubleshooting Amazon S3 Connector 5.8 - Mule 4

To troubleshoot Anypoint Connector for Amazon S3 (Amazon S3 Connector), become familiar with the information about interpreting commonly thrown exception messages.

== Understand Commonly Thrown Exceptions

Here is a list of commonly thrown exception messages and how to interpret them:

* S3:ACCESS_DENIED

 An Amazon S3 Connector operation attempts to access an Amazon S3 server path and performs an action for which the user does not have permission.

* S3:ACCOUNT_PROBLEM

 An error occurs due to a problem with your AWS account.

* S3:AMBIGUOUS_GRANT_BY_EMAIL_ADDRESS

 There is more than one account associated with the provided email address.

* S3:BAD_DIGEST

 The Content MD5 you specify does not match as expected.

* S3:BUCKET_ALREADY_EXISTS

 The bucket name you specify already exists.

* S3:BUCKET_ALREADY_OWNED_BY_YOU

 The bucket you create already exists and is owned by you.

* S3:BUCKET_NOT_EMPTY

 The bucket you attempt to delete is not empty.

* S3:CREDENTIALS_NOT_SUPPORTED

 The credentials are not supported by the request.

* S3:CROSS_LOCATION_LOGGING_PROHIBITED

 You attempt cross-location logging, which is not allowed.

* S3:ENTITY_TOO_LARGE

 The entity is larger than the maximum size limit.

* S3:ENTITY_TOO_SMALL

 The entity is smaller than the minimum size limit.

* S3:EXPIRED_TOKEN

 The token is expired.

* S3:ILLEGAL_VERSIONING_CONFIGURATION_EXCEPTION

 The versioning configuration is invalid.

* S3:INCOMPLETE_BODY

 The number of bytes in Content Length is unspecified.

* S3:INCORRECT_NUMBER_OF_FILES_IN_POST_REQUEST

 There is an incorrect number of files in the POST request, which allows only one file.

* S3:INLINE_DATA_TOO_LARGE

 The inline data is larger than the maximum size limit.

* S3:INTERNAL_ERROR

 There is an internal error, such as a server issue or a temporary glitch.

* S3:INVALID_ACCESS_KEY_ID

 The access key ID you provide is invalid.

* S3:INVALID_ADDRESSING_HEADER

 The addressing header is invalid and the role must be anonymous.

* S3:INVALID_ARGUMENT

 There is an invalid argument.

* S3:INVALID_BUCKET_NAME

 The bucket name you specify is invalid.

* S3:INVALID_BUCKET_STATE

 The bucket state is invalid with the request.

* S3:INVALID_DIGEST

 The Content MD5 you specify is invalid.

* S3:INVALID_ENCRYPTION_ALGORITHM_ERROR

 The encryption request you specify is invalid and must be `AES256`.

* S3:INVALID_LOCATION_CONSTRAINT

 The location constraint you specify is invalid.

* S3:INVALID_OBJECT_STATE

 The object state is invalid with the action.

* S3:INVALID_PART

 A part you specify is not found.

* S3:INVALID_PART_ORDER

 The part order is invalid and must be in ascending order by part number.

* S3:INVALID_PAYER

 Access to the object is not allowed.

* S3:INVALID_POLICY_DOCUMENT

 The form is invalid due to the policy document requirements.

* S3:INVALID_RANGE

 The range you specify is invalid.

* S3:INVALID_REQUEST

 The request you specify is invalid and must be `AWS4-HMAC-SHA256`.

* S3:INVALID_RESPONSE_PRESIGNEDURL_MALFORMED

 The response is malformed.

* S3:INVALID_SOAP_REQUEST

 The SOAP request is invalid and must be made over HTTPS.

* S3:INVALID_SECURITY

 The security credentials you provide are invalid.

* S3:INVALID_STORAGE_CLASS

 The storage class you specify is invalid.

* S3:INVALID_TARGET_BUCKET_FOR_LOGGING

 The target bucket for logging is invalid.

* S3:INVALID_TOKEN

 The token you specify is invalid.

* S3:INVALID_URI

 The URI is invalid.

* S3:KEY_TOO_LONG

 The key is too long.

* S3:MALFORMED_ACL_ERROR

 The XML you specify is malformed.

* S3:MALFORMED_POST_REQUEST

 The POST request body is malformed.

* S3:MALFORMED_XML

 The XML you send is malformed.

* S3:MAX_MESSAGE_LENGTH_EXCEEDED

 The request is larger than the maximum length limit.

* S3:MAX_POST_PRE_DATA_LENGTH_EXCEEDED_ERROR

 The pre-data POST request fields are larger than the maximum length limit.

* S3:METADATA_TOO_LARGE

 The metadata headers are larger than the maximum size limit.

* S3:METHOD_NOT_ALLOWED

 The method is not allowed for the specified resource.

* S3:MISSING_ATTACHMENT

 A SOAP attachment is missing.

* S3:MISSING_CONTENT_LENGTH

 A Content-Length HTTP header is missing.

* S3:MISSING_REQUEST_BODY_ERROR

 The request body is empty as an empty XML document is sent.

* S3:MISSING_SECURITY_ELEMENT

 The security element is missing from the request.

* S3:MISSING_SECURITY_HEADER

 The security header is missing from the request.

* S3:NO_LOGGING_STATUS_FOR_KEY

 The key does not contain a logging status.

* S3:NO_SUCH_BUCKET

 The bucket you specify does not exist.

* S3:NO_SUCH_BUCKET_POLICY

 The bucket you specify does not contain a bucket policy.

* S3:NO_SUCH_KEY

 The key you specify does not exist.

* S3:NO_SUCH_LIFECYCLE_CONFIGURATION

 The lifecycle configuration you specify does not exist.

* S3:NO_SUCH_UPLOAD

 The upload you specify does not exist.

* S3:NO_SUCH_VERSION

 The version ID you specify does not match with any existing versions.

* S3:NOT_IMPLEMENTED

 The header you specify contains functionality that is not implemented.

* S3:NOT_SIGNED_UP

 The account you specify is not signed up for Amazon S3.

* S3:OPERATION_ABORTED

 The operation is aborted because there is another in-progress action against the same resource.

* S3:PERMANENT_REDIRECT

 The endpoint you specify must be used to access the bucket.

* S3:PRECONDITION_FAILED

 The preconditions you specify are not satisfied.

* S3:REDIRECT

 There is a temporary redirect.

* S3:REQUEST_IS_NOT_MULTI_PART_CONTENT

 The request must be multipart.

* S3:REQUEST_TIME_TOO_SKEWED

 The time in between the request time and the server time is too large.

* S3:REQUEST_TIMEOUT

 The request timed out before the request could be read or written.

* S3:REQUEST_TORRENT_OF_BUCKET_ERROR

 You are not allowed to request the bucket torrent file.

* S3:RESTORE_ALREADY_IN_PROGRESS

 The restore is already in progress.

* S3:SERVICE_UNAVAILABLE

 There are resource constraints on the request.

* S3:SIGNATURE_DOES_NOT_MATCH

 The signature you provide does not match the expected signature.

* S3:SLOW_DOWN

 There are too many requests.

* S3:TEMPORARY_REDIRECT

 There is a temporary redirect due to DNS updates.

* S3:TOKEN_REFRESH_REQUIRED

 The token you provide requires a refresh.

* S3:TOO_MANY_BUCKETS

 The amount of buckets created is larger than the maximum limit.

* S3:UNEXPECTED_CONTENT

 There is content in a request that does not support content.

* S3:UNKNOWN

 There is an unknown or an unexpected error.

* S3:UNRESOLVABLE_GRANT_BY_EMAIL_ADDRESS

 The email address you provide does not match existing email addresses.

* S3:USER_KEY_MUST_BE_SPECIFIED

 The user key must be specified in the bucket and in the correct order.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:amazon-s3-connector-reference.adoc[Amazon S3 Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
