= Troubleshooting Amazon S3 Connector 4.6 - Mule 4

To troubleshoot Anypoint Connector for Amazon S3 (Amazon S3 Connector), become familiar with the information about interpreting commonly thrown exception messages.

== Understand Commonly Thrown Exceptions

Here is a list of commonly thrown exception messages and how to interpret them:

* S3:ACCESS_DENIED

 An Amazon S3 Connector operation attempts to access an Amazon S3 server path and performs an action for which the user does not have permission.

* S3:ACCOUNT_PROBLEM

 An error occurs due to a problem with your AWS account.

* S3:AMBIGUOUS_GRANT_BY_EMAIL_ADDRESS

 There is more than one account associated with the provided email address.

* S3:BAD_DIGEST

 The *Content MD5* you specify does not match as expected.

* S3:BUCKET_ALREADY_EXISTS

 The bucket name you specify already exists.

* S3:BUCKET_ALREADY_OWNED_BY_YOU

 The bucket you create already exists and is owned by you.

* S3:BUCKET_NOT_EMPTY

 The bucket you attempt to delete is not empty.

* S3:CREDENTIALS_NOT_SUPPORTED

 The credentials are not supported by the request.

* S3:CROSS_LOCATION_LOGGING_PROHIBITED

 You attempt cross-location logging, which is not allowed.

* S3:ENTITY_TOO_LARGE

 The entity is larger than the maximum size limit.

* S3:ENTITY_TOO_SMALL

 The entity is smaller than the minimum size limit.

* S3:EXPIRED_TOKEN

 The token is expired.

* S3:ILLEGAL_VERSIONING_CONFIGURATION_EXCEPTION

 The versioning configuration is invalid.

* S3:INCOMPLETE_BODY

 The number of bytes in *Content Length* is unspecified.

* S3:INCORRECT_NUMBER_OF_FILES_IN_POST_REQUEST

 There is an incorrect number of files in the POST request, which allows only one file.

* S3:INLINE_DATA_TOO_LARGE

 The inline data is larger than the maximum size limit.

* S3:INTERNAL_ERROR

 There is an internal error, such as a server issue or a temporary glitch.

* S3:INVALID_ACCESS_KEY_ID

 The access key ID you provide is invalid.

* S3:INVALID_ADDRESSING_HEADER

 The addressing header is invalid and the role must be anonymous.

* S3:INVALID_ARGUMENT

 There is an invalid argument.

* S3:INVALID_BUCKET_NAME

 The bucket name you specify is invalid.

* S3:INVALID_BUCKET_STATE

 The bucket state is invalid with the request.

* S3:INVALID_DIGEST

 The *Content MD5* you specify is invalid.

* S3:INVALID_ENCRYPTION_ALGORITHM_ERROR

 The encryption request you specify is invalid and must be `AES256`.

* S3:INVALID_LOCATION_CONSTRAINT

 The location constraint you specify is invalid.

* S3:INVALID_OBJECT_STATE

 The object state is invalid with the action.

* S3:INVALID_PART

 A part you specify is not found.

* S3:INVALID_PART_ORDER

 The part order is invalid and must be in ascending order by part number.

* S3:INVALID_PAYER

 Access to the object is not allowed.

* S3:INVALID_POLICY_DOCUMENT

 The form is invalid due to the policy document requirements.



== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:amazon-s3-connector-reference.adoc[Amazon S3 Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
