= XML Reference for the Salesforce Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: salesforce connector, inbound, outbound, streaming, poll, dataweave, datasense
:icons: font

If you are creating Salesforce connector XML by hand, you need to add the namespace for the connector. By contrast, Anypoint Studio creates the namespace for a connector automatically when you create a project for a Mule app.

[source,text,linenums]
----
xsi:schemaLocation="
...
http://www.mulesoft.org/schema/mule/sfdc
http://www.mulesoft.org/schema/mule/sfdc/current/mule-salesforce.xsd"
----

Example

[source,xml,linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:sfdc="http://www.mulesoft.org/schema/mule/salesforce"
      xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core
               http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/sfdc
               http://www.mulesoft.org/schema/mule/sfdc/current/mule-salesforce.xsd">

      <!-- Insert your configuration elements and your flow here -->
</mule>
----

== Configuring Maven Dependencies


Repository information for your projects's `pom.xml` file:

[source,xml,linenums]
----
<repositories>
   <repository>
        <id>mule-ee-releases</id>
        <name>MuleEE Releases Repository</name>
        <url>https://repository-master.mulesoft.org/nexus/content/repositories/releases-ee/</url>
    <repository>
        <id>mule-ee-snapshots</id>
        <name>MuleEE Snapshots Repository</name>
        <url>https://repository-master.mulesoft.org/nexus/content/repositories/ci-snapshots/</url>
    </repository>
</repositories>
----

This snippet specifies a project dependency for a specific release version:

[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.connectors</groupId>
    <artifactId>mule-sfdc-connector</artifactId>
    <version>RELEASE</version>
    <classifier>mule-plugin</classifier>
</dependency>
----

This snippet adds specifies a project dependency for the latest version:

[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-sfdc-connector</artifactId>
    <version>LATEST</version>
</dependency>
----

////
TODO? DOUBLE-CHECK WITH MARCOS OR NATHAN? BOGDAN THINKS IT MIGHT NOT BE NECESSARY.
If you plan to use this module inside a Mule app, you need to include it in the packaging process so that the final zip file that contains your flows and Java code also contains this module and its dependencies. You add a special `inclusion` element like this one to the configuration of the Mule Maven plugin for the connector:

[source,xml,linenums]
----
<plugin>
    <groupId>org.mule.tools</groupId>
    <artifactId>maven-mule-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <excludeMuleDependencies>false</excludeMuleDependencies>
        <inclusions>
            <inclusion>
                <groupId>org.mule.modules</groupId>
                <artifactId>mule-sfdc-connector</artifactId>
            </inclusion>
        </inclusions>
    </configuration>
</plugin>
----
////

== See Also

xref:salesforce/salesforce-about.adoc[About the Salesforce Connector]

xref:salesforce/salesforce-connector-tech-ref.adoc[Salesforce Connector Technical Reference]