= Salesforce XML and Maven Support - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

== Add a Namespace for the Connector

In Studio, when you drag a connector from the palette to the Canvas, Studio 
automatically populates the XML code with the connector namespace and schema location.
If you manually code the Mule application in Studio's XML editor or another text editor, 
paste the following into the header of your configuration XML, inside the  tag:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/salesforce 
http://www.mulesoft.org/schema/mule/salesforce/current/mule-salesforce.xsd
----

Example:

[source,xml,linenums]
----
<mule xmlns:salesforce="http://www.mulesoft.org/schema/mule/salesforce" 
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:file="http://www.mulesoft.org/schema/mule/file" 
	xmlns="http://www.mulesoft.org/schema/mule/core" 
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core 
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/file 
	http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
	http://www.mulesoft.org/schema/mule/http 
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/core 
	http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
	http://www.mulesoft.org/schema/mule/salesforce 
	http://www.mulesoft.org/schema/mule/salesforce/current/mule-salesforce.xsd">
----

== Configure the Maven POM File

When creating an application in XML, put the following dependency statements in your Apache Maven  file to 
enable access to this connector. The Mule runtime translates the  dependency keyword to the current version.

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-salesforce-connector</artifactId>
  <version>LATEST</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

To obtain the most up-to-date `pom.xml` file information, access the connector in 
https://www.mulesoft.com/exchange/[Anypoint Exchange], and click *Dependency Snippets*.

== Next

Now that you have understand the Maven XML support, you can try out the xref:salesforce/salesforce-connector-examples.adoc[Salesforce Examples].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
