= About Apex Settings and Invoke Operations
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: salesforce connector, inbound, outbound, streaming, poll, dataweave, datasense
:icons: font

Invoke Apex REST Method (introduced in version 6.2.0) and Invoke Apex Soap Method (introduced in 6.1.0) work with Apex Class Name settings. When you connect to Salesforce, the Salesforce connector gets the names of the Apex classes and methods belonging to them that can be invoked.

All Salesforce connection configurations support these Apex settings:

* Fetch All Apex SOAP Metadata - Fetches the metadata of all the Apex SOAP classes. Takes precedence over Apex Class Name settings.
* Fetch All Apex REST Metadata - Fetches the metadata of all the all Apex REST classes. Takes precedence over Apex Class Name settings.
* Apex Class Name - List of Apex class names to use for limiting the set of classes you fetch along with the methods they expose. This setting can speed the fetch process if there are a lot of classes that you do not need to fetch.

////
Input to the two Invoke Apex operations is set by default as the `payload` of the selected method. For the SOAP-based operation, you can also use Map to transform the input format to a different output format.
////

== See Also

xref:salesforce/salesforce-about.adoc[About the Salesforce Connector]

xref:salesforce/salesforce-connector-tech-ref.adoc[Salesforce Connector Technical Reference]

////
No more action needed:
ARE THESE OPTIONS AVAILABLE? NOTIFIED BOGDAN ON 07/18.
. Apex Class Name:
.. None - No Apex class name is mentioned for DataSense to acquire.
.. From Message - Lets you specify the class name from a MEL expression.
.. Create Object manually - A user creates a list and adds class names to the list - only those classes and their methods are acquired by DataSense.
+
////

////
No more action needed:
ARE THESE OPTIONS AVAILABLE? NOTIFIED BOGDAN ON 07/18.
 which can be found in the dropdown for the Apex Class Method Name parameter. Choose a method and DataSense to get the input and output for that method.
////

////
No more action needed: XMLStreamReader not needed by customers.
SHOULD WE MENTION THE XMLStreamReader?  asked BOGDAN ON 07/18.
Input to the operations is an `XMLStreamReader`, which creates from XML representing the input of the method selected (similar to the input of a SOAP operation):
+
[source,xml,linenums]
----
<soap:testSOAPMethod>
    <soap:name>John</soap:name>
    <soap:someNumber>54</soap:someNumber>
</soap:testSOAPMethod>
----
////

////
No more action needed:
asked BOGDAN ON 07/18. NOT SURE WHAT TO SAY ABOUT mapping with REST. Looks like the option is to specify key/value pairs.
////