= Salesforce Marketing Cloud - Upgrade and Migrate - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Upgrade Anypoint Connector for Salesforce Marketing Cloud (Salesforce Marketing Cloud Connector) to version 3.0.0.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|2.2.0 |3.0.0
|===

== Changes in This Release

This release contains the following changes:

* Removed FuelSDK and used Mule HTTP client to perform the SOAP requests to the API.
* When using the `upsert` operation, now the connector sends a CreateRequest, not an UpdateRequest.


=== Changes in Connection Types

This release contains the following changes to connection types:

* Added the OAuth client credentials connection provider to enable the use of the OAuth mechanism for authentication.
* Removed OAuth Username and Password authentication because the Salesforce Marketing Cloud deprecated this authentication type.


== Changed Operations, Parameters, and Return Types

Salesforce Marketing Cloud 3.0.0 has the same operations as the 2.x versions, but groups some of them differently.

The following table shows the changes to operation names, input parameters, and return types:

// [cols="50,50"]
[%header%autowidth.spread]
|===
|Salesforce Marketing Cloud 2.2.x Operation | Changes in Salesforce Marketing Cloud 3.0.0

| Configure Create
a| Operation is now called Configure. Use parameter action with value `Create`.

| Configure Update
a| Operation is now called Configure. Use parameter action with value `Update`.

| Configure Delete
a| Operation is now called Configure. Use parameter action with value `Delete`.

| Perform Start
a| Operation is now called Perform. Use parameter action with value `Start`.

| Perform Stop
a| Operation is now called Perform. Use parameter action with value `Stop`.

| Perform Get Max Count
a| Operation is now called Perform. Use parameter action with value `Get Max Count`.


|===

== Changes in Operations Metadata

There are no changes related to keys, input metadata, or output metadata.

== Removed Operations

The following operations were removed from Salesforce Connector:

//[cols="15%,35%,15%]
|===
|Removed Operation |Functionality Covered By

| Configure Create | Configure
| Configure Update | Configure
| Configure Delete | Configure
| Perform Start | Perform
| Perform Stop | Perform
| Perform Get Max Count | Perform
|===

== Upgrade Prerequisites

Before you perform the upgrade, you must:

. Create a backup of your files, data, and configuration in case you need to restore to the previous version.
. Install Salesforce Marketing Cloud Connector v3.0.0.

== Upgrade Steps

Follow these steps to perform the upgrade from Salesforce Marketing Cloud Connector v2.2.0 to Salesforce Connector v3.0.0:

. In Anypoint Studio, create a Mule project.
. In the Mule Palette view, click *Search in Exchange*.
. In the *Add Dependencies to Project* window, enter `Salesforce Marketing Cloud 3` in the search field.
. In the *Available modules* section, select *Salesforce Marketing Cloud Connector 3.0.0* and click *Add*.
. Click *Finish*.
. Verify that the `mule-sfdc-marketing-cloud-connector` dependency version is `3.0.0` in the `pom.xml`.

Studio upgrades the connector automatically.


== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Check the project `pom.xml` and verify that there are no problems.
. Test the connection and verify that the operations work.

== Troubleshooting

If there are problems with caching the parameters and caching the metadata, try restarting Studio.

== Revert the Upgrade

If it is necessary to revert to the previous version of Salesforce Connector, change the `mule-sfdc-marketing-cloud-connector` dependency version `3.0.0` in the project's `pom.xml` to the previous version.

You must update the project's `pom.xml` in Anypoint Studio.


== See Also

https://help.mulesoft.com[MuleSoft Help Center]
