= Salesforce Marketing Cloud - Upgrade and Migrate - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Upgrade Anypoint Connector for Salesforce Marketing Cloud (Salesforce Marketing Cloud Connector) to version 3.0.0.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|2.2.x |3.0.0
|===

== Changes in This Release

This release contains the following changes:

* Removed support for FuelSDK. The connector now uses the Mule HTTP client to perform the SOAP requests to the API.
* Changed the supported connection types
* Changed the Upsert entities operation
* Removed some operations and grouped their functionality into fewer operations

== Changes in Connection Types

This release contains the following changes to connection types:

* Added support for using OAuth authentication
* Removed OAuth Username and Password authentication, because the Salesforce Marketing Cloud deprecated this authentication type

== Changed Operations

When using the Upsert entities operation, the connector now sends a Create request instead of an Update request.
*What is the exact name of the request that is sent?*

== Removed Operations

Salesforce Marketing Cloud 3.0.0 has the same functionality as the 2.x versions, but it implements this functionality with fewer operations.

The following operations were removed from Salesforce Marketing Cloud Connector:

// [cols="50,50"]
[%header%autowidth.spread]
|===
|Removed Operation | Functionality Covered By

| Configure Create
a| Configure action operation with the Action parameter set to `Create`

| Configure Update
a| Configure action operation with the Action parameter set to `Update`

| Configure Delete
a| Configure action operation with the Action parameter set to `Delete`

| Perform Start
a| Perform action operation with the Action parameter set to `Start`

| Perform Stop
a| Perform action operation with the Action parameter set to `Stop`

| Perform Get Max Count
a| Perform action operation with the Action parameter set to  `Get Max Count`

|===

== Changes in Operations Metadata

There are no changes related to keys, input metadata, or output metadata.

== Upgrade Prerequisites

Before you perform the upgrade, you must:

. Create a backup of your files, data, and configuration in case you must restore to the previous version.
. Install Salesforce Marketing Cloud Connector v3.0.0.

== Upgrade Steps

Follow these steps to perform the upgrade from Salesforce Marketing Cloud Connector v2.2.x to Salesforce Marketing Cloud Connector v3.0.0:

. In Anypoint Studio, create a Mule project.
. In the Mule Palette view, click *Search in Exchange*.
. In the *Add Dependencies to Project* window, enter `Salesforce Marketing Cloud 3` in the search field.
. In the *Available modules* section, select *Salesforce Marketing Cloud Connector 3.0.0* and click *Add*.
*Can you just say "select Salesforce Marketing Cloud Connector here instead of adding 3.0.0?"*
. Click *Finish*.
. Verify that the `mule-sfdc-marketing-cloud-connector` dependency version is `3.0.0` in the `pom.xml` file.

Studio upgrades the connector automatically.

== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Check the project `pom.xml` file and verify that there are no problems.
. Test the connection and verify that the operations work.

== Troubleshooting

If there are problems with caching the parameters or caching the metadata, try restarting Studio.

== Revert the Upgrade

If it is necessary to revert to the previous version of Salesforce Marketing Cloud Connector, change the `mule-sfdc-marketing-cloud-connector` dependency version `3.0.0` in the project's `pom.xml` file to the previous version.


== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
