= To Generate a KeyStore and Public Key (Salesforce Connector)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: salesforce connector, inbound, outbound, streaming, poll, dataweave, datasense
:icons: font

The KeyStore is the path to the KeyStore file used to sign data during authentication. Only Java KeyStore format is allowed.

If you are using OAuth 2.0 configurations for Salesforce connections, you will need the public key produced by this procedure to create a consumer key.

To generate a KeyStore file:

. Open a command prompt (for Windows) or Terminal (for Mac) to your Mule workspace directory.
. Type `keytool -genkeypair -alias salesforce-cert -keyalg RSA -keystore salesforce-cert.jks` and press enter.
. Enter the following details:
+
* Password for the KeyStore.
* Your first name and last name.
* Your organization unit.
* Name of your city, state, and the two letters code of your county.
+
The system generates a Java KeyStore file containing a private/public key pair in your workspace.
+
. Provide the file path for the KeyStore in your connector configuration.
+
Type `keytool -exportcert -alias salesforce-cert -file salesforce-cert.crt -keystore salesforce-cert.jks` and press enter.
+
The system now exports the public key from the KeyStore into the workspace. This is the public key that you need to enter in your Salesforce instance.
+
. Make sure that both the KeyStore (`salesforce-cert.jks`) and the public key (`salesforce-cert.crt`) files are in your Mule workspace.

== See Also

xref:salesforce/salesforce-about-authentication.adoc[About Authentication through the Salesforce Connector]

xref:salesforce/salesforce-to-create-consumer-key.adoc[To Create a Consumer Key]

xref:salesforce/salesforce-connector-tech-ref.adoc[Salesforce Connector Technical Reference]