= Salesforce - Upgrade and Migrate - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Upgrade Anypoint Connector for Salesforce (Salesforce Connector) to version 10.0.0.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|9.8.x |10.0.0
|===

== Changes in This Release

This release contains the following changes:

* Removed deprecated connection providers
* Merged multiple operations into one
* Redesigned the Replay ID functionality
* Changed the Mule TLSContext usage
* Removed the Dozer library *(what is this and how does this affect the connector)???*
* Improved the error types *(When you say improved, can you be more specific? Did you add error types?)*

== Changes in Connection Providers

This release contains the following changes:

* Removed the following authentication methods:
** Username Password
** Basic Username Password
* Added the following authentication methods:
** Basic authentication
** OAuth Username Password
* Added new tabs *(please name the new tabs. Please send a screenshot.)* in Salesforce Config and reordered the parameters in a more intuitive way.
* Added the Connection Pool Config tab to improve multi-threading support while running operations. This tab contains three parameters to help you manage the application connection objects. *(Is connection pool functionality new for this release?)*
+
With the addition of the connection pool functionality, each request sent to the API has its own headers and read timeout. This functionality prevents the operation headers from being overridden with the wrong values when operations are executed at the same time.
+
* Moved the Read timeout parameter from the provider configuration to the connector configuration.
* Removed the following parameters:
** Advanced Reconnection Params
** Assignment Rule Id
** Client Id
** Time Object Store
** Batch Sobject Max Depth
** Disable session invalidation
** Allow field truncation support
** Use default rule
** Can Clear Fields by Updating Field value to Null

== Changed Operations, Parameters, and Return Types

In Salesforce 10.0, all operations contain the following new parameters:

* Time unit
* Read timeout

The following table shows other changes to operation names, input parameters, and return types:

// [cols="50,50"]
[%header%autowidth.spread]
|===
|Salesforce 9.8 Operation | Changes in Salesforce 10.0

| Abort job v 2
a| Operation is now called Abort job bulk api v2.

| Abort query job
a|  * Operation is now called Abort query job bulk api v2.
* Query job id parameter is now called Id.

| Batch result
a| Return type is now Bulk Operation Result, which can be integrated with the Batch scope.

| Batch result stream
a| Return type is now InputStream.

| Create
a| Return type is now Bulk Operation Result, which can be integrated with the Batch scope.

| Delete
a| Return type is now Bulk Operation Result, which can be integrated with the Batch scope.

| Find duplicates by ids
a| List of object ids used when searching for duplicates parameter is now Ids List.

| Get all jobs v 2
a| * Operation is now called Get all jobs bulk api v2.
* Is pk chunking enabled parameter is now called Pk Chunking.

| Get all query jobs
a| Operation is now called Get all query jobs bulk api v2.

| Get bulk job state bulk v 2
a| Operation is now called Get job state bulk api v2.

| Get bulk job state bulk v 2
a| * Operation is now called Get query job results bulk api v2.
* Query job id parameter is now called Id. (*George, in Studio I see a Job id parameter, but not a Query job id parameter)*

| Get deleted
a| * Duration parameter is replaced by the Start Date and End Date parameters.
* Type parameter is now called Object type.

| Get query job info
a| * Operation is now called Get query job info bulk api v2.
* Query job id parameter is now called Id.

| Get updated
a| * Operation is now called Get updated objects.
* Duration parameter is replaced by Start Date and End Date parameters.
* Type parameter is now called Object Type.

| Replay channel
a| Operation is now called Replay channel listener.

| Replay topic
a| Operation is now called Replay topic listener.

| Retrieve record failure bulk v 2
a| Operation is now called Retrieve job failed result bulk v2.

| Retrieve record success bulk v 2
a| Operation is now called Retrieve job successful result bulk v2.

| Update
a| Return type is now the Bulk Operation Result, which can be integrated with the Batch scope.

| Upsert
a| Type parameter is now called Object Type.

|===

== Changes in Operations Metadata

There are no changes related to keys, input/output metadata.

== Removed Operations

The following operations were removed from Salesforce Connector:

//[cols="15%,35%,15%]
|===
|Operation |Functionality Covered By

| Create single | Create
| Create multiple | Create
| Create bulk | Create job operation with an `insert` operation parameter and a Create Batch operation
| Update single	| Update operation
| Update multiple | Update operation
| Update bulk | Create job operation with an `update` operation parameter and a Create Batch operation
| Upsert multiple | Upsert
| Upsert bulk | Create Job operation with an `upsert` operation parameter and a Create Batch operation
| Delete multiple | |Delete
| Hard delete bulk | Create Job operation with a `hardDelete` operation parameter and a Create batch operation Bulk Operation Result
| Query single | Query operation
| Non paginated query | Query operation
| Get updated objects | Get updated objects operation and Retrieve operation
| Get updated | Get updated objects operations
| Get deleted range | Get deleted objects operation
| Create bulk for query | Create batch for query operation
| Create multiple bulk | Create Job operation with a `create` operation parameter and a Create batch operation
| Update multiple bulk | Create Job operation with an `update` operation parameter and a Create batch operation
| Upsert multiple bulk | Create Job operation with an `upsert` operation parameter and a Create batch operation
| Hard delete multiple | Create Job with a `hardDelete` operation parameter and a Create batch operation
| Create multiple batch | Create batches operation (*Don't see this operation*)
| Create multiple batch stream | Create batch stream operation
| Bulk result | Batch result operation
| Bulk result stream| Batch result stream operation
| Bulk info | Batch info operation
| Query multiple result stream | Query result stream operation
| Bulk info list | Batch info list operation
|===

== Upgrade Steps

Follow these steps to perform the upgrade from Salesforce Connector v9.8 to Salesforce Connector v10.0:

. Create a backup of your files, data, and configuration in case you need to restore to the previous version.
. In Studio, create a Mule project.
. In the Mule Palette view, click *Search in Exchange*.
. In the *Add Dependencies to Project* window, type 'Salesforce 10' in the search field.
. In the *Available modules* section, select *Salesforce Connector 10.0.0*, and then click *Add*.
. Click *Finish*.
. Verify that the `salesforce-connector` dependency version is `10.0.0` in the pom.xml.

Anypoint Studio upgrades the connector automatically.


== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Anypoint Studio, verify that there are no errors in the *Problems* or *Console* views.
. Check the project pom.xml and verify that there are no problems.
. Test the connection and verify that the operations work.

== Troubleshooting

If there are problems with caching the parameters and caching the metadata, try restarting Anypoint Studio.

== Revert the Upgrade

If it is necessary to revert to the previous version of Salesforce Connector, change the `salesforce-connector` dependency version `10.0.0` in the project's pom.xml to the previous version.

You must update the project's pom.xml in Anypoint Studio.


== See Also

https://help.mulesoft.com[MuleSoft Help Center]
