= To Create a Consumer Key (Salesforce Connector)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: salesforce connector, inbound, outbound, streaming, poll, dataweave, datasense
:icons: font

A consumer key is required when setting up OAuth 2.0 configurations for the Salesforce connector. It is used by the OAuth 2.0 JWT and SAML bearer configurations and by the OAuth 2.0 Username Password configuration.

This procedure provides guidance on using Salesforce to create a consumer key. It explains how to create a connected app in Salesforce. However, note that the steps might differ somewhat in your Salesforce instance

Prerequisite:

This procedure assumes that you already have a certification file (such as `salesforce-cert.crt`). If not, you can produce one by generating a Java KeyStore and Public Key.

[[create-consumer-key]]
. Log into Salesforce, and go to Setup > Build > Create > Apps.
. Under the Connected App section, click New.
. Follow these steps to create a new connected app, and enter the following information in the appropriate fields:
+
* A name for the connected app.
* The API name.
* Contact email.
+
. Under API (Enable OAuth Settings), select Enable OAuth Settings:
+
* Enter the Callback URL.
* Select the Use Digital Signatures checkbox.
* Click Browse (or Choose File), and load your Salesforce certificate (for example, `salesforce-cert.crt`), which contains your public key.
+
In Studio, you typically store this in the workspace that contains your Mule application.
+
.. Add and Save these OAuth scopes to Selected OAuth Scopes:
+
Full Access (`full`) and Perform Requests On Your Behalf At Any Time (`refresh_token`, `offline_access`)
+
. Configure the Authorization Settings for the app:
+
Click Manage. Then under the OAuth Policies section, expand the Permitted Users dropdown, and select Admin Approved Users are Pre-Authorized. Then Save.
. Under the Profiles section, click Manage Profiles.
. Select your user profile, and then click Save.
. Go back to the list of Connected Apps: Build > Create > Apps.
. Under the Connected Apps section, select the connected app you created.

You can see the Consumer Key that you need to provide in your connector's configuration.

== See Also

xref:salesforce/salesforce-about-authentication.adoc[About Authentication through the Salesforce Connector]

xref:salesforce/salesforce-to-generate-keystore-file.adoc[To Generate a KeyStore and Public Key]

xref:salesforce/salesforce-connector-tech-ref.adoc[Salesforce Connector Technical Reference]

https://help.salesforce.com/articleView?id=connected_app_create.htm&language=en_US&type=0[Salesforce Documentation: Create a Connected App]