= About Authentication through the Salesforce Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To access the data in a Salesforce instance, you have to set up a configuration that supports the authentication with the Salesforce service you require.

You can configure the Salesforce connector to authenticate by Username Password or by an OAuth 2.0-based mechanism (OAuth JWT, OAuth SAML, or OAuth Username Password).

Username Password (Basic) authentication is generally is generally recommended for internal applications only. Important parameters:

* Username: Enter the Salesforce username. (required)
* Password: Enter the corresponding password. (required)
* Security Token: Enter the corresponding security token.

OAuth 2.0-based authentication provides better security but requires additional parameters. You might use it if your service is exposed to external users. Important parameters:

* Consumer Key - The consumer key for the Salesforce connected app.
* Consumer Secret - The consumer secret for the connector to access Salesforce.
* Key Store - The path to the key store used to sign data during authentication. Only Java key store format is allowed.
* Store Password - Key store password.
* Principal - Username of desired Salesforce user.

All configuration parameters are described in _Salesforce Connector Reference_. Salesforce documentation provides more information about authentication through Salesforce.

== See Also

xref:salesforce/salesforce-to-create-consumer-key.adoc[To Create a Consumer Key]

xref:salesforce/salesforce-to-generate-keystore-file.adoc[To Generate a Keystore File]

xref:salesforce/salesforce-connector-tech-ref.adoc[Salesforce Connector Technical Reference]

https://developer.salesforce.com/docs[Salesforce developer documentation]

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_login.htm[Salesforce documentation: Basic Authentication]

https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_oauth_web_server_flow.htm&language=en_US[Salesforce documentation: OAuth 2.0]

https://help.salesforce.com/HTViewHelpDoc?id=remoteaccess_oauth_jwt_flow.htm[Salesforce documentation: OAuth 2.0 JWT Bearer]

https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_oauth_SAML_bearer_flow.htm&language=en_US[Salesforce documentation: OAuth 2.0 SAML Bearer]

https://help.salesforce.com/articleView?id=remoteaccess_oauth_username_password_flow.htm&type=0&language=en_US[Salesforce documentation: OAuth 2.0 Username-Password]