// TODO: Need better business purpose in the about section
= About the TD Ameritrade Connector

The TD Ameritrade connector for MuleSoft Anypoint platform enables integration to the TD Ameritrade Web API.
The Connector lets you perform all the operations available in the WEB API.

== Prerequisites

This document assumes that you are familiar with TD Ameritrade, Mule Concepts, Anypoint Connectors, and Anypoint Studio.

//TODO: Cover this in release notes. Where should release notes go?
You need login credentials to test your connection to your target resource.
For hardware and software requirements and compatibility information, see the Connector Release Notes.

To use this connector with Maven, view the pom.xml dependency information in the Dependency Snippets in Anypoint Exchange.

== Authentication

This document assumes that you are familiar with TD Ameritrade, Mule, Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and Global Elements. You also need a TD Ameritrade account and credentials for creating your access and refresh token. TD Ameritrade API uses an OAuth 2.0 Authentication, which requires a username and a password.

Use the following steps to create the authentication tokens.

//TODO: Add link to the TD Ameritrade portal
1. Navigate to the TD Ameritrade website and create an account. After the registration, you get two sets of credentials: Site and MyApp.
1. Use instructions available on TD Ameritrade developer portal to get access token and refresh token. Use refresh token that you can use for 90 days to request access tokens and allow you to authenticate without needing a server. Note that you will need to update your app's refresh token at least once every 90 days to keep it functioning. For detailed steps, see set up simple auth for local apps.

== About Connector Namespace and Schema
//TODO: Check instructions in other connector docs for this.

When designing your application in Studio, drag the connector from the palette to the Anypoint Studio canvas. This automatically populates the XML code with the connector namespace and schema location.

* Namespace: http://www.mulesoft.org/schema/mule/td
* Schema Location: http://www.mulesoft.org/schema/mule/td/current/mule-td.xsd

== Connect in the Design Center
//TODO: Add instructions

// In this section, explain how to use the connector in the Design Center. Optionally, add a table explaining the configurations required for each of the operations as a part of the steps to configure the connector as a component. For example, see Cassandra and Marketo.
// Connect in Anypoint Studio

== Install TD Ameritrade Connector in Anypoint Studio

1. In Anypoint Studio, click the Exchange icon in the Studio taskbar.
2. Click Login in Anypoint Exchange.
3. Search for this connector and click Install.
4. Follow the prompts to install this connector.

== Configure in Anypoint Studio

// TODO: verify this
NOTE: Ensure that you have a new refresh token before you configure the connector in Anypoint Studio. See Authentication for more information.

// TODO: ALl configuration instructions are to be verified.

== Use Cases

=== To Create a Watchlist

After the Listener Drag and drop a “Set Payload” in the canvas, where the value is as follows,

[source, json]
----
{
    "name": "TestList-0002",
    "watchlistItems": [
        {
            "quantity": 1,
            "averagePrice": 0,
            "commission": 0,
            "purchasedDate": "2002-10-10",
            "instrument": {
                "symbol": "B",
                "assetType": "EQUITY"
            }
        }
    ]
}
----
Change the data as you like, but the format should be the same so that the API accepts the payload.

* Now drag and drop the “Create Watchlist” connector operation beside the listener.
* There is only one required parameter “Account id”, and set the payload as shown below,
// TODO: Add image
* Also drag and drop a transform message and set the output as
// TODO: Add image
* If there is no error on the canvas, run the project and test it using:
// TODO: Add image

Test the connector using the request,
`http://localhost:8082/createWatchlist`

The xml Snip for the Get Option Chain is as follows:

[source, XML]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core" xmlns:td="http://www.mulesoft.org/schema/mule/td"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/td http://www.mulesoft.org/schema/mule/td/current/mule-td.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd">
	<flow name="createWatchlistFlowFlow" doc:id="d82531e4-bcb7-4a07-ab94-fae29652d4e4" >
		<http:listener doc:name="8082/createWatchlist" doc:id="b8bdf948-91ca-46ff-9277-f79ee973206d" config-ref="HTTP_Listener_config" path="createWatchlist"/>
		<set-payload value='#[{
    "name": "TestList-0002",
    "watchlistItems": [
        {
            "quantity": 1,
            "averagePrice": 0,
            "commission": 0,
            "purchasedDate": "2002-10-10",
            "instrument": {
                "symbol": "B",
                "assetType": "EQUITY"
            }
        }
    ]
}]' doc:name="Request Body JSON" doc:id="2ff74e95-eeae-437a-afe5-7fe9cf367bdb" />
		<td:create-watch-list doc:name="Create watchlist" doc:id="830f8c2e-2496-4a4c-957b-1b01424259b6" config-ref="TD_Ameritrade_Config" accountId="494381739" watchList="#[payload]"/>
		<ee:transform doc:name="Transform Message" doc:id="4768efff-1237-4f80-b8ba-da14e1e6110f" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0 output application/json payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
</mule>
----

=== To Delete a Watchlist

* Drag and drop a “Delete watchlist” operation from the TD Ameritrade connector, and inside the connector properties, select the configuration we have created before.
* In the connector configuration, add your Account id and the Watchlist id you want to delete.
// TODO : Add image
* Also add a transform message to the canvas to convert the output to JSON,
// TODO: Add image
* You can run the project and once deployed, you can use either POSTMAN or ARC to test it. You can test it with the following request,  `http://localhost:8082/deleteWatchlist`

The XML snippet of the above flow is:

[source, XML]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core" xmlns:td="http://www.mulesoft.org/schema/mule/td"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/td http://www.mulesoft.org/schema/mule/td/current/mule-td.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd">
	<flow name="deleteWatchlistFlowFlow" doc:id="f95f79ca-c9cf-4a44-8ac7-38307ee20f10" >
		<http:listener doc:name="8082/deleteWatchlist" doc:id="3f42e78b-598f-4d6a-a593-0039320ab078" config-ref="HTTP_Listener_config" path="deleteWatchlist"/>
		<td:delete-watchlist doc:name="Delete watchlist" doc:id="5b1d99b4-765d-425f-891f-f217d54b23a1" config-ref="TD_Ameritrade_Config" accountid="494381739" watchlistid="TestList-0002"/>
		<ee:transform doc:name="Response Body" doc:id="916e29a8-c1e9-4c57-a214-4f2a78c8a40a" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0 output application/json payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
</mule>
----

=== To Get a watchList

* Now drag and drop the “Get Watchlist” connector operation beside the listener.
* Both the “Account id” and “Watchlist id” are required parameters, because the API needs both to cancel your order. Fill both correctly.
// TODO: Add image
* Add a transform message to the canvas after the connector to convert the message to json,
// TODO: Add image
* If there is no error on the canvas, run the project and test it using:
// TODO: Add image
Test the flow using the request `http://localhost:8082/getWatchlist`

The xml Snip for the Cancel Order is as follows:

[source, XML]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:td="http://www.mulesoft.org/schema/mule/td" xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
http://www.mulesoft.org/schema/mule/td http://www.mulesoft.org/schema/mule/td/current/mule-td.xsd">
	<flow name="getWatchlistFlowFlow" doc:id="7f2b1941-47eb-490b-a290-fdf8a721d84b" >
		<http:listener doc:name="8082/getWatchlist" doc:id="bcb96327-b4a6-4aeb-920f-c56e8627b44a" config-ref="HTTP_Listener_config" path="getWatchlist"/>
		<td:get-watchlist doc:name="Get watchlist" doc:id="75f45f2f-f717-4b3a-93f6-d6a3da0b3b9e" config-ref="TD_Ameritrade_Config" accountId="494381739" watchlistId="1225172678"/>
		<ee:transform doc:name="Get Watchlist Response" doc:id="dd2fa1fb-ddb8-4f2b-af98-1e58e212634a" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0 output application/json payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
</mule>
----

=== To Replace a Watchlist

After the Listener Drag and drop a “Set Payload” in the canvas, where the value is as follows,

[source, JSON]
----
{
    "name": "replaceWatchlist",
    "watchlistId": "1219680531",
    "watchlistItems": [
        {
            "quantity": 6,
            "averagePrice": 0,
            "commission": 0,
            "purchasedDate": "2002-10-10",
            "instrument": {
                "symbol": "A",
                "assetType": "EQUITY"
            }
        }
    ]
}
----

* Drag and drop a “Replace Watchlist” operation from the TD Ameritrade connector, and inside the connector properties, select the configuration we have created before.
// TODO: Add image (2)
* You can run the project and once deployed, you can use either POSTMAN or ARC to test it.
* You can test it with the following request, (In the below request, the Listener path is /test) http://localhost:8082/replaceWatchlist
* The XML snippet of the above flow is:
// TODO: Add image

[source, XML]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core" xmlns:td="http://www.mulesoft.org/schema/mule/td"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/td http://www.mulesoft.org/schema/mule/td/current/mule-td.xsd
http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd">
	<flow name="replaceWatchlistFlowFlow" doc:id="7b3c19a3-f49f-4da4-899c-15a09f93e5a1" >
		<http:listener doc:name="8082/replaceWatchlist" doc:id="8a3bea02-b074-4081-82d6-65279ce71728" config-ref="HTTP_Listener_config" path="replaceWatchlist"/>
		<set-payload value='#[{
    "name": "replaceWatchlist",
    "watchlistId": "1219680531",
    "watchlistItems": [
        {
            "quantity": 6,
            "averagePrice": 0,
            "commission": 0,
            "purchasedDate": "2002-10-10",
            "instrument": {
                "symbol": "A",
                "assetType": "EQUITY"
            }
        }
    ]
}]' doc:name="Replace watchlist request body" doc:id="485fe37c-a7b2-4206-8424-54f28872692b" />
		<td:replace-watchlist doc:name="Replace watchlist" doc:id="d5319056-0686-4180-83a6-3e208edabc3c" config-ref="TD_Ameritrade_Config" accountId="494381739" watchlistId="1219680531" watchlist="#[payload]"/>
		<ee:transform doc:name="Response body" doc:id="3c135c0c-c859-4d66-8a4e-1d1b72ed2146" >
			<ee:message >
				<ee:set-payload ><![CDATA[%dw 2.0 output application/json payload]]></ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
</mule>
----

== See Also
// TODO Add links
