= Web Service Consumer Connector- Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Web Service Consumer Connector Version 1.5

Anypoint Connector for Web Service Consumer (Web Service Consumer Connector) consumes a SOAP Web service
to acquire data from an external source. In many cases, you can use an existing MuleSoft connector, such as Workday or ServiceNow, to connect to a service provider. When no connector is available for a specific Web service, the easiest way to consume the service from a Mule app is to use the Web Service Consumer Connector.

The main features of this connector include:

* Consuming DOC Literal Web services.
* SOAP multipart messages.
* SOAP Headers.
* DataSense support for SOAP Headers, SOAP Body, and Attachment.
* Embedded DataWeave transformations inside the operation.
* Support and Unified experience for SOAP with attachments and MTOM handling.
* Custom HTTP configuration as transport (runtime and design time).
* Web Service Security (WS Security) support.

NOTE: RPC WSDLs are not supported by the Web Service Consumer.

Release Notes: xref:release-notes::connector/connector-wsc.adoc[Web Service Consumer Release Notes] +
Exchange: https://www.mulesoft.com/exchange/org.mule.connectors/mule-wsc-connector/[Web Service Consumer Connector]

== POM File Information

[source,xml,linenums]
----
<dependency>
  <groupId>org.mule.connectors</groupId>
  <artifactId>mule-wsc-connector</artifactId>
  <version>RELEASE</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

Mule converts RELEASE to the latest version. To specify a version, view
Anypoint Exchange and click *Dependency Snippets*.

== See Also

* xref:web-service-consumer-reference.adoc[Web Service Consumer Technical Reference]
* xref:web-service-consumer-configure.adoc[Configure the WSC]
* xref:web-service-consumer-consume.adoc[Consume a Service]
