= SAP S/4HANA OData Cloud Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Premium]

SAP S/4HANA OData Cloud Connector v2.1

Anypoint Connector for SAP S/4HANA OData Cloud (SAP S/4HANA OData Cloud Connector) provides full support for the query, get, create, update, delete entities, execute functions, and execute batch requests using the OData API exposed by SAP S/4HANA.

The connector enables you to perform operations to:

* Create, update, and delete entities
* Retrieve a single entity
* Query multiple entities
* Invoke a remote function
* Execute batch requests that consist of multiple requests

For software requirements and compatibility
information, see the xref:release-notes::connector/sap-s4-hana-connector-release-notes-mule-4.adoc[SAP S4/HANA Connector Release Notes].


== Prerequisites

Before you create an app and use this connector, you must:

* Have a developer account or other valid SAP S/4HANA instance
* Have a MuleSoft Enterprise license
* Be familiar with: 
** SAP S/4HANA OData
** Mule runtime engine (Mule)
** Anypoint Connectors
** Anypoint Studio essentials

== Audience

* Starting user -- To create your Mule app,
see xref:sap/sap-s4hana-cloud-connector-studio.adoc[Studio Configuration].  The
xref:sap/sap-s4hana-cloud-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Power user - Read the xref:sap/sap-s4hana-cloud-connector-xml-maven.adoc[XML and Maven Support],
and xref:sap/sap-s4hana-cloud-connector-examples.adoc[Examples] topics.

== Common Use Cases For the Connector

Perform CRUD operations on entity types of SAP S/4HANA's OData API and process the response.

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
you can use as a starting point for your app, as well as examples that illustrate a complete solution.

== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app with xref:sap/sap-s4hana-cloud-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:release-notes::connector/sap-s4-hana-connector-release-notes-mule-4.adoc[SAP S/4HANA OData Cloud Connector Release Notes]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-sap-s4hana-cloud-connector/[SAP S/4HANA OData Cloud Connector on Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
