= SAP S/4HANA SOAP Cloud - Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

To configure a connector in Anypoint Studio:

. Add the connector to your Studio project
. Configure the connector
. Configure an input source for the connector

== Add the Connector to Your Project

Anypoint Studio provides two ways to add the connector to your Studio project: from 
the Exchange button in the Studio taskbar or from the Mule Palette view.

=== Add the Connector Using Exchange

. In Studio, create a Mule project.
. Click the Exchange icon *(X)* in the upper-left of the Studio task bar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for SAP S/4HANA SOAP Cloud.
. Select the SAP S/4HANA SOAP Cloud connector and click *Add to project*.
. Follow the prompts to install the connector.

=== Add the Connector in Studio

. In Studio, create a Mule project.
. In the Mule Palette view, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type SAP S/4HANA SOAP Cloud in the search field.
. Click the SAP S/4HANA SOAP Cloud connector name in *Available modules*.
. Click *Add*.
. Click *Finish*.

== Configure an Input Source

This connector does not provide an input source operation. You can configure an input source for the connector using *HTTP Listener*, or *Scheduler*.

== Configure the Connector

The required fields for this connector are:

[%header,cols="20s,20a,60a"]
|===
| Name | Type | Description 
|Name | String | The name for this configuration. Connectors reference the configuration with this name.
The only supported connection type is Basic Authentication. &#8224;* 
| The connection types to provide to this configuration
| Service base URL a| String |  The base URL of the service on SAP S/4HANA to be accessed from the connector.
| Username a| String |  The account username with which to log into SAP S/4HANA.
| Password a| String |  The account password with which to log into SAP S/4HANA.
|===

&#8224;* Basic Authentication is the simplest way of enforcing access controls because it does not require cookies, session identifiers, or login pages. Instead, it uses standard fields in the HTTP header, removing the need for handshakes. This mechanism provides no confidentiality protection for the transmitted credentials, which are encoded with Base64 in transit, but not encrypted or hashed in any way.

== Next Step

After configuring the SAP S/4HANA SOAP Cloud Connector for use in Studio, see the
xref:sap/sap-s4hana-soap-connector-examples.adoc[Examples] 
topic for more Studio information.

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
