= SAP XML and Maven Support - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

If you manually code a Mule application in XML either from the Studio XML editor 
or from a text editor, perform the following actions to get access to the connector:

. Add the namespace for the connector to your XML flow.
. Add dependency information to your Maven `pom.xml` file.

In the Studio visual editor, when you drag a connector from the palette to the 
canvas, Studio automatically populates the XML code with the connector namespace and schema location.

== Add a Namespace for the Connector

Paste the following code inside the `<mule>` tag of the header of your configuration XML:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/sap 
http://www.mulesoft.org/schema/mule/sap/current/mule-sap.xsd
----

This example shows how the namespace statements are placed in the `<mule>` XML block: 

[source,xml,linenums]
----
<mule xmlns:sap="http://www.mulesoft.org/schema/mule/sap" 
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:file="http://www.mulesoft.org/schema/mule/file" 
	xmlns="http://www.mulesoft.org/schema/mule/core" 
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core 
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/file 
	http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
	http://www.mulesoft.org/schema/mule/http 
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/core 
	http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
	http://www.mulesoft.org/schema/mule/sap 
	http://www.mulesoft.org/schema/mule/sap/current/mule-sap.xsd">
----

== Add a POM File Dependency 

The `pom.xml` Maven file generated by Anypoint Studio contains dependencies for a Mule app. When you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to this connector. The Mule runtime engine translates the `LATEST` dependency keyword to the current version.

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-sap-connector</artifactId>
  <version>LATEST</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

To obtain the most up-to-date `pom.xml` file information, access the connector in 
https://www.mulesoft.com/exchange/[Anypoint Exchange] and click *Dependency Snippets*.

For JCo library support, add these dependencies:

[source,xml,linenums]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.mule.tools.maven</groupId>
            <artifactId>mule-maven-plugin</artifactId>
            <version>${mule.maven.plugin.version}</version>
            <extensions>true</extensions>
            <configuration>
                <sharedLibraries>
                    <sharedLibrary>
                        <groupId>com.sap.conn.jco</groupId>
                        <artifactId>com.sap.conn.jco.sapjco3</artifactId>
                    </sharedLibrary>
                    <sharedLibrary>
                        <groupId>com.sap.conn.idoc</groupId>
                        <artifactId>com.sap.conn.idoc.sapidoc3</artifactId>
                    </sharedLibrary>
                    <sharedLibrary>
                        <groupId>com.sap.conn.jco</groupId>
                        <artifactId>com.sap.conn.jco.libsapjco3</artifactId>
                    </sharedLibrary>
                </sharedLibraries>
            </configuration>
        </plugin>
    </plugins>
</build>
----

== Next

After completing XML and Maven, you can try out the SAP xref:sap/sap-connector-examples.adoc[Examples].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
