= SAP Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Premium

SAP Connector v4.1 and v4.2

The SAP connector enables the integration of data to and from SAP NetWeaver-based and external systems.

Note: This connector is only available in Mule 4 and Studio 7, and is not available in the Design Center feature of Anypoint Platform.

This connector requires a separate license. Contact MuleSoft to evaluate or use this connector in production.

Mule runtime supports SAP integration through our Anypoint Connector for SAP, an SAP-certified Java connector that leverages the SAP Java Connector (JCo) libraries, thus allowing Mule applications to:

* Execute BAPI functions over the RFC protocol, supporting the following types:
** Synchronous RFC (sRFC)
** Transactional RFC (tRFC)
** Queued RFC (qRFC)
* Act as a JCo Server to be called as a BAPI over sRFC, tRFC, and qRFC.
* Send IDocs over tRFC and qRFC.
* Receive IDocs over tRFC and qRFC.
* Transform SAP objects (JCo Function/BAPI & IDocs) to and from XML.

== About Connectors

Anypoint Connectors are extensions of Mule that let you work with external systems 
such as Salesforce, ServiceNow, Workday, Twitter, and more to send and receive information from these systems to create something new. Anypoint Connectors let you connect Mule applications to APIs and resources. 

A connector lets you send and receive data over a protocol, or to and from an API. Use 
this information to work with Anypoint Studio to adjust the UI settings to enable the connector to work with a Mule application.

== Prerequisites

This document assumes you have:

* A working knowledge of the SAP business context and in particular, the SAP R/3 Business Suite.
* A basic understanding of the SAP NetWeaver Platform from an administration point of view.
* Knowledge of the ABAP language.
* Login credentials to test your connection to your target resource.

For software requirements and compatibility information, see the 
xref:release-notes::connector/sap-connector-release-notes-mule-4.adoc[SAP Connector Release Notes].

See also: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-sap-connector/[SAP Connector in Anypoint Exchange]

*Note:* This connector version is not supported for use in Design Center.

== Audience

* Starting user -- Read this Get Started document. Configure your Mule application in 
xref:sap/sap-connector-studio.adoc[Anypoint Studio]. The xref:sap/sap-connector-config-topics.adoc[Additional Configuration Information] topic
helps you extend your understanding of SAP actions.
* Power user - Read xref:sap/sap-connector-xml-maven.adoc[XML and Maven Support], 
the xref:sap/sap-connector-config-topics.adoc[Additional Configuration Information] topic, 
and xref:sap/sap-connector-examples.adoc[Examples].
////
Audience without the "Additional Configuration Information" topic:
== Audience
* Starting user -- Read Get Started (this document) and configure your Mule application in 
xref:sap/sap-connector-design-center.adoc[Design Center] or 
xref:sap/sap-connector-studio.adoc[Anypoint Studio]. 
* Power user - Read xref:sap/sap-connector-xml-maven.adoc[XML and Maven Support]
and xref:sap/sap-connector-examples.adoc[Examples].
////

== Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates and examples 
to simplify your use of the Salesforce connector. Templates provide a starting point 
that enable you to add additional functionality. Examples provide a complete solution.

== SAP Exchange Examples and Templates

* *General:* https://www.mulesoft.com/exchange/org.mule.templates/template-apiled-system-account-sap/[Account System API - SAP Implementation Template],
https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sfdc.wday.sap.db-account-broadcast/[Salesforce to Salesforce, Workday, SAP, and Database Account Broadcast]

* *Salesforce and SAP:* https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-account-aggregation/[Account Aggregation], 
https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-customer-bidirectional-sync/[Account Customer Bidirectional Sync], 
https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-opportunity-aggregation/[Opportunity Aggregation], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-product-aggregation/[Product Aggregation], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-product-bidirectional-sync/[Product Bidirectional Sync]

* *Salesforce to SAP:* https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-account-broadcast/[Account Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-account-migration/[Account Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-opportunity-broadcast/[Opportunity Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-opportunity-migration/[Opportunity Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-sfdc2sap-product-broadcast/[Product Broadcast]

* *SAP to Salesforce:* https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-contact-broadcast/[Contact Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-contact-migration/[Contact Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-customer-broadcast/[Customer Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-customer-migration/[Customer Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-product-broadcast/[Product Material Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2sfdc-material-migration/[Product Material Migration]

* *SAP to Workday:* https://www.mulesoft.com/exchange/org.mule.templates/template-sap2wday-employee-migration/[Employee Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2wday-organization-broadcast/[Organization Broadcast], https://www.mulesoft.com/exchange/org.mule.templates/template-sap2wday-organization-migration/[Organization Migration]

* *Workday and SAP:* 
https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sap-organization-aggregation/[Organization Aggregation], https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sap-worker-aggregation/[Worker (Employee) Aggregation]

* *Workday to SAP:* https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sap-worker2employee-migration/[Worker (Employee) Migration], https://www.mulesoft.com/exchange/org.mule.templates/template-wday2sap-worker-broadcast/[Worker Broadcast]

== Next

Now that you've started, try 
xref:sap/sap-connector-studio.adoc[Anypoint Studio].

== See Also

* The SAP connector uses the RFC protocol to connect to NetWeaver Application Servers (NWAS)
* http://www.cipherbsc.com/solutions/sap-erp-central-component-erp-ecc/[ECC] and https://help.sap.com/viewer/p/SAP_CUSTOMER_RELATIONSHIP_MANAGEMENT[CRM] run on top of NWAS, as other SAP solutions do, and hence any customer using the connector may access those systems
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
