= SAP Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

To configure a connector in Anypoint Studio follow this process:

. Install the connector.
. Configure the connector.
. Configure an input source for the connector.

== Install the Connector

. In Anypoint Studio, click the Anypoint Exchange icon in the Studio task bar.
. Click *Login* in Anypoint Exchange and supply your Anypoint Platform username and password.
. Search for the SAP connector, click on the connector in Exchange, and click *Add to project*.
. Follow the prompts to install the connector.

== Configure the Connector

If needed, you can create a global SAP element if you need more than one SAP connector instance in your Mule project.

The SAP connector object holds the configuration properties that allow you to connect to the SAP server.

To create a configuration for an SAP connector, complete the following steps:

. Go to Global Elements section, and click Create.
. Select either SAP Inbound or SAP Outbound in the Connector Configuration section
. In the General tab pane, enter the required parameters for defining an SAP connection, which your SAP system administrator should supply.

The SAP Global Element Configuration allows you to define connection properties as well as to easily add the required SAP dependencies to your project.

For ease of use, the SAP connector only shows the most common properties as connector parameters. To configure a property that is not listed in the Properties panel, consult the "Extended Properties" section in this guide.

The minimum required attributes to define are:

[[gepparms]]
[%header%autowidth.spread]
|===
|Field |Description
|Application Server Host | SAP endpoint
|Username | Username of an authorized SAP user.
|Password | Password credential of an authorized SAP user.
|System Number | System number used to connect to the SAP system.
|Client| The SAP client ID (usually a number) used to connect to the SAP system.
|Login Language | The language to use for the SAP connection. For example, EN for English.
|===

As a best practice, use property placeholder syntax to load the credentials in a more simple and reusable way.

Click the Test button to verify that the connection to the SAP instance succeeded. If the credentials are correct you should receive a Test Connection Successful message.

== SAP Libraries

See xref:sap/sap-connector-config-topics.adoc[Additional Configuration Information] for SAP library install information as well as how to define extended properties, and SAP JCO notes.

== Configure an Input Source

Configure an input source for this connector such as a connector operation, an HTTP Listener, or Scheduler.

The following operations for this connector can be put in the Source area of the Studio canvas:

* Document Source
* Function Source

Both operations have these fields: *Configuration* name, *Operation Timeout, Gateway Host, Gateway Service, Program ID, Connection Count, Targeted Function, Transactional Action, Primary Node, Streaming Strategy, Redelivery Policy*, and *Reconnection Strategy*. Function Source also provides the *Response* payload.

== Next

Now that you have completed configuring Studio, 
see the xref:sap/sap-connector-config-topics.adoc[Additional Configuration Information] topic
for more configuration ideas.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
