= SAP S/4HANA SOAP Cloud Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Premium]

SAP S/4HANA SOAP Cloud Connector v2.0

Anypoint Connector for SAP S/4HANA SOAP Cloud (SAP S/4HANA SOAP Cloud Connector) provides full support for the SOAP APIs exposed by S/4HANA Cloud ERP. This connector enables you to automatically discover SOAP services enabled on your SAP S/4HANA instance and to invoke the SOAP service and associated operations.

For software requirements and compatibility
information, see the xref:release-notes::connector/sap-s4-hana-soap-cloud-connector-release-notes-mule-4.adoc.adoc[SAP S/4HANA SOAP Cloud Connector Release Notes] 

== Prerequisites

Before you create an app and use this connector, you must:

* Have a developer account or other valid SAP S/4HANA instance.
* Have a MuleSoft Enterprise license.
* Be familiar with: 
** SAP S/4HANA OData
** Mule runtime engine (Mule)
** Anypoint Connectors
** Anypoint Studio essentials

== Audience

* Starting user -- To create your Mule app,
see xref:sap/sap-s4hana-soap-connector-design-center.adoc[Design Center Configuration]
or xref:sap/sap-s4hana-soap-connector-studio.adoc[Studio Configuration].  The
xref:sap/sap-s4hana-soap-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Power user - Read the xref:sap/sap-s4hana-soap-connector-xml-maven.adoc[XML and Maven Support],
and xref:sap/sap-s4hana-soap-connector-examples.adoc[Examples] topics.


== Common Use Cases For the Connector

Send an XML request to SAP S/4HANA's SOAP API and print a response.

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
you can use as a starting point for your app, as well as examples that illustrate a complete solution.

== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app with
xref:sap/sap-s4hana-soap-connector-design-center.adoc[Design Center] or xref:sap/sap-s4hana-soap-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-sap-s4hana-soap-cloud-connector/[SAP S/4HANA SOAP Cloud Connector on Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
