= SAP S/4HANA SOAP Cloud Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

SAP S/4HANA SOAP Cloud Connector Version Major.Minor

Release Notes: xref:release-notes::connector/sap-s4hana-soap.adoc[SAP S/4HANA SOAP Cloud Connector Release Notes]

// Anypoint Connector for SAP S/4HANA SOAP Cloud provides ... 

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect 
to APIs and resources on external systems, such as Salesforce, SAP S/4HANA SOAP Cloud, ServiceNow,
and Twitter.

== Prerequisites

Before creating an app, you must have access to the SAP S/4HANA SOAP Cloud target resource and 
Anypoint Platform. You also need understand how to create a Mule app using 
Design Center or Anypoint Studio.

// If your connector has other prerequisites, list them here.

== Audience

* Starting user -- To create your Mule app,
see xref:sap/sap-s4hana-soap-connector-design-center.adoc[Design Center Configuration]
or xref:sap/sap-s4hana-soap-connector-studio.adoc[Studio Configuration]. The
xref:sap/sap-s4hana-soap-connector-config-topics.adoc[Additional Configuration Information]
topic helps extend your understanding of the SAP S/4HANA Cloud SOAP connector. The
xref:sap/sap-s4hana-soap-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Power user - Read the xref:sap/sap-s4hana-soap-connector-xml-maven.adoc[XML and Maven Support],
xref:sap/sap-s4hana-soap-connector-config-topics.adoc[Additional Configuration Information],
and xref:sap/sap-s4hana-soap-connector-examples.adoc[Examples] topics.

== OAuth Types

// List the OAuth types for this connector

== Input Sources (Triggers)

Anypoint Connector for SAP S/4HANA SOAP Cloud enables you to start an app using these input sources:

* operation: description
* operation: description
* etc

Alternatively, you can use HTTP to listen for inputs or use a scheduler to choose when to run your app.

== Common Use Cases For the Connector

// List common use cases for the SAP S/4HANA SOAP Cloud Connector and provide 
// a link to the xref:sap/sap-s4hana-soap-connector-examples.adoc[Examples] use cases.

== Learn Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
you can use as a starting point for your app, as well as examples that illustrate a complete solution.

// If available for this connector, list up to 10 Exchange templates and examples.
// Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).

== Next Step

After you have met the prerequisites and experimented with templates and examples, you are ready to create an app with
xref:sap/sap-s4hana-soap-connector-design-center.adoc[Design Center] or xref:sap/sap-s4hana-soap-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/?search=sap-s4hana-soap&type=connector[Anypoint Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
