= Upgrading and Migrating Anypoint MQ Connector Connector to 4.x 


Upgrade Anypoint Connector for Anypoint MQ (Anypoint MQ Connector) to version 4.x.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|3.x |4.x
|===

== Changes in This Release

Anypoint MQ Connector 4.x includes support for the Connected Apps feature.

The changes included in this version break backward compatibility.

This release contains the following changes:

* 
 ** 


== Upgrade Prerequisites

Before you perform the upgrade, you must create a backup of your files, data, and configurations in case you need to revert to the previous version.

== Upgrade Steps

Follow these steps to perform the upgrade to Anypoint MQ Connector 4.x:

. In Studio, create a Mule project.
. In the Mule Palette view, click *Search in Exchange*.
. In Add Modules to Project, type `Anypoint MQ` in the search field.
. In Available modules, select *Anypoint MQ Connector* and then click *Add*.
. Click *Finish*. +
Anypoint Studio upgrades the connector automatically.
. Verify that the `mq-connector` dependency version is `4.0.0` in the pom.xml.


== Post Upgrade Steps

After you install the latest version of the connector, follow these steps to complete the upgrade:

. In Anypoint Studio, verify that there are no errors in the *Problems* or *Console* views.
. Check the project pom.xml and verify that there are no problems.
. Test the connection and verify that the operations work.

== Troubleshooting

If there are problems with caching the parameters and caching the metadata, try restarting Anypoint Studio.

=== Reverting the Upgrade

If it is necessary to revert to the previous version of Apache Kafka Connector, in Anypoint Studio, change the `mq-connector` dependency version `4.0.0` in the project's pom.xml to the previous version.


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
