= Salesforce CDP Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Salesforce CDP (Salesforce CDP Connector) provides customers a pipeline to send data from both non-Salesforce and Salesforce properties alike into Salesforce CDP.

This connector works with the Salesforce CDP Bulk and Streaming API, depending on the operation you configure. Each API call uses a request/response pattern over an HTTPS connection. All required request headers, error handling, and HTTPS connection configurations are built into the connector.
For information about compatibility and fixed issues, see the Salesforce CDP Connector Release Notes. 

== Prerequisites

To use this connector, you must be familiar with:

* The Salesforce CDP API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Salesforce CDP target resource
* Anypoint Platform
* Anypoint Studio version 7.3.x or later

== Common Use Cases For the Connector

These are some common use cases for Salesforce CDP Connector:

* Stream data via upsert and delete object endpoints of the Ingestion API Connector
* Query CDP objects
* Create a bulk job, upload job data, close/abort the job, get job status and delete the job

For examples, see xref:salesforce-cdp-connector-examples.adoc[Salesforce CDP Connector Examples] use cases.

== Connection Types

Salesforce CDP connections use the following authentication types:

* OAuth JWT +
Uses OAuth 2.0 with a JSON Web token (JWT) request for user authentication
* OAuth Username Password +
Uses OAuth 2.0 with a user and password for authentication


For information about configuring authentication types, see xref:salesforce-cdp-connector-studio.adoc[Use Studio to Configure Salesforce CDP Connector].


== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:salesforce-data-cloud-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:salesforce-cdp-connector-reference.adoc[Salesforce CDP Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
