= Salesforce CDP Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]


Anypoint Connector for Salesforce CDP (Salesforce CDP Connector) provides ...

For information about compatibility and fixed issues, see the Salesforce CDP Connector Release Notes. 

== Prerequisites

To use this connector, you must be familiar with:

* The Salesforce CDP API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Salesforce CDP target resource
* Anypoint Platform
* Anypoint Studio version 7.3.x or later
//* If your connector has other prerequisites specific to this connector, list them here.

== Common Use Cases For the Connector
// Make the title singular if there is just one use case

// Add a lead in sentence and then list common use cases for the connector
These are some common use cases for Salesforce CDP Connector... 

For examples, see xref:salesforce-data-cloud-connector-examples.adoc[Salesforce CDP Connector Examples] use cases.

== Connection Types

Salesforce CDP connections use the following authentication types:

* OAuth JWT +
Uses OAuth 2.0 with a JSON Web token (JWT) request for user authentication
* OAuth username and password +
Uses OAuth 2.0 with a user and password for authentication


For information about configuring authentication types, see xref:salesforce-data-cloud-studio.adoc[Use Studio to Configure Salesforce CDP Connector].

== Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as a starting point for your app, as well as examples that illustrate a complete solution.

////
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:salesforce-data-cloud-connector-studio.adoc[Anypoint Studio].

== See Also
// Add useful links. Add link to upgrade topic if applicable
* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:salesforce-data-cloud-connector-reference.adoc[Salesforce CDP Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
