= Intercom Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Intercom (Intercom Connector) gives you access to the Intercom platform. This connector exposes the most important operations provided by the Intercom API.

For compatibility information and fixed issues, see the Intercom Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Intercom APIs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector


== Authentication Types

Intercom Connector connections use the following authentication methods:

* OAuth 2.0
* Unsecure connection provider


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:intercom-connector-reference.adoc[Intercom Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
