= EDIFACT EDI Connector 2.2 - Generate Control Numbers - Mule 4

The EDIFACT Connector provides three ways of generating control numbers on the generated EDIFACT payload from the Write operation.

== EDIFACT Connector managed global control numbers through control number keys

When to use: If your organization or your trading partner have a requirement to maintain uniqueness of interchange, group or transaction set control numbers across different identifier combinations and document types.

How to use:
* Set the configuration “Use supplied values” to False.
* Leverage the control number key configurations (at the configuration level, or operation level) to set a key that is unique for the partner. These values can be dynamically passed at the operation-level.

IMAGE

For example: The values for the interchange and group control number keys can be “PartnerName-UNB”, used across different identifiers and transaction types for the same partner.

== EDIFACT Connector managed identifier combination control numbers:

The connector automatically maintains the sequencing of control numbers for the sender/receiver identifier combination, initializing the value to the number specified in the configuration.

When to use: If you want the connector to automatically maintain the sequencing based on the sender/receiver identifiers and do not have requirements for global control numbers at a partner level.

How to use:
* This is the default behavior when no value is passed into the optional interchange / group / Transaction number key configurations.
* The Write configuration “Use supplied values” must be set to False.

== Bring your own control number

If you need to generate the control numbers and use them on the EDI payload, you can set the parameter “Use supplied values” to true, and map the desired control number on the payload in the DataWeave map.
