= Smartsheets Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Smartsheet (Smartsheet Connector) gives you access to the Smartsheet platform, which you can use to access and manage your organization's data and account information.

For compatibility information and fixed issues, see the Smartsheet Connector Release Notes.

== Prerequisites

To use this connector, you should be familiar with:

* The Smartsheet API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the Smartsheet target resource
* Anypoint Studio version 7.3.5 or later

== Authentication Types

Smartsheet Connector uses the OAuth 2.0 authentication type, which uses access tokens provided by the authorization server to get access to protected data.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
