= Smartsheets Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Smartsheet (Smartsheet Connector) synchronizes data and automates business processes between Smartsheet and third-party applications, either on-premises or in the cloud.

Smartsheet is a SaaS project management tool focused at enhancing team productivity and collaboration. Using Smartsheet, employees can easily manage projects and tasks through one integrated collaborative project management interface.

For compatibility information and fixed issues, see the Smartsheet Connector Release Notes.

== Prerequisites

To use this connector, you should be familiar with:

* The Smartsheet API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the Smartsheet target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Common use cases for Smartsheet Connector include the following:

* Improve cross-team communication
+
Automate a workflow in which users get notified via a messaging system like Slack any time a new work item is created in Smartsheet. Then, when a work item gets resolved, notify your team via messaging software such as Slack or Microsoft Teams.
+
* Enhance sales collaboration
+
Automate the lead tracking and nurturing process so that when a new lead or opportunity is created in your CRM system, a task is created and assigned to the appropriate user via Smartsheet.
+
* Streamline the contract approval process
+
Integrate your customer and partner management systems. For example, when a new contract is created in your CRM, create work items in Smartsheet and assign them to various stakeholders, such as legal, finance, procurement, business development, and sales.

== Authentication Types

Smartsheet Connector uses the OAuth 2.0 authentication type, which uses access tokens provided by the authorization server to get access to protected data.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
