= Agentforce Connector 1.2 
:lc-connector-name: agentforce

Agentforce Connector provides MuleSoft developers with the ability to seamlessly integrate with AI agents running in Salesforce’s Agentforce platform.

Agentforce Connector offers a group of capabilities that simplify agent integration in MuleSoft applications.

Use this connector to:

* Build AI agents in a low-code environment.
* Authenticate with a Salesforce org and discover active agents.
* Start a new session with an AI agent application.
* Extend the power of Agentforce by surfacing prompts from external applications to AI agents running in Salesforce.
* Orchestrate new, innovative experiences for your customers, partners and employees. 

For information about compatibility and fixed issues, see the Agentforce Connector release notes.

== Before You Begin

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Code Builder or Anypoint Studio

Before creating an app, you must have:

* Java 8, 11, or 17
* Apache Maven
* Anypoint Platform
* Credentials to connect with your Salesforce org
* The latest versions of Anypoint Code Builder or Anypoint Studio

To configure the connector, you must create a Connected App in Salesforce. For more information, see https://developer.salesforce.com/docs/einstein/genai/guide/agent-api-get-started.html[Get Started with the Agent API ].

== Common Use Cases for the Connector

These are some common use cases for the connector:

* Customer Service 
+
Increase human agents' productivity by having AI agents complete time-consuming tasks such as reviewing case history, analyzing reported issues, and looking up other related information.
* Sales 
+
Improve sales team efficacy by accelerating prospect research, generating customized collateral, and preparing contracts.
* Marketing 
+
Support marketing teams by drafting social media copy, executing market research, and completing campaign analysis.


== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:{lc-connector-name}-connector-studio.adoc[Anypoint Studio] or xref:{lc-connector-name}-connector-config-acb.adoc[Anypoint Code Builder].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[]
* xref:connectors::introduction/intro-config-use-acb.adoc[]
* xref:connectors::introduction/intro-config-use-studio.adoc[]
* xref:agentforce-connector-reference.adoc[Agentforce Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
