= XML Module Examples - Mule 4

To fully benefit from using XML module, see the following examples of configuring the module operations:

* xref:xml-xquery.adoc[Configure XQuery Transformations] +
Configure the *Xquery transform* operation to take XML input content and transform it based on XQuery expressions.
* xref:xml-xpath.adoc[Configure XPath Extractions] +
Configure the *Xpath extract* operation to evaluate Xpath expressions in XML input content and extract the result. The operation also enables you to set namespace mapping.
* xref:xml-xslt.adoc[Configure Xslt Transformations] +
Configure the *Xslt transform* operation to take XML input document and transform it using an XSL style sheet.
* xref:xml-xslt.adoc[Validate Documents against an XSD Schema] +
Configure the *Validate schema* operation to validate documents against an XSD schema.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
