= Using Anypoint Studio to Configure MuleSoft Inference Connector 1.2 
:exchange-search-name: mulesoft inference
:connector-name: MuleSoft Inference
:lc-connector-name: mulesoft-inference
:studio-connector-name: MuleSoft Inference Connector

include::connectors::partial$t-studio-partial.adoc[tags=topic-intro]

[[create-mule-project]]
== Create a Mule Project

include::connectors::partial$t-studio-partial.adoc[tags=create-project-intro]

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

Add MuleSoft Inference Connector to your Mule project to automatically populate the XML code with the connector's namespace and schema location and add the required dependencies to the project's `pom.xml` file:

. In *Mule Palette*, click *(X) Search in Exchange*.
. In *Add Dependencies to Project*, type `mulesoft inference` in the search field.
. Click *MuleSoft Inference Connector* in *Available modules*.
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio does not make that connector available to other projects in your Studio workspace.

[[configure-source]]
== Configure a Source

include::connectors::partial$t-studio-partial.adoc[tags=configure-source-intro]
You can configure one of these sources to use with MuleSoft Inference Connector:

include::connectors::partial$t-studio-partial.adoc[tags=listener-scheduler-descriptions]

include::connectors::partial$t-studio-partial.adoc[tags=listener-steps]

[[add-connector-operation]]
== Add a Connector Operation to the Flow

When you add a connector operation to your flow, you are specifying an action for that connector to perform.

To add an operation for MuleSoft Inference Connector, follow these steps:

. In *Mule Palette*, select *MuleSoft Inference Connector* and then select the operation to add.
. Drag the operation onto the Studio canvas, next to the source.

[[configure-global-element]]
== Configure a Global Element for the Connector

When you configure a connector, configure a global element that all instances of that connector in the app can use. Configuring a global element requires you to provide the authentication credentials that the connector requires to access the target inference provider.

include::connectors::partial$t-studio-partial.adoc[tags=property-placeholders]

To configure the global element for MuleSoft Inference Connector, follow these steps.

. Select the operation in the Studio canvas.
. On the properties screen for the operation, click the Add (*+*) icon to access the global element configuration fields.
. Choose from these configs.
+
* Image Generation Config
* Moderation Config
* Text Generation Config
* Vision Config
. Fill out the fields depending on the inference type. 
. Click *OK*.

[[configure-other-fields]]
== Configure Additional Connector Fields

After you configure a global element for the connector, configure the other required fields. The required fields vary depending on which connector operation you use.

For detailed configuration information for each operation type, see xref:mulesoft-inference-additional-config.adoc[MuleSoft Inference - Additional Configuration Information].

[[view-app-log]]
== View the App Log

include::connectors::partial$t-studio-partial.adoc[tags=view-app-log]

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-config-use-studio.adoc[Using Studio to Configure a Connector]
* xref:mulesoft-inference-connector-reference.adoc[MuleSoft Inference Connector Reference]
* https://help.salesforce.com[Salesforce Help] 