= Slack Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Slack (Slack Connector) enables access to the Slack platform. This connector exposes all of the operations provided by Slack's REST API

For compatibility information and fixed issues, see the Slack Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Slack API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the Slack target resource
* Anypoint Studio version 4.1.1 or later

== Common Use Cases for the Connector

*Need to add some use cases here*

For examples, see xref:slack-connector-examples.adoc[Examples].

== Audience

* New users, read:
** xref:slack-connector-studio.adoc[Use Studio to Configure the Connector] to create your Mule app
** xref:slack-connector-examples.adoc[Examples], which provide one or more use cases for the connector
* Advanced users, read:
** xref:slack-connector-xml-maven.adoc[XML and Maven Support]
** xref:slack-connector-examples.adoc[Examples], which provides one or more use cases for the connector

== Authentication Types

Slack Connector uses the OAuth 2.0 authentication type, which uses access tokens provided by the authorization server to get access to protected data.

For information about configuring the OAuth 2.0 authentication type, see xref:connector-studio.adoc[Use Studio to Configure Slack Connector].

== Next Step

After you complete the prerequisites, you are ready to create your own app and configure the connector using xref:slack-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
