= XML Module
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: XML, xpath, xslt, xquery, XSD, validation

Release Notes: xref:release-notes::mule-runtime/module-xml.adoc[XML Module Release Notes]

The XML Module can process and extract data from an XML document. Although DataWeave is recommended for most XML-related use cases, the XML module should be used for cases that involve the use of XML standards such as XSLT, XPath and XQuery, or XSD.

To use the XML module, you simply add it to your Mule app through the Studio or Flow Designer UI, or you can add the following dependency in your `pom.xml` file:

[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-xml-module</artifactId>
    <version>1.1.0</version> <!-- or newer -->
    <classifier>mule-plugin</classifier>
</dependency>
----

== See Also

xref:xml/xml-xpath.adoc[Using XPath with the XML Module]

xref:xml/xml-xslt.adoc[XSLT Transformations with the XML Module]

xref:xml/xml-schema-validation.adoc[Validating Documents against an XSD Schema with the XML Module]

xref:xml/xml-xquery.adoc[Using XQuery with the XML Module]

xref:xml/xml-reference.adoc[XML Module Documentation Reference]