= Using Anypoint Code Builder to Configure HTTP Connector


include::connectors::partial$configure-acb-connectors-partial.adoc[tag="individual-connector-config"]

=== Configuring Attributes for the HTTP Listener

The Anypoint Connector for HTTP (HTTP Connector) *Listener* component enables you to set up an HTTP server and trigger flows when receiving HTTP requests.

To configure the HTTP *Listener* attributes in the UI:

. Click the *Listener* component on the canvas.
+
The configuration UI opens.
. In the *General* tab, enter the relative path for the path set in the HTTP configuration element in *Path*. See xref:http-listener-ref.adoc#configure-paths[Configure Paths]. 
. Click the *Advanced* tab to configure the following attributes:
* *Allowed methods*
+
Comma-separated list of allowed HTTP methods by this listener. To allow all methods, do not define this attribute.
+
* *Response streaming mode*
+
Defines whether or not to use streaming when the response is sent.
+
* *Output MIME type*
+
Defines the format of the response.
+
* *Parameters* 
+
Add additional parameters for the *Listener*.
+
* *Output encoding*
* *Streaming Strategy*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:connectors::streaming-strategies.adoc[]
* *Primary node only*
+
Check this box to execute the *Listener* trigger on the primary node only when running in a cluster.
* *Redelivery policy*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:http-documentation.adoc#RedeliveryPolicy[Redelivery Policy].
* *Connection*
** *Reconnection strategy*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:http-documentation.adoc#reconnect[Reconnect] and xref:http-documentation.adoc#reconnect[Reconnect Forever].
* *Reponse*
+
See xref:http-documentation.adoc#HttpResponseAttributes[HTTP Respoonse Attributes]
+
* *Error Response*
+
An HTTP error response returns a status code for the error. 
+
** *Body*
+
The body of the error message.
** *Headers*
+
Headers to include in the error message.
** *Status code*
+
The status code of the error response, for example `500`.
** *Reason phrase*
+
Reason for the error, for example `Gateway Timeout` or `Internal Server Error`.

For details about the Listener configuration attributes, see xref:http-documentation.adoc#listenerConfig[Listener Configuration].

=== Configuring Attributes for the HTTP Request

The Anypoint Connector for HTTP (HTTP Connector) *Request* operation enables you to consume an external HTTP service using the default `GET` method. Otherwise, you can choose what methods the operation accepts

To configure the attributes for HTTP *Request* in the Anypoint Code Builder UI:

. Click the *Request* component on the canvas.
+
The configuration UI opens.
. In the *General* tab, configure the following attributes:
+
* *Method*
* *URI Settings*
* *Path*
* *Request*
** *Body*
** *Headers*
** *URI Parameters*
** *Query Parameters*
* *Send correlation ID*
* *Correlations ID*
. In the *Advanced* tab, configure the following attributes:
+
* *Output MIME type*
* *Parameters*
* *Output encoding*
* *Streaming Strategy*

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-test-connection"]

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-template-see-also"]
== See Also

* xref:http-documentation.adoc[]
* xref:anypoint-code-builder::acb-components.adoc[]
* xref:anypoint-code-builder::int-create-secure-configs.adoc[]
* xref:anypoint-code-builder::int-trigger-flows.adoc[]