= Using Anypoint Code Builder to Configure HTTP Connector

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-connector-config-intro"]

== Creating a New Integration Project

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-create-integration-project"]

== Adding the Connector to Your Integration Project

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-add-connector-to-project"]

[[configuring-http-source]]
== Configuring the Source For the Flow

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-configure-source"]

== Adding Components to Your Project

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-add-components-to-project"]

== Configuring the Component Attributes

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-configure-attributes"]

=== Configuring Attributes for the HTTP Listener

The Anypoint Connector for HTTP (HTTP Connector) *Listener* component enables you to set up an HTTP server and trigger flows when receiving HTTP requests.

To configure the HTTP *Listener* attributes in the UI, see <<configure-http-source,Configuring the Source For the Flow>>.

[[configuring-basic-security-filter]]
== Configuring the Attributes for Basic Security Filter

The *Basic security filter* component authenticates received HTTP requests. Use this component after a *Listener* component in your integration flow.

. Click the *Basic security filter* component on the canvas.
+
The configuration UI opens.
. In the *General* tab, configure the following attributes:
* *Realm*
+
Authentication realm.
+
*Security providers*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:http-documentation.adoc#basicSecurityFilter[Basic Security Filter].
+
* *Attributes*
+
HTTP Request attributes that come from an HTTP Listener source and check the `Authorization` header. 

[[configure-http-request]]
=== Configuring Attributes for the HTTP Request

The Anypoint Connector for HTTP (HTTP Connector) *Request* operation enables you to consume an external HTTP service using the default `GET` method. Otherwise, you can choose which methods the operation accepts.

To configure the attributes for HTTP *Request* in the Anypoint Code Builder UI:

. Click the *Request* component on the canvas.
+
The configuration UI opens.
. In the *General* tab, configure the following attributes:

* *Method*
+
Comma-separated list of allowed HTTP methods. To allow all methods, do not define this attribute.
+
* *URI Settings*
** *URL*
+
URL to send the request to.
+
** *Path*
+
Path for where to send the request.
+
* *Request*
** *Body*
+
Body of the request response message.
+
** *Headers*
+
Headers to include in the response message.
+
** *URI Parameters*
+
URI parameters used to create the request.
+
** *Query Parameters*
+
Query parameters to include in the request.
+
* *Correlations ID*
+
Select an option for whether to include an outbound correlation ID in the request. 
+
. Select the *Advanced* tab to configure the following attributes:
+
* *Output MIME type*
+
Defines the format of the request.
+
* *Parameters*
+
Adds parameters to the request. 
+
* *Output encoding*
+
Select the encoding to transform the data to.
+
* *Streaming Strategy*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:connectors::streaming-strategies.adoc[]
+
* *Connector Overrides*
** *Follow redirects*
+
Specifies whether or not to follow redirects.
+
** *Send body mode*
+
Select an option to define whether the request contains a body. If you select *Auto*, the behavior is determined by the defined allowed HTTP methods (GET, HEAD, and OPTIONS does not send a body).
+
** *Request streaming mode*
+
Select an option to define whether the request is sent using streaming.
+ 
** *Response timeout*
+
Maximum time in milliseconds that the request element blocks the execution of the flow waiting for the HTTP response.
+
* *Response*
** *Response validator*
+
Configures default error handling for the request. This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:http-documentation.adoc#SuccessStatusCodeValidator[Success Status Code Validator] and xref:http-documentation.adoc#FailureStatusCodeValidator[Failure Status Code Validator].
* *Output*
** *Target Variable*
+
Name of the variable on which the operation's output is placed.
+
** *Target Value*
+
An expression that's evaluated against the operation's output. The outcome of that expression is stored in the target variable.
+ 
* *Error Mappings*
+
This attribute is not currently enabled. 
+
* *Connection*
** *Reconnection strategy*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:http-documentation.adoc#reconnect[Reconnect] and xref:http-documentation.adoc#reconnect[Reconnect Forever]. 

[[configure-load-static-resource]]
== Configuring Attributes for Load Static Resource

The static resource serves static content to use with HTTP. The request path is used to look up the resource. 

To configure the attributes for HTTP *Load static resource* in the Anypoint Code Builder UI:

. Click the *Load static resource* component on the canvas.
+
The configuration UI opens.
+
. In the *General* tab, configure the following attributes:
* *Resource base path*
+
The base path of the resource that serves up the content, for example, `/Users/maxthemule/` resources.
* *Default file*
+
The default file to serve when a directory is specified. The default is `index.html`.
+
* *Attributes*
+
The HTTP request attributes coming from the HTTP Listener source to check the required resources. 
+
. Select the *Advanced* tab to configure the following attributes: 
* *Output MIME type*
+
Defines the format of the request.
+
* *Parameters*
+
Add parameters to the request. 
+
* *Output encoding*
+
Select the encoding to transform the data to.
+
* *Output*
** *Target Variable*
+
Name of the variable that stores the operation's output.
+
** *Target Value*
+
Expression that evaluates the operation's output. The expression outcome is stored in the target variable.
+
* *Error Mappings*
+
This attribute is not currently enabled. 

[[creating-config-xml-files]]
== Creating a New Configuration XML File

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-create-config-file-acb"]

[[testing-http-listener-connection]]
== Testing an HTTP Listener Connection

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-http-listener-test-connection"]

== See Also

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-template-see-also"]
* xref:http-documentation.adoc[HTTP Connector Reference]