= Using Anypoint Code Builder to Configure HTTP Connector


include::connectors::partial$configure-acb-connectors-partial.adoc[tag="individual-connector-config"]

=== Configuring Attributes for the HTTP Listener

The Anypoint Connector for HTTP (HTTP Connector) *Listener* component enables you to set up an HTTP server and trigger flows when receiving HTTP requests.

To configure the HTTP *Listener* attributes in the UI:

. Click the *Listener* component on the canvas.
+
The configuration UI opens.
. In the *General* tab, enter the relative path for the path set in the HTTP configuration element in *Path*. See xref:http-listener-ref.adoc#configure-paths[Configure Paths]. 
. Select the *Advanced* tab to configure the following attributes:
* *Allowed methods*
+
Comma-separated list of allowed HTTP methods by this listener. To allow all methods, do not define this attribute.
+
* *Response streaming mode*
+
Defines whether or not to use streaming when the response is sent.
+
* *Output MIME type*
+
Defines the format of the response.
+
* *Parameters* 
+
Add additional parameters for the *Listener*.
+
* *Output encoding*
+
Select the encoding to transform the data to.
+
* *Streaming Strategy*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:connectors::streaming-strategies.adoc[]
+
* *Primary node only*
+
Check this box to execute the *Listener* trigger on the primary node only when running in a cluster.
* *Redelivery policy*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:http-documentation.adoc#RedeliveryPolicy[Redelivery Policy].
* *Connection*
** *Reconnection strategy*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:http-documentation.adoc#reconnect[Reconnect] and xref:http-documentation.adoc#reconnect[Reconnect Forever].
* *Reponse*
+
See xref:http-documentation.adoc#HttpResponseAttributes[HTTP Respoonse Attributes]
+
* *Error Response*
+
An HTTP error response returns a status code for the error. 
+
** *Body*
+
The body of the error message.
** *Headers*
+
Headers to include in the error message.
** *Status code*
+
The status code of the error response, for example `500`.
** *Reason phrase*
+
Reason for the error, for example `Gateway Timeout` or `Internal Server Error`.

For details about the Listener configuration attributes, see xref:http-documentation.adoc#listenerConfig[Listener Configuration].

== Configuring the Attributes for Basic Security Filter

Authenticates received HTTP requests. Must be used after a listener component.

. Click the *Basic security filter* component on the canvas.
+
The configuration UI opens.
. In the *General* tab, configure the following attributes:
* *Realm*
+
Authentication realm.
+
*Security providers*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:http-documentation.adoc#basicSecurityFilter[Basic Security Filter].
+
* *Attributes*
+
HTTP Request attributes that come from an HTTP Listener source and check the `Authorization` header. 


=== Configuring Attributes for the HTTP Request

The Anypoint Connector for HTTP (HTTP Connector) *Request* operation enables you to consume an external HTTP service using the default `GET` method. Otherwise, you can choose what methods the operation accepts

To configure the attributes for HTTP *Request* in the Anypoint Code Builder UI:

. Click the *Request* component on the canvas.
+
The configuration UI opens.
. In the *General* tab, configure the following attributes:

* *Method*
+
Comma-separated list of allowed HTTP methods. To allow all methods, do not define this attribute.
+
* *URI Settings*
** *URL*
+
URL to send the request to.
+
** *Path*
+
Path for where to send the request.
+
* *Request*
** *Body*
+
Body of the request response message.
+
** *Headers*
+
Headers to include in the response message.
+
** *URI Parameters*
+
URI parameters used to create the request.
+
** *Query Parameters*
+
Query parameters to include in the request.
+
* *Send correlation ID*
* *Correlations ID*
+
Select an option for including an outbound correlation ID in the request. 
+
. Select the *Advanced* tab to configure the following attributes:
+
* *Output MIME type*
+
Defines the format of the request.
+
* *Parameters*
+
Add parameters to the request. 
+
* *Output encoding*
+
Select the encoding to transform the data to.
+
* * *Streaming Strategy*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:connectors::streaming-strategies.adoc[]
+
* *Connector Overrides*
** *Follow redirects*
+
Specifies whether or not to follow redirects.
+
** *Send body mode*
+
Select an option to define whether the request contains a body. If you select *Auto*, the behavior is determined by the defined methods (GET, HEAD, and OPTIONS does not send a body).
+
** *Request streaming mode*
+
Select an option to define whether the request is sent using streaming.
+ 
** *Response timeout*
+
Maximum time in milliseconds that the request element blocks the execution of the flow waiting for the HTTP response.
+
* *Response*
** *Response validator*
+
Configures default error handling for the request. This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:http-documentation.adoc#SuccessStatusCodeValidator[Success Status Code Validator] and xref:http-documentation.adoc#FailureStatusCodeValidator[Failure Status Code Validator].
* *Output*
** *Target Variable*
+
Name of the variable on which the operation's output is placed.
+
** *Target Value*
+
An expression that's evaluated against the operation's output. The outcome of that expression is stored in the target variable.
+ 
* *Error Mappings*
+
This attribute is not currently enabled. 
+
* *Connection*
** *Reconnection strategy*
+
This attribute is not currently enabled in the configuration UI. Configure it in the XML editor. See xref:http-documentation.adoc#reconnect[Reconnect] and xref:http-documentation.adoc#reconnect[Reconnect Forever]. 

== Configuring Attributes for Load Static Resource

The static resource serves static content to use with HTTP. The request path is used to look up the resource. 

To configure the attributes for HTTP *Load static resource* in the Anypoint Code Builder UI:

. Click the *Load static resource* component on the canvas.
+
The configuration UI opens.
+
. In the *General* tab, configure the following attributes:
* *Resource base path*
* *Default file*
* *Attributes*
. Select the *Advanced* tab to configure the following attributes: 
* *Output MIME type*
+
Defines the format of the request.
+
* *Parameters*
+
Add parameters to the request. 
+
* *Output encoding*
+
Select the encoding to transform the data to.
+
* *Output*
** *Target Variable*
+
Name of the variable that stores the operation's output.
+
** *Target Value*
+
Expression that evaluates the operation's output. The expression outcome is stored in the target variable.
+
* *Error Mappings*
+
This attribute is not currently enabled. 






include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-test-connection"]

include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-template-see-also"]
== See Also

* xref:http-documentation.adoc[]
* xref:anypoint-code-builder::acb-components.adoc[]
* xref:anypoint-code-builder::int-create-secure-configs.adoc[]
* xref:anypoint-code-builder::int-trigger-flows.adoc[]