= Using Anypoint Code Builder to Configure HTTP Connector


include::connectors::partial$configure-acb-connectors-partial.adoc[tag="individual-connector-config"]


== Configure the Attributes 

After you add components to your integration project, configure the attributes in the component UI, or configure the attributes directly in the XML code editor.  

== Configuring the Attributes for HTTP Listener

To configure the HTTP Listener attributes in the UI:

. Click the *Listener* component on the canvas.
+
The configuration UI opens.
. In the *General* tab, enter the relative path for the path set in the HTTP configuration element in *Path*. See xref:http-listener-ref.adoc#configure-paths[Configure Paths]. 
. Click the *Advanced* tab to configure the following attributes:
* *Allowed methods*
* *Response streaming mode*
* *Output MIME type*
* *Parameters* 
* *Output encoding*
* *Streaming Strategy*
+
This attribute is not currently enabled in the configuration UI. Configure in the XML editor. See xref:http-documentation.adoc#repeatable-in-memory-stream[Repeatable In-Memory Stream] and xref:http-documentation.adoc#repeatable-file-store-stream[Repeatable File Store Stream].
* *Primary node only*
+
Check this box to execute the *Listener* trigger on the primary node only when running in a cluster.
* *Redelivery policy*
+
This attribute is not currently enabled in the configuration UI. Configure in the XML editor. See xref:http-documentation.adoc#RedeliveryPolicy[Redelivery Policy].
* *Connection*
** *Reconnection strategy*
+
This attribute is not currently enabled in the configuration UI. Configure in the XML editor. See xref:http-documentation.adoc#reconnect[Reconnect] and xref:http-documentation.adoc#reconnect[Reconnect Forever].
* *Reponse*
+
See xref:http-documentation.adoc#HttpResponseAttributes[HTTP Respoonse Attributes]
+
** *Body*
+
The body of the response message.
** *Headers*
** *Status code*
** *Reason phrase*
* *Error Response*
+
An HTTP error response returns a status code for the error. 
+
** *Body*
+
The body of the error message.
** *Headers*
+
Headers to include in the error message.
** *Status code*
+
The status code of the error response, for example `500`.
** *Reason phrase*
+
Reason for the error, for example `Gateway Timeout` or `Internal Server Error`.





include::connectors::partial$configure-acb-connectors-partial.adoc[tag="acb-test-connection"]

== See Also

* xref:http-documentation.adoc[]
* xref:anypoint-code-builder::int-create-secure-configs.adoc[]
* xref:anypoint-code-builder::int-trigger-flows.adoc[]