= Scripting Module - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Scripting Module v2.0

The Scripting Module executes custom logic written in a scripting language. In some cases, you might need to create custom code to perform all or part of a complex task, or to reuse modules that you have already written. Supported scripting languages are:

* Groovy 2.4.16
* JRuby 9.2.11.1 (Java implementation of Ruby)
* Jython 2.7.2 (Java implementation of Python)
* Nashorn (JavaScript engine)

For information about compatibility and fixed issues, see xref:release-notes::mule-runtime/module-scripting.adoc[Scripting Module Release Notes]

== Prerequisites

To use this module, you must be familiar with the following concepts:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* Understand how to create a Mule app using Design Center or Anypoint Studio

Before creating an app, you must:

* Have access to Anypoint Platform.
// If your connector has other prerequisites, list them here.

== Common Use Cases For the Connector

// List common use cases for the scripting Module Connector and provide
// a link to the xref:Connectors/scripting-module-connector-examples.adoc[Examples] use cases.

== Audience

* Starting user
+
To create your Mule app,
see xref:Connectors/scripting-module-studio.adoc[Studio Configuration].

* Power user
+
Read the xref:Connectors/scripting-module-xml-maven.adoc[XML and Maven Support],
For a major or minor release, view
xref:Connectors/scripting-module-upgrade-migrate.adoc[Upgrade and Migrate].


== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app with xref:connectors::scripting/scripting-module-studio.adoc[Anypoint Studio].

== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://www.mulesoft.com/exchange/?search=scripting-module&type=connector[Scripting Module Connector on Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
