= Scripting Module - XML and Maven Support - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you manually code a Mule app in XML either from the Anypoint Studio XML editor
or from a text editor, you can get access to the connector in your app by adding
reference statements to your XML Mule flow and in the Apache Maven POM file.

[NOTE]
====
You can avoid this manual process by using Studio. When
you add the connector in Anypoint Studio, Studio automatically populates
the XML code with the connector's namespace and schema location, and adds a
dependency to the pom.xml file.
====

== Add a Namespace for the Connector

Paste the following code inside the `mule` tag of the header
of your configuration XML:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/scripting-module
http://www.mulesoft.org/schema/mule/scripting-module/current/mule-scripting-module.xsd
----

This example shows how the namespace statements are placed in the XML:

[source,xml,linenums]
----
<mule xmlns:scripting="http://www.mulesoft.org/schema/mule/scripting"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/file
	http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
	http://www.mulesoft.org/schema/mule/http
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/core
	http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
    http://www.mulesoft.org/schema/mule/scripting
    http://www.mulesoft.org/schema/mule/scripting/current/mule-scripting.xsd">
----


== Add a POM File Dependency

The `pom.xml` Apache Maven file generated by Anypoint Studio contains dependencies
for a Mule app. When you code a Mule app manually, include this XML snippet in
your POM file to enable access to this connector:

[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-scripting-module</artifactId>
    <version>2.0.0</version>
    <classifier>mule-plugin</classifier>
</dependency>
----

Verify that the connector `version` corresponds to the one you are using.

To obtain the most up-to-date pom.xml file information:

. Go to https://www.mulesoft.com/exchange/[Anypoint Exchange].
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for scripting Module.
. Click *Dependency Snippets*.

Notice that since Scripting Module does not provide execution engines, you have to provide an execution engine yourself.
For example, review the following list of engines provided by the previous version of Scripting Module:

Groovy:
[source,xml,linenums]
----
    <dependency>
        <groupId>org.codehaus.groovy</groupId>
        <artifactId>groovy-all</artifactId>
        <version>2.4.16</version>
        <classifier>indy</classifier>
    </dependency>
----

Python:
[source,xml,linenums]
----
    <dependency>
        <groupId>org.python</groupId>
        <artifactId>jython-standalone</artifactId>
        <version>2.7.2</version>
    </dependency>
----

Ruby:
[source,xml,linenums]
----
    <dependency>
        <groupId>org.jruby</groupId>
        <artifactId>jruby-core</artifactId>
        <version>9.2.11.1</version>
    </dependency>
    <dependency>
        <groupId>org.jruby</groupId>
        <artifactId>jruby-stdlib</artifactId>
        <version>9.2.11.1</version>
    </dependency>
----


== See Also

https://help.mulesoft.com[MuleSoft Help Center]
