= Java Module
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: Java, custom code

The Java module in Mule 4 is built to:

* Minimize the need for custom code.
* Avoid the need for you to know or understand Java.

However, there are some advanced uses cases that require integration with
custom Java code, for example:

* Reuse of a library, such as a tax calculation library.
* Reuse of a canonical object model that is standard in the organization.
* Execution of custom logic using Java.

Note that in Mule 3, MEL serves as bridge for creating instances of particular
Java classes and executing Java methods. In Mule 4, interoperation with Java
changes due to the replacement of MEL by DataWeave, a functional language.
Functional languages should not have side effects on their input arguments,
so it does not make sense for DataWeave to execute random instance
methods on random object instances.

== Java Module versus the Scripting Module

You can use Java module or execute Groovy code through the
xref:scripting/scripting-module.adoc[Scripting module]. However, the Scripting
module does not offer DataSense support.

== See also

xref:java/java-create-instance.adoc[Example: To Create an Instance of a Class]

xref:java/java-invoke-method.adoc[Example: To Invoke Methods]

xref:java/java-instanceof.adoc[Example: To Test for an Instance of a Class]

xref:java/java-throwable.adoc[Example: Working With Throwables]

xref:java/java-reference.adoc[Java Module Documentation Reference]

xref:java/java-argument-transformation.adoc[Java Module Argument transformation]
