= Example: To Create an Instance of a Class
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: Java, create instance





This example shows how to create an instance of a class whose constructor does not require parameters:

[source,xml,linenums]
----
<java:new class="com.foo.Person" constructor="Person()"/>
----

This example shows how to create an instance of a class when the constructor requires parameters:

[source,xml,linenums]
----
<java:new class="com.foo.Person" constructor="Person(String, Integer)">
    <java:args>#[{
      name: 'Jhon Doe',
      age: 10
    }]</java:args>
</java:new>
----

IMPORTANT: When configuring the constructor arguments in the `<java:args>` parameter,
the keys of the map will determine how the parameters will be passed to the constructor. *In
order to reference the parameters by name* (`firstName`, `age`, etc.),
the java class containing the Method or Constructor has to be compiled
using https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html[the `-parameters` compiler flag].
If the class was not compiled with this flag, then the same parameters
should be referenced in the declared order and with the canonical names (`arg0: 'Jhon Doe'`, `arg1: 10`, etc.).

[TIP]
===============================
If your Java classes are defined in your Studio Project, you will need to add
the Maven Compiler plugin as a dependency in you `pom.xml` in order to compile your classes
with the `-parameters` flag:
[source,xml,linenums]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.1</version>
    <configuration>
        <compilerArgs>
            <arg>-parameters</arg>
        </compilerArgs>
    </configuration>
</plugin>
----
===============================

One of the advantages of using the Java Module is that you will get https://docs.mulesoft.com/studio/7.3/datasense-concept[DataSense] support,
which can help you build the `<java:args>` map and will also provide Metadata for the
operation's output. In the above examples, the `Person` object will be placed in the
payload. If you would rather save it to a variable, the `new` operation supports https://docs.mulesoft.com/mule-runtime/4.2/target-variables[target parameters],
as the following example shows:

[source,xml,linenums]
----
<java:new class="com.foo.Person" constructor="Person(String, Integer)" target="jhon">
    <java:args>#[{
      name: 'Jhon Doe',
      age: 10
    }]</java:args>
</java:new>
----

You can later access that object as `"#[vars.jhon]"`.

IMPORTANT: The classes used with the Java Module must be exported, if not the
execution will fail with a JAVA:CLASS_NOT_FOUND error. See xref:4.1@mule-runtime::how-to-export-resources.adoc[How to
export resources].