= Java Module - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Java Module v1.2

Release Notes: xref:release-notes::connector/java-module.adoc[Java Module Release Notes] +
Exchange: https://www.mulesoft.com/exchange/org.mule.module/mule-java-module/[Java Module]

Mule 4 is built to:

* Minimize the need for custom code.
* Avoid the need for you to know or understand Java.

However, some advanced uses cases require integration with
custom Java code, such as:

* Reuse of a library, such as a tax calculation library.
* Reuse of a canonical object model that is standard in the organization.
* Execution of custom logic using Java.

In Mule 3, MEL served as a bridge for creating instances of 
Java classes and executing Java methods. In Mule 4, interoperation with Java
changed, due to the replacement of MEL by DataWeave, which is a functional language.
Functional languages do not have side effects on their input arguments,
so it does not make sense for DataWeave to execute random instance methods on random object instances.
Therefore, pure DataWeave supports calling only static Java methods, without use of the Java module.

== Java Module Versus the Scripting Module

You can use the Java module, or execute Groovy code through the
xref:scripting/scripting-module.adoc[Scripting module]. However, the Scripting
module does not offer DataSense support, user interface support, visual aids 
for methods available for each class, autocompletion, and so on. See 
xref:4.2@mule-runtime::intro-java-integration.adoc[Java Integration].

== POM File Information

[source,xml,linenums]
----
<dependency>
  <groupId>org.mule.module</groupId>
  <artifactId>mule-java-module</artifactId>
  <version>RELEASE</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

Mule converts RELEASE to the latest version. To specify a version, view https://www.mulesoft.com/exchange/org.mule.module/mule-java-module/[Java Module] in Anypoint Exchange and click *Dependency Snippets*.

== See Also

* xref:java/java-create-instance.adoc[Create an Instance of a Class]
* xref:java/java-invoke-method.adoc[Invoke Methods]
* xref:java/java-instanceof.adoc[Test for an Instance of a Class]
* xref:java/java-throwable.adoc[Work With Throwables]
* xref:java/java-reference.adoc[Java Module Reference]
* xref:java/java-argument-transformation.adoc[Java Module Argument Transformation]
* https://help.mulesoft.com[MuleSoft Help Center]