= Example: To Invoke Methods Using the Java Module
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: Java, create instance





This example shows how to invoke instance methods. First, it creates the instance on which the method will be invoked. Then it invokes a method that does not take any arguments.

[source,xml,linenums]
----
<java:new class="com.foo.TaxCalculator"
  constructor="TaxCalculator()"
  target="taxCalculator"/>
<java:invoke instance="#[vars.taxCalculator]"
  class="com.foo.TaxCalculator"
  method="init()"/>
----

Note that you can obtain a method from elsewhere instead of creating an instance with `<java:new>`.

This example invokes a method that takes arguments:

[source,xml,linenums]
----
<java:new class="com.foo.TaxCalculator"
  constructor="TaxCalculator()"
  target="taxCalculator"/>
<java:invoke instance="#[vars.taxCalculator]"
  class="com.foo.TaxCalculator"
  method="calculate(Long, String)">
    <java:args>#[{price: payload.price, description: payload.description}]</java:args>
</java:invoke>
----

IMPORTANT: When configuring the Method arguments in the `args` parameter, the keys of the map will identify which parameter to invoke. *To reference the parameters by name* (`firstName`, `age`, and so on), the Java class containing the Method or Constructor must be compiled using the https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html[`-parameters` compiler flag]. If the class was not compiled with this flag, then the same parameters should be refenced in the canonical way as `arg0`, `arg1`, and so on.

//TODO: WOULD HELP TO SHOW OR CLARIFY WHAT "GET DATASENSE" MEANS:
Note that you get DataSense with `<java:new/>` and both the output value and the input arguments.

== Invoking Static Methods

You can invoke static Java methods like this:

[source,xml,linenums]
----
<java:invoke-static
  class="java.lang.Math"
  method="toRadians(double)">
    <java:args>#[{arg0: 180}]</java:args>
</java:invoke-static>
----

== Invoking Methods with DataWeave

You can invoke methods using DataWeave functions. This is especially helpful for methods that return `boolean` values:

[source,xml,linenums]
----
<choice>
    <when
      expression="#[Java::invoke('com.foo.TaxCalculator',
      'isTaxFree(Invoice)', vars.taxCalculator,
      {invoice: vars.invoice})]">
        <flow-ref name="skipTax" />
    </when>
</choice>
----

Note that `vars.taxCalculator` contains an instance of `com.foo.TaxCalculator` that is created with `<java:new/>`, as explained above.
