= Example: To Create an Instance of a Class
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: Java, create instance
:toc:
:toc-title:

toc::[]

This example shows how to create an instance of a class:

[source,xml,linenums]
----
<java:new class="com.foo.Person" constructor="Person()"/>
----

This example shows how to create an instance using the default constructor. You can also use a non-custom constructor.
[source,xml,linenums]
----
<java:new class="com.foo.Person" constructor="Person(String, Integer)">
    <java:args>#[{
      firstName: 'MG',
      age: 34
    }]</java:args>
</java:new>
----

IMPORTANT: When configuring the constructor arguments in the `args` parameter, the keys of the map will identify which parameter should be invoked. *In order to reference the parameters by name* (`firstName`, `age`, etc.), the java class containing the Method or Constructor has to be compiled using https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html[the `-parameters` compiler flag]. If the class was not compiled with this flag, then the same parameters should be refenced in the canonical way as `arg0`, `arg1`, etc.

//TODO: IT MIGHT HELP TO SHOW DATASENSE HERE OR LINK OUT A DATASENSE SECTION
Note that you will get DataSense on the operation's output (in this case a `Person` object), and you will use DataSense to help you build the arguments map.

IMPORTANT: The classes used with the Java Module must be exported, if not the execution will fail with a JAVA:CLASS_NOT_FOUND error. See xref:4.1@mule4-runtime::how-to-export-resources.adoc[How to export resources].