= WebSocket Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

WebSocket Connector Version 1.0

A Websocket is a bi-directional, TCP connection between a client and server that is kept open until the application closes it. When using WeSockets, an application makes an initial connection with HTTP. The connection then gets upgraded to a TCP socket-based connection.

WebSockets are a key piece of modern integration due to their ability to:

* Establish bi-directional and full-duplex communication between a server and client
* Implement server push notifications
* Seamlessly work on top of existing HTTP infrastructure
* Avoid the need for clients to regularly poll the server for new data

WebSocket Connector enables you to create Mule apps that <<TBD - Waiting to get this information from Esteban>>>

For more information about WebSockets, see the IETF document for RFC 6455 - The WebSocket Protocol.

== Common Use Cases for WebSocket Connector

WebSocket Connector is useful for real-time applications that need to avoid the overhead caused by the HTTP request-response message exchange pattern.

Typical use cases for WebSocket Connector include chat applications and stock quote applications.

=== Chat Applications

A chat application sends messages to one or more groups to which multiple clients subscribe. If a Mule app uses HTTP to send messages, the clients must constantly poll the server for available messages, which can create performance issues. If an app uses WebSockets, the server can push the available message to all subscribed users without the need for client polling.

=== Stock Quotes Applications

A stock quotes application continuously sends updated prices for a set of relevant stocks. Clients can open a WebSocket to access this service. Because prices change continuously, the ability to reuse the same connection and receive messages at random times make WebSockets ideal for this type of application.

In this scenario, once the connection is established, the client has no need to send additional requests to the server.

== Compatibility

WebSocket Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.2.2 or higher
|Java |1.8.0_x
|Anypoint Studio|7.4 or higher
|===

== Prerequisites

Before creating an app, you must have access to the WebSocket target resource and Anypoint Platform. You must also understand how to create a Mule app using Design Center or Anypoint Studio.

== Triggers [[triggers]]

Triggers initiate the execution of a flow upon receiving a message or event notification. You can specify the following triggers for WebSocket-related events:

* `inbound-listenerPort` exposes an endpoint to which external systems can connect and initiates an app flow when a message is received.
* `on-inbound-connection` initiates an app flow when a new connection to the Inbound Listener is established.
* `outbound-listener` exposes an endpoint that initiates an app flow when an outbound WebSocket receives a message from an external system.
* `on_connection-closed` initiates an app flow when an inbound or outbound WebSocket is closed.

== Operations [[operations]]

WebSocket Connector support the following operations:

* `open-outbound-socket` connects to an external system and creates an outbound webSocket.
* `send` sends a message through a WebSocket.
* `subscribe-groups` subscribes a WebSocket to one or more groups.
+
The Mule app can invoke this operation on the same web socket multiple times. If an app invokes this operation for . Repeated groups are ignored.
+
* `unsubscribe-groups` unsubscribes a Websocket from one or more groups.
+
You can invoke this operation multiple times on the same socket, with each invocation being additive over the previous ones. Repeated groups are ignored.
+
* `broadcast` send a message to multiple Websocket's classified by path, type, and group.
* `close-socket` closes a Websocket connection.

== Security Scheme (in progress)

WebSockets Connector supports securing the client and server endpoints through TLS, using the following URI schemes:

* WS (Web Socket protocol) identifies a WebSocket server and resource name without using encryption (e.g: ws://localhost:80).
* WSS (Secure Web Socket protocol) identifies a WebSocket server and resource name, secure through TLS (e.g: wss://localhost:433).

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]

<Additional links TBD>
