= WebSocket Triggers - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

WebSocket Connector supports the following triggers and operations:

* Server triggers
** `<websocket:inbound-listener>`
** `<websocket:outbound-listener>`
* Client triggers
** `<websocket:outboundSocketId-listener>`
* Messaging operations
** `<websocket:send>`
* Management operations
** `<websocket:close-socket>`

== Inbound Listener (`<websocket:inbound-listener>`)

Use the `<websocket:inbound-listener>` element to represent a WebSocket endpoint to which clients can connect. By hitting this endpoint, external clients establish a WebSocket connection and trigger the associated flow each time they send a message.

You can use the `defaultGroups parameter` to specify the default groups to which the inbound endpoint subscribes. The endpoint receives and processes broadcast operations that are performed on the subscribed groups.

The group subscription only affects WebSockets that reside in the same app domain. Therefore, it is useful when one WebSocket in the app domain wants to send messages to the other WebSockets in the app domain.

For more information about groups, see xxx.

The following example takes these actions:

* In the flow named `on onIncomingMessageFlow`:
. The Inbound Listener listens for messages on path `/chat/hello`.
.
* In the flow named `sendFriendlyMessageFlow`:
. Listens for a message on the path `/chat/hello`.
. Responds `Good morning to you` when it hears a message.

[source,xml,linenums]
----
<flow name="onIncomingMessageFlow">
    <websocket:inbound-listener ​path​=​"/chat"​ ​defaultGroups​=​"#[['AVENGERS', 'REVENGERS']]"​ ​config-ref​=​"ws"​ />
    <logger level="INFO" message="#['Received message ' ++ payload ++ ' from socket: ' ++ attributes.socketId]" />
    <websocket:send doc:name="SendResponse" socketId="#[attributes.socketId]" config-ref="ws" >
        <websocket:content>#['I'm fine, thank you!']</websocket:content>
    </websocket:send>
</flow>
<flow name="sendFriendlyMessageFlow">
    <websocket:open-outbound-socket path="/chat" config-ref="ws" />
    <websocket:send doc:name="SendMessage" socketId="#[attributes.socketId]" config-ref="ws" >
        <websocket:content>#['Hi! How are you?']</websocket:content>
    </websocket:send>
</flow>
----

=== Sending Responses

Because a WebSocket is full-duplex, the Inbound Listener doesn't automatically send a response. Depending on your use case, you might want to process the messages without sending a response, or only send responses in certain cases.

To send a response, use the `<websocket:send>` operation.

=== Output

Each time a new message arrives, the Inbound Listener triggers the associated flow, with the Inbound Listener payload containing the message's content. The message MIME type is obtained from the Content-Type header of the HTTP request. If the Content-Type header isn't set, the MIME type defaults to one of these values, depending on the protocol’s DATA frame type:

* For a binary DATA frame, the MIME type is application/octect-stream.
* For a text DATA frame, the MIME type is text/plain.

The attributes will contain a WebSocket Attributes Object.
