= WebSocket Connector Components - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/


== Messaging Operations

=== Send Operation

Use `<websocket:send` to send a message through a WebSocket identified by its socket ID. You can use this operation for both inbound and outbound WebSockets.

The following example takes these actions:

* In the flow called `Say Hello`:
. Opens an outbound endpoint on a WebSocket called `socketId` on path `/chat/hello`.
. Sends the message `Good morning!` through the WebSocket.
* In the flow named `Say Hello Back`:
. Listens for a message on the path `/chat/hello`.
. Responds `Good morning to you` when it heard a message back.

[source,xml,linenums]
----
    <flow name="sayHello">
      <websocket:open-outbound-socket path="/chat/hello"
        config-ref="ws" target="outboundSocketId"
        targetValue="#[attributes.socketId]"/>
      <websocket:send socketId="#[vars.socketId]"
        config-ref="ws">
        <websocket:content>'Good morning!'</websocket:content>
      </websocket:send>
    </flow>
    <flow name="sayHelloBack">
        <websocket:inbound-listener path="/chat/hello"
          config-ref="ws" outputMimeType="text/plain" />
        <websocket:send socketId="#[attributes.socketId]"
          config-ref="ws">
          <websocket:content>#['Good morning to you ' ++
           attributes.socketId ++ '!']</websocket:content>
        </websocket:send>
    </flow>
----

=== Broadcast Operation

Use `<websocket:broadcast>` to send a message to a group of other WebSockets. You can select the target group according to this criteria:

* WebSockets subscribed to specific groups (`groups` attribute)
* WebSockets connected to a specific path (`path` attribute)
* Inbound or outbound WebSockets (`type` attribute)

The `groups` and `type` parameters work in tandem. You can use them separately, but when used together, they provide two levels of filtering.

The Broadcast operation returns an empty payload and no attributes.

The following examples show the

[source,xml,linenums]
----
<!-- send to all WebSockets connected to an endpoint of path /quotes -->
<websocket:broadcast path=”/quotes” ​config-ref​=​"ws"​ />
<!-- send to all Inbound WebSockets connected to an endpoint of path /quotes -->
<websocket:broadcast path=”/quotes” ​type​=​"INBOUND"​ ​config-ref​="​ws"​ />
<!-- send to all Outbound sockets connected to the /quotes endpoint -->
<websocket:broadcast path=”/quotes” ​type​=​"OUTBOUND"​ ​config-ref​=​"ws"​ />
<!-- send to all INBOUND sockets connected to the /quotes endpoint, in the MARVEL and DC groups -->
<websocket:broadcast path=”/quotes” ​type​=​"INBOUND"​ ​groups​="​ #[['MARVEL', 'DC']]"​ ​config-ref​=​"ws"​ />
----

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]

<Additional links TBD>
