= EDIFACT EDI Connector 2.3 - Batching Outbound EDIFACT Messages - Mule 4

It is best practice to batch B2B/EDI messages that are not time sensitive (such as invoices and payment remittances) into a single interchange and send them to trading partners, instead of transmitting each individual transaction as a separate interchange or file.

You can use the EDIFACT Connector’s Batch operation to merge individual EDIFACT messages created and accumulated over a period of time into a single interchange and send to your trading partners.

== Batching Stages

Implementing batch involves 2 stages.
* Stage One - Accumulation of transactions
* Stage Two - Releasing the batch

=== Stage One - Accumulation of Transactions

* As you receive application messages (such as a JSON invoice) from the backend systems, you can transform the payloads into EDIFACT messages using dataweave and EDIFACT Write operation as you would normally create EDIFACT payloads.
* You need to use temporary control number keys in the EDIFACT Write operation, which allows these intermediate EDIFACT messages accumulated to be sent as a batch at a later time, created with control numbers that will not be used in the final batch sent to the trading partner.
`<edifact:write doc:name="Write individual D97A ORDERS" doc:id="3d51215a-125d-461b-9791-0a939e5ebc45" config-ref="EDIFACT_Write_ORDERS" interchangeControlNumberKey="NTO-MYTHICAL-UNB-TMP"/>`
* You can store the intermediate EDIFACT message payloads in your choice of storage such as a database table.

The picture below shows a representative implementation of a Mule flow that:
* Receives JSON payloads from the backend systems
* Transforms to EDIFACT D97A ORDERS message
* Generates the intermediate EDIFACT message payload using EDIFACT Write operation
* Stores the EDIFACT payload in a Database table

=== Stage Two - Releasing the Batch

* Different trading partners have different criteria on how they want the transactions to be batched. The criteria can be one of the following conditions, or a combination of more than one (to be implemented outside of the EDIFACT connector operations):
** Release the batch at specific time interval, or specific time of the day
** Release the batch when specific number of transactions are accumulated
** Release the batch when the total size of the accumulated transactions is near a threshold
* You need to implement the logic or module to monitor the transactions getting accumulated in the temporary storage and determine when a particular batch needs to be released.
* When the batch needs to be released, retrieve the accumulated intermediate EDIFACT messages from the temporary storage based on the batch criteria, append the transactions together and send the appended payload to the EDIFACT Batch operation.
* You can choose to use the desired control number key on the Batch operation, or leave the control number key fields empty at the time of Batch operation execution - allowing the EDIFACT connector to generate the control number sequence automatically based on the sender and receiver identifier combination.
`<edifact:batch doc:name="Batch" doc:id="3ce80437-63e2-404c-b875-531708b7bfdb" config-ref="EDIFACT_Batch" interchangeControlNumberKey="NTO-MYTHICAL-UNB-TMP"> <edifact:batch-content ><![CDATA[#[vars.mergedInput]]]></edifact:batch-content> </edifact:batch>`
* You have to ensure that the input payload sent to the Batch operation contains EDI transactions with data elements in the UNB envelope segments, such as Sender ID, receiver ID, version number.
** If the input payload contains EDI transactions with non matching data elements in the envelope segments, the Batch operation throws an exception.

The picture below shows a representative implementation of a Mule flow that:
* Receives a HTTP request to release accumulated EDIFACT messages transactions for a specific partner.
** The request is typically triggered when the batch release criteria is met.
* Retrieves the intermediate EDIFACT messages from the database table
* Applies a transformation to append the individual EDIFACT messages together
* Sends the appended payload through EDIFACT Batch operation to merge the messages into a single interchange.
* Print the generated control numbers - which can be saved to reconcile inbound functional acknowledgements received from the partners.
* The batched EDIFACT interchange is delivered to the trading partner’s SFTP site.
