= Database Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/


To configure a connector in Anypoint Studio:

. Install the connector.
. Configure the connector.
. Configure an input source for the connector.

== Install the Connector

. In Anypoint Studio, click the Anypoint Exchange icon in the Studio task bar.
. In Anypoint Exchange, click *Login* and supply your Anypoint Platform username and password.
. Search for the Database connector, click the card for the connector, and click *Add to project*.
. Follow the prompts.

== Configure the Connector

No additional configuration is required. Optionally, you can xref:4.2@mule-runtime::global-settings-configuration.adoc[configure global properties] for this connector.

== Configure an Input Source

Configure an input source for the connector such as a connector operation,
using *HTTP Listener*, or *Scheduler*.

You can put the following operations for the connector in the *Source* area
of the Studio canvas.

* `On table row`


== See Also

https://help.mulesoft.com[MuleSoft Help Center]
