= Database Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Release Notes: xref:release-notes::connector/connector-db.adoc[Database Connector Release Notes]

The Database connector establishes communication between your Mule app and a relational database. 

To install this connector:

. In Anypoint Studio, click the Exchange icon in the Studio task bar.
. Click Login in Anypoint Exchange and supply your Anypoint Platform username and password.
. Search for the Database connector for Mule 4 and click Install.
. Follow the prompts to install the connector.

After adding the connector to Studio, the connector and its operations appear in the Mule Palette.

== Database Listeners and Operations

The Database connector provides a listener to read from a database in the Source section of a flow. Other operations also allow you to read and write to a database anywhere in the Process section. Instead of writing single records to a database, bulk operations allow you to modify a collection of records by simply supplying the SQL to modify each record. Other operations allow you to carry out Data Definition Language (DDL) operations, to execute stored procedures, or to execute entire SQL scripts at once.

== Database Connector Features

* Improved operations: Operations are streamlined to make it easier to interface with a database, either with single or bulk operations.
* Dynamic queries are easy: There is a single experience for executing static and dynamic queries.
* Embeddable transformations: You can embed DataWeave transformations inside the Insert and Update operations to construct the data sets that you want to send to the database without a side effect on the message or the need to use enrichers.
* Streaming support: The connector uses Mule’s streaming framework to handle streaming automatically and transparently. You can even execute a Select statement and process the results asynchronously without worrying about leaking connections.

== Supported Database Types

The Database Connector provides specialized support for the following database:

* MySQL
* Oracle
* Microsoft SQL Server

You can set up other JDBC databases using a generic JDBC configuration. You can also reference a JDBC `DataSource` object or a `XADataSource` object, which is required for XA transactions. You typically create the object in Studio using Spring.

== See Also

* xref:db/db-configure-connection.adoc[Configure connections to a database]
* xref:db/db-connector-query.adoc[Query data from a database]
* xref:db/db-connector-trigger.adoc[Trigger a flow for each row in a table]
* xref:db/db-connector-insert-update-delete.adoc[Insert, update, and delete data in a database]
* xref:db/db-connector-transactions-ref.adoc[Using transactions in a database]
* xref:db/db-connector-execute-script-ref.adoc[Execute database scripts]
* xref:db/db-connector-datatypes-ref.adoc[Use database custom types]
* xref:db/db-connector-ddl.adoc[Create tables, triggers, procedures and other schema objects in a database]
* xref:database/database-documentation.adoc[Database Connector Reference]
* xref:4.1@mule-runtime::migration-connectors-database.adoc[Migrate the Database Connector]