= Using Websockets Connector in CloudHub
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket, CloudHub, vpc

=== WebSocket Connector in VPC

If your application exposes inbound WebSocket endpoints and you choose to deploy it in CloudHub, a Dedicated Load Balancers must be setup to route WS and WSS traffic to Mule applications. This means that a VPC (Virtual Private Cloud) needs to be configured for your application. Applications that only open outbound WebSockets don't have this restriction.

To set up your inbound WebSocket endpoints, configure your `<ws:inbound-listener>`` to listen on `0.0.0.0`. If you want to communicate over WS you will need to set the listener port to 8091, or port 8092 if you want to communicate over WSS.

The next step is to deploy your application to your VPC and set up your Load Balancer's URL mapping rules. These rules will indicate your Dedicated Load Balancer to associate a URI to a specific Mule app. For example, if your app is called 'my-websocket-mule-app' you can define your rule as:

    * Input Path: /my-websocket-mule-app/
    * Target App: my-websocket-mule-app
    * Output Path: /
    * Protocol: ws

This will route all requests made to your Dedicated Load Balancer's URL and the specified Input Path to your Mule app's root path /. Your Load Balancer's name will determine its assigned URL, so for this example, if you name your Load Balancer 'mylb', then you would need to hit: ws://mylb.lb.anypointdns.net:80/my-websocket-mule-app/ to connect to your WebSocket Listener. Your Dedicated Load Balancer will forward all requests issued to port 80 to your app's port 8091, which will be destined for all WS connections. When using WSS, however, you will need to issue requests to port 443, and these requests will then be forwarded to your Mule app's port 8092.


=== See Also

* https://docs.mulesoft.com/runtime-manager/vpc-architecture-concept
* https://docs.mulesoft.com/runtime-manager/lb-architecture
* https://docs.mulesoft.com/runtime-manager/lb-mapping-rules
