= About Websocket Reconnection
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket, reconnection

== About WebSockets Reconnection

WebSockets are based on persistent and stateful connections. Therefore, it is possible for a connection to be abnormally closed in the lapse between it was established and it's being used in any operation due to factors like idle timeouts, network conditions, etc. 

Inbound sockets cannot be automatically reconnected because for those connections to be reestablished because it is up to the remote system to resend the connection request.

For Outbound sockets however, a reconnection policy can be used to reestablish the connection in case it drops. When your Mule Application tries to use a WebSocket that has been abnormally closed (for example to send a message to it), reconnection is reestablished by replaying the same Http Request that originally established the outbound socket. After which, the operation is automatically retried.

Let's see an example:

[source,xml,linenums]
----
<websocket:send socketId="#[vars.socketId]" config-ref="ws">
    <reconnect count="5" frequency="1000"/>  
    <websocket:content>Hello World!</websocket:content>
</websocket:send>
----

The snippet above shows how to send a reconnection policy on a `<websocket:send>` operation so that reconnection is reattempted once every second up to 5 times in case the connection is dropped.

== See Also

* xref:http/websocket-about-websocket-connector.adoc[About Websocket Connector]
* xref:http/websocket-connector-configuration.adoc[About Websocket Connector Configuration]
* xref:http/websocket-connector.adoc[Websocket Connector]
