= WebSocket Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

WebSocket Connector Version 1.0

WebSockets are a key piece of modern integration due to their ability to:

* Establish bi-directional and full duplex communication between server and client.
* Implement server push patterns
* Seamlessly work on top of the existing HTTP infrastructure.
* Avoid polling

== Basic Concepts

There are two WebSocket types:

* Inbound: these types of WebSockets allow the user to expose an endpoint that the Mule application will be listening on, and to which external systems can connect to initiate communication.
* Outbound: represents a WebSocket that will open a connection to other WebSockets through the 'connect' operation.

All WebSockets, both Inbound and Outbound, will have their own unique socket ID to identify them.

== Triggers

Triggers will fire the execution of a flow upon receiving a message or event notification. These are the available triggers for WebSocket related events:

* Inbound Message Listener: will expose an endpoint that external systems can connect to and trigger the containing flow whenever a message is received.
* On Inbound Connection: will initiate a flow when a new connection to the Inbound Listener is established.
* Outbound Message Listener: exposes an endpoint that will trigger a flow when an Outbound WebSocket receives a message from an external system.
* On Close: will trigger the containing flow when a WebSocket endpoint is closed.

== Operations

* Open Outbound Socket
* Send: sends a message through a WebSocket.
* Subscribe: subscribes a WebSocket to one or more groups. It can be invoked on the same socket as many times as necessary, each invocation being additive over the previous ones. Repeated groups will be ignored.
* Broadcast: send a message to several sockets classified by path, type and group.
* Close: closes a WebSocket connection.

== Supported Protocols

This connector supports both URI(uniform resource identifier) schemes defined by the WebSocket specification.

* WS: identifies a WebSocket server and resource name, e.g: ws://localhost:80.
* WSS: identifies a WebSocket server and resource name and supplies a secure communication channel that guarantees all traffic will be protected via TLS, e.g: wss://localhost:433.

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect 
to APIs and resources on external systems, such as Salesforce, WebSocket, ServiceNow,
and Twitter.

== Prerequisites

Before creating an app, you must have access to the WebSocket target resource and 
Anypoint Platform. You must also understand how to create a Mule app using 
Design Center or Anypoint Studio.

== Audience

* Starting user -- Read this Get Started document and create your Mule app in 
xref:websockets/websocket-connector-design-center.adoc[Design Center] or 
xref:websockets/websocket-connector-studio.adoc[Anypoint Studio]. 
The xref:websockets/websocket-connector-config-topics.adoc[Additional Configuration Information] topic
helps you extend your understanding of WebSocket actions.
* Power user - Read xref:websockets/websocket-connector-xml-maven.adoc[XML and Maven Support], 
the xref:websockets/websocket-connector-config-topics.adoc[Additional Configuration Information] topic, 
and xref:websockets/websocket-connector-examples.adoc[Examples].

=== Compatibility

The WebSocket Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.2.x or higher
|Amazon Java SDK for EC2|v1.11.134
|Java |1.8.0_x
|Anypoint Studio|7.3 or higher
|===

Audience without the "Additional Configuration Information" topic:

== Audience

* Starting user -- Read this Get Started document and create your Mule app in 
xref:websockets/websocket-connector-design-center.adoc[Design Center] or 
xref:websockets/websocket-connector-studio.adoc[Anypoint Studio]. 
* Power user - Read xref:websockets/websocket-connector-xml-maven.adoc[XML and Maven Support]
and xref:websockets/websocket-connector-examples.adoc[Examples].

== Common Use Cases for this Connector

WebSockets are useful for real-time applications where you need to avoid the overhead caused by the HTTP request-response pattern. WebSockets enables a server to push data to all subscribed clients as soon as it becomes available, without forcing the clients to overwhelm the server with requests.

A typical use case example would be a chat application, as soon as a client sends a message to a chat group, all the other subscribed participants will want to receive that message as soon as it becomes available. Using HTTP would imply that the clients would need to constantly poll the server for available messages, this could result in performance issues. Using webSockets, however, the server can simply push the available message to all subscribed users.

== Next

After you have met the prerequisites and experimented with templates 
and examples, you are ready to create an app with
xref:websockets/websocket-connector-design-center.adoc[Design Center] or 
xref:websockets/websocket-connector-studio.adoc[Anypoint Studio].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
