= WebSocket Examples - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

This is a short demonstration of how to use Websockets connector in Studio. We will create a basic app to send a message using a WebSocket send operation and receive it using a WebSocket Inbound Listener.

1. Go to Global Elements tab. Create a basic HTTP Request Listener Config and name it 'httpListenerConfig'.
    Settings:
        . Host: localhost
        . Port: 8081

2. In the Global Elements tab go to Connector Config and create a WebSockets Config. Check both Server Settings and Client Settings and introduce the following values:

    Server Settings:
        . Listener base path: /ws
        . Listener config: 'httpListenerConfig'

    Client Settings:
        . Base path: /ws
        . Host: localhost
        . Port: 8081

3. Back in the Message Flow Canvas create a flow by dragging and dropping an Inbound Listener. An error will occur as it will be missing a configuration. Go to Basic Settings and select the Websocket Configuration you created in step 1. In the General section specify Path: '/ws'.

4. After the Inbound Listener, place a logger component and log the received message: #['Received ' ++ payload].

5. Generate a second flow by dragging and dropping an HTTP Listener, reference your 'httpListenerConfig' and set your path so that it's different from '/chat'. For example, '/wstest'.

6. After the HTTP Listener place an Open Outbound Socket component and reference the Websocket Config created in step 1. An error will occur as you must specify a path or url. Set Path to '/chat'.

7. Finally, add the third and last component to the flow: Send. The Send operation will also require you to reference the Websocket Config created in step 1. In General set socketId to: #[attributes.socketId] and write a message in the Content section, for example 'Hello World!'.


You can run this application and test it by sending an HTTP GET to localhost:8081/testws or whichever path you chose in step 5.

The Inbound Listener should receive the message sent and you should see it logged in the console.

[source,xml,linenums]
----
	<websocket:config name="WebSockets_Config" doc:name="WebSockets Config" >
		<websocket:connection >
			<websocket:server-settings listenerConfig="httpListenerConfig" listenerBasePath="/ws"/>
			<websocket:client-settings host="localhost" port="8081" basePath="/ws"/>
		</websocket:connection>
	</websocket:config>

	<http:listener-config name="httpListenerConfig" doc:name="HTTP Listener config">
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<flow name="websockets-example-docsFlow" >
		<websocket:inbound-listener doc:name="Inbound listener"config-ref="WebSockets_Config" path="/chat"/>
		<logger level="INFO" doc:name="Logger" message="#['Received ' ++ payload]"/>
	</flow>
	<flow name="websockets-example-docsFlow1" >
		<http:listener doc:name="Listener" config-ref="httpListenerConfig" path="/testws"/>
		<websocket:open-outbound-socket doc:name="Open outbound socket" config-ref="WebSockets_Config" path="/chat"/>
		<websocket:send doc:name="Send" config-ref="WebSockets_Config" socketId="#[attributes.socketId]">
			<websocket:content ><![CDATA[#['Hello World!']]]></websocket:content>
		</websocket:send>
	</flow>
----

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
