= About Websocket Client Components
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket

== WebSocket Client Components

=== Open Outbound Socket Operation

This operation establishes a connection to a remote endpoint, producing an Outbound WebSocket.

==== Output

This operation returns a WebSocketAttributes Object in the attributes and an empty payload.

==== Socket Id

The WebSocketAttributes Object will provide you with a Socket Id (unless you specify your own socket Id in the <ws:open-outbound-socket> operation using the socketId parameter). If you specify your own id, you must make sure that the id is unique. Failure to do so with result in a `WEBSOCKET:NON_UNIQUE_SOCKET_ID` error.

Once the connection has been established, the Socket Id can be accessed using the following expression: `#[attributes.socketId]`. This attribute is especially important because it is what you will use to reference the connection in many operations. You will need the Socket Id to reference that WebSocket in any operation, such as sending messages or closing said WebSocket.

You can also automatically subscribe the newly established outboun WebSocket to a set of groups. This allows the WebSocket to participate in broadcast operations targeting any of those groups. 

NOTE: Keep in mind that only the Outbound WebSocket is subscribed to those groups. If the remote system is also a Mule application, the Inbound listener that exists in the other end of the connection is not automatically subscribed to any these groups.

[source,xml,linenums]
----
<flow ​name​=​"connectToMuleStocksAndSendMessage"​>
    ​<websocket:open-outbound path=​"/quotes"​ ​config-ref​=​"ws"​ ​defaultGroups​=​"#[['MULESOFT']]"​/>

    <websocket:send doc:name="Send" config-ref="ws" socketId="#[attributes.socketId]">
        <websocket:content>#['Hello World!']</websocket:content>
    </websocket:send>
</flow>
----

==== Headers and Query Parameters

Because WebSockets are established by the means of an Http request, you can include your own query parameter and headeres on such request. They can be defined using DataWeave expressions in the same way as in the http connector.

For example:

[source,xml,linenums]
----
<flow ​name​=​"connect"​>
    <websocket:open-outbound-socket path="/chatEcho" config-ref="ws" target="connectionAttributes" targetValue="#[attributes]">
        <websocket:headers><![CDATA[
                #[
                    {
                        chatAlias: 'Captain Marvel',
                        personalities: 'Vers',
                        personalities: 'Carol Danvers'
                    }
                ]
            ]]>
        </websocket:headers>
        <websocket:query-params><![CDATA[
                #[
                    {
                        theme: 'USA'
                    }
                ]
            ]]>
        </websocket:query-params>
    </websocket:open-outbound-socket>
</flow>
----

==== ERRORS

* If you attempt to establish a connection to a socket with an invalid Socket Id, this operation will fail with `WEBSOCKET:INVALID_SOCKET_ID`.
* If you attempt to establish a connection to an non-existing endpoint, this operation will fail with `WEBSOCKET:CONNECTIVITY`.
* If you attempt to establish a connection to valid endpoint but an invalid path, this operation will fail with `WEBSOCKET:SERVICE_UNAVAILABLE`.
* If an already existing Socket Id is provided for this operation, it will fail with `WEBSOCKET:NON_UNIQUE_SOCKET_ID`.

=== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
* xref:http/websockets-connector-get-started.adoc[About WebSocket Connector]
* xref:http/websockets-connector-config-topics.adoc[About WebSocket Connector Configuration]
* xref:http/websockets-connector-connection-close.adoc[About Closing A WebSocket Connection]
* xref:http/websockets-connector-attributes-object.adoc[About WebSocket Attributes Object]
