= WebSocket Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

To configure a connector in Anypoint Studio:

. Install the connector.
. Configure the connector.
. Configure an input source for the connector.

== Install the Connector  

. In Anypoint Studio, click the Anypoint Exchange icon in the Studio task bar.
. In Anypoint Exchange, click *Login* and supply your Anypoint Platform username and password.
. Search for the WebSocket connector, click the card for the connector, and click *Add to project*.
. Follow the prompts.

== Configure the Connector

. Go to the Global Elements tab, click *create* button and select the WebSockets Config from Connector Configuration.
. If you want your connector to listen for incoming requests check 'Configure Inbound WebSocket' section, if you want to perform requests to external services check 'Configure Outbound WebSocket' section. Or check out both if your application will be doing both.

=== Configure Inbound WebSocket

. Go to the Global Elements tab, click *create* button and select the HTTP Listener Config from Connector Configuration.
. In your WebSockets Configuration check the *Server settings* box.
. Specify the listener base path(optional) and reference the HTTP Listener Config you created before.

=== Configure Outbound WebSocket

. In your WebSockets Configuration check the *Client settings* box.
. Specify Host(optional), Port(optional) and Path(optional).
. In the Default Headers section and Query Parameters section you can introduce your default values for headers and query parameters by selecting an option from the drop-down list: select 'Expression' to enter a dwl expression or 'Edit Inline' to enter key/value pairs by clicking the '+' sign.

== Configure an Input Source

Configure an input source for the connector.

You can put the following operations for the connector in the *Source* area 
of the Studio canvas.

* Inbound Listener.
* On Outbound Socket Message.
* On Inbound Connection (Requires an Inbound Listener).
* On Socket Closed.

== Next

Now that you have completed configuring Studio, 
see the xref:websockets/websocket-connector-config-topics.adoc[Additional Configuration Information] topic
for more configuration ideas.

== See Also

* xref:http/websockets-connector-get-started.adoc[About WebSocket Connector]
* xref:http/websockets-connector-config-topics.adoc[About WebSocket Config]
