= WebSocket Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

WebSocket Connector Version 1.0

WebSockets are a key piece of modern integration due to their ability to:

* Establish bi-directional and full duplex communication between server and client.
* Implement server push patterns
* Seamlessly work on top of the existing HTTP infrastructure.
* Avoid polling

== Common Use Cases for this Connector

WebSockets are useful for real-time applications where you need to avoid the overhead caused by the HTTP request-response pattern. 

For example, in traditional HTTP, a client connects to a server and sends a request. The server processes it and sends a response back, after which, the connection is ended.

With WebSockets, a client connects to a server but a persistent connection is established and is maintained open. Both client and server can send as many messages to one and other as they wish, without the need to follow the request-response pattern. Actually, none of the parts are obligated to send a response to any of the messages. This is called Full Duplex Connection.

The difference between a WebSocket and a traditional Socket (TCP or UDP), is that this full duplex protocol is built on top of existing HTTP infrastructure, making it easy to reuse infrastructure alreayd in place for traditional HTTP.

A typical use case example would be a chat application, as soon as a client sends a message to a chat group, all the other subscribed participants will want to receive that message as soon as it becomes available. Using HTTP would imply that the clients would need to constantly poll the server for available messages, this could result in performance issues. Using webSockets, however, the server can simply push the available message to all subscribed users.

Another example would be a service that provides stock quotes. Clients can open a WebSocket to such service, which will continously send updated prices for a set of relevant stocks. Because such prices change continuosly, the ability to reuse the same connection and receive messages at random times make WebSockets an ideal solution for this problem (notice that in this case, the client doesn't really send any messages to the server after the connection has been established).

== Basic Concepts

=== Socket Types

There are two types of WebSockets:

* Inbound: these are WebSockets that are created because an external system connected to an endpoint exposed by your Mule application. In simple words, these are sockets that are produced as a result of your Mule Application listening for incoming connections.
* Outbound: these are WebSockets in which your Mule application is the one that initiated the communication and requested an external system to establish a WebSocket. In simple words, these are sockets that are produced as a result of your Mule Application connecting to an external system.

=== Socket Id

All WebSockets, both Inbound and Outbound, will have their own unique socket ID to identify them. Keeping track of these ids is very important, as you'll need them to reference the WebSockets you'll want to operate on.

=== Groups

Groups are String identifiers that all Websockets can be optionally subscribed to. This is useful for what we call `Message segregation`, which is the ability to broadcast one single message to a group of different WebSockets. Groups are a mechanism to facilitate the process of identifying which WebSockets should participate on each broadcast.

Groups are not a concept taken from the WebSockets protocol. They are a tool introduced by this connector to easily perform segregation during broadcast operations. This means that all these suscriptions will only exists in the context of each instance of a Mule WebSocket Connector Configuration. Therefore, when a WebSocket is established between a Mule app and a remote system, subscribing the WebSocket on Mule's end of the connection to a group doesn't have any effect on the WebSocket on the remote system's end.

== Triggers

Triggers will fire the execution of a flow upon receiving a message or event notification. These are the available triggers for WebSocket related events:

* Inbound Message Listener: will expose an endpoint that external systems can connect to and trigger the containing flow whenever a message is received.
* On Inbound Connection: will initiate a flow when a new connection to the Inbound Listener is established.
* Outbound Message Listener: exposes an endpoint that will trigger a flow when an Outbound WebSocket receives a message from an external system.
* On Close: will trigger the containing flow when a WebSocket (either Inbound or Outbound) is closed.

== Operations

* Open Outbound Socket: Connects to an external system and produces an outbound WebSocket.
* Send: sends a message through a WebSocket.
* Subscribe Groups: subscribes a WebSocket to one or more groups. It can be invoked on the same socket as many times as necessary, each invocation being additive over the previous ones. Repeated groups will be ignored.
* Unsubscribe Groups: unsubscribes a WebSocket from one or more groups. It can be invoked on the same socket as many times as necessary, each invocation being additive over the previous ones. Repeated groups will be ignored.
* Broadcast: send a message to several sockets classified by path, type and group.
* Close: closes a WebSocket connection.

== Security Schemes

The connector supports securing both the client and server endpoints through the use of TLS. This means that the following URI schemes are supported:

* WS: identifies a WebSocket server and resource name without any encryption (e.g: ws://localhost:80).
* WSS: identifies a WebSocket server and resource name, secure through TLS (e.g: wss://localhost:433).

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect 
to APIs and resources on external systems, such as Salesforce, WebSocket, ServiceNow,
and Twitter.

== Prerequisites

Before creating an app, you must have access to the WebSocket target resource and 
Anypoint Platform. You must also understand how to create a Mule app using 
Design Center or Anypoint Studio.

== Audience

* Starting user -- Read this Get Started document and create your Mule app in 
xref:websockets/websocket-connector-design-center.adoc[Design Center] or 
xref:websockets/websocket-connector-studio.adoc[Anypoint Studio]. 
The xref:websockets/websocket-connector-config-topics.adoc[Additional Configuration Information] topic
helps you extend your understanding of WebSocket actions.
* Power user - Read xref:websockets/websocket-connector-xml-maven.adoc[XML and Maven Support], 
the xref:websockets/websocket-connector-config-topics.adoc[Additional Configuration Information] topic, 
and xref:websockets/websocket-connector-examples.adoc[Examples].

=== Compatibility

The WebSocket Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.2.2 or higher
|Amazon Java SDK for EC2|v1.11.134
|Java |1.8.0_x 
|Anypoint Studio|7.4 or higher
|===

Audience without the "Additional Configuration Information" topic:

== Audience

* Starting user -- Read this Get Started document and create your Mule app in 
xref:websockets/websocket-connector-design-center.adoc[Design Center] or 
xref:websockets/websocket-connector-studio.adoc[Anypoint Studio]. 
* Power user - Read xref:websockets/websocket-connector-xml-maven.adoc[XML and Maven Support]
and xref:websockets/websocket-connector-examples.adoc[Examples].



== Next

After you have met the prerequisites and experimented with templates 
and examples, you are ready to create an app with
xref:websockets/websocket-connector-design-center.adoc[Design Center] or 
xref:websockets/websocket-connector-studio.adoc[Anypoint Studio].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
