= About Websocket Connection Management Components
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket

== About Closing A WebSocket Connection

=== Close Operation

This operation enables a Websocket to close a currently open connection. The socket id whose connection is to be closed must be provided.

[source,xml,linenums]
----
<flow name="closeConnection">
    <websocket:close-socket ​socketId​=​"#[attributes.socketId]"​ reason="I don't like to talk."/>
</flow>
----

==== Output

This operation returns no payload or attributes.

=== On Socket Closed

This component's owner flow will be triggered each time a connection is closed. This is useful to perform cleanup operations such as logging or updating the application's state.

This is asynchronous. By the time this flow is invoked the socket has already been closed. Don’t try to send messages through it.

[source,xml,linenums]
----
<flow name="onConnectionClosed">
    <websocket:on-connection-closed ​path​=​"/chat/*" ​config-ref​=​"ws"​ />
    <logger level="INFO" message="No more messages please: you shall not pass." />
</flow>

<flow name="receiveMessagesFlow">
    <websocket:on-inbound-connection path="/chat" config-ref="ws" />
    <logger level="INFO" message="Someone just sent a message and now I will close this connection!" />

    <websocket:close-socket ​socketId="#[attributes.socketId]" reason="I don't like to talk." ​config-ref​=​"ws"​ />
</flow>

----

The path parameter indicates the path of sockets that when closed will trigger the flow. To indicate 'catch-all' you can use the Wildcard symbol(*).

==== Output

This operation returns an empty payload and a WebSocketAttributes Object in the attributes.

== See Also

* xref:http/websockets-connector-client-components.adoc[About Websocket Client Components]
* xref:http/websockets-connector-server-components.adoc[About Websocket Server Components]
* xref:http/websockets-connector-get-started.adoc[About WebSocket Connector]
