= About Websocket Connection Configuration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket

== About Websocket Connector Configuration

There are two possible approaches to configuring a Websocket Connector. Both approaches will require an underlying HTTP Configuration from which several connection settings will be inherited, however these settings can be overridden in the Websocket configuration or at the operation level.

=== Approach 1: Mimic HTTP Connector

The first approach describes how to configure the connector in a structurally similar way to the HTTP Connector. It is somewhat more difficult, however, to select which configuration reference to use in each operation.

[source,xml,linenums]
----
<websocket:listener-config ​name​=​"wsListener"​> ​
    <websocket:listener-connection ​basePath​=​"/ws" listenerConfig​=​"httpListenerConfig"​ />
</websocket:listener-config>

<websocket:client-config ​name​=​"wsClient"​> ​
    <websocket:client-connection ​requesterConfig​=​"httpRequesterConfig" basePath​=​"/push"​ />
</websocket:client-config>

<flow name="chatFlow">
    ​<websocket:inbound-listener ​path​=​"/chat"​ ​config-ref​=​"wsListener"​ />
    ​
    <!--Send message through an INBOUND connection, use listener config-->
    <websocket:send ​config-ref​=​"wsListener"​ socketId​=​"#[attributes.socketId]">
  ​  ​   <websocket:content>​Hello!​</websocket:content> ​
    </websocket:send>

    <!--Send message through an OUTBOUND connection, use client config-->
    <websocket:send ​config-ref​=​"wsClient"​ socketId​=​"#[vars.outboundSocketId]"/>
    ​   <websocket:content>​Somebody just connected​</websocket:content>
    ​</websocket:send>
<flow>
----

=== Approach 2: Single Configuration

In this approach we define everything in one single configuration.

[source,xml,linenums]
----
<http:listener-config name="httpListenerConfig" basePath="/willBeOverriddenByWSConfig">
   <http:listener-connection host="0.0.0.0" port="${listenerPort}" />
</http:listener-config>

<websocket:config ​name​=​"ws"​> ​
    <websocket:connection>
    ​   <websocket:server-settings ​listenerConfig​=​"httpListenerConfig" listenerBasePath​=​"/ws"​/>
    ​   <websocket:client-settings ​host​=​"localhost" port​=​"${listenerPort}"​ ​basePath​=​"/ws"​>
    ​       <websocket:default-headers>
                ​<websocket:header ​key​=​"defaultHeader"​ v​alue​=​"defaultHeader1" />
                ​<websocket:header ​key​=​"defaultHeader"​ v​alue​=​"defaultHeader2" />
            ​</websocket:default-headers>
            ​<websocket:default-query-params>
                ​<websocket:query-param ​key​=​"defaultQueryParam" value="query1" />
                ​<websocket:query-param ​key​=​"defaultQueryParam" value="query2" />
            ​</websocket:default-query-params>
    ​   </websocket:client-settings>
    </websocket:connection>
</websocket:config>
----

In this example, we set the HTTP listener reference for the server configuration and its base path. We then set the default headers and query params, that will be sent along with every request made through Websocket client that references this configuration.

== See Also

* xref:http/websocket-about-websocket-connector.adoc[About Websockets Connector]
* xref:http/http-connector-xml-reference.adoc[HTTP Connector XML Reference]
* xref:http/websocket-connector-server-components.adoc[About Websockets Connector Server Components]
* xref:http/websocket-connector-client-components.adoc[About Websockets Connector Client Components]
* xref:http/websocket-connector-connection-management-components.adoc[About Websockets Connection Management Components]
