= About Websocket Connector In Studio
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket

== Websocket Connector (Studio)

This is a short demonstration of how to use Websockets connector in Studio. We will create a basic app to send and receive a message using WebSockets.

1. Go to Global Elements tab. Create a basic HTTP Request Listener Config and name it 'httpListenerConfig'.
    Settings:
        . Host: localhost
        . Port: 8081

2. In the Global Elements tab go to Connector Config and create a WebSockets Config. Check both Server Settings and Client Settings and introduce the following values:

    Server Settings:
        . Listener base path: /ws
        . Listener config: 'httpListenerConfig'

    Client Settings:
        . Base path: /ws
        . Host: localhost
        . Port: 8081

3. Back in the Message Flow Canvas create a flow by dragging and dropping an Inbound Listener. An error will occur as it will be missing a configuration. Go to Basic Settings and select the Websocket Configuration you created in step 1. In the General section specify Path: '/ws'.

4. After the Inbound Listener, place a logger component and log the received message: #['Received ' ++ payload].

5. Generate a second flow by dragging and dropping an HTTP Listener, reference your 'httpListenerConfig' and set your path so that it's different from '/chat'. For example, '/wstest'.

6. After the HTTP Listener place an Open Outbound Socket component and reference the Websocket Config created in step 1. An error will occur as you must specify a path or url. Set Path to '/chat'.

7. Finally, add the third and last component to the flow: Send. The Send operation will also require you to reference the Websocket Config created in step 1. In General set socketId to: #[attributes.socketId] and write a message in the Content section, for example 'Hello World!'.


You can run this application and test it by sending an HTTP GET to localhost:8081/wstest or whichever path you chose in step 5.

The Inbound Listener should receive the message sent and you should see it logged in the console.

== See Also

* xref:http/websocket-about-websocket-connector.adoc[About Websockets Connector]
* xref:http/websocket-connector-configuration.adoc[About Websockets Connector Configuration]
