= About Websocket Connection Management Components
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket

== About WebSockets Broadcasting

=== Broadcast Operation

The broadcast operation enables a socket to send a message to all other sockets:

    * Subscribed to a specific group.
    * Listening at a specific path.
    * Of a specific type (INBOUND/OUTBOUND).

The type and group parameters work in tandem, in an additive way. They are both optional and can be used separately, but when used together they act as two levels of filtering.

[source,xml,linenums]
----
<!-- send to all active sockets connected to the /quotes endpoint -->
<websocket:broadcast path=”/quotes” ​config-ref​=​"ws"​ />

<!-- send to all INBOUND sockets connected to the /quotes endpoint -->
<websocket:broadcast path=”/quotes” ​type​=​"INBOUND"​ ​config-ref​="​ws"​ />

<!-- send to all INBOUND sockets connected to the /quotes endpoint -->
<websocket:broadcast path=”/quotes” ​type​=​"OUTBOUND"​ ​config-ref​=​"ws"​ />

<!-- send to all INBOUND sockets connected to the /quotes endpoint, in the MARVEL and DC groups -->
<websocket:broadcast path=”/quotes” ​type​=​"INBOUND"​ ​groups​="​ #[['MARVEL', 'DC']]"​ ​config-ref​=​"ws"​ />
----

==== Output

This operation returns empty payload and attributes.

== See Also

* xref:http/websocket-about-websocket-connector.adoc[About Websocket Connector]
* xref:http/websocket-connector-configuration.adoc[About Websocket Connector Configuration]
* xref:http/websocket-connector.adoc[Websocket Connector]
