= About Websocket Client Components
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket

== WebSocket Client Components

=== Open Outbound Operation

This operation allows an OUTBOUND socket to establish a connection to a websocket endpoint.

In order to establish a connection a configuration reference must be provided. In addition, parameters like path and uri can be provided. For further reference check connector's technical reference.

The following example opens a connection reusing most of the settings defined in the configuration reference, but others like the uri are overridden.

==== Output

This operation returns a WebSocketAttributes Object in the attributes and an empty payload.

==== Socket Id

The WebSocketAttributes Object will provide you with a Socket Id (unless you specify your own socket Id in the <open-outbound> operation using the socketId parameter)

The Socket Id can be accessed using the following expression: #[attributes.socketId]. This attribute is especially important because it is what you will use to reference the connection in many operations. You will need the Socket Id to send messages through a WebSocket and close an established connection.

You can also indicate the default groups that this endpoint will be automatically subscribed to in the defaultGroups parameter. If any broadcast operations are performed to said groups, this endpoint will receive and process them. This subscription is done inside the app domain, which means that adding the default groups parameter will not send any information about this subscription to the inbound WebSocket counterpart, because the groups feature is not part of WS protocol. What this means, is that if we subscribe our outbound WebSocket to a group, that will be useful if other WebSockets within our app domain want to send a message to all other WebSockets, also in our app domain, which have been subscribed to the specified groups. In short, the group subscription will only affect WebSockets residing in the same app domain, and WebSockets from external applications will not be subscribed by our mule application to any groups.

[source,xml,linenums]
----
<flow ​name​=​"connectToMuleStocksAndSendMessage"​>
    ​<websocket:open-outbound path=​"/quotes"​ ​config-ref​=​"ws"​ ​defaultGroups​=​"#[['MULESOFT']]"​/>

    <websocket:send doc:name="Send" config-ref="ws" socketId="#[attributes.socketId]">
        <websocket:content>#['Hello World!']</websocket:content>
    </websocket:send>
</flow>
----

==== Headers and Query Parameters

You can add custom headers or query parameters to your connection operation. These will be sent along with the default headers and parameters in the initial HTTP request to establish the WS connection. They can be set using DataWeave expressions as shown in the example below.

[source,xml,linenums]
----
<flow ​name​=​"connect"​>
    <websocket:open-outbound-socket path="/chatEcho" config-ref="ws" target="connectionAttributes" targetValue="#[attributes]">
        <websocket:headers><![CDATA[
                #[
                    {
                        chatAlias: 'Captain Marvel',
                        personalities: 'Vers',
                        personalities: 'Carol Danvers'
                    }
                ]
            ]]>
        </websocket:headers>
        <websocket:query-params><![CDATA[
                #[
                    {
                        theme: 'USA'
                    }
                ]
            ]]>
        </websocket:query-params>
    </websocket:open-outbound-socket>
</flow>
----

==== ERRORS

* If you attempt to establish a connection to a socket with an invalid Socket Id, this operation will fail with WEBSOCKET:INVALID_SOCKET_ID.
* If you attempt to establish a connection to an non-existing endpoint, this operation will fail with WEBSOCKET:CONNECTIVITY.
* If you attempt to establish a connection to valid endpoint but an invalid path, this operation will fail with WEBSOCKET:SERVICE_UNAVAILABLE.
* If an already existing Socket Id is provided for this operation, it will fail with WEBSOCKET:NON_UNIQUE_SOCKET_ID.

=== See Also

* xref:http/websockets-connector-get-started.adoc[About WebSocket Connector]
* xref:http/websockets-connector-config-topics.adoc[About WebSocket Connector Configuration]
* xref:http/websockets-connector-attributes-object.adoc[About WebSocket Attributes Object]
