= About Websocket Server Components
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket

== About Websocket Server Components

=== Inbound Listener

The Inbound Listener component represents an websocket endpoint that clients can connect to. By hitting this endpoint, external clients not only establish a Websocket connection, they will trigger the owning server flow each time they send a message.

[source,xml,linenums]
----
<flow name="onIncomingMessage">
    <websocket:inbound-listener ​path​=​"/quotes"​ ​defaultGroups​=​"#[['AVENGERS', 'REVENGERS']]"​ ​config-ref​=​"ws"​ />
    <set-variable name="myMessage" value="#[payload]" />
    <set-variable name="senderSocketId" value="#[attributes.socketId]" />
    <set-variable name="senderSocketType" value="#[attributes.socketType]" />
    <set-variable name="senderSocketGroups" value="#[attributes.groups]" />
</flow>
----

The payload will be set with the received message content, and its mime-type will be obtained from the incoming HTTP request header. If not set, the mime-type will default to one of:

* application/octet-stream if it's binary content.
* text/plain if it's text content.

The output attributes will contain every attribute expected in the HttpRequestAttributes plus:

    * Receiving socket's id.
    * Receiving socket's type.
    * Group list the receiving socket is currently subscribed to.

=== On Inbound Connection

This component's owner flow will be triggered each time an INBOUND Websocket connection is established. This is useful to perform post-connect tasks such as logging or assigning the socket with a group.

Any messages being sent to or broadcasted from this socket will be queued until this operation has been resolved.

[source,xml,linenums]
----
<flow name="onNewInboundConnection">
    <websocket:on-inbound-connection ​path​=​"/ws/*"​ ​config-ref​=​"ws"​ />
    <logger level="INFO" message="#['New connection established with ' ++ attributes.socketId ]" />
</flow>
----


== See Also

* xref:http/websocket-about-websocket-connector.adoc[About Websockets Connector]
* xref:http/websocket-connector-client-components.adoc[About Websockets Connector Client Components]
* xref:http/websocket-connector-connection-management-components.adoc[About Websockets Connection Management Components]
* xref:http/websocket-connector-configuration.adoc[About Websockets Connector Configuration]
