= About Websocket Connection Configuration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket

== TLS for WebSockets

By default Websocket Connector will use WS, but you can configure the connector to use WSS.

=== TLS for Inbound Websocket

TLS and other http related configurations will be inherited from the referenced http listener config. So for example, in order to configure TLS on a WebSocket listener, just point to a <http:listener-config>​ with TLS configured:

=== TLS for Outbound Websocket

For Outbound Sockets the <websocket:client-settings> parameter is consistent with the <http:request-config> elements. The protocol parameter must indicate one of two options: WS (insecure) or WSS. If a protocol is not indicated, it will default to WS. A TLS Context must also be referenced in this case, either by referencing it through the tlsContext option or by adding a <tls:context> element.

[source,xml,linenums]
----
    <tls:context name="listenerTlsContext" >
        <tls:key-store path="tls/clientServerKeystore" keyPassword="mulepassword" password="mulepassword" alias="muleserver" />
    </tls:context>

    <http:listener-config name="listenerTlsConfig">
        <http:listener-connection protocol="HTTPS" host="localhost" port="${listenerPort}" tlsContext="listenerTlsContext"/>
    </http:listener-config>

    <tls:context name="requestTlsContextWithCertificate" >
        <tls:trust-store path="tls/trustStore" password="mulepassword" />
    </tls:context>

    <websocket:config name="requestConfigWithCertificate">
        <websocket:connection>
            <websocket:server-settings listenerConfig="listenerTlsConfig" listenerBasePath="/"/>
            <websocket:client-settings host="localhost" port="${listenerPort}" tlsContext="requestTlsContextWithCertificate" protocol="WSS"/>
        </websocket:connection>
    </websocket:config>
----

== See Also

* xref:http/websocket-about-websocket-connector.adoc[About Websockets Connector]
* xref:http/websocket-connector-configuration.adoc[About Websockets Connector Configuration]
