= About Websocket Connection Management Components
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket, broadcast

== About WebSockets Broadcasting

=== Broadcast Operation

The broadcast allows to send a certain message to a group of other sockets. The group of WebSockets to which the message can be broadcasted can be selected by:

    * Subscribed to specific groups.
    * Connected to a specific path.
    * Or being of a specific type (INBOUND/OUTBOUND).

The type and group parameters work in tandem, in an additive way. They are both optional and can be used separately, but when used together they act as two levels of filtering.

Examples: 

[source,xml,linenums]
----
<!-- send to all WebSockets connected to an endpoint of path /quotes -->
<websocket:broadcast path=”/quotes” ​config-ref​=​"ws"​ />

<!-- send to all Inbound WebSockets connected to an endpoint of path /quotes -->
<websocket:broadcast path=”/quotes” ​type​=​"INBOUND"​ ​config-ref​="​ws"​ />

<!-- send to all Outbound sockets connected to the /quotes endpoint -->
<websocket:broadcast path=”/quotes” ​type​=​"OUTBOUND"​ ​config-ref​=​"ws"​ />

<!-- send to all INBOUND sockets connected to the /quotes endpoint, in the MARVEL and DC groups -->
<websocket:broadcast path=”/quotes” ​type​=​"INBOUND"​ ​groups​="​ #[['MARVEL', 'DC']]"​ ​config-ref​=​"ws"​ />
----

==== Output

This operation returns empty payload and attributes.

== See Also

* xref:http/websocket-about-websocket-connector.adoc[About Websocket Connector]
* xref:http/websocket-connector-configuration.adoc[About Websocket Connector Configuration]
* xref:http/websocket-connector.adoc[Websocket Connector]
