= About Websocket Client Components
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, ws, wss, websocket

=== WebSocket Connector in VPC

If you choose to deploy your applications in a VPC(Virtual Private Cloud), you can configure your WebSocket connector to work in this environment. Dedicated Load Balancers will allow you to route WS and WSS traffic to Mule applications deployed into Cloud Hub in a particular Virtual Private Cloud(VPC).

To set up your WebSocket Connector, configure your <inbound-listener> to listen on 0.0.0.0. If you want to communicate over WS you will need to configure your listener to use port 8091, or use port 8092 if you want to communicate over WSS.

The next step is to deploy your application to your VPC and set up your Load Balancer's URL mapping rules. These rules will indicate your Dedicated Load Balancer to associate a URI to a specific Mule app. For example, if your app is called 'my-websocket-mule-app' you can define your rule as:

    * Input Path: /my-websocket-mule-app/
    * Target App: my-websocket-mule-app
    * Output Path: /
    * Protocol: ws

This will route all requests made to your Dedicated Load Balancer's URL and the specified Input Path to your Mule app's root path /. Your Load Balancer's name will determine its assigned URL, so for this example, if you name your Load Balancer 'mylb', then you would need to hit: ws://mylb.lb.anypointdns.net:80/my-websocket-mule-app/ to connect to your WebSocket Listener. Your Dedicated Load Balancer will forward all requests issued to port 80 to your app's port 8091, which will be destined for all WS connections. When using WSS, however, you will need to issue requests to port 443, and these requests will then be forwarded to your Mule app's port 8092.


=== See Also

* https://docs.mulesoft.com/runtime-manager/vpc-architecture-concept
* https://docs.mulesoft.com/runtime-manager/lb-architecture
* https://docs.mulesoft.com/runtime-manager/lb-mapping-rules
