= Configuring Foundational Model Operations

Configure the *FOUNDATIONAL Model Details* and *FOUNDATIONAL Model List* operations.

== Configure the FOUNDATIONAL Model Details Operation

The *FOUNDATIONAL Model Details* operation gets additional details for a foundational model.

To configure the *FOUNDATIONAL Model Details* operation:

include::connectors::partial$t-configure-operations.adoc[]
* *Model name*
+
The name of the LLM. You can select any model from the supported LLM Providers.

* *Region*
+
The AWS region.

This is the XML for this operation:

[source,xml,linenums]
----
<mac-bedrock:
  foundational-model-details 
  doc:name="Foundational model details"
  doc:id="d1abedc9-8600-440c-af24-2f913fff4dbe" 
  config-ref="AWS" 
  modelName="ai21.j2-mid-v1"
/>
----

=== Output Configuration

This operation responds with a JSON payload. This is an example response:

[source,json]
----
{
    "modelName": "Jurassic-2 Mid",
    "responseStreamingSupported": false,
    "modelId": "ai21.j2-mid-v1",
    "inputModalities": [
        "TEXT"
    ],
    "outputModalities": [
        "TEXT"
    ],
    "inferenceTypesSupported": [
        "ON_DEMAND"
    ],
    "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/ai21.j2-mid-v1",
    "modelLifecycleStatus": "ACTIVE",
    "customizationsSupported": [],
    "providerName": "AI21 Labs"
}
----

* `modelName`: The name of the model.
* `responseStreamingSupported`: Whether the model supports response streaming.
* `modelId`: The unique identifier for the model.
* `inputModalities`: The input modalities supported by the model.
* `outputModalities`: The output modalities supported by the model.
* `inferenceTypesSupported`: The inference types supported by the model.
* `modelArn`: The Amazon Resource Name (ARN) for the model.
* `modelLifecycleStatus`: The lifecycle status of the model.
* `customizationsSupported`: The customizations supported by the model.
* `providerName`: The name of the provider.

== Configure the FOUNDATIONAL Model List Operation

The *FOUNDATIONAL Model List* operation gets a list of all available foundational models on the AWS region.

To configure the *FOUNDATIONAL Model List* operation:

include::connectors::partial$t-configure-operations.adoc[]
* *Region*
+
The AWS region.

This is the XML for this operation:

[source,xml,linenums]
----
<mac-bedrock:
  foundational-models-list 
  doc:name="Foundational models list" 
  doc:id="a1683e27-72d8-42b4-9493-48ea5259f8c0"
  config-ref="AWS" 
/>
----

=== Output Configuration

This operation responds with a JSON payload. This is an example response:

[source,json]
----
[
    {
        "modelName": "Amazon",
        "responseStreamingSupported": true,
        "modelId": "amazon.titan-tg1-large",
        "provider": "Titan Text Large",
        "inputModalities": [
            "TEXT"
        ],
        "outputModalities": [
            "TEXT"
        ],
        "inferenceTypesSupported": [
            "ON_DEMAND"
        ],
        "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-tg1-large",
        "modelLifecycleStatus": "ACTIVE",
        "customizationsSupported": []
    },
    {
      ...
    },
    ...
]
----

* `modelName`: The name of the model.
* `responseStreamingSupported`: Whether the model supports response streaming.
* `modelId`: The unique identifier for the model.
* `provider`: The name of the provider.
* `inputModalities`: The input modalities supported by the model.
* `outputModalities`: The output modalities supported by the model.
* `inferenceTypesSupported`: The inference types supported by the model.
* `modelArn`: The Amazon Resource Name (ARN) for the model.
* `modelLifecycleStatus`: The lifecycle status of the model.
* `customizationsSupported`: The customizations supported by the model.

== See Also

* xref:index.adoc[Amazon Bedrock Connector Overview]
* xref:amazon-bedrock-connector-reference.adoc[Amazon Bedrock Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
