= Configuring Embedding Operations

Configure the *EMBEDDING Generate from Text* operation.

== Configure the EMBEDDING Generate from Text Operation

The *EMBEDDING Generate from Text* operation creates embeddings from a text provided as input. Embeddings are numerical vector representations of text that can be used for tasks like text similarity, clustering, and search functionalities.

To configure the *EMBEDDING Generate from Text* operation:

include::connectors::partial$t-configure-operations.adoc[]
* *Prompt*
+
The text as plain text for the operation to generate embeddings from.

* *Model name*
+
The name of the LLM. You can select any model from the supported LLM Providers.

* *Region*
+
The AWS region.

* *Dimension*
+
The number of dimensions the output embeddings should have. Accepted values are 1024 (default), 512, or 256.

* *Normalize*
+
A flag indicating whether to normalize the output embeddings. Defaults to `true`.

This is the XML for this operation:

[source,xml,linenums]
----
<mac-bedrock:
  embedding-generate-from-text 
  doc:name="Embedding generate from text" 
  doc:id="3e79af34-8551-4a2b-9458-150f2ac22a36" 
  config-ref="AWS" 
  prompt="#[payload.prompt]"
/>
----

=== Output Configuration

This operation responds with a JSON payload. This is an example response:

[source,json]
----
{
   "inputTextTokenCount": 17,
   "embedding": [
      0.0058898926,
      -0.11621094,
      0.26171875,
      -0.30078125,
      -0.15527344,
      -0.24707031,
      0.296875,
      4.15802E-4,
      -0.17285156
   ]
}
----

* `inputTextTokenCount`
+
The number of tokens used to process the input text.

* `embedding`
+
An array of floating-point numbers representing the vector embedding of the input text.

== See Also

* xref:index.adoc[Amazon Bedrock Connector Overview]
* xref:amazon-bedrock-connector-reference.adoc[Amazon Bedrock Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
