= Insert large file's content into table Examples - Mule 4
:page-aliases: connectors::db/db-connector-insert-large-clob.adoc

Anypoint Connector for Database (Database Connector) supports the *Insert* operation of character large objects (CLOBs) into tables.

In the following example, you read a large file's content and insert it into a table that supports that type.

The following SQL statement creates the table:
[source,sql,linenums]
----
CREATE TABLE AWESOMECLOBDATA(
    id INT AUTO_INCREMENT PRIMARY KEY,
    clob_data CLOB
);
----

== Configure the Read Operation in Studio

To read the file properly, define the following configuration:
[source,xml,linenums]
---
<file:config name="File_Config">
    <file:connection workingDir="/dir/containing/file/"/>
</file:config>
---

And configure the *Read* operation like this:
[source,xml,linenums]
---
<file:read config-ref="File_Config" path="awesomeFile.json" outputMimeType="application/octet-stream"/>
---

=== On application/octet-stream MIME Type
This type converts the contents of the file to `binary` format allowing the proper handover of data from the *Read* operation to the *Insert* operation.

If, for example, `text/plain` is used as MIME Type then an OOM error would arise since the DW block (on the Input Parameters from the *Insert* operation) will try to convert to text the whole data-stream from the file before delivering the data to the operation itself.

Finally, the `application/json` MIME Type can also be used but when referencing the payload use `payload.^raw` on the *Insert* operation.

== Configure the Insert Operation in Studio

Given that the table `AWESOMECLOBDATA` is already created and there is a Database Connector connection configuration named `dbConfig`, you can configure the *Insert* operation that inserts a new record with the file's content in the table:

. In your Studio flow, select the *Insert* operation.
. In the XML editor, the `<db:insert>` configuration looks like this:

[source,xml,linenums]
----
<db:insert config-ref="dbConfig">
    <db:sql>
        <![CDATA[INSERT INTO AWESOMECLOBDATA (clob_data) VALUES (:payload)]]></db:sql>
    <db:input-parameters ><![CDATA[#[{
                                        payload: payload
                            }]]]>
    </db:input-parameters>
</db:insert>
----

The `id` parameter is not passed in the query because it is an auto-increment key that is generated automatically by the database.

== See Also

* xref:database-connector-examples.adoc[Database Connector Examples]
* https://docs.mulesoft.com/file-connector/1.3/[File Connector]
* https://help.mulesoft.com[MuleSoft Help Center]
