= Zendesk Connector - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]
// If this is a Premium connector, change Select to Premium

Anypoint Connector for Zendesk provides ...

For information about compatibility and fixed issues, see Zendesk Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Zendesk Connector's API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to:

* The Zendesk target resource
* Anypoint Platform
* Anypoint Studio version <x.x> or later
*// If your connector has other prerequisites specific to this connector, list them here.

== Common Use Cases For the Connector

// List common use cases for the Zendesk Connector and provide
// a link to the xref:zendesk-connector-examples.adoc[Examples] use cases.

These are some common use cases for Zendesk Connector...

== Audience
// Adjust this list as necessary. Not all connectors include an Additional Configuration topic and some may contain additional topics to reference

* New user
+
To create your Mule app, see:

* xref:zendesk-connector-studio.adoc[Studio Configuration]
* xref:zendesk-connector-config-topics.adoc[Additional Configuration Information]
to help extend your understanding of Zendesk Connector
* xref:zendesk-connector-examples.adoc[Examples], with use case information for the connector
+
* Advanced user
+
* Read the following:

* xref:zendesk-connector-xml-maven.adoc[XML and Maven Support]
* xref:zendesk-connector-config-topics.adoc[Additional Configuration Information]
* xref:zendesk-connector-examples.adoc[Examples], with use case information for the connector

// The following line is only needed for connectors with upgrade information

For a major or minor release, see
xref:zendesk-connector-upgrade-migrate.adoc[Upgrade and Migrate].

== Connection Types

// If there is one authentication type, use the following format:

Zendesk connections use the <authentication-type> authentication type, which ... <add a brief description of the authentication type like the descriptions below>.

////
If there is more than one authentication type, use a list like the one shown below (use only the applicable connection types--delete the others):

Zendesk connections can use the following authentication types:

* Basic authentication
+
Uses a username and password for authentication
+
* OAuth
+
Uses access tokens provided by the authorization server to get access to protected data
+
* OAuth2
+
Delegates user authentication to the service hosting the user account
+
Kerberos
+
Uses the Kerberos principal as the username. The keytab path you specify obtains a ticket-granting ticket (TGT) from the authorization server.
////

For information about configuring authentication types, see xref:zendesk-studio.adoc[Use Studio to Configure Zendesk Connector].

////
Include the following section only if Exchange provides templates, examples, or both for the connector. If there are templates and not examples, or vice versa, reword the section as applicable.
////

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as a starting point for your app, as well as examples that illustrate a complete solution.

////
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////

== Next Step

After you complete the prerequisites and try the templates and examples, you are ready to create an app and configure the connector using xref:zendesk-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
