= Use Anypoint Studio to Configure Amazon Kinesis Data Streams Connector 1.0 - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Studio (Studio) editors help you design and update your Mule applications, properties, and configuration files.

To add and configure a connector in Studio:

. <<create-mule-project,Create a mule project>>.
. <<add-connector-to-project,Add the connector to your Mule project>>.
. <<add-connector-operation,Add a connector operation to the flow>>.
. <<configure-global-element,Configure a global element for the connector>>
. <<conigure-other-fields,Configure the other connector fields>>.

When you run the connector, you can view the app log to check for problems, as described in <<view-app-log,View the App Log>>.

If you are new to configuring connectors in Studio, see xref:connectors::introduction/intro-config-use-studio.adoc[Use Studio to Configure a Connector]. If, after reading this topic, you need additional information about the connector fields, see the xref:amazon-kinesis-connector-reference.adoc[Amazon Kinesis Reference].

[[create-mule-project]]
== Create a Mule Project

In Studio, create a new Mule project in which to add and configure the connector:

. In Studio, select *File > New > Mule Project*.
. Enter a name for your Mule project and click *Finish*.

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

Add Anypoint Connector for Amazon Kinesis Data Streams Connector (Amazon Kinesis Data Streams Connector) to your Mule project to automatically populate the XML code with the connector's namespace and schema location and add the required dependencies to the project's `pom.xml` file:

. In the *Mule Palette* view, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type `kinesis` in the search field.
. Click *Amazon Kinesis* in *Available modules*. (*Reviewers, is *Amazon Kinesis* correct? I can't see the connector because it is not in Exchange yet.* )
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio does not make that connector available to other projects in your Studio workspace.

[[configure-consumer]]
=== Configure a Source

A source initiates a flow when a specified condition is met.
You can configure one of these sources to use with Amazon Kinesis Data Streams Connector:

* *Kinesis Stream Listener* (Applies to the consumer configuration)
+
Enables a consumer to subscribe to a particular data stream. This source uses the Kinesis Client Library (KCL) to listen from a specified initial point in the data stream. It returns individual records.
+
* *Kinesis Stream Batch Listener* (Applies to the consumer configuration)
+
Works similarly to *Kinesis Stream Listener*, but returns batches of records instead of individual ones. The size of the batch is dynamic.
+
* *HTTP > Listener* (Applies to both the consumer and producer configurations)
+
Initiates a flow each time it receives a request on the configured host and port
* *Scheduler* (Applies to both the consumer and producer configurations)
+
Initiates a flow when a time-based condition is met

For example, to configure the *Kinesis Stream Listener* source in the consumer configuration, follow these steps:

. In the *Mule Palette* view, select *Kinesis*.
. Drag *Kinesis Stream Listener* to the Studio canvas.
. On the *Kinesis Stream Listener* configuration screen, optionally change the value of the *Display Name* field.
. Click the plus sign (*+*) next to the *Connector configuration* field to configure a global element that can be used by all instances of Amazon Kinesis Connector in the app.
. On the *General* tab, specify connection information for the connector.
. On the *Security* tab, optionally specify the TLS information for the connector.
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.

[[add-connector-operation]]
== Add a Connector Operation to the Flow

When you add a connector operation to your flow, you immediately define a specific operation for that connector to perform.

You can use the following operations in the consumer configuration:

* *Checkpoint*, which keeps track of the current position in the Kinesis data stream
* *Get Sequence Number*, which locates the closest sequence number in a Kinesis shard after the specified timestamp
* *Seek*, which moves the reading position of the sources (listeners)
+
While moving forward in the stream is fluent, moving backward causes an internal restart of the Kinesis Client Library (KCL) instance. Therefore, use this operation sparingly to move backward in a stream.

You can use the *Put Record* operation in the producer configuration. This operation puts a record into the Kinesis data stream in batch with aggregation, which xxx. Records include binary data, partitionKey and explicitHashKey. The explicitHashKey value is normally computed with the MD5 function of the record partition key, but you can override the Explicit Hash Key with explicitHashKey field. The operation uses KPL which increases throughput.

To add an operation for Amazon Kinesis Data Streams Connector, follow these steps:

. In the *Mule Palette* view, select *Kinesis* and then select the desired operation.
. Drag the operation onto the Studio canvas to the right of the source.

[[configure-global-element-consumer]]
== Configure a Global Element for the Connector

When you configure a connector, it's best to configure a global element that all instances of that connector in the app can use. Configuring a global element requires you to provide the authentication credentials that the connector requires to access the target Amazon Kinesis Data Streams system.

Amazon Kinesis Data Streams Connector supports the following types of authentication, which you configure in the global element:

* Key-based authentication
+
This type of authentication uses the *Access Key* and *Secret Key* fields for AWS Identity and Access Management (IAM).
+
* Role-based authentication
+
This type of authentication uses the *Role* field for AWS IAM.

When you configure a global element, you can reference a configuration file that contains ANT-style property placeholders (recommended), or you can enter your authorization credentials in the global configuration properties. For information about the benefits of using property placeholders and how to configure them, see xref:introduction/intro-connector-configuration-overview.adoc[Anypoint Connector Configuration].


[[global-element-consumer]]
=== Configure a Global Element for the Consumer Configuration

To configure a global element for the consumer configuration, follow these steps:

. Select the name of the connector in the Studio canvas.
. In the configuration screen for the operation, click the plus sign (*+*) next to the *Connector configuration* field to access the global element configuration fields.
. On the *General* tab, configure the following fields.
+
[%header,cols="30s,70a"]
|===
|Field |Description
|Name | Enter the name used to reference the connector instance.
|Kinesis Client Library | Click *Configure* and select a local file dependency or a Maven dependency. (*Reviewers, what about the Add recommended libraries* option?)
|TLS Configuration *???* | xxx
|Secret Key |Enter the secret key, which acts like a password.
|Region Endpoint | Enter the URL entry point for a web service.
|Role | Optionally enter the Amazon IAM role.
|Default Stream Name | Global value for the stream name to use in all operations
|===
+
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.

[[configure-global-element-producer]]
=== Configure a Global Element for the Producer Configuration

To configure the global element for Amazon Kinesis Producer, follow these steps:

. Select the name of the connector in the Studio canvas.
. In the configuration screen for the operation, click the plus sign (*+*) next to the *Connector configuration* field to access the global element configuration fields.
. On the *General* tab, configure the following fields:
+
[%header,cols="30s,70a"]
|===
|Field |Description
|Name | Enter the name used to reference the connector instance.
|Kinesis Producer Library | Click *Configure* and select a local file dependency or a Maven dependency. (*Reviewers, what about the Add recommended libraries* option?)
|Access Key | Enter an alphanumeric text string that uniquely identifies the user who owns the AWS account.
|Secret Key |Enter the secret key, which acts like a password.
|Region Endpoint | Enter the URL entry point for a web service.
|Role | Optionally enter the Amazon IAM role.
|Default Stream Name | Global value for the stream name to be used in all operations

|===

[[configure-other-fields]]
== Configure Additional Connector Fields

After you configure a global element for Amazon Kinesis Connector, configure the the other required fields for the connector operation.

For example, to use the *Put Record* operation in the producer configuration, enter a value for the *Partition Key* field. This field identifies the shard in the stream to which the data record is assigned. To use the *Seek* operation in the consumer configuration, enter values for these fields:

[%header,cols="30s,70a"]
|===
|Field |Description
|Consumer ID | Unique consumer identifier
|Shard ID | Initial reading point in the data stream
|Sequence Number | Sequence number from which the source listens
|===

[[view-app-log]]

== View the App Log

To check for problems, you can view the app log as follows:

* If you're running the app from Anypoint Platform, the app log output is visible in the Anypoint Studio console window.
* If you're running the app using Mule from the command line, the app log output is visible in your OS console.

Unless the log file path is customized in the app's log file (`log4j2.xml`), you can also view the app log in the default location `MULE_HOME/logs/<app-name>.log`. You can configure the location of the log path in the app log file `log4j2.xml`.

== Next Step

After you configure a global element and connection information, configure the other fields for the connector. See xref:amazon-kinesis-connector-config-topics.adoc[Additional Configuration Information] for more configuration steps.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
// Add link to connector reference and specific connector intro topic
* https://help.mulesoft.com[MuleSoft Help Center]
