= Use Anypoint Studio to Configure Amazon Kinesis Data Streams Connector 1.0 - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Studio (Studio) editors help you design and update your Mule applications, properties, and configuration files.

To add and configure a connector in Studio:

. <<create-mule-project,Create a mule project>>.
. <<add-connector-to-project,Add the connector to your Mule project>>.
. <<add-connector-operation,Add a connector operation to the flow>>.
. <<configure-global-element,Configure a global element for the connector>>
. <<configure-other-fields,Configure the other connector fields>>.

When you run the connector, you can view the app log to check for problems, as described in <<view-app-log,View the App Log>>.

If you are new to configuring connectors in Studio, see xref:connectors::introduction/intro-config-use-studio.adoc[Use Studio to Configure a Connector]. If, after reading this topic, you need additional information about the connector fields, see the xref:amazon-kinesis-connector-config-topics.adoc[Amazon Kinesis Configuration].

[[create-mule-project]]
== Create a Mule Project

In Studio, create a new Mule project in which to add and configure the connector:

. In Studio, select *File > New > Mule Project*.
. Enter a name for your Mule project and click *Finish*.

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

Add Anypoint Connector for Amazon Kinesis Data Streams Connector (Amazon Kinesis Data Streams Connector) to your Mule project to automatically populate the XML code with the connector's namespace and schema location and add the required dependencies to the project's `pom.xml` file:

. In the *Mule Palette* view, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type `kinesis` in the search field.
. Click *Amazon Kinesis* in *Available modules*. (*Reviewers, is *Amazon Kinesis* correct? I can't see the connector because it is not in Exchange yet.* )
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio does not make that connector available to other projects in your Studio workspace.

=== Configure a Source

A source initiates a flow when a specified condition is met.
You can configure one of these sources to use with Amazon Kinesis Data Streams Connector:

* *Kinesis Stream Batch Listener*
+
Enables you to subscribe to a particular data stream. This source uses the Kinesis Client Library (KCL) to listen from a specified initial point in the data stream. Returns dynamically sized batches of records however the max size can be configured.
+
* *HTTP > Listener*
+
Initiates a flow each time it receives a request on the configured host and port
+
* *Scheduler*
+
Initiates a flow when a time-based condition is met

For example, to configure the *Kinesis Stream Listener* source, follow these steps:

. In the *Mule Palette* view, select *Kinesis*.
. Drag *Kinesis Stream Listener* to the Studio canvas.
. On the *Kinesis Stream Listener* properties window, optionally change the value of the *Display Name* field.
. Click the plus sign (*+*) next to the *Connector configuration* field to configure a global element that can be used by all instances of the Amazon Kinesis Connector in the app.
. On the *General* tab, complete the following fields:
+
[%header,cols="30s,70a"]
|===
|Field a|Description
|Name |
|Kinesis Client Libary | *Need a description for this field*
|Access Key |
|Secret Key |
|Region Endpoint |
|Role |
|Default Stream Name |
|===
+
. On the *Security* tab, optionally specify the TLS information for the connector.
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.
. In the *Listener Params* section of the *Kinesis Stream Listener* properties window, enter values for these required fields:
+
[%header,cols="30s,70a"]
|===
|Field |Description
|Application Name | Name of your app. Multiple sources can share the same app name. *(Reviewers, does these mean that multiple sources can share the use the same app?)*
|Acknowledgement mode | Unique identifier for the source. Connector operations can use this name to reference this source configuration. *(Reviewers, what does this do for the other operations?)*

[[add-connector-operation]]
== Add a Connector Operation to the Flow

When you add a connector operation to your flow, you immediately define a specific operation for that connector to perform.

You can use the following operations:

* *Checkpoint*, which keeps track of the current position in the Kinesis data stream
* *Seek*, which moves the reading position of the sources (listeners)
+
While moving forward in the stream is fluent, moving backward causes an internal restart of the Kinesis Client Library (KCL) instance. Therefore, use this operation sparingly to move backward in a stream.
+
* *Put Record*, which puts a record into the Kinesis data stream.
+
If Aggregation is enabled, multiple records are combined and stored in one Kinesis Data Streams record. For more information on how this mechanism works visit xref:amazon-kinesis-connector-advanced-config.adoc[Amazon Kinesis Connector Configuration].

Records include binary data, partitionKey and explicitHashKey. The explicitHashKey value is normally computed with the MD5 function of the record partition key, but you can override the Explicit Hash Key with explicitHashKey field. The operation uses KPL which increases throughput.

To add an operation for Amazon Kinesis Data Streams Connector, follow these steps:

. In the *Mule Palette* view, select *Kinesis* and then select the desired operation.
. Drag the operation onto the Studio canvas to the right of the source.

[[configure-global-element]]
== Configure a Global Element for the Connector

When you configure a connector, it's best to configure a global element that all instances of that connector in the app can use. Configuring a global element requires you to provide the authentication credentials that the connector requires to access the target Amazon Kinesis Data Streams system.

Amazon Kinesis Data Streams Connector supports Access Key authentication, which uses the *Access Key* and *Secret Key* field values for AWS Identity and Access Management (IAM).

When you configure a global element, you can reference a configuration file that contains ANT-style property placeholders (recommended), or you can enter your authorization credentials in the global configuration properties. For information about the benefits of using property placeholders and how to configure them, see xref:connectors::introduction/intro-connector-configuration-overview.adoc[Anypoint Connector Configuration].

To configure a global element, follow these steps:

. Select the name of the connector in the Studio canvas.
. In the configuration screen for the operation, click the plus sign (*+*) next to the *Connector configuration* field to access the global element configuration fields.
. On the *General* tab, configure the following fields.
+
[%header,cols="30s,70a"]
|===
|Field |Description
|Name | Enter the name used to reference the connector instance.
|Kinesis Client Library | Click *Configure* and select a local file dependency or a Maven dependency. (*Reviewers, what about the Add recommended libraries* option?)
|Proxy | Optionally, you can setup your proxy details if your network setup requires it.
|Access Key |Enter the Access key, which acts like an username.
|Secret Key |Enter the secret key, which acts like a password.
|Region Endpoint | Enter the URL entry point for a web service.
|Role | Optionally enter the Amazon IAM role.
|Default Stream Name | Name of the stream to use by default if an operation doesn’t specify it.
|Default Application Name|  Name of the app to use by default if an operation that requires this value doesn’t specify it.
|===
+
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.

[[view-app-log]]

== View the App Log

To check for problems, you can view the app log as follows:

* If you're running the app from Anypoint Platform, the app log output is visible in the Anypoint Studio console window.
* If you're running the app using Mule from the command line, the app log output is visible in your OS console.

Unless the log file path is customized in the app's log file (`log4j2.xml`), you can also view the app log in the default location `MULE_HOME/logs/<app-name>.log`. You can configure the location of the log path in the app log file `log4j2.xml`.

== Next Step

After you configure a global element and connection information, configure the other fields for the connector. See xref:amazon-kinesis-connector-config-topics.adoc[Additional Configuration Information] for more configuration steps.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
// Add link to connector reference and specific connector intro topic
* https://help.mulesoft.com[MuleSoft Help Center]
