= Amazon Kinesis Data Streams Connector Examples - Mule 4

Common use cases for the connector include:

. Use real-time dashboards to evaluate events
. Use log and event data collection to analyze problems 

== Use Case: Putting record to specific stream in a batch

The operation puts a record into a Kinesis Data Stream in batch with aggregation which increases shard throughput. Record includes binary data, partitionKey and explicitHashKey. The explicitHashKey value is normally computed with the MD5 function of the record partition key but you can override the Explicit Hash Key with explicitHashKey field. The operation uses KPL which increases throughput.

  PLACE FOR IMAGE OF FLOW

. Create a new Mule project in Studio.
. Drag an *HTTP Listener* into the canvas, and select it to open the properties editor.
. Add a new *HTTP Listener* Config global element:
.. In General Settings, click the *+* button:
.. Configure the following HTTP parameters, retain the default values for the other fields, and click *OK*.
+
[%header%autowidth.spread]
|===
|Field |Value
|Name |HTTP_Listener_Configuration
|Host |127.0.0.1
|Port |8081
|===
+
.. Reference the HTTP Listener Configuration global element. In the General tab, specify the `/` *Path*.
. Drag a *Put Record* operation into the flow, and double-click it to open its properties editor.
.. If you don't have an existing Amazon Kinesis producer global element to choose, click the plus sign next to *Connector Configuration*.
.. Configure the global element properties, and then click *OK*.

+
.. Configure the connector parameters in the properties window:
+
[%header%autowidth.spread]
|===
|Field |Value
|Display Name |Name for the connector operation
|Connector Configuration |Global configuration you just created
|Stream name |Name of the stream 

If provided, the value of this field takes precedence over the value of the *Default Global Stream name* field on the *Global Configuration Elements* window.

|Partition key |Partition key.
|Data |Content with size up to 1MB.
|===
+

For example:

  PLACE FOR IMAGE OF PUT RECORD CONFIG

. Drag a *Transform Message* component into the flow and double click on it
.. In the *Transform Message* configuration, add this script to the *Output* section:

+
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
payload
----
The following screenshot shows the script as it appears in the Output section of Studio:

  PLACE FOR IMAGE OF DATAWEAVE SCRIPT

. In the Mule Palette view, search for *Logger*.
.. Drag the component onto the canvas, to the right of the *Transform Message* component.
.. Configure the following fields:

+
[%header%autowidth.spread]
|===
|Field |Value
|Display Name |Name for the logger, such as `Log Response`
|Message | #[payload]
|Level |INFO (Default)
|===
The following screenshot shows the logger configuration as it appears in Studio:

  IMAGE OF LOGGER CONFIG


=== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
