= Amazon Kinesis Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]
// If this is a Premium connector, change Select to Premium

Anypoint Connector for Amazon Kinesis provides ...
// Document the benefits/functionality of the connector

For compatibility information and fixed issues, see the Amazon Kinesis Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Amazon Kinesis Data Streams API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* AWS Identity and Access Management (IAM) credentials
* Access to the Amazon Kinesis target resource
* Anypoint Studio version 4.1.0 or later

== Common Use Cases for the Connector
// Make the title singular if there is just one use case

// Add a lead in sentence and then list common use cases for the connector
// Make the title singular if there is just one case

// For examples, see xref:amazon-kinesis-connector-examples.adoc[Examples].

== Audience
// Adjust this list as necessary. Not all connectors include an Additional Configuration topic

* New users, read:
** xref:amazon-kinesis-connector-studio.adoc[Use Studio to Configure the Connector] to create your Mule app
** xref:amazon-kinesis-connector-config-topics.adoc[Additional Configuration Information]
to help extend your understanding of the Amazon Kinesis connector
** xref:amazon-kinesis-connector-examples.adoc[Examples], which provide one or more use cases for the connector
* Advanced users, read:
** xref:amazon-kinesis-connector-xml-maven.adoc[XML and Maven Support]
** xref:amazon-kinesis-connector-config-topics.adoc[Additional Configuration Information] to help extend your understanding of the Amazon Kinesis connector
** xref:amazon-kinesis-connector-examples.adoc[Examples], which provides one or more use cases for the connector

== Authentication Types

//If there is one authentication type, use the following format:

<connector name> connections use the <authentication-type> authentication type, which ... <add a brief description of the authentication type like the descriptions below>.

//If there is more than one authentication type, use a list like this:

////
<connector name> connections use the following authentication types:

* Basic authentication +
Uses a username and password for authentication
+
* OAuth +
Uses access tokens provided by the authorization server to get access to protected data
+
* OAuth2 +
Delegates user authentication to the service hosting the user account
+
* Kerberos +
Uses the Kerberos principal as the username. The `keytab` path you specify obtains a ticket-granting ticket (TGT) from the authorization server.
////

For information about configuring these authentication types, see xref:Amazon Kinesis-studio.adoc[Use Studio to Configure Amazon Kinesis].


////
Include this section only if Exchange provides templates, examples, or both for the connector. If there are templates and not examples, or vice versa, reword the section as applicable.
////

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as starting points for your apps and examples that illustrate a complete solution.

////
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////

== Next Step

After you complete the prerequisites and try the templates and examples, you are ready to create your own app and configure the connector using xref:amazon-kinesis-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
