= Amazon Kinesis Data Streams Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Amazon Kinesis Data Streams (Amazon Data Streams Connector)
// Document the benefits/functionality of the connector

This connector provides a single common configuration that enables access to both writing and reading operations on your
Kinesis stream given you have the necessary permissions assigned to your account. To learn more about configuring the
connector read: xref:amazon-kinesis-connector-config-topics.adoc[Kinesis Streams Configuration]

For compatibility information and fixed issues, see the Amazon Kinesis Data Streams Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Amazon Kinesis Data Streams API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* AWS Identity and Access Management (IAM) credentials
* Access to the Amazon Kinesis target resource
* Anypoint Studio version 4.1.0 or later

== Common Use Cases for the Connector

Common use cases for Kinesis Data Streams connector include the following:

* Troubleshooting
+
Collect log and event data from sources such as servers, desktops, and mobile devices. Then build continuously process the data, generate metrics, power live dashboards, and put the aggregated data into data stores such as Amazon S3.
+
* Real-time analytics
+
Run real-time analytics on high frequency event data such as sensor data or social media data collected by Kinesis Data Streams. These analytics enable you to gain insights from your data at a frequency of minutes instead of a frequency of hours or days.
+
* Mobile data capture
+
Have your mobile applications push data to Kinesis Data streams from hundreds of thousands of devices, making the data available to you as soon as it is produced on the mobile devices.

For examples, see xref:amazon-kinesis-connector-examples.adoc[Examples].

== Audience
// Adjust this list as necessary. Not all connectors include an Additional Configuration topic

* New users, read:
** xref:amazon-kinesis-connector-studio.adoc[Use Studio to Configure the Connector] to create your Mule app
** xref:amazon-kinesis-connector-config-topics.adoc[Additional Configuration Information]
to help extend your understanding of the Amazon Kinesis connector
** xref:amazon-kinesis-connector-examples.adoc[Examples], which provide one or more use cases for the connector
* Advanced users, read:
** xref:amazon-kinesis-connector-xml-maven.adoc[XML and Maven Support]
** xref:amazon-kinesis-connector-config-topics.adoc[Additional Configuration Information] to help extend your understanding of the Amazon Kinesis connector
** xref:amazon-kinesis-connector-examples.adoc[Examples], which provides one or more use cases for the connector

== Authentication Types

*Should we call these authenticatin types Consumer basic, Producer basic instead of Consumer/Producer access key?*

Amazon Kinesis Data Streams Connector connections use the following authentication types:

* Consumer access key
+
Consumers authenticate to AWS by using an access key and secret key, and, optionally, a role.
+
* Producer access key
+
Producers authenticate to AWS by using an access key and secret key, and, optionally, a role.


For information about configuring these authentication types, see xref:Amazon Kinesis-studio.adoc[Use Studio to Configure Amazon Kinesis Data Streams].

////
Include this section only if Exchange provides templates, examples, or both for the connector. If there are templates and not examples, or vice versa, reword the section as applicable.
////

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as starting points for your apps and examples that illustrate a complete solution.

////
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////

== Next Step

After you complete the prerequisites and try the templates and examples, you are ready to create your own app and configure the connector using xref:amazon-kinesis-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
