= Asana Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Asana (Asana Connector) synchronizes data and automates business processes between Asana and third-party applications, either on-premises or in the cloud.

Asana is a SaaS project management tool that enhances team collaboration. Employees can easily manage projects and tasks through one integrated collaborative project management interface when using Asana.

For compatibility information and fixed issues, see the Asana Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Asana APIs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Automate powerful business processes by integrating Asana with other IT tools and systems in your enterprise such as messaging, calendar, and issue triaging systems. Possible uses include:

* Improve cross-team communication by automating a workflow where users get notified (via a messaging system such as Slack) anytime a task or comment is created in Asana.

* Enhance sales collaboration by automating the lead tracking and nurturing process where any time a new lead or opportunity is created in your CRM system (such as Salesforce), a task is created and assigned to a user via your Asana dashboard for triaging and tracking.

* Help teams stay organized by integrating the team’s calendar with an Asana workspace so that anytime a new team event is created, it gets posted to the Asana workspace.

== Authentication Types

Asana Connector connections use the following authentication methods:

* OAuth 2.0
* Unsecure connection provider


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:asana-connector-reference.adoc[Asana Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
