= Microsoft Dynamics 365 for Finance and Operations Connector 3.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]


Anypoint Connector for Microsoft Dynamics 365 for Finance and Operations (Microsoft Dynamics 365 for Finance and Operations Connector) enables integration with Microsoft Dynamics 365 for Operations Web API.

== Prerequisites

To use this connector, you must be familiar with:

* The Microsoft Dynamics 365 for Finance and Operations API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to a Microsoft Dynamics 365 instance (online or on-premises) managed by Azure Active Directory.


== Common Use Cases for the Connector

This connector enables you to perform these operations:

* Authorize or unauthorize access to a Microsoft Dynamics 365 for Finance and Operations server
* Create a recurring job on Microsoft Dynamics 365 for Finance and Operations server
* Retrieve multiple entries, including retrieval using DataSense Query Language
* Execute operations

See xref:microsoft-365-finance-operations-connector-examples.adoc[Examples] for use cases.


== Audience

* New users, read:
** xref:microsoft-365-finance-operations-connector-studio.adoc[Use Studio to Configure the Connector] to create your Mule app
* xref:microsoft-365-finance-operations-connector-examples.adoc[Examples], which provides an example use case for the connector
* Advanced users, read:
** xref:microsoft-365-finance-operations-connector-xml-maven.adoc[XML and Maven Support]
* The xref:microsoft-365-finance-operations-connector-examples.adoc[Examples], which provide one or more use cases for the connector

== Authentication Types

Microsoft Dynamics 365 for Finance and Operations Connector uses the OAuth 2.0 authentication connection type, which delegates user authentication to the service hosting the user account.

== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app and configure the connector using xref:microsoft-365-finance-operations-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:microsoft-365-ops-connector-reference.adoc[Microsoft Dynamics 365 for Finance and Operations Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
