= Upgrade Microsoft Dynamics for Finance and Operations Connector to Version 3.0 - Mule 4

Anypoint Connector for Microsoft Dynamics 365 for Finance and Operations (Microsoft Dynamics 365 for Finance and Operations Connector) version 3.0 supports OAuth Client Credentials authentication.  

== Supported Upgrade Paths

// Is this a direct upgrade (from previous version to latest version) or 
// a “multi-version-hop” upgrade? What is the supported path?

[%header,cols="50a,50a"]
|===
|From Version | To Version
|2.x.x |3.x.x
|===

== Changes in This Release

The OAuth Client Credentials connection authentication type has been added in Microsoft Dynamics 365 for Finance and Operations Connector version 3.0. To use this authentication method, you must use Mule 4.2.1 or later. 

== Requirements

Ensure that you are using Mule 4.2.1 or later before you perform the upgrade.

== Upgrade Prerequisites

Before you perform the upgrade, you must create a backup of your files, data, and configurations in case you need to restore to them. 

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, open the Mule project for your connector.
. In the Anypoint Studio menu, select *Help > Check for Updates*. 
. Select the latest version of *Mule Server Runtime* and click *Next*.
. Select *I accept the terms of the license agreement* and click *Finish*.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `dynamics finance` in the search field.
. In *Available modules*, select *Microsoft Dynamics 365 for Operations* and click *Add*.
. Click *Finish*.
. Click *Yes* to restart Studio. +
Studio upgrades the connector automatically.
. After Studio restarts, verify that the dependency version is 3.0.0 in the `pom.xml` file in the Mule project.

== Post-Upgrade Steps

After you install the latest version of the connector, follow these steps to complete the upgrade:

// * Do they need to update endpoints? 
// * Do they need to re-create/refactor any customizations?
// * Does the user need to map any files?
// * Verify the upgrade.

=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Troubleshoot

If there are common known issues and errors that occur when upgrading, give troubleshooting tips.

=== Revert the Upgrade

If it is necessary to revert to the previous version of Microsoft Dynamics 365 for Finance and Operations Connector Connector, change the `mule-microsoft-dynamics365-for-operations-connector` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.


