= Google Sheets Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Google Sheets (Google Sheets Connector) provides access to standard spreadsheet operations. Google Sheets is a spreadsheet program included as part of the free, web-based Google Docs office suite offered by Google within its Google Drive service.

Google Sheets Connector provides operations that you can use to perform tasks on spreadsheets and drives. You can create and update rows in a spreadsheet, checks for changes in spreadsheets, and checks for newly created spreadsheets.

For compatibility information and fixed issues, see the Google Sheets Connector release notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Google Sheets and Google Drive APIs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have access to:

* The Google Sheets and target resource
* Anypoint Studio version 4.2.1 or later

== Common Use Case for the Connector

Use Google Sheets Connector to check for newly-created spreadsheets, insert or update rows in a spreadsheet, get information about inserted or updated rows, create spreadsheets, and retrieve metadata information about spreadsheets.

== Next Step

After you complete the prerequisites, you are ready to create your own app and configure the connector using xref:google-sheets-connector-studio.adoc[Anypoint Studio] or xref:google-sheets-connector-design-center.adoc[Flow Designer].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
