= Workday - Studio Configuration - Mule 4
:page-aliases: connectors::workday/workday-studio.adoc, connectors::workday/workday-connector-studio.adoc

Anypoint Studio (Studio) editors help you design and update your Mule applications, properties, and configuration files.

To add and configure a connector in Studio:

. <<create-mule-project,Create a Mule project>>.
. <<add-connector-to-project,Add the connector to your Mule project>>.
. <<configure-input-source,Configure an input source for the connector's flow>>.
. <<add-connector-operation,Add a connector operation to the flow>>.
. <<configure-global-element,Configure a global element for the connector>>.

When you run the connector, you can view the app log, as described in <<view-app-log,View the App Log>>.

If you are new to configuring connectors in Studio, see xref:connectors::introduction/intro-config-use-studio.adoc[Use Studio to Configure a Connector]. If, after reading this topic, you need additional information about the connector fields, see the xref:workday-reference.adoc[Workday Reference].

[[create-mule-project]]
== Create a Mule Project

In Studio, create a new Mule project in which to add and configure the connector: 

. In Studio, select *File > New > Mule Project*.
. Enter a name for your Mule project and click *Finish*.

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

Add Workday Connector to your Mule project to automatically populate the XML code with the connector's namespace and schema location and add the required dependencies to the project's `pom.xml` file:

. In the *Mule Palette* view, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type `workday` in the search field.
. Click *Workday Connector* in *Available modules*.
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio does not make that connector available to other projects in your Studio workspace.

[[configure-input-source]]
== Configure an Input Source

An input source initiates a flow when a specified condition is met.
You can configure one of these input sources to use with Workday Connector:

* On Modified Objects +
Starts your app when an object is created, modified, or deleted in Workday.
* HTTP Listener +
Starts your app using a browser or a command such as `curl`.
* Scheduler +
Starts your app at specified timed intervals.

To configure an *On Modified Objects* input source:

. In the *Mule Palette* view, select *Workday > On Modified Objects*.
. Drag *On Modified Objects* to the Studio canvas.
. On the *On Modified Objects* configuration screen, optionally change the value of the *Display Name* field.
. Enter the required information for the following fields:
* *Object type* 
* *Scheduling Strategy* +
Tells the source how it can poll the data. This field accepts two options:
** *Fixed Frequency*
+
Polls for data at a specified number of milliseconds, seconds, minutes, hours, or days. The default is 1000 milliseconds.
** *Cron*
+
Accepts an expression that polls for data based on a filter, such as, every Monday in a month at a given time. See xref:mule-runtime::scheduler-concept.adoc#cron-expressions[Cron Expressions] for examples.
+
. Click the plus sign (+) next to the *Connector configuration* field to <<configure-global-element,configure a global element>> that can be used by all instances of the On Modified Objects operation in the app.


[[add-connector-operation]]
== Add a Connector Operation to the Flow

When you add a connector operation to your flow, you immediately define a specific operation for that connector to perform. Workday Connector operations enable your app to process data received from the input source. 

To add an operation for Workday Connector, follow these steps:

. In the *Mule Palette* view, select *Workday* and then select the desired operation.
. Drag the operation onto the Studio canvas to the right of the input source.

Each Workday operation has its own required fields in Anypoint Studio. For more information, see
the xref:workday-reference.adoc[Connector Reference].

[[configure-global-element]]
== Configure a Global Element

When you configure a connector, it’s best to configure a global element that all instances of that connector in the app can use. Configuring a global element requires you to provide the authentication credentials the connector uses to access the target Workday system. 

To configure the global element for Workday Connector, follow these steps:

. Select the name of the connector in the Studio canvas.
. In the configuration screen for the operation, click the plus sign (+) next to the *Connector configuration* field to access the global element configuration fields.
. On the *General* tab, configure the authentication for the connector:
+
[%header,cols="30s,70a"]
|===
|Field |Description
|Configuration Name |The name of the configuration.
|Connection |The connection associated with the configuration.
|Username |Username to log in to Workday with
|Password |Password that corresponds to the username 
|Tenant Name | Workday Tenant ID, which usually has the suffix `pt1` appended to it, such as `acme_pt1`.
This parameter supports expressions, which allow the value of the parameter to change dynamically. For example, you can use an expression to create a multi-tenant connection.
|Host Name | Host name of one of Workday’s cloud servers. The default value is: `impl-cc.workday.com`.
|===
+
You can reference a configuration file that contains ANT-style property placeholders (recommended), or you can enter your authorization credentials in the global configuration properties. For information about the benefits of using property placeholders and how to configure them, see xref:connectors::introduction/intro-connector-configuration-overview.adoc[Anypoint Connector Configuration].
+
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server. +
To validate connectivity using the *Test Connection* button, Workday Connector uses an Identity_Management WSDL service with the `Get_Workday_Account_Signons_Request` operation. You must ensure that your service account has permissions to operate on that service. 
. Click *OK*.


[[view-app-log]]
== View the App Log

You can view the app log as follows:

* If you’re running the app from Anypoint Platform, the output is visible in the Anypoint Studio console window.
* If you’re running the app using Mule from the command line, the app log is visible in your OS console.

Unless the log file path was customized in the app’s log file (`log4j2.xml`), you can view the app log in this default location: `MULE_HOME/logs/<app-name>.log`.

== Next Step

After configuring Workday Connector in Studio, see the xref:workday-connector-examples.adoc[Examples] for financial management use cases that demonstrate the use of this connector.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
