= MongoDB Connector 6.0 - Mule 4



MongoDB Connector Version 6.0

Anypoint Connector for MongoDB (MongoDB Connector) is a closed-source connector that provides a connection between the Mule runtime engine (Mule) and third-party software on a MongoDB server.

Release Notes: xref:release-notes::connector/mongodb-connector-release-notes-mule-4.adoc[MongoDB Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-mongodb-connector/[MongoDB Connector]

== Before You Begin

To use this information, you must be familiar with MongoDB, Mule runtime engine (Mule), Anypoint Connectors, Anypoint Studio, elements in a Mule flow, and global elements.

Before creating an app, you must have access to the MongoDB target resource and Anypoint Platform. You must also understand how to create a Mule app using Anypoint Studio.

To use the this connector, you need:

* A MongoDB instance
* A set of valid credentials, including the required MongoDB endpoints that point to your instance


== Audience

* Starting user
+
To create your Mule app, see xref:mongodb-connector-studio.adoc[Studio Configuration].
* Power user
+
Read xref:mongodb-connector-xml-maven.adoc[XML and Maven Support]
and xref:mongodb-connector-examples.adoc[Examples].

== Exchange Example

https://www.mulesoft.com/exchange/org.mule.examples/importing-a-CSV-file-into-Mongo-DB/[Anypoint Exchange] has an example that shows how to import data in a CSV format from a local directory into MongoDB.

== Important Considerations when Migrating from Mule 3 to Mule 4

When migrating Mule apps from Mule 3 to Mule 4 that use MongoDB Connector, consider the following changes in date handling:

* *Automatic conversion to UTC*
+
In Mule 3, MongoDB Connector stores dates exactly as they are sent, preserving the original timezone. However, in Mule 4, all dates (whether they are sent to or retrieved from MongoDB) are automatically converted to UTC before they are stored in MongoDB. This change ensures more consistent and standardized date handling in a distributed environment. 

* *ISO 8601 format*
+
Dates (whether they are sent to or retrieved from MongoDB) in JSON documents are transformed to the ISO 8601 format. Additionally, any String values in JSON documents that match the ISO 8601 format are automatically transformed and stored as Date types in MongoDB. This change ensures more consistent and standardized date handling in a distributed environment. 

* *Millisecond truncation*
+
Dates that include milliseconds with a value of `.000` are not shown in the output generated by MongoDB Connector in Mule 4. This behavior differs from Mule 3, in which all date components are preserved.

Here is an example of the changes in date handling in a Mule app when migrating from Mule 3 to Mule 4:

Mule 3:
[source,json,linenums]
----
{
  "timeStamp": "2024-06-17T16:44:17.000+01:00"
}
----

Mule 4:
[source,json,linenums]
----
{
  "timeStamp": "2024-06-17T15:44:17+00:00"
}
----

Because of these changes in date handling, it is important to:

* *Review data flows involving dates*
+
If your Mule apps rely on specific timezones of dates stored in MongoDB, you must review and possibly adjust flows to correctly handle the UTC conversion in Mule 4.

* *Test thoroughly*
+
Conduct thorough testing in a controlled environment to ensure that the changes in date handling do not negatively impact the expected behavior of the Mule app.

* *Document the behavioral differences*
+
Document the key differences in date handling between Mule 3 and Mule 4 to ensure smooth transition and adaptation.

== Next Steps

After you have met the prerequisites and experimented with the example, you are ready to create an app with xref:mongodb-connector-studio.adoc[Studio].

== See Also

* xref:connectors::introduction/intro-use-exchange.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
