= Upgrade Quickbooks Connector to Version 2.0 - Mule 4

Upgrade Anypoint Connector for Quickbooks (Quickbooks Connector) to version 2.x.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|1.x |2.x
|===

== Changes in This Release

This release contains the following changes:

* Made the following changes to some operations:
** <<changed_operations, Changed operation names>>
** The *Get query* operation now makes an HTTP GET request instead of an HTTP POST request to the /query endpoint
** The *Get invoice by invoice id* operation now makes an HTTP GET request instead of an HTTP POST request to the /invoice/{invoiceId} endpoint
** The *Upload* operation now has the *File_content_0-Body* parameter, the *File_content_0-Filename* parameter, and the *File_metadata_0-Body* parameter
** Removed the *Content type* parameter from all operations
** Removed the *Accept* parameter from all operations
** Added the *Body* parameter to some operations
* <<new_sources, Added sources>>


[[changed_operations]]
== Changed Operations

The following table shows changes to operation names:

[%header%autowidth.spread]
|===
|Quickbooks 1.x Operation | Changes in Quickbooks 2.0

| *Account Post2*
a| Operation is now called *Create account*.

| *Account Update*
a| Operation is now called *Create account update*.

| *Attachable Post3*
a| Operation is now called *Create attachable*.

| *Batch Post*
a| Operation is now called *Create batch*.

| *Bill Post3*
a| Operation is now called *Create bill*.

| *Billpayment Post3*
a| Operation is now called *Create billpayment*.

| *Class Post3*
a| Operation is now called *Create class*.

| *Creditmemo Post3*
a| Operation is now called *Create creditmemo*.

| *Customer Post3*
a| Operation is now called *Create customer*.

| *Department Post3*
a| Operation is now called *Create department*.

| *Deposit Post3*
a| Operation is now called *Create deposit*.

| *Employee Post3*
a| Operation is now called *Create employee*.

| *Estimate Post3*
a| Operation is now called *Create estimate*.

| *Invoice Post4*
a| Operation is now called *Create invoice*.

| *Item Post3*
a| Operation is now called *Create item*.

| *Journalentry Post3*
a| Operation is now called *Create journalentry*.

| *Payment Post3*
a| Operation is now called *Create payment*.

| *Paymentmethod Post3*
a| Operation is now called *Create paymentmethod*.

| *Preferences Post*
a| Operation is now called *Create preferences*.

| *Purchase Post3*
a| Operation is now called *Create purchase*.

| *Purchaseorder Post3*
a| Operation is now called *Create purchaseorder*.

| *Query Post32*
a| Operation is now called *Get query*.

| *Refundreceipt Post3*
a| Operation is now called *Create refundreceipt*.

| *Salesreceipt Post4*
a| Operation is now called *Create salesreceipt*.

| *Taxagency Post*
a| Operation is now called *Create taxagency*.

| *Taxservice Taxcode Post*
a| Operation is now called *Create taxservice taxcode*.

| *Term Post3*
a| Operation is now called *Create term*.

| *Timeactivity Post4*
a| Operation is now called *Create timeactivity*.

| *Transfer Post3*
a| Operation is now called *Create transfer*.

| *Upload Post*
a| Operation is now called *Create upload*.

| *Vendor Post3*
a| Operation is now called *Create vendor*.

| *Vendorcredit Post3*
a| Operation is now called *Create vendorcredit*.

| *Account Get*
a| Operation is now called *Get account by account id*.

| *Attachable Get*
a| Operation is now called *Get attachable by attachable id*.

| *Bill Get*
a| Operation is now called *Get bill by bill id*.

| *Billpayment Get*
a| Operation is now called *Get billpayment by billpayment id*.

| *Cdc Get*
a| Operation is now called *Get cdc*.

| *Class Get*
a| Operation is now called *Get class by class id*.

| *Companyinfo By Companyid Get*
a| Operation is now called *Get companyinfo by company id*.

| *Creditmemo Get*
a| Operation is now called *Get creditmemo by creditmemo id*.

| *Customer Get*
a| Operation is now called *Get customer by customer id*.

| *Department Get*
a| Operation is now called *Get department by department id*.

| *Deposit Get*
a| Operation is now called *Get deposit by deposit id*.

| *Employee Get*
a| Operation is now called *Get employee by employee id*.

| *Estimate Get*
a| Operation is now called *Get estimate by estimate id*.

| *Exchangerate Get*
a| Operation is now called *Get exchangerate*.

| *Invoice Get*
a| Operation is now called *Get invoice by invoice id*.

| *Item ID Get*
a| Operation is now called *Get item by item id*.

| *Journalentry Get*
a| Operation is now called *Get journalentry by journalentry id*.

| *Payment174Get*
a| Operation is now called *Get payment by payment id*.

| *Paymentmethod Get*
a| Operation is now called *Get paymentmethod by paymentmethod id*.

| *Preferences Get*
a| Operation is now called *Get preferences*.

| *Purchase Get*
a| Operation is now called *Get purchase by purchase id*.

| *Purchaseorder Get*
a| Operation is now called *Get purchaseorder by purchaseorder id*.

| *Refundreceipt Get*
a| Operation is now called *Get refundreceipt by refundreceipt id*.

| *Reports Account List Get*
a| Operation is now called *Get reports account list*.

| *Reports Aged Payable Detail Get*
a| Operation is now called *Get reports aged payable detail*.

| *Reports Aged Payables Get*
a| Operation is now called *Get reports aged payables*.

| *Reports Aged Receivable Detail Get*
a| Operation is now called *Get reports aged receivable detail*.

| *Reports Aged Receivables Get*
a| Operation is now called *Get reports aged receivables*.

| *Reports Balance Sheet Get*
a| Operation is now called *Get reports balance sheet*.

| *Reports Cash Flow Get*
a| Operation is now called *Get reports cash flow*.

| *Reports Class Sales Get*
a| Operation is now called *Get reports class sales*.

| *Reports Customer Balance Get*
a| Operation is now called *Get reports customer balance*.

| *Reports Customer Balance Detail Get*
a| Operation is now called *Get reports customer balance detail*.

| *Reports Customer Income Get*
a| Operation is now called *Get reports customer income*.

| *Reports Customer Sales Get*
a| Operation is now called *Get reports customer sales*.

| *Reports Department Sales Get*
a| Operation is now called *Get reports department sales*.

| *Reports General Ledger Get*
a| Operation is now called *Get reports general ledger*.

| *Reports Inventory Valuation Summary Get*
a| Operation is now called *Get reports inventory valuation summary*.

| *Reports Item Sales Get*
a| Operation is now called *Get reports item sales*.

| *Reports Profit And Loss Get*
a| Operation is now called *Get reports profit and loss*.

| *Reports Profit And Loss Detail Get*
a| Operation is now called *Get reports profit and loss detail*.

| *Reports Transaction List Get*
a| Operation is now called *Get reports transaction list*.

| *Reports Trial Balance Get*
a| Operation is now called *Get reports trial balance*.

| *Reports Vendor Balance Get*
a| Operation is now called *Get reports vendor balance*.

| *Reports Vendor Balance Detail Get*
a| Operation is now called *Get reports vendor balance detail*.

| *Reports Vendor Expenses Get*
a| Operation is now called *Get reports vendor expenses*.

| *Salesreceipt Get*
a| Operation is now called *Get salesreceipt by salesreceipt id*.

| *Taxagency Get*
a| Operation is now called *Get taxagency by taxagency id*.

| *Taxcode Get*
a| Operation is now called *Get taxcode by taxcode id*.

| *Taxrate Get*
a| Operation is now called *Get taxrate by taxrate id*.

| *Term Get*
a| Operation is now called *Get term by term id*.

| *Transfer Get*
a| Operation is now called *Get transfer by transfer id*.

| *Vendor Get*
a| Operation is now called *Get vendor by vendor id*.

| *Vendorcredit Get*
a| Operation is now called *Get vendorcredit by vendorcredit id*.

|===


[[new_sources]]
== New Sources

[%header%autowidth.spread]
|===
|<connector> Source | Description | Parameters

| On new customer
a| Triggers an event for every new customer. a|
* Configuration
* Created time
* Config Ref
* Primary Node Only
* Scheduling Strategy
* Streaming Strategy
* Redelivery Policy
* Reconnection Strategy

| On new invoice
a| Triggers an event for every new invoice. a|
* Configuration
* Created time
* Config Ref
* Primary Node Only
* Scheduling Strategy
* Streaming Strategy
* Redelivery Policy
* Reconnection Strategy

| On new item
a| Triggers an event for every new item. a|
* Configuration
* Created time
* Config Ref
* Primary Node Only
* Scheduling Strategy
* Streaming Strategy
* Redelivery Policy
* Reconnection Strategy

| On updated customer
a| Triggers an event for every updated customer. a|
* Configuration
* Last Updated Time
* Config Ref
* Primary Node Only
* Scheduling Strategy
* Streaming Strategy
* Redelivery Policy
* Reconnection Strategy

| On updated invoice
a| Triggers an event for every updated invoice. a|
* Configuration
* Last Updated Time
* Config Ref
* Primary Node Only
* Scheduling Strategy
* Streaming Strategy
* Redelivery Policy
* Reconnection Strategy

| On updated item
a| Triggers an event for every updated item. a|
* Configuration
* Last Updated Time
* Config Ref
* Primary Node Only
* Scheduling Strategy
* Streaming Strategy
* Redelivery Policy
* Reconnection Strategy

|===



== Upgrade Prerequisites

Before you perform the upgrade, you must:

. Create a backup of your files, data, and configuration in case you need to restore to the previous version.
. Install Quickbooks Connector v2.x to replace the Quickbooks operations that were previously included in Quickbooks Connector v1.x.

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In *Mule Palette*, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `quickbooks` in the search field.
. In *Available modules*, select *Quickbooks Connector - Mule 4* and click *Add*.
. Click *Finish*.
. Verify that the `quickbooks-connector` dependency version is `2.x.x` in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.


=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Troubleshooting

If there are problems with caching the parameters and caching the metadata, try restarting Studio.

=== Revert the Upgrade

If it is necessary to revert to the previous version of Quickbooks Connector, change the `quickbooks-connector` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
