= Sockets Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Sockets Connector v1.1

Anypoint Connector for Sockets (Sockets Connector) provides a sockets listener, send capability, and send and receive functionality. Provides TCP and UDP requesters.

Release Notes: xref:release-notes::connector/connector-sockets.adoc[Sockets Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/org.mule.connectors/mule-sockets-connector/[Sockets Connector]

== POM File Information

[source,xml,linenums]
----
<dependency>
  <groupId>org.mule.connectors</groupId>
  <artifactId>mule-sockets-connector</artifactId>
  <version>RELEASE</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

Mule converts RELEASE to the latest version. To specify a version, view 
Anypoint Exchange and click *Dependency Snippets*.

== Supported Protocols

Sockets Connector supports these TCP protocols:

* Custom Class Loading Length Protocol
* Custom Protocol
* Direct Protocol
* EOF Protocol
* Length Protocol
* Safe Protocol
* Streaming Protocol
* XML Message Eof Protocol
* XML Message Protocol

For more information, see the xref:sockets/sockets-documentation.adoc[Sockets Connector Reference].

== See Also

* xref:sockets/sockets-documentation.adoc[Sockets Connector Reference]
* xref:mule-runtime::tls-configuration.adoc[Configure TLS with Keystores and Truststores]
* https://help.mulesoft.com[MuleSoft Help Center]