= Sockets Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Sockets Connector v1.1

Anypoint Connector for Sockets (Sockets Connector) provides a sockets listener, send capability, and send and receive functionality. Provides TCP and UDP requesters.

Release Notes: xref:release-notes::connector/connector-sockets.adoc[Sockets Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/org.mule.connectors/mule-sockets-connector/[Sockets Connector]

== POM File Information

[source,xml,linenums]
----
<dependency>
  <groupId>org.mule.connectors</groupId>
  <artifactId>mule-sockets-connector</artifactId>
  <version>RELEASE</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

Mule converts RELEASE to the latest version. To specify a version, view 
Anypoint Exchange and click *Dependency Snippets*.

== Configure a Socket Listener

The Socket Listener represents a socket endpoint that clients can connect to. By browsing to this endpoint, external clients establish a TCP Socket connection, and trigger the flow each time they send a message.

You can configure a Socket Listener by referencing the configuration element from the listener's `config-ref`.

[source,xml,linenums]
----
	<sockets:listener-config name="SocketsListenerConfig">
		<sockets:tcp-listener-connection host="localhost" port="8082" />
	</sockets:listener-config>
----

This configuration will set up a Socket Listener to accept local incoming connections on port 8082.

== Supported Operations

Socket connector provides the user with two basic operations:

    * Send
    * Send and Receive

== Supported Protocols

Sockets Connector supports these TCP protocols:

* Direct Protocol
    The socket reads until no more bytes are (momentarily) available. On slow networks EOFProtocol and LengthProtocol may be more reliable.
* EOF Protocol
    Reading is terminated by the stream being closed by the client.
* Length Protocol
    This protocol is defined by sending / reading an integer (the packet length) and then the data to be transferred.
* Custom Class Loading Length Protocol
    A Length Protocol that uses a specific class loader to load objects from streams
* Safe Protocol
    This is a test protocol and should not used in productive environments. This protocol precedes every message with a cookie.
* Streaming Protocol
    This allows the socket's send operation to return a message with the original InputStream as payload.
* XML Message Protocol
    The XmlMessageProtocol is a protocol that can be used to read streaming xml documents. The only requirement
    is that each document include an xml declaration at the beginning of the document of the form "<?xml...". Please make sure
    that the xml documents being streamed begin with an xml declaration when using this protocol. Data are read until a new document
    is found or until there is no more data (momentarily). For slower networks, XmlMessageEOFProtocol may be more reliable. Also, the default
    character encoding for the platform is used to decode the message bytes when looking for the XML declaration. Some caution with
    message character encodings is warranted.
* XML Message Eof Protocol
    Extends XmlMessageProtocol to continue reading until either a new message or EOF is found.
* Custom Protocol
    Users can define their own protocol by writing a class that extends TcpProtocol, and that will be used as custom protocol.

These are application level protocols, meaning they are implemented on top of TCP. For these protocols to work properly, they need to be implemented in both ends (client and server).

By default, a Socket will implement the `Safe Protocol`, unless a different protocol is specified in the config element. The following example, demonstrates how to configure the socket to use Direct Protocol.

[source,xml,linenums]
----
	<sockets:listener-config name="Sockets_Listener_config" doc:name="Sockets Listener config" >
		<sockets:tcp-listener-connection host="localhost" port="8082" >
			<sockets:protocol>
				<sockets:direct-protocol />
			</sockets:protocol>
		</sockets:tcp-listener-connection>
	</sockets:listener-config>
----

For more information, see the xref:sockets/sockets-documentation.adoc[Sockets Connector Reference].

== See Also

* xref:sockets/sockets-documentation.adoc[Sockets Connector Reference]
* xref:mule-runtime::tls-configuration.adoc[Configure TLS with Keystores and Truststores]
* https://help.mulesoft.com[MuleSoft Help Center]