= SAML module validate security assertion - Mule 4

The mule SAML module can be use to validate a SAML assertion version 1.1 or 2.0

== Global configuration

Although it is optional you can create a global configuration for the validation operation.

Here is a simple configuration example with all its parameters configured:

[source,xml,linenums]
----
<saml:validation-config name="SAML_Validation_config" defaultAssertionValidity="1" defaultAssertionValidityTimeUnit="MINUTES" skewTime="1" skewTimeUnit="MINUTES">
    <saml:truststore path="/path/to/your/trueStore" password="yourPassword" />
</saml:validation-config>
----

== Operation configuration

=== Assertion

The assertion is the XML that contains the SAML assertion to be validated.

=== Element path

The element path is an XPath expression that indicates where the assertion in the given XML is located. This is the only
required parameter.

=== Version

The version indicates the version of the SAML standard used in the assertion. It can be either 1.1 or 2.0.

=== Required confirmation method

The required confirmation method is a list of the confirmation method that must be present in the assertion to be
validated.

=== Require signature

This indicates if the assertion must be signed to be validated.

=== Verify expiration

This indicates in the expiration date must be verified in the validation.

== See Also

* xref:generate-saml-20-assertion-example.adoc[Generate assertion example]