= Microsoft Excel Online Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Microsoft Excel Online (Excel Online Connector) gives you access to the Excel platform. This connector exposes the most commonly used operations provided by the Microsoft Excel Online API.

For compatibility information and fixed issues, see the Microsoft Excel Online Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Microsoft Excel Online API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the Excel target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Some possible uses for this connector include:

* Sales

** Organize your company's sales in a spreadsheet to perform cost studies, inventory management, or production scheduling.
** Create a chart of your company's inventory and analyze that data to encourage your customers to buy certain items.

* Data

** Visualize and share data regarding your customers, subscriptions, orders, charges, refunds, and events.


== Authentication Type

Microsoft Excel Online Connector uses the OAuth 2.0 authentication type, which delegates user authentication to the service hosting the user account.

== Next Step

After you complete the prerequisites, you are ready to create your own app and configure the connector using xref:microsoft-excel-online-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
