= Microsoft OneDrive Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Microsoft OneDrive (OneDrive Connector)... 

For compatibility information and fixed issues, see the Microsoft OneDrive Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Microsoft OneDrive APIs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Common use cases for OneDrive Connector include:




== Authentication Types

OneDrive Connector uses the following authentication methods:

* OAuth 2.0 authorization code grant connection type, which is used in apps that are installed on a device to gain access to protected resources.
* OAuth 2.0 client credentials grant, which uses the identity of the application to access web-hosted resources.


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:microsoft-onedrive-connector-reference.adoc[Microsoft OneDrive Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
