= Upgrading and Migrating FTPS Connector to Version 2.0  - Mule 4

Upgrade Anypoint Connector for FTPS (FTPS Connector) to version 2.x.

== Supported Upgrade Paths

// Is this a direct upgrade (from previous version to latest version) or
// a “multi-version-hop” upgrade? What is the supported path?

[%header,cols="50a,50a"]
|===
|From Version | To Version
|1.8.x |2.0.x
|===

== Changes in This Release

This release contains the following changes:

* The FTPS connector is now compatible with `Java 17`.
* The FTPS connector is now `FIPS 140-2 compliant`.
* The FTPS connector no longer uses Reflection to reuse SSL Session from the command channel to data channels. Now, it uses `Bouncy Castle` libraries provided externally by the client to achieve SSL Session resumption between client and host.
* Based on the requirement, users can provide the following additional properties:
** jdk.tls.client.protocols
** org.bouncycastle.jsse.client.assumeOriginalHostName
* The `mule-file-commons` module dependency is removed.
* The *List* operation now returns the file path instead of the file content.
// List all changes that affect users, including changed schemas,
// changed data structures, changed POM files, changed and new fields
// (locations, names, etc) and parameters, deprecated parameters, etc

// Examples:
//
// * The create operation name changed from old-name to new-name.
// * The field-name>is now located in the tab-name tab.
// * What happens with the upgrade? Are changes made to app data?
// * The single global configuration is divided into operation and source-specific global configurations like:
// ** send-config - used by send-with-sync-mdn and send-with-async-mdn operations.
// ** listener-config - used by as2-listener source.
// ** mdn-listener-config - used by as2-mdn-listener source.
// * Changed namespace from <old-namespace> to <new-namespace>.

// If applicable, use tables to describe new and changed operations and sources. Examples follow:

////
[[new_operations]]
== New Operations

[%header%autowidth.spread]
|===
|Operation | Description | Parameters
| <operation-name>, for example: *Commit*
a| Enter a description for the operation, for example: Commits the offsets associated to a message or batch of messages consumed in a message listener. a| Specify the operation parameters, for example: Consumer commit key. The consumer commit key to use to commit the message.
|===


[[changed_operations]]
== Changed Operations

[%header%autowidth.spread]
|===
|Operation | Description | Parameters

| <operation-name>, for example: *Commit*
a| Enter a description for the operation, for example: Commits the offsets associated to a message or batch of messages consumed in a message listener. a| Specify the operation parameters. Example: Consumer commit key. The consumer commit key to use to commit the message.
|===


[[new_sources]]
== New Sources

[%header%autowidth.spread]
|===
|Source | Description | Parameters

| <source-name>, for example: *Batch message listener*
a| Enter a description for the source, for example: The message list that was obtained in the poll is handled by a flow as a single event, so the handling of concurrency is simpler than in the simple message listener. a| Enter the parameters. Example: * Poll timeout
* Poll timeout time unit
* Acknowledgment mode
* Number of parallel consumers
|===

[[changed_sources]]
== Changed Sources

[%header%autowidth.spread]
|===
|Source | Earlier version | Parameters

| <name-in-new-version>, for example: *Message listener* | <name-in-oldMessage consumer a| * Poll timeout
* Poll timeout time unit
* Acknowledgment mode
* Number of parallel consumers
|===
////


== Requirements

Ensure that you meet these requirements before you perform the upgrade:

// * Any particular database, OS version, etc?
// * Any software requirements?
// * Minimum hardware requirements (CPU, memory, disk space, etc)?
// * Licensing requirements?
[%header,cols="50a,50a"]
|===
|Application/Service| Version
|Mule |4.3.0 and later
|===


== Limitations

Before you perform the upgrade, be aware of these known limitations:

* Session reuse does not work well with TLS 1.3 in CloudHub (same as with previous versions of FTPS connector).
* The security providers are set in a way that affects the entire environment. This means that all Mule applications running on the same Java Virtual Machine (JVM) will share these security settings.

// (Examples)
// * There is no rollback mechanism
// * A protocol will be broken
// * Migration of _____ is not supported

== Upgrade Prerequisites

Before you perform the upgrade, create a backup of your files, data, and configurations in case you need to restore them.
// * Do they need to rename or copy over any files before downloading the latest version?

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In *Mule Palette*, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `FTPS` in the search field.
. In *Available modules*, select *FTPS Connector* and click *Add*.
. Click *Finish*.
. Verify that the FTPS Connector `mule-ftps-connector` dependency version is the one you are upgrading to in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

== Post-Upgrade Steps

After you install the latest version of the connector, follow these steps to complete the upgrade:

// * Do they need to update endpoints?
// * Do they need to re-create/refactor any customizations?
// * Does the user need to map any files?
// * Verify the upgrade.

=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

=== Reverting the Upgrade
If it is necessary to revert to the previous version of FTPS Connector, change the `mule-ftps-connector` dependency version in the project's `pom.xml` file to the previous version.
You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
