= FTPS Connector - Mule 4
:page-aliases: connectors::ftp/ftps-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Premium]

Anypoint Connector for FTPS (FTPS Connector) connects to FTP servers the same way as the xref:ftp-connector::index.adoc[FTP Connector] but adds support for xref:mule-runtime::tls-configuration.adoc[Transport Layer Security (TLS)].

== Before You Begin

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have access to Anypoint Platform and Anypoint Studio.

== Breaking changes with version 1.x.y
* Changed way how to enable SSL Session resumption, for more information how to set up the feature see xref:ftps-studio-configuration.adoc[FTPS Studio Configuration] section.


== See Also

* xref:ftps-documentation.adoc[FTPS Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
