= Microsoft Outlook 365 Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Microsoft Outlook 365 (Outlook 365 Connector) enables you to access ...

For compatibility information and fixed issues, refer to the Microsoft Outlook 365 Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* Microsoft Outlook 365 API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Outlook 365 Connector provides email and calendar capabilities.

== Authentication Types

Outlook 365 Connector uses the following authentication methods:

* OAuth 2.0 authorization code grant connection type, which is used in applications that are installed on a device to gain access to protected resources.
* OAuth 2.0 client credentials grant, which uses the identity of the application to access web-hosted resources.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:microsoft-outlook-365-connector-reference.adoc[Microsoft Outlook 365 Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
