= Troubleshooting Microsoft Dynamics 365 Connector 2.6 - Mule 4

To troubleshoot Anypoint Connector for Microsoft Dynamics 365 (Microsoft Dynamics 365 Connector), become familiar with the information about interpreting commonly thrown exception messages.


include::connectors::partial$verbose-exception-logs.adoc[]

include::connectors::partial$verbose-logs-org.adoc[]

== Understand Commonly Thrown Exceptions

Here is a list of commonly thrown exception messages and how to interpret them:

* DYNAMICS:CONNECTIVITY

 Either a connection could not be established or there is a connectivity error.

* DYNAMICS:INVALID_PAGE_SIZE

 The page size is invalid, for example, if the fetch size value exceeds 5000.

* DYNAMICS:NOT_FOUND

 The server could not find the requested resource.

* DYNAMICS:OPERATION_FAILED

 The operation fails, for example, if the protocol or entity attributes are invalid or if invocation fails.

* DYNAMICS:PARSE_ERROR

 There is an error when parsing a JSON entity, for example, the entity ID is invalid or the encoding for the provided JSON is invalid.

* DYNAMICS:RETRY_EXHAUSTED

 The consumer is not subscribed to any topics, and no manually assigned partitions are set to consume from.

* DYNAMICS:TIMEOUT

 A specific request takes longer than the configuration timeout values.

* DYNAMICS:UNAUTHORIZED

 There is an unauthorized request.

* DYNAMICS:UNKNOWN

 There is an unknown or an unexpected error.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:microsoft-dynamics-365-connector-reference.adoc[Microsoft Dynamics 365 Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
* https://issues.salesforce.com/[Known Issues]
