= Microsoft .NET Connector - Mule 4
:page-aliases: connectors::microsoft/microsoft-dotnet-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Microsoft .NET Connector v3.0

Anypoint Connector for Microsoft .NET enables you to execute native .NET code in a Mule application.

Supported scenarios include: executing code in an existing binary assembly (DLL) without modification, or new development of .NET code that extends the capability of your integration application.

This connector executes .NET code using the Java Native Interface (JNI), which provides fast interprocess communication between the Java Virtual Machine (JVM) and a native application running in a host operating system.

The connector supports one operation, the Execute operation, which allows users to select a class and a method to execute, and to pass the corresponding arguments for that method.

NOTE: This connector is compatible only with Java 8.

Release Notes: xref:release-notes::connector/microsoft-dotnet-connector-release-notes-mule-4.adoc[Microsoft .NET Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-microsoft-dotnet-connector/[Microsoft .NET Connector]

== Prerequisites

To use this information, you should be familiar with .NET, Mule runtime engine (Mule), Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and Global Elements.

For software requirements and compatibility information, see the Connector Release Notes.

To use this connector with Maven, view the pom.xml dependency information in the Dependency Snippets in Anypoint Exchange.

NOTE: This connector is not supported for use with Anypoint Design Center.

== Connect in Anypoint Studio 7

You can use this connector in Anypoint Studio by first downloading it from Exchange and configuring it as needed.

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
