= Microsoft Dynamics 365 - Design Center Configuration - Mule 4

Anypoint Design Center's Flow Designer enables you to create apps visually. For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour].

To create an app in Flow Designer:

* Configure the input source (trigger) for your app.
* Add the connector as a component to process the input for the app.

For information about Flow Designer field values, see
the xref:microsoft-dynamics-365-connector-reference.adoc[Microsoft Dynamics 365 Connector Reference].

== Configure the Input Source Trigger

Create an app in Flow Designer based on what input source you want for the app. Anypoint Connector for Microsoft Dynamics 365 (Microsoft Dynamics 365 Connector) enables
you to have your app receive input when objects are created or modified. Alternatively, you can set up an input source using HTTP, or at timed intervals using Scheduler.

. In Design Center, click *Create*.
. Click *Create new application* to open Flow Designer.
. Specify a value for *Project name* and click *Create*.
. Click *Go straight to canvas* to exit from *Let's get started*.
. Click the trigger card.
. Select *Microsoft Dynamics 365 Connector* and select your input source as either *On New Object* or *On Modified Object*.
See xref:index.adoc#trigger-required-fields[Trigger Required Fields].
. Click the *Test* button to test the connection.

Design Center automatically saves all changes.

== Configure the Target Component

. Click *+* next to the trigger card.
. In *Select a component*, search for Microsoft Dynamics 365 Connector.
. Select the connector name.
. Select an operation for the connector.
. Complete the required fields for the operation.
. Click the *Test* button to test the connection.

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
