= MCP Connector 0.1.0 - Examples - Mule 4

These are some examples of how to use existing APIs to build agents using MCP Connector. 

== Create an MCP Server and Tools

In this example, you will create an MCP server and two specific tools: 

* One tool provides the agent with a live list of approved vendors categorized by product for the agent to choose from. 
* The other tool enables the agent to initiate the purchase order creation process with the necessary details. 

In these examples, MCP tools are Remote Procedure Calls (RPC) that take a list of input arguments and produce a result.

=== Create the MCP Server Configuration

This configuration implements an MCP server using the SSE transport on top of an existing `<http:listener-config>`. This configuration provides all the configuration options of the HTTP Connector. You can also write apps that serve both MCP and traditional APIs on the same port.

[source,xml,linenums, subs=attributes+]
----
<http:listener-config name="HTTP_Listener_config">
	<http:listener-connection host="0.0.0.0" port="${https.port}" />
</http:listener-config>
	
<mcp:server-config name="MCP_Server"serverName="Mule MCP Server" serverVersion="1.0.0">
		<mcp:sse-server-connection listenerConfig="HTTP_Listener_config" sseEndpointPath="/sse" messagesPath="/message" />
</mcp:server-config>
----

=== Write a Tool That Provides a List of Vendors

Write a tool that provides a list of vendors. 

In this example, each vendor is assigned a product category that's mapped to a custom field called `Custom19`:

[source,xml,linenums, subs=attributes+]
----
<flow name="vendorsTool" >
 <mcp:tool-listener config-ref="MCP_Server" name="get-vendors"> #(1)
	<mcp:description>Get all approved vendors</mcp:description> #(2)
	<mcp:parameters-schema ><![CDATA[{ #(3)
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {},
  "required": []
}]]></mcp:parameters-schema>
<mcp:responses> #(4)
	<mcp:text-tool-response-content text="#[payload.^raw]" />
	</mcp:responses>
  </mcp:tool-listener>

  <flow-ref name="getTokenFlow" target="token"/>
  <mule-sap-concur-connector:get-vendors config-ref="SAP_Concur_Config"/>
  <ee:transform>
	<ee:message >
<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload.Vendor filter ($.Approved == "true") map {
	id: $.ID,
	name: $.VendorName,
	country: $.Country,
	city: $.City,
	productCategories: $.Custom19		
}
]]></ee:set-payload>
	</ee:message>
   </ee:transform>
</flow>
----

[calloutlist]
.. The tool is implemented through a flow triggered through the <mcp:tool-listener>.
.. The tool includes a description that allows the LLM to determine when to use it.
.. This is a simple tool that doesn’t take any input arguments, but according to MCP standards, it requires a JSON schema to define that.
.. The tool produces a text response, which in this case is the JSON produced by the flow. The connector also supports other types of responses like images and binary objects.

This implementation uses the off-the-shelf SAP Concur Connector to get the vendors and a DataWeave (DW) transformation to filter by approved status and map the custom field to a `productCategories` field.

This is enough for the LLM to access the live data in Concur and select an appropriate vendor based on city, product category, and other criteria, without needing additional custom logic.

=== Write a Tool That Creates the Purchase Order

The tool in this example takes input arguments (each including a natural language description) defined in the JSON schema. This allows the LLM to map and consume the values. 

[source,xml,linenums, subs=attributes+]
----
<flow name="purchaseOrderTool">
  <mcp:tool-listener config-ref="MCP_Server" name="create-concur-purchase-order">
<mcp:description></mcp:description>
	<mcp:parameters-schema ><![CDATA[{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
  	"name": {
      "type": "string",
      "description": "Name for the purchase order."
    },
     "description": {
		"type": "string",
      	"description": "Purchase order description."
     },
     "vendorCode": {
     	"type": "string",
      	"description": "Code that identifies the vendor."
     },
     "itemDescription": {
     	"type": "string",
      	"description": "Description of the item purchased in this order."
     },
     "price": {
     	"type": "number",
     	"description": "Monetary amount of the purchase order."     
	 },
	 "currency": {
	 	"type": "string",
	 	"description": "Currency code for the purchase order monetary amount."
    }
  },
  "required": ["name", "description", "vendorCode", "itemDescription", "price", "currency"]
}]]></mcp:parameters-schema>
  <mcp:responses >
<mcp:text-tool-response-content text="#['Created Order $(payload.PurchaseOrderNumber)']" />
  </mcp:responses>
</mcp:tool-listener>
		
<flow-ref name="getTokenFlow" target="token"/>
<mule-sap-concur-connector:create-purchase-order config-ref="SAP_Concur_Config">
	<mule-sap-concur-connector:create-purchase-order-request-data ><![CDATA[#[output application/json
---
{
	Name: payload.name,
	CurrencyCode: payload.currency,
	Description: payload.description,
	VendorCode: payload.vendorCode,
	LineItem: {
		Description: payload.itemDescription,
		ApprovedLineItemAmount: payload.price as String,
		TotalPrice: payload.price as String
	}
}]]]></mule-sap-concur-connector:create-purchase-order-request-data>
		</mule-sap-concur-connector:create-purchase-order>
	</flow>
----

The flow then uses the connector to create the order and returns a single text line, including the order’s ID. There’s no need for a formatted response.

== Configure the MCP Client to Use Third-Party MCP Servers

The previous examples showed you how to write a tool that draws from existing Anypoint Connctors.

By configuring the MCP Client, you can use third-party MCP servers that are already implemented and ready to use. These examples show you how you can integrate your Mule applications with existing third-party MCP servers by configuring the MCP Client and using the *Call Tool* operation.

Here is an example of configuring the MCP Client with the Google Maps MCP server deployed to Heroku: 

[source,xml]
----
<mcp:client-config name="MCP_Client" clientName="Mule MCP Connector" clientVersion="1.0.0">
		<mcp:sse-client-connection serverUrl="http://google-maps-mcp-sse-f5ebe64f8456.herokuapp.com">
		</mcp:sse-client-connection>
</mcp:client-config>
----

After the MCP Client configuration is defined, you can use the *Call tool* (`mcp-call-tool`) operation to invoke specific tools exposed by the MCP server. The *Call Tool* operation dynamically retrieves the metadata (including available tools and their arguments) from the target MCP server, providing DataSense auto-completion within your Mule flow.

This example demonstrates how to create an MCP tool that retrieves weather information using the external OpenMeteo API (not an MCP server directly). This illustrates how you can integrate standard HTTP-based services within an MCP tool:

[source,xml]
----
<http:request-config basePath="/v1" name="HTTP_Request_configuration">
        <http:request-connection host="api.open-meteo.com" protocol="HTTPS"></http:request-connection>
    </http:request-config>

<flow name="getWeatherByCoordinatesToolFlow">
        <mcp:tool-listener config-ref="MCP_Server" name="get-weather-by-coordinates">
            <mcp:description>Provides the weather at a given coordinates expressed as latitude and longitude]></mcp:description>
            <mcp:parameters-schema><![CDATA[{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "latitude": {
      "type": "number",
      "description": "The latitude component of a location's coordinates"
    },
    "longitude": {
      "type": "number",
      "description": "The longitude component of a location's coordinates"
    }
  },
  "required": ["latitude", "longitude"]
}]]></mcp:parameters-schema>
            <mcp:responses>
				<mcp:text-tool-response-content text="#['Current temperature at location is $(payload.current.temperature_2m)']" />
            </mcp:responses>
        </mcp:tool-listener>
		<http:request config-ref="HTTP_Request_configuration" method="GET" path="/forecast">
            <http:query-params><![CDATA[#[output application/java
				---
				{
					latitude : payload.latitude,
					longitude : payload.longitude,
					current: 'temperature_2m'
				}]]]></http:query-params>
        </http:request>
    </flow>
----

This tool uses the OpenMeteo API to return the forecast at a particular coordinate. 

To handle weather lookups by address instead of coordinates, you can compose a new MCP tool that leverages the Google Maps MCP Server (configured earlier) to get coordinates and then uses the `get-weather-by-coordinates` tool (which internally calls the OpenMeteo API):

[source,xml]
----
<flow name="getWeatherByAddressToolFlow">
  <mcp:tool-listener doc:name="Call Tool Listener" config-ref="MCP_Server" name="get-weather-by-address">
   <mcp:description>Provides the weather at a specific address</mcp:description>
  <mcp:parameters-schema ><![CDATA[{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "address": {
      "type": "string",
      "description": "The address we want to learn the weather for"
    }
  },
  "required": ["address"]
}]]></mcp:parameters-schema>
    <mcp:responses >
    <mcp:text-tool-response-content text="#[payload.contents[0].text]" />
</mcp:responses>
 </mcp:tool-listener>
 <mcp:call-tool config-ref="MCP_GMaps_Client" toolName="maps_geocode">
	<mcp:arguments ><![CDATA[#[output application/java
---
{
	address: payload.address
}]]]>
</mcp:arguments>
 </mcp:call-tool>
 <mcp:call-tool config-ref="MCP_Client" toolName="get-weather-by-coordinates">
    <mcp:arguments ><![CDATA[#[output application/java
---
{
	latitude: read(payload.contents[0].text!, 'json').location.lat as Number,
	longitude: read(payload.contents[0].text!, 'json').location.lng as Number
}]]]>
</mcp:arguments>
 </mcp:call-tool>
</flow>
----

== See Also

* xref:mcp-connector-config-topics.adoc[Applying Security to the MCP Server]
* xref:mcp-connector-reference.adoc[MCP Connector Reference]
* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
