= MCP Connector 0.1.0 - Examples - Mule 4

These are some examples of how to use existing APIs to build agents using MCP Connector. 

== Create an MCP Server and Tools

Create an MCP server and two specific tools: one to provide the agent with a live list of approved vendors categorized by product for the agent to choose from. The other tool enables the agent to initiate the purchase order creation process with the necessary details. 

This implementation lets you give the agent with a live list of vendors and their assigned categories. It also keeps the LLM decoupled from Concur and all its details like authentication, custom field setup, and so on.

In this example, MCP tools are Remote Procedure Calls (RPC) that take a list of input arguments and produce a result.

=== Create the MCP Server Configuration

This configuration implements an MCP server using the SSE transport on top of an existing `<http:listener-config>`. This configuration provides all the configuration options of the HTTP Connector. You can also write apps that serve both MCP and traditional APIs on the same port.

[source,xml,linenums, subs=attributes+]
----
<http:listener-config name="HTTP_Listener_config">
	<http:listener-connection host="0.0.0.0" port="${https.port}" />
</http:listener-config>
	
<mcp:server-config name="MCP_Server"serverName="Mule MCP Server" serverVersion="1.0.0">
		<mcp:sse-server-connection listenerConfig="HTTP_Listener_config" sseEndpointPath="/sse" messagesPath="/message" />
</mcp:server-config>
----

=== Write a Tool That Provides a List of Vendors

Write a tool that provides a list of vendors. 

In this example, each vendor is assigned a product category that's mapped to a custom field called `Custom19`:

[source,xml,linenums, subs=attributes+]
----
<flow name="vendorsTool" >
 <mcp:tool-listener config-ref="MCP_Server" name="get-vendors"> #(1)
	<mcp:description>Get all approved vendors</mcp:description> #(2)
	<mcp:parameters-schema ><![CDATA[{ #(3)
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {},
  "required": []
}]]></mcp:parameters-schema>
<mcp:responses> #(4)
	<mcp:text-tool-response-content text="#[payload.^raw]" />
	</mcp:responses>
  </mcp:tool-listener>

  <flow-ref name="getTokenFlow" target="token"/>
  <mule-sap-concur-connector:get-vendors config-ref="SAP_Concur_Config"/>
  <ee:transform>
	<ee:message >
<ee:set-payload ><![CDATA[%dw 2.0
output application/json
---
payload.Vendor filter ($.Approved == "true") map {
	id: $.ID,
	name: $.VendorName,
	country: $.Country,
	city: $.City,
	productCategories: $.Custom19		
}
]]></ee:set-payload>
	</ee:message>
   </ee:transform>
</flow>
----

[calloutlist]
.. The tool is implemented through a flow triggered through the <mcp:tool-listener>.
.. The tool includes a description that allows the LLM to determine when to use it.
.. This is a simple tool that doesn’t take any input arguments, but according to MCP standards, it requires a JSON schema to define that.
.. The tool produces a text response, which in this case is the JSON produced by the flow. The connector also supports other types of responses like images and binary objects.

This implementation uses the off-the-shelf SAP Concur Connector to get the vendors and a DataWeave (DW) transformation to filter by approved status and map the custom field to a `productCategories` field.

This is enough for the LLM to access the live data in Concur and select an appropriate vendor based on city, product category, and other criteria, without needing additional custom logic.

=== Write a Tool That Creates the Purchase Order

The tool in this example takes input arguments (each including a natural language description) defined in the JSON schema. This allows the LLM to map and consume the values. 

[source,xml,linenums, subs=attributes+]
----
<flow name="purchaseOrderTool">
  <mcp:tool-listener config-ref="MCP_Server" name="create-concur-purchase-order">
<mcp:description></mcp:description>
	<mcp:parameters-schema ><![CDATA[{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
  	"name": {
      "type": "string",
      "description": "Name for the purchase order."
    },
     "description": {
		"type": "string",
      	"description": "Purchase order description."
     },
     "vendorCode": {
     	"type": "string",
      	"description": "Code that identifies the vendor."
     },
     "itemDescription": {
     	"type": "string",
      	"description": "Description of the item purchased in this order."
     },
     "price": {
     	"type": "number",
     	"description": "Monetary amount of the purchase order."     
	 },
	 "currency": {
	 	"type": "string",
	 	"description": "Currency code for the purchase order monetary amount."
    }
  },
  "required": ["name", "description", "vendorCode", "itemDescription", "price", "currency"]
}]]></mcp:parameters-schema>
  <mcp:responses >
<mcp:text-tool-response-content text="#['Created Order $(payload.PurchaseOrderNumber)']" />
  </mcp:responses>
</mcp:tool-listener>
		
<flow-ref name="getTokenFlow" target="token"/>
<mule-sap-concur-connector:create-purchase-order config-ref="SAP_Concur_Config">
	<mule-sap-concur-connector:create-purchase-order-request-data ><![CDATA[#[output application/json
---
{
	Name: payload.name,
	CurrencyCode: payload.currency,
	Description: payload.description,
	VendorCode: payload.vendorCode,
	LineItem: {
		Description: payload.itemDescription,
		ApprovedLineItemAmount: payload.price as String,
		TotalPrice: payload.price as String
	}
}]]]></mule-sap-concur-connector:create-purchase-order-request-data>
		</mule-sap-concur-connector:create-purchase-order>
	</flow>
----

The flow then uses the connector to create the order and returns a single text line, including the order’s ID. There’s no need for a formatted response.

== Use Third-Party MCP Servers

There is a growing list of MCP servers that are already implemented and ready to use by configuring the MCP client. For example:

[source,xml]
----
<mcp:client-config name="MCP_Client" clientName="Mule MCP Connector" clientVersion="1.0.0">
		<mcp:sse-client-connection serverUrl="http://google-maps-mcp-sse-f5ebe64f8456.herokuapp.com">
		</mcp:sse-client-connection>
</mcp:client-config>
----

In this example, the Google Maps MCP server is deployed in Heroku. 

You can then create an MCP Client configuration to consume it by using the *Call Tool* operation. The *Call Tool* operation automatically fetches all the metadata from the MCP server and shows the existing tools, while also providing DataSense auto-completion on the arguments.


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
