= Jira Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Jira (Jira Connector) gives you access to the Jira APIs. This connector exposes the most commonly used operations provided by the Jira APIs. 

For compatibility information and fixed issues, see the Jira Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Jira APIs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector




== Authentication Types

Jira Connector connections use the following authentication methods:



== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:jira-connector-reference.adoc[Jira Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
