= Jira Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Jira (Jira Connector) synchronizes data and automates business processes between Jira and third-party applications, either on-premises or in the cloud.

Jira is a software development platform to help agile product development teams triage and track their work from inception to launch. Jira Connector enables organizations of all sizes to establish scalable and sustainable product development workflows by connecting Jira to other tools in the organization such as the customer service platforms, project management tools, and others.

For compatibility information and fixed issues, see the Jira Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Jira APIs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the target Jira resource
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Automate business processes by integrating Jira with other IT tools and systems in your enterprise such as messaging, CRM, messaging, and others. 

Possible use cases include:

* Enhance customer experience by connecting Jira with your customer service platform, thereby reducing the cycle times between when a customer raises an issue through a customer service platform, like Salesforce’s Sales Cloud, and when that issue gets added to the product team’s work backlog in Jira. 
* Streamline crossteam handoffs by ensuring that the updated information on every issue is available across all systems and stakeholders. For example, when the engineering team marks a customer issue as resolved, update the status across your CRM and customer support platforms, so the customer-facing teams (sales and support) are notified immediately.
* Foster team collaboration and improve productivity by automating the flow of information between Jira and your team’s communication platform, so that when a new issue gets added to the backlog or an issue gets updated, relevant team members are notified so the appropriate next steps can be taken. 


== Authentication Types

Jira Connector connections use the following authentication methods:

* Basic authentication +
Uses a username and password for authentication
* OAuth2 +
Delegates user authentication to the service hosting the user account


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:jira-connector-reference.adoc[Jira Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
