= Cassandra Connector Data Types Reference

The Cassandra connector supports the following CQL primitive data types only:

[frame=none]
|===
| ascii | counter | float | text | tinyint
| bigint | date | inet | time | uuid
| blob | decimal | int | timestamp | varchar
| boolean | double | smallint | timeuuid | varint
|===

The following operations require you to specify the column type, or new column type in the case of Change Column Type, and accept only primitive data types:

* Create Table
* Change column type
* Add new column

== Unsupported Data Types

The Cassandra connector does not support the following CQL data types:

* list
* map
* set
* tuple

To create a table with columns of unsupported CQL types, or to add a new column of a complex type to an existing table, use the Execute CQL operation.

== Data Type Mapping

The connector maps the primitive data types using uppercase. You need to specify data types in one of the following ways:

* Use uppercase for names of data types
* Use a transformer to map the type to uppercase:

----
{
 "columns": payload.columns map {
  name: $.name,
  primaryKey: $.primaryKey,
  type: upper $.type
 }
----

== See Also

http://docs.datastax.com/en/cql/3.1/cql/cql_reference/cql_data_types_c.html[CQL data types]
