= Zuora Connector - Get Started
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/
Support Category: Select
Zuora Connector v1.0
<What this connector does>

== Prerequisites

This document assumes that you are familiar with Zuora, Mule, Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and Global Elements.

You need login credentials to test your connection to your target resource.

For hardware and software requirements and compatibility information, see the Connector Release Notes.

To use this connector with Maven, view the pom.xml dependency information in the Dependency Snippets in Anypoint Exchange.

This document set consists of the following documents:

* xref:zuora/zuora-connector-design-center.adoc[Zuora - Design Center]
* xref:zuora/zuora-connector-studio.adoc[Zuora - Studio]
* xref:zuora/zuora-connector-config-topics.adoc[Zuora - Configuration Topics]
* xref:zuora/zuora-connector-use-cases.adoc[Zuora - Use Cases]

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
