= Zuora - Upgrade and Migrate - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Upgrade Anypoint Connector for Zuora (Zuora Connector) to version 5.0.0.  

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|4.2.x |5.0.0
|===

== Changes in This Release

    See the changes below for more details

== Changes in Operations Parameters

[cols="5%,17%,15%,15%,17%,15%,15%"]
|===
4+|Existing in Zuora 4.x 3+| Modified in Zuora 5.x
|Nr |Operation Name	| Input Params	|Output Params	| Operation Name	                         |Input Params	                                    |Output Params

|1| Get Account Crud
|
Fields (String)

Id (String)

| N/A
| CRUD: Get account
|
id (String) (Modified)

fields (String) (Modified)

| Attributes Type (HttpResponseAttributes) (New)

|2| Get Payment Crud
| Id (String)
| N/A
| CRUD: Get payment
| id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|3| Get Payment Method Crud
|
Fields (String)

Id (String)

| N/A
| CRUD: Get payment method
|
id (String) (Modified)

fields (String)

| Attributes Type (HttpResponseAttributes) (New)

|4| Get Payment Method Snapshot Crud
|
Fields (String)

Id (String)

| N/A
| CRUD: Get payment method snapshot
|
id (String) (Modified)

fields (String) (Modified)

| Attributes Type (HttpResponseAttributes) (New)

|5| Get Payment Transaction Log Crud
| Id (String)
| N/A
| CRUD: Get payment transaction log
| id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|6| Get Refund Crud
|
Fields (String)

Id (String)

| N/A
| CRUD: Get refund
|
id (String) (Modified)

fields (String) (Modified)

| Attributes Type (HttpResponseAttributes) (New)

|7| Get A Notification Definition
| Id (String)
| N/A
| Get a notification definition
| id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|8| Get Account
| Account Key (String)
| N/A
| Get account
| Account key (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|9| Get Account Summary
| Account Key (String)
| N/A
| Get account summary
| Account key (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|10| Get Accounting Period
| Account Id (String)
| N/A
| Get accounting period
| Ap id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

| 11	|
Create Account|
Create Accounting Request Data(Any) |N/A|Create account|

Create Accounting Request Data (Any) (Removed);

Content(Binary); | Type (HttpResponseAttributes) (New)

|12	|
Create accounting period|
Create Accounting Period Request Data (Any)
|N/A
|No changes
|
Create Accounting Period Request Data (Any) (Removed);

Content(Binary); | Type (HttpResponseAttributes) (New)


| 13	|Create Account Crud|
Create Account Crud Request Data (Any)
|N/A
|CRUD: Create account|
Create Accounting Period Request Data (Any) (Removed);

Content(Binary); | Type (HttpResponseAttributes) (New)


| 14	|Create Accounting Code|
Create Accounting Code Request Data (Any)
|N/A| No changes
|
Create Accounting Code Request Data (Any) (Removed);

Content(Binary); | Type (HttpResponseAttributes) (New)


|15| Create An Email Template	|
Create An Email Template Request Data (Any)
|	N/A	|
No changes	|
Create An Email Template Request Data (Any) (Removed);

Content(Binary); | Type (HttpResponseAttributes) (New)

|16| Update Credit Balance Adjustment Crud
|
Update Credit Balance Adjustment Crud Request Data (Any);

Id (String)
| N/A
| CRUD: Update CreditBalanceAdjustment
|
Update Credit Balance Adjustment Crud Request Data (Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)


|17| Update Invoice Adjustment Crud
|
Update Invoice Adjustment Crud Request Data (Any)

Id (String)
| N/A
| CRUD:	Update InvoiceAdjustment
|
Update Invoice Adjustment Crud Request Data (Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|18| Update Invoice Payment Crud
|
Update Invoice Payment Crud Request Data (Any);

Id (String)
| N/A
| CRUD:	Update InvoicePayment
|
Update Invoice Payment Crud Request Data (Any);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|19| Update Product Crud
|
Update Product Crud Request Data (Any);

Id (String)
| N/A
| CRUD:	Update Product
|
Update Product Crud Request Data (Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|20| Update Product Rate Plan Crud
|
Update Product Rate Plan Crud Request Data (Any);

Id (String)
| N/A
| CRUD:	Update ProductRatePlan
|
Update Product Rate Plan Crud Request Data (Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|21| Update Product Rate Plan Charge Crud
|
Update Product Rate Plan Charge Crud Request Data (Any);

Id (String)
| N/A
| CRUD:	Update ProductRatePlanChargeTier
|
Update Product Rate Plan Crud Request Data (Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|22| Update Subscription Crud
|
Update Subscription Crud Request Data (Any);

Id (String)
| N/A
| CRUD: Update Subscription
|
Update Subscription Crud Request Data (Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|23| Update Taxation Item Crud
|
Update Taxation Item Crud Request Data (Any);

Id (String)
| N/A
| CRUD:	CRUD: Update Taxation Item
|
Update Taxation Item Crud Request Data (Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|24| Update Subscription Crud
|
Update Subscription Crud Request Data (Any);

Id (String)
| N/A
| CRUD: Update Subscription
|
Update Subscription Crud Request Data (Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|25| Update Account Crud
|
Update Account Crud Request Data (Any);

Id (String)
| N/A
| CRUD: Update Account
|
Update Account Crud Request Data(Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|26| Update Unit Of Measure Crud
|
Update Unit Of Measure Crud Request Data (Any);

Id (String)
| N/A
| CRUD: Update UnitOfMeasure
|
Update Unit Of Measure Crud Request Data(Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|27| Update Amendment Crud
|
Update Amendment Crud Request Data (Any);

Id (String)
| N/A
| CRUD: Update amendment
|
Update Amendment Crud Request Data(Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|28| Update Contact Crud
|
Update Contact Crud Request Data (Any);

Id (String)
| N/A
| CRUD: Update contact
|
Update Contact Crud Request Data(Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|29| Update Refund Crud
|
Update Refund Crud Request Data (Any);

Id (String)
| N/A
| CRUD: Update refund
|
Update Refund Crud Request Data(Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|30| Update Usage Crud
|
Update Usage Crud Request Data (Any);

Id (String)
| N/A
| CRUD: Update usage
|
Update Usage Crud Request Data(Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|31| Update Invoice Crud
|
Update Invoice Crud Request Data (Any);

Id (String)
| N/A
| CRUD: Update Invoice
|
Update Invoice Crud Request Data(Any) (Removed);

Content (Binary) (New);

id (String) (Modified)
| Attributes Type (HttpResponseAttributes) (New)

|===

== Changes in Operations Metadata

[cols="5%,17%,15%,15%,17%,15%,15%"]
|===
4+|Metadata Existing in Zuora 4.x 3+| Metadata in Zuora 5.x
|Nr |Operation Name	| Input Metadata	|Output Metadata	| Operation Name	                         |Input Metadata	                                    |Output Metadata

|1| Submit data query
| N/A
| N/A
| POST Data Query Job
|
useIndexJoin (Boolean) (New);

columnSeparator (String) (New)

| N/A

|2| Create account
|
endingUnit (String);

    price (String);

    startingUnit (String);

    includedUnits (String);

    discountAmount (String);

    discountPercentage (String);

    overagePrice (String);

    unusedUnitsCreditRates (String);

    quantity (String);

    priceIncreasePercentage (string);
| N/A
| Create account
|
    endingUnit (Number) (Modified);

    price (Number) (Modified);

    startingUnit (Number) (Modified);

    includedUnits (Number) (Modified);

    discountAmount (Number) (Modified);

    discountPercentage (Number) (Modified);

    overagePrice (Number) (Modified);

    unusedUnitsCreditRates (Number) (Modified);

    quantity (Number) (Modified);

    priceIncreasePercentage (Number) (Modified);

| N/A

|3| Amend
| N/A
| N/A
| Amend
|
ResumeDate (date) (New);

SuspendDate (Date) (New)

| N/A

|4| Create account crud
| N/A
| N/A
| CRUD: Create account
|
Class_NS (String) (New);

SyncDate_NS (String) (New);

CustomerType_NS (String) (New);

IntegrationStatus_NS (String) (New);

Subsidiary_NS (String) (New);

Location_NS (String) (New);

IntegrationId_NS (String) (New);

Department_NS (String) (New);

| N/A


|5| Create credit balance adjustment crud
| N/A
| N/A
| CRUD: Create credit balance adjustment
|
IntegrationId_NS (String) (New);

IntegrationStatus_NS (String) (New);

SyncDate_NS (String) (New);

| N/A

|6| Create import crud
| ImportType (String);

    File (String);

    Name (String);
| N/A
| CRUD: Create import
|
    ImportType (String) (Removed);

    File (String) (Removed);

    Name (String) (Removed);

| N/A

|7| Create payment method crud
| MitProfileAgreedOn (String);
| N/A
| CRUD: Create payment method
|
    MitProfileAgreedOn (String) (Removed);

    BankTransferAccountName (String) (New);

    BankTransferAccountNumber (String) (New);

| N/A

|8| Create payment crud
| N/A
| N/A
| CRUD: Create payment
|
    SyncDate_NS (String) (New);

    Origin_NS (String) (New);

    IntegrationStatus_NS (String) (New);

    IntegrationId_NS (String) (New);

    Transaction_NS (String) (New);
| N/A

|9| Create product crud
| N/A
| N/A
| CRUD: Create product
|
    SyncDate_NS (String) (New);

    ItemType_NS (String) (New);

    IntegrationStatus_NS (String) (New);

    IntegrationId_NS (String) (New);
| N/A

|10| Create product rate plan charge crud
| N/A
| N/A
| CRUD: Create product rate plan charge
|
    ProductRatePlanChargeTierData (Object) (New);

    StartingUnit (Number) (New);

    DiscountPercentage (Number) (New);

    EndingUnit (Number) (New);

    Price (Number) (New);

    Currency (String) (New);

    IsOveragePrice (Boolean) (New);

    PriceFormat (String) (New);

    DiscountAmount (Number) (New);

    DeferredRevAccount_NS (String) (New);

    Class_NS (String) (New);

    RevRecTemplateType_NS (String) (New);

    RecognizedRevAccount_NS (String) (New);

    Location_NS (String) (New);

    RevRecEnd_NS (String) (New);

    RevRecStart_NS (String) (New);

    IntegrationId_NS (String) (New);

    Department_NS (String) (New);

    ItemType_NS (String) (New);

    IncludeChildren_NS (String) (New);

    IntegrationStatus_NS (String) (New);

    Subsidiary_NS (String) (New);
| N/A

|11| Create product rate plan crud
| N/A
| N/A
| CRUD: Create product rate plan
|
    SyncDate_NS (String) (New);

    Class_NS (String) (New);

    IncludeChildren_NS (String) (New);

    Deparment_NS (String) (New);

    IntegrationId_NS (String) (New);

    BillingPeriod_NS (String) (New);

    Price_NS (String) (New);

    Location_NS (String) (New);

    Subsidiary_NS (String) (New);

    IntegrationStatus_NS (String) (New);

    ItemType_NS (String) (New);

| N/A

|12| Create refund crud
| N/A
| N/A
| CRUD: Create refund
|
    SyncDate_NS (String) (new);

    IntegrationId_NS (String) (new);

    SynctoNetSuite_NS (String) (new);

    IntegrationStatus_NS (String) (new);

    Origin_NS (String) (new);

| N/A

|13| Create usage crud
| N/A
| N/A
| CRUD: Create usage
|
    Description (String) (New);

| N/A

|14| Create order
| N/A
| N/A
| Create order
| N/A
|
    SubscriptionId(String) (New);

    OrderId(String)(New);

    AccountId(String)(New);

    PaymentId(String)(New);

    SubscriptionsIds(Array<String>)(New);

    CreditMemoIds(Array<String>)(New);

    InvoiceIds(Array<String>)(New);


|15| Create payment method
| N/A
| N/A
| CRUD: Create payment method
|
    MitConsentAgreementRef(String)(New);

    ZipCode(String)(New);

    MakeDefault(Boolean)(New);

    BAID(String)(New);

    City(String)(New);

    CardHolderInfo(Object)(New);

    MitProfileAction(String)(New);

    BankName(String)(New);

    MitConsentAgreementSrc(String)(New);

    AddressLine1(String)(New);

    AddressLine2(String)(New);

    BankAccountNumber(String)(New);

    State(String)(New);

    AuthGateway(String)(New);

    MitNetworkTransactionId(String)(New);

    Email(String)(New);

    ExpirationYear(String)(New);

    BankAccountName(String)(New);

    MitProfileAgreedOn(String)(New);

    MitProfileType(String)(New);

    CardType(String)(New);

    SecurityCode(String)(New);

    ExpirationMonth(String)(New);

    AccountKey(String)(New);

    BankAccountType(String)(New);

    Phone(String)(New);

    PreApprovalKey(String)(New);

    CardNumber(String)(New);

    BankABACode(String)(New);
| N/A

|16| Create stored credential profile
| N/A
| N/A
| Create stored credential profile
|
    NetworkTransactionId(String)(New);
| N/A

|17| Cancel authorization
     | N/A
     | N/A
     | Cancel authorization
     |
         PaymentGatewayId(String)(New);
     | N/A

|18| Create payment
| N/A
| N/A
| Create payment
|
    Origin_NS(String)(New);

    IntegrationStatus_NS(String)(New);

    IntegrationId_NS(String)(New);

    Transaction_NS(String)(New);

    SyncDate_NS(String)(New);
| N/A

|19| Refund payment
| N/A
| N/A
| Refund payment
|
    Origin_NS(String)(New);

    IntegrationStatus_NS(String)(New);

    IntegrationId_NS(String)(New);

    SyncToNetSuite_NS(String)(New);

    SyncDate_NS(String)(New);
|
    Origin_NS(String)(New);

    IntegrationStatus_NS(String)(New);

    IntegrationId_NS(String)(New);

    SyncToNetSuite_NS(String)(New);

    SyncDate_NS(String)(New);

|20| Create subscription
| N/A
| TotalContractedValue (String)

    PaidAmount(String)

    ContractedMrr(String)
| Create subscription
|
    PaymentMethodId(String)(New);

    QuoteNumber_QT(String)(New);

    OpportunityName_QT(String)(New);

    CPQBundleJsonId_QT(String)(New);

    QuoteType_QT(String)(New);

    QuoteBusinessType_QT(String)(New);

    OpportunityCloseDate_QT(String)(New);

    IntegrationId_NS(String)(Name);

    Project_NS(String)(Name);

    SalesOrder_NS(String)(Name);

    IntegrationStatus_NS(String)(Name);

    SyncDate_NS(String)(Name);
| TotalContractedValue (Number)(Modified);

    PaidAmount(Number)(Modified);

    ContractedMrr(Number)(Modified);

|21| Post usage
| File (String)
| N/A
| Post usage
|
    File (String) (Removed);
| N/A

|===

== New Operations in Zuora Connector 5.0.0

[cols="5%,25%,70%"]
|===
3+|New in Zuora 5.x
| Nr | Name	| Description

|1| CRUD: Get amendment	| This operation makes an HTTP GET request to the /v1/object/amendment/{id} endpoint
|2| CRUD: Get bill run	| Business operations depending on the completion of the bill run will not be available while the bill run query returns `PostInProgress`. Upon completion of the bill run, a query will return `Posted`.
|3| CRUD: Get contact	| This operation makes an HTTP GET request to the /v1/object/contact/{id} endpoint
|4| CRUD: Get invoice	| This operation makes an HTTP GET request to the /v1/object/invoice/{id} endpoint
|5| CRUD: Get product rate plan charge	| This operation makes an HTTP GET request to the /v1/object/product-rate-plan-charge/{id} endpoint
|6| CRUD: Get rate plan charge	| This operation makes an HTTP GET request to the /v1/object/rate-plan-charge/{id} endpoint
|7| CRUD: Get usage	| This operation makes an HTTP GET request to the /v1/object/get-usage/{id} endpoint
|8| CRUD: Update product rate plan charge tier	| This operation makes an HTTP PUT request to the/v1/object/product-rate-plan-charge-tier/{id} endpoint
|9| CRUD: Update rate plan charge	| This operation makes an HTTP PUT request to the /v1/object/rate-plan-charge/{id} endpoint
|10| Create custom object definition	| Post custom object definition with the given type
|11| Create custom object records | Create custom object records with the given type
|12| Create usage records | Create usage records
|13| DELETE Data Query Job | Cancels a [data query](https://knowledgecenter.zuora.com/DC_Developers/BA_Data_Query) job, which prevents Zuora from performing the query
|14| Delete event trigger | This operation makes an HTTP DELETE request to the /events/event-triggers/{id} endpoint
|15| Delete a workflow by ID | Deletes a specific workflow by its ID
|16| Delete custom object definition | This operation makes an HTTP DELETE request to the /objects/definitions/default/{object} endpoint
|17| Delete custom object record | This operation makes an HTTP DELETE request to the /objects/records/default/{object}/{id} endpoint
|18| Delete schema of Usage custom field definition | This operation makes an HTTP DELETE request to the /usage/{id} endpoint
|19| Delete usage record | This operation makes an HTTP DELETE request to the /usage/{id} endpoint
|20| Download usage file template | Download usage file template
|21| Download usage import failure file | Download usage import failure file
|22| Download usage import file | Download usage import file
|23| Export a workflow | Export a Workflow in a JSON document
|24| Get Event Trigger | This operation makes an HTTP GET request to the /events/event-trigger/{id} endpoint
|25| Get Event Triggers | This operation makes an HTTP GET request to the /events/event-triggers endpoint
|26| Get Usage custom field definition | Get Usage custom field definition
|27| Get a task by id | Retrieves a specific workflow task by its ID.
|28| Get a workflow by ID | Retrieves information about a specific workflow by its ID
|29| Get all custom object definitions | Retrieves information about a specific object definition
|30| Get custom object definition | Retrieves information about a specific workflow by its ID
|31| Get custom object record | Retrieves information about a custom record
|32| Get details of usage import | Get details of usage import
|33| Get rated usage by account | Get rated usage by account
|34| Get rated usage by charge | Get rated usage by charge
|35| Get rated usage by subscription | Get rated usage by subscription
|36| Get rating results by account | Get rated usage by account
|37| Get rating results by charge | Get rated usage by charge
|38| Get rating results by subscription | Get rated usage by subscription
|39| Get status of usage import | Get status of usage import
|40| Get tasks | Retrieves a specific workflow task by its ID.
|41| Get usage imports | This operation makes an HTTP GET request to the /usage-imports endpoint
|42| Get usage record | This operation makes an HTTP GET request to the /usage-record endpoint
|43| Get work flows | Retrieves a specific workflow task by its ID.
|44| Import a workflow | Imports a workflow by ID
|45| Import usage file | Imports usage file
|46| List all settings | Lists all settings
|47| Post data query job| Submits a [data query](https://knowledgecenter.zuora.com/DC_Developers/BA_Data_Query) to be performed by Zuora and creates a query job. You can use [Get data query job](#operation/GET_DataQueryJob) to track the status of the query job and obtain the URL of, the query results.
|48| Post event trigger| This operation makes an HTTP POST request to the /events/event-triggers endpoint
|49| Put event trigger| This operation makes an HTTP GET request to the /events/event-triggers endpoint
|50| Query an accounting code| This operation makes an HTTP POST request to the /v1/accounting-codes/{ac-id} endpoint
|51| Query custom object records| This operation makes an HTTP GET request to the /custom/query endpoint
|52| Query usage records| This operation makes an HTTP GET request to the /usage/query endpoint
|53| Query usage records in stream| This operation makes an HTTP GET request to the /usage/stream-query endpoint
|54| Re-open accounting period| This operation makes an HTTP POST request to the /v1/accounting-periods/{ap-id} endpoint
|55| Run a workflow| Run a specified workflow. In the reqeust body, you can include parameters that you want to pass to the workflow. For the parameters to be recognized and picked up by tasks in the workflow,you need to define the parameters first.
|56| Set schema of usage custom field definition| Set schema of Usage custom field definition
|57| Submit multiple settings requests as a batch| Submit multiple requests as a batch
|58| Update custom object definition| This operation makes an HTTP PUT request to the /objects/definition/default/{object}/{id} endpoint
|59| Update custom object record| This operation makes an HTTP PUT request to the /objects/records/default/{object}/{id} endpoint
|60| Update individual fields in a custom object record| Update individual fields in a record
|61| Update Or Delete Custom Object Records As a Batch| This operation makes an HTTP PUT request to the /workflows/tasks/batch_update endpoint
|62| Update Tasks In Batch| This operation makes an HTTP PUT request to the /workflows/tasks/batch_update endpoint
|63| Update Usage Record| This operation makes an HTTP PUT request to the /fields/definitions/Usage endpoint
|===

== Removed Operations in Zuora Connector 5.0.0
Four operations were removed from the Zuora connector and were added separately in the new Anypoint Connector for AQuA (AQuA Connector).

[cols="15%,35%,15%,35%"]
|===
2+|Removed in Zuora 5.x 2+| Available in Zuora AQuA 1.x as
|Name	| Description	|Name	|Description

| Aqua_  Delete A Running Job	| Delete the current job, if it is not complete, else an error is thrown. |	Delete a Running Job	|No changes
| Aqua_  Get Job Results | Retrieves an aggregate query using the Job ID. | Get Job Results | No changes
| Aqua_  Get Last Job Completed | Returns the details of the last completed job. | Get Last Job Completed | No changes
| Aqua_  Post Query Or Export Deleted Data | Post query. | Post Query or Export Deleted Data | No changes
|===

== Limitations

AQuA operations are removed from Zuora Connector. To use AQuA operations, install Zuora AQuA Connector.  

After you upgrade to Zuora Connector 5.0.0, the following operations are no longer available in Zuora Connector and must be replaced with the corresponding Zuora AQuA Connector operations.

=== CRUD Operations

All of the CRUD operations were changed so that CRUD is prepended to operation names. A few examples are: 

|===
|4.2.x|5.0.0

|Create import crud operation
|CRUD: Create Import operation

|Delete bill run crud
|CRUD: Delete bill run

|Get account crud
|CRUD: Get account

|Update product crud
|CRUD: Update Product
|===

=== Changes to Operations Names

Some of the operations' names are updated:

|===
|4.2.x|5.0.0

|Create revenue schedule for invoice item adjustment distribute by date range
|Create revenue schedule for invoice item adjustment (distribute by date range)

|Remove an event trigger
|DELETE Event Trigger

|Delete usage crud
|Delete usage record
|===

=== Changes in Fields and Values

Some fields and their corresponding values have changed: 

* The credit memo items operation and the taxation items created in the `write-off` operation are now applied to the corresponding invoice items and invoice taxation items, respectively.
* The values of the following fields are also changed to the taxation items of credit memo items operation:
  ** taxRate +
  The value of this field is now set to `0`.
  ** exemptAmount +
  The value of this field is now set to `0`.
  ** taxRateType + 
  The value of this field is now set to `null`.

== Upgrade Prerequisites

Before you perform the upgrade, you must:

. Create a backup of your files, data, and configuration in case you need to restore to the previous version. 
. Install Zuora AQuA Connector to replace the AQuA operations that were previously included in Zuora Connector 4.2.x:
.. In Studio, create a Mule project.
.. In the Mule Palette view, click *Search in Exchange*.
.. In Add Modules to Project, type 'Zuora AQuA' in the search field.
.. In Available modules, select *Zuora AQuA Connector*, and then click *Add*.
.. Click *Finish*.	
.. Verify that the `zuora-aqua-connector` dependency version is `1.0.0` in the pom.xml. +
Anypoint Studio upgrades the connector automatically.

== Upgrade Steps

Follow these steps to perform the upgrade to Zuora Connector 5.0.0:

.. In Studio, create a Mule project.
.. In the Mule Palette view, click *Search in Exchange*.
.. In Add Modules to Project, type 'Zuora AQuA' in the search field.
.. In Available modules, select *Zuora AQuA Connector*, and then click *Add*.
.. Click *Finish*.
.. Verify that the `zuora-connector` dependency version is `5.0.0` in the pom.xml. 

Anypoint Studio upgrades the connector automatically. 


== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Anypoint Studio, verify that there are no errors in the *Problems* or *Console* views.
. Check the project pom.xml and verify that there are no problems.
. Test the connection and verify that the operations work.  

== Troubleshooting

If there are problems with caching the parameters and caching the metadata, try restarting Anypoint Studio.  

== Reverting the Upgrade

If it is necessary to revert to the previous version of Zuora Connector, change the `zuora-connector` dependency version `5.0.0` in the project's pom.xml to the previous version.  

You must update the project's pom.xml in Anypoint Studio. 


== See Also

https://help.mulesoft.com[MuleSoft Help Center]
