= Zuora Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

Zuora Connector v1.0

The Anypoint Connector for Zuora lets you connect to the Zuora platform. The connector exposes convenient methods for taking advantage of the capabilities of Zuora, allowing you to access the entire Zuora REST API.

This connector exposes all the operations provided by Zuora's REST API. Use these REST calls to interact with Zuora.

== Audience

* New user -- Read this document and configure your Mule application in xref:zuora/zuora-connector-design-center.adoc[Design Center].
* Current Mule user -- Read this document and configure your Mule application in xref:zuora/zuora-connector-design-center.adoc[Design Center] or xref:zuora/zuora-connector-studio.adoc[Anypoint Studio].
* Power user - Read the xref:zuora/zuora-connector-xml-maven.adoc[XML and Maven Support] and xref:zuora/zuora-connector-use-cases.adoc[Use Cases].

[[prereqs]]
== Prerequisites

 This document assumes that you are familiar with Zuora, HTTP, REST APIs, Mule runtime engine (Mule), Anypoint Connectors, Anypoint Studio (Studio), Mule concepts, elements in a Mule flow, and Global Elements.

 Requirements for using the connector:

* Login credentials to Zuora.
* Namespace and schema location: If you plan to create the XML for your Mule application, you need to include the correct namespace and schema location in your XML file. Anypoint Studio adds this information to the XML file automatically when you add the Zuora connector to a flow in a Mule app.

For hardware and software information, see the release notes.

[[developapp]]
== Develop an application

Build an application in this order:

. Configure the connector.

. Test the connection.

. Build the rest of your flow.

. Add and configure DataWeave.

== See Also
* https://www.zuora.com/developer/api-reference[Zuora REST API Reference]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
