= Zuora Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

Zuora Connector v1.0

The Anypoint Connector for Zuora lets you connect to the Zuora platform. This connector exposes all of the operations provided by Zuora's REST API.

For information about the Zuora REST API methods and parameters, see the https://www.zuora.com/developer/api-reference[Zuora REST API Reference].

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect to APIs and resources on external systems, such as Salesforce, Zuora, ServiceNow, and Twitter.

== Prerequisites

Before creating an app, you must have access to the Zuora target resource and Anypoint Platform. You must also understand how to create a Mule app using Design Center or Anypoint Studio.

== Audience

* Starting user -- Read this Get Started document
 and create your Mule app in zuora/zuora-connector-design-center.adoc[Design Center] or zuora/zuora-connector-studio.adoc[Anypoint Studio].
* Power user - Read the zuora/zuora-connector-xml-maven.adoc[XML and Maven Support] and zuora/zuora-connector-examples.adoc[Examples] documents.

== Next Steps

After you have met the prerequisites and experimented with templates and examples, you are ready to create an app with
xref:zuora/zuora-connector-design-center.adoc[Design Center] or
xref:zuora/Zuora-connector-studio.adoc[Anypoint Studio].


== See Also
* https://anypoint.mulesoft.com/exchange/com.mulesoft.connectors/mule-zuora-connector[Zuora connector in Anypoint Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
