= Salesforce Design Center Configuration - Mule 4
:page-aliases: connectors::salesforce/salesforce-connector-100-design-center.adoc

Design Center enables you to create apps visually. To use Design Center, work with your Anypoint Platform administrator to ensure that you have a xref:access-management::environments.adoc#to-create-a-new-environment[Design environment]. For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour].

To create an app in Flow Designer:

* Configure the input source (trigger) for your app.
* Add the connector as a component to process the input for the app.

For information about Flow Designer field values, see the xref:salesforce-connector-reference.adoc[Salesforce Connector Reference].

== Configure the Trigger

. In Flow Designer, click *Create*.
. Click *Create new application*.
. Specify a value for *Project name*.
. Exit from *Let's get started* by clicking *Go straight to canvas*.
. Click the name of the trigger card.
. If you use Salesforce Connector as your trigger, a change in a Salesforce object, topic, or channel is sent as input to your app to enable you to process the change.
+
Alternatively, you can use one of these triggers:

* HTTP Listener, to provide input to your app from a browser or an application such as Postman or `curl`
* Scheduler, to provide input to your app at a specific time

Salesforce trigger operations:

* *On Deleted Object*
+
Initiates your app when a Salesforce user deletes an object. Possible object types are `Contact`, `Lead`, `Account`, `Contracts`, `Opportunity`, or the name of a custom object.
+
* *On Modified Object*
+
Initiates your app when a Salesforce user modifies an object. Possible object types are `Contact`, `Lead`, `Account`, `Contracts`, `Opportunity`, or the name of a custom object.
+
* *On New Object*
+
Initiates your app when a Salesforce user creates a new object. Possible object types are `Contact`, `Lead`, `Account`, `Contracts`, `Opportunity`, or the name of a custom object.
+
* *Replay Channel Listener*
+
Subscribes to a streaming channel. This trigger provides channel-related notification settings for new events and events stored by Salesforce within the 24-hour retention period. Events that take place in the specified channel trigger the flow.
+
* *Replay Topic Listener*
+
Subscribes to a topic to receive topic-related notification settings for new events and events stored by Salesforce within the 24-hour retention period. Events that take place on records in the specified topic trigger the flow.
+
* *Subscribe Channel Listener*
+
Subscribes to a streaming channel to receive channel-related notification settings for new events that take place after you subscribe.
+
* *Subscribe Topic Listener*
+
Subscribes to a topic to provide topic-related notification settings for new events that take place after you subscribe.

Before you can subscribe to a channel or topic, it must first be published to Salesforce.

The following table describes the most important fields for triggers:

[%header,cols="30a,70a"]
|===
|Input Trigger Types |Important Fields
|Channel operations a|

* *Streaming Channel*: Name of the channel
* *Replay Option*: Options for receiving channel events after subscribing to a channel
* *Connection type*: See <<Configure a Connection Type>>.

| Object operations a|
** *Object type*: `Contact`, `Lead`, `Account`, `Contracts`, `Opportunity`
** *Since*: Start time for processing the object
** *Scheduling Strategy*: How often to schedule changes
** *Connection type*: See <<Configure a Connection Type>>.
|  Topic operations a|
** *Topic*: Topic to which to subscribe
** *Replay Option* (Replay Topic only): What events to receive and reply to
|===

== Configure a Connection Type

. Specify the Connection Type:
+
[%header%autowidth.spread]
|===
|Connection Type |Salesforce Information Site
| <<Configure Basic Authentication Authorization, Basic Authentication>> |https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_login.htm[SOAP API Username Password Login]
| <<Configure OAuth 2.0 Authorization, OAuth 2.0>> |https://help.salesforce.com/articleView?id=remoteaccess_oauth_web_server_flow.htm[OAuth 2.0 Web Server Authorization Flow]
| <<Configure OAuth JWT Authorization, OAuth JWT>> |https://help.salesforce.com/articleView?id=remoteaccess_oauth_jwt_flow.htm[OAuth 2.0 JWT Bearer Token Flow]
| <<Configure OAuth SAML Authorization, OAuth SAML>> |https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_oauth_SAML_bearer_flow.htm[OAuth 2.0 SAML Bearer Assertion Flow]
| <<Configure OAuth Username Password Authorization, OAuth Username Password>> |https://help.salesforce.com/articleView?id=remoteaccess_oauth_username_password_flow.htm[OAuth 2.0 Username-Password Flow]
|===
+
. Specify the parameters required for each configuration type and click *Test* to ensure that you have a valid connection to Salesforce.
. If needed, configure the *Apex* tab to determine what metadata to fetch and to add Apex class names.
. If you haven't specified a *Connection Type*, you can configure the *Advanced* tab to set the *Max Idle Time* and *Time Units* fields for how long to hold open a connection before it expires.
. After you specify a connection type, you can use the *Advanced* tab to change values for the *Reconnection Strategy*, *Pooling Profile*, and *Expiration Policy* fields.
. If needed, set the *Redelivery Policy* field on the main configuration screen to specify the maximum number of times to try delivering trigger content.

== Configure the Target Component

. Click “+” next to the trigger card.
. In *Select a component*, search for the connector name.
. Select the connector name.
. Select an operation for the connector.
. Enter the required values in the *General* tab.
. If needed, enter values for other tabs.
. Specify access information to the connector resource.
. If a *Test* button is available, click it to test the connection.

In Flow Designer, after you specify a trigger, you can add:

* Salesforce Connector as a component to process the input you received from the trigger
* A DataWeave transform placed between the trigger and the component to transform the input information before you process it

The following table describes some of the operations you can use with Salesforce Connector:

[%header,cols="30s,70a"]
|===
|Operation |Use
|Create |
* *Type*: Salesforce object type
* *Records*: Creates a collection of Salesforce objects
|Query |
* *Salesforce query*: Salesforce query to retrieve objects
* *Parameters* Values for placeholders in the Salesforce query
|Update |
* *Type*: Salesforce object type
* *Records*: Creates a collection of Salesforce objects to update
|Delete |
*Records To Delete Ids*: Creates a collection of Salesforce objects to delete
|===

== Configure Basic Authentication Authorization

Important fields:

* *Username* (required)
+
Salesforce username
+
* *Password* (required)
+
Corresponding password
+
* *Security Token*
+
Corresponding security token
+
* *Authorization URL*
+
URL for the endpoint configured to handle SOAP authentication requests

Implementing OAuth 2.0-based authentication mechanisms involves extra steps, but it offers better security if your service is exposed to external users.

== Configure OAuth 2.0 Authorization

Important fields:

* *Consumer Key* (required)
+
Consumer key for the Salesforce-connected app. See xref:9.8@salesforce-connector-config-topics.adoc#create-consumer-key[Create a Consumer Key].
+
* *Consumer Secret* (required)
+
Consumer secret for accessing Salesforce
+
* *Listener Config* (required)
+
Configuration for the listener, for example, `HTTP_Listener_config`
+
* *Callback Path* (required)
+
Path for the callback, for example, `/callback`
* *Authorize Path* (required)
+
Path for authorization, for example, `/authorize`
* *External Callback URL*
+
Callback URL, for example, `+http://localhost:8085/callback+`

== Configure OAuth JWT Authorization

Important fields:

* *Consumer Key* (required)
+
Consumer key for the Salesforce-connected app. See xref:9.8@salesforce-connector-config-topics.adoc#create-consumer-key[Create a Consumer Key].
+
* *Key Store* (required)
+
Path to the keystore used to sign data during authentication. Use only a Java-format keystore. See xref:9.8@salesforce-connector-config-topics.adoc#keystoregen[Generate a Keystore File].
+
* *Store Password* (required)
+
Password for the keystore
+
* *Principal* (required)
+
Salesforce username

== Configure OAuth SAML Authorization

Important fields:

* *Consumer Key* (required)
+
Consumer key for the Salesforce-connected app. See xref:9.8@salesforce-connector-config-topics.adoc#create-consumer-key[Create a Consumer Key].
+
* *Key Store* (required)
+
Path to the keystore used to sign data during authentication. Format the keystore in JAVA. See xref:9.8@salesforce-connector-config-topics.adoc#keystoregen[Generate a Keystore File].
+
* *Store Password* (required)
+
Keystore password
+
* *Principal* (required)
+
Username of the authorized Salesforce user

== Configure OAuth Username Password Authorization

Important fields:

* *Consumer Key* (required)
+
Consumer key for the Salesforce-connected app. See xref:9.8@salesforce-connector-config-topics.adoc#create-consumer-key[Create a Consumer Key].
+
* *Consumer Secret* (required)
+
Consumer secret for accessing Salesforce
+
* *Username* (required)
+
Salesforce username
+
* *Password* (required)
+
Corresponding password
+
* *Security token*
+
Corresponding security token

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
