= MQTT Connector FAQ

MQTT Connector frequently asked questions (FAQ) are:

==  Does MQTT Connector use an object store for the Enable File Persistence feature?

The *Enable file persistence* feature is available only on the on-premises installation and uses a file for persistent messages. Note that an object store enables persistent storage for CloudHub applications. Refer to the xref:object-store::index.adoc[object store] documentation for details.

== Is MQTT Connector supported on CloudHub and Cluster environments?

Yes, MQTT Connector is supported on CloudHub and on cluster environments.

== Is MQTT Connector cluster-aware?

MQTT Connector is cluster-aware. MQTT brokers usually implement a client takeover mechanism that closes an old connection if a new connection request with the same client ID as the existing (old) connection is received and then accepts the new connection.
The client takeover mechanism can become a problem if you want to deploy an application in a cluster, and still provide an explicit client ID that identifies the client. MQTT Connector provides client ID generators that help you set a static client ID, set a client ID with a dynamic component to adjust to different deployment scenarios, or define your custom client ID generator.

For further information, refer to the xref:mqtt3-connector-client-id.adoc[set a Client ID with MQTT Connector] documentation.

== What are the authentication types supported?

MQTT Connector authentication supports user and password, and certificate-based authentication (TLS or WSS). Refer to the xref:mqtt3-connector-studio-configuration.adoc#configure-authentication[configure credentials for authentication] documentation.

== Does MQTT Connector trace connection and operation executions?

Refer to the xref:mqtt3-connector-troubleshooting.adoc[troubleshoot MQTT Connector] documentation to learn how to enable verbose logging in DEBUG mode for the connector, for Eclipse Paho driver and the Mosquitto broker.

==  What is the server-side configuration required for MQTT Connector to work?

MQTT Connector works with any MQTT version 3.x compliant server also known as MQTT broker.  To configure the server, refer to your MQTT broker’s documentation,  for example, refer to the https://mosquitto.org/documentation[Eclipse Mosquitto] broker documentation.

== Does MQTT Connector use a 3rd party library to connect with the external system?
MQTT Connector uses Eclipse Mosquitto libraries. The ArtifactID is `org.eclipse.paho.client.mqttv3`.

== Is there any documentation or release notes for the Eclipse Mosquitto external library?

To get release notes for Eclipse Mosquitto library, refer to the https://github.com/eclipse/paho.mqtt.java/releases[Eclipse public repository].

== Are there any permission, roles, or additional configuration required on the broker side to connect with our credentials using MQTT Connector?

No, there aren't any additional permissions or configuration requirements to connect to MQTT version 3.x compliant MQTT brokers. On the MQTT broker side, you do need to configure the listeners properly.

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
