= MQTT Connector FAQ

MQTT Connector frequently asked questions (FAQ) are:

==  Does MQTT Connector use an object store for the Enable File Persistence feature?

The *Enable file persistence* feature does not use an object store. The file feature relies on the driver to use a file for persistent messages and you can only use the feature in on-premise installations.

== Was MQTT Connector tested in multiple environments such as CloudHub/RTF/Cluster/PCE?

MQTT Connector has been tested against multiple environments, such as on CloudHub and on clusters.

== Is MQTT Connector cluster-aware?

MQTT Connector is cluster-aware. MQTT brokers usually implement a client takeover mechanism that closes an old connection if a new connection request with the same client ID as the existing (old) connection is received and then accepts the new connection.
The client takeover mechanism can become a problem if you want to deploy an application in a cluster, and still provide an explicit client ID that identifies the client. MQTT Connector provides client ID generators that help you set a static client ID, set a client ID with a dynamic component to adjust to different deployment scenarios, or define your custom client ID generator.

For further information, refer to the xref:mqtt3-connector-client-id.adoc[set a Client ID with MQTT Connector] documentation.

== What are the authentication types supported?

MQTT Connector authentication requirements are limited to no authentication, user and password, and certificate based authentication (TLS or WSS). Refer to the configure credentials for authentication documentation.

== Does MQTT Connector trace the authentication dance and operation execution?

Refer to the xref:mqtt3-connector-troubleshooting.adoc[troubleshoot MQTT Connector] documentation to learn how to enable verbose logging in DEBUG mode for the connector, for Eclipse Paho driver and the Mosquitto broker.

==  What is the server-side configuration required for MQTT Connector to work?

To get information on the server-side configuration, refer to the https://mosquitto.org/documentation/[Eclipse Mosquitto] broker documentation.

== Does MQTT Connector use a 3rd party library to connect with the external system?
MQTT Connector uses Eclipse Mosquitto libraries. The ArtifactID is `org.eclipse.paho.client.mqttv3`.

== Is there any documentation or release notes for the Eclipse Mosquitto external library?

To get release notes for Eclipse Mosquitto library, refer to the https://github.com/eclipse/paho.mqtt.java/releases[Eclipse public repository].

== Are there any permission, roles or additional configuration required on the broker side to connect with our credentials using MQTT Connector?

If you already have a broker up and running that uses MQTT Connector make sure to configure the listeners properly on the broker side.


== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
