= Configure the Quality of Service for MQTT Connector

The MQTT protocol enables you to specify levels of delivery assurance for inbound or outbound messages. These levels
are referred to as _quality of service_ (QoS).

The available QoS levels to configure for MQTT Connector are:

 * *AT_MOST_ONCE*
+
Messages are delivered at most one time ("fire and forget") and delivery is not guaranteed.
 * *AT_LEAST_ONCE*
+
Messages are delivered correctly at least one time. The message could be delivered more than once.
 * *EXACTLY_ONCE*
+
Messages are sent once and delivery is ensured.

The quality of service is sometimes different between message publishing and message subscribing, even if the published message and the subscription have a common topic. For example, a message published with QoS 1 or 2 might not be successfully delivered to the *On New Message* source, if that listener source is subscribed with QoS *AT_MOST_ONCE* (QoS=0).

== See Also

* xref:mqtt3-connector-examples.adoc[MQTT3 Connector Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
