= Microsoft Dynamics 365 for Finance and Operations Connector 2.2 - Mule 4
:page-aliases: connectors::microsoft/microsoft-365-ops-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]


Anypoint Connector for Microsoft Dynamics 365 for Finance and Operations (Microsoft Dynamics 365 for Operations Connector) enables integration with Microsoft Dynamics 365 for Operations Web API. You can configure this connector using the Flow Designer feature of Design Center or using Anypoint Studio. This connector enables connection types for OAuth 2 or OAuth 2 with a username and password.

== Prerequisites

To use this connector, you must be familiar with:

* The Microsoft Dynamics 365 for Finance and Operations API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to a Microsoft Dynamics 365 instance (online or on-premises) managed by Azure Active Directory.


== Common Use Cases for the Connector

This connector enables you to perform these operations:

* Authorize or unauthorize access to a Microsoft Dynamics 365 for Operations server
* Create a recurring job on Microsoft Dynamics 365 for Operations server
* Retrieve multiple entries, including retrieval using DataSense Query Language
* Execute operations

See xref:microsoft-365-finance-operations-connector-examples.adoc[Examples] for use cases.

== Audience

* New users, read:
** xref:microsoft-365-finance-operations-connector-studio.adoc[Use Studio to Configure the Connector] to create your Mule app
* xref:microsoft-365-finance-operations-connector-examples.adoc[Examples], which provides an example use case for the connector
* Advanced users, read:
** xref:microsoft-365-finance-operations-connector-xml-maven.adoc[XML and Maven Support]
* The xref:microsoft-365-finance-operations-connector-examples.adoc[Examples], which provide one or more use cases for the connector

== Connection Types

Microsoft Dynamics 365 for Finance and Operations Connector uses the OAuth 2.0 connection type, which delegates user authentication to the service hosting the user account.

== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app and configure the connector using xref:microsoft-365-finance-operations-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:microsoft-365-ops-connector-reference.adoc[Microsoft Dynamics 365 for Finance and Operations Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
