= Azure Service Bus Management XML and Maven Support - Get Started Mule 4

If you manually code a Mule app in XML either from the
Studio XML editor or a text editor, perform the 
following actions to get access to the connector:

. Add the namespace for the connector to your XML flow.
. Add dependency information to your Maven `pom.xml` file.

In the Studio visual editor, when you drag a connector from the palette to the canvas, Studio automatically populates the XML code with the connector namespace and schema location.

== Add a Namespace for the Connector

Paste the following code inside the <mule> tag of the header of your configuration XML:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/<connector> 
http://www.mulesoft.org/schema/mule/<connector>/current/mule-<connector> .xsd
----

// Writer: Please check this in the XML code in the connector guide.

This example shows how the namespace statements are placed in the mule XML block: 

[source,xml,linenums]
----
<mule xmlns:<connector>="http://www.mulesoft.org/schema/mule/<connector>" 
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:file="http://www.mulesoft.org/schema/mule/file" 
	xmlns="http://www.mulesoft.org/schema/mule/core" 
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core 
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/file 
	http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
	http://www.mulesoft.org/schema/mule/http 
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/core 
	http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
	http://www.mulesoft.org/schema/mule/<connector> 
	http://www.mulesoft.org/schema/mule/<connector>/current/mule-<connector>.xsd">
----

// Writer: Ensure that XML code examples have line breaks after XML elements
// to reduce the need for users to scroll the code to read it.

== Add a POM File Dependency 

The `pom.xml` Maven file generated by Anypoint Studio contains dependencies for a Mule app. When you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to this connector. The Mule runtime engine translates the `RELEASE` dependency keyword to the current version.

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-sap-connector</artifactId>
  <version>RELEASE</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

To obtain the most up-to-date `pom.xml` file information, access the connector in https://www.mulesoft.com/exchange/[Anypoint Exchange] and click *Dependency Snippets*.

== Next Step

After completing your namespace and `pom.xml` file, you can try out xref:azure-service-bus-management-connector-examples.adoc[Azure Service Bus Management Examples].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
