= Azure Service Bus Management Design Center Configuration - Mule 4

Design Center enables you to create apps visually. To use Design Center, work with your Anypoint Platform administrator to ensure that you have a xref:access-management::environments.adoc#to-create-a-new-environment[Design environment]. For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour]. Design Center automatically saves all changes.

To create an app in Design Center:

* Configure the input source (trigger) for your app.
* Add the connector as a component to process the input for the app.

For information on Design Center field values, see the xref:azure-service-bus-management-connector-reference.adoc[Azure Service Bus Management Connector Reference].

== Configure the Input Source Trigger

. In Design Center, click *Create*.
. Click *Create new application*.
. Specify a value for *Project name*, and click *Create*.
. Exit from *Let's get started* by clicking *Go straight to canvas*.
. Click on the trigger card.
. If you are using your connector as an input source trigger, search for the connector; otherwise, you can use HTTP or Scheduler.
. Complete these fields: <list fields and values>
. Click off the trigger card to save the configuration.

== Configure the Target Component

. Click “+” next to the trigger card.
. In *Select a component*, search for the connector name.
. Select the connector name. 
. Select an operation for the connector.
. Complete these fields: <list fields and values>
. Click the *Test* button to test the connection. 

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]

