= Azure Service Bus Management Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Microsoft Azure Service Bus Management (Azure Service Bus Management Connector) enables management integration with Azure Service Bus on the cloud. This connector connects to the Azure REST API and supports management operations for queues, topics, subscriptions. In addition, you can use the built-in management API to discover Azure Service Bus objects automatically and to provision them.

For compatibility information, see the xref:release-notes::connector/<connector>.adoc[Azure Service Bus Management Connector Release Notes].

== Prerequisites

To use this connector, you must be familiar with:

* The Microsoft Azure REST API
* Anypoint connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to:

* The Microsoft Azure target resource
* Anypoint Studio version 4.2 or later

== Common Use Cases For the Connector

Common use cases for this connector include:

* Creating, modifying, deleting a queue, topic, and subscription
* Retrieve all queues, topics, and subscriptions from the service bus instance

For examples, see xref:azure-service-bus-management-connector-examples.adoc[Examples].

== Audience

* New user
+
To create your Mule app, see:

* xref:azure-service-bus-management-connector-studio.adoc[Use Studio to Configure Microsoft Azure Connector]
* The xref:azure-service-bus-management-connector-examples.adoc[Examples], which provide one or more use cases for the connector.
+
* Advanced user
+
* Read the following:

* xref:azure-service-bus-management-connector-xml-maven.adoc[XML and Maven Support]
* xref:azure-service-bus-management-connector-examples.adoc[Microsoft Azure Service Bus Management Examples] topics


////
Include this section only if Exchange provides templates, examples, or both for the connector. If there are templates and not examples, or vice versa, reword the section as applicable.
////

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as a starting point for your app, as well as examples that illustrate a complete solution.

////List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////
== Next Step
After you complete the prerequisites and experiment with templates and examples, you are ready to create an app and configure the connector using xref:azure-service-bus-management-connector-studio.adoc[Anypoint Studio].

== See Also
xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
<link to the connector in Exchange>
https://help.mulesoft.com[MuleSoft Help Center]
