= Salesforce Marketing Cloud REST Connector 1.2 - Mule 4



Anypoint Connector for Salesforce Marketing Cloud REST (Salesforce Marketing Cloud REST Connector) enables you to integrate with the Salesforce Marketing Cloud marketing platform. This connector exposes operations provided by the Salesforce Marketing Cloud REST API.

For information about compatibility and fixed issues, refer to the Salesforce Marketing Cloud REST Connector Release Notes.

== Before You Begin

To use this connector, you must be familiar with:

* The Salesforce Marketing Cloud REST API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Salesforce Marketing Cloud REST target resource
* Anypoint Platform
* Anypoint Studio version 7.3.5 or later

== Connection Types

Salesforce Marketing Cloud REST connections use the OAuth Client Credentials authentication type, which enables a client to use its own credentials.

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:salesforce-marketing-cloud-rest-connector-reference.adoc[Salesforce Marketing Cloud REST Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
