= Troubleshoot Email Connector - Mule 4

To troubleshoot Anypoint Connector for Email Connector, become familiar with the information about app logs, Javamail debugging, troubleshooting access attachments, troubleshooting protocols behaviours issues, and interpreting commonly thrown messages.

== View the App Log

To check for problems, you can view the app log as follows:

. If you’re running the app from Anypoint Platform, the output is visible in the Anypoint Studio console window.

. If you’re running the app using Mule from the command line, the app log is visible in your OS console.

Unless the log file path is customized in the app’s log file (log4j2.xml), you can also view the app log in the default location MULE_HOME/logs/<app-name>.log.


== Enable JavaMail Debuging

You can enable JavaMail Debuging Loggin which is used by the underlying 3rd party classes. 


For that you must add `<property key="mail.debug" value="true"/>` on the IMAP/SMTP connection element. 
To enable Email logging:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/mule` path folder.
. Open your Mule app xml file inside the folder.
. Add `<property key="mail.debug" value="true"/>` on the IMAP/SMTP connection element. 

[source,xml,linenums]
----
  <email:imaps-connection host="..." user="..." password="..." >
    <email:properties >
      <email:property key="mail.debug" value="true" />
    </email:properties>
  </email:imaps-connection>
----

. Save your changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.
. Navigate to the *Console* view to read the Email messages in the logger:

Example:
[source,plain-text]
----
DEBUG: JavaMail version 1.6.3
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: getProvider() returning javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle]
DEBUG IMAP: mail.imap.fetchsize: 16384
DEBUG IMAP: mail.imap.ignorebodystructuresize: false
DEBUG IMAP: trying to connect to host "******", port 993, isSSL true
* OK The Microsoft Exchange IMAP4 service is ready. [******]
A0 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
A0 OK CAPABILITY completed.
...
----

The debug lines will be printed to standard output. Meaning, the console if the application is executed inside Studio, or the log file if you run the application in a standalone Mule Runtime.


== Enable Email Connector's Debug Logging

To begin troubleshooting Email Connector, you can enable debug logging to see the exact error messages and its trace.

To enable Email Connector's Debug logging:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. If the following line is already in the `log4j2.xml` file, uncomment it to enable it; otherwise, add it:

[source,xml,linenums]
----
<AsyncLogger name="org.mule.extension.email" level="DEBUG" />
----
+
. Save your changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.
. Navigate to the *Console* view to read the Email Connector's messages in the logger:

Example:
[source,plain-text]
----
DEBUG 2021-04-26 18:51:08,536 [_pollingSource_imapattachmentFlow/executor.01] [processor: ; event: ] org.mule.extension.email.internal.mailbox.BaseMailboxPollingSource: Poll will be skipped, since last poll emails are still being processed
INFO  2021-04-26 18:51:09,166 [[MuleRuntime].uber.04: [imapattachment].imapattachmentFlow.CPU_LITE @111719e0] [processor: imapattachmentFlow/processors/1/processors/2; event: 820f7fe0-a6d9-11eb-a84b-147dda4dba09] org.mule.runtime.core.internal.processor.LoggerMessageProcessor: "" as Binary {base: "64"}
DEBUG 2021-04-26 18:51:15,360 [_pollingSource_imapattachmentFlow/executor.01] [processor: ; event: ] org.mule.extension.email.internal.mailbox.BaseMailboxPollingSource: Email [172] was not processed.
....
----


== SMTPS and Gmail Connection Issues

The method that you use to troubleshoot SMTPS connection issues depends on whether or not your Gmail account uses two-factor authentication:

=== Two-factor authentication

If your account uses two-factor authentication value generate an app-specific password and use that instead of your normal password.
See https://support.google.com/accounts/answer/185833[Sign in Using App Password] for details. You do not need to enable *Less Secure Apps* in your Gmail account.

=== Password based authentication

If your Gmail account does not use two-factor authentication, set up and enable *Less Secure Apps* in your Gmail account, and if your password does not work, go to https://accounts.google.com/b/0/DisplayUnlockCaptcha[Allow Access to Your Google Account] and follow these steps:

. Enter your username and password.

. Enter the letters on the captcha screen.

. Return to your Mule app and rerun the flow.


== Differences in the behavior of the different protocols

If your problem is about the behavior of each protocol, we recommend you check the RFC documents.  A Request for Comments (RFC) is a publication from the Internet Society (ISOC) and its associated bodies, most prominently the Internet Engineering Task Force (IETF), the principal technical development and standards-setting bodies for the Internet. The IETF adopts some of the proposals published as RFCs as Internet Standards.
Some documents that you could check are:

* https://tools.ietf.org/html/rfc5322[RFC-5322 - Internet Message Format]
* https://tools.ietf.org/html/rfc1064[RFC-1064 - IMAP2 - INTERACTIVE MAIL ACCESS PROTOCOL - VERSION 2]
* https://tools.ietf.org/html/rfc1939[RFC-1939 - POP3 - Post Office Protocol - Version 3]
* https://tools.ietf.org/html/rfc5321[RFC-5321 - SMTP - Simple Mail Transfer Protocol]
* https://tools.ietf.org/html/rfc2045[RFC-2045 - MIME - Multipurpose Internet Mail Extensions Part One: Format of Internet Message Bodies]


== Understand Common Throws

Here is a list of common throw messages and how to interpret them.

* EMAIL:EMAIL_NOT_FOUND

  Indicates that the email with the emailId provided couldn't be found in a mailbox folder.

* EMAIL:ACCESSING_FOLDER

  Indicates that there was a problem accessing an email folder or the folder doesn´t exist.

* EMAIL:CONNECTIVITY

  Indicates that a problem occurred and a connection could not be established.

* EMAIL:RETRY_EXHAUSTED

  Indicates that a problem occurred when routing a message.

* EMAIL:EMAIL_LIST

  Indicates that an error occurred trying to list emails.

* EMAIL:SEND

  Indicates that an exception occurred trying to send an Email.

* EMAIL:FETCHING_ATTRIBUTES

  Indicates that there was an error while parsing attributes from an email.

* EMAIL:MARK

  Indicates that there was an error while marking email flags.

* EMAIL:EXPUNGE_ERROR

  Indicates that there was an error while deleting emails from folder.

* EMAIL:ATTACHMENT

  Indicates that there was an error while sending attachment.

* EMAIL:READ_EMAIL

  Indicates that there was an error reading email content.

* EMAIL:AUTHENTICATION

  Indicates that there was an authentication failure.

* EMAIL:INVALID_CREDENTIALS

  Indicates that it cannot checks the consistency of the username and password parameters.ß

* EMAIL:UNKNOWN_HOST

  Indicates that the IP address of a host could not be determined or port out of range.

* EMAIL:CONNECTION_TIMEOUT

  Indicates that there was an error because the server took too long to reply to a data request.

* EMAIL:DISCONNECTED

  Indicates that there was an error connecting to the store or the connection was interrupted.

* EMAIL:SSL_ERROR

  Indicates that there was an error creating SSL context or TLS context wasn't configured properly.


== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* https://www.mulesoft.com/exchange/org.mule.connectors/mule-email-connector/[Email Connector - Mule 4]
* xref:email-documentation.adoc[Email Connector Reference]
* https://tools.ietf.org/html/rfc5322[RFC-5322 - Internet Message Format]
* https://tools.ietf.org/html/rfc1064[RFC-1064 - IMAP2 - INTERACTIVE MAIL ACCESS PROTOCOL - VERSION 2]
* https://tools.ietf.org/html/rfc1939[RFC-1939 - POP3 - Post Office Protocol - Version 3]
* https://tools.ietf.org/html/rfc5321[RFC-5321 - SMTP - Simple Mail Transfer Protocol]
* https://tools.ietf.org/html/rfc2045[RFC-2045 - MIME - Multipurpose Internet Mail Extensions Part One: Format of Internet Message Bodies]

