= Email Connector 1.4 - Mule 4
:page-aliases: connectors::email/email-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Email (Email Connector) sends and retrieves email messages over standard email protocols. Email Connector configurations share a basic set of parameters that require a connection over the protocols you use.

For compatibility information and fixed issues, see the Email Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have access to Anypoint Platform and Anypoint Studio.


== Common Use Cases for the Connector

Email Connector enables you to:

* Retrieve emails from POP3 mailboxes
* Retrieve, delete, and store emails from IMAP mailboxes
* Send emails over the SMTP protocol
* Support secure connections for all protocols over Transport Layer Security (TLS)

For examples, see xref:email-examples.adoc[Examples].

== Audience

* New users, read:
** xref:email-studio-configuration.adoc[Use Studio to Configure the Connector] to create your Mule app
** xref:email-examples.adoc[Examples], which provide one or more use cases for the connector
* Advanced users, read:
** xref:email-xml-maven.adoc[XML and Maven Support]
** xref:email-examples.adoc[Examples], which provides one or more use cases for the connector


== Next Step

After you complete the prerequisites and try the templates and examples, you are ready to create your own app and configure the connector using xref:email-studio-configuration.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
