= AS2 - Studio Configuration - Mule 4


To configure a connector in Anypoint Studio:

. Install the connector.
. Configure the connector.
. Configure an input source for the connector.

== Add the Connector to a Studio Project

Anypoint Studio provides two ways to add the connector to your Studio project:
from the Exchange button in the Studio taskbar or from the Mule Palette view.

=== Add the Connector Using Exchange

. In Studio, create a Mule project.
. Click the Exchange icon *(X)* in the upper-left of the Studio task bar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for "as2".
. Select the connector and click *Add to project*.
. Follow the prompts to install the connector.

=== Add the Connector in Studio

. In Studio, create a Mule project.
. In the Mule Palette view, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type "as2" in the search field.
. Click this connector's name in *Available modules*.
. Click *Add*.
. Click *Finish*.

== Configure an Input Source
Configure an input source for the connector such as an operation for
the AS2 connector, *HTTP Listener*, or *Scheduler*.
You can put the following operations for the connector in
the *Source* area of the Studio canvas.
// List of operations that can be an input source (from Design Center)

== Configure the Connector

The AS2 Connector reads data using repeatable streams. Data is read into memory until a configurable threshold is reached, at which point the data is written to disk.
The default threshold for writing to disk is 64 KB. You can change this by using the system property `com.mulesoft.connectors.as2.CachedOutputStream.Threshold`.
This property requires an integer value:

** A positive value defines the maximum amount of data to read into memory in KB.

** A zero value means that all data is written directly to disk.

** A value of -1 means that the data is never written to disk, and is stored into memory.

By default, the data is written to temporary files in the directory set by `java.io.tmpdir`.
To change the directory, set the System property `com.mulesoft.connectors.as2.CachedOutputStream.OutputDirectory`.


== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
