= Introduction to Anypoint Connectors
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/


== What are Anypoint Connectors

Anypoint Connectors are extensions of Mule that let you work with external systems such as Salesforce, SAP, ServiceNow, Workday, and more to send and receive information from the backend systems to create something new.

Anypoint Connectors let you connect Mule apps to APIs and resources. You can use connectors within your Mule apps to send and receive data over a protocol, or to and from an API.

You can create Mule apps in Anypoint Studio or Flow Designer.

== How Anypoint Connectors Work

When you add a connector to the start of a flow, it’s known as a message processor or "trigger" because it starts the Mule flow by receiving information from the connector’s resource. For example, when a Salesforce user updates a sales opportunity, the connector application can receive the information and direct it to a database or to another connector for processing.

You can also use the HTTP connector as a message processor so that users can send information to your Studio application using a web browser, Postman, or the curl command.

You can also use different operations from the same connector in a project. One operation can receive data, another can process the data.

In addition, Exchange provides templates and examples that let you jumpstart application development.

== Common Use Cases

== Connector Support Categories

=== MuleSoft Certified

MuleSoft Certified connectors are developed by MuleSoft’s partners and developer community and are reviewed and certified by MuleSoft. For support, customers should contact the MuleSoft partner that created the MuleSoft Certified connector.

=== Select

MuleSoft maintains Select connectors. Connectors included in the open source Mule distribution can be used by everyone, however support is only included in an Anypoint Platform subscription. To use all other Select Connectors and access support, you must have an active Anypoint Platform subscription.

=== Premium

MuleSoft maintains Premium connectors. You must purchase Premium connectors as add-ons to your subscription.



