= Tableau Connector - Mule 4
:keywords: Tableau
:imagesdir: images
:page-aliases: connectors::tableau/tableau-user-manual.adoc
:toc: macro
:toclevels: 2

Anypoint Connector for Tableau Online (Tableau Connector) enables integration with the Tableau REST API.

This connector enables you to perform operations to:

* Authorize or unauthorize server access
* Create or replace datasources with defined structure
* Add data to existing datasources

Release Notes: xref:release-notes::connector/tableau-connector-release-notes-mule-4.adoc[Tableau Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-tableau-connector/[Tableau Connector]

== Prerequisites

Before creating an app, you must have access to the Tableau server instance and
Anypoint Platform. You also must understand how to create a Mule app using
Design Center or Anypoint Studio.

Before starting:

You need access to a Tableau instance which enables you to create credentials needed for Tableau connector authentication.
To create Tableau personal access token please follow the action steps described here: https://help.tableau.com/v2019.4/pro/desktop/en-us/useracct.htm#create-and-revoke-personal-access-tokens


== Common Use Cases for the Connector

Common use cases for Tableau Connector include creating or replacing datasource with specified structure, adding data to existing datasources.
 For an example of these use cases, see xref:tableau-connector-examples.adoc[Tableau Examples].


 == Audience

* New users, read:
** xref:tableau-connector-studio.adoc[Use Studio to Configure the Connector] to create your Mule app
** xref:tableau-connector-examples.adoc[Examples], which provides an example use case for the connector
* Advanced users, read:
** xref:tableau-connector-xml-maven.adoc[XML and Maven Support]
** xref:tableau-connector-examples.adoc[Examples], which provides an example use case for the connector

== Authentication Types

Tableau Connector supports:

* *Personal Token  Authentication* +
Personal access tokens provide Tableau users the ability to create long-lived authentication tokens.
Tokens consist of personal access token name and personal access token secret. 


== Next Step

After you have met the prerequisites and experimented with templates and examples, you are ready to create an app with xref:tableau-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
