= Trello Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Trello provides ...

For information about compatibility and fixed issues, see the Trello Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Trello API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to:

* The Trello target resource
* Anypoint Platform
* Anypoint Studio version <x.x> or later
*// If your connector has other prerequisites specific to this connector, list them here.

== Common Use Cases For the Connector

These are some common use cases for Trello Connector...

== Connection Types

Trello connections use token-based authentication. Each Trello user is given an API key, which enables the user to generate a token. A user then passes his or her API key and token in the URL for each request.

== Next Step

After you complete the prerequisites and try the templates and examples, you are ready to create an app and configure the connector using xref:trello-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
