// Landing Page Topic

////
Set connector-specific values for the following variables:

* {connector-name} - Name of the connector without the word "Connector." For example, Redis.
* {version} - Connector version. For example, 1.0.
* {lc-connector-name} - Lower case connector name to use in the links in the Next Steps and See Also sections. For example, redis.
* {studio-version} - Studio version to use in the Before You Begin section. For example, 4.1.1
////
:connector-name: <value>
:version: <value>
:lc-connector-name: <value>
:studio-version: <value>

= {connector-name} Connector {version} - Mule 4

////
Anypoint Connector for <connector-name> provides ...
 
For information about compatibility and fixed issues, see the <connector-name> Connector Release Notes.
 
For a major or minor release, see xref:connector-template-files-connector-upgrade-migrate.adoc[Upgrading and Migrating-{connector-name}-Connector to <major or minor version> - Mule 4].
////

== Before You Begin

include::connectors::partial$t-index-partial.adoc[tags=prerequisites]

== Common Use Cases for the Connector

// Make the title singular if there is just one use case

// Add a lead in sentence and then list common use cases for the connector
These are some common use cases for {connector-name} Connector...

For examples of these use cases, see xref:{lc-connector-name}-connector-examples.adoc[{connector-name} Connector Examples].

== Connection Types

////
If there is one authentication type, use the following format:
{connector-name} Connector connections use the <authentication-type> authentication type, which ... <add a brief description of the authentication type like the descriptions below>.
If there is more than one authentication type, use a list like the one shown below (use only the applicable connection types--delete the others):
{connector-name} connections use the following authentication types:
* Basic authentication +
Uses a username and password for authentication
* OAuth +
Uses access tokens provided by the authorization server to get access to protected data
* OAuth2 +
Delegates user authentication to the service hosting the user account
Kerberos +
Uses the Kerberos principal as the username. The keytab path you specify obtains a ticket-granting ticket (TGT) from the authorization server.
////

For information about configuring authentication types, see xref:{lc-connector-name}-connector-studio.adoc#configure-global-element[Configure a Global Element for the Connector].

////
Include the following section only if Exchange provides templates, examples, or both for the connector. If there are templates and not examples, or vice versa, reword the section as applicable.
== Exchange Templates and Examples
https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as a starting point for your app, as well as examples that illustrate a complete solution.
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////

== Next Step

include::connectors::partial$t-index-partial.adoc[tags=next-step]

== See Also

// You can add additional see also links before this include, if applicable.

include::connectors::partial$t-index-partial.adoc[tags=see-also]