= <Connector name> Connector <version> - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]
// If this is a Premium connector, change Select to Premium

include::connectors::partial$t-index-partial.adoc[tags=prerequisites]


== Common Use Cases For the Connector
// Make the title singular if there is just one use case

// Add a lead in sentence and then list common use cases for the connector
These are some common use cases for <Connector name> Connector...

For examples of these use cases, see xref:connector-template-files-connector-examples.adoc[<Connector name> Connector Examples].

== Connection Types

// If there is one authentication type, use the following format:

<Connector name> connections use the <authentication-type> authentication type, which ... <add a brief description of the authentication type like the descriptions below>.

////
If there is more than one authentication type, use a list like the one shown below (use only the applicable connection types--delete the others):

<Connector name> connections use the following authentication types:

* Basic authentication +
Uses a username and password for authentication
* OAuth +
Uses access tokens provided by the authorization server to get access to protected data
* OAuth2 +
Delegates user authentication to the service hosting the user account
Kerberos +
Uses the Kerberos principal as the username. The keytab path you specify obtains a ticket-granting ticket (TGT) from the authorization server.
////

For information about configuring authentication types, see xref:connector-template-files-connector-studio.adoc#configure-global-element[Configure a Global Element for the Connector].

////
Include the following section only if Exchange provides templates, examples, or both for the connector. If there are templates and not examples, or vice versa, reword the section as applicable.
////

== Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as a starting point for your app, as well as examples that illustrate a complete solution.

////
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////

== Next Step

include::connectors::partial$t-index-partial.adoc[tags=next-step]

== See Also

//You can add additional see also links before this include, if applicable.
include::connectors::partial$t-index-partial.adoc[tags=see-also]
