= Upgrading and Migrating Salesforce Connector to 11.x - Mule 4
:page-aliases: connectors::salesforce/salesforce-connector-100-upgrade-migrate.adoc


Upgrade Anypoint Connector for Salesforce (Salesforce Connector) from version 10.x to version 11.0.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|10.x |11.0
|===

== Changes

=== 11.0

This release contains the following changes:

* Added support for *OAuth Client Credentials* configuration.
* Removed the *Subscribe Channel Listener* source. Use *Replay Channel Listener* instead.
* Removed the *Subscribe Topic Listener* source. Use *Replay Topic Listener* instead.
* Removed the deprecated *Query Result Stream* operation. Use both of the following operations instead:
** *Query Result List* to return a list of result IDs for a specific batch.
** *Query Result Stream by Id* to return an InputStream with the query results for a specific result ID of a submitted BatchInfo.
 

=== 10.22

* The *Update Metadata* operation now updates the `valueSettings` metadata type as intended.

=== 10.21

* Salesforce Connector now supports Salesforce API v61.0.

=== 10.20

* Salesforce Connector now supports Salesforce API v60.0.

=== 10.19

* Salesforce Connector now supports Salesforce API v59.0.

=== 10.18

* Salesforce Connector now supports Salesforce API v58.0.

=== 10.17

* Salesforce Connector now supports Salesforce API v57.0.

=== 10.16

* Salesforce Connector now supports Salesforce API v56.0.

=== 10.15

* Added support for Salesforce API v55.0.

=== 10.14

* Added support for Salesforce API v54.0.
* Added the *Cache events in memory* advanced option for *Replay Topic Listener* and *Replay Channel Listener* to reduce daily limit consumption.

=== 10.13

* Added support for Salesforce API v53.0.
* Added the *Query Xml Stream* operation due to a limitation in the *Query* operation. The *Query* operation is now deprecated.

=== 10.12

* Added support for Salesforce API v52.0.

=== 10.11

* The *Query Result Stream* operation is deprecated. Use both of the following new operations instead:
** *Query Result List* to return a list of result IDs for a specific batch.
** *Query Result Stream by Id* to return an InputStream with the query results for a specific result ID of a submitted BatchInfo.

=== 10.10

Added the optional Assignment Rule Id field to the Create Job Bulk Api V2 operation.

=== 10.9

* Added the Login Request Timeout field and Login Request Time Unit field to all of the connection types
* Deprecated the *The Size (in Bytes) of the Event Queue* field in the Replay Channel Listener source
* Added the following fields to the Lead Convert Request type:
** Owner Id
** Related Person Account Id
** Related Person Account Record

=== 10.8

For fixed issues, see the Salesforce Connector 10.8 Release Notes.

=== 10.7

* Improved the performance when using the Sources with the `Continue from Last Replay Id` option.

=== 10.6

* Added a new advanced parameter, Throw Exception When Organization Daily Limit Exceeded, which enables the connector to throw an exception if the limit is exceeded at deployment time.
* Enhanced logging messages for the Streaming sources.

=== 10.5

This release contains the following changes:

* Added support for Salesforce API v50.0.
* The Create job bulk Api V2 and Create Query Job Bulk Api V2 operations now support the `Sforce-Call-Options` header to specify a default namespace.
* The Create Job Bulk Api V2 operation now supports the `hardDelete` value in the `Operation` field.
* The Batch Result Stream operation now supports specifying an output MIME type based on the content type provided when creating the batch.

=== 10.4

This release contains the following changes:

* The Retrieve Job Unprocessed Results BulkV2 operation added
* The Retrieve Job Failed Results BulkV2 and Retrieve Job Successful Results BulkV2 operations now return the original fields of the records
* Logging improvements over all operations and connection types
* The Subscribe Streaming Channel and Replay Streaming Channel sources now display all types of events available in the configured organization:
** Generic Events
** Platform Events
** Change Data Capture Events

=== 10.3

This release contains the following changes:

* Added support for Salesforce API v49.0.
* Added the Merge Multiple operation to enable merging up to 200 records in a single SOAP call.

=== 10.2

This release contains the following changes:

* Added support for multiple keys in the JKS file specified for the SAML and JWT authentication mechanisms. Use the new Certificate Alias field to specify which certificate should be used. (CONN-6019, CONN-6020)
* Added support for custom headers for the Invoke APEX SOAP operation. (SE-15884)
* Bulk API V2 operations now return the response headers and status as message attributes.

=== 10.1

This release contains the following changes:

* Added support for API v48.0.
* Added support for subscribing to these newly-added platform events: FOStatusChangedEvent, OrderSummaryCreatedEvent, and OrderSumStatusChangedEvent.
* Added support for using the new RecordVisibilityContext clause when using the WITH filteringExpression in a query.

=== 10.0

This release contains the following changes:

* Removed deprecated connection types
* Made the following changes to some operations:
 ** Merged multiple operations into one
 ** Renamed some operations and parameters
 ** Changed some operation return types
* Redesigned the Replay ID functionality
* Changed the Mule TLS Context usage
* Improved the error types
* Removed the dependency on the Dozer library
* Removed the keep alive feature as a configurable option
+
The connector now automatically performs one API call every
14 minutes (Salesforce minimum TTL is 15 minutes), so the session no longer expires.

=== Changes in Connection Types

Salesforce Connector 11.x contains the following changes to connection types:

* Added support for *OAuth Client Credentials* configuration.

== Changed Operations, Sources, Parameters, and Return Types

In Salesforce Connector 11.x, contains the following changes to operation types:

|===

== Changes in Operations Metadata

There are no changes related to keys, input metadata, or output metadata.

== Removed Operations

The following operations were removed from Salesforce Connector 11.x:

//[cols="15%,35%,15%]
|===
|Removed Operation |Functionality Covered By

| Query Result Stream | Query Result List and Query Result Stream by Id

|===

== Removed Sources

The following sources were removed from Salesforce Connector 11.x:

//[cols="15%,35%,15%]
|===
|Removed Source |Functionality Covered By

| Subscribe Channel Listener | Replay Channel Listener
| Subscribe Topic Listener | Replay Topic Listener

|===


== Upgrade Prerequisites

Before you perform the upgrade, you must:

. Create a backup of your files, data, and configuration in case you need to restore to the previous version.
. Install Salesforce Connector 11.x to replace the Salesforce operations that were previously included in Salesforce Connector 10.x.

== Upgrade Steps

Follow these steps to perform the upgrade from Salesforce Connector v10.x to Salesforce Connector v11.x:

. In Anypoint Studio, create a Mule project.
. In the Mule Palette view, click *Search in Exchange*.
. In the *Add Dependencies to Project* window, enter `Salesforce` in the search field.
. In the *Available modules* section, select *Salesforce Connector - Mule 4* and click *Add*.
. Click *Finish*.
. Verify that the `salesforce-connector` dependency version is `11.x.x` in the `pom.xml` file, where `x.x` is the minor release and patch version number. For example, if you are upgrading to v11.0, the dependency version in the `pom.xml` file should be `11.0.0`.

Studio upgrades the connector automatically.


== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Check the project `pom.xml` file and verify that there are no problems.
. Test the connection and verify that the operations work.

== Troubleshooting

If there are problems with caching the parameters and caching the metadata, try restarting Studio.

== Revert the Upgrade

If it is necessary to revert to the previous version of Salesforce Connector, change the `salesforce-connector` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
