= Set Parsing Text File Attachment as Body Message
:keywords: anypoint, connectors, transports

When Anypoint Connector for Email (Email Connector) receives a message without body and only an attachment file with Content-Type as `text`, the attachment file is not processed as a separate file instead the file is included in the message body as plain text.
Mule apps can use this behavior to receive the data in the message body instead of as an attachment file.

To change the behavior of parsing attached text files when the file is the only content in the message, you can set the system property `parsing.text.attachment.as.body` to either any of these values:

* `true` (default) +
Preserves the previous behavior and converts the text file attachment in the body message.
* `false` +
Adds the attachment text file to the attachment list in the payload.

To learn how to set system properties in Anypoint Studio or for On-Premises deployments, refer to the xref:mule-runtime::mule-app-properties-system.adoc[system properties] documentation.

== Jakarta Mail System Properties

Email Connector uses internally the Jakarta Mail library, thereby you can change how the connector behaves on certain aspects by changing specific Jakarta Mail system properties. Refer to the xref:email-troubleshooting.adoc[troubleshoot MIME Types and MIME Multipart issues] section that covers some of the most consulted Jakarta Mail system properties.

For precise and updated information on these system properties, refer to the Jakarta Mail documentation.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
