= Troubleshoot Email Connector - Mule 4

To troubleshoot Anypoint Connector for Email (Email Connector), become familiar with the information about app logs, JavaMail debugging, troubleshooting access attachments, troubleshooting protocols issues, and interpreting commonly thrown messages.

== View the App Log

If you encounter problems while running your Mule runtime engine (Mule) app, view the app log as follows:

* If you’re running the app from Anypoint Platform, the output is visible in the Anypoint Studio console window.
* If you’re running the app using Mule from the command line, the app log is visible in your OS console.

Unless the log file path is customized in the app’s log file `log4j2.xml`, view the app log in the default location `MULE_HOME/logs/<app-name>.log`.


== Enable JavaMail Debug Logging

JavaMail debugging logging is used by underlying third-party classes.

To enable JavaMail debugging logging:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/mule` path folder.
. Open your Mule app XML file inside the folder.
. Add the `<property key="mail.debug" value="true"/>` to the IMAP or SMTP connection element.
+
[source,xml,linenums]
----
  <email:imaps-connection host="..." user="..." password="..." >
    <email:properties >
      <email:property key="mail.debug" value="true" />
    </email:properties>
  </email:imaps-connection>
----
+
[start=6]
. Save your changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.
. Navigate to the *Console* view to read the email messages in the logger:
+
[source,plain-text]
----
DEBUG: JavaMail version 1.6.3
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: getProvider() returning javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle]
DEBUG IMAP: mail.imap.fetchsize: 16384
DEBUG IMAP: mail.imap.ignorebodystructuresize: false
DEBUG IMAP: trying to connect to host "******", port 993, isSSL true
* OK The Microsoft Exchange IMAP4 service is ready. [******]
A0 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
A0 OK CAPABILITY completed.
...
----

If you run the app in Anypoint Studio, the logging prints the debug lines in the console view. +
If you run the app in a standalone Mule, the logging prints the debug lines in the log file.


== Enable Email Connector Debug Logging

To begin troubleshooting Email Connector, enable debug logging to see the exact error messages:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. If the following line is already in the `log4j2.xml` file, uncomment it to enable it; otherwise, add it:
+
[source,xml,linenums]
----
<AsyncLogger name="org.mule.extension.email" level="DEBUG" />
----
+
[start=6]
. Save your changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.
. Navigate to the *Console* view to read the Email Connector's messages in the logger:
+
[source,plain-text]
----
DEBUG 2021-04-26 18:51:08,536 [_pollingSource_imapattachmentFlow/executor.01] [processor: ; event: ] org.mule.extension.email.internal.mailbox.BaseMailboxPollingSource: Poll will be skipped, since last poll emails are still being processed
INFO  2021-04-26 18:51:09,166 [[MuleRuntime].uber.04: [imapattachment].imapattachmentFlow.CPU_LITE @111719e0] [processor: imapattachmentFlow/processors/1/processors/2; event: 820f7fe0-a6d9-11eb-a84b-147dda4dba09] org.mule.runtime.core.internal.processor.LoggerMessageProcessor: "" as Binary {base: "64"}
DEBUG 2021-04-26 18:51:15,360 [_pollingSource_imapattachmentFlow/executor.01] [processor: ; event: ] org.mule.extension.email.internal.mailbox.BaseMailboxPollingSource: Email [172] was not processed.
....
----

== Troubleshoot Attachment Issues
When a message only has one mimetype part with an attachment and no body, and its Content Type is part of text family, the email-connector publish that text content as payload body. If you want to receive it in the payload attachments list, you must set the parsing.text.attachment.as.body properties to false. (See more about System Properties on xref:email-documentation.adoc[Email Connector Reference])

== Troubleshoot MimeTypes Issues
Email Connector uses the java.mail library, for that, you can affect some aspect behavior.

Several System properties control strict conformance to the MIME spec. Note that these are not session properties but must be set globally as System properties.

* *mail.mime.decodetext.strict*: This property controls decoding of MIME encoded words. The MIME spec requires that encoded words start at the beginning of a whitespace separated word. Some mailers incorrectly include encoded words in the middle of a word. If the mail.mime.decodetext.strict System property is set to "false", an attempt will be made to decode these illegal encoded words. The default is true.

* *mail.mime.encodeeol.strict*: This property controls the choice of Content-Transfer-Encoding for MIME parts that are not of type "text". Often such parts will contain textual data for which an encoding that allows normal end of line conventions is appropriate. In rare cases, such a part will appear to contain entirely textual data, but will require an encoding that preserves CR and LF characters without change. If the mail.mime.encodeeol.strict System property is set to "true", such an encoding will be used when necessary. The default is false.

* *mail.mime.charset*: This property can be used to specify the default MIME charset to use for encoded words and text parts that don't otherwise specify a charset. Normally, the default MIME charset is derived from the default Java charset, as specified in the file.encoding System property. Most applications will have no need to explicitly set the default MIME charset. In cases where the default MIME charset to be used for mail messages is different than the charset used for files stored on the system, this property should be set.

* *mail.mime.ignoreunknownencoding*: This property controls whether unknown values in the Content-Transfer-Encoding header, as passed to the decode method, cause an exception. If set to "true", unknown values are ignored and 8bit encoding is assumed. Otherwise, unknown values cause a MessagingException to be thrown.

== Troubleshoot MimeMultipart Issues

* *mail.mime.multipart.ignoremissingendboundary*: This property may be set to false to cause a MessagingException to be thrown if the multipart data does not end with the required end boundary line. If this property is set to true or not set, missing end boundaries are not considered an error and the final body part ends at the end of the data.

* *mail.mime.multipart.ignoremissingboundaryparameter*: This System property may be set to false to cause a MessagingException to be thrown if the Content-Type of the MimeMultipart does not include a boundary parameter. If this property is set to true or not set, the multipart parsing code will look for a line that looks like a bounary line and use that as the boundary separating the parts.

* *mail.mime.multipart.ignoreexistingboundaryparameter*: This System property may be set to true to cause any boundary to be ignored and instead search for a boundary line in the message as with mail.mime.multipart.ignoremissingboundaryparameter.

* *mail.mime.multipart.allowempty*: Normally, when writing out a MimeMultipart that contains no body parts, or when trying to parse a multipart message with no body parts, a MessagingException is thrown. The MIME spec does not allow multipart content with no body parts. The mail.mime.multipart.allowempty System property may be set to true to override this behavior. When writing out such a MimeMultipart, a single empty part will be included. When reading such a multipart, a MimeMultipart will be created with no body parts.

== Troubleshoot SMTPS and Gmail Connection Issues

The method that you use to troubleshoot SMTPS connection issues depends on whether or not your Gmail account uses two-factor authentication:

=== Two-Factor Authentication

If your account uses two-factor authentication value, generate an app-specific password and use that instead of your normal password.
See https://support.google.com/accounts/answer/185833[Sign in Using App Password] for details. You do not need to enable *Less Secure Apps* in your Gmail account.

=== Password-Based Authentication

If your Gmail account does not use two-factor authentication, set up and enable *Less Secure Apps* in your Gmail account, and if your password does not work, go to https://accounts.google.com/b/0/DisplayUnlockCaptcha[Allow Access to Your Google Account] and follow these steps:

. Enter your username and password.
. Enter the letters on the captcha screen.
. Return to your Mule app and rerun the flow.


== Understand the Behavior of the Different Protocols

If your problem is protocol behavior, check the RFC documents. A Request for Comments (RFC) is a publication from the Internet Society (ISOC) and its associated bodies, most prominently the Internet Engineering Task Force (IETF), the principal technical development and standards-setting bodies for the internet. The IETF adopts some of the proposals published as RFCs as internet standards.
Some documents that you can check are:

* https://tools.ietf.org/html/rfc5322[RFC-5322 - Internet Message Format]
* https://tools.ietf.org/html/rfc1064[RFC-1064 - IMAP2 - INTERACTIVE MAIL ACCESS PROTOCOL - VERSION 2]
* https://tools.ietf.org/html/rfc1939[RFC-1939 - POP3 - Post Office Protocol - Version 3]
* https://tools.ietf.org/html/rfc5321[RFC-5321 - SMTP - Simple Mail Transfer Protocol]
* https://tools.ietf.org/html/rfc2045[RFC-2045 - MIME - Multipurpose Internet Mail Extensions Part One: Format of Internet Message Bodies]


== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* EMAIL:EMAIL_NOT_FOUND

  The email identified by `emailId` cannot be found in a mailbox folder.

* EMAIL:ACCESSING_FOLDER

  There was a problem accessing an email folder or the folder does not exist.

* EMAIL:CONNECTIVITY

  A connection could not be established.

* EMAIL:RETRY_EXHAUSTED

  A problem occurred during message routing.

* EMAIL:EMAIL_LIST

  An error occurred during an attempt to list emails.

* EMAIL:SEND

  An exception occurred during an attempt to send an email.

* EMAIL:FETCHING_ATTRIBUTES

  An error occurred during email attribute parsing from an email.

* EMAIL:MARK

  An error occurred during email flag marking.

* EMAIL:EXPUNGE_ERROR

  A error occurred during an attempt to delete emails from a folder.

* EMAIL:ATTACHMENT

  An error occurred during an attempt to send an attachment.

* EMAIL:READ_EMAIL

  An error occurred during an attempt to read the email content.

* EMAIL:AUTHENTICATION

  Authentication failed.

* EMAIL:INVALID_CREDENTIALS

  An error occurred during the username and password parameter consistency check.

* EMAIL:UNKNOWN_HOST

  The IP address of a host cannot be determined or a port is out of range.

* EMAIL:CONNECTION_TIMEOUT

  The server took too long to reply to a data request.

* EMAIL:DISCONNECTED

  An error occurred during store connecting, or the connection was interrupted.

* EMAIL:SSL_ERROR

  An error occurred during SSL context creation, or the TLS context wasn't properly configured.


== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
* xref:email-documentation.adoc[Email Connector Reference]
