= Configuring Chat Operations

== Configure the Chat Answer Prompt Operation

The *Chat answer prompt* operation sends a request to the configured LLM. This operation uses a plain text prompt as input and responds with a plain text answer.

. Select the operation on the Anypoint Code Builder or Studio canvas.
. In the *General* properties tab for the operation, enter plain text for the *Prompt*.
include::connectors::partial$einstein-ai-chat-config-properties-partial.adoc[]

This is the XML configuration for this operation:

[source,xml]
----
<mac-einstein:chat-answer-prompt 
  doc:name="Chat answer prompt" 
  doc:id="8ba9d534-f801-4ac7-8a31-11462fc5204b" 
  config-ref="MuleChain_AI_Llm_configuration" 
  prompt="#[payload.prompt]"  
/>
----

[[output-config]]
=== Output Configuration

This operation responds with a JSON payload containing the main LLM response. 

This is an example response:

[source,json]
----
{
    "response": "The capital of Switzerland is Bern. It's known for its well-preserved medieval old town, which is a UNESCO World Heritage site. Bern became the capital of Switzerland in 1848. The Swiss parliament, the Federal Assembly, is located in Bern."
}
----

The operation also returns attributes that aren't within the main JSON payload, which include information about token usage, for example:

[source,json]
----
{
  "tokenUsage": {
      "outputCount": 9,
      "totalCount": 18,
      "inputCount": 9
  },
  "additionalAttributes": {}
}
----

== Configure the Chat Generate from Messages Operation

The *Chat generate from messages* operation is a prompt request operation with provided messages to the configured LLM. It uses a plain text prompt as input and responds with a plain text answer.

. Select the operation on the Anypoint Code Builder or Studio canvas.
. In the *General* properties tab for the operation, enter plain text for the *Messages*.
include::connectors::partial$einstein-ai-chat-config-properties-partial.adoc[]

This is the configuration XML for this operation:

[source,xml]
----
<mac-einstein:chat-generate-from-messages 
  doc:name="Chat generate from messages" 
  doc:id="94fa27f3-18ce-436c-8a5f-10b8dbfa4ea3" 
  config-ref="Einstein_AI" 
  messages="#[payload.messages]"
/>
----

== Configure the Chat Answer Prompt With Memory Operation

The *Chat answer prompt with memory* operation is useful for retaining conversation history for a multi-user chat operation.

To configure the *Chat answer prompt with memory* operation:

include::connectors::partial$t-configure-operations.adoc[]
* *Prompt*
+
Contains the prompt for the operation.
* *Memory Path* 
+
Path to the in-memory database for storing the conversation history. 
+
You can also use a DataWeave expression for this field, for example: 
+
`#["/Users/john.wick/Desktop/mac-demo/db/" ++ payload.memoryName].`
* *Memory name*
+
Name of the conversation. For multi-user support, enter the unique user ID.
* *Keep last messages*
+
Maximum number of messages to remember for the conversation defined in *Memory name*.
include::connectors::partial$einstein-ai-chat-config-properties-partial.adoc[]

This is the XML configuration for this operation:

[source,xml]
----
<mac-einstein:chat-answer-prompt-with-memory 
  doc:name="Chat answer prompt with memory" 
  doc:id="a1d7d0e0-a568-4824-9849-6f1ff03d6dee" 
  config-ref="Einstein_AI" 
  prompt="#[payload.prompt]" 
  memoryPath="#[payload.memoryPath]" 
  memoryName="#[payload.memoryName]" 
  keepLastMessages="#[payload.lastMessages]"
/>
----

=== Output Configuration

This operation responds with a JSON payload containing the main LLM response, with additional metadata stored in attributes.

This is an example response:

[source,json]
----
{
    "response": "I'm sorry, I do not have access to personal information such as your name."
}
----

The operation also returns attributes that aren't within the main JSON payload, which include information about token usage, for example:

[source,json]
----
{
  "tokenUsage": {
    "outputCount": 13,
    "totalCount": 44,
    "inputCount": 31
  },
  "additionalAttributes": {
    "memoryName": "memory",
    "maxMessages": "2",
    "dbFilePath": "/.../memory.db"
  }
}
----

== See Also

* xref:connectors::introduction/intro-config-use-acb.adoc[]
* xref:index.adoc[Einstein AI Connector Overview]
* xref:einstein-ai-connector-reference.adoc[Einstein AI Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
