= Einstein AI Connector 1.0 - Mule 4
:lc-connector-name: einstein-ai

Anypoint Connector for Einstein AI (Einstein AI Connector)  applications.

Einstein AI Connector supports these operations, which are categorized into:

* Agent
* Chat
* Embeddings
* RAG

For information about compatibility and fixed issues, see the Einstein AI Connector release notes.
 
== Before You Begin

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Code Builder or Anypoint Studio

Before creating an app, you must have:

* Java 8 or 17
* Apache Maven
* Credentials to access the Einstein Connector target resource
* Anypoint Platform
* The latest versions of Anypoint Code Builder or Anypoint Studio

== Common Use Cases for the Connector

=== Agent Operations

Some common use cases for Agent operations include:

* Customer Service Agents
+
Enhance customer service by providing case summaries, case classifications, large dataset summaries, and more.
* Sales Operation Agents
+
Assist sales teams in writing sales emails, summarizing cases for specific accounts, assessing the probability of closing deals, and more.
* Marketing Agents
+
Support marketing teams in generating product descriptions, creating newsletters, planning social media campaigns, and more.

=== Chat Operations

Some common use cases for Chat operations include: 

* Basic chatbots that answer simple user prompts.
* Customer service queries that provide direct answers to frequently asked questions.
* Customer support chats that retain the context of the ongoing support conversations.
* Multi-user chat applications that maintain the conversation history for different users.
* Personal assistants that keep track of user interactions to provide more relevant responses.

=== Embeddings Operations

Some common use cases for Embeddings operations include:

* Creating a new in-memory vector store for storing document embeddings.
* Exporting an in-memory embedding to a physical file for persistence across sessions.
* Querying a knowledge store with a plain text prompt and receiving a refined response powered by an LLM.
* Retrieving and interpreting data from documents in an embedding store, with enhanced context from the LLM.
* Adding documents, such as PDFs and text files, into an embedding store for future retrieval.
* Adding a folder for documents, such as PDFs and text files, into an embedding store for future retrieval.
* Ingesting documents from a specific directory into an in-memory embedding store for contextual analysis.
* Querying a vector store for specific information using semantic search.
* Retrieving multiple relevant documents or text segments from an embedding store based on a given prompt.

=== RAG Operations

Use Retrieval-Augmented Generation (RAG) operations to retrieve information from a document based on a plain text prompt. 

Some common use cases for Retrieval-Augmented Generation (RAG) operations include:

* Knowledge Management
+
Extract specific information from documents stored in a knowledge base.
* Customer Support 
+
Retrieve relevant data from customer service documents to assist with inquiries.
* Research
+
Access information from research papers or documents based on specific queries.


== Next Step

include::connectors::partial$t-index-partial.adoc[tags=next-step]

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-config-use-acb.adoc[]
* xref:connectors::introduction/intro-config-use-studio.adoc[Using Studio to Configure a Connector]
* xref:einstein-ai-connector-reference.adoc[Einstein AI Connector Reference]
* xref:einstein-ai-additional-config.adoc[Einstein AI Connector - Additional Configuration Information]
* https://help.mulesoft.com[MuleSoft Help Center]