= SAP S/4HANA OData Connector 2.3 - Mule 4
:page-aliases: connectors::sap/sap-s4hana-cloud-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Premium]

Anypoint Connector for SAP S/4HANA OData (SAP S/4HANA OData Connector) provides support for the OData APIs exposed by SAP S/4HANA Cloud and SAP S/4HANA on-premise.

The connector enables you to perform operations to:

* Create, get, update, and delete entities
* Retrieve a single entity
* Query multiple entities
* Invoke a remote function
* Execute batch requests that consist of multiple requests

For software requirements and compatibility
information, see the SAP S4/HANA Connector Release Notes.

include::connectors::partial$prerequisites-partial.adoc[]
* Have a developer account or other valid SAP S4HANA instance

== Common Use Case for the Connector

Perform CRUD operations on entity types of SAP S/4HANA's OData API and process the response.

== Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
you can use as a starting point for your app, as well as examples that illustrate a complete solution.

== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app with xref:sap-s4hana-cloud-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:release-notes::connector/sap-s4-hana-connector-release-notes-mule-4.adoc[SAP S/4HANA OData Connector Release Notes]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-sap-s4hana-cloud-connector/[SAP S/4HANA OData Connector on Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
