= Web Service Consumer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: core, connector, Web service consumer, WSS, service, consumer, wsdl, soap

The Web Service Consumer (WSC) connector consumes a SOAP Web service
to acquire data from an external source. In many cases, you can use an existing MuleSoft connector, such as Workday or Service Now, to connect to a service provider. However, when no connector available for a specific Web service, the easiest way to consume the service from a Mule app is to use the Web Service Consumer connector.

The main features of this connector include:

* Consuming DOC Literal Web services.
* SOAP multipart messages.
* SOAP Headers.
* DataSense support for SOAP Headers, SOAP Body, and Attachment.
* Embedded DataWeave transformations inside the operation.
* Support and Unified experience for SOAP with attachments and MTOM handling.
* Custom HTTP configuration as transport (Runtime and Design Time).
* WS Securities support.

== See Also

* xref:web-service/web-service-consumer-reference.adoc[Web Service Consumer Technical Reference]
* xref:web-service/web-service-consumer-configure.adoc[To Configure the WSC]
* xref:web-service/web-service-consumer-consume.adoc[To Consume a Service]


NOTE: RPC WSDLs are not supported by the Web Service Consumer.