= Azure Data Lake Storage Examples - Mule 4

The following examples will show you how to create a file system, create a path, and upload a file to a path, and implement a simple flow that handles errors, with the Azure Data Lake Storage Connector:

- <<create-file-system-example,Create a file system>>. This flow will teach you how to create a file system, using the Azure Data Lake Storage connector.

- <<create-path-example,Create a path in a file system>>. This flow will teach you how to create a path inside a file system, using the Azure Data Lake Storage connector.

- <<update-path-example,Update a path in a file system>>. This flow will teach you how to update a path inside a file system, using the Azure Data Lake Storage connector.

- <<error-handling-example,Error handling example>>. This flow will show you a little example on how to implement error handling with the Azure Data Lake Storage connector.

These examples use variables for some field values. You can either:

* Replace the variables with their values in the code
* Provide the values for each variable in a properties file and then refer to that file from the connector configuration.

If you don’t know how to use a properties file, see Configuring Property Placeholders.

If you wanna see more detailed examples or use cases, check all the *demos* we have available <link-to-demos>

[[create-file-system-example]]
== Creating a File System

=== Steps for creating a file system

==== Setting up the flow:
. Create a new Mule project in Studio.
. In the *Mule Palette* view, search for `http` and select the *Listener* operation:
. Drag the *Listener* operation onto the Studio canvas.
. In the *Listener* configuration, click *+* next to the *Connector configuration* field to add a global element.
. Accept the defaults.
. Set the *Path* field to `/create-fs`

==== Filling values for create file system operation:
. In the Mule Palette view, search for azure and select the Azure Data Lake Storage Connector *Create File System* operation.
. Drag the *Create File System* operation from the Studio canvas into the Listener flow.
. In the *Create File System* configuration, click *+* next to the Connector Configuration field to add a Connection Config.
. Choose your connection and fill all the required values.
. Save the configuration.
. Fill the field `File System` with your desired file system name.
. Save the project.
. Test the app by sending a GET request to `localhost:8081/create-fs`.

=== XML for creating a file system

Paste this code into your Studio XML editor to quickly load the flow for this example into your Mule app:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:http="http://www.mulesoft.org/schema/mule/http"
xmlns:azure-data-lake-storage="http://www.mulesoft.org/schema/mule/azure-data-lake-storage"
xmlns="http://www.mulesoft.org/schema/mule/core"
xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/azure-data-lake-storage http://www.mulesoft.org/schema/mule/azure-data-lake-storage/current/mule-azure-data-lake-storage.xsd">
<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config">
<http:listener-connection host="0.0.0.0" port="8081" />
</http:listener-config>
<azure-data-lake-storage:config name="Azure_Data_Lake_Storage_Connector_Config" doc:name="Azure Data Lake Storage Connector Config">
<azure-data-lake-storage:shared-access-signature-connection accountName="${account.name}" dnsSuffix="${dns.suffix}" sasToken="${sas.token}" />
</azure-data-lake-storage:config>
<flow name="create-file-system-flow">
<http:listener doc:name="Listener" config-ref="HTTP_Listener_config" path="create-fs"/>
<azure-data-lake-storage:create-file-system doc:name="Create File System" config-ref="Azure_Data_Lake_Storage_Connector_Config" filesystem="newfilesystem"/>
</flow>

</mule>
----
For more information, see the *Create File System DEMO*. <link-to-demo>

[[create-path-example]]
== Create Path

=== Steps for creating a path

==== Setting up the flow
. Create a new Mule project in Studio.
. In the *Mule Palette* view, search for `http` and select the *Listener* operation:
. Drag the *Listener* operation onto the Studio canvas.
. In the *Listener* configuration, click *+* next to the *Connector configuration* field to add a global element.
. Accept the defaults.
. Set the *Path* field to `/create-path`

==== Filling values for create path operation:
. In the Mule Palette view, search for azure and select the Azure Data Lake Storage Connector *Create/Rename Path* operation.
. Drag the *Create/Rename Path* operation from the Studio canvas into the Listener flow.
. In the *Create/Rename Path* configuration, click *+* next to the Connector Configuration field to add a Connection Config.
. Choose your connection and fill all the required values.
. Save the configuration.
. Fill the field `File System` with your target file system. Take in mind that the file system must exists, or else it will throw an error.
. Fill the field `Path` with your desired path name.
. Fill the field `Resource` with either "file" or "directory".
. Save the project.
. Test the app by sending a GET request to `localhost:8081/create-path`.

=== XML for creating a path
Paste this code into your Studio XML editor to quickly load the flow for this example into your Mule app:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:azure-data-lake-storage="http://www.mulesoft.org/schema/mule/azure-data-lake-storage"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
		http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
		http://www.mulesoft.org/schema/mule/azure-data-lake-storage http://www.mulesoft.org/schema/mule/azure-data-lake-storage/current/mule-azure-data-lake-storage.xsd">
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config">
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<azure-data-lake-storage:config name="Azure_Data_Lake_Storage_Connector_Config" doc:name="Azure Data Lake Storage Connector Config">
		<azure-data-lake-storage:shared-access-signature-connection accountName="${account.name}" dnsSuffix="${dns.suffix}" sasToken="${sas.token}" />
	</azure-data-lake-storage:config>
	<flow name="create-path-flow">
		<http:listener doc:name="Listener" config-ref="HTTP_Listener_config" path="create-path"/>
		<azure-data-lake-storage:create-or-rename doc:name="Create/Rename Path" config-ref="Azure_Data_Lake_Storage_Connector_Config" fileSystem="newfilesystem" path="newpath" resource="directory"/>
	</flow>

</mule>
----
For more information, see the *Path CRUD DEMO*. <link-to-demo>

[[update-path-example]]
== Update Path

=== Steps for Updating a path

==== Setting up the flow
. Create a new Mule project in Studio.
. In the *Mule Palette* view, search for `http` and select the *Listener* operation:
. Drag the *Listener* operation onto the Studio canvas.
. In the *Listener* configuration, click *+* next to the *Connector configuration* field to add a global element.
. Accept the defaults.
. Set the *Path* field to `/update-path`

==== Adding File Connector to the project:
. In the Mule Palette view, click on *Search in Exchange*. Then type `file connector` and add it to the project.

==== Using the File Connector to read a file:
. In the Mule Palette, click on *File* and drag the *Read* operation into the flow.
. In the *Read* configuration, click *+* next to the Connector Configuration field to add a Connection Config.
. In *File Path*, fill the value with the absolute path to the file that you want to upload.
. Drag a *Set Variable* from the Mule Palette view, and put it next to the *Read* operation.
. Fill the name as `fileSize` and the value must be the *Mule Expression* `#[attributes.size]`. This will save the length of the file for the next operations.

==== Using the Update Path operation for append:
. In the Mule Palette view, search for azure and select the Azure Data Lake Storage Connector *Update Path* operation.
. Drag the *Update Path* operation from the Studio canvas into the Listener flow, next to the *Set Variable* box.
. In the *Update Path* configuration, click *+* next to the Connector Configuration field to add a Connection Config.
. Choose your connection and fill all the required values.
. Save the configuration.
. Fill the field `File System` with your target file system.
. Fill the field `Path` with your target path.
. Fill the field `Action` with `append`.
. Fill the field `Position` with the value `0`.
. Fill the field `Content Length` with the *Mule Expression* `#[vars.fileSize]`.
. The `Content` field must be `payload`.

==== Using the Update Path operation for flush:
. In the Mule Palette view, search for azure and select the Azure Data Lake Storage Connector *Update Path* operation.
. Drag the *Update Path* operation from the Studio canvas into the Listener flow, next to the *Update Path* box that we just created in the step for append.
. Choose your connection.
. Fill the field `File System` with your target file system.
. Fill the field `Path` with your target path.
. Fill the field `Action` with `flush`.
. Fill the field `Position` with the *Mule Expression* `#[vars.fileSize]`.
. Fill the field `Content Length` with the value `0`.

==== Finishing up:
. Save the project.
. Test the app by sending a GET request to `localhost:8081/update-path`.

=== XML for updating a path

Paste this code into your Studio XML editor to quickly load the flow for this example into your Mule app:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:azure-data-lake-storage="http://www.mulesoft.org/schema/mule/azure-data-lake-storage"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="
		http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
		http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
		http://www.mulesoft.org/schema/mule/azure-data-lake-storage http://www.mulesoft.org/schema/mule/azure-data-lake-storage/current/mule-azure-data-lake-storage.xsd
http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd">
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config">
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<azure-data-lake-storage:config name="Azure_Data_Lake_Storage_Connector_Config" doc:name="Azure Data Lake Storage Connector Config">
		<azure-data-lake-storage:shared-access-signature-connection accountName="${account.name}" dnsSuffix="${dns.suffix}" sasToken="${sas.token}" />
	</azure-data-lake-storage:config>
	<file:config name="File_Config" doc:name="File Config"/>
	<flow name="create-path-flow">
		<http:listener doc:name="Listener" config-ref="HTTP_Listener_config" path="update-path"/>
		<file:read doc:name="Read" config-ref="File_Config" path="${file.path}"/>
		<set-variable value="#[attributes.size]" doc:name="Set Variable" variableName="fileSize"/>
		<azure-data-lake-storage:update-path doc:name="Update Path" config-ref="Azure_Data_Lake_Storage_Connector_Config" fileSystem="${filesystem.name}" path="${path.name}" action="append" position="0" contentLength="#[vars.fileSize]"/>
		<azure-data-lake-storage:update-path doc:name="Update Path" config-ref="Azure_Data_Lake_Storage_Connector_Config" fileSystem="${filesystem.name}" path="${path.name}" action="flush" position="#[vars.fileSize]" contentLength="0"/>
	</flow>

</mule>
----

For more information, see the *Path CRUD DEMO*. <link-to-demo>


[[error-handling-example]]
== Error Handling

This section will teach you how to implement a simple error handling on a flow that uses Azure Data Lake Storage Connector

=== Setting up the error handling flow
. In any flow, drag from  "*Mule Palette* -> *Core*" the object *On Error Continue* and drag it to the *Error Handling* section of the flow
. From the Mule Palette, drag from "*Mule Palette* -> *Core*" a Transform Message, and fill it with the following values:

 output application/json
 ---
 error.errorMessage.payload

. Then, if you want to access to the *error code* that comes from the Azure service, the expression is:

 error.muleMessage.typedValue.error.code

. And if you want to access to the *error message*, the expression is:

 error.muleMessage.typedValue.error.message

== See Also

* xref:connectors::introduction/anypoint-connector-authentication.adoc[Anypoint Connector Authentication]
* https://help.mulesoft.com[MuleSoft Help Center]
