= Azure Data Lake Storage Connector - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]


Anypoint Connector for Azure Data Lake Storage (Azure Data Lake Storage Connector) enables integration with Azure Data Lake using its Gen2 REST API.

For information about compatibility and fixed issues, see Azure Data Lake Storage Connector Release Notes. 

== Prerequisites

To use this connector, you must be familiar with:

* Azure Data Lake Gen2 API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to:

* The Azure Data Lake target resource
* Anypoint Platform
* Anypoint Studio version 7.1 or later


== Common Use Cases For the Connector

Common use cases for Azure Data Lake Storage Connector include the following: 

* Create, read, update, and delete files in an existing Azure Data Lake file system.
* Create, rename, and delete directories from the Azure Data Lake file system.
* Rename existing files. 
* Append the contents of a file and flush the file's contents.
* Obtain properties and status for a file or directory.
* Obtain the ACL (access control list) of a file or directory.
* Get a list of all the available paths in the file system.

For examples of some of these common use cases, see xref:azure-data-lake-connector-examples.adoc[Examples].

== Audience

* New user
+
To create your Mule app, see:

* xref:azure-data-lake-connector-studio.adoc[Studio Configuration] 
* xref:azure-data-lake-connector-examples.adoc[Examples], with use case information for the connector
+
* Advanced user
+
* Read the following: 

* xref:azure-data-lake-connector-xml-maven.adoc[XML and Maven Support]
* xref:azure-data-lake-connector-examples.adoc[Examples], with use case information for the connector

== Connection Types

Azure Data Lake Storage Connector connections use the following authentication types:

* Azure Active Directory OAuth 2.0 Connection Provider +
Delegates user authentication to the service hosting the user account
* Shared Access Signature +
Information contained in the SAS token is used to authorize the client request
* Shared Key Connection +
Uses a shared access key that is generated by Azure and used for the storage account

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:azure-data-lake-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:azure-data-lake-connector-reference.adoc[Azure Data Lake Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
