= Azure Data Lake Storage Connector - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]


Anypoint Connector for Azure Data Lake Storage (Azure Data Lake Storage Connector) enables integration with Azure Data Lake using its Gen2 REST API.

For information about compatibility and fixed issues, see Azure Data Lake Storage Connector Release Notes. 

== Prerequisites

To use this connector, you must be familiar with:

* Azure Data Lake Gen2 API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to:

* The Azure Data Lake target resource
* Anypoint Platform
* Anypoint Studio version 7.1 or later


== Common Use Cases For the Connector

These are some common use cases for Azure Data Lake Connector:  

== Audience

* New user
+
To create your Mule app, see:

* xref:azure-data-lake-connector-studio.adoc[Studio Configuration] 
* xref:azure-data-lake-connector-config-topics.adoc[Additional Configuration Information]
to help extend your understanding of Azure Data Lake Storage Connector 
* xref:azure-data-lake-connector-examples.adoc[Examples], with use case information for the connector
+
* Advanced user
+
* Read the following: 

* xref:azure-data-lake-connector-xml-maven.adoc[XML and Maven Support]
* xref:azure-data-lake-connector-config-topics.adoc[Additional Configuration Information]
* xref:azure-data-lake-connector-examples.adoc[Examples], with use case information for the connector

// The following line is only needed for connectors with upgrade information

For a major or minor release, see
xref:azure-data-lake-connector-upgrade-migrate.adoc[Upgrade and Migrate].

== Connection Types

Azure Data Lake Storage Connector connections use the following authentication types:

* OAuth 2.0 Connection Provider +
Delegates user authentication to the service hosting the user account
* Share Access Signature
* Shared Key Connection

For information about configuring authentication types, see xref:azure-data-lake-studio.adoc[Use Studio to Configure Azure Data Lake Storage Connector].

== Next Step

After you complete the prerequisites and try the templates and examples, you are ready to create an app and configure the connector using xref:azure-data-lake-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
