= Database Connector Troubleshooting - Mule 4

To troubleshoot Anypoint Connector for Database (Database Connector), review the following issue and possible solution.

== Pooling Profiles Connections Making the Flow Hang
Using a pooling profile that provides fewer connections than the flow requires can make the entire flow hang.

=== Solution
One solution is to increase the size of the pool. However, sometimes that's not possible, so another solution is to use Anypoint Connector for Virtual Machine (VM Connector) to shorten the life of the connection to match the life of a VM message. This way, every call to the *Stored procedure* operation is executed, its result is consumed, and the connection associated with the operation is closed and returned to the pool.

The following example shows how to use pooling profiles with the *Stored procedure* operation and VM Connector. In this example, When the `foreach` element reaches the eleventh iteration, the *Stored procedure* operation doesn't hang, because the pool is able to provide a connection:

[source,xml,linenums]
----
	<db:config name="Database_Config">
		<db:generic-connection url="someUrl" user="someUser" password="somePassword" driverClassName="someDriver">
			<db:pooling-profile maxPoolSize="10">
			</db:pooling-profile>
		</db:generic-connection>
	</db:config>

	<vm:config name="VM_Config">
		<vm:queues >
			<vm:queue queueName="testQueue" />
		</vm:queues>
	</vm:config>

	<flow name="processingFlow">
		<foreach collection="#[1 to 11]">
			<logger level="INFO" message="#['Starting Iteration ' ++ payload as String]" />
			<vm:publish config-ref="VM_Config" queueName="testQueue"/>
			<logger level="INFO" message="#['Finishing Iteration ' ++ payload as String]"/>
		</foreach>
	</flow>

	<flow name="coolFlow">
		<vm:listener config-ref="VM_Config" queueName="testQueue" numberOfConsumers="1"/>
		<db:stored-procedure config-ref="Database_Config">
				<db:sql><![CDATA[{call testProc2()}]]></db:sql>
			</db:stored-procedure>
		<logger level="INFO" message="#[output application/json --- payload.resultSet1]" />
	</flow>
----

== Snowflake JDBC Driver Throws Exception for Stored Procedure

Some drivers have their own specifications when calling stored procedures. When you set the callable statement with curly brackets `{` and `}` for the Snowflake JDBC driver, for example:

`{call doubleMyInt(:myInt)}`

Running the application, causes the Snowflake JDBC driver to throw the exception:

`net.snowflake.client.jdbc.SnowflakeSQLException: Unsupported feature 'call'`


=== Solution

For Snowflake JDBC driver set the callable statement without the curly brackets `{` and `}`:

`call doubleMyInt(:myInt)`

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
