= Database Connector Troubleshooting - Mule 4

The Anypoint Connector for Database (Database Connector) follows the standards and guidelines detailed by the JDBC 4.2 library (bundled with the Java SE JDK 1.8).

To troubleshoot the Database Connector, review the following sections for help performing general troubleshooting, addressing specific common errors, and interpreting commonly thrown messages.

== Enabling verbose logging
There are two options to do so, manually changing the log4j file or through Anypoint Runtime Manager (the only way if you are using Cloudhub APIs).
	
	1. Changing log4j file:

		1.a.  Modify the log4j2.xml file of your project and inside "Logger" tag, add an special "AsyncLogger" this way:

[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="org.mule.extension.db" level="DEBUG"/>
				...
			</Loggers>
----


		1.b.  Save your project and deploy the new version

	2. Changing logs from Anypoint Runtime Manager:

		2.a. Go to the API configuration
		2.b. Under "Logging" sub-tab, add the "<package>" at DEBUG level (replace the package with the corresponding one explained before point 1)
		2.c. Apply changes

Remember to always disable the enhanced verbosity after troubleshooting since it will affect your MuleApp performance.

== Pooling Profiles Connections Making the Flow Hang
Using a pooling profile that provides fewer connections than the flow requires can make the entire flow hang.

=== Solution
One solution is to increase the size of the pool. However, sometimes that's not possible, so another solution is to use Anypoint Connector for Virtual Machine (VM Connector) to shorten the life of the connection to match the life of a VM message. This way, every call to the *Stored procedure* operation is executed, its result is consumed, and the connection associated with the operation is closed and returned to the pool.

The following example shows how to use pooling profiles with the *Stored procedure* operation and VM Connector. In this example, When the `foreach` element reaches the eleventh iteration, the *Stored procedure* operation doesn't hang, because the pool is able to provide a connection:

[source,xml,linenums]
----
	<db:config name="Database_Config">
		<db:generic-connection url="someUrl" user="someUser" password="somePassword" driverClassName="someDriver">
			<db:pooling-profile maxPoolSize="10">
			</db:pooling-profile>
		</db:generic-connection>
	</db:config>

	<vm:config name="VM_Config">
		<vm:queues >
			<vm:queue queueName="testQueue" />
		</vm:queues>
	</vm:config>

	<flow name="processingFlow">
		<foreach collection="#[1 to 11]">
			<logger level="INFO" message="#['Starting Iteration ' ++ payload as String]" />
			<vm:publish config-ref="VM_Config" queueName="testQueue"/>
			<logger level="INFO" message="#['Finishing Iteration ' ++ payload as String]"/>
		</foreach>
	</flow>

	<flow name="coolFlow">
		<vm:listener config-ref="VM_Config" queueName="testQueue" numberOfConsumers="1"/>
		<db:stored-procedure config-ref="Database_Config">
				<db:sql><![CDATA[{call testProc2()}]]></db:sql>
			</db:stored-procedure>
		<logger level="INFO" message="#[output application/json --- payload.resultSet1]" />
	</flow>
----

== Snowflake JDBC Driver Throws an Exception for a Stored Procedure

Some drivers have their own specifications when calling stored procedures. Running the application when you set the callable statement with curly brackets (`{` and `}`), for example, `{call doubleMyInt(:myInt)}`, causes the Snowflake JDBC driver to throw the following exception:

`net.snowflake.client.jdbc.SnowflakeSQLException: Unsupported feature 'call'`


=== Solution
For Snowflake JDBC driver, set the callable statement without the curly brackets `{` and `}`, for example:

`call doubleMyInt(:myInt)`


== Database Connector Exceptions

=== CONNECTIVITY
This is the generic error for a connectivity issue with the Database. This error shows up on badly configured connections, no Database response while waiting results or fetching rows, lost of Database connection, and similars.

=== INVALID_CREDENTIALS
This shows up when the Database rejects the provided credentials.

=== INVALID_DATABASE
This shows up when the connection to the RDBMS was established, but the Database doesn't exist.

=== CANNOT_REACH
This shows up when the Connector can not establish a connection with the RDBMS.

=== CANNOT_LOAD_DRIVER
This shows up when the Connector could not load the JDBC driver.

=== BAD_SQL_SYNTAX
This shows up when the provided SQL query has bad syntax.

=== QUERY_EXECUTION
This shows up when there was an error executing the query.

=== RETRY_EXHAUSTED
Though not a Database Connector error, this shows up when all reconnection attempts have failed.


== See Also

https://help.mulesoft.com[MuleSoft Help Center]
