= Execute Bulk Operations Examples - Mule 4

Anypoint Connector for Database (Database Connector) supports the Bulk Insert, Bulk Update, and Bulk Delete operations that enables you to manage data in bulk. This improves the performance compared to executing a single insert, update or delete operation at various times.

These operations are similar as their single counterparts, except that instead of receiving input parameters as key-value pairs, the bulk operations expect a list of key-value pairs. Avoid unnecessary steps by doing a bulk operation,

* Parse the query only once
* Require only one database connection since a single statement is executed
* Minimize network overhead
* RDBMS can execute the bulk operation

While some statements in the bulk operation can be successfully executed, some can result in an error (for example, if thee Bulk Insert fails to insert 1 out of 100 rows, a single exception is thrown describing what went wrong). It will be up to the driver to either stop the execution immediately and ignore all the remaining operations, or continue to execute the remaining statements.
In both cases, whenever an error occurs examining the application logs provide details on what caused the failure.

== Configure the Bulk Insert Operation in Studio

. In your Studio flow, select the *Bulk insert* operation.
. In the connector configuration screen, set the *SQL Query Text* field to the query to execute, for example:

//Add XML code sample here


[source,xml,linenums]
----
<db:bulk-insert config-ref="dbConfig" >
  <db:bulk-input-parameters>
    #[[{'id': 2, 'name': 'George', 'lastName': 'Costanza'}, {'id': 3, 'name': 'Cosmo', 'lastName': 'Kramer'}]]
  </db:bulk-input-parameters>
  <db:sql>
    insert into customers (id, name, lastName) values (:id, :name, :lastName)
  </db:sql>
</db:bulk-insert>
----

== Configure the Bulk Update Operation in Studio

In your Studio flow, select the *Bulk update* operation.
. In the connector configuration screen, set the *SQL Query Text* field to the query to execute, for example:

//Add XML code sample here

The same concept applies for update. If you use `UPDATE PRODUCTS set PRICE = PRICE * 0.9 where PRICE > :price`, you may want to apply a 10% discount on many products, but the `price` input parameter accepts only one value.

If you want to apply different discount rates on products that have different prices, you can execute many operations.

The following example is a payload that is a list of objects of the following structure `{ price : number, discountRate: number}`:

[source,xml,linenums]
----
<foreach>
  <db:update config-ref="dbConfig">
    <db:input-parameters>
     #[
      {
        'discountRate' : payload.discountRate,
        'price' : payload.price,
      }
    ]
    </db:input-parameters>
    <db:sql>
      UPDATE PRODUCTS set PRICE = PRICE * :discountRate where PRICE > :price
    </db:sql>
  </db:update>
</foreach>
----


== Configure the Bulk Delete Operation in Studio

. In your Studio flow, select the *Bulk delete* operation.
. In the connector configuration screen, set the *SQL Query Text* field to the query to execute, for example:

//Add XML code sample here

//If you don't use bulk operations, when performing a `delete` operation, many rows could match the criteria and get deleted if only one criteria `(POSITION = X)` is provided.

== See also

xref:database-connector-examples.adoc[]
