= SendGrid Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for SendGrid (SendGrid Connector ) enables you to connect to the SendGrid REST API.

For information about compatibility and fixed issues, see the SendGrid Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The SendGrid Connector's API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to:

* The SendGrid target resource
* Anypoint Platform
* Anypoint Studio version 4.2.1 or later

== Common Use Cases For the Connector

Common use cases for SendGrid Connector include the following:



== Authentication Types

SendGrid connections can use the following authentication types:



== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
