= Configure Driver Visibility using Mule Maven Plugin

Although Anypoint Studio enables you to configure database driver dependencies without problems in most cases, there are some scenarios where you must use the Mule Maven Plugin to properly set up the driver classes' visibility because of class loading isolation mechanisms.

== Configure Driver Visibility Across the Application

To configure additional database driver dependencies and make the driver visible across components within your Mule application, refer to the xref:mule-runtime::mmp-concept.adoc#configure-shared-libraries[Configure Shared Libraries] section in the Mule Maven Plugin documentation.

== Configure Driver Visibility Only for the Connector

When there is a risk of dependencies colliding and it's necessary to have the Database Connector and the driver's dependencies in the same class loader, to make the driver visible only for the connector, refer to the xref:mule-runtime::mmp-concept.adoc#configure-plugin-dependencies[Configure Additional Plugin Dependencies] section in the Mule Maven Plugin documentation.


[NOTE]
Be aware of which component must establish the connection with the database, as the driver must be in the scope of that component's class loader. For example, if a Mule application uses a datasource reference connection and targets a Spring bean datasource definition, it is the Spring's class loader that requires the database library, not the database. Configure additional application dependencies using _shared libraries_.


== See Also

* xref:mule-runtime::mmp-concept.adoc[Mule Maven Plugin]
* xref:database-documentation.adoc[Database Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
