= Using Anypoint Studio to Configure MuleSoft WebCrawler Connector 1.0
:exchange-search-name: mulesoft webcrawler
:connector-name: MuleSoft WebCrawler
:lc-connector-name: mulesoft-webcrawler
:studio-connector-name: MuleSoft WebCrawler Connector

include::connectors::partial$t-studio-partial.adoc[tags=topic-intro]

[[create-mule-project]]
== Create a Mule Project

include::connectors::partial$t-studio-partial.adoc[tags=create-project-intro]

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

Add MuleSoft WebCrawler Connector to your Mule project to automatically populate the XML code with the connector's namespace and schema location and add the required dependencies to the project's `pom.xml` file:

. In *Mule Palette*, click *(X) Search in Exchange*.
. In *Add Dependencies to Project*, type `mulesoft webcrawler` in the search field.
. Click *MuleSoft WebCrawler Connector* in *Available modules*.
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio does not make that connector available to other projects in your Studio workspace.

[[configure-source]]
== Configure a Source

include::connectors::partial$t-studio-partial.adoc[tags=configure-source-intro]
You can configure one of these sources to use with MuleSoft WebCrawler Connector:

* *On Site Crawl*
+
Crawls a website starting from seed URLs, emitting each discovered page as a Mule event. Supports deduplication via an object store and URL scheduling via a VM queue.
* *HTTP Listener*
+
Initiates a flow each time it receives a request on the configured host and port.
* *Scheduler*
+
Initiates a flow when a time-based condition is met.

include::connectors::partial$t-studio-partial.adoc[tags=listener-steps]

[[add-connector-operation]]
== Add a Connector Operation to the Flow

When you add a connector operation to your flow, you are specifying an action for that connector to perform.

To add an operation for MuleSoft WebCrawler Connector, follow these steps:

. In *Mule Palette*, select *MuleSoft WebCrawler Connector* and then select the operation to add.
. Drag the operation onto the Studio canvas, next to the source.

[[configure-global-element]]
== Configure a Global Element for the Connector

When you configure a connector, configure a global element that all instances of that connector in the app can use. Configuring a global element requires you to provide the connection settings that the connector requires to access the target web resources.

To configure the global element for MuleSoft WebCrawler Connector, follow these steps:

. Select the operation in the Studio canvas.
. In the *General* configuration screen for the operation, click the *Add* icon to access the global element configuration fields.
. In the *General* tab, in *Connection*, select the connection type to configure:
* <<http>>
* <<remote-webdriver>>

+
You can reference a configuration file that contains ANT-style property placeholders (recommended), or you can enter your connection settings in the global configuration properties. For information about the benefits of using property placeholders and how to configure them, refer to xref:connectors::introduction/intro-connector-configuration-overview.adoc[Anypoint Connector Configuration].
. In the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.

[[http]]
=== HTTP

Use the HTTP connection type for crawling static web content.

Enter the following information in the *General* tab of the *Global Element Properties* screen to configure the HTTP connection:

[%header,cols="30s,70a"]
|===
|Field |User Action
|Name |Enter the configuration name.
|Connection | Select *HTTP*.
|User agent | Enter the request user-agent header (optional).
|Referrer | Enter the request referrer header (optional).
|Response timeout | Enter the response timeout value for HTTP fetches. Default is 10.
|Response timeout unit | Select the time unit for the response timeout. Default is SECONDS.
|===

Optionally configure TLS settings for secure connections in the *TLS* tab.

[[remote-webdriver]]
=== Remote WebDriver

Use the Remote WebDriver connection type for crawling dynamic web content that requires JavaScript rendering.

Enter the following information in the *General* tab of the *Global Element Properties* screen to configure the Remote WebDriver connection:

[%header,cols="30s,70a"]
|===
|Field |User Action
|Name |Enter the configuration name.
|Connection | Select *Remote WebDriver*.
|Remote WebDriver URL | Enter the URL of the remote Selenium WebDriver endpoint (for example, Selenium Grid, standalone ChromeDriver, BrowserStack, or a CloudHub-hosted remote-browser app). Chromium-only (Chrome, Chromium, Edge).
|User agent | Enter the browser user-agent override (optional).
|Referrer | Enter the Referer header for navigations (optional).
|===

[[configure-crawler-options]]
=== Configure Crawler Options

After selecting the connection type, configure the crawler options in the *General* tab:

[%header,cols="30s,70a"]
|===
|Field |User Action
|Delay between pages | Enter the delay introduced between each request. Default is 0.
|Delay time unit | Select the time unit for the delay. Default is SECONDS.
|Enforce robots.txt | Select *true* to enforce checks against the robots.txt file. Default is *false*.
|===

[[configure-page-load-options]]
=== Configure Page Load Options

Configure page load options to control how the connector waits for content. These options are especially relevant for the Remote WebDriver connection type:

[%header,cols="30s,70a"]
|===
|Field |User Action
|Wait on page load | Enter the time to wait on page load. Default is 0.
|Wait on page load unit | Select the time unit for the page-load wait. Default is SECONDS.
|Wait for XPath | Enter the XPath to wait for (not available for HTTP connection).
|Extract Shadow DOM | Select *true* to extract the Shadow DOM content (not available for HTTP connection). Default is *false*.
|Shadow Host(s) XPath | Enter the Shadow host(s) to extract by XPath (not available for HTTP connection).
|===

[[configure-other-fields]]
== Configure Additional Connector Fields

After you configure a global element for the connector, configure the other required fields. The required fields vary depending on which connector operation you use.

For detailed configuration information for each operation type, see xref:mulesoft-webcrawler-connector-additional-config.adoc[MuleSoft WebCrawler Connector - Additional Configuration Information].

[[view-app-log]]
== View the App Log

include::connectors::partial$t-studio-partial.adoc[tags=view-app-log]

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-config-use-studio.adoc[Using Studio to Configure a Connector]
* xref:{lc-connector-name}-connector-reference.adoc[MuleSoft WebCrawler Connector Reference]
* https://help.salesforce.com[Salesforce Help]
