= Using the Execution Mode

Determine whether a script is automatically compiled or forced to be interpreted using the Scripting Module *Execution Mode* field.

Configure the field in these modes:

* *AUTO* +
Uses the compiled version of the script if the compilation is possible and successful during the initialization. This mode doesn't perform a dynamic analysis of the script's content to determine whether it should switch to interpreted execution. For example, if the script contains hardcoded parameters or local values that need to be dynamic, the `AUTO` mode doesn't detect this situation and can opt for compilation, resulting in the loss of these values.
+
Therefore, `AUTO` mode applies only if there are no critical dependencies on local variables that could be lost during compilation.

* *INTERPRETED* +
Avoids issues related to variable retention.
+
Using `INTERPRETED` mode can lead to performance degradation because the script is interpreted with each execution instead of being compiled once. This mode only applies to scenarios where modifying the script to receive parameters explicitly is not feasible, as it is inherently less efficient.


This XML example shows the *Execution Mode* field (`executionMode`) configuration:

[source,xml,linenums]
----
<mule ...>
	<flow name="conn-flow" >
		<scripting:execute
engine="jruby" executionMode="INTERPRETED">
               <scripting:code>
				...
</scripting:code>
                ...
            </scripting:execute>

	</flow>
</mule>
----

== See Also 

* xref:scripting-module-examples.adoc[]
