= Upgrading and Migrating SAP SuccessFactors Connector to Version 5.0 

Upgrade Anypoint Connector for SAP SuccessFactors (SuccessFactors Connector) to version 5.x.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|4.x |5.x
|===

== Changes in This Release

SAP SuccessFactors Connector 5.0 includes these changes.

* Basic Authentication is now deprecated. 
* In OAuth SAML Bearer Assertion Authentication:
** *The private key from the X.509 certificate.* and *The authorisation url.* fields are removed.
+
For more information about how to generate a keystore file, refer to xref:sap-successfactors-connector-config-topics.adoc#generate-keystore[Generate a Keystore File].
** *Key store*, *Store password*, *Type*, and *Certificate alias* fields are added.
** *Scopes* is moved from the *Advanced* tab to the *General* tab.

== Upgrade Prerequisites

Before you perform the upgrade, you must create a backup of your files, data, and configurations in case you need to restore to them.

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `successfactors` in the search field.
. In *Available modules*, select *SuccessFactors* and click *Add*.
. Click *Finish*.
. Verify that the SAP SuccessFactors Connector dependency version is `5.0.0` in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Troubleshoot

If there are problems with caching the parameters and caching the metadata, try restarting Anypoint Studio.

=== Revert the Upgrade

If it is necessary to revert to the previous version of SAP SuccessFactors Connector, change the `sap-successfactors-connector` dependency version `5.0.0` in the project's `pom.xml` to the previous version.

You must update the project's `pom.xml` in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:sap-successfactors-connector-reference.adoc[SAP SuccessFactors Connector Reference]
* https://help.salesforce.com[Salesforce Help]
