= Trello Connector 1.1 

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Trello (Trello Connector) enables you to integrate custom applications into Trello to facilitate faster collaboration between teams. Use Trello Connector to manage Trello boards, lists, and cards.

For information about compatibility and fixed issues, see the Trello Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Trello API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to:

* The Trello target resource
* Anypoint
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Common use cases for Trello Connector include the following:

* Customer case management
+
Send customer case information managed by your support teams to your sales, development, and other teams for better and faster collaboration.
+
* Project collaboration
+
Manage key tasks for your project teams across all your IT apps (email, messaging, and calendar) in one streamlined and easy-to-use interface. This can make working across teams smoother, especially in a remote work environment.

== Connection Types

Trello connections use token-based authentication. Each Trello user is given an API key, which enables the user to generate a token. Users then pass their API key and token in the URL for each request.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
