= Azure Event Hubs Management Connector - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Azure Event Hubs Management (Azure Event Hubs Management Connector) enables you to ..

For information about compatibility and fixed issues, refer to the Azure Event Hubs Management Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Azure Event Hubs Management API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Azure Event Hubs Management target resource
* Anypoint Platform
* Anypoint Studio version 7.3.5 or later

== Connection Types

Azure Event Hubs Management Connector connections use the Shared Access Signature authentication type.

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:azure-event-hubs-management-connector-reference.adoc[Azure Event Hubs Management Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
