= Upgrading and Migrating Salesforce Commerce Cloud B2C Data Connector to Version 2.0 - Mule 4

Upgrade Anypoint Connector for Salesforce Commerce Cloud B2C Data (Salesforce Commerce Cloud B2C Data Connector) to version 2.0.

== Supported Upgrade Paths

[%header,"cols=50a,50a"]
|===
|From Version | To Version
|1.0 |2.0
|===

== Changes in This Release

* This connector is now compatible with Java 17.
* There will be no further updates or new versions to this connector. Use xref:http-connector::index.adoc[Anypoint Connector for HTTP (HTTP Connector)] instead.

== Requirements

Ensure your system meets the following compatibility requirements before you perform the upgrade:

[%header%autowidth.spread]
|===
|Software |Version
|Anypoint Studio |7 and later
|Mule runtime engine |4.6.14 and later
|OpenJDK |8, 11, and 17
|===

== Upgrade Prerequisites

Before you perform the upgrade, create a backup of your files, data, and configuration in case you need to restore to the previous version.

== Upgrade Steps

Follow these steps to perform the upgrade to version 2.0:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `b2c data` in the search field.
. In *Available modules*, select *Salesforce Commerce Cloud B2C Data* and click *Add*.
. Click *Finish*.
. Verify that the Salesforce Commerce Cloud B2C Data dependency version is 2.0 in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

== Post-Upgrade Steps

After you install the latest version of the connector, verify that your error handling is updated to work with the minor changes in error codes in this version of the connector.

== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Revert the Upgrade

If it is necessary to revert to the previous version of Salesforce Commerce Cloud B2C Data Connector, change the dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
