= Using Anypoint Studio to Configure gRPC Connector 1.0
:exchange-search-name: grpc
:connector-name: gRPC
:lc-connector-name: grpc
:studio-connector-name: gRPC Connector

include::connectors::partial$t-studio-partial.adoc[tags=topic-intro]

[[create-mule-project]]
== Create a Mule Project

include::connectors::partial$t-studio-partial.adoc[tags=create-project-intro]

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

include::connectors::partial$t-studio-partial.adoc[tags=add-connector-to-project]

[[configure-source]]
== Configure a Source

include::connectors::partial$t-studio-partial.adoc[tags=configure-source-intro]
You can configure one of these sources to use with gRPC Connector:

include::connectors::partial$t-studio-partial.adoc[tags=listener-scheduler-descriptions]

* *gRPC Connector sources* – Use a gRPC source (for example, *Bidirectional Streaming Listener*, *Server Streaming Subscriber*) when the flow is driven by gRPC calls. See xref:grpc-connector-reference.adoc#BidiStreamingListener[gRPC Connector Reference] for sources.

include::connectors::partial$t-studio-partial.adoc[tags=listener-steps]

[[add-connector-operation]]
== Add a Connector Operation to the Flow

include::connectors::partial$t-studio-partial.adoc[tags=add-connector-operation]

[[configure-global-element]]
== Configure a Global Element for the Connector

When you configure the connector, configure a global element that all instances of that connector in the app can use. Configuring a global element requires you to provide the connection settings the connector needs to access the gRPC service or expose a gRPC server.

To configure the global element for gRPC Connector, follow these steps:

. Select the operation or source in the Studio canvas.
. In the *General* configuration screen for the operation or source, click the *Add* icon to access the global element configuration fields.
. In the *General* tab, in *Connection*, select the configuration type to use:
* *Client* for connecting to gRPC services as a client. Then select the connection type:
** <<no-auth>> 
** <<oauth-client-credentials>>
** <<google-service-account>> 
* *Server* for exposing gRPC methods. Then configure <<grpc-server>>.
+
You can reference a configuration file that contains ANT-style property placeholders (recommended), or you can enter your connection details in the global configuration properties. For information about the benefits of using property placeholders and how to configure them, refer to xref:connectors::introduction/intro-connector-configuration-overview.adoc[Anypoint Connector Configuration].
. In the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server (for client configuration).
. Click *OK*.

[[no-auth]]
=== No Auth

Enter the host, port, IDL definition (protobuf descriptor), and connection mode (PlainText or TLS) in the *General* tab. For full parameter details, see xref:grpc-connector-reference.adoc#Client_NoAuth[Client - No Auth] in the gRPC Connector Reference.

[[oauth-client-credentials]]
=== OAuth Client Credentials

Enter the host, port, IDL definition, OAuth client ID, client secret, token URL, and optionally scopes and TLS for the auth server. For full parameter details, see xref:grpc-connector-reference.adoc#Client_OauthClientCredentials[Client - Oauth Client Credentials] in the gRPC Connector Reference.

[[google-service-account]]
=== Google Service Account Auth Provider

Enter the host, port, IDL definition, private key ID, client ID, client email, and private key (as text or from a file). For full parameter details, see xref:grpc-connector-reference.adoc#Client_GoogleServiceAccountAuthProvider[Client - Google Service Account Auth Provider] in the gRPC Connector Reference.

[[grpc-server]]
=== Grpc Server

Enter the HTTP listener config reference and IDL definition (protobuf descriptor) for the gRPC server. For full parameter details, see xref:grpc-connector-reference.adoc#Server_GrpcServer[Server - Grpc Server] in the gRPC Connector Reference.

[[client-config-parameters]]
=== Client Configuration Parameters

When you configure a client connection (No Auth, OAuth Client Credentials, or Google Service Account), the following parameters are required:

[%header%autowidth.spread]
|===
| Parameter | Type | Description
| host | String | gRPC server hostname or IP address
| port | Integer | gRPC server port
| idlDefinition | IDL Definition | Service definition (protobuf descriptor)
|===

For optional parameters (defaultHeaders, connectionTimeout, connectionTimeoutUnit, tlsContext), see xref:grpc-connector-reference.adoc[gRPC Connector Reference].

[[configure-other-fields]]
== Configure Additional Connector Fields

include::connectors::partial$t-studio-partial.adoc[tags=config-additional-fields]

.Client operations
[%header%autowidth.spread]
|===
| Operation | Description
| Unary Call | Single request, single response
| Server Streaming with Delegation | Single request, multiple responses; handling delegated to a listener
| Server Streaming with Iterator | Single request, multiple responses; returns iterable for immediate consumption
| Client Streaming | Multiple requests from client, single response
| Bidirectional Streaming | Multiple requests and responses in both directions
|===

For detailed configuration information for each operation and source, see xref:grpc-connector-reference.adoc[gRPC Connector Reference].

[[view-app-log]]
== View the App Log

include::connectors::partial$t-studio-partial.adoc[tags=view-app-log]

== See Also

include::connectors::partial$t-studio-partial.adoc[tags=see-also]
