= Upgrade Amazon S3 Connector to Version 5.x
:page-aliases: connectors::amazon/amazon-s3-connector-upgrade-migrate.adoc

== Supported Upgrade Paths

[%header,"cols=50a,50a"]
|===
|From Version | To Version
|5.6.0 |5.7.0
|===

== Changes in This Release

* Added support for custom domain endpoints to provide Amazon Virtual Private Cloud (VPC) feature utilization.
* Upgraded the Amazon SDK for Java dependency to version 1.11.969.

=== Requirements

Ensure your system meets the following compatibility requirements before you perform the upgrade:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule |4.1.1 and later
|AWS SDK for Java	|1.11.969
|===

== Upgrade Prerequisites

Before you perform the upgrade, create a backup of your files, data, and configuration in case you need to restore to the previous version.

== Upgrade Steps

Follow these steps to perform the upgrade to version 5.7.0:

* Download the current version.
* Import data.
* Update the configuration.

== See Also
https://help.mulesoft.com[MuleSoft Help Center]
