= Email Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: email, connector, send, retrieve, manage, match, matcher, smtp, pop3, imap


//Anypoint Studio, Design Center connector
[[short_description]]
The Email connector can send and retrieve email messages over the standard email protocols. Its main features include these:

* Retrieving emails from POP3 mailboxes.
* Retrieving, deleting, and storing emails from IMAP mailboxes.
* Sending emails over the SMTP protocol.
* Supporting secure connections for all protocols over Transport Layer Security (TLS).

[[connection_settings]]
== Connector Configurations

Email connector configurations vary depending on the protocol you use. They share a basic set of parameters that require a connection over the protocols covered in this documentation.

== TLS Configuration with Keystores and Truststores

You can use Transport Layer Security (TLS) and configure email by providing a key store with your certificate. You can also enable 2-way authentication by providing a trust store. For details, see xref:4.1@mule-runtime::tls-configuration.adoc[Configure TLS with Keystores and Truststores].

[[see_also]]
== See Also
* xref:email/email-documentation.adoc[Email Connector Technical Reference]
* xref:email/email-list.adoc[To List emails]
* xref:email/email-send.adoc[To Send emails]
* xref:email/email-gmail.adoc[Connecting with Gmail]
