= Troubleshooting Amazon Event Hubs Connector - Mule 4

To troubleshoot Azure Event Hubs Connector, become familiar with the information about enabling verbose logging and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application is failing, temporarily enable verbose logging for Azure Event Hubs Connector. +

Remember to always disable the enhanced verbosity after troubleshooting because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name ="com.azure.messaging.eventhubs.checkpointstore.blob" level= "DEBUG"/> 
   <AsyncLogger name="com.azure.messaging.eventhubs" level="DEBUG"/>
   <AsyncLogger name="com.azure.core.amqp" level="DEBUG"/>
   <AsyncLogger name="com.azure.identity" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Understand Common Throws

Here is a list of common throws messages and how to interpret them.

* AZURE-EVENTHUBS:AEH_ERROR

 An error occurs in Azure Event Hubs.

* AZURE-EVENTHUBS:AUTHENTICATION

 Unable to authenticate to the Azure Event Hubs server.

* AZURE-EVENTHUBS:CONNECTIVITY

 The client became disconnected from the event hub while attempting to publish an event.

* AZURE-EVENTHUBS:INVALID_INPUT

 The user sent an invalid input.

* AZURE-EVENTHUBS:RETRY_EXHAUSTED

 The maximum number of retries for the operation is reached.


== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
* https://issues.salesforce.com/[Known Issues]
