= Azure Event Hubs Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Azure Event Hubs (Azure Event Hubs Connector) enables support for event producing and consuming.

Azure Event Hubs is a big data streaming platform and event ingestion service. It can receive and process millions of events per second. Data sent to an event hub can be transformed and stored by using any real-time analytics provider or batching/storage adapters.

For information about compatibility and fixed issues, refer to the Azure Event Hubs Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Azure Event Hubs
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Azure Event Hubs target resource
* Anypoint Platform
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Some common use cases for Azure Event Hubs Connector include:

* Sending an event
* Sending an event with a publisher ID
* Sending an event to a specific partition
* Sending a batch of events
* Consuming events (single or batch) from a specific partition

== Connection Types

Azure Event Hubs connections use the Config authentication type.

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:azure-event-hubs-connector-reference.adoc[Azure Event Hubs Messaging Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
