= Oracle Siebel Business Objects Connector API Reference
:keywords: oracle, siebel, business, objects
:last-update-label!:
:source-highlighter: coderay
:page-aliases: 3.9@mule-runtime::siebel-bo-apidoc.adoc

+++
Oracle Siebel Java Data Beans connector
+++

*Additional Info*
[%header%autowidth.spread]
|===
| Requirement |Required?
| Requires Mule Enterprise License |  Yes icon:star[]  {nbsp}
| Requires Entitlement |  Yes icon:star[]  {nbsp}
| Mule Version | 3.5.0 or higher
|===

== Configuration
`<siebel:config>`


`Connection Management`



=== Attributes

[%header%autowidth.spread]
|===
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| user | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel username+++ |   | *x*{nbsp}
| rsaEnabled | +++boolean+++ | +++Siebel encryption type. Make sure your server is configured to support RSA encryption. By default it is set to false.+++ |  false | {nbsp}
| password | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel password+++ |   | *x*{nbsp}
| server | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel server. The server IP.+++ |   | *x*{nbsp}
| port | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel port. The server port used for the connection. By default it is 2321.+++ |  2321 | {nbsp}
| serverName | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel Enterprise server name+++ |   | *x*{nbsp}
| objectManager | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel Object Manager+++ |   | *x*{nbsp}
| language | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++connection language+++ |  ENU | {nbsp}
| encoding | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++connection file encoding. It specifies the character encoding of the Siebel client. By default it is utf8.+++ |  utf8 | {nbsp}
| defaultViewModeBusComp | +++int+++ | +++Default view mode for DataSense purposes. By default it is set to '3' which means it will go through all the records for which there is a valid owner.+++ |  3 | {nbsp}
| dataSenseFilterQueryBusComp | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Query for filtering DataSense Business Components results.+++ |   | {nbsp}
| defaultViewModeBusObjects | +++int+++ | +++Default view mode for Business Objects discovery. By default it is set to '3' which means it will go through all the records for which there is a valid owner.+++ |  3 | {nbsp}
| dataSenseFilterQueryBusObjects | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Query for filtering DataSense Business Objects results+++ |   | {nbsp}
| dataSenseHierarchicalDiscovery | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Indicates if the fields discovery  recreates hierarchical objects within business components. By default it is set to false.+++ |  false | {nbsp}
|===



== Processors

---

=== Query Business Components
`<siebel:query-business-components>`



icon:cloud[] {nbsp} DataSense enabled

+++
Retrieves a list of business components depending on a given search spec or search expression
+++

==== XML Sample
[source,xml,linenums]
----
<siebel:query-business-components config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Action.Action" records="">
        <siebel:fields-to-retrieve>
                    <siebel:fields-to-retrieve>Description</siebel:fields-to-retrieve>
                </siebel:fields-to-retrieve>
        <siebel:search-spec>
            <siebel:search-spec key="Description">Action1</siebel:search-spec>
        </siebel:search-spec>
    </siebel:query-business-components>
----



==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
businessObjectComponentType icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel's business object component type+++ |  | *x*{nbsp}




|
fieldsToRetrieve  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++list of fields to retrieve in the query+++ |  | *x*{nbsp}




|
searchSpec  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++map with search values to be used as filters in the query+++ |  | {nbsp}




|
searchExpression  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++search expression for Siebel's business components+++ |  | {nbsp}




|
sortSpec  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++sorting specification for Siebel's business components+++ |  | {nbsp}




|
viewMode  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++integer representing the visibility type for the Business Component: 0 (SalesRepView) 1 (ManagerView) 2 (PersonalView) 3 (AllView) 4 (NoneSetView)+++ | 3 | {nbsp}




|
records  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++integer representing the number of records returned by the query. By default it returns all the records.+++ |  | {nbsp}


|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>>+++ | +++list of maps with the components values+++
|===




---

=== Query Join Business Components

`<siebel:query-join-business-components>`




+++
Allows retrieving two different business object, joining them according to an specified criteria
+++

==== XML Sample
[source,xml,linenums]
----
<siebel:query-join-business-components config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Opportunity.Opportunity" businessObjectComponentTypeToJoin="Opportunity.Opportunity Product">
        <siebel:fields-to-retrieve>
            <siebel:fields-to-retrieve>Id</siebel:fields-to-retrieve>
            <siebel:fields-to-retrieve>name</siebel:fields-to-retrieve>
        </siebel:fields-to-retrieve>
        <siebel:fields-to-retrieve-to-join>
            <siebel:fields-to-retrieve-to-join>Id</siebel:fields-to-retrieve-to-join>
            <siebel:fields-to-retrieve-to-join>Name</siebel:fields-to-retrieve-to-join>
        </siebel:fields-to-retrieve-to-join>
        <siebel:join-condition>
            <siebel:join-condition key="Id">Oppty Id</siebel:join-condition>
        </siebel:join-condition>
    </siebel:query-join-business-components>
----



==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
businessObjectComponentType  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel's business object component type+++ |  | *x*{nbsp}




|
fieldsToRetrieve  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++list of fields to retrieve in the query+++ |  | *x*{nbsp}




|
searchSpec  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++map with search values to be used as filters in the query+++ |  | {nbsp}




|
searchExpression  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++search expression for Siebel's business components+++ |  | {nbsp}




|
businessObjectComponentTypeToJoin  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Business object component to join+++ |  | *x*{nbsp}




|
fieldsToRetrieveToJoin  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++fields to retrieve for the business component to join+++ |  | *x*{nbsp}




|
joinCondition  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++map containing the join condition for the business object. The structure is (key[field in object1], value[field in object 2])+++ |  | *x*{nbsp}




|
viewMode  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Siebel business component view mode+++ | 3 | {nbsp}




|
nrRecords  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++number of records returned by the query+++ |  | {nbsp}


|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>>+++ | +++list of maps with the components values+++
|===




---

=== Create business component
`<siebel:create-business-component>`



icon:cloud[] {nbsp} DataSense enabled

+++
Creates a new business component
+++

==== XML Sample
[source,xml,linenums]
----
<siebel:create-business-component config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Action.Action">
        <siebel:business-component-fields>
            <siebel:business-component-field key="Description">New Action</siebel:business-component-field>
        </siebel:business-component-fields>
    </siebel:create-business-component>
----



==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
businessObjectComponentType icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel's business object component type+++ |  | *x*{nbsp}




|
businessComponentFields icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++map with the list of values to be added to the new component+++ | #[payload] | {nbsp}


|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++CreateResult+++ | +++created business component id+++
|===




---

=== Update Business Component

`<siebel:update-business-component>`



icon:cloud[] {nbsp} DataSense enabled

+++
Updates Siebel business component from values map
+++

==== XML Sample
[source,xml,linenums]
----
<siebel:update-business-component config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Action.Action">
        <siebel:search-spec>
            <siebel:search-spec key="Id">1-EA-2223</siebel:search-spec>
        </siebel:search-spec>
        <siebel:business-component-fields>
            <siebel:business-component-field key="Description">New Action</siebel:business-component-field>
        </siebel:business-component-fields>
    </siebel:update-business-component>
----



==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
businessObjectComponentType icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel's business object component type+++ |  | *x*{nbsp}




|
searchSpec  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++map containing the spec for searching business components to update+++ |  | *x*{nbsp}




|
businessComponentFields icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++map with the list of values to be updated in the component+++ | #[payload] | {nbsp}




|
viewMode  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Siebel business component view mode+++ | 3 | {nbsp}


|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++UpdateResult+++ | +++true if operation was successful+++
|===




---

=== Upsert Business Component

`<siebel:upsert-business-component>`



icon:cloud[] {nbsp} DataSense enabled

+++
Creates or updates a business component depending if it exists or no. For checking if the record exists, it queries Siebel taking into account the list of idfields. If the
list is null, it will take the Id field from the business component fields map.
+++

==== XML Sample

[source,xml,linenums]
----
<siebel:upsert-business-component config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Action.Action">
        <siebel:business-component-fields>
            <siebel:business-component-field key="Id">1-EA223</siebel:business-component-field>
            <siebel:business-component-field key="Description">New Action</siebel:business-component-field>
        </siebel:business-component-fields>
        <siebel:id-fields>
            <siebel:id-field>Description</siebel:id-field>
        </siebel:id-fields>
    </siebel:upsert-business-component>
----



==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
businessObjectComponentType icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel's business object component type+++ |  | *x*{nbsp}




|
businessComponentFields icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++map with the list of values to be updated in the component+++ | #[payload] | {nbsp}




|
idFields  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++list of fields to be taken as identifiers of the record to analyze if it should be created or not+++ |  | {nbsp}




|
viewMode  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Siebel business component view mode+++ | 3 | {nbsp}


|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++UpsertResult+++ | +++id of the created or updated business component+++
|===




---

=== Delete Business Component

`<siebel:delete-business-component>`



icon:cloud[] {nbsp} DataSense enabled

+++
Deletes a Siebel business component record from Id
+++

==== XML Sample
[source,xml,linenums]
----
<siebel:delete-business-component config-ref="Oracle_Siebel_Business_Objects" businessObjectComponentType="Action.Action"
        businessComponentId="EJJ-11"/>
----



==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
businessObjectComponentType icon:key[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Siebel's business object component type+++ |  | *x*{nbsp}




|
businessComponentId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++id of the business component to be deleted+++ |  | *x*{nbsp}




|
viewMode  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Siebel business component view mode+++ | 3 | {nbsp}


|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++boolean+++ | +++true if the operation was successful+++
|===

== See Also

https://www.mulesoft.com/exchange/org.mule.modules/mule-module-siebel-businessobject/[Oracle Siebel Business Objects Connector on Exchange]
