= Use Studio to Configure a Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

To use Anypoint Studio to configure a connector:

. Install the connector.
. Configure an input source for the connector.
. Configure the connector.

Follow these best practices when you configure an input source and connector in Studio:

*  Configure an associated global element for the input source and connector.
* Create a `.yaml` file or `.properties` file to contain your properties, and then reference the file from the configuration.
* Configure a reconnection strategy for the input source. (*Reviewers: Should you create a reconnection strategy for the connector as well?*)

For information about these best practices, see the <<Connector Configuration Overview topic>>.

== Install the Connector

Installing the connector adds it to a Studio project. Studio provides two ways to install a connector:

* Use the Exchange application in the Studio taskbar.

* Use the Exchange icon in the Mule Palette view.

(*Reviewers, is there any advantage to using one of these methods for installing a connector>* )

=== Install the Connector from the Studio Taskbar

. In Studio, create a Mule project.
. Click the Exchange icon *(X)* in the upper left of the Studio task bar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for the connector, for example, *Amazon SQS*.
. Select the connector.
. Click *Add to project*.
. Follow the prompts to install the connector.

=== Install the Connector from the Mule Palette View

. In Studio, create a Mule project.
. In the Mule Palette view, click *(X) Search in Exchange*.
. In *Add Modules to Project*, enter the connector name in the search field.
. Click the connector name in *Available modules*.
. Click *Add*.
. Click *Finish*.

== Configure an Input Source for the Connector

An input source starts a flow when a specified condition is met. Configure an input source for the connector, such as an HTTP Listener operation (HTTP Listener), Scheduler endpoint (Scheduler), or connector-specific input source.

=== Use HTTP Listener as an Input Source

HTTP Listener listens for HTTP requests and triggers the associated flow when it receives them. To use HTTP Listener as an input source:

. In the Mule Palette view, search for *HTTP* and select the *Listener* operation.
. Drag the *Listener* operation onto the canvas.
. In the *Listener* configuration screen, click the plus sign (*+*) next to the *Connector configuration* field to add a global element for HTTP Listener.
. Accept the defaults on the *General* tab or specify required information:
* To listen on a specific port for every network interface on the server, leave the default value `0.0.0.0` for the *Host* property.
* To listen for incoming requests generated inside the server, set the *Port* value to `localhost`.
. To use TLS, access the *TLS* tab and specify the required information.
. On the *Advanced* tab, specify a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.
. Set the *Path* field to the appropriate path.
. Select the other tabs and specify the appropriate field values.

For more information about HTTP Listener, see the xref:http/http-documentation.adoc[HTTP Connector Reference].

=== Use Scheduler as an Input Source

Use Scheduler to trigger a flow when a time-based condition is met. You can configure Scheduler to be triggered at a regular interval or give it a more flexible cron expression. For example, you can use Scheduler to trigger a flow every five seconds.

To use Scheduler as an input source:

. In the Mule Palette view, search for *Scheduler*.
. Drag *Scheduler* onto the canvas.
. In the *Scheduling Strategy* field of the *Scheduler configuration* screen, select whether you want to use a fixed frequency or cron expression to trigger the flow:
* If you select *Fixed Frequency*, enter values for these fields:
+
** *Frequency*
+
The frequency at which the Scheduler triggers the flow, based on the time unit specified in the *Time unit* field.
+
** *Start delay*
+
The amount of time to wait before triggering the flow for the first time after the app starts, based on the time unit specified in the *Time unit* field.
+
** *Time unit*
+
The time unit for the values of *Frequency* and *Start Delay*.
+
* If you select *Cron*, enter the cron expression in the *Expression* field and the time zone in the *Time Zone* field. Refer to the `java.util.TimeZone` JavaDoc for the format and valid values for the *Time Zone* field.
+
. To configure metadata for the payload, variables, and attributes, select the *Metadata* tab and add the appropriate metadata.

For more information about Scheduler, see xref:mule-runtime::scheduler-concept.adoc[Scheduler Endpoint (Trigger)]

=== Use a Connector-Specific Input Source

If a connector has associated input sources, you can use a connector input source to trigger the flow. Each connector input source has a unique configuration.

For example, you can use Amazon SQS Receive Messages as an input source for Amazon SQS Connector. This input source triggers a flow each time the configured Amazon SQS queue receives a new message.

To configure a connector-specific input source:

. In the Mule Palette view, search for the connector and select the input source.
. Drag the input source onto the canvas.
. In the configuration screen, click the plus sign (*+*) next to the *Connector configuration* field to add a global element for the input source.
. Enter values for the required fields.
. On the *Advanced* tab, specify a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.

== Configure the Connector

To configure a connector in your Mule app, first configure a global element that can be used by all instances of that connector in the flow:

. In the Mule Palette view, search for the connector and select the desired operation.
. Drag the operation onto the canvas.
. In the configuration screen for the operation, click the plus sign (*+*) next to the *Connector configuration* field to add a global element for connector.
. Specify the global element properties for the connector.
. On the *Advanced* tab, specify a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server.
. Click *OK*.

After you configure a global element, configure the other fields for the connector.

For information about configuring a specific connector, see the User Guide and Reference Guide for that connector.

== See Also

* <<Refer to the Connector Configuration Overview topic>>
* https://help.mulesoft.com[MuleSoft Help Center]
