= Introduction to Anypoint Connectors
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/


== What are Anypoint Connectors

Anypoint Connectors are extensions of Mule that let you integrate with external data and systems such as Salesforce, SAP, ServiceNow, Workday, and more to send and receive information from the backend systems to create something new. 

Anypoint Connectors enable you to connect Mule apps to resources, which can be any source of content, such as a database, protocol, or API. Anypoint connectors allow you to connect with enterprise data, such as accounting, CRM, ERP, marketing automation, on-premise and cloud data Stores through SQL. Use connectors within your Mule apps to send and receive data over any universal protocol or transport method, as well as to and from an API.

== Connector Architecture

== How Anypoint Connectors Work

When you add a connector to the start of a flow, it’s known as a message processor or "trigger" because it starts the Mule flow by receiving information from the connector’s resource. For example, when a Salesforce user updates a sales opportunity, the connector application can receive the information and direct it to a database or to another connector for processing.

You can also use the HTTP connector as a message processor so that users can send information to your application using a web browser, Postman, or the curl command.

You can use different operations from the same connector in a project. One operation can receive data and another can process the data.

In addition, Exchange provides templates and examples that enable you to jumpstart application development.

== Common Use Cases

== Connector Support Categories

Anypoint Connectors follow semantic versioning and have 4 categories: 

* Premium
* Select
* MuleSoft Certified
* Community

For information about these categories and the level of support offered with each category, see https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Anypoint Connectors] 





