= Configure a Connector Using Studio - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

To configure a connector in Anypoint Studio:

. Install the connector.
. Configure an input source for the connector.
. Configure the connector.

When you configure an input source and connector, it is recommended that you configure an associated global element for each. When doing so, you can either enter your credentials into the global configuration properties or reference a configuration placed in a file in the `src` folder of your project file that contains these values. For simpler maintenance and better reuse of your project, it is recommended that you use a configuration file.

== Install the Connector

Installing the connector adds it to a Studio project. Studio provides two ways to install a connector:

* Use the Exchange application in the Studio taskbar.

* Use the Exchange icon in the Mule Palette view.

=== Install the Connector from the Studio Taskbar

. In Studio, create a Mule project.
. Click the Exchange icon *(X)* in the upper left of the Studio task bar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for `Amazon SQS`.
. Select *Amazon SQS*.
. Click *Add to project*.
. Follow the prompts to install the connector.

=== Install the Connector from the Mule Palette View

. In Studio, create a Mule project.
. In the Mule Palette view, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type `Amazon SQS` in the search field.
. Click the connector name in *Available modules*.
. Click *Add*.
. Click *Finish*.

== Configure an Input Source for the Connector

An input source starts a flow when a specified condition is met. Configure an input source for the connector, such as an HTTP Listener operation, Scheduler component, or connector-specific input source.

=== Use the HTTP Listener Operation as an Input Source

The HTTP Listener operation listens for HTTP requests and triggers the associated flow when it receives them.

To use the HTTP Listener operation as an input source:

. In the Mule Palette view, search for *HTTP* and select the *Listener* operation.
. Drag the *Listener* operation onto the canvas.
. In the *Listener* configuration screen, click + next to the *Connector configuration* field to add a global element for HTTP Connector.
. Accept the defaults.
. Set the *Path* field to `/`.

For more information about the HTTP Listener operation, see xref:http/http-documentation.adoc[HTTP Connector Reference].

=== Use the Scheduler Component as an Input Source

The Scheduler component enables you to trigger a flow when a time-based condition is met. You can configure Scheduler to be triggered at a regular interval or give it a more flexible cron expression. For example, a Scheduler Component might trigger an event to start a flow every 5 seconds.

To use the Scheduler component as an input source:

. In the Mule Palette view, search for *Scheduler*.
. Drag the *Scheduler* component onto the canvas.
. In the *Scheduler* configuration screen,
* In the *Scheduling Strategy* field, select whether you want to use a fixed frequency or cron expression for triggering the flow:
** If you selected *Fixed Frequency* , enter values for the *Frequency*, *Start delay*, and *Time unit* fields.
** If you selected *Cron*, enter the cron expression.

For more information about the Scheduler component, see xref:mule-runtime::scheduler-concept.adoc[Scheduler Endpoint (Trigger)]

=== Use a Connector-Specific Input Source

If a connector has associated input sources, you can use a connector input source to trigger the flow. Each input source has a unique configuration.

For example, you can use Amazon SQS Receive Messages as an input source for Amazon SQS Connector. This input source triggers an app flow when the Amazon SQS queue receives a new message.

To configure Amazon SQS Receive Messages:

. In the Mule Palette view, search for *Amazon SQS* and select *Receive messages*.
. Drag the *Receive Messages* operation onto the canvas.
. In the *Receive messages* configuration, click + next to the *Connector configuration* field to add a global element for Receive Messages.
. Enter values for the following fields:
* Access Key*
* Secret Key*
. Click *Test Connection* to xxx
. Click *OK*.

== Configure the Connector

To configure a connector in your Mule app flow, configure a global element that can be used by all instances of that connector in the flow.

. In the Mule Palette view, search for the connector and select the desired operation.
. Drag the operation onto the canvas.
. In the configuration screen for the operation, click + next to the *Connector configuration* field to add a global element for connector.
. Specify the global element properties for the connector.
. Click *Test Connection*.
. Click *OK*.
+
[%header%autowidth.spread]
|===
|Field |Description
|Name | Name used to reference the configuration
|Access Key |Alphanumeric text string that uniquely identifies the user who owns the account
|Secret Key |Key that acts as a password
|Try AWS Credentials Provider Chain|Drop-down menu that controls whether temporary credentials should be used
|Region Endpoint |Regional endpoint to process your requests
|Default Global URL |URL of the Amazon SQS queue to act upon
|===
+
When you provide a queue URL in the *Default Global Queue URL* field of the global element, the connector automatically creates the queue and sets the URL of this queue as the provided value. All Amazon SQS message processors that reference the global element perform operations using this queue URL.
+
To reference a different queue URL for a particular message processor in the flow, perform the operation using the `Queue URL` attribute provided by the message processor.
. Leave the default entries for the *Proxy* and *Advanced* tabs.
. Click *Test Connection* to confirm that the parameters of your global configuration are accurate and that Mule is able to connect successfully to your instance of Amazon SQS.
. Click *OK*.

== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
