= Introduction to Anypoint Connectors
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/


== What are Anypoint Connectors

Anypoint Connectors are extensions of Mule that let you integrate with external data and systems such as Salesforce, SAP, ServiceNow, Workday, and more to send and receive information from the backend systems to create something new.

Anypoint Connectors enable you to connect Mule apps to resources, which can be any source of content, such as a database, protocol, or API. Anypoint connectors allow you to connect with enterprise data, such as accounting, CRM, ERP, marketing automation, on-premise and cloud data Stores through SQL. Use connectors within your Mule apps to send and receive data over any universal protocol or transport method, as well as to and from an API.

== Connector Architecture

== How Anypoint Connectors Work

Anypoint Connectors receive or send messages between Mule and one or more external sources, such as files, databases, or Web services. Connectors can act as message sources by working as inbound endpoints, or they can act as a message processor that performs an operation in the middle of a flow, or they can be at the end of a flow and act as the recipient of the final payload data.

When you add a connector to the start of a flow, it’s known as a message processor or "trigger" because it starts the Mule flow by receiving information from the connector’s resource. For example, when a Salesforce user updates a sales opportunity, the connector application can receive the information and direct it to a database or to another connector for processing.

Connectors in Mule are either select or premium:

=== Select Connectors


=== Premium Connectors

////

=== Endpoint-Based Connectors

These connectors follow either a one-way or request-response exchange pattern and are often (but not always) named and based around a standard data communication protocol, such as FTP and SMTP.

Endpoint-based connectors are configured as either inbound or outbound endpoints in a flow. Inbound endpoints serve as a message source for a flow. Outbound endpoints can occur mid-flow or at the end of flows, and send information to external systems.

=== Operation-Based Connectors

These connectors follow an information exchange pattern based on the operation that you select and are often (but not always) named and based around one or more specific third-party APIs.

When you add an operation-based connector to your flow, you immediately define a specific operation for that connector to perform.

You can use different operations from the same connector in a project. One operation can receive data and another can process the data.

////

In addition, Exchange provides templates and examples that enable you to jumpstart application development.

== Common Use Cases

== Connector Support Categories

Anypoint Connectors follow semantic versioning and have 4 categories:

* Premium
* Select
* MuleSoft Certified
* Community

For information about these categories and the level of support offered with each category, see https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Anypoint Connectors]
