= Use Flow Designer to Configure a Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Anypoint Design Center's Flow Designer enables you to create apps visually. For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour].

To use Flow Designer to configure a connector:

. Configure an input source (trigger) for the connector.
. Configure the connector.

[[configure-input-source]]
== Configure an Input Source for the Connector

. Log into Anypoint Platform.
. Click *Start designing*.
. In Design Center, click *Create*.
. Click *Create new application*.
. Enter a project name and click *Create*.
. Click *Go straight to canvas* to exit from *Let's get started*.
+
<<add screenshot>>
+
Result: Flow Designer appears with an empty trigger card displayed in the middle of the canvas.
+
<<add screenshot>>
+
. Click on the trigger card.
. Configure an input source for the connector, such as an HTTP Listener operation (HTTP Listener), Scheduler endpoint (Scheduler), or connector-specific input source, as described in the next sections.

=== Use HTTP Listener as an Input Source

HTTP Listener listens for HTTP requests and triggers the associated flow when it receives them. To use HTTP Listener as an input source:

. After following the procedure described in the <<configure-input-source,Configure an Input Source for the Connector>> section, search for *HTTP*.
. Select *HTTP Listener*.
. Enter a value for *Path*.
. Click Edit:
+
<add screenshot>>
+
. Click *Add connection*.
. Enter a connection name.
. Select *Listener* as the connection type.
. Enter values for the *Host* and *Port* fields:
* To listen on a specific port for every network interface on the server, leave the default value `0.0.0.0` for *Host*.
* To listen for incoming requests generated inside the server, set the *Port* value to `localhost`.
. Scroll down and select a reconnection strategy.
. To use TLS, specify the required information in the  *TLS Configuration* section.
. Click *Save*.

For more information about HTTP Listener, see the xref:http/http-documentation.adoc[HTTP Connector Reference].


=== Use Scheduler as an Input Source

Use Scheduler to trigger a flow when a time-based condition is met. You can configure Scheduler to trigger a flow at a regular interval or give it a more flexible cron expression. For example, you can use Scheduler to trigger a flow every five seconds.

To use Scheduler as an input source:

. After following the procedure described in the <<configure-input-source,Configure an Input Source for the Connector>> section, search for and click on *Scheduler*.
. In the *Scheduling Strategy* field of the *Scheduler configuration* screen, select whether you want to use a fixed frequency or cron expression to trigger the flow:
* If you select *Fixed Frequency*, enter values for these fields:
+
** *Time unit*
+
The time unit for the values of *Frequency* and *Start Delay*.
+
** *Frequency*
+
The frequency at which the Scheduler triggers the flow, based on the time unit specified in the *Time unit* field.
+
** *Start delay*
+
The amount of time to wait before triggering the flow for the first time after the app starts, based on the time unit specified in the *Time unit* field.
+
* If you select *Cron*, enter the cron expression in the *Expression* field and the time zone in the *Time Zone* field. Refer to the `java.util.TimeZone` JavaDoc for the format and valid values for the *Time Zone* field.

For more information about Scheduler, see xref:mule-runtime::scheduler-concept.adoc[Scheduler Endpoint (Trigger)]

=== Use a Connector-Specific Trigger






== Configure the Target Component

. Click *+* next to the trigger card.
. In *Select a component*, search for the connector name.
. Select the connector name.
. Select an operation for the connector.
. Complete these fields:
+
// List the important and required fields and their values in a table.
// Because each operation has different fields, list the fields
// that are common to each operation and describe them.
+
[%header,cols="30s,55a,15a"]
|===
|Field |Description |Required?
| | |<Yes or No>
|===
+
. Click the *Test* button to test the connection.

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
