= Introduction to Anypoint Connectors
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Anypoint Connectors are reusable, extensions of Mule that enable you to integrate a Mule app with third-party APIs and standard integration protocols. All connectivity in Mule 4 is provided through connectors.

Using connectors in an app provides provides the following advantages:

* Simplifies app development and saves time, since you don't have to program directly to APIs
* Can be updated without requiring updates to other parts of the app
* *Reviewers, are there other advantages I can add here?*

== Use Connectors for Connectivity

You can use connectors to facilitate connectivity from a Mule app to specific software applications, databases, and protocols.

=== Connect to Software Applications

You can use connectors to connect a Mule app to specific software applications. For example, you can use Anypoint Connector for Salesforce (Salesforce Connector) to integrate Salesforce with other business applications such as ERP, analytics, and data warehouse systems.

Likewise, you can use Anypoint Connector for Amazon SQS (Amazon SQS Connector) to send messages to and receive messages from an SQS queue.

For more information about Salesforce Connector and Amazon SQS Connector, see xref:salesforce/salesforce-connector.adoc[Salesforce Connector User Guide] and xref:amazon/amazon-sqs-connector.adoc[Amazon SQS Connector Connector User Guide].

=== Connect to Databases

You can use connectors to connect a Mule app to one or more databases. For example, you can use the Anypoint Connector for Databases (Database Connector) to connect a Mule app to any relational database engine. Then you can perform SQL queries on that database.

Likewise, you can use Anypoint Connector for Hadoop Distributed File System (HDFS Connector) to connect a Mule app to a Hadoop Distributed File System (HDFS). Then you can integrate databases such as MongoDB with Hadoop file systems to read, write, receive files, and send files on the HDFS server.

For more information about Database Connector and HDFS Connector, see xref:db/db-connector-index.adoc[Database Connector User Guide] and xref:hdfs/hdfs-connector.adoc[HDFS Connector User Guide].

=== Connect to Protocols

You can use connectors to connect send and receive data over protocols and, for come protocol connectors, to perform operations. For example, you can use Anypoint Connector for LDAP (LDAP Connector) to connect to an LDAP server and access Active Directory. Then you can add user accounts, delete user accounts, or retrieve user attributes, such as the user's e-mail or phone number.

Likewise, you can use Anypoint Connector for WebSockets (WebSockets Connector) to establish a WebSocket for bidirectional and full-duplex communication between a server and client and to implement server push notifications.

For more information about LDAP Connector and Protocol Connector, see xref:ldap/ldap-connector.adoc[LDAP Connector User Guide] and xref:websockets/websockets-connector.adoc[WebSockets Connector User Guide].

== How Connectors Work

Connectors can perform one or more functions in an app, depending on where you place them and the capabilities of the specific connector. A connector can act as:

* An inbound endpoint that starts the app flow. Connectors that have <<input-sources,input sources>> can perform this function.
* A message processor that performs <<operations,operations>> in the middle of a flow
* An outbound endpoint that receives the final payload data from the flow

[[input-sources]]
=== Input Sources

Some connectors have input sources, or "triggers". These components enable a connector to start a Mule flow by receiving information from the connector’s resource. For example, when a Salesforce user updates a sales opportunity, a flow that starts with a Salesforce Connector component can receive the information and direct it to a database connector for processing.

To see if a connector can act as an input source, see the Reference Guide for the connector.

App developers can also use an HTTP Listener or Scheduler as an input source for a flow:

* HTTP Listener is a connector that listens to HTTP requests. You can configure an HTTP Listener to start a flow when it receives specified requests.
* Scheduler is a core component that starts a flow when a time-based condition is met. You can configure a Scheduler to start a flow at regular intervals, or you can specify a more flexible cron expression to start the flow.

For more information about the HTTP Listener and the Scheduler component, see xref:http/http-connector.adoc[HTTP Connector User Guide] and https://docs.mulesoft.com/mule-runtime/4.2/scheduler-concept.adoc[Scheduler Endpoint (Trigger)].

[[operations]]
=== Operations

Most connectors have operations that execute API calls or other actions against their associated system, database, or protocol. For example, you can use Anypoint Connector for Workday (Workday Connector) to create a position request in Workday or add a fund to the financial management service.

To see a list of operations for a connector, see the Reference Guide for that connector.

== Access Connectors and Related Assets

Anypoint Exchange provides access to all publicly-available connector assets including connectors, templates, and examples.

=== Connectors in Exchange



For information about locating connectors in Exchange, see <<introduction/discover-add-connectors.adoc#Discover and Add Connectors>>.

=== Templates in Exchange

Templates provide starting points for creating Studio projects. Many templates include one or more connector configurations.  For example, the S/4HANA Cloud to Salesforce Partner Migration template helps you migrate partners from an SAP S/4HANA Cloud to a Salesforce instance.

Once you configure a template in Studio, you can customize it to meet your needs. *Reviewers, is this true in Flow Designer as well?*

For information about locating and using templates, see <<introduction/discover-add-templates.adoc#Discover and Add Templates to Flow Designer or Studio>>.

=== Examples in Exchange

Examples are apps that demonstrate how to handle a use case or solution. Many examples use one or more connectors to accomplish required tasks.

For example, the *Authenticating Salesforce using OAuth 2.0* example shows you how to connect to Salesforce using OAuth as the security protocol. It uses the Salesforce Connector to enable OAuth authentication before performing the integration process.

For information about locating and using examples, see <<introduction/discover-add-examples.adoc#Discover and Add Examples to Studio>>.

== Connector Support Categories

Anypoint Connectors have the following categories of support:

* Select connectors are available to anyone. However, you must have an Anypoint Platform subscription to access MuleSoft support.
* Premium connectors are available to licensed users only.
* Mulesoft Certified connectors are developed by MuleSoft's partners and developer community and subsequently reviewed and certified by MuleSoft. Access and support for these connectors is through MuleSoft partners.

For more information about connector support categories, see https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Anypoint Connectors].

== Where to Get Additional Information

Access the Release Notes, User Guide, and Reference Guide for a connector to view connector-specific information:

* Connector Release Notes provide compatibility information for a connector, information on new features, and a list of issues fixed in a release.
* Connector User Guides provide instructions for configuring the associated connector and configuration examples.
* Connector Reference Guides provide a list of supported input sources (if any) and operations for the associated connector. They also provide field descriptions for connector configurations and connection types.

== See Also

<Link to the configure topic>
* https://help.mulesoft.com[MuleSoft Help Center]
