= Introduction to Anypoint Connectors
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/


== What are Anypoint Connectors

Anypoint Connectors are extensions of Mule that let you integrate with external data and systems such as Salesforce, SAP, ServiceNow, Workday, and more to send and receive information from the backend systems to create something new.

Anypoint Connectors enable you to connect Mule apps to resources, which can be any source of content, such as a database, protocol, or API. Anypoint connectors enable you to connect with enterprise data, such as accounting, CRM, ERP, marketing automation, on-premise and cloud data Stores through SQL. Use connectors within your Mule apps to send and receive data over any universal protocol or transport method, as well as to and from an API.

== Connector Architecture

== How Anypoint Connectors Work

Anypoint Connectors receive or send messages between Mule and one or more external sources, such as files, databases, and Web services. Connectors can act as message sources by working as inbound endpoints, a message processor that performs an operation in the middle of a flow, or they can be at the end of a flow and act as the recipient of the final payload data.

When you add a connector to the start of a flow, it’s called a  message processor or "trigger" because it starts the Mule flow by receiving information from the connector’s resource. For example, when a Salesforce user updates a sales opportunity, the connector application can receive the information and direct it to a database or to another connector for processing.

Connectors in Mule are either select or premium:

=== Select Connectors


=== Premium Connectors

== Anypoint Exchange

Anypoint Exchange provides templates and examples that enable you to jumpstart application development.

=== Templates

Templates provide starting points for creating Studio projects. Many templates include connector configuration.  For example, the S/4HANA Cloud to Salesforce Partner Migration template helps you migrate partners from an SAP S/4HANA Cloud to a Salesforce instance. The template specifies filtering criteria for the migration and executes a specific behavior when an account already exists in the destination instance.

Once you configure a template in Studio, you can customize it to meet your needs.

NOTE: Not all connectors have associated templates.

=== Examples

Examples are apps that demonstrate how to handle a use case or solution. Many examples use one or more connectors to accomplish required tasks.

For example, the *Authenticating Salesforce using OAuth 2.0* example shows you how to connect to Salesforce using OAuth as the security protocol. It uses the Salesforce Connector to enable OAuth authentication before performing the integration process.


== Common Use Cases

== Connector Support Categories

Anypoint Connectors follow semantic versioning and have 4 categories:

* Premium
* Select
* MuleSoft Certified
* Community

For information about these categories and the level of support offered with each category, see https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Anypoint Connectors]
