= Use Connectors, Examples, and Templates from AnyPoint Exchange
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

  Install connectors from Exchange (Overview then link to Studio and Flow Designer topics - AUTOMATICALLY INSTALLED - SEARCH AND ADD)

Reference to the Anypoint Connector Tutorial and to user guides/reference guides for
   connector-specific information

Use Anypoint Exchange to discover connectors, templates, and examples, and to incorporate them into your app.

== Discover and Install Connectors from Exchange

=== Discover Available Connectors

You can view a list of all available connectors on Exchange:

. Log into Exchange.
. Under *All assets* on the left side of the screen, click *Provided by MuleSoft*.
. Select *Connectors* in the drop-down list to the left of the search bar.
. To filter the list of connectors, add text to the search field. For example, if you enter `Salesforce connector`, the search returns all Salesforce connectors.
. Click on a connector to view its details.

Searches in Exchange only apply to the Exchange organization you are viewing. If you search in a private Exchange organization, the search only lists that organization’s assets and not MuleSoft’s public assets.

For more information about searching in Exchange, see xref:release-notes::connector/to-find-info[Find Asset Information]

=== Install a Connector in Flow Designer



=== Install a Connector in Studio

To install a connector in Anypoint Studio:

. From your Studio project, click the Exchange icon in the Studio taskbar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for the connector.
. Select the connector and click *Add to project*.
. Follow the prompts to install the connector.

Once you import a connector to Studio, you can configure a global element and properties for the connector. For information, see <<the global element chapter>> and the User Guide for that connector.

== Templates

Templates provide starting points for creating Studio projects that use connectors. For example, the S/4HANA Cloud to Salesforce Partner Migration template helps you migrate partners from an SAP S/4HANA Cloud to a Salesforce instance. The template specifies filtering criteria for the migration and executes a specific behavior when an account already exists in the destination instance.

When you locate a template in Exchange, the landing page of the associated connector contains the following details:
+
* An overview of what the template does
* Prerequisites for using the template
* Instructions for configuring the template

Once you configure the template in Studio, you can customize it to meet your needs.

NOTE: Not all connectors have associated templates.

=== Discover Available Templates in Exchange

You can view a list of all available templates on Exchange:

. Log into Exchange.
. Under *All assets* on the left side of the screen, click *Provided by MuleSoft*.
. Select *Templates* in the drop-down list to the left of the search bar.
. To filter the list of templates, add text to the search field. For example, if you enter `Salesforce template`, the search returns all templates that use Salesforce Connector.
. Click on a template to view its details.

Alternatively, you can search for a specific connector, as described in xxx.

=== Import a Template to Studio


 . Import the template into Studio.
. Run the template on Studio, Mule Standalone, or deploy it to CloudHub.


 == Examples

 Examples in Exchange demonstrate how to handle a use case or solution using Studio. Many examples use one or more connectors to accomplish required tasks.

 For example, the *Authenticating Salesforce using OAuth 2.0* example shows you how to connect to Salesforce using OAuth as the security protocol. It uses the Salesforce Connector to enable OAuth authentication before performing the integration process.

 == Discover Available Examples in Exchange

Locate an example by selecting it from a list of all available examples:

 . Log into Exchange.
 . Under *All assets* on the left side of the screen, click *Provided by MuleSoft*.
. Select *Examples* in the drop-down list to the left of the search bar.
. Click on an example to view the example details.

You can filter the list of examples by using text in the search field. For example, if you enter `Salesforce Connector` the search returns all examples that use the Salesforce Connector.

 When you locate an example in Exchange, the landing page explains how to set up and run the example.
