= Locate and Install Connectors, Examples, and Templates from AnyPoint Exchange
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Where can you find connectors? For Studio, you can find available connectors, examples, and templates in Exchange
  Install connectors from Exchange (Overview then link to Studio and Flow Designer topics - AUTOMATICALLY INSTALLED - SEARCH AND ADD)
  View connector examples
  Use connector templates
Reference to the Anypoint Connector Tutorial and to user guides/reference guides for
   connector-specific information

Use Anypoint Exchange to discover connectors, connector examples, and connector templates, and to incorporate them into your app.

== Install a Connector in Anypoint Studio

. Click the following button to open Exchange:

. Search for the connector.

Searches only apply to the Exchange organization you are viewing. If you search in a private Exchange organization, the search only lists that organization’s assets and not MuleSoft’s public assets.

For more information about searching in Exchange, see xref:release-notes::connector/to-find-info[Find Asset Information]

You can use a premium connector development purposes. However, the connector requires additional licenses to run in a production environment. Contact your sales contact or info@mulesoft.com for more information.

 == Connector Examples

 Exchange examples enable you to create complete Studio projects. For example, xxx

 === Locate an Example in Exchange

 You can locate a connector example by selecting it from a list of all examples:

  . Log into Exchange.
  . Under *All assets* on the left side of the screen, click *Provided by MuleSoft*.
 . Select *Examples* in the drop-down list to the left of the search bar.
 . Click on an example to view the example details.

 Alternatively, you can search for a specific conector, as described in xxx. If the connector has associated examples, the conector landing page lists the examples and their descriptions.




 == Connector Templates

 Exchange templates provide starting points for creating Studio projects that use connectors. For example, the S/4HANA Cloud to Salesforce Partner Migration template helps you migrate partners from an SAP S/4HANA Cloud to a Salesforce instance. The template specifies filtering criteria for the migration and executes a specific behavior when an account already exists in the destination instance.

 Preconditions to meet, properties to configure. customize

 The details include:
 +
 * An overview of what the template does
 * A list of prerequisites for using it
 * A list of steps for configuring it

 Once you understand how a template is built, you can customize it to meet your needs.

 Not all connectors have associated templates.

=== Locate a Template in Exchange

You can locate a template by selecting it from a list of all templates:

 . Log into Exchange.
 . Under *All assets* on the left side of the screen, click *Provided by MuleSoft*.
. Select *Templates* in the drop-down list to the left of the search bar.
. Click on a template to view the template details.

Alternatively, you can search for a specific connector, as described in xxx. If the connector has associated templates, the conector landing page lists the templates and their details.

=== Import a Template to Studio




 To execute a template,

 . Import the template into Studio.
 . Run the template on Studio, Mule Standalone, or deploy it to CloudHub.

== Example


 https://www.mulesoft.com/exchange/

 ?search=salesforce&type=template[Anypoint Exchange templates] provide starting points for Anypoint Studio projects such as:
