= Use Anypont Exchange to Discover Connectors, Templates, and Examples

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Use Anypoint Exchange to discover integration assets such as connectors, templates, and examples and import them into your app or project. You can browse and search for assets built and curated by MuleSoft or assets available in your own organization's Exchange.

To access assets in MuleSoft's Exchange, do either of the following:

* Go to https://www.mulesoft.com/exchange/.
* Go to your organization's Exchange and click the *Provided by MuleSoft* link in the left navigation panel.

To access assets in your own organization's Exchange, you must have access rights to that Exchange.

For more information about searching for assets in Exchange, see xref:exchange::to-find-info.adoc[Find Asset Information].

== Discover and Add Connectors to Flow Designer and Studio Projects

Discover connectors either by starting the search in Exchange or by accessing Exchange from within an Anypoint Flow Designer or Anypoint Studio project:

* Start in Exchange to view a list of all or a subset of MuleSoft-provided connectors. From there, you can view a connector in Flow Designer or download it to Studio.
* Access Exchange from within a Flow Designer or Studio project to locate a template applicable to your use case.

=== Discover Connectors Provided by MuleSoft

To use Exchange as a starting point for discovering all or a subset of MuleSoft-provided connectors:

. https://www.mulesoft.com/exchange/[Access Exchange].
. Under *All assets* on the left side of the screen, click *Provided by MuleSoft*.
. Select *Connectors* in the drop-down list to the left of the search bar.
. To filter the list of connectors, add text to the search field.
+
For example, if you enter `Salesforce`, the search returns all Salesforce connectors.
+
. Click on connector to view its details.

[[add-connector-to-flow-designer]]
=== Add a Connector to a Flow Designer App

When you are working in a Flow Designer project, you can add a connector directly to the project. You can use Flow Designer only for supported connectors.

. Log into Anypoint Platform.
. Open Design Center and create a new Mule app in Flow Designer.
. In the *Let's Get Started wizard*, click *Go straight to canvas*, in the bottom-left corner.
. Click on the Trigger card.
. Select the connector.
. Continue designing the flow, as described in the User Guide for your connector.

[[import-connector-studio]]
=== Import a Connector into a Studio Project

To import a connector into a Studio project:

. In Studio, create a Mule project.
. In the Mule Palette view, click *(X) Search in Exchange*.
. In *Add Dependencies to Project*, type the connector name in the search field.
. Click the connector name in *Available modules*.
. Click *Add*.
. Click *Finish*.

=== Next Step

Follow the directions in the connector's User Guide for configuring the connector in Design Center (using Flow Designer) or Studio.

== Discover and Add Templates to Flow Designer or Studio

A template is a pre-built project that you can use as a starting point for applicable use cases. Many templates include one or more connector configurations.

Discover templates by starting in Exchange or by accessing Exchange from within Flow Designer or Studio:

* Start in Exchange to view a list of all or a subset of MuleSoft-provided templates. From there, you can view a template in Flow Designer or download it to Studio.
* Access Exchange from within Flow Designer or Studio to locate a template that fits your use case.

When you locate a template in Exchange, the landing page of the associated connector contains:

* An overview of what the template does
* Prerequisites for using the template
* Instructions for configuring the template

=== Discover MuleSoft Templates

To use Exchange as a starting point for discovering MuleSoft-provided templates:

. https://www.mulesoft.com/exchange/[Log into Exchange].
. Under *All assets* on the left side of the screen, click *Provided by MuleSoft*.
. Select *Templates* in the drop-down list to the left of the search bar.
. To filter the list of templates, add text to the search field.
+
For example, if you enter `Salesforce template`, the search returns all templates that use Salesforce Connector.
+
. Click on a template to view its details.
+
If a template can be used in Flow Designer, it has an *Open flow* button in the top-right corner of the details page. This option opens the template in read-only mode in Flow Designer, which enables you to find out which connectors and operations are used, how data changes as it moves through the flow, and what configurations for connecting to your systems are already set up.
+
For information about using a downloaded template in Flow Designer, see xref:design-center::import-template.adoc[Create a Mule App Quickly from a Template].
+
All templates can be downloaded to Studio by clicking *Download* on the upper right of the screen. You must be logged in to Anypoint Platform to download a template.
+
The system downloads the template as a `.jar` file.

[[import-downloaded-template-studio]]
=== Import a Downloaded Template to Studio

If you downloaded a template from Exchange, you can import the downloaded `.jar` file to Studio:

. From Studio, select *File > Import*.
. In the Import wizard, expand the *Anypoint Studio* folder.
. Select *Packaged mule application (.jar)* and click *Next*.
. In the *File* field, optionally enter a name for the file.
. Click the ellipses (…​) button.
. Select the `.jar` file to import.
. Click *Open*.
+
Studio imports the template as a new Studio project.

[[import-downloaded-templates-studio]]
=== Add a Template Directly to Studio

When you are working in Studio, you can import a template directly from Exchange:

. From Studio, click the Exchange icon *(X)* in the upper-left of the Studio taskbar.
. Log in to Exchange using your Anypoint Platform username and password.
. Search for the template either directly or by accessing the template link on the landing page of the associated connector.
. Select the template and click *Open*.
+
Studio imports the template as a new Studio project.

=== Next Step

Follow the instructions on the template's landing page in Exchange to use the template.

== Discover and Add Examples to Studio

An example is a Studio project that demonstrates how to handle a use case or solution. Many examples include one or more connector configurations. After you locate an example, you can import it to Studio and then run it.

Discover examples by starting in Exchange or by accessing Exchange from within a Studio project:

* Start in Exchange to view a list of all or a subset of MuleSoft-provided examples. From there, you can view download an example to Studio.
* Access Exchange from Flow Designer or Studio to locate an example that fits your project's use case.

When you locate an example in Exchange, the landing page explains how to set up and run the example.

=== Discover MuleSoft Examples

To use Exchange as a starting point for discovering MuleSoft-provided examples:

. Log in to Exchange with your Anypoint username and password.
. Under *All assets* on the left side of the screen, click *Provided by MuleSoft*.
. Select *Examples* in the drop-down list to the left of the search bar.
. To narrow the list of examples, enter applicable text in the Search field.
+
For example, if you enter `Salesforce Connector`, the search returns all examples that use the Salesforce Connector.
+
. Click on an example to view its details.
. To download the example for use in Studio, click *Download* on the upper right of the screen.
+
The system downloads the file as a `.jar` file.

=== Import a Downloaded Example to Studio

If you downloaded an example from Exchange, you can import the downloaded `.jar` file to Studio to create the new project:

. From Studio, select *File > Import*.
. In the Import wizard, expand the *Anypoint Studio* folder.
. Select *Packaged mule application (.jar)* and click *Next*.
. In the *File* field, optionally enter a name for the file.
. Click the ellipses (…​) button.
. Select the `.jar` file to import.
. Click *Open*.
+
Studio imports the example as a new Studio project.

=== Add an Example Directly to Studio

When you are working in Studio, you can import an example directly from Exchange:

. From Studio, click the Exchange icon *(X)* in the upper-left of the Studio taskbar.
. Log into Exchange using your Anypoint Platform username and password.
. Search for the example.
. Select the example and click *Open*.
+
Studio imports the example as a new Studio project.

=== Next Step

Follow the instructions on the example's landing page in Exchange to set up and run the example.

= See Also

* https://help.mulesoft.com[MuleSoft Help Center]
