= Box Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

Box Connector v4.0

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect to APIs and resources on external systems, Box, Salesforce, ServiceNow, Workday.

Box is an online file sharing and content management service for businesses. The Anypoint Connector for Box is a RAML-based connector that provides synchronization of data and automation of processes between Box
and third party CRMs, CMS, mobile, and social applications. Because this is a RAML-based connector, it uses only REST calls to interact with Box 2.0 API and supports only a subset of services available in the API.

== Prerequisites

Before creating an app, you must have access to the Box target resource and Anypoint Platform. You must also understand how to create a Mule app using Design Center or Anypoint Studio.

You should be familiar with the use of Box 2.0 API, Mule, Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and Global Elements.

To use this connector you need the following:

* A developer account or other valid Box instance.
* MuleSoft Enterprise License and necessary entitlements.

== Audience

* Starting user -- To create your Mule app, see xref:box/box-connector-design-center.adoc[Design Center]
or xref:box/box-connector-studio.adoc[Anypoint Studio].

The xref:box/box-connector-config-topics.adoc[Configuration Topics] topic helps extend your understanding of the Box connector.

The
xref:box/box-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Power user - Read the xref:$1/$2-connector-xml-maven.adoc[XML and Maven Support],
xref:$1/$2-connector-config-topics.adoc[Additional Configuration Information],
and [Examples] topics.

== Common Use Cases For the Connector
// List common use cases for the connector and provide
// link to the Examples section use cases.

== Learn Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
you can use as a starting point for your app, as well as examples that illustrate a complete solution.
// List up to 10 Exchange templates and examples for the connector
// Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation)

== Next Step
After you have met the prerequisites and experimented with templates and examples, you are ready to create an app with
xref:box/box-connector-design-center.adoc[Design Center] or xref:box/box-connector-studio.adoc[Anypoint Studio].

== See Also
* https://www.mulesoft.com/exchange/?search=$2&type=connector[Anypoint Exchange]
// * https://forums.mulesoft.com[MuleSoft Forum]" > box-connector-get-started.adoc
