= Box Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can use this connector in Anypoint Studio by first downloading it from Exchange and configuring it as needed.

Configure a connector in Anypoint Studio:
. Install the connector.
. Configure the connector.
. Configure an input source for the connector.

== Install the Box Connector

. In Anypoint Studio, click the Anypoint Exchange icon in the Studio task bar.
. In Anypoint Exchange, click *Login* and supply your Anypoint Platform username and password.
. Search for the $3 connector, click the card for the connector, and click *Add to project*.
. Follow the prompts.

== Configure the Connector

To use the Box connector in a Mule application,
configure a global Box configuration element that can be used by as many Box connectors as you require for your application.

[%header,cols="30a,70a"]
|===
|Parameter|Description
|clientId|The client identifier as assigned by the authorization server when the client application was registered
|clientSecret|The client application's client secret
|host|The host where Box exposes its API
|port|The port at which Box services listen for incoming requests. Default: 443
|basePath|The base path of the Box services' base URI
|protocol|The protocol which Box services follow. Default: HTTPS
|localCallbackPath|The local callback path. Default: /callback
|localCallbackConfig|The HTTP Listener configuration that is used to configure the local authorization URL
|externalCallbackUrl|The redirect URL that is configured in the client application
|localAuthorizationUrl|Local authorization URL that is used to initiate an OAuth2 dance
|authorizationUrl|The authorization URL to request for an authorization code
|accessTokenUrl|The access token URL to request for an access token
|===

== Configure an Input Source

Configure an input source for the connector such as a connector operation,
using *HTTP Listener*, or *Scheduler*.
You can put the following operations for the connector in the *Source* area
of the Studio canvas.

** Configuration Name: The configuration name for the Box connector global element.
** Host: The host where Box exposes its API.
** Port: The port at which Box services listen for incoming requests.
** Base Path: The base path of the Box services' base URI.
** Protocol: The protocol which Box services follow.
** Client Id: The client identifier as assigned by the authorization server when the client application was registered.
** Client Secret: The client application's client secret.
** Local Callback Path: The local callback path.
** Local Callback Config: The HTTP Listener configuration that is used to configure the local authorization URL.
** External Callback Url: The redirect URL that is configured in the client application.
** Local Authorization Url: Local authorization URL that is used to initiate an OAuth2 dance.
** Authorization Url: The authorization URL to request for an authorization code.
** Access Token Url: The access token URL to request for an access token.

== Next

Now that you have completed configuring Studio,
see the xref:box/box-connector-config-topics.adoc[Additional Configuration Information] topic
for more configuration ideas.

== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
