= Box Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select
Box Connector v4.0

== About Connectors

Anypoint Connectors are extensions of Mule that let you work with external systems such as Box, Salesforce, ServiceNow, Workday, Twitter, and more to send and receive information from these systems to create something new.
Anypoint Connectors let you connect Mule applications to APIs and resources.
A connector lets you send and receive data over a protocol, or to and from an API.
Use this information to work with Design Center or Anypoint Studio to adjust the UI settings to enable the connector to work with a Mule application.

Box is an online file sharing and content management service for businesses. The Anypoint Connector for Box is a RAML based connector that provides synchronization of data and automation of processes between Box
and third party CRM, CMS, mobile, and social applications. This is a RAML based connector that only uses REST calls to interact with Box 2.0 API, and only supports a subset of services available within it.

== Prerequisites

You should be familiar with the use of Box 2.0 API, Mule, Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and Global Elements.

Before starting, ensure you have access to the connector, Anypoint Platform, Design Center, or Anypoint Studio.
You should have the Mule Enterprise Edition and entitlements necessary to use this software.

To use this connector you need the following:

* A developer account or other valid Box instance.
* MuleSoft Enterprise License.

== Audience

* Starting user -- Read this Get Started document and create your Mule application in xref:box/box-connector-design-center.adoc[Design Center]
or xref:box/box-connector-studio.adoc[Anypoint Studio].

The xref:box/box-connector-config-topics.adoc[Configuration Topics] topic helps extend your understanding of Box actions.
* Power user - Read the xref:box/box-connector-xml-maven.adoc[XML and Maven Support],
xref:box/box-connector-config-topics.adoc[Additional Configuration Information],
and xref:box/box-connector-examples.adoc[Examples].

//
== Exchange Templates and Examples

<List up to 10 Exchange templates and examples for this connector -- Use the Integration
Pattern categories (broadcast, migration, bidirectional sync, aggregation)>

//
== Next
After you have met the prerequisites and experimented with templates
and examples, you are ready to create an app with xref:box/box-connector-design-center.adoc[Design Center] or xref:box/box-connector-studio.adoc[Anypoint Studio].


== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
