= Box Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select
Box Connector v4.0

Box is an online file sharing and content management service for businesses. The Anypoint Connector for Box is a RAML based connector that provides synchronization of data and automation of processes between Box
and third party CRM, CMS, mobile, and social applications. This is a RAML based connector that only uses REST calls to interact with Box 2.0 API, and only supports a subset of services available within it.

== Prerequisites

This document assumes that you are familiar with Box 2.0 API, Mule, Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and Global Elements.

To use this connector you need the following:

* A developer account or other valid Box instance.
* MuleSoft Enterprise License.

For hardware and software requirements and compatibility information, see the Connector Release Notes.


== Audience

* New user -- Read this document and configure your Mule application in
xref:box/box-connector-design-center.adoc[Design Center].
* Current Mule user -- Read this document and configure your Mule application in
xref:box/box-connector-design-center.adoc[Design Center] or
xref:box/box-connector-studio.adoc[Anypoint Studio].
The xref:box/box-connector-config-topics.adoc[Configuration Topics] help you extend your understanding of Box actions.
* Power user - Read the xref:box/box-connector-xml-maven.adoc[XML and Maven Support],
xref:box/box-connector-config-topics.adoc[Configuration Topics],
and xref:box/box-connector-examples.adoc[Examples].

== Templates and Examples

<List up to 10 Exchange templates and examples for this connector -- Use the Integration
Pattern categories (broadcast, migration, bidirectional sync, aggregation)>

== Triggers

TBD

== Next

Now that you have completed ____, you can try out ______.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
