= Agentforce Connector 1.3 XML and Maven Support 

include::connectors::partial$t-xml-maven-partial.adoc[tags=topic-intro]

== Add a Namespace for the Connector

Paste the following code inside the `mule` tag of the header of your configuration XML:

[source,xml,linenums, subs=attributes+]
----
http://www.mulesoft.org/schema/mule/ms-agentforce 
http://www.mulesoft.org/schema/mule/ms-agentforce/current/mule-ms-agentforce.xsd
----

This example shows how the namespace statements are placed in the `<mule>` XML block:

[source,xml,linenums, subs=attributes+]
----
<mule xmlns:ms-agentforce="http://www.mulesoft.org/schema/mule/ms-agentforce" 
    xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core 
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
    http://www.mulesoft.org/schema/mule/http 
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
    http://www.mulesoft.org/schema/mule/ms-agentforce 
	http://www.mulesoft.org/schema/mule/ms-agentforce/current/mule-ms-agentforce.xsd">
----

== Add a POM File Dependency

The Apache Maven `pom.xml` file generated by Anypoint Code Builder and Studio contains dependencies for a Mule app. If you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to this connector:

[source,xml,linenums,subs=attributes+]
----
<dependency>
	<groupId>com.mulesoft.connectors</groupId>
	<artifactId>mule4-agentforce-connector</artifactId>
	<version>x.x.x</version>
	<classifier>mule-plugin</classifier>
</dependency>
----

Replace `x.x.x` with the version that corresponds to the connector you're using.

To get the most up-to-date `pom.xml` file information:

. Go to https://www.mulesoft.com/exchange/[Anypoint Exchange].
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for `agentforce`.
. Select the connector.
. Click *Dependency Snippets* near the upper right of the screen.


== See Also

* xref:index.adoc[Agentforce Connector Overview]
* xref:agentforce-connector-reference.adoc[Agentforce Connector Reference]
