= Troubleshooting ServiceNow Connector 6.16 - Mule 4

To troubleshoot Anypoint Connector for ServiceNow (ServiceNow Connector), become familiar with the information about interpreting commonly thrown exception messages.

include::connectors::partial$verbose-exception-logs.adoc[]

include::connectors::partial$verbose-logs-com.adoc[]

== Understand Commonly Thrown Exceptions

Here is a list of commonly thrown exception messages and how to interpret them:

* SERVICENOW:BAD_REQUEST

 The request is incorrect, for example, there are invalid input headers or the service does not exist.

* SERVICENOW:CANNOT_DISPATCH

 An error occurs when sending the request.

* SERVICENOW:CONNECTIVITY

 Either a connection could not be established or there is a connectivity error.

* SERVICENOW:ENCODING

 There is an encoding error when parsing the request or the response.

* SERVICENOW:INVALID_WSDL

 The WSDL is invalid or inconsistent.

* SERVICENOW:PROCESSING_ERROR

 There is a processing error, for example, there is an interruption during initialization.

* SERVICENOW:RETRY_EXHAUSTED

 The maximum number of retries for the operation is reached.

* SERVICENOW:SOAP_FAULT

 There is a SOAP fault error.

* SERVICENOW:TIMEOUT

 A specific request takes longer than the configuration timeout values.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:servicenow-reference.adoc[ServiceNow Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
* https://issues.salesforce.com/[Known Issues]
