= Set a Client ID with MQTT 3 Connector

Client IDs are important for MQTT because they identify a connection to an MQTT broker. Moreover, they identify a specific device or client,
and it can be useful in terms of traceability to set a client id that clearly identifies a device's connection to the broker. This is why
it is a recommended practice that this parameter be set explicitly. However, MQTT brokers usually implement a mechanism by which, if new a connection
request is received by the broker, and if that connection's client id coincides with that of an existing connection, the broker will close the old
connection and accept the new one. This mechanism is known as a client take-over. MQTT brokers employ this mechanism to prevent situations such as
TCP connections reaching a half-open or invalid state due to a crash in one of the communication ends, which is undesirable. The broker assumes the
new incoming connection to be valid, closes the older connection, and continues using the newly established connection.


== Client ID Generators

The client-takeover mechanism can become a problem if we want to deploy an application in cluster, and still provide an explicit client id, that
will clearly identify the client. This is why the MQTT 3 Connector, provides client id generators, that will help you either: set a static client id,
set a client id with a dynamic component to adjust to different deployment scenarios or define your own custom client id generator.

=== Client ID Custom Expression Generator

This generator allows you to set a static string prefix and an expression as a suffix. Both are optional, but at least one of them must be
provided in order to generate a client id. If neither parameter is provided, an INVALID_CLIENT_ID exception will be thrown.

So, for example, the following configuration will take the clientId string and append the current date:

[source,xml,linenums]
----
    <mqtt3:config name="MQTT_ClientID_Static_Prefix_And_Expression_Suffix_Config">
        <mqtt3:form-connection username="aziraphale" password="principality" protocol="TCP" host="127.0.0.1" port="${mosquitto.port1}">
            <mqtt3:client-id-generator>
                <mqtt3:client-id-custom-expression-generator clientId="principality-123-" customClientIdSuffix="#[%dw 2.0 output text/plain --- now() as String {format: 'y-MM-dd'}]"/>
            </mqtt3:client-id-generator>
            <mqtt3:connection-options maxInFlight="60" cleanSession="true" />
        </mqtt3:form-connection>
    </mqtt3:config>
----

So, this would generate a client id similar to this one: `principality-123-2020-09-03`.

You could also, only wish to specify an expression as a client id:

[source,xml,linenums]
----
    <mqtt3:config name="MQTT_ClientID_Only_Expression_Suffix_Config">
        <mqtt3:form-connection username="aziraphale" password="principality" protocol="TCP" host="127.0.0.1" port="${mosquitto.port1}">
            <mqtt3:client-id-generator>
                <mqtt3:client-id-custom-expression-generator customClientIdSuffix="#['smart-bentley-' ++ randomInt(1000) as String]"/>
            </mqtt3:client-id-generator>
            <mqtt3:connection-options maxInFlight="60" cleanSession="true" />
        </mqtt3:form-connection>
    </mqtt3:config>
----

Bare in mind that dynamic configurations like the ones shown above, will generate new connections for each new expression value.

On the other hand, you might just want to set a simple string as your client id.

[source,xml,linenums]
----
    <mqtt3:config name="MQTT_Static_ClientID_Config">
        <mqtt3:form-connection username="aziraphale" password="principality" protocol="TCP" host="127.0.0.1" port="${mosquitto.port1}">
            <mqtt3:client-id-generator>
                <mqtt3:client-id-custom-expression-generator clientId="principality-123"/>
            </mqtt3:client-id-generator>
            <mqtt3:connection-options maxInFlight="60" cleanSession="true" />
        </mqtt3:form-connection>
    </mqtt3:config>
----

So this last example, would generate a static client id: `principality-123`.

=== Client ID Random Suffix Generator

This generator allows you to set an optional static string prefix and will add a random uuid as a suffix. If a static prefix is provided, it will
be separated from the random uuid suffix with a '-' character.

[source,xml,linenums]
----
    <mqtt3:config name="MQTT_Static_Prefix_And_Random_Suffix_Config">
        <mqtt3:connection username="mosquitto" password="mosquitto"  url="tcp://127.0.0.1:${mosquitto.port1}">
            <mqtt3:client-id-generator>
                <mqtt3:client-id-random-suffix-generator clientId="smart-bentley-123" />
            </mqtt3:client-id-generator>
            <mqtt3:connection-options maxInFlight="60" cleanSession="true"  />
        </mqtt3:connection>
    </mqtt3:config>
----

This example would generate a client id similar to: `smart-bentley-123-0f321a85-fddf-429f-ba89-26d201db9777`, but each new connection will
have its own randomly generated uuid suffix.

On the other hand, you could omit the clientId prefix, in which case, the generator will assign a random uuid as your client id. So,
the following example, would generate a client id similar to: `0f321a85-fddf-429f-ba89-26d201db9777`

[source,xml,linenums]
----
    <mqtt3:config name="MQTT_Static_Prefix_And_Random_Suffix_Config">
        <mqtt3:connection username="mosquitto" password="mosquitto"  url="tcp://127.0.0.1:${mosquitto.port1}">
            <mqtt3:client-id-generator>
                <mqtt3:client-id-random-suffix-generator />
            </mqtt3:client-id-generator>
            <mqtt3:connection-options maxInFlight="60" cleanSession="true"  />
        </mqtt3:connection>
    </mqtt3:config>
----

=== Use a Custom Client ID Generator

You might just want to supply your own custom client id generator. To achieve, you need to be familiar with the mule sdk subtypes
and the import and export annotations.

To provide your own client id generator you must:

1. Create your own connector project with the mqtt connector as a dependency.
2. In your custom extension, define your implementation for the ClientIDGenerator interface, exposed by the mqtt connector.
3. Define the subtype in your connector definition and export your custom implementation.
4. In studio import your custom connector and the MQTT Connector.
5. Use your custom id generator in an MQTT Connector Configuration.

1. Create your own connector project with the mqtt connector as a dependency.

Create a connector project, and include the mqtt connector as a dependency.

[source,xml,linenums]
----
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.example</groupId>
    <artifactId>mqtt3-extended-connector</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>mule-extension</packaging>
    <name>MQTT Extended Connector</name>

    <parent>
        <groupId>org.mule.extensions</groupId>
        <artifactId>mule-ee-core-modules-parent</artifactId>
    </parent>

    <dependencies>
        <dependency>
            <groupId>com.mulesoft.connectors</groupId>
            <artifactId>mule4-mqtt3-connector</artifactId>
            <version>1.0.0</version>
            <classifier>mule-plugin</classifier>
        </dependency>
    </dependencies>
----

And create your connector's definition class:

[source,java,linenums]
----
@Xml(prefix = "mqtt3-extended")
@Extension(name = "MQTT3Extended", category = SELECT)
public class MQTT3ExtendedConnector {

}
----

2. In your custom extension, define your implementation for the ClientIDGenerator interface, exposed by the mqtt connector.

The MQTT Connector exposes the ClientIDGenerator interface, which only requires that you implement the method generateClientID().
At this point you will need to import this interface, which is exported by the MQTT 3 Connector, using the @Import annotation.

[source,java,linenums]
----
@Xml(prefix = "mqtt3-extended")
@Extension(name = "MQTT3Extended", category = SELECT)
@Import(type = ClientIDGenerator.class)
public class MQTT3ExtendedConnector {

}
----

Now that you can access the ClientIDGenerator interface from your connector, you will need to define an implementation
for it.

[source,java,linenums]
----
@Alias("custom-client-id")
public class MyClientIdGenerator implements ClientIDGenerator {

  /**
   * Client id to be used to identify the connection to the MQTT broker.
   */
  @Parameter
  @DisplayName("Client ID")
  @Optional(defaultValue = "")
  @Expression(NOT_SUPPORTED)
  @ClientId
  protected String clientId;

  private String suffix = "my-custom-suffix";

  /**
   * @return a client ID that results from concatenating the clientId and a randomly generated UUID string.
   */
  @Override
  public String generateClientID() {
    return clientId + (clientId.isEmpty() ? "" : "-") + suffix;
  }
}
----

3. Define the subtype in your connector definition and export your custom implementation.

Now you will need to make this implementation, that you've defined, available to the MQTT 3 Connector. To do this
you need to define your custom implementation as a ClientIDGenerator subtype in your connector class, and also
you will need to export your MyClientIdGenerator class using the Export annotation.

[source,java,linenums]
----
@Xml(prefix = "mqtt3-extended")
@Extension(name = "MQTT3Extended", category = SELECT)
@Import(type = ClientIDGenerator.class)
@Export(classes = {MyClientIdGenerator.class})
@SubTypeMapping(baseType = ClientIDGenerator.class, subTypes = {MyClientIdGenerator.class})
public class MQTT3ExtendedConnector {

}
----

That's all you need to do in your custom connector project. Now we will explain how you can access this new
implementation from your application using the MQTT 3 Connector.

4. In studio import your custom connector and the MQTT Connector.

First, you will need to import both connectors in your application's pom.xml file. For example:

[source,xml,linenums]
----
	<groupId>com.mycompany</groupId>
	<artifactId>mqtt-custom-id-generator</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>mule-application</packaging>

	<name>mqtt-custom-id-generator</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<app.runtime>4.3.0-20210719</app.runtime>
		<mule.maven.plugin.version>3.5.2</mule.maven.plugin.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.0.0</version>
			</plugin>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<sharedLibraries>
						<sharedLibrary>
							<groupId>org.eclipse.paho</groupId>
							<artifactId>org.eclipse.paho.client.mqttv3</artifactId>
						</sharedLibrary>
					</sharedLibraries>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<version>1.5.25</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-sockets-connector</artifactId>
			<version>1.2.1</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.eclipse.paho</groupId>
			<artifactId>org.eclipse.paho.client.mqttv3</artifactId>
			<version>1.2.5</version>
		</dependency>
		<dependency>
		    <groupId>org.example</groupId>
		    <artifactId>mqtt3-extended-connector</artifactId>
		    <version>1.0.0-SNAPSHOT</version>
		    <classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
		    <groupId>com.mulesoft.connectors</groupId>
		    <artifactId>mule4-mqtt3-connector</artifactId>
		    <version>1.0.0</version>
		    <classifier>mule-plugin</classifier>
		</dependency>
	</dependencies>
</project>
----

5. Use your custom id generator in an MQTT Connector Configuration.

Now, if you try to create a new MQTT Connector Config in your application, your custom client id implementation should
have been added to the list of available client id generators. If we used the implementation from the previous example,
our MQTT Connector configuration would look like this:

[source,xml,linenums]
----
<mqtt3:config name="MQTT3_Config">
	<mqtt3:connection username="mosquitto" password="mosquitto" url="tcp://localhost:1883">
		<mqtt3:client-id-generator >
			<mqtt3-extended:custom-client-id clientId="123" />
		</mqtt3:client-id-generator>
	</mqtt3:connection>
</mqtt3:config>
----

