= Salesforce Pub/Sub Connector

Anypoint Connector for Salesforce Pub/Sub (Salesforce Pub/Sub Connector) enables you to connect to the Pub/Sub API, which provides a single interface for publishing and subscribing to platform events, including real-time event monitoring events and change data capture events. This connector complements Anypoint Connector for Salesforce (Salesforce Connector) and provides additional ways to interface with Salesforce's ecosystem. The Salesforce Pub/Sub API enables you to publish and subscribe to events and request schemas and topic information with one API. 

For information about compatibility and fixed issues, refer to the Salesforce Pub/Sub Connector Release Notes.

== Before You Begin

To use this connector, you must be familiar with:

* The Salesforce Pub/Sub Connector’s API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Salesforce Pub/Sub target resource
* Anypoint Platform
* Anypoint Studio version 7.3.5 or later

== Common Use Cases For the Connector

These are some common use cases for Salesforce Pub/Sub Connector:

* Subscribe to event monitoring real-time events
* Subscribe to a standard or high volume platform event, such as `AppointmentSchedulingEvent`
* Publish a platform event (high volume only) back into Salesforce to restrict a user’s profile when they log in to Salesforce after working hours
* Subscribe to change data capture events and syn order data in an external inventory system

For examples of these use cases, refer to xref:salesforce-pubsub-connector-examples.adoc[Salesforce Pub/Sub Connector Examples].

== Connection Types

Salesforce Pub/Sub connections use the following authentication types:

* Basic Authentication +
Uses a username and a password for authentication
* OAuth v2.0 +
Delegates user authentication to the service hosting the user account
* OAuth JWT +
Uses OAuth 2.0 with a JSON Web Token (JWT) request for user authentication
* OAuth Username Password +
Uses OAuth 2.0 with a username and a password for authentication
* OAuth SAML +
Uses OAuth 2.0 with a signed SAML 2.0 assertion to request an access token

For information about configuring authentication types, refer to xref:salesforce-pubsub-connector-studio.adoc#configure-global-element[Configure a Global Element for the Connector].

== Next Step

After you complete the prerequisites, you are ready to create an app and configure the connector using xref:salesforce-pubsub-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:salesforce-pubsub-connector-reference.adoc[Salesforce Pub/Sub Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
