= Processing Events with Salesforce Pub/Sub Connector 

== ReplayID

On the Salesforce Event Bus, each published event message is assigned an opaque ID, which is contained in the `ReplayId` attribute. The `ReplayId` field value is populated by the system when the event is delivered to subscribers and refers to the position of the even within the event stream. 

The event stream has a message durability of 72 hours for the high volume platform events so, using the `ReplayId`, it is possible to receive a message from the stream within that period. 

The following table shows the `ReplayId` options:

[%header%autowidth.spread]
|===
| Replay Option | Description | Usage
| ReplayId | Subscriber receives all stored events after the event specified by its `ReplayId` value and new events. | Catch up on missed events after a certain event message, for example, after a connection failure. To subscribe with a specific replay ID, save the replay ID of the event message after which you want to retrieve stored events. Then use it when you resubscriber.
| `-1` | If no replay option is specified, this is the default. Subscriber receives new events that are broadcast after the client subscribes. | It is best to subscribe with the `-1` option to receive new event messages. To get earlier event messages, don't use this option. 
| `-2` | Subscriber receives all events, including past events that are within the retention window. | Catch up on missed events and retrieve all stored events, for example, after a connection failure. Using this option can slow performance if a large number of event messages are stored. 
|===

The MuleSoft subscriber must carefully track with replayId is process to ensure it doesn't miss or duplicate process events in case of down time and restart (either intention or unintentional).

You are responsible for controlling the replay behavior, which allows advanced replayId tracking to correctly ensure that the event is received and processed. 


== MuleSoft Object Store


