= Salesforce Pub/Sub Connector - Additional Configuration Information - Mule 4

Salesforce Pub/Sub Connector can be used to track whether a platform event has been received and processed from MuleSoft. 

== ReplayID

On the Salesforce Event Bus, each published event message is assigned an opaque ID, which is contained in the `ReplayId` attribute. The `ReplayId` field value is populated by the system when the event is delivered to subscribers and refers to the position of the event within the event stream. 

The event stream has a message durability of 72 hours for the high volume platform events so, using the `ReplayId`, it is possible to receive a message from the stream within that period. 

The MuleSoft subscriber must carefully track which replay ID is processed to ensure it doesn't miss or duplicate process events in case of down time or restart (either intention or unintentional). To enable advanced replay ID tracking to ensure that the event is received and processed correctly, you are given control over the replay behavior. 

The following table shows the `ReplayId` options:

[%header%autowidth.spread]
|===
| Replay Option | Description | Usage
| ReplayId | Subscriber receives all stored events after the event specified by its `ReplayId` value and new events. | Catch up on missed events after a certain event message, for example, after a connection failure. To subscribe with a specific replay ID, save the replay ID of the event message after which you want to retrieve stored events. Then use it when you resubscribe.
| `-1` | If no replay option is specified, this is the default. Subscriber receives new events that are broadcast after the client subscribes. | It is best to subscribe with the `-1` option to receive new event messages. To get earlier event messages, don't use this option. 
| `-2` | Subscriber receives all events, including past events that are within the retention window. | Catch up on missed events and retrieve all stored events, for example, after a connection failure. Using this option can slow performance if a large number of event messages are stored. 
|===


== MuleSoft Object Store

Mule runtime engine (Mule) uses object stores to persist data for eventual retrieval. Mule uses object stores in various filters, routers, and other message processors that need to store states between messages. 

For CloudHub deployments, the free Object Store v2 limits usage to 10 transactions per second (TPS) per application. The premium add-on for Object Store v2 increases the limit to 100 TPS per app.

== Message Durability and Message Replay

The Salesforce event bus stores messages for 72 hours. The responsibility of keeping track of which message have been processed is in the hands of the receiver. Using a combination of Salesforce and Mule, it is possible to keep track of the processed messages,. 

It's recommended to design the pub-sub receiver flow so that it can reasonable recover after an intended or unintended restart. Specifically, this means, the receiver should be configure to pick up events from the last processed ReplayId only. The only way the receiver can get this is by reading a key from the persistent object store. 

=== Buffering the Standard Object Store for Higher Transaction Access

When reading and processing an event, the last processed event is stored to the in-memory object using a key, `LastReplayID_inMemory`.

To transfer the value of that key to the persistent CloudHub object store, you can create a scheduler flow with the following considerations:

* The standard object store allows a maximum of 10 TPS. The scheduler writes every second, which counts as one TPS. 
* If event processing is unexpectedly terminated, then after a restarting the event processing, it's possible that events will be reread from the topic and processed a second time. So you should ensure that the even processing logic you use is idempotent.

== BatcheventSize 

A key feature of Salesforce Pub/Sub Connector is that it allows you to control the number of messages received and processed in a given period of time. 

In a test case, 500 records were created in Salesforce using Apex code. After all the processing completed in Salesforce, the "delta" time between creating the log entry during record creation and the log entry from the confirmation message was analyzed and MuleSoft worker statistics were reviewed. 

In summary:

* Using `BatcheventSize=1` vs 100 triples the time until Salesforce records the processing, which is still in the area of milliseconds. 
* A CloudHub 0.1 vCore worker is sufficient to handle the load. There is no performance improvement when using a 0.2 core worker. 

For more details about this test case, see xref:https://docs.google.com/document/d/1NXLE93nzo7IRy4HSHsxh_InhhDJGv_m_xGo91VDyb3U/edit#heading=h.ormr8aypbrgp[BatcheventSize - How Does it Work?].

== See Also

* For more details and examples of these configurations, see xref:https://docs.google.com/document/d/1NXLE93nzo7IRy4HSHsxh_InhhDJGv_m_xGo91VDyb3U/edit#heading=h.jv94keayzqia[Have my Published Salesforce Platform Events Been Received by My Mule App?]




