= Processing Events with Salesforce Pub/Sub Connector 

== ReplayID

On the Salesforce Event Bus, each published event message is assigned an opaque ID, which is contained in the `ReplayId` attribute. The `ReplayId` field value is populated by the system when the event is delivered to subscribers and refers to the position of the event within the event stream. 

The event stream has a message durability of 72 hours for the high volume platform events so, using the `ReplayId`, it is possible to receive a message from the stream within that period. 

The following table shows the `ReplayId` options:

[%header%autowidth.spread]
|===
| Replay Option | Description | Usage
| ReplayId | Subscriber receives all stored events after the event specified by its `ReplayId` value and new events. | Catch up on missed events after a certain event message, for example, after a connection failure. To subscribe with a specific replay ID, save the replay ID of the event message after which you want to retrieve stored events. Then use it when you resubscribe.
| `-1` | If no replay option is specified, this is the default. Subscriber receives new events that are broadcast after the client subscribes. | It is best to subscribe with the `-1` option to receive new event messages. To get earlier event messages, don't use this option. 
| `-2` | Subscriber receives all events, including past events that are within the retention window. | Catch up on missed events and retrieve all stored events, for example, after a connection failure. Using this option can slow performance if a large number of event messages are stored. 
|===

The MuleSoft subscriber must carefully track which replay ID is processed to ensure it doesn't miss or duplicate process events in case of down time or restart (either intention or unintentional). To enable advanced replay ID tracking to correctly ensure that the event is received and processed, you are given control over the replay behavior. 


== MuleSoft Object Store

Mule runtime engine (Mule) uses object stores to persist data for eventual retrieval. Mule uses object stores in various filters, routers, and other message processors that need to store states between messages. For CloudHub deployments, the free Object Store v2 limits usage to 1- transactions per second (TPS) per application. The premium add-on for Object Store v2 increases the limit to 100 TPS per app.


== Tracking messages

