= Use Flow Designer to Configure Workday Connector 13.0 - Mule 4
:page-aliases: connectors::workday/workday-design-center.adoc, connectors::workday/workday-connector-design-center.adoc

Anypoint Design Center's Flow Designer enables you to create apps visually. To use Flow Designer, work with your Anypoint Platform administrator to ensure that you have a xref:access-management::environments.adoc#to-create-a-new-environment[Design environment]. For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour].

To create an app in Flow Designer:

* Configure the trigger (source) for your app.
* Configure the target component for your app.

For information on connector field values, see
the xref:workday-reference.adoc[Workday Connector Reference].

== Configure the Trigger

Workday Connector provides the *On Modified Objects* trigger, which starts your app when an object is created, modified, or deleted in Workday. Alternatively, you can use:

* *HTTP Listener* to start your app from a browser
or with a command such as `curl`.
* *Scheduler* to start your app on a timed schedule

To configure the trigger:

. In Design Center, click *Create new*.
. Click *Create new application*.
. Specify a value for *Project name*, and click *Create*.
. Click *Go straight to canvas* to exit from *Let's get started*.
. Click the empty trigger card in the middle of the canvas to expand it.
. Configure a trigger for the connector.
+
To use the *On Modified Objects* trigger, enter `workday` in the search field, select *Workday Connector*.
. Click *Add Connection*.
. In the *Connection Name field*, enter a name for the connection.
. In the *Connection Type* field, select whether to use Basic authentication or x.509 Authentication.
. Fill in the required fields.
. Click *Test* to test the connection.
. Click *Save*.

== Configure the Target Component

The target component enables your app to process data received from the trigger. Workday Connector provides operations that you can use to perform tasks for educational organizations, human resources, professional services,
payroll, and benefits administration.

To configure the target component:

. In the *Object Type* field, select the Workday object type.
. Click outside of the dialog.
. Click *+* next to the trigger card.
. In *Select a component*, search for `workday` and select *Workday Connector*.
. Select an operation.
. Click *Edit*.
. Click *Add Connection*.
. In the *Connection Name field*, select the configured connection.
. Fill in the required fields.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
