= Workday - Use Flow Designer to Configure Workday Connector 13.0 - Mule 4
connectors:workday/workday-connector-design-center.adoc

Anypoint Design Center's Flow Designer enables you to create apps visually. To use Flow Designer, work with your Anypoint Platform administrator to ensure that you have a xref:access-management::environments.adoc#to-create-a-new-environment[Design environment]. For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour].

To create an app in Flow Designer:

* Configure the input source (trigger) for your app.
* Configure the target component for your app.

For information on Design Center field values, see
the xref:workday-reference.adoc[Workday Connector Reference].

== Configure the Input Source Trigger

A trigger starts your app. Workday Connector provides the Modified Object Trigger operation that starts your app when an object is created, modified, or deleted in Workday. Alternatively, you can use the HTTP Listener operation to start your app from a browser
or with a command such as `curl`. Another alternative is to use Scheduler to start your app on a timed schedule.

. In Design Center, click *Create*.
. Click *Create new application*.
. Specify a value for *Project name*, and click *Create*.
. Click *Go straight to canvas* to exit from *Let's get started* and go to Flow Designer.
. Click the trigger card.
. If you are using Workday Connector as the input source trigger, search for the connector;
otherwise, you can use HTTP or Scheduler.
. Complete these fields when using the Modified Object Trigger operation:
+
[%header,cols="30s,55a,15a"]
|===
|Field |Description |Required?
|Configuration |Name of the configuration to use. |Yes
|Object Types |Object type that triggers the poll. |Yes
|Scheduling Strategy |Scheduler configuration that triggers your app by polling. |Yes
|Frequency |Polling frequency in time units. |No
|Start delay|Time that Scheduler waits before starting. |No
|Time Unit|Time unit for *Frequency* and *Start delay* values. |Yes
|===
+
. Click *Test*.

Design Center automatically saves all changes.

== Configure the Target Component

The target component enables your app to process data received from the trigger. Workday Connector
provides operations that you can use to perform tasks for educational organizations, human resources, professional services,
payroll, and benefits administration.

. Click *+* next to the trigger card.
. In *Select a component*, search for the Workday Connector.
. Select the connector name.
. Select an operation for the connector.
. Complete these fields:
+
[%header,cols="30s,55a,15a"]
|===
|Field |Description |Required?
|Configuration |Name of the configuration to use. |Yes
|Operation |Type of operation to execute. |Yes
|Content |Payload for the operation. |No
|===
+
. Click the *Test* button to test the connection.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
