= Troubleshooting WebSockets Connector - Mule 4

To troubleshoot Anypoint Connector for WebSockets (WebSockets Connector), become familiar with the information about enabling verbose logging and and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with the WebSockets Connector is failing, temporarily enable verbose logging for WebSockets Connector. +

Remember to always disable the enhanced verbosity after troubleshooting because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="com.mulesoft.connectors.ws" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* WEBSOCKET:CONNECTIVITY

There is an error because the connection is no longer valid. It is disposed of, but you can apply a reconnection policy if defined in the application setup.

* WEBSOCKET:RETRY_EXHAUSTED

There is an error because the maximum number of retries for the operation is reached.

* WEBSOCKET:NO_SUCH_SOCKET

There is an error because a WebSocket is referenced by its id, but no such WebSocket exists.

* WEBSOCKET:BASIC_AUTHENTICATION

There is an error because either the HTTP Request operation lacks basic authentication to send requests to the service, or the provided credentials are incorrect.

* WEBSOCKET:FORBIDDEN

There is an error because the server refuses to give the requested resource because the client does not have access rights to the content.

* WEBSOCKET:INTERNAL_SERVER_ERROR

There is an error because the server encountered a situation that prevented it from fulfilling the request.

* WEBSOCKET:INVALID_SOCKET_ID

There is an error because the WebSocket ID cannot be null or blank.

* WEBSOCKET:NON_UNIQUE_SOCKET_ID

There is an error while the WebSocket was registered because the id already exists.

* WEBSOCKET:NOT_FOUND

There is an error because the server could not find the requested resource.

* WEBSOCKET:REMOTELY_CLOSED

There is an error because the remote host closed connection. This could be a SSL/TLS handshake issue. Check protocols, cipher suites and certificate set up. Use -Djavax.net.debug=ssl for further debugging.

* WEBSOCKET:SERVICE_UNAVAILABLE

There is an error because the server is unable to manage the request because it is down for maintenance or overloaded.

* WEBSOCKET:UNAUTHORIZED

There is an error because authentication failed or has not yet been provided to get the requested response.

== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:websockets-connector-reference.adoc[WebSockets Connector Reference]
