= Troubleshooting WebSockets Connector - Mule 4

To troubleshoot Anypoint Connector for WebSockets (WebSockets Connector), become familiar with the information about enabling verbose logging and and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with the ... is failing, temporarily enable verbose logging for WebSockets Connector. +

Remember to always disable the enhanced verbosity after troubleshooting because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="" level="DEBUG"/>
				<AsyncLogger name="" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.


== Understand Common Throws

Here is a list of common throw messages and how to interpret them:

* WEBSOCKET:CONNECTIVITY


* WEBSOCKET:RETRY_EXHAUSTED


* WEBSOCKET:NO_SUCH_SOCKET


* WEBSOCKET:BASIC_AUTHENTICATION


* WEBSOCKET:FORBIDDEN



* WEBSOCKET:INTERNAL_SERVER_ERROR



* WEBSOCKET:INVALID_SOCKET_ID



* WEBSOCKET:NON_UNIQUE_SOCKET_ID



* WEBSOCKET:NOT_FOUND



* WEBSOCKET:REMOTELY_CLOSED



* WEBSOCKET:SERVICE_UNAVAILABLE



* WEBSOCKET:UNAUTHORIZED


== See Also
* https://help.mulesoft.com[MuleSoft Help Center]
* xref:websockets-connector-reference.adoc[WebSockets Connector Reference]
