= About the File Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Release Notes: xref:release-notes::connector/connector-file.adoc[File Connector Release Notes]

The File connector handles files and folders on a locally mounted file system. Its main features include:

// INCLUDE FOR file, ftp, and sftp connectors
include::partial$common-file-actions.adoc[]

For information on error conditions, see the xref:file/file-documentation.adoc[File Connector Reference].

[[connection_settings]]
== Configure the File Connector

The File connector does not always require configuration. However, it is good practice to define one. The most important configuration parameter is the Working Directory (`workingDir`), which is the path to a directory that is treated as the root of every relative path that you specify with this connector. If you do not provide a working directory, the connector configuration defaults to the value of the `user.home` system property. If the system property is not set, the connector  fails to initialize.

You can also set the default encoding to use when writing files. It defaults to Mule runtime's default encoding. If you use any File connector operations without referencing a configuration, the operation uses the default values.

This example sets a working directory for the File connector:

[source,xml,linenums]
----
<file:config name="File_Config">
  <file:connection workingDir="/Users/me/myfiles" />
</file:config>
----

//INCLUDED IN FTP, SFTP, FILE
include::partial$common-file-attributes.adoc[]

[[see_also]]
== See Also

* xref:file/file-documentation.adoc[File Connector Documentation Reference]
* xref:file/file-read.adoc[Read Files]
* xref:file/file-write.adoc[Write Files]
* xref:file/file-list.adoc[List Files]
* xref:file/file-on-new-file.adoc[Listen for New or Modified Files]
* xref:file/file-copy-move.adoc[Copy or Move Files]
