= To List Files Using the File Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: file, connector, list, directory



The List operation returns a List of Messages, where each message represents any file or folder found within the Directory Path (`directoryPath`).

By default, the operation does not read or list files or folders within any sub-folders of `directoryPath`.

To list files or folders within any sub-folders, you can set the `recursive` parameter to `true`.

This example lists all messages in a `directoryPath`, without listing the contents of any sub-folders. Note that the path can be absolute, or it can be relative to a Working Directory (`workingDir`) set in the File configuration (through `<file:config/>`).

[source,xml,linenums]
----
<flow name="list">
  <file:list directoryPath="~/dropFolder" />
  <foreach>
    <choice>
      <when expression="#[attributes.directory]">
        <flow-ref name="processDirectory" />
      </when>
      <otherwise>
        <logger message="Found file #[attributes.path] which content is #[payload]" />
      </otherwise>
    </choice>
  </foreach>
</flow>
----

The example above lists the contents of a folder, then uses the For Each and Choice components to handle each directory in the list differently than it handles each file.

== Matching
You can use the `<file:matcher>` element to filter files based on the matching criteria you use for accepting or rejecting a file. Here is an example of file matching rules you can use:

.Example: File Matcher
[source,xml,linenums]
----
<file:matcher
  filename-pattern="a?*.{htm,html,pdf}"
  path-pattern="a?*.{htm,html,pdf}"
  createdSince="2015-06-03T13:21:58+00:00"
  createdUntil="2015-07-03T13:21:58+00:00"
  updatedSince="2015-05-03T13:21:58+00:00"
  updatedUntil="2015-06-03T13:21:58+00:00"
  accessedSince="2015-06-03T13:21:58+00:00"
  accessedUntil="2015-06-03T13:21:58+00:00"
  directory="true|false"
  regularFile="true|false"
  symbolicLink="true|false"
  minSize="0"
  maxSize="1024" />
----

All of the attributes above are optional and are ignored if not provided. They all relate to each other under an `AND` operator.

As the next examples show, a file matcher can be a reusable element (a named top-level element), or it can be used as an inner element that is proprietary to a particular component.

=== Example: Top-level, Reusable Matcher

[source,xml,linenums]
----
<file:matcher name="smallFileMatcher" maxSize="100" />

<flow name="smallFiles">
  <file:list path="~/smallfiles" matcher="smallFileMatcher" />
  ...
</flow>
----

=== Example: Inner, Non-reusable Matcher

[source,xml,linenums]
----
<flow name="smallFiles">
	<file:list path="~/smallfiles">
        <file:matcher maxSize="100" />
	</file:list>
	...
</flow>
----

For more on the capabilities of the matcher, see xref:file/file-documentation.adoc[File Connector Documentation Reference].

//== STREAMING INCLUDE in File, FTP, and SFTP Connector docs
include::partial$common-streaming.adoc[]