= X12 EDI Connector 2.5.0 - Mule 4
:page-aliases: connectors::x12-edi/x12-edi-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Premium] +

Anypoint Connector for X12 EDI lets you convert X12 messages to and from DataWeave-compatible representations using lists and maps.
The schema definitions for all https://docs.mulesoft.com/connectors/x12-edi/x12-edi-versions-x12[supported X12 standard transaction sets] are provided.

Many HIPAA document versions are also supported, as listed separately in the https://docs.mulesoft.com/connectors/x12-edi/x12-edi-versions-hipaa[Connector HIPAA reference page].

== Prerequisites

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

* To use the X12 EDI connector in a production environment, you must
have purchased a MuleSoft license for Anypoint B2B.

* Anypoint Studio version <7.0> or later

NOTE: X12 EDI Connector supports files of up to 15 MB, and the memory requirement is roughly 40 to 1.
For example, a 1-MB file requires up to 40 MB of memory to process, so it's important to consider this memory requirement in conjunction with your TPS needs for large X12 files.
This is not an exact figure; the value might vary according to the complexity of the mapping instructions.

// == Common Use Cases for the Connector

// Make the title singular if there is just one use case
// Add a lead in sentence and then list common use cases for the connector
// Make the title singular if there is just one case

// For examples, see xref:<connector-name>-connector-examples.adoc[Examples].

== Audience
// Adjust this list as necessary. Not all connectors include an Additional Configuration topic

* New users, read:
** xref:<connector-name>-connector-studio.adoc[Use Studio to Configure the Connector] to create your Mule app
** xref:<connector-name>-connector-config-topics.adoc[Additional Configuration Information]
to help extend your understanding of the <connector-name> connector
** xref:<connector-name>-connector-examples.adoc[Examples], which provide one or more use cases for the connector
* Advanced users, read:
** xref:<connector-name>-connector-xml-maven.adoc[XML and Maven Support]
** xref:<connector-name>-connector-config-topics.adoc[Additional Configuration Information] to help extend your understanding of the <connector-name> connector
** xref:<connector-name>-connector-examples.adoc[Examples], which provides one or more use cases for the connector

// The following line is only needed for connectors with upgrade information
For a major or minor release, see
xref:<connector-name>-connector-upgrade-migrate.adoc[Upgrade and Migrate].


== Configure Schemas

Configure schemas to describe your messages according to your implementation.

=== About the EDI Schema Language

The X12 EDI Module uses a YAML format called ESL (for EDI Schema Language) to represent EDI schemas. Basic ESLs define the structure of EDI messages in terms of structures (transaction sets, in X12 terminology), groups (loops, in X12), segments, composites, and elements. ESLs for the all https://docs.mulesoft.com/connectors/x12-edi/x12-edi-versions-x12[supported X12 versions] are included. A set of https://docs.mulesoft.com/connectors/x12-edi/x12-edi-versions-hipaa[HIPAA variations] of base X12 transaction sets are also included.
// See the separate HIPAA documentation page for more details listed in the See Also section of this document.

You can customize the X12 schema definitions to suit your data by defining an overlay schema. An overlay schema is a special form of ESL that allows you to modify a base schema, such as an X12 4010 850 schema, with your specific conventions. You don't need an overlay schema if you're using the structure defined by the standard, but most EDI exchanges modify the base definitions in an implementation convention.

You can also define your own schemas from scratch, or copy and edit a base X12 schema definition to suit your data. See the EDI Schema Language Reference for more details.
// Listed in the See Also section of this document.

[NOTE]
====
YAML uses a combination of lists and sets of key-value pairs. The order of
values is not important, as long as the required items are present. Quotes
(either single or double quotes) are used around values that may consist
of digits but are meant to be interpreted as strings (since otherwise the
YAML parser treats the values as numbers). Indentation is used to show the nesting of lists.

For readability, the ESL structures shown here define all simple key-value
pairs before any lists that are part of the same definition.
====

=== Specify a Schema According to your Implementation Convention

To Define your implementation convention with an overlay schema:

. Create an overlay schema that imports the base schema you want to customize - for example, X12 005010 850.
. Customize the overall structure for segment usage, positions, groups, and counts.
. Customize segments, including usage and counts.

Overlay schemas are very similar in structure to a xref:1.0@partner-manager::edi-schema-language-reference.adoc[complete schema definition], but instead of providing all the details of the schema structure they only list changes. Overlay schemas specify how to use implementation conventions with a particular trading partner to extend and customizes the standard.

The following example provides the start of a sample overlay schema that modifies the basic X12 005010 850 transaction set definition. This example customizes the CUR segment and specifies that it is unused, thereby ensuring it is hidden from the mapping structures in Anypoint Studio.

[source,yaml,linenums]
----
form: X12
version: '005010'
imports: [ '/x12/005010/850.esl' ]
structures:
- idRef: '850'
  name: Purchase Order
  class: PO
  heading:
  - { idRef: 'CUR', position: '0400', usage: U }
----

=== Structure Overlay

A structure overlay details modifications to the base schema definition of an X12 transaction set. Most often these modifications take the form of marking segments or groups in the base definition as unused, but any usage or repetition count change is allowed.

The following is the form taken by a structure overlay:

[source,yaml,linenums]
----
- idRef: '850'
  heading:
  - { idRef: 'CUR', position: '0400', usage: U }
  - { idRef: 'PER', position: '0600', usage: U }
  - groupIdRef: 'N9_Loop'
    position: '2950'
    items:
    - { idRef: 'DTM', position: '2970', usage: U }
    - { idRef: 'PWK', position: '3050', usage: U }
    - { idRef: 'EFI', position: '3080', usage: U }
----

The modifications in this example specify that the CUR and PER segments of the standard 850 heading are not being used, along with the segments in the N9 loop.

The key-value pairs at the structure level are:

[%header,cols="30a,70a"]
|===
|Key |Description
|idRef |The ID for the transaction set being modified.
|name |The transaction set name (optional).
|heading, detail, summary |List of segment and group modifications within each section of the structure. These are optional, and each is only used when there are modifications to that section.
|===

The lists of segment modifications for the different sections of the structure (heading, detail, summary) all use the same structure. Each item in the list is either a segment reference or a group definition. Segment references are shown using a compact YAML syntax where the values for each reference are given as comma-separated key-value pairs enclosed in curly braces. The values are:

[%header,cols="30a,70a"]
|===
|Key |Description
|idRef |The referenced segment ID. This is optional and verified if provided, but otherwise ignored. The position value is used to uniquely identify segments within the section.
|position |The segment position within the transaction set section.
|usage |Usage code, which may be M for Mandatory, O for Optional, C for Conditional, or U for Unused.
|count |Maximum repetition count value, which may be a number or the special value `>1` meaning any number of repeats. The count value is optional and a base definition value is used if a value is not specified.
|===

Group overlays are shown in expanded form, with key-value pairs on separate lines. The values in a group definition are:

[%header,cols="30a,70a"]
|===
|Key |Description
|groupIdRef |The referenced group ID. This key is optional and verified if provided, but otherwise ignored. The position value is used to uniquely identify a group within a section.
|position |The segment position within the transaction set section.
|usage |Usage code, which may be M for Mandatory, O for Optional, C for Conditional, or U for Unused.
|count |Maximum repetition count value, which may be a number or the special value `>1` meaning any number of repeats. The count value is optional and a base definition value is used if a value is not specified.
|items |List of segments (and potentially nested loops) making up the loop.
|===

=== Segment Overlays

A segment overlay again details modifications to the base schema definition. Most often these modifications take the form of marking elements or composites in the base definition as unused, but any usage or repetition count change is allowed. Here are some sample segment overlays:

[source,yaml,linenums]
----
segments:
- { idRef: AMT, trim: 3 }
- idRef: BEG
  values:
  - { position: 4, usage: U }
- { idRef: DTM, trim: 3 }
- idRef: ITD
  values:
  - { position: 4, usage: U }
  - { position: 6, usage: U }
----

The above example uses the compact form for segment modifications that only involve a truncation, while modifications that make changes to individual values are expressed in expanded form. As with all the other YAML examples, the two forms are actually equivalent and can be used interchangeably.

NOTE: Segment overlays do not automatically apply to all uses of a segment, they are only effective for segments referenced within a structure overlay. The structure overlay doesn't need to make any changes to the usage of the segment, but must reference the segment at the appropriate position(s) so that the segment overlay is used to modify the base definition.

The key-value pairs in a segment overlay are:

[%header,cols="30a,70a"]
|===
|Key |Description
|idRef |Segment identifier.
|trim |Trim position in segment, meaning all values from this point on are marked as unused (optional).
|values |List of individual value modifications.
|===

The values list references values in the segment by position. The key-value pairs for these references are:

[%header,cols="30a,70a"]
|===
|Key |Description
|position |The value position within the segment.
|name |The name of the value in the segment (optional, base definition value used if not specified).
|usage |Usage code, which may be M for Mandatory, O for Optional, C for Conditional, or U for Unused.
|count |Maximum repetition count value, which may be any number or the special value `>1` meaning any number of repeats. The count value is optional and a base definition value is used if a value is not specified.
|===
== Set Your Schema Locations

To use the connector, you need to know the locations of the schemas
in your project. If you're using out-of-the-box X12 schemas and
not customizing anything, the schema location follows the
`/x12/{version}/{transaction set}.esl` pattern. For example, if you're using the 005010 version and the 850 transaction set, your schema location is `/x12/005010/850.esl`.

If you're using one or more custom schemas, you should put these under
a directory in `src/main/app` and refer to the location relative to this directory.
For example, if you've put your 850 schema (either overlay or full) under `src/main/app/mypartner/850.esl,
your schema location is `/mypartner/850.esl`.

You can configure schema locations in the Anypoint Studio XML view. The schema files are loaded when the connector is initialized,
thus runtime expressions such as flow variables are not supported.

To configure schemas in Anypoint Studio, switch to the XML view by clicking Configuration XML and modify your X12 EDI configuration to
 include a list of all the schemas you wish to use by adding an `+<x12:schema>+` element for each document type:

[source,xml,linenums]
----
<x12-edi:config name="X12_EDI__Configuration" identKeys="true" doc:name="X12 EDI: Configuration">
  <x12-edi:schemas>
    <x12:schema value="/x12/005010/850.esl"/>
  </x12-edi:schemas>
</x12-edi:config>
----

If you don't include any schemas in the configuration, X12 EDI will attempt to load an appropriate schema at runtime for each transaction set, using the
standard X12 schema definitions provided with the connector. However, in this case you won't see any metadata to define the structure of the
data passed in and out of the connector.

If the schema definition configuration includes a 997 or 999 Functional Acknowledgmet schema then that schema will be used to generate Functional Acknowledgments. **Note:** To use the Functional Acknowledgment schema type (997 or 999) it must match the `generate999Acks` Parser parameter (`false` for 997, true for `999`).

== About the X12 Message Structure

The connector enables reading or writing of X12 documents into or from the canonical EDI message structure. This structure is represented as a hierarchy of Java Maps and Lists, which can be manipulated using DataWeave or code. Each transaction has its own structure, as defined in the schemas, as outlined above.

The message itself contains the following keys (some of which only apply to either the read operation or the write operation, as indicated):

[%header%autowidth.spread]
|===
|Key name |Description
|Delimiters (optional) |The delimiters used for the message (set based on the last interchange processed by a read operation). If set for a write operation this overrides the values in the module configuration. The characters in the string are interpreted based on position, in the following order: (data separator), (sub-element separator), (repetition separator, or 'U' if none), (segment terminator).
|Errors (read only) |A list of errors that are associated with the input as a whole, or with interchanges with no valid transaction sets. See the X12Error structure description in the To Read and Validate X12 EDI Messages section below.
|FunctionalAcksGenerated (read only) |A list of 997 or 999 acknowledgments (as configured) that were generated by the module during the read operation. To send an acknowledgment, see the Sending Acknowledgments section below.
|Group (write only) |Map of GS group header segment values used as defaults when writing groups.
|Interchange (write only) |Map of ISA interchange header segment values used as defaults when writing interchanges.
|InterchangeAcksGenerated (read only) |A list of TA1 acknowledgments that were generated by the module during the read operation.
|InterchangeAcksReceived (read only) |A list of TA1 acknowledgments that were received by the module during the read operation.
|InterchangeAcksToSend (write only) |A list of TA1 acknowledgments that are to be sent by the module during the write operation.
|Transactions |A hierarchy of the transaction sets which were read by the module during a read operation, or which are to be sent by the module during a write operation. The value of this top-level key is a map with standard versions as keys, in the form "v005010" (for instance). For example, if you are using version 005010 850 and 855 transaction sets, the Transactions would contain a map with one key, "v005010". The value of this key would be another map, this one with two keys, "850" and "855". Each of these would contain a list of individual 850 and 855 transaction sets that you could then process. If you're using 997 functional acknowledgments "997" is the key for a list of 997 transaction sets.
|===

Individual transaction sets have their own maps, with the following keys:

[%header%autowidth.spread]
|===
|Key |Description
|Detail |Map of segments or loops from the detail section of the transaction set. Values are maps for segments or loops which occur at most once, lists of maps for values which may be repeated.
|Errors (read only) |A list of errors which are associated with the transaction set. (See the X12Error class description in the Reading and Validating EDI Messages section below.)
|Group |Map of GS group header segment values. When reading a message, this map is the actual data from the enclosing group (a single map linked from all transaction sets in the group). When writing a message, these values are used for creating the enclosing group. Values not populated in this map default to the values from the Group map at the message level.
|Heading |Map of segments or loops from the heading section of the transaction set. Values are maps for segments or loops which occur at most once, lists of maps for values which may be repeated.
|Id |Transaction ID, which must match the key of the containing transaction list.
|Interchange |Map of ISA interchange header segment values. When reading a message, this map is the actual data from the enclosing interchange (a single map linked from all transaction sets in the interchange). When writing a message, these values are used for creating the enclosing interchange (gathering transactions with the same interchange values into a single interchange, regardless of whether the actual maps are the same or not). Values not populated in this map default to the values from the Interchange map at the message level.
|Name |Transaction set name.
|SetHeader |Map of ST transaction set header segment values. This gives the actual header data for a read operation, and allows you to provide overrides for configuration settings for a write operation.
|Summary |Map of segments or loops from the summary section of the transaction set. Values are maps for segments or loops which occur at most once, lists of maps for values which may be repeated.
|===

Generated 997/999 functional acknowledgment transactions differ from received messages in their handling of interchange information:

[%header%autowidth.spread]
|===
|Key name |Description
|Interchange |Map of ISA interchange header segment values. For functional acknowledgments generated by receive processing, this map is a copy of the data for the containing interchange with sender and receiver identification components (ISA05/ISA06 and ISA07/ISA08) interchanged. When writing a message, these values are used for creating the enclosing interchange (gathering transactions with the same interchange values into a single interchange, regardless of whether the actual maps are the same or not). Values not populated in this map default to the values from the Interchange map at the message level.
|===

TA1 interchange acknowledgments are in the form of maps representing the TA1 segment data and linked to data on the corresponding interchange:

[%header%autowidth.spread]
|===
|Key name |Description
|Interchange |Map of ISA interchange header segment values. For TA1 acknowledgments generated by receive processing, this map is a copy of the data for the interchange matching the TA1 with sender and receiver identification components (ISA05/ISA06 and ISA07/ISA08) interchanged. When writing a message, these values are used for creating the enclosing interchange (gathering transactions with the same interchange values into a single interchange, regardless of whether the actual maps are the same or not). Values not populated in this map default to the values from the Interchange map at the message level.
|===

== About Time Fields

All X12 Time fields are represented as Integer values for the number of milliseconds.
For example, if a message has the value `024020`, its DataWeave mapping
appears as `9620000` milliseconds.

The value `024020` is in the format "HHMMSS", so if we convert it to milliseconds, use this formula:

----
(02*3600000) + (40*60000) + (20*1000) = 9620000
----

== See Also

* xref:release-notes::connector/x12-edi-connector-release-notes-mule-4.adoc[X12 EDI Connector Release Notes]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-x12-connector/[X12 EDI Connector in Anypoint Exchange]
* http://www.x12.org/x12-work-products/x12-transaction-sets.cfm[ASC X12 Transaction Sets]
* https://en.wikipedia.org/wiki/X12_Document_List[X12 Document List]
* xref:1.0@partner-manager::edi-schema-language-reference.adoc[EDI Schema Language Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
