= X12 EDI Connector 2.5.0 - Mule 4
:page-aliases: connectors::x12-edi/x12-edi-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Premium] +

Anypoint Connector for X12 EDI enables you to convert X12 messages to and from DataWeave-compatible representations using lists and maps.
The schema definitions for all xref:x12-edi-x12-edi-versions-x12.adoc[supported X12 standard transaction sets] are provided.

Many HIPAA document versions are also supported, as listed separately in the xref:x12-edi-x12-edi-versions-hipaa.adoc[Connector HIPAA reference page].

== Prerequisites

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

+ To use the X12 EDI connector in a production environment, you must have:

* purchased a MuleSoft license for Anypoint B2B.

* Anypoint Studio 7.0 or later

[NOTE]

X12 Connector supports files of up to 15 MB in size, and the memory requirement is approximately 40 to 1.
For example, a 1-MB file requires up to 40 MB of memory to process, so it's important to consider this memory requirement in conjunction with your Transactions Per Second (TPS)  needs for large X12 files.
This is not an exact figure; the value varies according to the complexity of the mapping instructions.

// == Common Use Cases for the Connector - there are currently no use cases for this connector.

// Make the title singular if there is just one use case
// Add a lead in sentence and then list common use cases for the connector
// Make the title singular if there is just one case

// For examples, see xref:<connector-name>-connector-examples.adoc[Examples].

== Audience
// Adjust this list as necessary. Not all connectors include an Additional Configuration topic

* New users, read:
** xref:<connector-name>-connector-studio.adoc[Use Studio to Configure the Connector] to create your Mule app
** xref:<connector-name>-connector-config-topics.adoc[Additional Configuration Information]
to help extend your understanding of the <connector-name> connector
** xref:<connector-name>-connector-examples.adoc[Examples], which provide one or more use cases for the connector
* Advanced users, read:
** xref:<connector-name>-connector-xml-maven.adoc[XML and Maven Support]
** xref:<connector-name>-connector-config-topics.adoc[Additional Configuration Information] to help extend your understanding of the <connector-name> connector
** xref:<connector-name>-connector-examples.adoc[Examples], which provides one or more use cases for the connector

// The following line is only needed for connectors with upgrade information
// For a major or minor release, see
// xref:<connector-name>-connector-upgrade-migrate.adoc[Upgrade and Migrate].

== About the EDI Schema Language

The X12 EDI Connector uses a YAML format called ESL (for EDI Schema Language) to represent EDI schemas.
Basic ESLs define the structure of EDI messages in terms of structures (known as transaction sets in X12 terminology), groups (known as loops, in X12), segments, composites, and elements.
ESLs for the all xref:x12-edi-x12-edi-versions-x12.adoc[supported X12 versions] are included.
If you are using HIPAA, then a set of xref:x12-edi-versions-hipaa.adoc[HIPAA variations] of base X12 transaction sets are included.

You can customize the X12 schema definitions to suit your data by defining an overlay schema. An overlay schema is a special form of ESL that allows you to modify a base schema, such as an X12 4010 850 schema, with your specific conventions.
You don't need an overlay schema if you're using the structure defined by the standard, but most EDI exchanges modify the base definitions in an implementation convention.

You can also define your own schemas from scratch, or copy and edit a base X12 schema definition to suit your data as seen in the EDI Schema Language Reference.

=== Readability
YAML uses a combination of lists and sets of key-value pairs. The order of
values is not important, as long as the required items are present. Quotes
(such as single or double) are used around values that consist
of digits but are meant to be interpreted as strings (otherwise the
YAML parser treats the values as numbers). Indentation is used to show the nesting of lists.

The ESL structures shown here defines all simple key-value pairs before any lists that are part of the same definition.

== About Schema Locations

To use the connector, you need to know the locations of the schemas
in your project. If you're using out-of-the-box X12 schemas and
not customizing anything, the schema location follows the
`/x12/{version}/{transaction set}.esl` convention.
For example, using the 005010 version and the 850 transaction set, has a schema location of `/x12/005010/850.esl`.

If you're using one or more custom schemas, refer to xref:x12-edi-x12-edi-connector-config-topics.adoc[XML Schema and Trading Partner Configuration] for complete information on setting your schema locations.

== About the X12 Message Structure

The connector enables reading or writing of X12 documents into or from the canonical EDI message structure.
This structure is represented as a hierarchy of Java Maps and Lists that can be manipulated using DataWeave or code.
Each transaction has its own structure as defined in the schemas.

The message itself contains the following keys (some of which only apply to either the read operation or the write operation, as indicated):

[%header%autowidth.spread]
|===
|Key name |Description
|Delimiters |The delimiters used for the message. If used, this set based on the last interchange processed by a read operation. If set for a write operation this overrides the values in the module configuration. The characters in the string are interpreted based on position, in the following order: data separator, sub-element separator, repetition separator, or 'U' if none, segment terminator.
|Errors (read only) |A list of errors that are associated with the input as a whole, or with interchanges with no valid transaction sets. For more information, refer to the EXAMPLES the X12Error structure description in the To Read and Validate X12 EDI Messages section.
|FunctionalAcksGenerated (read only) |A list of 997 or 999 configured acknowledgments that are generated by the module during the read operation. To send an acknowledgment, see the EXAMPLES Sending Acknowledgments.
|Group (write only) |Map of GS group header segment values used as defaults when writing groups.
|Interchange (write only) |Map of ISA interchange header segment values used as defaults when writing interchanges.
|InterchangeAcksGenerated (read only) |A list of TA1 acknowledgments that were generated by the module during the read operation.
|InterchangeAcksReceived (read only) |A list of TA1 acknowledgments that were received by the module during the read operation.
|InterchangeAcksToSend (write only) |A list of TA1 acknowledgments that are to be sent by the module during the write operation.
|Transactions |A hierarchy of the transaction sets that are read by the module during a read operation, or are to be sent by the module during a write operation. The value of this top-level key is a map with standard versions as keys, in the form 'v005010`.
For example, if you are using version 005010 850 and 855 transaction sets, the Transactions would contain a map with one key, `v005010`. The value of this key would be another map, one with two keys, "850" and "855". Each of these would contain a list of individual 850 and 855 transaction sets that can be processed. If you're using 997 functional acknowledgments `997` is the key for a list of 997 transaction sets.
|===

Individual transaction sets have their own maps, with the following keys:

[%header%autowidth.spread]
|===
|Key |Description
|Detail |Map of segments or loops from the detail section of the transaction set. Values are maps for segments or loops that occur at most once, lists of maps for values which can be repeated.
|Errors (read only) |A list of errors that are associated with the transaction set. (See the X12Error class description in the Reading and Validating EDI Messages section in EXAMPLES).
|Group |Map of GS group header segment values. When reading a message, this map is the actual data from the enclosing group (a single map linked from all transaction sets in the group). When writing a message, these values are used for creating the enclosing group. Values not populated in this map default to the values from the Group map at the message level.
|Heading |Map of segments or loops from the heading section of the transaction set. Values are maps for segments or loops that occur at most once, lists of maps for values which may be repeated.
|Id |Transaction ID, this must match the key of the containing transaction list.
|Interchange |Map of ISA interchange header segment values. When reading a message, this map is the actual data from the enclosing interchange (a single map linked from all transaction sets in the interchange). When writing a message, these values are used for creating the enclosing interchange (gathering transactions with the same interchange values into a single interchange, regardless of whether the actual maps are the same or not). Values not populated in this map default to the values from the Interchange map at the message level.
|Name |Transaction set name.
|SetHeader |Map of ST transaction set header segment values. This gives the actual header data for a read operation, and allows you to provide overrides for for write operation configuration settings.
|Summary |Map of segments or loops from the summary section of the transaction set. Values are maps for segments or loops that occur at most once, lists of maps for values that can be repeated.
|===

Generated 997/999 functional acknowledgment transactions differ from received messages in their handling of interchange information:

[%header%autowidth.spread]
|===
|Key name |Description
|Interchange |Map of ISA interchange header segment values. For functional acknowledgments generated by receive processing, this map is a copy of the data for the containing interchange with sender and receiver identification components (ISA05/ISA06 and ISA07/ISA08) interchanged. When writing a message, these values are used for creating the enclosing interchange (gathering transactions with the same interchange values into a single interchange, regardless of whether the actual maps are the same or not). Values not populated in this map default to the values from the Interchange map at the message level.
|===

TA1 interchange acknowledgments are in the form of maps representing the TA1 segment data and linked to data on the corresponding interchange:

[%header%autowidth.spread]
|===
|Key name |Description
|Interchange |Map of ISA interchange header segment values. For TA1 acknowledgments generated by receive processing, this map is a copy of the data for the interchange matching the TA1 with sender and receiver identification components (ISA05/ISA06 and ISA07/ISA08) interchanged. When writing a message, these values are used for creating the enclosing interchange (gathering transactions with the same interchange values into a single interchange, regardless of whether the actual maps are the same or not). Values not populated in this map default to the values from the Interchange map at the message level.
|===

== About Time Fields

All X12 Time fields are represented as Integer values for the number of milliseconds.
For example, if a message has the value `024020`, its DataWeave mapping
appears as `9620000` milliseconds.

The value `024020` is in the format "HHMMSS", so to convert it to milliseconds, use this formula:

----
(02*3600000) + (40*60000) + (20*1000) = 9620000
----

== Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
that you can use as starting points for your apps and examples that illustrate a complete solution.

////
List and link to up to 10 Exchange templates and examples.
Use the Integration Pattern categories (broadcast, migration, bidirectional sync, aggregation).
////

== Next Step

After you complete the prerequisites, you are ready to create your own app and configure the connector using xref:<connector-name>-connector-studio.adoc[Anypoint Studio].

== See Also
////
xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
////
xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
https://help.mulesoft.com[MuleSoft Help Center]
