= X12 EDI Connector 2.5 - Examples - Mule 4

Use this example to translate outbound enterprise purchase order XML messages from back-end ERP into EDI X12 850 transactions. This validates inbound EDI purchase orders received, translate to an Enterprise purchase order with a JSON structure, and integrate with back-end systems.

== Transforming Outbound XML Purchase Order Messages to X12 EDI 850 Transactions

 This use case has two fictional enterprises: NTO Retailer and Mythical Supplier,
 both exchanging purchase orders as outlined in the following diagram:



The flow for this example shows:

* At the NTO Retailer: Translate outbound enterprise purchase order XML messages from back-end ERP into EDI X12 850 transactions.

* At Mythical Supplier: Validate inbound EDI purchase orders received, translate to enterprise purchase order JSON structure, and integrate with back-end systems.

The example uses an HTTPS Listener as the message source to receive enterprise purchase order XML messages from back-end systems, DataWeave and X12 Writes to translate the XML message into an X12 v4010 850 Purchase order EDI message. The generated X12 message is published to an Anypoint MQ queue, and sent to Mythical Supplier via AS2.

== Prerequisites

The example uses static configurations for X12 identifiers and Anypoint MQ. They can be replaced with expressions for dynamic routing and setting up of identifiers.

. Open the Example project in Anypoint Studio from Anypoint Exchange.
. Install the latest version of Anypoint X12 connector.
. Update the configuration property file located in `src/main/resources/app.properties` with these values:

`tls-truststore.password=test`

`tls-keystore.password=muletest`

=== Configuring Anypoint MQ

. From Anypoint MQ console create a new Anypoint MQ called: `queue b2b-outbound-mythical-as2.q`.

. Create a new client app in Anypoint MQ console.

. Update these properties in the `app.properties` file with the API URL, Client Id and Client Secret for the Anypoint MQ connection:

`anypoint-mq.url`

`anypoint-mq.clientid`

`anypoint-mq.clientsecret`

. Deploy the example to CloudHub or run it locally.

== Running the Example

. Using a REST Client, POST the XML payload `src/main/resources/Enterprise-Outbound-PO.xml` to https://localhost:8443/b2b/enterprise-ob-po/ or https://app-name.cloudhub.io/b2b/enterprise-ob-po/ if deployed to CloudHub.

You see the raw EDI X12 850 purchase order transaction returned as the response. It is also published to the Anypoint MQ queue `b2b-outbound-mythical-as2.q`, ready to be sent to the trading partner.







== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
