= HL7 MLLP Connector 2.1 - Mule 4
:page-aliases: connectors::hl7/hl7-mllp-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Premium]

Anypoint Connector HL7 Minimal Lower-Layer Protocol (MLLP) Connector (HL7 MLLP Connector) provides connectivity and parsing functionality for HL7 MLLP messages.

For compatibility information and fixed issues, see the HL7 MLLP Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* Anypoint Connectors

* Mule runtime engine (Mule)

* Elements and global elements in a Mule flow

* Creating a Mule app using Anypoint Studio (Studio)

* HL7 MLLP Connector

To use HL7 MLLP Connector, you must have:

* Purchased a MuleSoft license for HL7. Contact your Account Representative about purchasing a license.

* Anypoint Studio 7.0 or later

* Java 8

== See Also

* xref:release-notes::connector/hl7-mllp-connector-release-notes-mule-4.adoc[HL7 MLLP Connector Release Notes]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-hl7-mllp-connector/[HL7 MLLP Connector in Anypoint Exchange]
