= About the FTP Connector
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Release Notes: xref:release-notes::connector/connector-ftp.adoc[FTP Connector Release Notes]

This connector provides access to files and folders on an FTP server. Its main features include:

// INCLUDE FOR file, ftp, and sftp connectors
include::partial$common-file-actions.adoc[]

[[connection_settings]]
== Connect to an FTP Server

You set up a connection through an `ftp:config` element, for example:

[source,xml,linenums]
----
<ftp:config name="ftp">
  <ftp:connection username="anonymous" password="password" host="localhost" port="${ftpPort}" workingDir="${workingDir}"/>
</ftp:config>
----

The `workingDir` provides the path to a directory that is treated as the root of every relative path used with this connector. If the directory is not provided, the remote server’s default serves as the working directory.
The `username`, `password`, `host`, and `port` attributes are self explanatory.

// Included in FTP, SFTP
include::partial$common-dynamic-connections.adoc[]

=== Example of Dynamic Connection

Consider the following example application:

[source,xml,linenums]
----
<ftp:config name="FTP_Config" doc:name="FTP Config" >

<ftp:sftp-connection host="#[payload.host]" username="#[payload.user]" password="#[payload.password]" />

</ftp:config>

<flow name="streaming-multitenantFlow" >
<http:listener config-ref="HTTP_Listener_config" path="/multitenant" 
doc:name="Listener" />
<set-variable variableName="content" value="#[payload]" doc:name="Variable" />
<file:read config-ref="File_Config" path="recipients.csv" doc:name="Read"
 outputMimeType="application/csv" />
<ee:transform doc:name="Transform Message">
<ee:message>

<ee:set-payload ><![CDATA[%dw 2.0
output application/java
—
payload map using (row = $) {
   host: row.Host,
   user: row.User,
   password: row.Password
}]]>

  </ee:set-payload>
  </ee:message>
  </ee:transform>
  <foreach doc:name="For Each" >
    <ftp:write config-ref="FTP_Config" doc:name="Write" path="demo.txt">
    <ftp:content >#[content]</ftp:content>
  </ftp:write>
</foreach>
<set-payload doc:name="Set Payload" value="Multicast OK"/>
</flow>
----
 
* This sample application defines an FTP config in which the host, username, and password are expressions.
* It uses a flow in which a random content is posted.
* It uses the file connector to load a recipients file, which is a CSV file containing a random set of FTP destinations
* There’s a DataWeave transformation that splits a CSV file.
* The application uses a foreach element to write the contents into each of the FTP destinations.
* On each foreach iteration, each of the expressions in the FTP config resolves to a different value, establishing different connections to each of the servers.


== Example: FTP Write

[source,xml,linenums]
----
<ftp:config name="ftp"> // <1>
  <ftp:connection host="#[payload.host]" username="#[payload.user]" password="#[payload.password]" />
</ftp:config>

<flow name="ftpMultitenant" >
  <http:listener config-ref="HTTP_Listener_config" path="/multitenant"/> // <2>
  <set-variable variableName="content" value="#[payload]" />
  <file:read path="recipients.csv" outputMimeType="application/csv" /> // <3>

  <foreach> // <4>
    <ftp:write path="demo.txt" config-ref="ftp"> // <5>
      <ftp:content >#[vars.content]</ftp:content>
    </ftp:write>
  </foreach>

  <set-payload value="Multicast OK"/>
</flow>
----

// Notes on Mule 4 behavior (for Mule 3 users):
//INCLUDED IN FTP, SFTP
include::partial$common-note-mule4.adoc[]

// == Attributes
//INCLUDED IN FTP, SFTP, FILE
include::partial$common-file-attributes.adoc[]

== Representation 

Mule 4 provides a message structure utilizing a pair of payload and attributes. While the payload is the same as Mule 3, in Mule 4 the data moves around. This means that the payload is a file’s content. The attributes provide an object that contains metadata on the payload and information such as the file’s name, path, size, timestamps, etc. For the FTP and SFTP connectors these attributes are known as the _file attributes_.

The Mule message contains the concepts of encoding and MIME type. These are used to describe the format in which a payload is represented. The file attributes describe a file’s encoding and MIME type.


[[see_also]]
== See Also

* xref:ftp/ftp-documentation.adoc[FTP Connector Documentation Reference]
* xref:ftp/ftp-read.adoc[Read Files]
* xref:ftp/ftp-write.adoc[Write Files]
* xref:ftp/ftp-list.adoc[List Files]
* xref:ftp/ftp-on-new-file.adoc[Listen for New or Modified Files]
* xref:ftp/ftp-copy-move.adoc[Copy or Move Files]