= Redis XML and Maven Support - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

If you manually code a Mule application in XML either from the Studio XML editor 
or standalone, to get access to a connector, you must:

. Add the namespace for the connector to your XML flow.
. Add dependency information to your Maven file.

In the Studio visual editor, when you drag a connector from the palette to the 
canvas, Studio automatically populates the XML code with the connector 
namespace and schema location.

== Add a Namespace for the Connector

If you manually code the Mule application in Studio’s XML editor or another 
text editor, paste the following into the header of your configuration XML, 
inside the tag:

[source,xml,linenums]
----
<mule xmlns:redis="http://www.mulesoft.org/schema/mule/redis
...
http://www.mulesoft.org/schema/mule/redis
http://www.mulesoft.org/schema/mule/redis/current/mule-redis.xsd">
----

For example:

[source,xml,linenums]
----
<mule xmlns:redis="http://www.mulesoft.org/schema/mule/redis"
	xmlns:tracking="http://www.mulesoft.org/schema/mule/ee/tracking"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:spring="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans 
	http://www.springframework.org/schema/beans/spring-beans-current.xsd
	http://www.mulesoft.org/schema/mule/core
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/http
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/tracking
	http://www.mulesoft.org/schema/mule/ee/tracking/current/mule-tracking-ee.xsd
	http://www.mulesoft.org/schema/mule/redis
	http://www.mulesoft.org/schema/mule/redis/current/mule-redis.xsd">
----

== Configure the Maven POM File

The `pom.xml` is a Maven file that Anypoint Studio generates that contains dependencies for a Mule application.

When you code a Mule application manually, include this XML snippet in your file to 
enable access to this connector. Mule translates `LATEST` to the current version.

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-redis-connector</artifactId>
  <version>LATEST</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

To obtain the most up-to-date `pom.xml` file information, access the connector in 
https://www.mulesoft.com/exchange/[Anypoint Exchange] and click *Dependency Snippets*.

== Next

Now that you have read about XML support, you can try out the Redis xref:redis/redis-connector-examples.adoc[Examples].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
