= Redis Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

Redis Connector v5.1

Remote Dictionary Server (Redis) is an open source, in-memory data structure store that is used for use cases such as caching a user profile, creating a leader board, tracking real time activities on a website, implementing a spam filtering system, using it as a message queue, use as a custom object store, and more.

== About Connectors

Anypoint Connectors are extensions of Mule that let you work with external systems 
such as Salesforce, ServiceNow, Workday, Twitter, and more to send and receive 
information from these systems to create something new. Anypoint Connectors let you 
connect Mule applications to APIs and resources. 

A connector lets you send and receive data over a protocol, or to and from an API. Use 
this information to work with Design Center or Anypoint Studio to adjust the UI settings 
to enable the connector to work with a Mule application.

== Prerequisites

This document assumes that you are familiar with Mule, Anypoint Connectors,
Anypoint Studio essentials, elements in a Mule flow, and global elements. 

You should have the Mule Enterprise Edition and entitlements necessary to use this software.

== Audience

* Starting user -- Read this Get Started document. Configure your Mule application in 
xref:redis/redis-connector-design-center.adoc[Design Center] or 
xref:redis/redis-connector-studio.adoc[Anypoint Studio]. 
* Power user - Read xref:redis/redis-connector-xml-maven.adoc[XML and Maven Support]
and xref:redis/redis-connector-examples.adoc[Examples].


== Next

Now that you're started, try xref:redis/redis-connector-design-center.adoc[Design Center] or 
xref:redis/redis-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-redis-connector/[Redis in Anypoint Exchange]
* https://eu1.anypoint.mulesoft.com/exchange/com.mulesoft.connectors/mule-redis-connector/[Redis in the EU Anypoint Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
