= Box XML and Maven Support 
:page-aliases: connectors::box/box-connector-xml-maven.adoc

If you manually code a Mule application in XML either from the Studio XML editor
or a text editor, you must perform the following actions to get
access to a connector:

. Add the namespace for the connector to your XML flow.
. Add dependency information to your Maven `pom.xml` file.

In the Studio visual editor, when you drag a connector from the palette to the
canvas, Studio automatically populates the XML code with the connector
namespace and schema location.

== Add a Namespace for the Connector

Paste the following code inside the `mule` tag in the header of your XML
configuration:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/mule-box-connector
http://www.mulesoft.org/schema/mule/box-connector/current/mule-mule-box-connector.xsd
----

This example shows how the namespace statements are
placed in the mule XML block:

[source,xml,linenums]
----
<mule xmlns:mule-box-connector="http://www.mulesoft.org/schema/mule/mule-box-connector"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns:file="http://www.mulesoft.org/schema/mule/file"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/file
	http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd
	http://www.mulesoft.org/schema/mule/http
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/core
	http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd
	http://www.mulesoft.org/schema/mule/mule-box-connector
	http://www.mulesoft.org/schema/mule/box-connector/current/mule-mule-box-connector.xsd">
----

== Add a POM File Dependency

The pom.xml Maven file generated by Anypoint Studio contains
dependencies for a Mule app. When you code a Mule app manually, include
this XML snippet in your pom.xml file to enable access to the connector.
The Mule runtime engine translates the RELEASE dependency keyword
to the current version.

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-box-connector</artifactId>
  <version>RELEASE</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

To obtain the most up-to-date pom.xml file information, access the connector in
https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-box-connector/[Anypoint Exchange] and click *Dependency Snippets*.

== Next

Now that you have read about XML support, you can try out the Box Examples xref:box-connector-examples.adoc[Examples].

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
