= Upgrade Box Connector to Version 5.x

Upgrade Anypoint Connector for Box (Box Connector) from version 4.x to version 5.x to take advantage of new functionality.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|4.x.x |5.x.x
|===

== Changes in This Release
 * prefix for all operations from *mule-box-connector* to *box*
 * OAuth2 config XML structure
+
In the previous release, the XML for this element looked like this:
+
[source,xml,linenums]
----
<mule-box-connector:config 
	name="Mule_box_connector_Config" 
	doc:name="Mule-box-connector Config" 
	property_clientId="clientId" 
	property_clientSecret="secret" 
	property_localCallbackConfig="HTTP_Listener_config" 
	property_host="api.box.com" 
	property_port="4439" 
	property_basePath="/2.0" 
	property_protocol="HTTPS" 
	property_responseTimeout="10000" 
	property_localCallbackPath="/callback" 
	property_externalCallbackUrl="http://my-app.cloudhub.io/callback" 	
	property_localAuthorizationUrl="http://localhost:8081/authorize" 
	property_authorizationUrl="https://account.box.com/api/oauth2/authorize" 	
	property_accessTokenUrl="https://api.box.com/oauth2/token"
/>
----
+
The XML now looks like this:
+
[source,xml,linenums]
----
<box:config name="Box_Connector_Config" doc:name="Box Connector Config" >
	<box:oauth2security-connection >
		<box:oauth-authorization-code 
			consumerKey="consumerKey"
			consumerSecret="consumerSecret" 
			authorizationUrl="https://account.box.com/api/oauth2/authorize" 	
			accessTokenUrl="https://api.box.com/oauth2/token" 
			resourceOwnerId=“resourceownerId” />
		<box:oauth-callback-config 
			listenerConfig="HTTP_Listener_config" 
			callbackPath="/callback" 
			authorizePath="/authorize" 
			externalCallbackUrl="http://localhost:8081/callback" />
	</box:oauth2security-connection>
</box:config>
----
 * Added new operations, mainly 
 - Upload file
 - Get file content
 - Get file information
 - Upload file version
 - Uploads in chunks
// List all changes that affect users, including changed schemas, 
// changed data structures, changed POM files, changed and new fields 
// (locations, names, etc.) and parameters, deprecated parameters, etc.
// EXAMPLES:
//
// * The create operation name changed from <old-name> to <new-name>.
// * The <field-name> is now located in the <tab-name> tab.
// * What happens with the upgrade? Are changes made to app data? 
// * The single global configuration is divided into operation and source-specific global configurations like:
// ** send-config
//Used by send-with-sync-mdn and send-with-async-mdn operations
// ** listener-config
//Used by as2-listener source
// ** mdn-listener-config
//Used by as2-mdn-listener source.
// * Changed namespace from <old-namespace> to <new-namespace>.

// If applicable, use tables to describe new and changed operations and sources. Examples follow: 

////
[[new_operations]]
== New Operations

[%header%autowidth.spread]
|===
|<connector> Operation | Description | Parameters
| Enter the name of the operation. Example: Commit
a| Enter a description for the operation. Example: Commits the offsets associated to a message or batch of messages consumed in a message listener. a| Specify the operation parameters. Example: Consumer commit key
|===


[[changed_operations]]
== Changed Operations

[%header%autowidth.spread]
|===
|<connector> Operation | Description | Parameters

| Enter the name of the operation. Example: Commit
a| Enter a description for the operation. Example: Commits the offsets associated to a message or batch of messages consumed in a message listener. a| Specify the operation parameters. Example: Consumer commit key
|===


[[new_sources]]
== New Sources

[%header%autowidth.spread]
|===
|<connector> Source | Description | Parameters

| Enter the name of the source. Example: Batch message listener
a| Enter a description for the source. Example: The message list that was obtained in the poll is handled by a flow as a single event, so the handling of concurrency is simpler than in the simple message listener. a| Enter the parameters. Example: * Poll timeout
* Poll timeout time unit
* Acknowledgment mode
* Number of parallel consumers
|===

[[changed_sources]]
== Changed Sources

[%header%autowidth.spread]
|===
|<connector> Source | Earlier Version | Parameters

| <name-in-new-version> Example:Message listener | <name-in-oldMessage consumer a| * Poll timeout
* Poll timeout time unit
* Acknowledgment mode
* Number of parallel consumers
|===


== Requirements and Limitations

Be aware of the following requirements and limitations before you upgrade to the latest version.

=== Requirements

Ensure that you meet the following requirements before you perform the upgrade:

// * Any particular database, OS version, etc.?
// * Any software requirements? 
// * Minimum hardware requirements (CPU, memory, disk space, etc.)?
// * Licensing requirements?

=== Limitations

Before you perform the upgrade, be aware of the following known limitations:

// (Examples) 
// * There is no rollback mechanism
// * A protocol will be broken
// * Migration of _____ is not supported
////

== Upgrade Prerequisites

Before you perform the upgrade, you must:

* Create a backup of your files, data, and configurations in case you need to restore to them. 

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `box` in the search field.
. In *Available modules*, select *Box Connector Config* and click *Add*.
. Click *Finish*.
. Verify that the Box Connector dependency version is 5.0.0 in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

//If there are additional steps, add them.
// * Download the current version. 
// * Import data?
// * Update the configuration.
// * What does the user need to do after downloading the connector before they can start using it?

== Post-Upgrade Steps

After you install the latest version of the connector, follow these steps to complete the upgrade:

// * Do they need to update endpoints? 
// * Do they need to re-create/refactor any customizations?
// * Does the user need to map any files?
// * Verify the upgrade.

=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.

== Troubleshoot

//If there are common known issues and errors that occur when upgrading, give troubleshooting tips.

=== Revert the Upgrade

If it is necessary to revert to the previous version of box connector, change the `5.0.0` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:box-connector-reference.adoc[Box Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
