= Box Connector 5.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]


Box is an online file sharing and content management service for businesses. Anypoint Connector for Box (Box Connector) is a RAML-based connector that provides synchronization of data and automation of processes between Box
and third party CRMs, CMS, mobile, and social applications. Because this is a RAML-based connector, it only uses REST calls to interact with the Box 2.0 API and supports only a subset of available API services.

== Prerequisites

Before creating an app, you must have access to the Box target resource and Anypoint Platform.
You must also understand how to create a Mule app using Anypoint Studio.

You should be familiar with the use of the Box 2.0 API, Mule, Anypoint Connectors, Anypoint Studio, Mule concepts, elements in a Mule flow, and global elements.

To use this connector you need the following:

* A developer account or other valid Box instance.
* MuleSoft Enterprise License and necessary entitlements.


== Next Step
After you complete the prerequisites, you are ready to create an app with xref:box-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-box-connector/[Box Connector on Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
