= Publish Messages to an MQTT Broker with MQTT3 Connector

The MQTT3 Connector allows you to publish a message to the desired topic and with a specific quality of service.

[source,xml,linenums]
----
<mqtt3:config name="MQTT_Config">
    <mqtt3:connection clientId="smart-bentley-123" username="crowley" password="theDemon">
        <mqtt3:connection-settings >
            <mqtt3:connection-string-mqtt3-authenticator url="tcp://127.0.0.1:1883" />
        </mqtt3:connection-settings>
    </mqtt3:connection>
</mqtt3:config>

<flow name="publishQuote">
    <http:listener config-ref="HTTP_Listener" path="/mqtt3/publish" />
    <mqtt3:publish config-ref="MQTT_Config" topic="quotes/terryPratchett" qos="AT_LEAST_ONCE" isRetained="true">
        <mqtt3:message>#["Stories of imagination tend to upset those without one."]</mqtt3:message>
    </mqtt3:publish>
</flow>
----

= Mark Messages as Retained

By default, a broker that receives a message on a topic for which there are no current subscribers will discard it
unless the 'isRetained' flag is set to 'true'. When a message is marked as retained, the broker stores the last
retained message and the corresponding QoS for the selected topic. Each client that subscribes to a topic pattern that
matches the topic of the retained message receives the retained messages after they subscribe. The broker stores only
one retained message per topic. This allows new subscribers to receive the most current value rather than waiting for
the next update from a publisher.
