= Listen and Publish Messages with MQTT3 Connector

In these examples, you configure the Anypoint Connector for MQTT3 (MQTT3 Connector) *On New Message* (`<mqtt3:listener>`) source and *Publish* (`<mqtt3:publish>`) operation to listen and publish messages to a specific topic.


== Create the First Mule Application

For the first example, you must start an MQTT broker and create a Mule app. To create the Mule app in the Studio XML editor, follow these steps:

. In the Studio project, navigate to the *Configuration XML* tab.
. Configure an `<mqtt3:config name="MQTT3_Config_1">` and an `<http:listener-config>` configuration element:

[source,xml,linenums]
----
	<http:listener-config name="HTTP_Listener_config">
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<mqtt3:config name="MQTT3_Config_1">
		<mqtt3:connection clientId="crowley123" username="mosquitto" password="mosquitto" url="tcp://0.0.0.0:1883" />
		<mqtt3:last-will-and-testament topic="topic/lwt" body="All the money goes to the cat" isRetained="true"/>
	</mqtt3:config>
----

. Create a flow with a listener source `<mqtt3:listener>` that triggers an event for incoming messages on topics matching the filter `topic/quotes/#`:

[source,xml,linenums]
----
	<flow name="listener-flow">
		<mqtt3:listener config-ref="MQTT3_Config_1" doc:name="On New Message 1">
			<reconnect />
			<mqtt3:topics >
				<mqtt3:topic topicFilter="topic/quotes/#" />
			</mqtt3:topics>
		</mqtt3:listener>
		<logger level="INFO" message="Received message '#[payload]' with at topic #[attributes.topic] with qos #[attributes.qos]"/>
	</flow>
----

. Create a flow with a publish operation `<mqtt3:publish>` that publish messages to the topic `topic/quotes/shakespeare` and triggers an event in the `listener-flow`:

[source,xml,linenums]
----
	<flow name="publish-message-flow">
		<http:listener config-ref="HTTP_Listener_config" path="publish/message"/>
		<mqtt3:publish config-ref="MQTT3_Config_1" topic="topic/quotes/shakespeare">
			<mqtt3:message ><![CDATA[#["Uneasy lies the head that wears a crown"]]]></mqtt3:message>
		</mqtt3:publish>
		<set-payload value="SUCCESSFULLY PUBLISHED MESSAGE!" doc:name="Set Payload"/>
	</flow>
----

. To publish the message, send a request to the HTTP endpoint using the following curl command: +
 `curl -v --request GET localhost:8081/publish/message`.

== Create the Second Mule Application

In the following example, you use the previous application and create a second application that subscribes to the topic `topic/lwt` to be notified if the first application crashes or disconnects. Notice that in the previous application's MQTT configuration element you configured  a `<mqtt3:last-will-and-testament>` message and `topic`. To create the Mule app in the Studio XML editor, follow these steps:

. In a new Studio project, navigate to the *Configuration XML* tab.
. Configure a new `<mqtt3:config name="MQTT3_Config_2">` configuration:

[source,xml,linenums]
----
<mqtt3:config name="MQTT3_Config_2">
	<mqtt3:connection clientId="azfell123" username="mosquitto" password="mosquitto" url="tcp://0.0.0.0:1884"/>
</mqtt3:config>
----

. And a listener source `<mqtt3:listener>` that subscribe to the topic `topic/lwt`:

[source,xml,linenums]
----
<flow name="listener-lwt-flow">
	<mqtt3:listener doc:name="On New Message 2" config-ref="MQTT3_Config_2">
		<mqtt3:topics >
			<mqtt3:topic topicFilter="topic/lwt" />
		</mqtt3:topics>
	</mqtt3:listener>
	<logger level="INFO" message="Received message '#[payload]' with at topic #[attributes.topic] with qos #[attributes.qos]"/>
</flow>
----

. Save and run the Mule application.

After both applications are running, you need to simulate a disconnection from the first application. A simple way to achieve the disconnection is by looking for the process ID of your first Mule app and killing it, which simulates an application crash.
The second application then logs the last will and testament message that was set by the first application. The second application is also notified that the first application crashed.

== See Also

* xref:mqtt3-connector-examples.adoc[MQTT3 Connector Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
