= Deploy MQTT3 Connector Apps in a Cluster

When an MQTT broker has established a connection with a client, it will identify that client by its client ID. If the broker has an established connection with a client that has the client ID: 'smart-bentley-123' and receives a new connection with the same client ID, it will close the previous connection (assuming it is stale) and take on the new connection. This is known as a client-takeover and it is a mechanism employed by the mqtt broker because in some cases TCP connections can reach a half-open or invalid state (perhaps due to a crash in one of the communication ends), which is undesirable. Therefore, the broker will always assume the new, incoming connection is the valid one, close the older connection and continue using the newly established one.

Because of this mechanism, applications that use the MQTT3 Connector in a Cluster will result in a different Client ID being generated for each configuration in each deployed instance, even when the specified client ID is the same in all the configurations. This means, that user need not concern themselves with defining a random or dynamic IDs to avoid client take-overs between the nodes.

This will only be the case, if the connector is deployed in cluster, in any other case, the specified client id will be left unchanged.

The way the client ID is resolved for each node is by taking the id specified in the configuration and appending an identifier specific to each node. The resulting client ID should have the following format: `{clientId}_{nodeId}_{domainId}_{appName}`.
