= Listen for New Messages with MQTT3 Connector

The MQTT3 Connector allows you to listen for new incoming messages for one or more topic filters and with a specific quality of service for each one.

The listener could subscribe to multiple individual topics:

[source,xml,linenums]
----
    <flow name="listenerAuthorQuotes">
        <mqtt3:listener config-ref="MQTT_Config">
            <mqtt3:topics>
                <mqtt3:topic topicFilter="quotes/terryPratchett" qos="EXACTLY_ONCE"/>
                <mqtt3:topic topicFilter="quotes/neilGaiman" qos="AT_LEAST_ONCE" />
                <mqtt3:topic topicFilter="quotes/ianMcEwan" qos="AT_MOST_ONCE" />
            </mqtt3:topics>
        </mqtt3:listener>
    </flow>
----

== Single-Level WildCards

You can use single-level wildcards to listen to multiple topics:

[source,xml,linenums]
----
    <flow name="listenerArgentinaTemperature">
        <mqtt3:listener config-ref="${config}">
            <mqtt3:topics>
                <mqtt3:topic topicFilter="quotes/+/authors"/>
            </mqtt3:topics>
        </mqtt3:listener>

        <logger level="DEBUG" message="A quote has been published to #[attributes.topic]: #[payload]"/>
    </flow>
----

This will enable the subscriber to receive messages published to all topics matching the structure 'quotes/+/authors'.

So, messages published to the following topics would reach trigger our message listener:

* quotes/british/authors
* quotes/american/authors

However, messages published to the following topics would NOT trigger our message listener:

* names/british/authors
* quotes/american/writers

== Multi-Level WildCards

Or multi-level wildcards:

[source,xml,linenums]
----
    <flow name="listenerArgentinaTemperature">
        <mqtt3:listener config-ref="${config}">
            <mqtt3:topics>
                <mqtt3:topic topicFilter="quotes/england/#"/>
            </mqtt3:topics>
        </mqtt3:listener>

        <logger level="DEBUG" message="A quote has been published to #[attributes.topic]: #[payload]"/>
    </flow>
----

Multi-level wildcards allow the listener to subscribe to all topics that share same root (everything that comes before '#').

So, messages published to the following topics would reach trigger our message listener:

* quotes/england/authors/terryPratchett
* quotes/england/authors/neilGaiman
* quotes/england/actors

However, messages published to the following topics would NOT trigger our message listener:

* quotes/american/actors
* phrases/england/authors/neilGaiman

== See Also

* xref:mqtt3-connector-examples.adoc[MQTT3 Connector Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
