= MQTT3 Connector Examples - Mule 4

To fully benefit from using Anypoint Connector for MQTT3 (MQTT3 Connector), see the following examples of configuring the connector:


* xref:mqtt3-connector-quality-of-service.adoc[Configure MQTT3 Quality of Service] +
Configure the quality of service (QoS) to specify levels of delivery assurance for inbound or outbound messages.
* xref:mqtt3-connector-listener.adoc[Listen for New Messages] +
Configure the *Listener* source to listen for messages on a unique or multiple topics, and listen for messages on multiple topics using single-level or multi-level wildcards.
* xref:mqtt3-connector-publish.adoc[Publish a Message] +
Configure the *Publish* operation to publish a message to the desired topic and with a specific quality of service.
* xref:mqtt3-connector-lwt-message.adoc[Configure the Last Will And Testament Message] +
Configure the last will and testament message to notify all the topic subscribers of the client’s disconnection from the broker.
* xref:mqtt3-connector-cluster.adoc[Deploy MQTT3 Connector Apps in a Cluster] +
Understand the client ID behavior of MQTT3 Connector when deploying Mule apps in a cluster.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
