= Deploy MQTT 3 Connector Apps in a Cluster

[NOTE]
MQTT Connector 1.0 is now available! Check the https://docs.mulesoft.com/mqtt3-connector/1.0/[MQTT Connector 1.0 documentation] site for the latest version. 

MQTT broker establishes a connection with a client using its clientID. If the broker establishes a connection with a client whose client ID is `smart-bentley-123`, and then the broker receives a new connection with the same client ID, the broker closes the previous connection (assuming it is stale) and accepts the new connection. This mechanism is known as a client take-over. MQTT brokers employ this mechanism to prevent situations such as TCP connections reaching a half-open or invalid state due to a crash in one of the communication ends, which is undesirable. The broker assumes the new incoming connection to be valid, closes the older connection, and continues using the newly established connection.

Because of this mechanism, Mule runtime engine (Mule) applications that use the MQTT 3 Connector deployed in a cluster must generate a unique client ID for each active node in the cluster.

== See Also

* xref:mqtt3-connector-examples.adoc[MQTT3 Connector Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
