= Configure Last Will And Testament Messages

Set a last will and testament message to ensure that if the client disconnects temporarily or permanently from the broker, a message is sent to a specific LWT topic, notifying all its subscribers of the client’s disconnection.
The LWT message is set at the time the connection to the broker is established.

Configure the last will and testament message in the XML configuration element and specify whether you want the broker to retain that message or not.
If an MQTT message is set for retention, the broker stores the last message marked as retained that arrived at a specific topic. If no listeners are subscribed to a matching topic at the time the message is sent,
the broker stores the message until a listener connects to that topic. Then, the broker delivers the listener to the last
message retained for that topic.

In the Configuration XML editor, the `<mqtt3:last-will-and-testament>` and `isRetained` configurations look like this:

[source,xml,linenums]
----
<mqtt3:config name="MQTT_LWT_Config">
    <mqtt3:connection clientId="azfell-and-co-123" username="aziraphale" password="principality" >
        <mqtt3:last-will-and-testament topic="LWT" body="The end is nye" isRetained="true"/>
        <mqtt3:connection-settings >
            <mqtt3:connection-string-mqtt3-authenticator url="tcp://127.0.0.1:1883" />
        </mqtt3:connection-settings>
    </mqtt3:connection>
</mqtt3:config>
----

== See Also

* xref:mqtt3-connector-examples.adoc[MQTT3 Connector Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
