= MongoDB Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for MongoDB is a closed-source connector that provides a connection between the Mule runtime and third-party software on a MongoDB server.

Release Notes: xref:release-notes::connector/mongodb-connector-release-notes-mule-4.adoc[MongoDB Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-mongodb-connector/[MongoDB Connector]

This documentation set consists of the following versioned documents:

[%header,cols="40a,60a"]
|===
|Version Documents |Updates in This Release
|xref:mongodb/mongodb-connector-6-0.adoc[MongoDB Connector v6.0] +
xref:mongodb/mongodb-connector-6-0-reference.adoc[MongoDB Connector 6.0 Reference]

| * Changed connection types and configuration
* Changed operation names, metadata, fields, and values
* Changed input sources

See the xref:mongodb/mongodb-connector-6-0-upgrade-migrate.adoc[Update and Migrate Guide] for more information.

| xref:mongodb/mongodb-connector-5-3.adoc[MongoDB Connector v5.3] +
xref:mongodb/mogodb-connector-reference.adoc[MongoDB Connector Reference v5.3]
| Added the New Object, Modified Object, and Deleted Object input sources, which enable you to execute a flow each time a MongoDB object is created, modified, or deleted.
|===

== See Also

*  xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
https://help.mulesoft.com[MuleSoft Help Center]
