= MongoDB Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To configure a connector in Anypoint Studio follow this process:

. Install the connector.
. Configure the connector.
. Configure an input source for the connector.

== Install the Connector Using Exchange

. In Studio, create a Mule project.
. Click the Exchange *(X)* icon in the upper left of the Studio task bar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for "MongoDB".
. Select the MongoDB Connector and click *Add to project*.
. Follow the prompts to install the connector.

== Install the Connector in Studio

. In Studio, create a Mule project.
. In the Mule Palette, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type the name of the connector in the search field.
. Click the MongoDB Connector name in *Available modules*.
. Click *Add*.
. Click *Finish*.

== Configure the Connector

. Click the operation.
. On the *Global Element* tab, click *Create*.
. Search for `MongoDB Config` from the Connector Configuration directory.
. Select *MongoDB Config* and click *OK*.
. In the *Connection* field, select the connection type.
. Enter a value for the following properties:
* *Servers*
+
A `host:port` comma-separated list (in case you have a replica set). The default value is `localhost:27017`.
+
* *Database*
+
Specify the database to send and retrieve data from the MongoDB instance.
+
* *Username*
+
Username to access the MongoDB instance
+
* *Password*
+
Corresponding password
+
. *Database*
+
 Database that sends and retrieves data from your MongoDB instance
 +
 *  *Servers*
 +
 A `host:port` comma-separated list (in case you have a replica set). This value defaults to `localhost:27017`.
. Select the *Connection* tab to adjust the values for the *Connections per host*, *Max wait time*, and *Socket timeout*, and *Pooling Settings* properties, which apply to requests sent to MongoDB.
+
The default value for *Connect Timeout* is 30000 milliseconds (30 seconds). Any connection requests that take longer than 30 seconds to send and receive throw an exception. You can override this behavior by setting their values to 0, meaning that the MongoDB connector waits indefinitely until a request is successfully sent and a response is received.
*Reviewers, which specific fields do you need to set to 0 to have MongoDB wait indefinitely?*
+
. Optionally, enable metadata and specify a collection sample.


Before running your app, make sure you have the necessary permissions to do so.

The MongoDB configuration with Spring property placeholders for the *Connection* field values is the recommended approach when you plan to deploy your application to CloudHub or to a Mule runtime.

However, you may hard code your connection credentials in the Global Element Properties if you are in the development stage and want to speed up the process.

|Enable Metadata |Enables metadata for collections, documents and files.
|Collection metadata samples |Allows you to add existing collections to take metadata structure from.
|===

=== Global Configuration with SSL (Optional)

MongoDB Connector v4.0.0 and later supports the use of SSL. To set up the Global Configuration:

* In the *Global Element* tab for your MongoDB connection, select the `true` SSL property field in the *Connection* tab.
* Your instance must support this feature.

== Next

After configuring Studio, see the xref:mongodb/mongodb-connector-examples.adoc[Examples] topic
for more configuration ideas.

== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
