= MongoDB Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

MongoDB Connector v5.3

The Anypoint Connector for MongoDB is a closed source connector that provides a connection between the Mule runtime and third-party software on a MongoDB server.

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect to APIs and resources on external systems, such as Salesforce, MongoDB, ServiceNow, and Twitter.

== Prerequisites

Before creating an app, you must have access to the MongoDB target resource and Anypoint Platform. You must also understand how to create a Mule app using Design Center or Anypoint Studio.

To use the this connector you need:

* MongoDB instance.
* Set of valid credentials, including the required MongoDB endpoints, pointing to your instance.


== Audience

* Starting user -- To create your Mule app, see 
xref:mongodb/mongodb-connector-design-center.adoc[Design Center] or 
xref:mongodb/mongodb-connector-studio.adoc[Anypoint Studio]. 
* Power user - Read xref:mongodb/mongodb-connector-xml-maven.adoc[XML and Maven Support]
and xref:mongodb/mongodb-connector-examples.adoc[Examples].

== Exchange Example

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides a MongoDB example
to simplify your use of the Salesforce connector. Examples provide a complete solution.

* https://www.mulesoft.com/exchange/org.mule.examples/importing-a-CSV-file-into-Mongo-DB/[Import a CSV File into MongoDB]

== Next

After you have met the prerequisites, and experimented with example, you are ready to create an app with xref:mongodb/mongodb-connector-design-center.adoc[Design Center] or 
xref:mongodb/mongodb-connector-studio.adoc[Anypoint Studio].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
