= MongoDB Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

MongoDB Connector v5.3

MongoDB Connector is a closed source connector which provides a connection between Mule and third-party software MongoDB server.

== About Connectors

Anypoint Connectors are extensions of Mule that let you work with external systems 
such as Salesforce, ServiceNow, Workday, Twitter, and more to send and receive information from these systems to create something new. Anypoint Connectors let you connect Mule applications to APIs and resources.

A connector lets you send and receive data over a protocol, or to and from an API. Use 
this information to work with Design Center or Anypoint Studio to adjust the UI settings 
to enable the connector to work with a Mule application.

== Prerequisites

This document assumes that you are familiar with MongoDB API. To use the this connector you need the following:

* MongoDB instance.
* Set of valid credentials, including the required MongoDB endpoints, pointing to your instance.
* MuleSoft Enterprise License.

== Audience

* Starting user -- Read Get Started (this document) and configure your Mule application in 
xref:mongodb/mongodb-connector-design-center.adoc[Design Center] or 
xref:mongodb/mongodb-connector-studio.adoc[Anypoint Studio]. 
* Power user - Read xref:mongodb/mongodb-connector-xml-maven.adoc[XML and Maven Support]
and xref:mongodb/mongodb-connector-examples.adoc[Examples].

== Exchange Template

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides a MongoDB example
to simplify your use of the Salesforce connector. Templates provide a starting point 
that enable you to add additional functionality. Examples provide a complete solution.

* https://www.mulesoft.com/exchange/org.mule.examples/importing-a-CSV-file-into-Mongo-DB/[Import a CSV File into MongoDB]

== Next

Now that you've started, try xref:mongodb/mongodb-connector-design-center.adoc[Design Center] or 
xref:mongodb/mongodb-connector-studio.adoc[Anypoint Studio].

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
