
= MongoDB Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

MongoDB Connector v5.3

Anypoint Connector for MongoDB is a closed-source connector that provides a connection between the Mule runtime and third-party software on a MongoDB server.

Release Notes: xref:release-notes::connector/mongodb-connector-release-notes-mule-4.adoc[MongoDB Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-mongodb-connector/[MongoDB Connector]

== Prerequisites

Before creating an app, you must have access to the MongoDB target resource and Anypoint Platform. You must also understand how to create a Mule app using Design Center or Anypoint Studio.

To use the this connector you need:

* MongoDB instance
* Set of valid credentials, including the required MongoDB endpoints, pointing to your instance


== Audience

* Starting user -- To create your Mule app, see
xref:mongodb/mongodb-connector-design-center.adoc[Design Center] or
xref:mongodb/mongodb-connector-studio.adoc[Anypoint Studio].
* Power user - Read xref:mongodb/mongodb-connector-xml-maven.adoc[XML and Maven Support]
and xref:mongodb/mongodb-connector-examples.adoc[Examples].

== Exchange Example

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides a MongoDB example
to simplify your use of the Salesforce connector. Examples provide a complete solution.

https://www.mulesoft.com/exchange/org.mule.examples/importing-a-CSV-file-into-Mongo-DB/[Import a CSV File into MongoDB]

== Next Steps

After you have met the prerequisites, and experimented with example, you are ready to create an app with xref:mongodb/mongodb-connector-design-center.adoc[Design Center] or
xref:mongodb/mongodb-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:introduction/intro-use-exchange.adoc[Use Anypoint Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
