= Mongo DB Connector API Reference
:toc:               left
:toc-title:         Connector Summary
:toclevels:         2
:last-update-label!:
:source-highlighter: coderay
:page-aliases: 3.8@mule-runtime::mongo-apidoc.adoc

+++
MongoDB is an open source, high-performance, schema-free, document-oriented database that manages collections of BSON documents.
+++

*Additional Info*
[width="50", cols=".<60%,^40%" ]
|===
| Requires Mule Enterprise License |  Yes  {nbsp}
| Requires Entitlement |  No  {nbsp}
| Mule Version | 3.6.0 or higher
|===


== Configs
---
=== Configuration
`<mongo:config>`


`Connection Management`



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| username | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the username to use for authentication.+++ |   | {nbsp}
| password | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the password to use for authentication. If the password is null or whitespaces only, the connector won't use authentication and username must be empty too.+++ |   | {nbsp}
| database | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the database+++ |   | *x*{nbsp}
| host | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A list of MongoDB instance, with the format <code>host:port</code>, separated by commas.
<p>
<pre>
Example: 127.0.0.1:27017, 192.168.1.2:27017
</pre>+++ |  localhost:27017 | {nbsp}
| connectionsPerHost | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++The number of connections allowed per host (the pool size, per host)+++ |   | {nbsp}
| threadsAllowedToBlockForConnectionMultiplier | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Multiplier for connectionsPerHost for # of threads that can block.+++ |   | {nbsp}
| maxWaitTime | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++The max wait time for a blocking thread for a connection from the pool in ms.+++ |   | {nbsp}
| connectTimeout | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++The connection timeout in milliseconds; this is for establishing the socket connections (open). 0 is default and infinite.+++ |  30000 | {nbsp}
| socketTimeout | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++The socket timeout. 0 is default and infinite.+++ |   | {nbsp}
| ssl | +++boolean+++ | +++This is for enabling an SSL connection. It is disabled by default.+++ |  false | {nbsp}
| authenticationDatabase | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | ++++++ |   | {nbsp}
|===
---
=== Connection String
`<mongo:config-connection-string>`


`Connection Management`



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| connectionString | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | ++++++ |   | *x*{nbsp}
|===



== Processors

---

=== Add user
`<mongo:add-user>`




+++
Adds a new user for this db
+++

==== XML Sample
[source,xml]
----
<mongo:add-user config-ref="Mongo_DB__Configuration" newUsername="myUser" newPassword="myPassword"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
newUsername  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Name of the user+++ |  | *x*{nbsp}




|
newPassword  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Password that will be used for authentication+++ |  | *x*{nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++Result of the operation+++
|===




---

=== Drop database
`<mongo:drop-database>`




+++
Drop the current database
+++

==== XML Sample
[source,xml]
----
<mongo:drop-database config-ref="Mongo_DB__Configuration"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}

|===





---

=== List collections
`<mongo:list-collections>`




+++
Lists names of collections available at this database
+++

==== XML Sample
[source,xml]
----
<mongo:list-collections config-ref="Mongo_DB__Configuration"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}

|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html">Iterable</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++the list of names of collections available at this database+++
|===




---

=== Exists collection
`<mongo:exists-collection>`




+++
Answers if a collection exists given its name
+++

==== XML Sample
[source,xml]
----
<mongo:exists-collection config-ref="Mongo_DB__Configuration" collection="aColllection"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection+++ | #[payload] | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++boolean+++ | +++if the collection exists+++
|===




---

=== Drop collection
`<mongo:drop-collection>`




+++
Deletes a collection and all the objects it contains. If the collection does not exist, does nothing.
+++

==== XML Sample
[source,xml]
----
<mongo:drop-collection config-ref="Mongo_DB__Configuration" collection="aCollection"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection to drop+++ | #[payload] | {nbsp}


|===





---

=== Create collection
`<mongo:create-collection>`




+++
Creates a new collection. If the collection already exists, a MongoException will be thrown.
+++

==== XML Sample
[source,xml]
----
<mongo:create-collection config-ref="Mongo_DB__Configuration" collection="aCollection" capped="true"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection to create+++ |  | *x*{nbsp}




|
capped  | +++boolean+++ | +++if the collection will be capped+++ | false | {nbsp}




|
maxObjects  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++the maximum number of documents the new collection is able to contain+++ |  | {nbsp}




|
size  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++the maximum size of the new collection+++ |  | {nbsp}


|===





---

=== Insert document
`<mongo:insert-document>`




+++
Inserts a document in a collection, setting its id if necessary.
+++

==== XML Sample
[source,xml]
----
<mongo:insert-document config-ref="Mongo_DB__Configuration" collection="Employees">
        </mongo:insert-document>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection where to insert the given document.+++ |  | *x*{nbsp}




|
document  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> instance.+++ | #[payload] | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the id that was just inserted+++
|===




---

=== Insert documents
`<mongo:insert-documents>`




+++
Inserts a list of documents in a collection, setting its id if necessary.
+++

==== XML Sample
[source,xml]
----
<mongo:insert-documents config-ref="Mongo_DB__Configuration" collection="Employees">
        </mongo:insert-documents>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection where to insert the given document.+++ |  | *x*{nbsp}




|
documents  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>>+++ | +++a <a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a> of <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>.+++ | #[payload] | {nbsp}




|
ordered  | +++boolean+++ | +++indicates if the list of write operations is ordered or unordered. By default, ff an error occurs during the processing of one of the write operations, MongoDB will return without processing any remaining write operations in the list.+++ | true | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> with the operation result+++
|===




---

=== Update documents
`<mongo:update-documents>`




+++
Updates documents that matches the given query. If query is not specified, all documents are retrieved. If parameter multi is set to false, only the first document matching
it will be updated. Otherwise, all the documents matching it will be updated.
+++

==== XML Sample
[source,xml]
----
<mongo:update-documents config-ref="Mongo_DB__Configuration" collection="myCollection" query-ref="#[payload]">
        </mongo:update-documents>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection to update+++ |  | *x*{nbsp}




|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query object used to detect the element to update.+++ |  | {nbsp}




|
element  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> mandatory object that will replace that one which matches the query.+++ | #[payload] | {nbsp}




|
multi  | +++boolean+++ | +++if all or just the first document matching the query will be updated+++ | true | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> with the update status+++
|===




---

=== Update documents by function
`<mongo:update-documents-by-function>`




+++
Update documents using a mongo function. If query is not specified, all documents are retrieved.
<p/>
+++

==== XML Sample
[source,xml]
----
<mongo:update-documents-by-function config-ref="Mongo_DB__Configuration" collection="myCollection" element-ref="#[payload]" upsert="true" function="$set">
        </mongo:update-documents-by-function>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection to update+++ |  | *x*{nbsp}




|
function  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the function used to execute the update+++ |  | *x*{nbsp}




|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query document used to detect the element to update.+++ |  | {nbsp}




|
element  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> mandatory document that will replace that one which matches the query.+++ | #[payload] | {nbsp}




|
upsert  | +++boolean+++ | +++if the database should create the element if it does not exist.+++ | false | {nbsp}




|
multi  | +++boolean+++ | +++if all or just the first document matching the query will be updated.+++ | true | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> with the update status.+++
|===




---

=== Update documents by functions
`<mongo:update-documents-by-functions>`




+++
Update documents using one or more mongo function(s). If query is not specified, all documents are retrieved. If there are duplicated operators. Only the last one will be
executed.
<p/>
+++




==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection to update+++ |  | *x*{nbsp}




|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query document used to detect the element to update+++ |  | {nbsp}




|
functions  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> of functions used to execute the update. e.g. <$set,{"key":123}>+++ | #[payload] | {nbsp}




|
upsert  | +++boolean+++ | +++whether the database should create the element if it does not exist+++ | false | {nbsp}




|
multi  | +++boolean+++ | +++if all or just the first document matching the query will be updated+++ | true | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> with the update status.+++
|===




---

=== Save document
`<mongo:save-document>`




+++
Inserts or updates a document based on its object _id.
+++

==== XML Sample
[source,xml]
----
<mongo:save-document config-ref="Mongo_DB__Configuration" collection="myCollection">
        </mongo:save-document>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the collection where to insert the object+++ |  | *x*{nbsp}




|
document  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the mandatory <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> document to insert.+++ | #[payload] | {nbsp}


|===





---

=== Remove documents
`<mongo:remove-documents>`




+++
Removes all the documents that match the a given optional query. If query is not specified, all documents are removed. However, please notice that this is normally less
performant that dropping the collection and creating it and its indices again
+++

==== XML Sample
[source,xml]
----
<mongo:remove-documents config-ref="Mongo_DB__Configuration" collection="myCollection">
        </mongo:remove-documents>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the collection whose elements will be removed+++ |  | *x*{nbsp}




|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the optional <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query object. Documents that match it will be removed.+++ | #[payload] | {nbsp}


|===





---

=== Map reduce objects
`<mongo:map-reduce-objects>`




+++
Transforms a collection into a collection of aggregated groups, by applying a supplied element-mapping function to each element, that transforms each one into a key-value
pair, grouping the resulting pairs by key, and finally reducing values in each group applying a suppling 'reduce' function.
<p/>
Each supplied function is coded in JavaScript.
<p/>
Note that the correct way of writing those functions may not be obvious; please consult MongoDB documentation for writing them.
+++

==== XML Sample
[source,xml]
----
<mongo:map-reduce-objects config-ref="Mongo_DB__Configuration" collection="myCollection" mapFunction="myMapFunction" reduceFunction="myReduceFunction"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection to map and reduce+++ |  | *x*{nbsp}




|
mapFunction  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++a JavaScript encoded mapping function+++ |  | *x*{nbsp}




|
reduceFunction  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++a JavaScript encoded reducing function+++ |  | *x*{nbsp}




|
outputCollection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the output collection to write the results, replacing previous collection if existed, mandatory when results may be larger than 16MB. If outputCollection is unspecified, the computation is performed in-memory and not persisted.+++ |  | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html">Iterable</a><<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>>+++ | +++an iterable that retrieves the resulting collection of <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++
|===




---

=== Count documents
`<mongo:count-documents>`




+++
Counts the number of documents that match the given query. If no query is passed, returns the number of elements in the collection
+++

==== XML Sample
[source,xml]
----
<mongo:count-documents config-ref="Mongo_DB__Configuration" collection="myCollection" query-ref="dbObject"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the target collection+++ |  | *x*{nbsp}




|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/conversions/Bson.html">Bson</a>+++ | +++the optional <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query for counting documents. Only documents matching it will be counted. If unspecified, all documents are counted.+++ | #[payload] | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++long+++ | +++the amount of documents that matches the query+++
|===




---

=== Find documents
`<mongo:find-documents>`




+++
Finds all documents that match a given query. If no query is specified, all documents of the collection are retrieved. If no fields object is specified, all fields are
retrieved.
+++

==== XML Sample
[source,xml]
----
<mongo:find-documents config-ref="Mongo_DB__Configuration" collection="myCollection" limit="5" numToSkip="10" query-ref="#[payload]" sortBy-ref="#[new org.bson.Document()]">
            <mongo:fields>
                <mongo:field>field1</mongo:field>
                <mongo:field>field2</mongo:field>
            </mongo:fields>
        </mongo:find-documents>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the target collection+++ |  | *x*{nbsp}




|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the optional <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query document. If unspecified, all documents are returned.+++ | #[payload] | {nbsp}




|
fields  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++alternative way of passing fields as a literal List+++ |  | {nbsp}




|
numToSkip  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++number of documents skip (offset)+++ |  | {nbsp}




|
limit  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++limit of documents to return+++ |  | {nbsp}




|
sortBy  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++indicates the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> used to sort the results+++ |  | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html">Iterable</a><<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>>+++ | +++an iterable of <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++
|===




---

=== Find one document
`<mongo:find-one-document>`




+++
Finds the first document that matches a given query. Throws a MongoException if no one matches the given query
+++

==== XML Sample
[source,xml]
----
<mongo:find-one-document config-ref="Mongo_DB__Configuration" collection="myCollection">
            <mongo:fields>
                <mongo:field>field1</mongo:field>
                <mongo:field>field2</mongo:field>
            </mongo:fields>
        </mongo:find-one-document>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the target collection+++ |  | *x*{nbsp}




|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the mandatory <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query document that the returned object matches.+++ | #[payload] | {nbsp}




|
fields  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++alternative way of passing fields as a literal List+++ |  | {nbsp}




|
failOnNotFound  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Flag to specify if an exception will be thrown when no object is found. For backward compatibility the default value is true.+++ | true | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> that matches the query. If nothing matches and the failOnNotFound is set to false, null will be returned+++
|===




---

=== Find one and update document
`<mongo:find-one-and-update-document>`




+++
Finds and update the first document that matches a given query. When returnNew = true, returns the updated document instead of the original document.
+++




==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the target collection+++ |  | *x*{nbsp}




|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query that the returned object matches.+++ |  | {nbsp}




|
element  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> mandatory object that will replace that one which matches the query+++ | #[payload] | {nbsp}




|
fields  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>>+++ | +++alternative way of passing fields as a literal List+++ |  | {nbsp}




|
returnNewDocument  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Flag to specify if the returning <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> should be the updated document instead of the original. Defaults to false, returning the document before modifications+++ | false | {nbsp}




|
sortBy  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++indicates the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> used to sort the results.+++ |  | {nbsp}




|
remove  | +++boolean+++ | +++removes the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> specified in the query field. Defaults to false+++ | false | {nbsp}




|
upsert  | +++boolean+++ | +++whether the database should create the element if it does not exist+++ | false | {nbsp}




|
bypassDocumentValidation  | +++boolean+++ | +++lets you update documents that do not meet the validation requirements. Defaults to false+++ | false | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> that matches the query. If nothing matches, null will be returned+++
|===




---

=== Create index
`<mongo:create-index>`




+++
Creates a new index
+++

==== XML Sample
[source,xml]
----
<mongo:create-index config-ref="Mongo_DB__Configuration" collection="myCollection" field="myField" order="DESC"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection where the index will be created+++ |  | *x*{nbsp}




|
field  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the field which will be indexed+++ |  | *x*{nbsp}




|
order  | +++<a href="javadocs/org/mule/modules/mongo/api/IndexOrder.html">IndexOrder</a>+++ | +++the indexing order+++ | ASC | {nbsp}


|===





---

=== Drop index
`<mongo:drop-index>`




+++
Drops an existing index
+++

==== XML Sample
[source,xml]
----
<mongo:drop-index config-ref="Mongo_DB__Configuration" collection="myCollection" index="myIndex"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection where the index is+++ |  | *x*{nbsp}




|
index  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the index to drop+++ |  | *x*{nbsp}


|===





---

=== List indices
`<mongo:list-indices>`




+++
List existent indices in a collection
+++

==== XML Sample
[source,xml]
----
<mongo:list-indices config-ref="Mongo_DB__Configuration" collection="myCollection"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
collection  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the name of the collection+++ |  | *x*{nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Collection.html">Collection</a><<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>>+++ | +++a collection of <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> with indices information+++
|===




---

=== Create file from payload
`<mongo:create-file-from-payload>`




+++
Creates a new GridFSFile in the database, saving the given content, filename, contentType, and extraData, and answers it.
+++

==== XML Sample
[source,xml]
----
<mongo:create-file-from-payload config-ref="Mongo_DB__Configuration" filename="#[variable:filename]" metadata-ref="myDbObject"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
payload  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>+++ | +++the mandatory content of the new gridfs file. It may be a java.io.File, a byte[] or an InputStream.+++ | #[payload] | {nbsp}




|
filename  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++the mandatory name of new file.+++ |  | *x*{nbsp}




|
metadata  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the optional <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> metadata of the new content type+++ |  | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>+++ | +++the new GridFSFile <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>+++
|===




---

=== Find files
`<mongo:find-files>`




+++
Lists all the files that match the given query
+++

==== XML Sample
[source,xml]
----
<mongo:find-files config-ref="Mongo_DB__Configuration" query-ref="myDbObject" />
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query+++ | #[payload] | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html">Iterable</a><<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>>+++ | +++a <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a> files iterable+++
|===




---

=== Find one file
`<mongo:find-one-file>`




+++
Answers the first file that matches the given query. If no object matches it, a MongoException is thrown.
+++

==== XML Sample
[source,xml]
----
<mongo:find-one-file config-ref="Mongo_DB__Configuration" query-ref="myDbObject" />
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> mandatory query+++ | #[payload] | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>+++
|===




---

=== Get file content
`<mongo:get-file-content>`




+++
Answers an inputstream to the contents of the first file that matches the given query. If no object matches it, a MongoException is thrown.
+++

==== XML Sample
[source,xml]
----
<mongo:get-file-content config-ref="Mongo_DB__Configuration" query-ref="myDbObject" />
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
fileId  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/BsonObjectId.html">BsonObjectId</a>+++ | +++the BsonObjectId of the file to be deleted+++ | #[payload] | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html">InputStream</a>+++ | +++an InputStream to the file contents+++
|===




---

=== List files
`<mongo:list-files>`




+++
Lists all the files that match the given query, sorting them by filename. If no query is specified, all files are listed.
+++

==== XML Sample
[source,xml]
----
<mongo:list-files config-ref="Mongo_DB__Configuration" query-ref="myDbObject"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> optional query+++ | #[payload] | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html">Iterable</a><<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>>+++ | +++an iterable of <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>+++
|===




---

=== Remove files
`<mongo:remove-files>`




+++
Removes the file that matches the given file id. If no file id is specified, all files are removed
<p/>
+++

==== XML Sample
[source,xml]
----
<mongo:remove-files config-ref="Mongo_DB__Configuration" query-ref="myDbObject"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
fileId  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/BsonObjectId.html">BsonObjectId</a>+++ | +++the BsonObjectId of the file to be deleted+++ | #[payload] | {nbsp}


|===





---

=== Execute command
`<mongo:execute-command>`




+++
Executes a command on the database
<p/>
+++




==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
commandName  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The command to execute on the database+++ |  | *x*{nbsp}




|
commandValue  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The value for the command+++ |  | {nbsp}


|===

==== Returns
[cols=".^40%,.^60%", options="header"]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The result of the command+++
|===




---

=== Dump
`<mongo:dump>`




+++
Executes a dump of the database to the specified output directory. If no output directory is provided then the default /dump directory is used.
+++

==== XML Sample
[source,xml]
----
<mongo:dump config-ref="Mongo_DB__Configuration" oplog="true"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
outputDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++output directory path, if no output directory is provided the default /dump directory is assumed+++ | dump | {nbsp}




|
outputName  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++output file name, if it's not specified the database name is used+++ |  | {nbsp}




|
zip  | +++boolean+++ | +++whether to zip the created dump file or not+++ | false | {nbsp}




|
oplog  | +++boolean+++ | +++point in time backup (requires an oplog)+++ | false | {nbsp}




|
threads  | +++int+++ | +++amount of threads to execute the dump+++ | 5 | {nbsp}


|===





---

=== Incremental dump
`<mongo:incremental-dump>`




+++
Executes an incremental dump of the database
<p/>
+++

==== XML Sample
[source,xml]
----
<mongo:incremental-dump config-ref="Mongo_DB__Configuration" />
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
outputDirectory  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++output directory path, if no output directory is provided the default /dump directory is assumed+++ | dump | {nbsp}




|
incrementalTimestampFile  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++file that keeps track of the last timestamp processed, if no file is provided one is created on the output directory+++ |  | {nbsp}


|===





---

=== Restore
`<mongo:restore>`




+++
Takes the output from the dump and restores it. Indexes will be created on a restore. It only does inserts with the data to restore, if existing data is there, it will not
be replaced.
+++

==== XML Sample
[source,xml]
----
<mongo:restore config-ref="Mongo_DB__Configuration" inputPath="dump/test.zip" oplogReplay="true"/>
----



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



|
inputPath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++input path to the dump files, it can be a directory, a zip file or just a bson file+++ | dump | {nbsp}




|
drop  | +++boolean+++ | +++whether to drop existing collections before restore+++ | false | {nbsp}




|
oplogReplay  | +++boolean+++ | +++replay oplog for point-in-time restore+++ | false | {nbsp}


|===
