= Upgrade SAP S/4HANA SOAP Connector to 2.x - Mule 4
:page-aliases: connectors::sap/sap-s4hana-soap-connector-upgrade-migrate.adoc

Upgrade Anypoint Connector for SAP S/4HANA SOAP to take advantage of the increased security offered by using OAuth 2.0 authentication to connect to SAP S/4HANA SOAP.

== Supported Upgrade Paths

This is a direct upgrade from version 1.0.0 version to 2.x.x.

[%header,cols="50a,50a"]
|===
|From Version | To Version
|1.0.0 |2.x.x
|===

== Changes in This Release

* OAuth 2.0 is supported. +
The *OAuth 2.0 Application Connection Provider* option has been added to *Connection* types. For information about the configuration parameters for this connection type, see xref:sap-s4hana-soap-connector-reference.adoc[SAP S/4HANA SOAP Connector Reference].
* Mule runtime engine (Mule) 4.2.1 or later is required.
* The base package name has been changed to `com.mulesoft.connector.sap.s4hana.soap` so that all exported classes now have different fully qualified names.

== Requirements and Limitations

Be aware of the following requirements and limitations before you upgrade to the latest version.

=== Requirements

You must be using Mule 4.2.1 or later.

=== Limitations

This upgrade breaks backward compatibility.

== Upgrade Prerequisites

Before you upgrade, create a backup of your files, data, and configurations in case you need to restore to them.

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In *Mule Palette*, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `SAP S/4HANA SOAP` in the search field.
. In *Available modules*, select *SAP S/4HANA SOAP Connector* and click *Add*.
. Click *Finish*.
. Verify that the `mule-sap-s4hana-soap-cloud-connector` dependency version is the one you are upgrading to in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

== Post Upgrade Steps

After you install the latest version of the connector, verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection and verify that the operations work.

== Troubleshooting

If there are problems with caching the parameters and metadata, try restarting Studio.

== Revert the Upgrade

If you must revert to your previous version of SAP S/4HANA SOAP Connector, change the `mule-sap-s4hana-soap-cloud-connector` dependency version 2.x.x in the project’s `pom.xml` to the previous version.

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
