= Amazon SQS Connector 5.9 - Mule 4

Anypoint Connector for Amazon SQS (Amazon SQS Connector) provides an easy way to interface with the Amazon Simple Queue Service (Amazon SQS) API, enabling Mule users to manage SQS queueing services without having to interact with the API directly.

Amazon SQS offers a reliable, highly scalable hosted queue for storing messages as they travel between computers. You can use Amazon SQS to move data between distributed application components and perform different tasks without losing messages or requiring each component to be always available. Amazon SQS makes it easy to build an automated workflow that works closely with Amazon Elastic Compute Cloud (Amazon EC2) and other AWS infrastructure web services.

The AWS SDK for Java provides a Java API for AWS infrastructure services. Amazon SQS Connector is built using the SDK for Java.

For compatibility information and fixed issues, see the Amazon SQS Connector Release Notes.

== Cluster Mode

Amazon SQS Connector supports listening for messages on the primary node only or on all nodes when running in cluster mode. For information, see xref:amazon-sqs-connector-config-topics.adoc#node-behavior[Receiving Messages in Cluster Mode].

== Queue Support

Amazon SQS Connector provides support for two types of queues:

* Standard Queues
+
Standard queues have high throughput. However, using these queues can occasionally result in having duplicate copies of messages delivered out of order.
+
* FIFO Queues
+
FIFO (First-In-First-Out) queues deliver messages in the order in which they are sent. However, these queues have limited throughput.

For information about creating FIFO queues, see xref:amazon-sqs-connector-config-topics.adoc[Additional Configuration Topics].

== Prerequisites

Before creating an app, you must:

* Have access to the Amazon SQS target resource and Anypoint Platform
* Understand how to create a Mule app using Design Center or Anypoint Studio
* Have AWS Identity and Access Management (IAM) credentials


== Audience

Read the Amazon SQS Connector documentation that meets the needs of the type of user that you are:

* New user
** To create your Mule app, see xref:amazon-sqs-connector-studio.adoc[Studio Configuration]. The xref:amazon-sqs-connector-config-topics.adoc[Additional Configuration Information]
topic helps extend your understanding of Amazon SQS Connector
** The xref:amazon-sqs-connector-examples.adoc[Examples] topic provides one or more use cases for using the connector.
* Advanced user
** Read the xref:amazon-sqs-connector-xml-maven.adoc[XML and Maven Support],
xref:amazon-sqs-connector-config-topics.adoc[Additional Configuration Information],
and xref:amazon-sqs-connector-examples.adoc[Examples] topics.

== Common Use Cases for the Connector

Common use cases for Amazon SQS Connector include sending messages to a queue and retrieving messages from a queue. For an example of these use cases, see xref:amazon-sqs-connector-examples.adoc#install-connector[Amazon SQS Examples].

== Authentication Types

Amazon SQS Connector connections use the following authentication types:

* Basic +
Uses a session token provided by Amazon STS to connect to Amazon SQS
* Role +
Uses the Amazon role ARN that uniquely identifies the role to assume to allow cross-account access

== Next Step

After you complete the prerequisites and experiment with examples, you are ready to create an app with xref:amazon-sqs-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-amazon-sqs-connector/[Amazon SQS Connector on Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
