= Using Anypoint Studio to Configure NetSuite REST Connector 1.0
:exchange-search-name: netsuite rest
:connector-name: NetSuite REST
:lc-connector-name: netsuite-rest
:studio-connector-name: NetSuite REST Connector

include::connectors::partial$t-studio-partial.adoc[tags=topic-intro]

[[create-mule-project]]
== Create a Mule Project

include::connectors::partial$t-studio-partial.adoc[tags=create-project-intro]

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

Add NetSuite REST Connector to your Mule project to automatically populate the XML code with the connector's namespace and schema location and add the required dependencies to the project's `pom.xml` file:

. In *Mule Palette*, click *(X) Search in Exchange*.
. In *Add Dependencies to Project*, type `netsuite rest` in the search field.
. Click *NetSuite REST Connector* in *Available modules*.
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio doesn't make that connector available to other projects in your Studio workspace.

[[configure-source]]
== Configure a Source

include::connectors::partial$t-studio-partial.adoc[tags=configure-source-intro]
You can configure one of these sources to use with NetSuite REST Connector:

* *On New Object*
+
Polls NetSuite for records of a specified type that were created since the last poll and emits an event for each one found.
* *On Modified Object*
+
Polls NetSuite for records of a specified type that were created or updated since the last poll and emits an event for each one found.
* *On Deleted Object*
+
Polls NetSuite for deleted-record metadata and emits an event for each deletion found.
* *HTTP Listener*
+
Initiates a flow each time it receives a request on the configured host and port.
* *Scheduler*
+
Initiates a flow when a time-based condition is met.

include::connectors::partial$t-studio-partial.adoc[tags=listener-steps]

[[add-connector-operation]]
== Add a Connector Operation to the Flow

When you add a connector operation to your flow, you are specifying an action for that connector to perform.

To add an operation for NetSuite REST Connector:

. In *Mule Palette*, select *NetSuite REST Connector* and then select the operation to add.
. Drag the operation onto the Studio canvas, next to the source.

[[configure-global-element]]
== Configure a Global Element for the Connector

When you configure a connector, configure a global element that all instances of that connector in the app can use. Configuring a global element requires you to provide the connection settings that the connector requires to access NetSuite.

To configure the global element for NetSuite REST Connector:

. Select the operation in the Studio canvas.
. In the *General* configuration screen for the operation, click the *Add* icon to access the global element configuration fields.
. In the *General* tab, in *Connection*, configure the <<oauth-client-credentials>> connection.
+
You can reference a configuration file that contains ANT-style property placeholders (recommended), or you can enter your connection settings in the global configuration properties. For information about the benefits of using property placeholders and how to configure them, refer to xref:connectors::introduction/intro-connector-configuration-overview.adoc[Anypoint Connector Configuration].
. In the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with NetSuite.
. Click *OK*.

[[oauth-client-credentials]]
=== OAuth 2.0 Client Credentials (JWT Bearer)

Use the OAuth 2.0 client credentials connection to authenticate with a JWT bearer assertion signed by a private key that is registered against a certificate in NetSuite.

Enter this information in the *General* tab of the *Global Element Properties* screen to configure the connection:

[%header,cols="30s,70a"]
|===
|Field |User Action
|Name |Enter the configuration name.
|Account ID | Enter the NetSuite account ID (for example, `TSTDRV1234567` or `1234567_SB1`).
|Client ID | Enter the OAuth 2.0 client ID from the integration record in NetSuite.
|Certificate ID | Enter the certificate ID (`kid`) registered in NetSuite for JWT signing.
|Private Key (PEM) | Enter the PEM-encoded private key that matches the registered certificate. Supply this value through a secure property.
|Signature Algorithm | Select the JWT signing algorithm: `ES512` (recommended), `ES256`, `ES384`, `PS256`, `PS384`, or `PS512`. The algorithm must match the key type of the registered certificate.
|Token Object Store | Optionally specify an object store for OAuth token persistence across cluster nodes. When unset, a persistent, config-name-keyed store is created automatically.
|===

In the *Advanced* tab, you can optionally configure timeouts, maximum connections, a proxy, a concurrency management strategy for HTTP 429 and 503 responses, and reconnection behavior. If you use the HTTPS protocol, configure TLS in the *TLS* tab.

[[configure-other-fields]]
== Configure Additional Connector Fields

After you configure a global element for the connector, configure the other required fields. The required fields vary depending on which connector operation you use.

For detailed configuration information for each operation type, see xref:netsuite-rest-connector-additional-config.adoc[NetSuite REST Connector - Additional Configuration Information].

[[view-app-log]]
== View the App Log

include::connectors::partial$t-studio-partial.adoc[tags=view-app-log]

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-config-use-studio.adoc[Using Studio to Configure a Connector]
* xref:{lc-connector-name}-connector-reference.adoc[NetSuite REST Connector Reference]
* https://help.salesforce.com[Salesforce Help]
