= Microsoft Dynamics 365 Business Central Connector 1.0 - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Microsoft Dynamics 365 Business Central (Microsoft Dynamics 365 Business Central Connector) enables you to manage entities for your companies in Microsoft Dynamics 365 Business Central.

For information about compatibility and fixed issues, refer to the Microsoft Dynamics 365 Business Central Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Microsoft Dynamics 365 Business Central API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have:

* Credentials to access the Microsoft Dynamics 365 Business Central target resource
* Anypoint Platform
* Anypoint Studio version 7.3.5 or later

== Common Use Cases for the Connector

Some common use cases for Microsoft Dynamics 365 Business Central Connector include:



== Connection Types

Microsoft Dynamics 365 Business Central connections use the following authentication types:

* Key Token authentication
+
Provides an all access key token.

* Resource Token authentication
+
Provides temporary (1-5 hours), limited access to resources in your account without providing direct access to the master key.


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:microsoft-dynamics-365-business-central-connector-reference.adoc[Microsoft Dynamics 365 Business Central Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
