= Upgrade and Migrate to NetSuite 10.0 - Mule 4

Upgrade NetSuite Connector to version 10.0 to use the new features. 

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|9.3.0 |10.0.0
|===

== Changes in This Release

This release contains the following changes:

* These authentication types were removed:
** *Login Authentication* 
** *SSO Authentication* 
* These operations were added: 
** *Get Account Governance Info* 
** *Get Integration Governance Info* 
* The *Map SSO* operation was removed.
* The *UKNOWN* error code was removed. +
All unknown errors are now thrown under the *ERROR_FAULT* error code.
* Many operation inputs were slightly altered, to make them more consistent with other Anypoint Connectors.
* All exposed classes have been moved from the `org.mule.module.netsuite.extension.api` package to the `com.mulesoft.connector.netsuite.extension.api` package.

[[changed_operations]]
== Changed Operations

[%header%autowidth.spread]
|===
|Operation | Parameter | Change

| Change Email a| newEmail a| No longer defaults to `payload`
| Change Password a| newPasword a| No longer defaults to `payload`
| Get Data Center URLs a| accountId a| No longer defaults to `payload`
| Async Search a| content a| Is now a *primary content* parameter
| Get Async Result a| jobId a| No longer defaults to `payload`
| Async Add List a| recordAttributes a| Is now a *primary content* parameter
| Async Update List a| recordAttributes a| Is now a *primary content* parameter
| Async Upsert List a| recordAttributes a| Is now a *primary content* parameter
| Update Invitee Status List a| inviteeStatuses a| Is now a *primary content* parameter
| Get Posting Transaction Summary a| fields a| Is now a *primary content* parameter
| Get Posting Transaction Summary a| filters a| Is now a *content* parameter
| Add File a| attributes a| Is now a *content* parameter
| Add Record a| attributes a| Is now a *content* parameter.
| Get Custom Record a| internalId a| No longer defaults to `payload` 
| Get Deleted Records a| deletedDate a| Is now a *content* parameter
| Update Record a| attributes a| Is now a *content* parameter
| Upsert Record a| attributes a| Is now a *content* parameter
|===

[[changed_sources]]
== Changed Sources

The three message sources were renamed.

[%header%autowidth.spread]
|===
|Source name |Old XML name | New XML name

| On New Object | `<netsuite:new-object-trigger ...` | `<netsuite:new-object-listener ...`
| On Modified Object |  `<netsuite:modified-trigger ...` | `<netsuite:modified-listener ...`
| On Deleted Object | `<netsuite:deleted-trigger ...` | `<netsuite:deleted-listener ...`
|===

== Upgrade Steps

If you are upgrading from an earlier version of the connector, a small popup appears in the bottom right corner of Anypoint Studio with the `Updates Available` message.

Click the pop-up and follow the prompts to install the latest version.

You can also follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In *Mule Palette*, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `NetSuite` in the search field.
. In *Available modules*, select *NetSuite* and click *Add*.
. Click *Finish*.
. Verify that the NetSuite Connector dependency version is 10.0.0 in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

== Additional Notes

* If you were using one of the authentication schemas that were removed, you must change your configurations so that they use either *Request Based* or *Token* authentication. 
* You must verify that your error handling is updated and works as expected, given the minor changes in error codes in this version of the connector. 
* Refer to the previous table for updated operations and sources. If your integration uses any of the affected components, make the necessary changes to comply with the new interfaces.
* All DataWeave mappings that create objects for operation inputs must be updated, since the package of the exposed classes was changed to `com.mulesoft.connector.netsuite.extension.api`. +
You must also update mappings that transform object outputs.

=== Verify the Upgrade

After you install the latest version of the connector, verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

=== Reverting the Upgrade

If you must revert to your previous version of NetSuite Connector, change the `mule-netsuite-connector` dependency version `10.0.0` in the project’s `pom.xml` to the previous version.
Additionally, revert any changes made in the operations to their previous state.

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
