= Veeva Vault Connector 1.3 Reference - Mule 4

[[connection_configuration]]
== Configuration

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Name |String | Name for this configuration. Connectors reference the configuration with this name. | |X
|Vault URL |String | URL of the Veeva Vault instance required for the connection. | |X
|Username |String | Username used to initialize the session. | |X
|Password |String | Password used to authenticate the user. | |X
|Version |String | Veeva Vault API version. |v20.1 |
|Client Id |String | Client ID to send with each request header to the Veeva Vault instance for tracking purposes. The format is `\{organization}-{component/team}`, for example `abcpharma-clinicalprod`. Before sending the request, the client ID is prefixed with `mulesoft` and suffixed with `client-vaultconnector`, for example `mulesoft-abcpharma-clinicalprod-client-vaultconnector`. | |X
|===

=== Response Timeout (Advanced Tab)

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Response Timeout |Integer | Maximum time, in milliseconds, that the connector waits for the Veeva Vault response. If the time is exceeded, a `Response Timeout` exception is thrown. | `30000 ms` |X
|===

=== Burst API Limit Profile (Advanced Tab)
`<veevavault:burst-api-limit-profile/>`

Use *Burst API Limit Profile* if the specified burst API limit of the Veeva Vault API reaches or exceeds the configured threshold value.

If the value of *Burst API Limit Profile* is set to `Burst api limit config (Default)`, the connector evaluates the specified burst API limit of the Veeva Vault API response header (`X-VaultAPI-BurstLimitRemaining`) against the configured threshold value. If the remaining burst API limit reaches or exceeds the configured threshold value, the connector waits for the specified amount of time to restart the count for *Burst Limit Remaining*.

For more information, refer to https://developer.veevavault.com/docs/#api-rate-limits[API Rate Limit Headers].

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|API Limit Threshold |Integer | Veeva Vault API threshold limit. When this threshold is reached or exceeded, the connector waits the specified time. | `200` |X
|Wait Time |Integer | Time the connector waits once the threshold value reaches or exceeds the remaining API calls. | `5` |X
|Time Unit a|
* DAYS
* HOURS
* MINUTES
* SECONDS
* MILLISECONDS
* NANOSECONDS

| Time unit for the *Wait Time* field. | `MINUTES` |X
|===

=== Daily API Limit Profile (Advanced Tab)
`<veevavault:daily-api-limit-profile/>`

Use *Daily API Limit Profile* to configure the API limit threshold that is evaluated against the remaining daily API limit calls. If the daily API limit calls reach or exceed the specified API limit threshold value, an exception is thrown. *Daily API Limit Profile* is disabled by default.

For more information, refer to https://developer.veevavault.com/docs/#api-rate-limits[API Rate Limit Headers].

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|API Limit Threshold |Integer | API limit threshold value to set the allowed daily limit for the number of API calls. Once the API limit threshold value is reached, the connector throws an `API_LIMIT_EXCEED` exception for each request invoking an API call.  | `10000` |X
|===

== Operations

* <<create_documents,Create Documents>>
* <<create_document_renditions,Create Document Renditions>>
* <<create_object_records,Create Object Records>>
* <<delete_documents,Delete Documents>>
* <<delete_document_renditions,Delete Document Renditions>>
* <<delete_object_records,Delete Object Records>>
* <<export_documents,Export Documents>>
* <<get_audit_details,Get Audit Details>>
* <<get_documents,Get Documents>>
* <<get_document_renditions_types,Get Document Renditions>>
* <<get_object_records,Get Object Records>>
* <<get_picklists,Get Picklists>>
* <<invoke_rest_api,Invoke REST API>>
* <<query,Query>>
* <<spark_validator,Spark Validator>>
* <<update_documents,Update Documents>>
* <<update_object_records,Update Object Records>>


[[create_documents]]
=== Create Documents
`<veevavault:create-documents>`

Creates single or multiple documents on Veeva Vault using document metadata provided in CSV or JSON format. You must upload document files with the content to attach to the created documents to the vault FTP server location.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Metadata Format a|
Enum (String):

* CSV
* JSON

|Format of the document metadata. | |X
|Document Metadata |Input Stream a| Document metadata as an Input Stream. The payload must be in the format specified in the *Metadata Format* field. | |X
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[create_document_renditions]]
=== Create Document Renditions
`<veevavault:create-document-renditions>`

Creates document renditions in bulk on Veeva Vault using document metadata provided in CSV or JSON format.

Your vault must be in Migration Mode before using this operation. This operation takes CSV input data with a maximum size of 1 GB with a standard UTF-8-encoded value.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Metadata Format a|
Enum (String):

* CSV
* JSON

|Format of the document metadata. | |X
|Document Metadata |Input Stream a|
Document metadata as an Input Stream. The payload must be in the format specified in the *Metadata Format* field.
| |X
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[create_object_records]]
=== Create Object Records
`<veevavault:create-object-records>`

Creates bulk object records for the selected vault object using object metadata provided in CSV or JSON format.


==== Parameters

|===
|Name |Type |Description |Default Value |Required
|Object Name |String a| Click the Veeva Vault refresh icon to retrieve the vault object list. Select the object name from the list to create records for the selected object.
| |X
|Metadata Format a|
Enum (String):

* CSV
* JSON

|Format of the object metadata. | |X
|Object Metadata |Input Stream a|
Object metadata as an Input Stream. The payload must be in the format specified in the *Metadata Format* field.
| |X
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED


[[delete_documents]]
=== Delete Documents
`<veevavault:delete-documents>`

Deletes single or multiple documents from Veeva Vault using document metadata provided in CSV or JSON format.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Metadata Format a|
Enum (String):

* CSV
* JSON

|Format of the document metadata. | |X
|Document Metadata |Input Stream a|
Document metadata as an Input Stream. The payload must be in the format specified in the *Metadata Format* field.
| |X
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[delete_document_renditions]]
=== Delete Document Renditions
`<veevavault:delete-document-renditions>`

Deletes document renditions in bulk from Veeva Vault using document metadata provided in CSV or JSON format.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Metadata Format a|
Enum (String):

* CSV
* JSON

|Format of the document metadata. | |X
|Document Metadata |Input Stream a|
Document metadata as an Input Stream. The payload must be in the format specified in the *Metadata Format* field.
| |X
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED


[[delete_object_records]]
=== Delete Object Records
`<veevavault:delete-object-records>`

Deletes object records in bulk from the selected vault object using object metadata provided in CSV or JSON format.

==== Parameters
[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Object Name |String a| Click the Veeva Vault refresh icon to retrieve the vault object list. Select the object name from the list to delete records for the selected object.
| |X
|Metadata Format a|
Enum (String):

* CSV
* JSON

|Format of the object metadata. | |X
|Object Metadata |Input Stream a|
Object metadata as an Input Stream. The payload must be in the format specified in the *Metadata Format* field.
| |X
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[export_documents]]
=== Export Documents
`<veevavault:export-documents>`

Queries a set of documents to export to your vault’s FTP staging server.

Use the *Export Documents* operation in a separate asynchronous flow by using Async Scope and passing the payload with document IDs. When used asynchronously, the *Export Documents* operation executes in separate flow thread and waits for the specified polling interval to poll the job status until it is successful while the main flow continues its process.

The FTP staging area in the folder stores the exported documents, with the
`\{root}/\{userId}/\{jobId}/\{documentIds}/\{versions}` hierarchy structure.

The following example shows the *Export Documents* operation returning job results as a response:

----
[
  {
	"file": "/41601/249051/0_1/TestDocument.docx",
	"user_id__v": 1885110,
	"id": 249051,
	"responseStatus": "SUCCESS",
	"minor_version_number__v": 1,
	"major_version_number__v": 0
  },
  {
	"file": "/41601/249050/0_1/TestDocument.docx",
	"user_id__v": 1885110,
	"id": 249050,
	"responseStatus": "SUCCESS",
	"minor_version_number__v": 1,
	"major_version_number__v": 0
  },
  {
	"file": "/41601/249052/0_1/TestDocument.docx",
	"user_id__v": 1885110,
	"id": 249052,
	"responseStatus": "SUCCESS",
	"minor_version_number__v": 1,
	"major_version_number__v": 0
  }
]
----

This example contains the following attributes:

* `file` +
Uses the `"/{jobId}/{documentId}/{major-minor-version}/{filename}"` format, which is the absolute file path location on the Vault FTP server staging area.
* `user_id__v` +
Vault system user ID of a user whose credentials are configured in the connector. The folder is created on the Vault FTP server staging area root location under where the exported file is located. The folder is created with the name of the user ID prefixed with the letter `u`, for example
`/uXXXXXXX/{jobId}/{documentId}/{major-minor-version}/{filename}\)`.
* `id` +
Document ID of the exported document file.
* `major_version_number__v` +
Major version number of the exported document file.
* `minor_version_number__v` +
Minor version number of the exported document file.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Metadata Format a|
Enum (String):

* CSV
* JSON

|Format of the object metadata. | |X
|Document Metadata |Input Stream a|
Document metadata as an Input Stream. The payload must be in the format specified in the *Metadata Format* field.
|#[payload] |X
|Source |Boolean |To exclude source files, set to `false`.  |`true` |
|Renditions |Boolean |To include renditions, set to `true`.  |`false` |
|All Versions |Boolean |To include all versions or the latest version, set to `true`. |`false` |
|Polling Interval |Integer |Poll the vault at the specified interval, in seconds, until the job is successful. |`30` |
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[get_audit_details]]
==== Get Audit Details
`<veevavault:get-audit-details>`

Retrieves audit details for the specified audit type.

This operation provides a paging mechanism based on Mule standard pagination. Refer to xref:veevavault-connector-config-topics#streaming_and_pagination.adoc[Streaming and Pagination] for more details.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Audit Type |String a|Click the Veeva Vault refresh icon to retrieve audit types from the vault. Select an audit type from the list whose audit details you need to retrieve.
| |X
|Start Date |String |The date from which to start retrieving audit information. This date cannot be more than 30 days in the past. Dates must be in `YYYY-MM-DDTHH:MM:SSZ` format. Dates and times are in UTC. If the time is not specified, the start date defaults to midnight (T00:00:00Z) on the specified date.
| |
|End Date |String |The date from which to stop retrieving audit information. This date cannot be more than 30 days in the past. Dates must be in `YYYY-MM-DDTHH:MM:SSZ` format. Dates and times are in UTC. If the time is not specified, the start date defaults to midnight (T00:00:00Z) on the specified date.
| |
|Fetch Size |Integer |Provides the number of records per page. |`100` |
|Batch Size |Integer |Provides the number of pages per batch.  |`10` |
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED


[[get_documents]]
=== Get Documents
`<veevavault:get-documents>`

Retrieves document details from Veeva Vault. You can either:

* Provide document properties (document type, subtype, and classification) to retrieve document details.
+
If document properties are provided, the *Get Documents* operation builds the VQL query dynamically. The VQL query is then executed on the vault to retrieve document details.

* Have document properties (document type, subtype, and classification) fetched to retrieve document details.
+
If document properties are not provided, the document properties metadata is fetched using `/api/{version}/metadata/objects/documents/properties` and the VQL query is built based on the document metadata properties added or inserted in the *Document Properties* list. If metadata properties are not provided, then all queryable document properties are used and executed in the VQL query.

Place a For-Each/Splitter element after this operation to fetch each document’s data (page) sequentially.

This operation provides a paging mechanism based on Mule standard pagination. Refer to xref:veevavault-connector-config-topics#streaming_and_pagination.adoc[Streaming and Pagination] for more details.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Type |String |List of all document types that are available to select from. | |
|Subtype |String |List of all document subtypes that are available to select from. | |
|Classification |String |List of all document classifications that are available to select from. | |
|Document Properties |List<String> |Insert document properties based on your business requirements into the list. If not provided, all queryable document properties are selected to build a VQL query and are invoked internally to retrieve document details. | |
|WHERE Clause |String | WHERE clause that is appended to dynamically build a VQL query. | |
|Fetch Size |Integer |Provides the number of records per page. |`100` |
|Batch Size |Integer |Provides the number of pages per batch.  |`10` |
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[get_document_renditions_types]]
=== Get Document Renditions Types
`<veevavault:get-document-renditions>`

Retrieves document renditions details.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Document Metadata |Input Stream a|
Document metadata as an Input Stream. The payload must be in the format specified in the *Metadata Format* field.
| |X
|===

==== Configurations

<<connection_configuration,Configuration>>


==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[get_object_records]]
=== Get Object Records
`<veevavault:get-object-records>`

Retrieves object records details using object metadata fields to build a VQL query dynamically and execute on the vault to get object details. Place a For-Each/Splitter element after this operation to fetch each object records (page) sequentially.

This operation provides a paging mechanism based on Mule standard pagination. Refer to xref:veevavault-connector-config-topics#streaming_and_pagination.adoc[Streaming and Pagination] for more details.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Object Name |String a| List of all vault objects available to select from.
| |X
|Object Fields |List<String> |Insert object fields based on your business requirements into the list. If not provided, all active object fields available are selected to build a VQL query and are invoked internally to retrieve object records details.  | |
|WHERE Clause |String |LINKK SKK VQL WHERE clause (without using the keyword WHERE) that is appended to dynamically build a VQL query to execute on the vault, for example `study_country__v = ‘0SC000000000101`.
| |
|Fetch Size |Integer |Provides the number of records per page. |`100` |
|Batch Size |Integer |Provides the number of pages per batch.  |`10` |
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[get_picklists]]
==== Get Picklists
`<veevavault:get-picklists>`

Retrieves all available values configured on a picklist.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Picklist Name |String a|
List of audit types available on the vault to select from.
| |X
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[invoke_rest_api]]
=== Invoke REST API
<veevavault:invoke-rest-api>

Invokes https://developer.veevavault.com/api/20.1/#documents[Veeva Vault Rest APIs] and returns responses in JSON (default) or XML format depending on the header *Accept* value provided. It is important to use bulk Rest APIs whenever possible, rather than single APIs, to maintain https://developer.veevavault.com/docs/#api-rate-limits[API rate limits].

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Method |String a|
List of methods to invoke REST API.
| `GET` |X
|Path |String |
URI path of where to send the request.
| |X
|Body |Input Stream |
Body of the request message to send with the request (except for with the GET method request).

|#[payload]  |
|Headers |Map |
Headers in key-value format to send along with the request. If there are no headers required in a request, leave this parameter empty (default).
| |
|URI Parameters |Map |
URI parameters in key-value format to resolve the value in a path. If there are no URI parameters in a path, leave this parameter empty (default).
| |
|Query Parameters |Map |
Query parameters in key-value format to send along with the request. If there are no query parameters required in a request, leave this parameter empty (default).
| |
|Request Streaming Mode |Stream a|
Request to send in streaming mode. By default, if the type of the payload is a stream, streaming is used to send the request. You can select from the following options:

* ALWAYS
* AUTO
* NEVER | |
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[query]]
=== Query
`<veevavault:query>`

Executes the specified VQL query on the vault and retrieves the result in a paginated data input stream. Place a For-Each/Splitter element after the Query operation to fetch each record in sequential order.

This operation provides a paging mechanism based on Mule standard pagination. Refer to xref:veevavault-connector-config-topics#streaming_and_pagination.adoc[Streaming and Pagination] for more details.

[NOTE]
Do not specify `LIMIT` and `OFFSET` in the VQL query. These parameters are incorporated internally.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|VQL Query |String a|
VQL query to define based on the Veeva Vault VQL specification to execute, for example `SELECT id, name__v, study__v FROM :table`. Refer to https://developer.veevavault.com/api/19.1/#vault-query-language-vql[VQL query documentation] for more details.
| |X
|Input Parameters |Map<String, Object> a|
Map of String and Objects in which every item represents a row to insert. The map contains the parameter names as keys and the parameter they are bound to as values, for example:

----
{

'table': 'site__v'

}
----

|#[{}] |
|Fetch Size |Integer |Provides the number of records per page. |`100` |
|Batch Size |Integer |Provides the number of pages per batch.  |`10` |
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[spark_validator]]
=== Spark Validator
`<veevavault:spark-message-validator>`

Validates and verifies Spark messages triggered from the vault with a signature and public key. Upon successful validation and verification, the Spark message can be further processed in the Mule flow according to your business requirements. Refer to https://developer.veevavault.com/sdk/#spark-messaging[Spark Messaging feature and functionalities and setup] for more details.

The output of the *Spark Validator* operation includes Spark attributes (optional) with the Spark message as it is received from the vault.

[NOTE]
Before triggering a Spark message from the vault, make sure to raise a support ticket with Veeva Vault Support to increase the time interval (for example, 10 seconds) for the Spark message to resend or retry. By default, the time interval is configured as 5 seconds, which is less than the time required for the *Spark Validator* operation to complete message validation and verification.

[NOTE]
As per Veeva Systems, the public key (00001.pem) expires every two years. You receive notification in advance advising you of the expiration date. If you are using the *Spark Validator* operation in a Mule application flow, after the public key expiration date you must remove the public key file from the path configured in the *Public Key Path* field. A new public key will be created during execution of the key removal. If you don’t do this, Spark message verification fails as `INVALID_SPARK_MESSAGE`. The Mule application deployed on CloudHub with the default path must be restarted for successful Spark message verification.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Include Spark Headers|
Boolean
|Flag to include Spark headers received from the vault in the Spark validator output.
|FALSE|
|Public Key Path|
String
|Directory path to store the public key (00001.pem) file that is used to verify incoming Spark messages with a signature. Retrieved from the vault, if not specified.
|`${mule.home}/apps/${app.name}/publickeys`|
|Spark Headers|
Object
|Spark headers received from the vault and embedded in the Spark message.
|#[attributes.headers]|
|Spark Message|
Input Stream
|Spark message body received from the vault.
|#[payload]|
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED
* VEEVAVAULT:INVALID_SPARK_MESSAGE
* VEEVAVAULT:INVALID_KEY_FORMAT


[[update_documents]]
=== Update Documents
`<veevavault:update-documents>`

Updates bulk documents using editable metadata in the payload provided in CSV or JSON format.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Metadata Format a|
Enum (String):

* CSV
* JSON

|Format of the object metadata. | |X
|Document Metadata |Input Stream a|
Document metadata as an Input Stream. The payload must be in the format specified in the *Metadata Format* field.
| |X
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED

[[update_object_records]]
=== Update Object Records
`<veevavault:update-object-records>`

Updates object records of a specified vault object using editable object metadata in the payload provided in CSV or JSON format.

==== Parameters

[%header%autowidth.spread]
|===
|Name |Type |Description |Default Value |Required
|Object Name |String a|
List of all vault objects available to select from.
| |X
|Metadata Format a|
Enum (String):

* CSV
* JSON

|Format of the object metadata. | |X
|Object Metadata |Input Stream a|
Object metadata as an Input Stream. The payload must be in the format specified in the *Metadata Format* field.
| |X
|===

==== Configurations

<<connection_configuration,Configuration>>

==== Throws

* VEEVAVAULT:API_LIMIT_EXCEEDED
* VEEVAVAULT:ATTRIBUTE_NOT_SUPPORTED
* VEEVAVAULT:INACTIVE_USER
* VEEVAVAULT:INVALID_DATA
* VEEVAVAULT:INVALID_DOCUMENT
* VEEVAVAULT:INSUFFICIENT_ACCESS
* VEEVAVAULT:MALFORMED_URL
* VEEVAVAULT:METHOD_NOT_SUPPORTED
* VEEVAVAULT:NO_PERMISSION
* VEEVAVAULT:OPERATION_NOT_ALLOWED
* VEEVAVAULT:PARAMETER_REQUIRED


== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
