= Amazon SQS - Upgrade and Migrate - Mule 4
:page-aliases: connectors::amazon/amazon-sqs-connector-upgrade-migrate.adoc

Upgrade Anypoint Connector for Amazon SQS to take advantage of running the application on single or multiple nodes.

== Supported Upgrade Paths

[%header,cols="50a,50a"]
|===
|From Version | To Version
|5.5.0 |5.6.0
|5.4.3 |5.6.0

== Changes in This Release

* Cluster node support was added back to the xref:amazon-sqs-connector-reference.adoc#sources[Receive Messages] input source. The cluster node support behavior in this version works the same as in version 5.4.3. The input source listens for messages on all cluster nodes by default, but you can change this behavior by using the `Primary node only` field on the `Advanced tab`. For more information, see 5.6/amazon-sqs-connector-config-topics.adoc#node-behavior,Receiving Messages on Single or Multiple Nodes>>.
* Version 5.5.0 was deprecated because cluster mode support was accidentally removed from that version.

== Requirements

Ensure your system meets the following requirements before you perform the upgrade:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule |4.1.1 and later
|Java|1.8.0_x
|Anypoint Studio|7.0 and later
|===

See the xref:release-notes::connector/amazon-sqs-connector-release-notes-mule-4.adoc[Amazon SQS Connector Release Notes] for updated compatibility information for patch updates.

== Upgrade Prerequisites

Before you upgrade, create a backup of your files, data, and configurations in case you need to restore to them.

== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. Enter `Amazon_SQS_Configuration` in the search field.
. In the *Available modules* section, select *Amazon SQS Connector* and click *Add*.
. Click *Finish*.
. Verify that the `mule-amazon-sqs-connector` dependency version is 5.6.x in the `pom.xml` file in the Mule project. Replace `x` with the version that corresponds to the connector you are using.

Studio upgrades the connector automatically.

== Post Upgrade Steps

After you install the latest version of the connector, verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. When the application contains *Receive Message* source, choose whether the application should run on single or multiple nodes by using the *Primary node only* option on *Advanced tab*.
. Test the connection and verify that the operations work.

== Troubleshooting

If there are problems with caching the parameters and metadata, try restarting Studio.

== Revert the Upgrade

If you must revert to your previous version of Amazon SQS Connector, change the `mule-amazon-sqs-connector` dependency version `5.6.x` in the project’s `pom.xml` to the latest version which is not deprecated, `5.4.3`.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
