= Compression Module - Mule 4
:page-aliases: connectors::compression/compression-module.adoc

Compression module supports and provides access to the most-used file archiver and compression formats through a Mule app.

A file archiver is a computer program that combines a number of files together into one archive file for easier transportation or storage. Most archivers employ data compression in their archive formats to reduce the size of the final archive. However, not all compression algorithms can archive multiple files. Some are limited to single-file data compression.

This module compresses and decompresses files for each of the available formats without losing any of the features that the format associated algorithm
provides.

To achieve this capability, the module provides the *Compress* and *Decompress* operations that enables you to compress or decompress a single file, and the *Archive* and *Extract* operations for archiving and extracting a bundle of files. You can configure each of these operations with the compression or archiving  strategies of your choice.

For information about compatibility and fixed issues, see the Compresion module Release Notes.

== Before You Begin

To use this connector, you must be familiar with:

* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* How to create a Mule app using Anypoint Studio

Before creating an app, you must have access to Anypoint Platform and Anypoint Studio version.


== See Also
* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* xref:compression-documentation.adoc[Compression Module Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
