= Google Drive Connector 1.0

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Google Drive (Google Drive Connector) synchronizes data and automates business processes between Google Drive and third-party applications, either on-premises or in the cloud.

Google Drive is a calendar and task planning application that focusses on enhancing personal and team productivity. Using Google Drive, individuals can easily schedule tasks and meetings. They can also share events with colleagues through an easy-to-use calendar interface.

For compatibility information and fixed issues, see the Google Drive Connector Release Notes.

== Prerequisites

To use this connector, you should be familiar with:

* The Google Drive API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access Google Drive
* Anypoint Studio version 4.2.1 or later

== Common Use Cases for the Connectors

Common use cases for Google Drive Connector include the following:


== Authentication Types

Google Drive Connector uses the OAuth 2.0 authentication type, which uses access tokens provided by the authorization server to get access to protected data.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://help.mulesoft.com[MuleSoft Help Center]
