= AMQP Connector Examples - Mule 4

To fully benefit from using Anypoint Connector for AMQP (AMQP Connector), see the following examples of configuring the connector operations:

* xref:amqp-ack.adoc[Manage Message Acknowledgment] +
Configure AMQP Connector to manage different acknowledgment configurations, such as automatic acknowledgment on success, immediate acknowledgment, and manual acknowledgment.
* xref:amqp-listener.adoc[Listen for New Messages] +
Configure the *Listener* source to listen for new messages as they arrive into an AMQP queue.
* xref:amqp-publish.adoc[Publish New Messages] +
Configure the *Publish* operation to create a new AMQP message and send it to the specified exchange.
* xref:amqp-consume.adoc[Consume Messages] +
Configure the *Consume* operation to consume a message at any given time in the flow, from any given AMQP queue.
* xref:amqp-publish-consume.adoc[Publish and Consume a Message] +
Configure the *Publish consume* operation to publish a message to any exchange, and then wait for a reply on a different destination.
* xref:amqp-transactions.adoc[Manage Transactions] +
Configure AMQP Connector to manage transactional connections to execute a series of operations.
* xref:amqp-topography.adoc[Avoid Changing the AMQP Topography] +
Configure AMQP Connector global config properties so that the declaration of AMQP exchanges and queues is disabled.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
