= Redis Connector - Get Started - Mule 4

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Redis Connector v5.1

Anypoint Connector for Remote Dictionary Server (Redis Connector) is an open source, in-memory data structure store that is used for use cases such as caching a user profile, creating a leader board, tracking real time activities on a website, implementing a spam filtering system, using it as a message queue, use as a custom object store, and more.

Release Notes: xref:release-notes::connector/redis-connector-release-notes-mule-4.adoc[Redis Connector Release Notes] +
Exchange: https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-redis-connector/[Redis Connector]

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect to APIs
and resources on external systems, such as Salesforce, Redis, ServiceNow, and Twitter.

== Prerequisites

Before creating an app, you must have access to the Redis target resource and Anypoint Platform. You must also understand how to create a Mule runtime engine (Mule) app using Design Center or Anypoint Studio.

== Audience

* Starting user
+
Read this Get Started document and create your Mule app in xref:redis-connector-design-center.adoc[Design Center] or xref:redis-connector-studio.adoc[Anypoint Studio]. The xref:redis-connector-config-topics.adoc[Additional Configuration Information] topic helps extend your understanding of the Redis connector.
* Power user
+
Read the xref:redis-connector-xml-maven.adoc[XML and Maven Support], xref:redis-connector-config-topics.adoc[Additional Configuration Information], and xref:redis-connector-examples.adoc[Examples] documents.


== Next

After you have met the prerequisites, you are ready to create an app with xref:redis-connector-design-center.adoc[Design Center] or xref:redis-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/com.mulesoft.connectors/mule-redis-connector/[Redis in Anypoint Exchange]
* https://eu1.anypoint.mulesoft.com/exchange/com.mulesoft.connectors/mule-redis-connector/[Redis in the EU Anypoint Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
