= Redis XML and Maven Support - Mule 4

If you manually code a Mule app in XML either from the Anypoint Studio XML editor or from a text editor, you can get access to the Redis Connector in your app by adding reference statements to your XML Mule flow and in the Apache Maven `pom.xml` file.

[NOTE]
====
You can avoid the manual process described in this topic by using Studio. When you install the Redis Connector in Anypoint Studio, Studio automatically populates the XML code with the Redis Connector namespace and schema location, and adds a dependency to the `pom.xml` file.
====

== Add a Namespace for the Connector

Paste the following code inside the `<mule>` tag of the header of your configuration XML:

[source,xml,linenums]
----
<mule xmlns:redis="http://www.mulesoft.org/schema/mule/redis
...
http://www.mulesoft.org/schema/mule/redis
http://www.mulesoft.org/schema/mule/redis/current/mule-redis.xsd">
----

This example shows how the namespace statements are placed in the mule XML block:

[source,xml,linenums]
----
<mule xmlns:redis="http://www.mulesoft.org/schema/mule/redis"
	xmlns:tracking="http://www.mulesoft.org/schema/mule/ee/tracking"
	xmlns:http="http://www.mulesoft.org/schema/mule/http"
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:spring="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
	http://www.springframework.org/schema/beans/spring-beans-current.xsd
	http://www.mulesoft.org/schema/mule/core
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/http
	http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
	http://www.mulesoft.org/schema/mule/ee/tracking
	http://www.mulesoft.org/schema/mule/ee/tracking/current/mule-tracking-ee.xsd
	http://www.mulesoft.org/schema/mule/redis
	http://www.mulesoft.org/schema/mule/redis/current/mule-redis.xsd">
----

== Add a POM File Dependency

The `pom.xml` Maven file generated by Anypoint Studio contains dependencies for a Mule app. When you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to the connector. 


[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-redis-connector</artifactId>
  <version>x.x.x</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

Replace `x.x.x` with the version that corresponds to the connector you are using.

To obtain the most up-to-date `pom.xml` file information, access the connector in https://www.mulesoft.com/exchange/[Anypoint Exchange] and click *Dependency Snippets*.

== Next

After completing your namespace and `pom.xml` file, you can try the Redis xref:redis-connector-examples.adoc[Examples].

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
