= Twilio Connector 4.0 - Mule 4
:page-aliases: connectors::twilio/twilio-connector.adoc

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Anypoint Connector for Twilio (Twilio Connector) provides a cloud communications infrastructure as a service (IaaS).

Twilio Connector provides connectivity to the Twilio SMS API, which enables you to send SMS messages, receive SMS messages. To get started with Twilio, follow the steps in to gain access to the Twilio free sandbox service to send SMS text messages. You can configure the Twilio connector in Anypoint Studio with your API credentials.

For compatibility information and fixed issues, see the Twilio Connector Release Notes.

== Prerequisites

To use this connector, you must be familiar with:

* The Twilio Messaging API
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* An active Twilio.com trial or paid account
* Credentials to access the Twilio target resource

[[create-twilio-account]]
== Create a New Twilio Account

To create a new Twilio account, browse to the https://www.twilio.com/try-twilio+L[Try Twilio] website and follow the directions.

Copy the Account SID and Auth Token values to use with the Twilio Connector configuration. As you copy fields from the Twilio website to the Anypoint Studio connector configuration, ensure that you don't copy in additional leading and trailing characters or spaces. Doing so will cause authentication to fail.

== Next Step

After you complete the prerequisites, you are ready to create your own app and configure the connector using xref:twilio-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:connectors::introduction/intro-use-exchange.adoc[Use Exchange to Discover Connectors, Templates, and Examples]
* https://www.twilio.com/docs/api/rest[Twilio's REST APIs]
* https://help.mulesoft.com[MuleSoft Help Center]
