= Twilio Connector 4.0 Examples - Mule 4

In this example, a Mule app sends a message to a phone number and then redacts it. The example uses variables in place of the Twilio credentials and the phone number from which the SMS is sent.

== Preliminary steps

Follow these steps to use property placeholders for field values:

. Create a new Mule project in Studio.
. Add the following properties to a YAML or XML file:
+
[source,text,linenums]
----
config.accountSid=<Your account SID>
config.authToken=<Your authentication token>
config.fromNumber=<The phone number from which the SMS is sent, as configured inside the Twilio instance>
----
+
. Place the file in the project’s `src/main/resources` folder.
. Reference this file in the connector configuration, as described in xref:connectors::introduction/intro-connector-configuration-overview.adoc#property-placeholders[Use Property Placeholders for Property Values].

== Configure the Mule App

Follow these steps to configure the Mule app for this example:

. Drag the *HTTP Listener* operation to the Studio canvas and set its path to `/send/{toNumber}`.
. Drag a *Transform Message* component to the right of *Listener* and use DataWeave to prepare the input for the Twilio connector:
+
[source,dataweave,linenums]
----
%dw 2.0
output application/java
---
{
    Body: "You are now subscribed!",
    From: p('fromNumber'),
    To: "+" ++ attributes.uriParams.toNumber as String default "my default value"
}
----
+
. Drag the Twilio *Send Message* operation to the right of the *Transform Message* component and set the *Account Sid* field to `${accountSid}`.
. Drag a *Set Variable* component to the right of the *Transform Message* component and configure the following fields:
** Set the *Name* field to `messageSid`.
** Set the *Value* field to `#[payload.sid].
+
. Drag a *Transform Message* component to the right of *Set Variable* to create the input for the *Update Message* operation:
+
[source,dataweave,linenums]
----
%dw 2.0
output application/java
---
{
    Body: "",
    From: payload.from,
    To: payload.'to'
}
----
+
. Drag a Twilio *Update Message* operation to the right of the *Transform Message* component and configure the following fields:
** Set the *Account Sid* field to `${accountSid}`.
** Set the *Message Sid* field to `#[messageSid]`, which is the variable stored in step 5.
+
. Drag a *Transform Message* component to the right of *Redact Message* and set the output to `application/json`:
+
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
payload
----
+
. Run the application and point your browser to `+http://localhost:8081/send/{toNumber}+`, replacing the `toNumber` with the phone number obtained from Twilio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
