= Upgrade Twilio Connector to Version 4.x - Mule 4

Upgrade Anypoint Connector for Twilio (Twilio Connector) from version 3.x.x to version 4.x.x to take advantage of new functionality.

== Supported Upgrade Paths


[%header,cols="50a,50a"]
|===
|From Version | To Version
|3.x.x |4.x.x
|===

== Changes in This Release

 * The prefix for all the connector operations changed from *twilio-connector* to *twilio*.
 * The prefix *property_* was removed from Connector configuration. Before *property_username=*, *property_password=*. Now *username=*, *password=*.
 * The *Redact Message* operation name changed to *Update Message*.
 * The *Get Message List* operation name changed to *List Message Old* and new fields have been added (*Date Created<*, *Date Created>*, *Page Size*).
 * The *Get Media List* operation name changed to *List Media Old* and new fields have been added (*Date Sent<*, *Date Sent>*, *Page Size*).
 * The *Get Media* operation name changed to *Fetch Media*
 * The *Get Message* operation name changed to *Fetch Message*
 * The *Send Message* operation name changed to *Create Message*
 
 
== New Operations
 

 New operations for Twilio Connector 4.0.0 include:

[%header%autowidth.spread]
|===
|Twilio Operation | Description
|Create Account | Create a new Twilio Subaccount from the account making the request.
|Create address| Creates a new Address within your account.
|Create Application | Create a new application within your application. 
|Create Call | Create a new outgoing call to phones, SIP-enabled endpoints or Twilio Client connections.
|Delete Key | Deletes an API Key. This revokes its authorization to authenticate to the REST API and invalidates all Access Tokens generated using its secret.
|Delete Queue | Remove an empty queue.
|Delete Recording | Delete recording from your account.
|Fetch Balance | Fetch the balance for an Account based on Account Sid. Balance changes may not be reflected immediately. Child accounts do not contain balance information.
|Fetch Conference | Fetch an instance of a conference.
|Update Payments | Update an instance of payments with different phases of payment flows.
|Update Sip Credentials | Update a credential resource.
|===
 
 


== Upgrade Prerequisites

Before you perform the upgrade, you must:

* Create a backup of your files, data, and configurations in case you need to restore to them.


== Upgrade Steps

Follow these steps to perform the upgrade:

. In Anypoint Studio, create a Mule project.
. In the *Mule Palette* view, click *Search in Exchange*.
. In *Add Dependencies to Project*, enter `twilio` in the search field.
. In *Available modules*, select *Twilio Connector* and click *Add*.
. Click *Finish*.
. Verify that the Twilio Connector dependency version is 4.0.0 in the `pom.xml` file in the Mule project.

Studio upgrades the connector automatically.

== Post-Upgrade Steps

After you install the latest version of the connector, follow these steps to complete the upgrade:


=== Verify the Upgrade

After you install the latest version of the connector, follow these steps to verify the upgrade:

. In Studio, verify that there are no errors in the *Problems* or *Console* views.
. Verify that there are no problems in the project `pom.xml` file.
. Test the connection to verify that the operations work.

== Troubleshoot

If there are common known issues and errors that occur when upgrading, give troubleshooting tips.

=== Revert the Upgrade

If it is necessary to revert to the previous version of Twilio Connector, change the `4.0.0` dependency version in the project's `pom.xml` file to the previous version.

You must update the project's `pom.xml` file in Anypoint Studio.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:twilio-connector-reference.adoc[Box Connector Reference]
* https://help.mulesoft.com[MuleSoft Help Center]
