= ServiceNow - XML and Maven Support
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

If you manually code a Mule application in XML either from the Studio XML editor or another editor, to get access to a connector, you must:

. Add the namespace for the connector to your XML flow.
. Add dependency information to your Maven `pom.xml` file.

== Add a Namespace for the Connector

If you manually code the Mule application
in Studio's XML editor or another text editor, paste the following into the header of your configuration
XML, inside the `<mule>` tag:


[source,xml,linenums]
----
xsi:schemaLocation="
...
http://www.mulesoft.org/schema/mule/servicenow
http://www.mulesoft.org/schema/mule/servicenow/current/mule-servicenow.xsd"
----

Example of where to add these lines to your flow:

[source,xml,linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:connector="http://www.mulesoft.org/schema/mule/servicenow"
      xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core
               http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/servicenow
               http://www.mulesoft.org/schema/mule/servicenow/current/mule-servicenow.xsd">

      <!-- put your global configuration elements and flows here -->

</mule>
----

== Configure the Maven POM File

The `pom.xml` is a Maven file that Anypoint Studio generates that contains dependencies for a Mule app. When you code a Mule app manually, include this XML snippet in your `pom.xml` file to enable access to the ServiceNow connector. Mule translates the `LATEST` dependency keyword to the current version. You can use a version number instead.

[source,xml,linenums]
----
<dependency>
  <groupId>com.mulesoft.connectors</groupId>
  <artifactId>mule-servicenow-connector</artifactId>
  <version>LATEST</version>
  <classifier>mule-plugin</classifier>
</dependency>
----

== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
