= ServiceNow Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

ServiceNow Connector v6.2.2

The ServiceNow connector facilitates connections between Mule and ServiceNow apps. You can use the ServiceNow operations with the custom ServiceNow tables, along with any operations available through the installed plugins.

== About Connectors

Anypoint Connectors are extensions of Mule that let you work with external systems such as Salesforce, ServiceNow, Workday, Twitter, and more to send and receive information from these systems to create something new. Anypoint Connectors let you connect Mule applications to APIs and resources.

A connector lets you send and receive data over a protocol, or to and from an API. Use this information to work with Design Center or Anypoint Studio to adjust the UI settings to enable the connector to work with a Mule application.

== Prerequisites

Before starting, ensure you have the Mule Enterprise Edition and have access to the following:

* ServiceNow connector on Exchange
* Anypoint Platform
* Design Center
* Anypoint Studio

You should be familiar with ServiceNow and with creating a Mule application.

== Audience

* Starting user -- Read this Get Started document and create your Mule application in
 xref:servicenow/servicenow-connector-design-center.adoc[ServiceNow - Design Center] or xref:servicenow/servicenow-connector-studio.adoc[ServiceNow - Studio].
* Power user - Read the xref:servicenow/servicenow-connector-xml-maven.adoc[ServiceNow - XML and Maven Support] and xref:servicenow/servicenow-connector-examples.adoc[Examples].

The ServiceNow SOAP site provides a full list of actions for any version of the ServiceNow connector.

The xref:servicenow/servicenow-reference.adoc[ServiceNow Connector Technical Reference] provides details on the configuration options.

== Exchange Templates

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates to simplify your use of the ServiceNow connector. Templates provide a starting point that enables you to add additional functionality.

Exchange provides the following ServiceNow templates:

* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker-bidirectional-sync[Workday and ServiceNow Worker Bidirectional Sync]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-workerservicerequest-migration[Workday Worker to ServiceNow Service Request Migration]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-employee-aggregation[Workday and ServiceNow Employee Aggregation]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker-migration[Workday to ServiceNow Service Worker Migration]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker2servicerequest-broadcast[Workday Worker to ServiceNow Service Request Broadcast]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker2user-broadcast[Workday Worker to ServiceNow User Broadcast]

== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
