= ServiceNow Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/
:page-aliases: servicenow-about.adoc, servicenow-to-use.adoc

Support Category: Select 

ServiceNow Connector Version 6.3.0

The ServiceNow connector provides connections between Mule and ServiceNow apps.
Use the ServiceNow operations with the custom ServiceNow tables, along with any operations available through the installed plugins.

== About Connectors

Anypoint connectors are Mule runtime engine extensions that enable you to connect
to APIs and resources on external systems, such as Salesforce, ServiceNow, and Twitter.

== Prerequisites

Before creating an app, you must have access to the ServiceNow target resource and
Anypoint Platform. You also need to understand how to create a Mule app using
Design Center or Anypoint Studio.

== Audience

* Starting user -- To create your Mule app,
see xref:servicenow/servicenow-connector-design-center.adoc[Design Center Configuration]
or xref:servicenow/servicenow-connector-studio.adoc[Studio Configuration].
//The xref:servicenow/servicenow-connector-config-topics.adoc[Additional Configuration Information]
//topic helps extend your understanding of the ServiceNow connector.


* Power user - Read the xref:servicenow/servicenow-connector-xml-maven.adoc[XML and Maven Support]
//xref:servicenow/servicenow-connector-config-topics.adoc[Additional Configuration Information],
and xref:servicenow/servicenow-connector-examples.adoc[Examples] topics.
The Examples topic provides one or more use cases for using the connector.

== Common Use Cases For the Connector

With the ServiceNow connector, organizations can fully integrate business processes across HR, legal, procurement, operations, marketing, and facilities departments.
Creating connectivity within and outside the enterprise is quick and simple with connectivity to over 120 Anypoint connectors.

MuleSoft’s Anypoint ServiceNow connector allows businesses to create instant API connectivity with the ServiceNow API, allowing them to quickly and easily interface with ServiceNow from within the MuleSoft Anypoint Platform.


xref:servicenow/servicenow-connector-examples.adoc[Example] use cases includes getting a ServiceNow incident record.

== Learn Using Exchange Templates and Examples

https://www.mulesoft.com/exchange/[Anypoint Exchange] provides templates
you can use as a starting point for your app, as well as examples that illustrate a complete solution.

* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker-bidirectional-sync[Workday and ServiceNow Worker Bidirectional Sync]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-workerservicerequest-migration/[Workday Worker to ServiceNow Service Request Migration]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-employee-aggregation/[Workday and ServiceNow Employee Aggregation]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker-migration/[Workday to ServiceNow Service Worker Migration]
* https://anypoint.mulesoft.com/exchange/org.mule.templates/template-wday2snow-worker2servicerequest-broadcast/[Workday Worker to ServiceNow Service Request Broadcast]

== Next Step

After you have met the prerequisites and experimented with templates and examples, you are ready to create an app with
xref:servicenow/servicenow-connector-design-center.adoc[Design Center] or xref:servicenow/servicenow-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/?search=servicenow&type=connector[Anypoint Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]
