= ServiceNow Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/

Support Category: Select

ServiceNow Connector v6.2.0

The ServiceNow connector facilitates connections between Mule and ServiceNow apps. You can use the ServiceNow operations with the custom ServiceNow tables, along with any operations available through the installed plugins.

== Audience

* New user -- Read this document and configure your Mule application in the xref:servicenow/servicenow-connector-design-center.adoc[ServiceNow - Design Center].
* Current Mule user -- Read this document and configure your Mule application in the xref:servicenow/servicenow-connector-design-center.adoc[ServiceNow - Design Center] or xref:servicenow/servicenow-connector-studio.adoc[ServiceNow - Studio].
* Power user - Read the xref:servicenow/servicenow-connector-xml-maven.adoc[ServiceNow - XML and Maven Support], and xref:servicenow/servicenow-connector-use-cases.adoc[ServiceNow - Examples].

== Prerequisites

This document assumes that you are familiar with ServiceNow, HTTP, SOAP, REST, Bulk and Streaming APIs, Mule runtime engine (Mule), Anypoint Connectors, Anypoint Studio (Studio), Mule concepts, elements in a Mule flow, and Global Elements. *(Reviewers - do all of these prerequisites apply to the ServiceNow connector?)*

Requirements for using the connector:

* A ServiceNow account.

* Namespace and schema location: If you plan to create the XML for your Mule application, you need to include the correct namespace and schema location in your XML file. Anypoint Studio adds this information to the XML file automatically when you add the Salesforce connector to a flow in a Mule app.

If you are upgrading from a previous version of the connector through Anypoint Studio, click the *Updates Available* message.

== Develop an application

. Configure the connector.
. Test the connection.
. Build the rest of your flow.
. Add and configure DataWeave.

The ServiceNow SOAP site provides a full list of actions for any version of the ServiceNow connector.

// Should we be referting to the Reference instead of the SOAP API?

The xref:servicenow/servicenow-reference.adoc[ServiceNow Connector Technical Reference] provides details on the configuration options.

== Examples

* xref:servicenow/servicenow-connector-examples.adoc#example-incident-record[Get a ServiceNow Incident Record]
* xref:servicenow/servicenow-connector-examples.adoc#example-incident-table[Get Records from a ServiceNow Incident Table]
* xref:servicenow/servicenow-connector-examples.adoc#example-incident-table-keys[Get ServiceNow Incident Table Keys]

== See Also
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
