= Troubleshooting Cassandra Connector 

To troubleshoot Apache Cassandra (Apache Cassandra Connector), become familiar with the information about enabling verbose logging and interpreting commonly thrown messages.

== Enable Verbose Logging

To get a better understanding of why an application's interaction with Cassandra Connector is failing, temporarily enable verbose logging for the module.

Remember to always disable the enhanced verbosity after troubleshooting, because it affects your Mule application performance.

To enable verbose logging in the configuration file:

. Access Anypoint Studio and navigate to the *Package Explorer* view.
. Open your application's project name.
. Open the `src/main/resources` path folder.
. Open the `log4j2.xml` file inside the folder.
. Add an `<AsyncLogger>` tag inside the `<Loggers>` tag:
+
[source,xml,linenums]
----
			<Loggers>
				...
				<AsyncLogger name="com.mulesoft.connector.cassandradb" level="DEBUG"/>
				<AsyncLogger name="com.datastax.oss.driver" level="DEBUG"/>
				...
			</Loggers>
----
[start=6]
. Save your application changes.
. Click the project name in *Package Explorer* and then click *Run* > *Run As* > *Mule Application*.

== Troubleshoot Prepared Statements Cache Size

If you receive the following warning message when running your Mule application:

---
WARN com.datastax.oss.driver Re-preparing already prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once.
---

To avoid the previous message, increase the value of the xref:cassandra-connector-reference.adoc#config_connection[*Prepared Statements Cache Size*] field. Set a value with at least the number of different statements that you handle in your Mule application.

== See Also

* https://help.salesforce.com[Salesforce Help]
include::release-notes::partial$release-notes/rn-known-issues.adoc[tag=knownIssuesSeeAlsoLink]