= Hadoop (HDFS) Connector - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Select]

Hadoop (HDFS) Connector Version v6.0

Anypoint Connector for the Hadoop Distributed File System (HDFS) (Hadoop (HDFS) Connector) is used as a bidirectional gateway between Mule applications and HDFS. You can use this connector to poll the content of a file at a configurable rate or interval, or to manipulate data in an HDFS server.

For information about compatibility and fixed issues, see xref:release-notes::connector/hdfs-connector-release-notes-mule-4.adoc[Hadoop (HDFS) Connector Release Notes] 

== Prerequisites

To use this connector, you must be familiar with the following concepts:

* Anypoint connectors
* Mule runtime engine (Mule)
* Elements in a Mule flow
* Global elements
* How to create a Mule app using Design Center or Anypoint Studio

Before creating an app, you must have:

* Access to the Hadoop (HDFS) target resource and Anypoint Platform 
* Anypoint Studio version 7.0 or later 
* An instance of Hadoop Distributed File System running


== Audience

* Starting user
+
To create your Mule app, see:
** xref:hdfs/hdfs-connector-studio.adoc[Studio Configuration]
** xref:hdfs/hdfs-connector-examples.adoc[Examples], which has use cases for the connector
+
* Power user
+
Read the following topics: 
** xref:hdfs/hdfs-connector-xml-maven.adoc[XML and Maven Support]
** xref:hdfs/hdfs-connector-examples.adoc[Examples]  

== Connection Types

The following connection authentication types are supported:

* Kerberos 
* Simple


== Next Step

After you complete the prerequisites and experiment with templates and examples, you are ready to create an app with xref:hdfs/hdfs-connector-studio.adoc[Anypoint Studio].

== See Also

* xref:introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* xref:introduction/intro-config-use-fd.adoc[Use Flow Designer to Configure a Connector]
* https://www.mulesoft.com/exchange/?search=hdfs&type=connector[Hadoop (HDFS) Connector on Exchange]
* https://help.mulesoft.com[MuleSoft Help Center]
