= Hadoop (HDFS) Connector - XML and Maven Support - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you manually code a Mule app in XML, either from the Anypoint Studio XML editor 
or from a text editor, configure access to the connector in your app by adding 
reference statements to your XML Mule flow and in the Apache Maven POM file.

[NOTE]
====
You can avoid this manual process by using Anypoint Studio. When 
you add the connector in Studio, Studio automatically populates 
the XML code with the connector's namespace and schema location, and adds a 
dependency to the `pom.xml` file.
====

== Add a Namespace for the Connector

Paste the following code inside the `mule` tag of the header 
of your configuration XML:

[source,xml,linenums]
----
http://www.mulesoft.org/schema/mule/hdfs 
http://www.mulesoft.org/schema/mule/hdfs/current/mule-hdfs.xsd
----

This example shows how the namespace statements are placed in the XML: 

[source,xml,linenums]
----
<mule xmlns:hdfs="http://www.mulesoft.org/schema/mule/hdfs" 
	xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core 
	http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/hdfs 
	http://www.mulesoft.org/schema/mule/hdfs/current/mule-hdfs.xsd">
----


== Add a POM File Dependency 

The `pom.xml` Apache Maven file generated by Anypoint Studio contains dependencies 
for a Mule app. When you code a Mule app manually, include this XML snippet in 
your POM file to enable access to this connector:

[source,xml,linenums]
----
<dependency>
	<groupId>org.mule.connectors</groupId>
    <artifactId>mule-hdfs-connector</artifactId>
    <version>6.0.3</version>
    <classifier>mule-plugin</classifier>
</dependency>
----

Verify that the connector `version` corresponds to the one you are using. 

To obtain the most up-to-date `pom.xml` file information:

. Go to https://www.mulesoft.com/exchange/[Anypoint Exchange].
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for `HDFS`.
. Click *Dependency Snippets*.

== Next Step

After completing your namespace and `pom.xml` file, you can try 
the xref:hdfs/hdfs-connector-examples.adoc[Examples].

== See Also

https://help.mulesoft.com[MuleSoft Help Center]
