= Write a File Using the SFTP Connector - Mule 4
:page-aliases: connectors::sftp/sftp-write.adoc

A Write operation is available to the File, FTP, and SFTP connectors. For these connectors, the operation writes content into the given path on demand. It supports common use cases described below.

== Embedded DataWeave Transformations

By default, the connector writes whatever is in the message payload:

.Example: SFTP Connector
[source,xml]
----
<sftp:write path="output.csv" />
----

However, if the payload is a different format (for example, not CSV) and you need to transform it before writing it, what do you do? If you place a Transform component before the Write operation, the message payload changes and that impacts the operation that is placed after the Write operation.

To avoid this undesired impact, you can place the transformation inside the Write operation to generate content to be written without producing a side effect on the message in transit.

The next example uses the SFTP connector to write the content:

.Example: Transformation within an SFTP Write Operation
[source,xml,linenums]
----
<sftp:write path="output.csv">
  <sftp:content>#[%dw 2.0
                   output application/csv
                   ---
                   payload.customers.email
                  ]
  </sftp:content>
</sftp:write>
----

== Write into Directories

If any of the `a`, `b`, or `c` directories in the example below do not exist, the Write operation will fail by default. However, if you set the `createParentDirectories` to `true`, the connector will automatically create any missing directories.

.Example: SFTP Connector writes to a Directory
[source,xml]
----
<sftp:write path="a/b/c/myFile.txt" />
----

// INCLUDE FOR THESE SECTIONS:
// == Writing to Existing Files
// == Locks
include::partial$common-write.adoc[]

== See Also

xref:sftp-copy-move.adoc#createDirectory[Create a directory in SFTP]
