= SFTP Connector Examples - Mule 4

To fully benefit from using Anypoint Connector for SFTP (SFTP Connector), see the following examples of configuring the connector operations:

* xref:sftp-read.adoc[Read a File] +
Configure the *Read* operation to read a file at any point in the flow.
* xref:sftp-write.adoc[Write a File] +
Configure the *Write* operation to write content into the given path on demand.
* xref:sftp-list.adoc[List Files] +
Configure the *List* operation to list the files and folders in the configured directory path.
* xref:sftp-copy-move.adoc[Copy and Move Files] +
Configure the *Copy* and *Move* operations to copy or move files or directories on demand.
* xref:sftp-on-new-file.adoc[Trigger a Flow for a New Created or Updated File] +
Configure the *On New or Updated File* source to trigger a flow for a new created or modified file.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
